### ISSUE TITLE
How to get and configure the Tachiyomi extension with Komga?

### ISSUE THREAD

**Issue by phanirithvij** [gotson/komga#1]
So I did a `docker-compose up` with this docker-compose.yml

https://github.com/gotson/komga/blob/dba9d13c3dd6c324df1f4bc6af7b222439bde04f/doc/docker-compose.yml#L1-L20

And the server's running on my pc.

How do I connect it to the android app that's on my mobile? Can you provide an extension apk before the [PR](https://github.com/inorichi/tachiyomi-extensions/pull/1409) gets accepted?

**Comment by gotson** [comment]
Hello,

You have to configure the extension in Tachiyomi, and provide 3 parameters :

- the url of the server (without trailing /) 
- the login (here `user`)
- the password

And then restart Tachiyomi for preferences to be taken into account (you can kill the app). 

Here is a development build you can use :
https://www.dropbox.com/s/kisrf7z6gs2tfqb/tachiyomi-all.komga-v1.2.1-debug.apk?dl=0

Or you can build the APK from the PR if you don't want to install an unknown APK.

**Comment by phanirithvij** [comment]
1. How do I set a user name? I see `KOMGA_ADMIN_PASSWORD`, `KOMGA_USER_PASSWORD` but no username?
2. Where do I store the books in my pc (say a Windows one)?

In the example, you're mounting this path as /books right.
`/mnt/nas/media/Books/:/books`

I tried `D:\\Comics:/books` with a single CBR file in it but I still got

```
komga     | 2019-08-23 07:34:43.203  INFO 1 --- [           main] o.g.komga.domain.service.LibraryManager  : Parsing all books in status: unknown
```

**Comment by gotson** [comment]
> * How do I set a user name? I see `KOMGA_ADMIN_PASSWORD`, `KOMGA_USER_PASSWORD` but no username?

At the moment there are only 2 users: `admin` and `user`. The default password for each is the same as the login (so `admin` and `user`).

- `admin` can perform admin actions on the API, access the embedded database via the h2-console, and access the Spring Actuator endpoints
- `user` can only access series and books. That's the one you should configure in Tachiyomi: Komga.

> 2\. Where do I store the books in my pc (say a Windows one)?

I am running it on Ubuntu, so i am not sure how to mount local drives inside the container on Windows.

Basically the container expects the root folder of your library inside the container to be at `/books` (that's the `KOMGA_ROOT_FOLDER` parameter).

Then in the sample `docker-compose.yml`, this line maps a local folder within the container: 
```
/mnt/nas/media/Books/:/books
```

So `/mnt/nas/media/Books/` is a local folder on my Linux machine, and Docker mounts it inside the container at path `/books`.



> I tried `D:\\Comics:/books` with a single CBR file in it but I still got


You should look for this line of log instead:

```
2019-08-23 14:33:31.646  INFO 4116 --- [nTaskExecutor-1] o.g.komga.domain.service.LibraryManager  : Updating library: default, root folder: D:\Comics\
```

The line of log you are showing is normal. Komga starts by first getting all the files/folders under the root directory, then it will parse books that are not yet parsed (so subsequent scans only add/remove/update books).

**Comment by gotson** [comment]
I've added some details on how it works and how to configure it in the `README`. I could also provide an executable `jar` file if that could help you to run it on Windows!

**Comment by gotson** [comment]
@phanirithvij i am now distributing executable `jar` files from the [releases](https://github.com/gotson/komga/releases) tab. Maybe that can help you run it on Windows without having to mount drives.
