### ISSUE TITLE
Create User with no existing users

### ISSUE THREAD

**Issue by keinezeit8** [gotson/komga#100]
When starting Komga for the first time, it is clear to make a new account with personal credentials, and to delete the old one.

But when you delete the old one first there is no way to create a new account in the web view.
Maybe it should never be possible to delete every user.

**Comment by gotson** [comment]
Actually if you self-delete the only admin account, a new admin account will be created on application startup.

**Comment by keinezeit8** [comment]
But you still have to restart the Applikation.
I think, that just adding a plus to add a new account, even if all others have been deleted, would be good.

**Comment by gotson** [comment]
It's not possible, you can't do anything without valid credentials. The only way is to prevent self deletion.

My last comment was to explain there is a workaround.
