### ISSUE TITLE
auto update library

### ISSUE THREAD

**Issue by francecisco** [gotson/komga#1000]
### Describe your suggested feature

hello,
Nice work with Komga, I really appreciate
Maybe it might be good to have the choice to configure the automatic update for each library? Every day / week.
Because I have a folder that is automatically supplying with RSS broadcast / download lists.
If this option exists, I did not find it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can't set it per library, only for all libraries: https://komga.org/installation/configuration.html#komga-libraries-scan-cron-komga-libraries-scan-cron-cron

**Comment by francecisco** [comment]
Hello and thank you for the reply.
But I was thinking of thinking of something simpler for beginner users (like me) in the web interface in the same place where we can choose certain libraries parameters.
I will look at the information you have transmitted to me.

![Capture d’écran 2022-11-08 100615](https://user-images.githubusercontent.com/89357371/200522946-5dbcf29a-b6fc-45dc-b336-f269a41099d6.png)
