### ISSUE TITLE
Komga Not Starting or Showing Libraries

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#1001]
### Steps to reproduce

Start Komga as usual.

### Expected behavior

Komga should show libraries

### Actual behavior

Komga won't show any of the libraries.

### Logs

https://www.dropbox.com/t/2AOvQ3clHiS6aWVg

### Komga version

0.157.2

### Operating system

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can't find logs in your log zip 🤷🏻‍♂️

**Comment by gotson** [comment]
You have a lot of `java.sql.SQLTransientConnectionException: SqliteUdfPool - Connection is not available, request timed out after 30000ms.`

Maybe your disk with the DB going to sleep. What's your hardware setup?

**Comment by kanjieater** [comment]
Were there other logs I needed to include?

I'm using it locally, on the same network. 
- windows 10 PC 
- i7 4770k
- 2 GB of ram alotted for Komga,  `-jar -Xmx2g`, 32GB system total,
- Library & Komga server is on: HGST Ultrastar 7K4000 4TB 64MB Cache 7200RPM SATA 6.0Gb/s 3.5inch Internal Hard Drive

It seems like when a scan happens the server becomes slower/unresponsive. I can try moving the server to an SSD, to see if HDD library scans are slowing it down, but I don't really have any ideas beyond that.
