### ISSUE TITLE
"Artists" Field in "Authors"

### ISSUE THREAD

**Issue by Zombanana** [gotson/komga#1004]
### Describe your suggested feature

Hi,

Komga is able to manage authors metadata.
There are fields for "Pencillers" and "Inkers".
My Suggestion is to add an additional field for "Artists" above the Pencillers/Inkers fields.

In many collected editions pencillers/inkers are just credited as "Artists".
So you have allways the problem to identify the role of the artist: is the artist a penciller, inker, or both.
I don't want the hassle to identify the role. I just want a field for "Artists".

At the moment, I am using a workaround, making "Custom Fields".
But this method feels like a quick an dirty solution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can already add new roles as you see fit.

**Comment by Zombanana** [comment]
Hi gotson,

yes you are right, but this brings another stupid situation: 
https://github.com/gotson/komga/issues/1005
