### ISSUE TITLE
Add X-Robots-Tag header

### ISSUE THREAD

**Issue by robsonsobral** [gotson/komga#1006]
### Describe your suggested feature

Hi!

Could you, please, add `X-Robots-Tag: noindex, nofollow` to the response headers?

### Other details

The [`X-Robots-Tag`](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag) would help protect Komga serves from being discovered online.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by darthmooguy** [comment]
You can add that header using a reverse proxy, it doesn't necessarily need to be in Komga's headers. Plus, if you are exposing your instance to the internet, you are probably already (or should be) using a reverse proxy!

**Comment by robsonsobral** [comment]
> ...you are probably already (or should be) using a reverse proxy!

Actually, I'm using a CloudFlare tunnel.

**Comment by darthmooguy** [comment]
2 things to note: 1st using Cloudflare Argo tunnels for services like Komga or Jellyfin (aka mostly media files, vs a mostly html website) is against their TOS, so use it at your own risk.

2nd, you could still set up a reverse proxy to add the header, and expose the reverse proxy with Cloudflare Argo tunnels instead! That way you still get the feature you want right away, and if gotson adds the feature to Komga then you can get rid of the reverse proxy.

**Comment by gotson** [comment]
I don't think this should be in Komga. Some people may want to have their instance discoverable, who knows ?

Is that a thing generally done on other selfhosted software like Sonarr/Radarr etc ?
