### ISSUE TITLE
Global Library settings

### ISSUE THREAD

**Issue by cloudycloud47** [gotson/komga#1007]
### Describe your suggested feature

I'd like to be able to set Global library settings which would affect all libraries at once.

Settings could be over-ridden at each library level but if/when new settings are added, it would be useful to make one change instead of making multiple changes for each library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
What kind of settings ? Seems like an edge case. Can you explain more in details ?
