### ISSUE TITLE
Use year as volume from series.json when volume is null or greater than 1

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#1009]
### Describe your suggested feature

When we have a series.json with"volume": nulll or"volume": 1 there is no volume in komga set.
All numbers > 1 in volume use year from series.json

when there is a year in series.json it should always used as volume ignoring null, 1 or >1.

Motivation:
I whish this to handle better reading lists.
At the moment all reading lists with volume didn't find a match in komga when we have a series.json with volume : 1 or zero but with a correct year.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
i don't understand, can you clarify what's the link between this and reading lists ?

**Comment by gotson** [comment]
The series title computation for Mylar's `series.json` is in line with the one for `ComicInfo.xml`.

- `series.json`:
  - if `volume` is `null` or `1` => title = `name`
  - else => title = `name (year)`
- `ComicInfo.xml`:
  - if `volume` is `null` or `1` => title = `series`
  - else => title = `series (volume)`

**Comment by MKH-42** [comment]
My wish is to have:
series.json:
title = name (year)

instead of 
    if volume is null or 1 => title = name
    else => title = name (year)

reason: when there is a year, than it should always used as volume.
komga uses volumes as years and should ignores volume informations from series.json.
mylar3 fill out year information correctly, volume is an optional setting.


so the if branche has no helpfull effect.
when year is set, you can use it. when year is not set, we have the same effect as (volume is null or 1).
the main information is year, not volume in series.json.

**Comment by gotson** [comment]
There is no need to add the year if there is no volume. The volume/year is added to differentiate series with the same name.

**Comment by MKH-42** [comment]
This will not work in the reality.
When in series.json volume is set 1 than the year is not set right and so the reading lists doesn't find a match.
Workaround at the moment is to replace all properties in series.json with >"volume": null,< or >"volume": 1<, with >"volume": 999,<.
Problem here: After a refresh from mylar3 this setting is gone.

I add 2 test directories to clarify my test setup:
Series A: with volume : 1
![grafik](https://user-images.githubusercontent.com/76835223/204057050-c8fcdf3d-5b5d-4f26-b7ec-865a108c0773.png)


Series B: with volume : 999:![grafik](https://user-images.githubusercontent.com/76835223/204057361-c3f5cf26-95e8-4c99-93a4-371eae24a87d.png)

For better reproducing I created a test szanario:
[TestImportVolume.zip](https://github.com/gotson/komga/files/10095149/TestImportVolume.zip)

One solution could be to ignore the volume value and always use the year.

**Comment by gotson** [comment]
That's an XY problem, you are trying to solve readlist matching by tweaking metadata in the way you think it would work. That's not the right way of fixing this.

And there is already #776

**Comment by MKH-42** [comment]
> That's an XY problem, you are trying to solve readlist matching by tweaking metadata in the way you think it would work. That's not the right way of fixing this.
> 
> And there is already #776

#776 and #1009 are complete different requests.
#776 want to have year from a cbl as a matching criteria. #1009 wants volume as matching critera. 

#1009 shows that the volume is not used when in series.json volume is set to 1 or null and an existing year is ignoring. komga useses already year as volume in all other situations.

**Comment by MKH-42** [comment]
For everybody have the same problem to import reading lists (no matche for series found) and uses mylar3 to write a series.json:
you have to replace >"volume": 1,< or >"volume": null,< with >volume: 999,< (without the ><).

best way to do this is to mass replace with a tool like notepad++

this will fix:
a) volume is shown in komga 
b) reading list importer will find a match
