### ISSUE TITLE
Reading List Import Result Export

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#1010]
### Describe your suggested feature

After Importing a Reading List (CBL) there is a result view in Komga.
This result view is a one timer and at the moment no known solution to show again the result.

It would be nice to have a possibility to export this result for manage the result also later.

### Other details

The export could be a normal text file or a csv file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand what you mean, or what you want to do, can you clarify ?

**Comment by MKH-42** [comment]
When you import a reading list than it could be you have importing errors.
![grafik](https://user-images.githubusercontent.com/76835223/203791615-5d860f44-2196-45c6-bde7-c62cf1a9ab04.png)

At the moment there is no possibility to store this result.
When you want to fix the reading list OR the metadata in Komga you have to navigate to the series to compare the error with the series data.
But when you navigate to a series you lose your import result.

So it would be nice to have a possibility to store this information e.g. with an export function or with a history view.
Export to csv / plain text would be enough in the first step.

**Comment by gotson** [comment]
Open a second tab (i know you do already).
