### ISSUE TITLE
Show Exact Page of Progress for Books in Progress

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#1012]
### Describe your suggested feature

If you want to quickly glance at what the exact page you are on you have to open the book. I was hoping it could be displayed on the book page. So in this image, it could display 117/152 pages or something to that effect.

![image](https://user-images.githubusercontent.com/32607317/204164924-1c9bffc5-b772-4156-8ebb-73baab0312fa.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
why would you want to have that level of precision ?

**Comment by kanjieater** [comment]
Sure, a few reasons I have:
- Curiosity
- To check how many more pages I have left read - I can read x amount in y amount of time, and can schedule appropriately. Is it 10, 50 or 150 pages left
- Stat tracking of pages read outside of komga

**Comment by gotson** [comment]
> * Stat tracking of pages read outside of komga

Can you expand on that ? I don't understand what that means in this context.

**Comment by kanjieater** [comment]
I track how many pages I've read outside of komga in a spreadsheet.  If I can quickly glance at the number without having to open and wait for it to load, it just makes getting that number faster.

**Comment by gotson** [comment]
> I track how many pages I've read outside of komga in a spreadsheet. If I can quickly glance at the number without having to open and wait for it to load, it just makes getting that number faster.

that seems… like a very weird use case.

**Comment by kanjieater** [comment]
If it doesnt make sense to show what page number you are on for a book, that's fine, i just thought it would be helpful. If its too much work or feels like bloat feel free to close this.
