### ISSUE TITLE
Better Mobile support (PWA)

### ISSUE THREAD

**Issue by quincarter** [gotson/komga#1014]
### PWA support, Caching, and Login on multiple devices 

Hi there. First off, great app. Love it and love what you've done. I use this on a multitude of devices. I've noticed a few things that could be improved in the overall user experience when shifting between devices. 

## Official PWA support 
- if you're able to execute this, then the rest of the features I'm going to ask for will be much easier
    - give users an install button in Chrome to Install it on their home screen 
    - implementation of a service worker and metadata to allow for the recognized PWA support by chrome and other browsers

## Offline Data
- currently when I install this on my home screen, I don't have offline support with my data. Even my local state is not stored so it has to go out to the internet and request data each time. If some kind of local storage or session storage was implemented, or indexdb then I could install this on my home screen and access everything that was loaded prior to going offline. This would also eliminate a lot of API calls and make the app appear to run a little faster
- probably the easiest way to do this would be to utilize some sort of State Management where it will fetch from the store first, and then you can just subscribe to changes on that store. But then if you have data already, it will be loaded from the store and then if it is updated then it will repopulate that value within the variable
### Download book
- I tried this for the first time recently with a comic book and it downloaded every image from the cbz file instead of keeping it inside of my komga reader. If the above is implemented, somehow we could store the downloaded book in local storage? Or somehow keep it in the database locally. This is just an idea

## login caching
- when I run this on my phone or my tablet, I have to login every time I open the site. It doesn't save my session if I close the tab. This may be a bug more than a feature, but I thought I would mention it here. It kind of coincides with the other features that I've presented  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
PWA was talked many times on Discord, and is most likely never gonna be done. The main reasons being:
- storage constraints for offline (see [here](https://stackoverflow.com/a/58594013/2041863)), which basically render this useless for the purpose of downloading books for offline viewing
- the fact that it's not really supported on all browsers

---

Now about some of the things you mentioned in your post:

> * give users an install button in Chrome to Install it on their home screen

You can already install the app on the home screen both on iOS and Android


> * implementation of a service worker and metadata to allow for the recognized PWA support by chrome and other browsers

To what end ? What would that accomplish ?

> * currently when I install this on my home screen, I don't have offline support with my data. Even my local state is not stored so it has to go out to the internet and request data each time. If some kind of local storage or session storage was implemented, or indexdb then I could install this on my home screen and access everything that was loaded prior to going offline. This would also eliminate a lot of API calls and make the app appear to run a little faster

What data would you want to store ? What is this "local state" you refer to ? And more importantly, to what end ? What is the actual use case here ? Browsing stale data while offline ? For what reason would you want to do that ?



> * I tried this for the first time recently with a comic book and it downloaded every image from the cbz file instead of keeping it inside of my komga reader. If the above is implemented, somehow we could store the downloaded book in local storage? Or somehow keep it in the database locally. This is just an idea

What did you try ? When you hit the download button it will give you the original file for download, so a cbz/cbr/pdf/epub. Local storage has limitation in terms of size, you would quickly reach the limit anyway.

> * when I run this on my phone or my tablet, I have to login every time I open the site. It doesn't save my session if I close the tab. This may be a bug more than a feature, but I thought I would mention it here. It kind of coincides with the other features that I've presented

Try to set [Remember Me](https://komga.org/installation/configuration.html#komga-rememberme-key-komga-remember-me-key-key).

**Comment by quincarter** [comment]
Hey thanks for responding. I didn't know there was a discord. I'd love to be part of that community. 

Also didn't know about the remember me feature - I didn't see a checkbox on the login screen which is where I'd expect it. I'll implement this right now. 

As far as a the install button and PWA support, it could be expanded on more. I would have appreciated a little more conversation before just closing my issue or dismissing it, I may bring something else to the table that hasn't been discussed before. To that end, I just joined the discord so we can chat there if it is easier.
