### ISSUE TITLE
Add documentation for using JPEG XL with Java 19

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#1015]
### Describe your suggested feature

This issue is related to the closed issue #982 from @unfinishedh. From what I can tell, all you have to do to use JPEG XL with Java 19 instead of Java 18 is to replace `--add-modules jdk.incubator.foreign` with `--enable-preview`.

**Logs**
> **org.gotson.komga.ApplicationKt:** Starting ApplicationKt using Java 19.0.1
> **c.g.g.n.j.i.plugins.JxlImageReaderSpi:** Loaded libjxl v0.7.0
> **o.g.k.i.image.ImageConverter:** Supported read formats: [ ... jxl ... ]
> **o.g.k.i.image.ImageConverter:** Supported read mediaTypes: [ ... image/jxl ... ]

The reason why I upgraded to Java 19 to begin with is because I saw this message in my Komga logs today:

> **org.gotson.komga.ApplicationKt:** Starting ApplicationKt using Java 18.0.2.1
> **c.g.g.n.j.i.plugins.JxlImageReaderSpi:** This plugin only supports Java 19, plugin will be disabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by whalehub** [comment]
Just discovered that the [documentation for the plugin](https://github.com/gotson/NightMonkeys#how-it-works) contains that info.

**Comment by gotson** [comment]
As explained in the FAQ: https://komga.org/faq/#how-to-enable-support-for-jpeg-xl :)
