### ISSUE TITLE
Manga details and hide volumes number option

### ISSUE THREAD

**Issue by IzeroCs** [gotson/komga#1018]
### Describe your suggested feature

I hope to be able to add the file book-title/info.json so I don't have to go to webui edit title, summany,... manually.

I hope you can add the unknown option before the chapter "1-Chapter 1", "2-Chapter 2",...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> I hope you can add the unknown option before the chapter "1-Chapter 1", "2-Chapter 2",...

already raised in #746, we won't be doing that.



> I hope to be able to add the file book-title/info.json so I don't have to go to webui edit title, summany,... manually.

what does that mean ?

**Comment by IzeroCs** [comment]
> > I hope you can add the unknown option before the chapter "1-Chapter 1", "2-Chapter 2",...
> 
> already raised in #746, we won't be doing that.
> 
> > I hope to be able to add the file book-title/info.json so I don't have to go to webui edit title, summany,... manually.
> 
> what does that mean ?

Manga-Title
  - Chapter 1
  - Chapter 2
  - Chapter n
  - info.json

Is it possible to specify data like title, summany,... from info.json file instead of editing in webui of komga. Instead of the name displayed in the scan as Manga-Title, if the title in info.json is: "One Piece", we get that title displayed. It can be considered the metadata of that manga that is not a chapter.

And the part number that comes before the "1-Chapter" chapter I don't understand why you wouldn't want to do that problem. It is agreed that I can set the Number field to "Vol.1" and the Title to "Ch.1" to obtain the result "Vol.1 - Ch.1", but for manga that I do not know the Vol number it is "1 - Ch.1".

I have found out the above problems whether there is a solution to ask you, however the issue standing before the chapter you did not do then info.json I think you will also not do.

**Comment by gotson** [comment]
What is `info.json` ?
