### ISSUE TITLE
Having option to control x-frame-option

### ISSUE THREAD

**Issue by DuvelCorp** [gotson/komga#1022]
### Describe your suggested feature

Actually in the header, it is set to 
`X-Frame-Options: SAMEORIGIN`

I am using organizr for my myriad of services being accessible from the web, and they all have their own subdomain.
I'd like to be able to define custom header like
ALLOW-FROM=mysubdomain.mydomain.com

My reverse proxy (apache) is on another server controlling everything and I cant tweak that there, it has to be done in my Komga container's proxy. So it would be nice to have an option for this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand your problem.

**Comment by gotson** [comment]
> I'd like to be able to define custom header like
> ALLOW-FROM=mysubdomain.mydomain.com

This is deprecated and not supported in modern browsers. 

> My reverse proxy (apache) is on another server controlling everything and I cant tweak that there

Why? A reverse proxy should allow to tweak headers, you could remove the header.

**Comment by plumber-craic** [comment]
this would have been a nice to have. After updating from 154 to 160 komga can only open in a new window instead of as an iframe. Still, splitting hairs. Komga still awesome.
