### ISSUE TITLE
No webreader settings or progess bar visible

### ISSUE THREAD

**Issue by CrimsonFlash** [gotson/komga#1026]
### Steps to reproduce

1. Open up any file.
2. Webreader settings/progress bar not visible 

### Expected behavior

Expect to see progress bar and other settings in the webreader as shown here: https://komga.org/guides/webreader.html

### Actual behavior

No settings or progress bar visible when hovering over page or moving mouse to top/bottom of viewport.

![Screen Shot 2022-12-24 at 9 43 57 AM](https://user-images.githubusercontent.com/25064322/209441103-efb610fb-9fc7-42b9-9548-c1daddc2828a.png)

### Komga version

v0.157.5-master

### Operating system

Windows Server 2019

### Other details

Running the jar version as a windows service. Files are in PDF or CBZ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Kussie** [comment]
You need to click the mouse, they dont show on hover
