### ISSUE TITLE
Filter: Selecting Multiple Genres Does not Behave as Expected

### ISSUE THREAD

**Issue by ispaure** [gotson/komga#1032]
### Steps to reproduce

1. Browse a library
2. Click on Filter Button in Upper-Right
3. Select Two or More Different Genres

### Expected behavior

You would expect having multiple genres selected to narrow down the filtered choices to only the series matching each of the genres.

### Actual behavior

The filtered list shows each serie which has at least one of the genres selected (thus, adding more genres usually adds more to the selection instead of reducing it / filtering it more).

### Komga version

0.157.5

### Operating system

Windows 10 + macOS Ventura 13.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by ispaure** [comment]
Note: Seems similar to [https://github.com/gotson/komga/issues/887]

**Comment by Shakahron** [comment]
If this won't be changed I really wish it could be a toggle or something. The full text search isn't that useful when you have over a hundred tags.
