### ISSUE TITLE
Browse page lacks "Recently Added Books" filter items

### ISSUE THREAD

**Issue by ORO44** [gotson/komga#1033]
### Describe your suggested feature

1. date added: Only for Recently Added authors, not Recently Added books
2. date update: Only for Recently Added authors and Recently Added or modified tags

So if you import a lot of new books(The authors of these books already exist), there is no suitable filter. Only the Recently Added Books section of the recommended page.

thanks

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you explain with screenshots ? I don't understand what's missing.

**Comment by ORO44** [comment]
> 
![image](https://user-images.githubusercontent.com/17335291/210197628-cf244b55-994e-4464-b942-f2e1adf286b6.png)
exist:
./[author_existed]/books 1,books 2

add:
./[author_existed]/books 3,books 4,

These two filter items cannot be filtered out books 3,books 4 (BROWSE→filtered: date added, date updated)
Can only filter out:
./[author_new1]/books 1,books 2,

i want:
./[author_existed]/books 3,books 4,

**Comment by gotson** [comment]
I don't get it. What you highlighted on the screenshot are sort options, they don't filter anything.

I don't understand also why you mention authors.

**Comment by gotson** [comment]
I'm sorry but I can't understand anything you're saying. Unless you manage to explain clearly what you think the problem is, I will close those issue.
