### ISSUE TITLE
Allow creating custom fields like "Rating" or "Alternative title"

### ISSUE THREAD

**Issue by DonZumito** [gotson/komga#1034]
### Describe your suggested feature

I would like it to be possible to create custom fields to add things like Alternative Titles (for romaji or title translations into another languages), Rating, or "difficulty level" (I find this last one useful for language learners, for example).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There won't be custom fields. Use tags if you need flexibility.

**Comment by DonZumito** [comment]
That's a bit of a shame... Anyway, do you have any suggestion on how can I set an alt or romaji title for a book or series using tags?
Thanks!

**Comment by gotson** [comment]
There's already #58 and #878
