### ISSUE TITLE
你好,老外!这些封面丑暴了.怎么办?

### ISSUE THREAD

**Issue by 277383761** [gotson/komga#1035]
### Describe your suggested feature

![image](https://user-images.githubusercontent.com/49450669/210694062-b4b878bf-3d93-4451-9b48-78cd24b12de9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please write in english and add a description
