### ISSUE TITLE
[Feature Request] Automatically create admin user at first login

### ISSUE THREAD

**Issue by himura95** [gotson/komga#104]
First, thanks for this awsome project and sorry for my bad english.

### Is your feature request related to a problem? Please describe.
I would like to replace my Ubooquity server by Komga server in Dietpi and I try to help the implementation.
The goal of Dietpi is "to quickly and easily install popular software that's "Ready to run" and optimised for your system"
But today the users who install komga via the dietpi interface can't login at first startup without open Komga logs :(

For information, I open a issue in dietpi because it would be really nice to see an foss alternative to Ubooquity in Dietpi : https://github.com/MichaIng/DietPi/issues/3403

### Describe the solution you'd like
It would be great if the first login (at the first launch) automatically create the admin account.
With this, the user can "quickly and easily install Komga that's "Ready to run" and optimised for his system"

**Comment by gotson** [comment]
How would address this exactly? The user is already created at first run. A fixed password is not secure, so that's out of question. 

On top of that there are a few other configuration keys that are required to set, so just running it without config will not be a thing. And I would say that if one has config access, one has log access to. 

I don't know about DietPi, but installing stuff quickly and easily is already done by using Docker images.

**Comment by himura95** [comment]
I ddo not talk about a fixed password.

What I would say is at startup the user is in the login screen and what he write in login and password create the admin user.(Only the first attempt at first launch)

A default application.yml would be create by dietpi for define port and maybe other stuff.

I do not know well docker, maybe the dietpi team can use it.

**Comment by muchtea** [comment]
Maybe give the option to set some optional environment variable or file containing the admin password on first startup of Komga. If the variable is used, then overwrite the randomly created password (and maybe don't show the specified new password in the log).

That works for many applications, and it should be save enough, since presumably the one setting the env-variable would be the same person who would currently read the password from the log file.

**Comment by gotson** [comment]
That would still require configuration, which is not compatible with the OP's requirement.

I am thinking I could add a new profile that would, when enabled :
- disable initial user creation
- expose an unprotected API endpoint which would accept a user email and password, and create an admin account, but only if no other user exists

This would be reachable by Swagger at first, so no need to develop another part of the front-end for that (at least for now). 

I think it would match the OP's requirements. The DietPi default configuration could enable this profile by default. 

@himura95 would that work for you?

**Comment by himura95** [comment]
If I understand we could launch like this ? : java -jar Komga.jar --user=mail@address.com --password=ThePassword
And It will create admin user only if no user exists ?

I think it's a good solution, I will test as soon as possible and give you feedback.

**Comment by gotson** [comment]
> If I understand we could launch like this ? : java -jar Komga.jar --user=[mail@address.com](mailto:mail@address.com) --password=ThePassword
> And It will create admin user only if no user exists ?
> 
> I think it's a good solution, I will test as soon as possible and give you feedback.

Not really.

- You would add a profile `claim` in the `application.yml` (it would be done by default by DietPi packaging).
- You would start the application as usual (whatever how it is done in DietPi)
- You would navigate to http://localhost:8080/swagger-ui.html
- On the Swagger page, you would have a section where you can input an email/password, and a button to validate. That would create the user.
- You would then navigate to http://localhost:8080 and use the email/password you created just before.

**Comment by himura95** [comment]
Thanks, it seem perfect for integrate to Dietpi :)

**Comment by gotson** [comment]
Done, i'll need to add some documentation with screenshots on the website.

**Comment by gotson** [comment]
> Done, i'll need to add some documentation with screenshots on the website.

Done in https://github.com/gotson/komga-website/commit/f050e2657960945985a44a85a45593b76931c10c
