### ISSUE TITLE
Collections - Back Button Issue

### ISSUE THREAD

**Issue by gardn701** [gotson/komga#1042]
### Describe your suggested feature

If you go into a collection and see all the books from the various libraries you have collected there and then click into the series to view the issues and read, the Komga back button or "Go to library" button in the top left returns the user to the parent directory of the series you were inside instead of returning the user to the Collection they were viewing from.   This back button should return the user to the collection they entered the series from.

This is annoying for me, since I read all my titles from a Collection I made for "want to read", but then every time I read a single new issue, I have to go through multiple clicks to reopen the collection from the sidebar instead of the back button simply taking me where I want to be.  This seems like an oversight rather than by design.  Fixing would be a huge quality of life upgrade.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> This back button should return the user to the collection they entered the series from.

No, that's not this button's role.

---

You should use your browser's back button.

**Comment by gotson** [comment]
Actually i realized i already implemented something similar for read lists, should be doable for collections too.

**Comment by gardn701** [comment]
> > This back button should return the user to the collection they entered the series from.
> 
> No, that's not this button's role.
> 
> You should use your browser's back button.

While that does work on a pc, it does not while I'm using komga as a webapp on an ipad.  In that mode you do not have access to browser buttons.

**Comment by gotson** [comment]
> While that does work on a pc, it does not while I'm using komga as a webapp on an ipad. In that mode you do not have access to browser buttons.

iPad design flaw 🙃
