### ISSUE TITLE
add cache control headers

### ISSUE THREAD

**Issue by xtra-be** [gotson/komga#1046]
### Describe your suggested feature

looks like komga is marking all pages as not to cache
I run my instance behind cloud flare and would like to leverage cloud flare cache to speed up delivery of the pages
or nginx or any other reverse proxy

however I noticed following header:
Cache-Control: max-age=0, must-revalidate, no-transform, private, max-age=0, must-revalidate, no-transform, private

it would be nice if komga allows images to be cached

preferably the /books/ endpoint is allowed to be cached

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Everything is cached, check network tools and you will see 304 answers.
