### ISSUE TITLE
Series level tag or author filter duplicate results

### ISSUE THREAD

**Issue by Shakahron** [gotson/komga#1052]
### Steps to reproduce

At series level, filter more than 1 tag that exist for a book.

### Expected behavior

Only 1 version of a book should appear if filtering multiple tags.

### Actual behavior

The more tags selected that a book has, the more duplicates appear.

### Komga version

0.160.0

### Operating system

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please provide screenshots.

**Comment by Shakahron** [comment]
Sure. Here you go

![firefox_oO6n8ZIcPb](https://user-images.githubusercontent.com/106402227/213734548-331272dd-311f-4c9f-b0a2-c0f9792f75f3.png)

**Comment by gotson** [comment]
It also happens with authors.
