### ISSUE TITLE
NPE in OIDC Authentication Flow with no `email_verified` Claim

### ISSUE THREAD

**Issue by dwmunster** [gotson/komga#1054]
### Steps to reproduce

1. Configure Komga to utilize [Azure AD](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens) as an OpenID Connect provider.
2. Attempt to log in via OIDC.

### Expected behavior

User should be logged in.

### Actual behavior

Whitelabel Error Page is displayed with, e.g.,
```
Mon Jan 23 00:38:47 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).
No message available
```

### Logs

```
java.lang.NullPointerException: null
	at org.gotson.komga.infrastructure.security.oauth2.KomgaOAuth2UserServiceConfiguration.oidcUserService$lambda$1(KomgaOAuth2UserServiceConfiguration.kt:59)
        ...
```

Full log available: [Pastebin](https://pastebin.com/mkKsMfSu)

### Komga version

0.160.0

### Operating system

Docker

### Other details

The stack trace seems to refer to the [following line](https://github.com/gotson/komga/blob/781d839702d4f3b337228c36de6ccf53c26eea5b/komga/src/main/kotlin/org/gotson/komga/infrastructure/security/oauth2/KomgaOAuth2UserServiceConfiguration.kt#L59):
```kotlin
if (!oidcUser.emailVerified) throw OAuth2AuthenticationException("ERR_1026")
```

I believe the cause is that the ID and access tokens for Azure AD do not include any variant of `email_verified` in their claims.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
NPE should not happen indeed, a condition must be added to verify that it's not null. `email_verified` is a standard OIDC claim so it should be present, you may need to check elsewhere if you configured Azure AD properly to return that claim.

**Comment by dwmunster** [comment]
While `email_verified` may be common to many OIDC providers, it is not part of the [spec](https://openid.net/specs/openid-connect-core-1_0.html#IDToken). Browsing similar issues in other libraries, ([example](https://github.com/dexidp/dex/issues/1405)), it would appear that azure ad is not the only provider that does not include this field.

Under their model, the `email` claim will only return verified emails, rendering an `email_verified` claim redundant.

**Comment by gotson** [comment]
It's in your link under section 5.1 though. I guess an option to skip verification could solve this.

**Comment by dwmunster** [comment]
Section 5.1 merely defines the claim key and value. That said, 5.4 (which defines some OpenID scopes) defines the `email` scope as requesting both of the `email` and `email_verified` claims. So spec compliance depends on if you interpret that as requiring a response to those claim requests or not. A bit moot, in any case, since we do not control AAD.

In theory, it might be possible to just add that claim with a value of "true" to all tokens for this application. But an option to skip that validation would be greatly appreciated.
