### ISSUE TITLE
Failed to parse opds catalog when trying to connect to koreader

### ISSUE THREAD

**Issue by klundry** [gotson/komga#1055]
### Steps to reproduce

Komga is installed and the web interface is working. If I put the opds catalog url in my browser I get the XML page.  But when I put the exact same URL in koreader I get the message "Failed to parse the catalog."

### Expected behavior

The OPDS catalog to show up when accessing it with koreader.

### Actual behavior

Failed to parse the catalog error message.

### Komga version

0.160.0

### Operating system

Arbmian/Yunohost

### Other details

However, the demo komga server works fine with koreader. So I'm not sure why my selfhosted komga install wont' work. I am using yunohost to install komga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You might need to report this to the Koreader folks and understand what's the problem on their end.

**Comment by klundry** [comment]
Ok, thanks. You can close this if you want and I'll comment again if I figure anything out.
