### ISSUE TITLE
Can't delete from search results page selection bar

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#1056]
### Steps to reproduce

1. Search.
2. Mark some series or books.
3. Hit delete.

### Expected behavior

It should delete the books or series.

### Actual behavior

Doesn't do anything.

### Komga version

0.160.0

### Operating system

Android 12 and Windows 11

### Other details

This may be a feature and not a bug. But I wanted to verify. I've been trying to use search to find titles that have material I want nothing to do with since I've recently imported over 7k manga. If this behavior is by design, then just let me know and the reason for it, and I'll move on :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Deletion only happens on the file system, in the UI the books will be marked as _Unavailable_. Can you also check logs?

**Comment by billsargent** [comment]
I tail the logs. Nothing shows up when you click the delete button.... I'm talking the button, not the 3 dots on each individual item. That works. But if you select more than one and hit the delete button, nothing happens. So there's no entry in the logs.

**Comment by billsargent** [comment]
![image](https://user-images.githubusercontent.com/32219940/214837024-5b8aae18-bf46-43c0-a870-9c167c9b8f81.png)
The word delete comes out next to the button but nothing is sent back to Komga to handle.

**Comment by billsargent** [comment]
![image](https://user-images.githubusercontent.com/32219940/214883669-5d04342d-ef38-4f4f-b601-dc153f6fdbf2.png)
This is it. I can click that delete button all day and nothing in this changes.

**Comment by billsargent** [comment]
Search has stopped working now. When I search for anything, it drops down the list of results, but when i hit enter, or click the "Search all..." from the drop down, nothing happens. So this prevents me from even getting to the point where I could test your fix here.

**Comment by gotson** [comment]
> Search has stopped working now. When I search for anything, it drops down the list of results, but when i hit enter, or click the "Search all..." from the drop down, nothing happens. So this prevents me from even getting to the point where I could test your fix here.

Open a new issue
