### ISSUE TITLE
Sort Number "0" not possible in bulk edit dialogue

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1057]
### Steps to reproduce

1. Select multiple books in a series, where one of the sort numbers is "0"
2. Open "Bulk edit metadata"
3. Try to save while sort number is "0"

### Expected behavior

Sort number is saved as "0" and the edit dialogue is closed

### Actual behavior

Sort number "0" is rejeected with the error message "required".
![grafik](https://user-images.githubusercontent.com/56667539/215122790-ddbe2fc3-1ac1-44cf-a0e7-e341b0117924.png)

### Komga version

v0.160.0-master

### Operating system

Docker

### Other details

If the existing sort number is something different than "0", it can be changed and saved as "0" in the dialogue without error. Only exting "0"s are the problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
In addition, using the increment / decrement to change a number to 0 will trigger the same validation rule, but not direct input.
