### ISSUE TITLE
Search has stopped working

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#1058]
### Steps to reproduce

1. Type in a query to search for
2. Hit enter or click "Search All..." in the drop down box that shows results.

### Expected behavior

A pull down menu should appear populated with titles Komga has found. Hitting enter or "Search all" should open a page with all results shown tiled on the screen.

### Actual behavior

A list populates the pull down menu but hitting enter or clicking Search All... in the pull down doesn't do anything.

### Komga version

0.161.0

### Operating system

Android, Windows 11, with Komga running on Asustor NAS

### Other details

This was working before the 0.161.0 update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Works for me. Can you try another browser, or incognito mode, or another computer?

**Comment by billsargent** [comment]
Yes and I'll close this out. It works absolutely fine today. I have no idea what was going on yesterday. Seems a reboot over night and all fixed it. I tried in both Chrome and Firefox and it works just fine.
