### ISSUE TITLE
Docker with watchtower issue with update (buildx)

### ISSUE THREAD

**Issue by stanthewizzard** [gotson/komga#1059]
### Steps to reproduce

Error 404 with watchtower for update of container

### Expected behavior

update ok

### Actual behavior

Hello

Apparently there is an issue with buildx

You should disable provenance as shown in https://github.com/docker/buildx/issues/1513#issuecomment-1398340039

Thanks

### Komga version

latest

### Operating system

docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
i don't understand what's your problem, can you elaborate ?

**Comment by darthmooguy** [comment]
Oh, I'm getting this too in my watchtower pings. It looks like this:

![image](https://user-images.githubusercontent.com/10374678/215268256-955eb261-03cb-4df0-b4f9-7ed787311e67.jpeg)

I don't know why it does that, it only seems to have trouble with the Komga container.

**Comment by stanthewizzard** [comment]
A lot of container have the issue.
Could you follow the link in the first post ? Thank you thank you :))

**Comment by gotson** [comment]
> A lot of container have the issue.

then it's not a Komga issue.

**Comment by stanthewizzard** [comment]
Not directly. But it's the way komga docker is build

**Comment by gotson** [comment]
> Not directly. But it's the way komga docker is build

Works for me so probably a you issue

**Comment by stanthewizzard** [comment]
There is issue for everyone of many docker containers (pi-hole for ex). Could you kindly go to the link at the beginning of the post ?

**Comment by gotson** [comment]
The link is about failing to push, but the push for Komga ia working, so I don't know how it's related?

**Comment by gotson** [comment]
https://github.com/containrrr/watchtower/issues/1528 actually describes the issue. Images still get updated, but warnings are issued.

It's a watchtower issue, following a docker change. It's been fixed in https://github.com/containrrr/watchtower/pull/1533

I don't think there's anything to be done here.

**Comment by stanthewizzard** [comment]
ok
thanks
