### ISSUE TITLE
[Feature Request] Reading Lists (akin to Plex's "Playlists" feature)

### ISSUE THREAD

**Issue by frameset** [gotson/komga#106]
I'd like a feature where we can create custom "playlists" of comics/books. With Western comics there can often be complex "crossover" events where it would be great to create reading lists to allow for smooth reading of these comics in the intended order. Right now you have to jump back to Library search view and find the issue you want to read.

A Playlists tab in the web interface. The interface on clicking would display all created playlists. You could also create a new playlist and rearrange the order of books within playlists. To add items to a playlist, you would find the item(s) in the Library view and use multi select to highlight them, and choose an "add to playlist" button that would appear. (Again this is similar to Plex's playlist feature, try it out if you don't follow my explanation.)

Some managment apps (e.g. Mylar's "story arcs" feature) let you do this via creating folders of symbolic links that can then be read by Komga as differing files and presented to the user as a series folder, but I think having the functionality natively in Komga would be handy.

These playlists could also be exposed via the API for potential client applications.

**Comment by gotson** [comment]
I planned for collections #30 but that would be for series.

Collections for books would indeed be interesting, the whole crossover reading arc is indeed the best use case there. Plex playlist analogy is on point, and the UI would be similar. 

And as always, all features are available on API, since the webui uses it. 

It would also be interesting to add it to the opds feed.

**Comment by frameset** [comment]
Adding it to the OPDS feed would be great, especially for iOS users using Chunky as their client. Single page streaming OPDS of comics in story arc order is about as close to my dream use case as I can get without a native client! 😄
