### ISSUE TITLE
Metrics REST Enpoint

### ISSUE THREAD

**Issue by KillahB33** [gotson/komga#1062]
### Describe your suggested feature

Hey guys, I am working with the homepage team and this request came in https://github.com/benphelps/homepage/issues/474 I am wondering if it's possible to make library count, book count and series count available. This way I can pull them and display them as a widget in homepage. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
they already are available, since the Komga web client is showing them. You can check your network tools to inspect the API.

**Comment by KillahB33** [comment]
Thanks, I thought I checked there already but I guess not.
