### ISSUE TITLE
Ability to move series and books between libraries

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#1063]
### Describe your suggested feature

Select single or multiple series, books, etc.. and be able to move them to a new library. In my instance, I'd like to be able to search by tag and move hundreds of manga to a new library based on a search result. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Not sure what would be the use case of that tbh.

**Comment by billsargent** [comment]
I gave you one. I'm positive there are more people than me who have tons of manga tha are unsorted and its a daunting task to do it manually. Many of mine have tags but they were ripped from large sites that didn't have them categorized very well. 

That and since you offer delete, a move function would be nice as well making this have a management system as well as just a viewer. Right now as it stands, if I find a manga that is in the wrong library, then I need to copy the path and then go out to the terminal and move it and I honestly can't think of a more daunting task than to do this hundreds and hundreds of times for mistagged items etc...

**Comment by gotson** [comment]
> I gave you one

That's not a use case, it doesn't explain why you want to do that.

You are probably using libraries in the wrong way, there's no reason to separate content of the same kind in different libraries.

**Comment by billsargent** [comment]
strike the word manga .... I am managing thousands of doujin... Usually they have 1 chapter. So I create a library for the anime or manga they are written for and then dump the doujin into that library. 

For example, i ripped nhentai's all-male tag and dumped them into a Library with the intent on sorting them into their proper groups but there's no option to move. 

So you're probably right. I'm using it wrong but I cant think of a better way to manage this much doujin.  Yesterday I spent a very very long time trashing most of anything that looks like shota and anything with skirts or cross dressing. I ended up deleted nearly 2500 doujin. But I'm left with a couple thousand in that folder that I can see from the covers that could be moved into proper libraries. 

If you know of a better way, then please offer some advice. :)

**Comment by gotson** [comment]
I don't understand much of what you said, but libraries are clearly not made to separate content like you do. It's more to separate big families of content, like 1 library for comics, 1 for manga, and 1 for magazines.

For organization you can use tags and genre. You can group related series into collections, and books of different series together in a readlist.

**Comment by billsargent** [comment]
Ok. I'll think on that some and see if I can re-organize my collection.
