### ISSUE TITLE
Preload images in komga Webtoon reading mode

### ISSUE THREAD

**Issue by SheepYY039** [gotson/komga#1067]
### Describe your suggested feature

I usually read webtoon directly in browser both on phone and laptop. However, I have to wait (usually for more than 0.5 mins) for the webtoon to load the next page of the same chapter from time to time. It would be great if the reading experience can be more fluent. Thanks.

### Other details

![E091C75C-EC1D-49C9-B3B1-F6E7A68A24B2](https://user-images.githubusercontent.com/56354081/218240399-b68b41b3-1817-4989-8686-91ce94147c77.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Check your network tab in dev tools to see why it takes so long, as the webreader already preload images.

**Comment by SheepYY039** [comment]
I have checked my network and found that sometimes the read-prograss PATCH request takes a long time... 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/56354081/218246654-74e1caaa-d992-4d16-9f0e-b9cebb3397d1.png">

From my observation, all my GET requests happen after the read-progress, since I guess that since the read-progress PATCH responds slow, the GET request for page also turns out slow.

**Comment by gotson** [comment]
you need to check the image loading time
