### ISSUE TITLE
Support for LocalizedSeries

### ISSUE THREAD

**Issue by parasiteoflife** [gotson/komga#1068]
### Describe your suggested feature

Please add support for the LocalizedSeries tag.
Manga Manager supports it.

Having original and localized series title is useful because most information on the Internet is for the original language so when searching for info we need to use the original title but we know the series by the localized title so it's kinda difficult to search for a series in Komga when the original series title is shown and one only knows the localized series title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
What kind of tag is that ? Is that part of `Comicinfo.xml` ?

**Comment by gotson** [comment]
It's not part of the `Comicinfo.xml`, it's [been added](https://github.com/anansi-project/comicinfo/issues/6#issuecomment-1137210167) in Manga Manager despite no consensus being reached on how this should be handled in the schema.

**Comment by majora2007** [comment]
This is also added in Kavita and thus why MangaManager has added it.
