### ISSUE TITLE
Green overlay on some webp images when converted to jpeg/png

### ISSUE THREAD

**Issue by azuravian** [gotson/komga#1077]
### Steps to reproduce

Import comics consisting of WebP images.

### Expected behavior

All issues should import normally and generated images should appear the same as the first page of the cbz.

### Actual behavior

Some issues end up with a green overlay on the generated image.

### Komga version

0.161.0

### Operating system

Windows 11

### Other details

![image](https://user-images.githubusercontent.com/7379812/222874849-9fe7ec2e-144f-4a22-a576-abbdb886ffe6.png)

First image attached as zip (webp format can't be attached on Github).
[001e.zip](https://github.com/gotson/komga/files/10887426/001e.zip)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is not an issue with the thumbnail generation, but from the conversion from `webp` to `jpeg` (or `png` for that matter).

**Comment by gotson** [comment]
It seems it is an issue with the webp image library. I tested it with NightMonkeys ImageIO webp and it works fine.
