### ISSUE TITLE
Question: "Server Settings -> Media Analysis" usage

### ISSUE THREAD

**Issue by keinezeit8** [gotson/komga#108]
The tab "Server Settings -> Media Analysis" only shows `No data available`.

Is that function not yet implemented or have I misinterpreted something.

**Comment by himura95** [comment]
It show the medias that have problems.
I have a cbz file reported to be html/I don't remeber what ^^

**Comment by keinezeit8** [comment]
Okay. Then it's clear why nothing shows up.

**Comment by raining1123** [comment]
> Okay. Then it's clear why nothing shows up.

so what is the ''clear'' reason at all ?
I meet the same problem.

**Comment by keinezeit8** [comment]
There are no problems with my files. So nothing should show up. It is working as intended.

**Comment by gotson** [comment]
Please do not comment on closed issues.
