### ISSUE TITLE
[Feature Request] Ability to change the books under title to other name such as Volume, Chapter

### ISSUE THREAD

**Issue by bsammour** [gotson/komga#1080]
### Describe your suggested feature

Currently, all items are listed as Books whether we add volume or chapters or parts
Is it possible to have the ability to rename or select the format under edit next to the book format
This will also change (Total Book Count)

### Other details

If possible something like this screenshot
![image](https://user-images.githubusercontent.com/40859390/222972958-ad0a1ebf-9921-4140-a5ad-8c63da1fa6e0.png)

As of now, some series will have volumes and other series so the total number of books will be different 
![image](https://user-images.githubusercontent.com/40859390/222973487-054725de-ac09-4519-8490-c1981c971b33.png)

If the series is a new release, it will be released as chapters instead before a volume is released

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
In Komga it's always a book.
