### ISSUE TITLE
[OPDS] show issue number in series book list

### ISSUE THREAD

**Issue by befuddled-dude** [gotson/komga#1082]
### Describe your suggested feature

I notice when viewing a series list in OPDS in Panels, the listing for each issue doesn't show the issue number if there is an issue title

The screenshot in the "details" box shows issue numbers 1 through 9, but it's not apparent from the listing.  For most US comics the issue number is more important for referencing than the issue title.

Would it be possible to add the issue number to somewhat mirror what the web UI does? So instead of:

"Miles Behind Us 2"

it reads: 

"#8 - Miles Behind Us 2"

Honestly, my preference,  (even though it might be bit redundant) would be to have it be consistent regardless of context, so:

"The Walking Dead (2003) #8: - Miles Behind Us 2"

Thanks!

### Other details

![IMG_0446(1)](https://user-images.githubusercontent.com/3521270/223014220-d00abbcf-4f32-4935-9eba-753dc6d1aea1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's by design, and that's how OPDS works, ie showing the title and not other information about the book itself.

**Comment by befuddled-dude** [comment]
Interesting!

Thinking more about it now, I'm occurs to me that what I was thinking of as the issue title ("Miles Behind Us 2") is really the _story_ title.  And of course a single issue (or book, as far as OPDS is concerned) maybe contain more than one story, each with its own title.  (e.g. https://metron.cloud/issue/action-comics-2016-1052/).

I'm now thinking that the issue/book title would be "The Walking Dead (2003) #8", and _that's_ what should be in the OPDS feed, since it's only about the book, not about content/story details, as you said above.   Just some food for thought :-)
