### ISSUE TITLE
Crash/Exception at startup

### ISSUE THREAD

**Issue by lambdareader** [gotson/komga#1087]
### Steps to reproduce

I stopped komga during analyzong of new files.

### Expected behavior

startup normal

### Actual behavior

Gives an exception and no further logs.
If i try connecting to webui it raises a further exception and webui won't load. Tried restarting komga multiple times but it has the same error messages.

I run it with only 2450m ram so sometimes during scanning it gives java heap size errors and either retries or doesn't scan the book. That is acceptable for me and usually either i wait or restart komga since that usually helps if it is stuck on a file.

But now it won't even start anymore , hope there is a fix because i don't have more ram.

At 20:00:50 i try to refresh webui but it doesn't load.

Is there a fix so i can stop the scan or something before startup and perhaps the possibility to make it more ram efficient in the future? 

EDIT: thought i fixed by deleting the file, after that it continued scanning normally. 
Now it is crashing the rest of the files too. It is strange since it worked ok with older komga versions. Sometimes it gives heap space warnings and either skips or retries but now it analyzes 3-4 files and then gives the same exception as in log. After restart it crashes at start like above/in the log.
I will try the older version again.

EDIT 2: 0.161.0 works fine. It gives the expected heap space warning but is scanning slowly. I have scanned a lot in older versions and the only error was komga not analyzing some books or the webui being slower.
Please try to fix it so it works like in older versions and perhaps it is possible to improve low ram behavior in general. I am very confused even by older versions behavior. it skips small files thumbnail generation because heap size but scans bigger without a problem.  
Perhaps the issue in the new version is that it doesn't retry or skip correctly?

### Logs

[log](https://pastebin.com/izEEmsqd)

### Komga version

0.163.0

### Operating system

Raspberry OS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
if you have heap size exceptions **you need to give it more ram**. It's not a warning, things won't work as expected if those happen.

**Comment by lambdareader** [comment]
I always head heap size warnings. I can't give it anymore ram since my machine doesn't have enough. With 0.161.0 and all older versions komga still worked even with warnings. 
I understand that things might not work as expected but some people only have limited physical ram.

I just want to know if you can possibly fix the issue due to low ram, since in the past komga always still worked and 0.161.0 still does. So i assume some changes were made.
I get that low ram may be an issue that is not important but i think a lot of people would benefit if you fixed it, because with this new bug komga is unusable on machines with only 4g physical ram. I presume a lot of people use raspberry pi with only 4g ram or old hardware as a server.

**Comment by gotson** [comment]
> I just want to know if you can possibly fix the issue in 0.163.0 due to low ram, since in the past komga always still worked and 0.161.0 still does. So i assume some changes were made.

That's a wrong assumption.

**Comment by lambdareader** [comment]
Okay then that's weird. I'll be using older versions for the time being.
Would you consider making komga more ram efficient in the future? Perhaps a low ram mode which doesn't load so much into ram or something like that.
