### ISSUE TITLE
[Feature Request] Theming/Guest account

### ISSUE THREAD

**Issue by Drazzilb08** [gotson/komga#109]
With many of us we absolutely love the original theme of Komga.
However, some of us would love to see the ability to theme or skin this software to suite our own sites and integrations with softwares such as Organizr.

I know it has been discussed with having members sign up in order to view the library and to send them a link/temp log in credentials in order to make their own account. However, what I'd be looking for is for it to be completely open such as a guest account. This is mainly due to my instance being offline and allowing everybody within my household to view the content without having to set up an account.

**Comment by gotson** [comment]
Please do not open 2 issues in one. Can you open 2 separate issues for the 2 requests you have?
