### ISSUE TITLE
[OPDS] Supply thumbnail URL for collections and read lists

### ISSUE THREAD

**Issue by GsMumbo** [gotson/komga#1092]
### Describe your suggested feature

OPDS supports sending a thumbnail image for collection items. While Komga does a great job sending a thumbnail for Series, it doesn't currently send any for Collections or Reading Lists.

Both of these already support custom covers in the frontend, this would just encompass passing along that image to OPDS. For Collections / Reading Lists without a custom cover, Komga could either serve a generic thumbnail, no thumbnail, or a generated 4-cover thumbnail that matches what the frontend already shows.

**Custom covers in Komga Frontend**
<img width="994" alt="CleanShot 2023-03-14 at 12 57 21@2x" src="https://user-images.githubusercontent.com/77939716/225080541-a011a641-af96-4069-ae80-4cb4702d2cbe.png">

**OPDS feed showing thumbnails for series**
![IMG_5831](https://user-images.githubusercontent.com/77939716/225083021-fc697403-841a-4ad5-bd27-5e6a83e0ca1a.jpeg)

**OPDS feed without thumbails for Collections and Reading Lists**
![IMG_5832](https://user-images.githubusercontent.com/77939716/225083235-329e1852-39c0-4002-86ca-127dd5b63670.jpeg)

![IMG_5833](https://user-images.githubusercontent.com/77939716/225083271-4ebacfd6-a285-4e3a-9122-92eb1dcd6b6b.jpeg)

### Other details

Related conversation on the Panels app community forums:

https://community.panels.app/t/feature-request-collection-images-from-komga/1730/2?u=gsmumbo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> OPDS supports sending a thumbnail image for collection items. While Komga does a great job sending a thumbnail for Series, it doesn't currently send any for Collections or Reading Lists.

OPDS doesn't support thumbnails for folders, only for acquisition items (ie books).

Panels uses the Komga API to retrieve the Series thumbnails. They could do the same thing for collections/readlists.

**Comment by fillito** [comment]
Sorry for the confusion. My bad 🤦 I forgot I implemented that and thought we were getting it from the feed. We are indeed inferring the thumbnail API endpoint using the feed identifier. We'll do the same for collections/readlists. 👍 

@gotson I have a question, though. I double-checked the OPDS 1.2 specs [regarding artworks](https://specs.opds.io/opds-1.2#522-artwork-relations), and I think any `entry` can have it. The acquisition relation is not required. Let me know if I'm missing something 🤔

**Comment by gotson** [comment]
> @gotson I have a question, though. I double-checked the OPDS 1.2 specs [regarding artworks](https://specs.opds.io/opds-1.2#522-artwork-relations), and I think any `entry` can have it. The acquisition relation is not required. Let me know if I'm missing something 🤔

Section 5 mentions:
> OPDS Catalog Entry Documents are Atom [[RFC4287](https://tools.ietf.org/html/rfc4287)] Entry documents that provide a complete representation of the metadata and data associated with an available Publication.
> 
> Each OPDS Catalog Entry Document must include at least one Acquisition Link.

My understanding is that "folders" (whatever they are, series/collections/readlists) are not catalog entries, because they do not represent "a Publication", and they do not include an "Acquisition Link", but instead a "Navigation Link".

Section 2.2 mentions:

> A Navigation Feed is an OPDS Catalog Feed Document whose Atom Entries serve to create a suggested hierarchy for presentation and browsing. A Navigation Feed must not contain OPDS Catalog Entries but instead contains Atom Entries that link to other Navigation or Acquisition Feeds or other Resources.

The `<entry>` elements are not to be confused with an OPDS Catalog Entry. It is an Atom Entry.

---

I wanted to try it with the OPDS validator, but it's down at the moment :(

**Comment by fillito** [comment]
Thanks for clarifying 🙌 It makes total sense. I'm still learning OPDS 😅 
>The <entry> elements are not to be confused with an OPDS Catalog Entry. It is an Atom Entry.

This is what confused me. I assumed they were equivalent. 

Thanks for taking the time to write such a detailed explanation 🖤💯

**Comment by gotson** [comment]
it's really confusing i have to admit, i had to re-read the whole thing to make sure i understood correctly ! It's too bad it's not supported though :(

**Comment by gotson** [comment]
@fillito since we started talking about OPDS 2.0 in the anansi project for OPDS-PSE, it might be worth raising this request in https://github.com/opds-community/drafts/issues

**Comment by fillito** [comment]
Thanks for the callout! 

Done! 
https://github.com/opds-community/drafts/issues/64
