### ISSUE TITLE
Handle read progress better when a book file changes

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1093]
### Describe your suggested feature

Currently if you use the import feature to upgrade a book, it's reading status gets reset to unread.

Wold be nice if the reading status and reading date would be kept even after an upgrade, the same way how the rest of the metadata is kept.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It is kept, unless the number of pages differ, which is the same behaviour as when a book is updated during a scan.

**Comment by PhilippKammann** [comment]
Makes sense for partial reading progress. 
But if I just upgrade an already read book with a better quality file, but the new file contains a credit page I deleted from the old book (either manual or trough Duplicate Pages) or there is some other imprint in the new book, I don't expect to lose my read status

**Comment by gotson** [comment]
I kinda agree, but what should the rule be then?

Don't touch the read progress when a book changes? Something else?

**Comment by PhilippKammann** [comment]
I would say: 
When the book changes trough file replacement or import and changes page number, 
- if readProgress.completed = True or readProgress = null: Don't touch the read progress.
The third case, I'm not sure
- if readProgress.completed = False: Either set the readProgress back to null or reset readProgress.page = 1
With the first method it would be the same as now, where IN_PROGRESS books get set to UNREAD, but with the second they would keep their IN_PROGRESS status and only lose the page number. That would even keep the readProgress.created timestamp for people who want them

**Comment by gotson** [comment]
I think for in progress we mostly need to check whether the current progress is beyond the total number of pages of the new book, which would be inconsistent. If that's the case adjusting to 1 as you proposed is probably a good idea.

**Comment by PhilippKammann** [comment]
Keeping the current progress in pages, when the total number of pages changed, could be problematic. If e.g. two-page illustriations get joined or split in the new book - different to the old book, you're read progress would suddenly be offset from your actual position in the book
