### ISSUE TITLE
Use a Datepicker to set release date

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1094]
### Describe your suggested feature

It would be nice if you could pick a release date from a calender instead of writing it manually in the Edit Book dialogue.

Like the forms described here https://bootstrap-vue.org/docs/components/form-datepicker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by revanthsonu** [comment]
I would like to work on this can someone assign this to me

**Comment by gotson** [comment]
> I would like to work on this can someone assign this to me

hey, sorry i didn't see your comment earlier!
