### ISSUE TITLE
allow text entry for release date in book's edit dialog in addition to the date picker

### ISSUE THREAD

**Issue by gsargent70** [gotson/komga#1097]
### Describe your suggested feature

The new date picker feature is great but for those of us who use the keyboard mostly it now takes longer to enter a date utilizing the mouse and mouse clicks.  Could we have a feature added to turn the date picker on/off in the settings that way you can use the old way or the new date picker according to the end users workflow preference?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
If every time we add a feature, there's a toggle to remove it, that's not gonna work.

**Comment by Kussie** [comment]
I have to agee with the others, I loathe any non native date picker and find them much much slower.  Maintaining the ability to type the date would be ideal.  Be it making the selection via the picker optional (it can still pop up and the user can either use it or not) or opening it via an icon would be ideally and is fairly standard.

**Comment by gotson** [comment]
> Maintaining the ability to type the date would be ideal.

Seems possible. The text field is read-only to prevent the keyboard from popping up on mobile. We could imagine setting read-only only for xs size screens, as inputting a date on a mobile device in a text field would be painful anyway. Or just leave it editable in all sizes.

**Comment by Kussie** [comment]
You could be really clever and if it's a mobile device, set the field to be a type of 'date' so it will use the native mobile date picker, and the popup date picker only shows on non mobile, which means the field wouldn't need to be readonly and get the best of both worlds

**Comment by gsargent70** [comment]
Yea any of the above ideas would be great.  I am just for having options in terms of data entry as not everyone will have the same workflows.
