### ISSUE TITLE
Config for OPDS prefetching 

### ISSUE THREAD

**Issue by rage1337** [gotson/komga#1098]
### Describe your suggested feature

I'm monstly reading via Panels / OPDS Stream.

My library solely consist of WebP CBZ - everything I add runs through a parser before being added.
Sometimes, mostly when skipping through bigger books, I need to wait for the pages to be preloaded. This means, that
Panels shows me a placeholder image while buffering the real image.
The logs show me, that every image is converted to jpeg, done in org.gotson.komga.domain.service.BookLifecycle. Ok so far if necessary. If I could increase the count of prefetched pages via a config, I would be able to reduce the waiting times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> every image is converted to jpeg

This is a requirement of OPDS-PSE, see [here](https://anansi-project.github.io/docs/opds-pse/specs/v1.2#specifications):

> type MUST indicate the type of image returned by the server (value MUST be one of the following : image/jpeg, image/gif or image/png)

That means `webp` is not supported, and thus need to be converted.



> If I could increase the count of prefetched pages via a config, I would be able to reduce the waiting times.

This is a client side configuration, not server side. You need to request this to Panels directly.
