### ISSUE TITLE
[OPDS] Image link should return full-sized custom thumbnail if set

### ISSUE THREAD

**Issue by awh-tokyo** [gotson/komga#1099]
### Steps to reproduce

1. Access the OPDS catalog and view an entry for any book without a custom poster set
2. Access the "image/thumbnail" link and note that it's a thumbnail of the first page
3. Access the "image" link and note that it's a the first page of the book
4. In the GUI, change that book's poster to a custom image
5. Access the OPDS catalog again

### Expected behavior

The "image" link should be the original image uploaded as the custom poster, and the "image/thumbnail" link should be a thumbnail version of the same image.

### Actual behavior

Although the "image/thumbnail" link contents have changed, it's a full-size image, not a thumbnail, and the "image" link is still the first page of the book.

### Komga version

0.163.0

### Operating system

Linux, running the docker image

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The links will not change, however the content returned by the image/thumbnail link changes. I just tried and it works as expected.

Are you testing via an OPDS client, or directly via the browser ?

**Comment by awh-tokyo** [comment]
I'm testing via a browser, but I tried clearing the cache and then using a different browser entirely so I don't think it's a caching issue.

The "image/thumbnail" link does change, though the returned image seems to be full-resolution for me, not a smaller version.  That may be by design.

However, the "image" link remains a link to the first page of the book: 

```
<link type="image/jpeg" rel="http://opds-spec.org/image/thumbnail" href="/opds/v1.2/books/09ZF85SYB236B/thumbnail"/>
<link type="image/jpeg" rel="http://opds-spec.org/image" href="/opds/v1.2/books/09ZF85SYB236B/pages/1"/>
```

My expectation would have been that the "image" link would return the full-size poster image (either page 1 of the book, or whatever the user has uploaded through the edit book dialog), and the "image/thumbnail" would return a lower-resolution version of the same image.

**Comment by gotson** [comment]
I finally understood what you meant, sorry about that.

The [spec](https://specs.opds.io/opds-1.2.html#522-artwork-relations) says:

> OPDS Catalog Entries may include atom:link elements to images that provide a visual representation of the Publication. For many Publications, these images will be the Publication’s artwork. This specification defines two Artwork Relations, which begin with http://opds-spec.org/image:
> 
> http://opds-spec.org/image: a graphical Resource associated to the OPDS Catalog Entry
> http://opds-spec.org/image/thumbnail: a reduced-size version of a graphical Resource associated to the OPS Catalog Entry

The spec is vague enough so that whatever image could be used. However, the `image/thumbnail` should be the reduced-size version of the `image` link.

Which is not what is happening now.

So it could go one of 2 ways:
- either always display the first page, and forego custom thumbnails. It would be valid as per OPDS spec, but not in line with the rest of Komga.
- or have a way to provide the full size equivalent of the thumbnail.

Point 2 is what you suggest, however i can't remember whether Komga keeps the full size image in various cases.
