### ISSUE TITLE
[Feature Request] BW mode / Contrast modes

### ISSUE THREAD

**Issue by gerroon** [gotson/komga#110]
Hi

It would be nice if one could read the comics in BW/Grayscale with contrast settings. 

The contrast setting can be very helpful on Eink devices.

thanks

**Comment by gotson** [comment]
Hi, could you clarify where / how this would apply? Would this be a webreader setting? Or an api parameter to transform images on the fly?

How do you use Komga on an e-ink device exactly?

For next time please follow the template if possible.

**Comment by gerroon** [comment]
Hi,

The contrast setting can be a book setting like other settings. 

I have an android based eink device and I can use a regular web browser on it.  Eink devices cant show subtle lines and fonts, so contracting or various bw modes help with better color to bw conversion.

I would assume that a lot of people use Android Eink devices (there are even large format ones) for reading comics and books.

**Comment by gotson** [comment]
Which other book settings are you referring to? There might be a confusion about book settings. Book settings would assume that the settings is related to the book itself, which wouldn't be the case here as it would depend on the device.

I am not familiar with e-ink devices showing content that was not made for it. Would you know if the contrast or B&W profile would be :
- specific to a device: all content with the same profile for this device would look good
- specific to a content: this content with this profile would look good on any device 
- specific per content per device: each content for this device need a different profile to look good
- specific to user's likings: some people would prefer the content displayed in a profile while other would prefer another profile

**Comment by gerroon** [comment]
I am talking about the settings below, see the image please.

https://i.imgur.com/S0fh057.png

I personally think that the bw profile should be per book (remembered if it is set) since each book or comic can have its own style, I doubt even the content specific would do an adequate job. 

You can take a look at the Koreader project which is a reader app for Android, Kindle etc specifically for Eink devices but you cna use it on any Android device. It has couple nice settings like contrast, reflow, crop, render quality etc.


thanks





https://github.com/koreader/koreader/

**Comment by gotson** [comment]
The settings shown on the screenshot are per browser (device), persisted in cookies. Some will be overridden by book metadata, like the reading direction).

It seems css offer some filters for grayscale, contrast and brightness, we could try to use that to tweak the image. It could be saved in cookies on the device, per book.

**Comment by gerroon** [comment]
I see I thought that was a per book thing.

See this video, the guy reviews an Android device, and it shows some comic frames there which might give you some idea about general usability of Comic inside a browser via Komga and BW modes.

https://www.youtube.com/watch?v=LvnN3Jkh1Ts

I would be happy to test it whenever you implement it.

**Comment by gotson** [comment]
You would probably have better result by using an app like Tachiyomi, no ?

**Comment by gerroon** [comment]
Well sure , maybe but the issue is that page numbers wont be remembered across devices, at least in a self hosted way. I feel like browser based ereader is the way to go with this.

**Comment by gotson** [comment]
Tachiyomi connects to Komga, so you don't need a local library.

As for read progress, it's not implement for the moment.

**Comment by gerroon** [comment]
> Tachiyomi connects to Komga, so you don't need a local library.

Not sure about that solution, it has been broken for me for quite a while so I stopped using it. It just does not connect to the server. It used to work. I get `unexpected url: /api/v1/series?page=0` 

Also it is not a cross platform solution. I will just wait until KOmga has that feature I guess.
