### ISSUE TITLE
Only display released items in "Recently Released Books" 

### ISSUE THREAD

**Issue by zachstultz** [gotson/komga#1100]
### Describe your suggested feature

Fairy simple concept, to only display items that are the current date and before in the "Recently Released Books".

Sometimes different publishers/digital stores release on different dates. But you can occasionally wind up with a group of books taking up room on the Recently Released Books for weeks and months because their actual date is so far away.
![Screenshot 2023-03-24 at 3 56 28 PM](https://user-images.githubusercontent.com/8385256/227639269-74ed9463-5077-4716-a7b6-d058bd754bb1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's a metadata problem in that case, no?

**Comment by zachstultz** [comment]
> It's a metadata problem in that case, no?

In some cases yes, when a site such as bookwalker has an exclusive edition that is released early, but the metadata for the volume itself is from Yen Press' site. Though some exclusive editions can end up being slightly different from a version that is released at a later date on another site where the metadata was matched to, so that could be considered an incorrect match.

Though I have run into this scenario quite a few times in the past with google's book api for a volume that is released earlier elsewhere, but the volume itself is exactly the same in every aspect, just not released yet on the site that the metadata was scrapped from.
