### ISSUE TITLE
Search series with a colon in title

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [gotson/komga#1101]
### Steps to reproduce

1. Add manga with colon in title to library (eg. `Dance in the Vampire Bund II: Scarlet Order`)
2. Search for the whole title (eg. `Dance in the Vampire Bund II: Scarlet Order`)

### Expected behavior

Search results should show the manga

### _The search returned no results_
_Try searching for something else_

### Komga version

v0.165.0-master

### Operating system

Docker on Manjaro Linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Colon `:` is a special character to denote searching by field. Either enclose the full title within `"`, like `"Dance in the Vampire Bund II: Scarlet Order"`, or search for partial title like `Dance in the Vampire Bund II Scarlet Order`.

**Comment by papaj-na-wrotkach** [comment]
Thank you. I think I should open a issue on tachiyomi org plugin repo then. I originally tried to migrate a manga to Komga source in Tachiyomi app but it didn't show up in search results.

**Comment by gotson** [comment]
> Thank you. I think I should open a issue on tachiyomi org plugin repo then. I originally tried to migrate a manga to Komga source in Tachiyomi app but it didn't show up in search results.

you can change the title afterwards to find the right one
