### ISSUE TITLE
Datepicker for Release Date shows wrong First day of week

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1113]
### Steps to reproduce

1. Edit Book Metadata
2. Click on "Release Date" field and open Datepicker

### Expected behavior

Datepicker opens with locale First day of week (Monday in my case as my whole system is set to German/Germany)

### Actual behavior

Datepicker opens with First day of week as Sunday

### Komga version

v0.165.0

### Operating system

Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
@PhilippKammann sadly this doesn't work on Firefox yet: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo#browser_compatibility

**Comment by PhilippKammann** [comment]
Works for me in Firefox 
![grafik](https://github.com/gotson/komga/assets/56667539/174bb5bb-fa3d-4e6c-899e-e76ab3e17f34)

**Comment by gotson** [comment]
> Works for me in Firefox ![grafik](https://user-images.githubusercontent.com/56667539/250206934-174bb5bb-fa3d-4e6c-899e-e76ab3e17f34.png)

Because it defaults to Monday if it can't find the week info from the locale.
