### ISSUE TITLE
Generating Invite Links for creating new users

### ISSUE THREAD

**Issue by ghost** [gotson/komga#1116]
### Describe your suggested feature

Basically the same as this [FR](https://github.com/gotson/komga/issues/101), but it was marked as Stale and disappeared into the mists of closed issues. The lovely developer even seemed interested in the idea. So I hope it's okay that I'm here to revive it :)

**Short description**
It would be nice to be able to generate some link, where users can press it and sign up for a new user. Currently I'm creating users manually, which I personally think is a bit odd.

It could work like this:
1) Go to the Komga instance
2) Head to `Server Settings`
3) Select the `(+)` option
4) Select `Create Invite Link`
5) There could be a few options in here, like:
- One-time Use
- Limited Use (specify a number, e.g. max 10 uses)
- Time-limited Use (link will expire after X days)
- Unlimited Uses (obviously with a warning that this could be abused etc etc)

### Other details

Discussed before here:
https://github.com/gotson/komga/issues/101

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by 2640yang** [comment]
agree，pls

**Comment by gotson** [comment]
Probbaly best to ask for Komga support in https://github.com/Wizarrrr/wizarr
