### ISSUE TITLE
[Feature Request] Webreader zoom

### ISSUE THREAD

**Issue by ayyilmaz** [gotson/komga#112]
I cant zoom to page at Webreader page. Chrome's PDF extenson allow to oom page. But this is not possible for Komga Webreader page.

**Comment by gotson** [comment]
What kind of zoom would that be ? Using CTRL+Mouse wheel, or pinch-zoom from touch screen?

**Comment by ayyilmaz** [comment]
CTRL+Mouse VVheel zoom page. I think vve can zoom on picture by just  mouse vvheel vithout CTRL button.

**Comment by cloudycloud47** [comment]
Using Chrome Browser as the Webreader, I am unable to 'maintain' the zoom effect.
CTRL+Mouse will allow for Zoom in or out, of the browser page but then the comic page image returns to full screen size.
The Chrome Browser is STILL at more or less than 100% zoom but the webreader remains the same size.

**Comment by sam5558** [comment]
In linux i have an app called mcomix, it is capable of doing a "located zoom" based on cursor's hovering some specific zone.
Would it be possible to implement something similar in komga or not ?
Here's some footage of how it works.

![mcomix-zoom](https://user-images.githubusercontent.com/26897744/89642017-d81c6180-d8aa-11ea-83de-a5ad3375bb64.gif)

**Comment by foux** [comment]
Hi! I think the zoom issue would be particularly useful, and can work like Izneo, Chunky on iPad, or most comics reader : 

- Either a +/- zoom button, or on tactile screens pinch and zoom
- Remember the zoom level between pages, and going to top left of the page when changing page (or top right on a right to left browsing)

**Comment by foux** [comment]
And example with the Izneo action bar, quite well made : 
![Izneo example](https://user-images.githubusercontent.com/246550/112352393-041a1500-8ccb-11eb-8278-e62121bcbb6e.png)

The fullscreen toggle is also particularly useful for reading comics (related to #167 )

**Comment by kjboa** [comment]
Yeah zooming in the webreader would be a nice feature
