### ISSUE TITLE
enhance Komga performance with Redis caching

### ISSUE THREAD

**Issue by ShivamB25** [gotson/komga#1120]
### Describe your suggested feature

I wanted to suggest that you consider using Redis alongside MySQL for caching. Redis is an in-memory data store that can significantly improve the speed of data retrieval, reduce server load, and improve user experience. By caching frequently accessed data in Redis, Komga can reduce the number of queries to MySQL, resulting in faster response times.
Elastic Search is also a option. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You are suggesting a solution without stating a problem.

Mysql is not practical nor fit for selfhosting solutions, and same goes for redis.
