### ISSUE TITLE
Add "Chapter Start" and "Chapter End" metadata tags to books.

### ISSUE THREAD

**Issue by albgraf** [gotson/komga#1121]
### Describe your suggested feature

It would be useful to have the metadata tags "Chapter Start" and "Chapter End" available for books, since you can have on the same library both volumes and individual chapters. Searching a chapter number would then also return the volume on which such chapter is present.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand, can you explain with an example maybe?

**Comment by albgraf** [comment]
Sure. Let's say you have added a series, with files containing full volumes
and individual chapters. Let's say you have 3 volumes, covering chapters 1
to 11, 12 to 23 and 24 to 35, respectively, and another 60 files, with
individual chapters from 36 onwards.

Having the additional "Chapter Start" and "Chapter End" metadata tags would
allow the search to return the 1st volume of the series when searching just
"10", for example. With such metadata, you can then have volume files and
individual chapter files mixed on the same series and library, but still be
able to quickly find any chapter within the series, be it inside a volume
or an individual file.

**Comment by gotson** [comment]
> would allow the search to return the 1st volume of the series when searching just "10"

Searching globally for just a number would yield a lot of results.

I still don't quite understand the use case tbh. For volumes you could set the number to `1-11`, it would then be clear what it contains.

**Comment by albgraf** [comment]
Setting the number 1-11 wouldn’t cause the volume to show up in a search containing the series name and chapter 7, for instance.  We can limit the search using the series name and chapter number, but we would still not able to quickly locate the volume which contains a certain chapter using the search, hence why I think it would be a good idea to have these metadata tags. On 22 May 2023, at 15:45, Gauthier ***@***.***> wrote:﻿

would allow the search to return the 1st volume of the series when searching just "10"

Searching globally for just a number would yield a lot of results.
I still don't quite understand the use case tbh. For volumes you could set the number to 1-11, it would then be clear what it contains.
