### ISSUE TITLE
[Bug] Comma delimited SeriesGroup field in ComicInfo not importing as expected

### ISSUE THREAD

**Issue by shrublet** [gotson/komga#1122]
### Steps to reproduce

1. Create an archive with the SeriesGroup field in ComicInfo.xml
2. Import into library with Collections from ComicInfo enabled

### Expected behavior

Based on the documentation [here](https://anansi-project.github.io/docs/comicinfo/documentation#seriesgroup) for the Anansi Project, I presumed comma-separated values would be converted into discrete collections in Komga.

### Actual behavior

Komga imports the collection as a singular entry with a comma in the name instead.

### Komga version

0.165.0

### Operating system

Windows 11

### Other details

Have additionally tried importing with multiple SeriesGroup fields, but only one is ingested.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
From the [documentation](https://komga.org/guides/scan-analysis-refresh.html#collections):

> The SeriesGroup element will be used to create a collection with that name, or add the series to an existing collection with that name.

> If the SeriesGroup element is set to a different value in each book of the series, then each value of the element will create a collection.

**Comment by gotson** [comment]
Well ComicInfo is not documented, and the documentation we produced came after the Komga implementation. Changing the behaviour now would introduce a change for existing users, and i am not really sure of what's the usage of that field in the wild.
