### ISSUE TITLE
Add the function of recognizing epob book genre as the book tags in metadata

### ISSUE THREAD

**Issue by narcissu0713** [gotson/komga#1123]
### Describe your suggested feature

Komga can only recognize the genres information of epub books in the series metadata now. I hope to add the function of recognizing the genres information of a single epub book as the book tags in the future

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you explain what tag you are referring to in epub?

**Comment by narcissu0713** [comment]
I use Calibre to write metadata to my comic file. The display of EPUB books is shown in Figures P1&P2, and the display of CBZ books is shown in Figures P3&P4. I hope that EPUB books can recognize the tags of individual books like CBZ books do

I am not good at writing English. Thank you very much for reading through my questions

![P1](https://github.com/gotson/komga/assets/108988713/c317d4d7-02d6-4c88-b148-ff3a98075ed7)
![P2](https://github.com/gotson/komga/assets/108988713/38c6f756-2d7a-493d-84ac-9d96a879f106)
![P3](https://github.com/gotson/komga/assets/108988713/2005a050-4153-42c7-9857-0441dc38bf3e)
![P4](https://github.com/gotson/komga/assets/108988713/026ababd-9ae1-40f8-a5be-19b7d135f8fb)

**Comment by gotson** [comment]
I need details on the metadata inside the epub file. Can you post the opf file inside that is inside the epub?

**Comment by narcissu0713** [comment]
> I need details on the metadata inside the epub file. Can you post the opf file inside that is inside the epub?

The original files of the comics are in PDF format, and I used Calibre to convert them into EPUB format and write metadata into them.

`<?xml version="1.0" encoding="utf-8"?>
<package version="2.0" unique-identifier="uuid_id" xmlns="http://www.idpf.org/2007/opf">
  <metadata xmlns:opf="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:calibre="http://calibre.kovidgoyal.net/2009/metadata">
    <dc:title>All You Need Is Kill Vol 01</dc:title>
    <dc:creator opf:role="aut" opf:file-as="小畑健">小畑健</dc:creator>
    <dc:contributor opf:role="bkp">calibre (6.17.0) [https://calibre-ebook.com]</dc:contributor>
    <dc:identifier id="uuid_id" opf:scheme="uuid">44770cc0-9e5d-4674-a846-22eb7d769447</dc:identifier>
    <dc:description>&lt;div&gt;
&lt;p&gt;被称为「GITAI」的谜之生物袭击地球，士兵桐谷启二加入与GITAI作战的统合防疫军。首次出战就战死的他，由于某种不明原因，竟然重获生命，回到出战前的那天早晨。这种奇怪的现象不断重复，把桐谷卷入诡异的时间轮回。但当他轮回到第158次的时候，在战场上与一位女性重逢……&lt;/p&gt;&lt;/div&gt;</dc:description>
    <dc:date>0101-01-01T00:00:00+00:00</dc:date>
    <dc:subject>战斗</dc:subject>
    <dc:subject>科幻</dc:subject>
    <dc:language>zh</dc:language>
    <dc:identifier opf:scheme="calibre">44770cc0-9e5d-4674-a846-22eb7d769447</dc:identifier>
    <meta name="calibre:timestamp" content="2023-05-22T03:14:57.357458+00:00" />
    <meta name="calibre:title_sort" content="All You Need Is Kill Vol 01" />
    <meta name="cover" content="cover" />
  </metadata>`

**Comment by gotson** [comment]
Can you point out what value you're talking about?
