### ISSUE TITLE
Enhanced Deduplication, Metadata Retention, and API Integration for Efficient Manga Collection Deduplication

### ISSUE THREAD

**Issue by JediMaster25** [gotson/komga#1124]
Hello,

I recently came across a few large manga collections and wanted to utilize Komga, the free and open-source comics/mangas media server, to deduplicate them effectively. However, I discovered that the current deduplication feature in Komga only detects exact duplicates based on file hashing, making the process time-consuming and manual. 

To address this limitation and streamline the deduplication process, I would like to request the addition of an enhanced deduplication feature with metadata retention functionality and API integration for Komga.

Background:
I encountered difficulties while attempting to deduplicate my manga collections using Komga's existing deduplication feature. The time required to manually identify and delete exact duplicates using file hashing became impractical, especially with large collections. This sparked the idea of leveraging a metadata database, similar to MusicBrainz, to automate the deduplication process and enhance the overall efficiency of manga organization.

Feature Request:
I propose implementing the following enhancements to Komga:

1. Metadata-based Deduplication: In addition to file hashing, Komga should consider metadata attributes (such as title, author, series, etc.) when detecting duplicates. This would enable Komga to identify duplicates even if the file content differs slightly. By utilizing metadata-based deduplication, the process would become more accurate and efficient.

2. Retaining Metadata: It is crucial to retain the metadata of deleted duplicate books in the Komga library. This ensures that even after deduplication, the metadata remains accessible and facilitates better manga organization and categorization.

3. API Integration: To further enhance the deduplication process and enable automation, integrating the API would allow users to send duplicated files to a public demo instance. This would transform the public demo into a manga metadata database, capable of maintaining a comprehensive record of all duplicates and associated metadata.

Benefits:
- Efficient Deduplication: The proposed enhancements would significantly improve the efficiency of manga collection deduplication. By considering both file hashing and metadata, Komga would be able to automatically detect duplicates, reducing manual efforts and saving time for users.

- Streamlined Manga Organization: With metadata retention, users can benefit from a comprehensive and organized manga library even after duplicates have been deleted. The retained metadata ensures that books are properly categorized and can be easily searched and accessed.

- Automated Metadata Database: The API integration, along with the public demo acting as a manga metadata database, would provide users with a powerful resource for discovering new manga based on metadata-driven recommendations. This would enhance the overall browsing experience and promote manga exploration.

Next Steps:
I kindly request your consideration and implementation of these features. By adding an enhanced deduplication feature with metadata retention and API integration, Komga would become an invaluable tool for manga enthusiasts, streamlining the deduplication process and promoting efficient manga organization.

Thank you for your attention to this request. I appreciate your dedication to continually improving Komga's functionality and user experience.

Best regards.

**Comment by gotson** [comment]
No plans for that.
