### ISSUE TITLE
Easily set the current progress

### ISSUE THREAD

**Issue by Belphemur** [gotson/komga#1125]
### Describe your suggested feature

Hey,

It would be nice to be able to set everything as read for a series until a specific entry like in tachiyomi.

# Use case
I use Kaizoku and Mangal to download series automatically. It download everything from the first chapter to the latest released.
If I was reading that serie already, I have to go to each individual chapter and put them as read.

# Workaround
I use tachiyomi to set the progress of the serie.
Works for me, but I started to share my love with other fiends 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Select first book, shift click the last book you want to mark read, and Komga will select all books in between. Click mark as read. Done.

**Comment by Belphemur** [comment]
Sorry, but that doesn't work with multiple page. I would still need to do that page by page.
That is not a good UX.

**Comment by gotson** [comment]
Increase the number of books on a page
