### ISSUE TITLE
Save reading mode per librairie/series

### ISSUE THREAD

**Issue by simonjodet** [gotson/komga#1138]
### Describe your suggested feature

Hi.
It would be really nice to save reading mode per librairie and/or series. Switching from webtoon to left-to-right and the other way around screws up the reading point.
It would be great if Komga could retain the reading mode for a series or a librairie and not retain it when going from Webtoon A to manga B for example.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can already set the reading direction at Series level. For libraries there is already #873

**Comment by simonjodet** [comment]
Ok I totally missed the reading direction in the series settings. It's not called reading mode, maybe something to consider? 
Thanks anyway. Closing now.
