### ISSUE TITLE
Unable to edit book details from series screen.

### ISSUE THREAD

**Issue by THElegend5** [gotson/komga#1139]
### Steps to reproduce

1. Open any series.
2. Try to edit details of any of the books using the edit button of that book in the series.

### Expected behavior

You are able to edit the book details from the edit screen.

### Actual behavior

Edit button doesn't do anything.

### Komga version

1.0.0

### Operating system

Windows 11

### Other details

Happening on Firefox nightly 116.0a1 (2023-06-27) (64-bit) [ Haven't tried on any other browser]
and getting the following error when clicking the edit button from console logs of the browser.
TypeError: can't access property "firstDay", (new Intl.Locale(...)).weekInfo is undefined
    ht EditBooksDialog.vue:4
    VueJS 13
    setUpdateBooks store.ts:108
    k vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    dialogUpdateBooks store.ts:209
    M vuex.esm.js:851
    dispatch vuex.esm.js:516
    dispatch vuex.esm.js:406
    editSingleBook BrowseSeries.vue:896
    editItem ItemCard.vue:357
    click ItemCard.vue:3
    VueJS 4
    click VBtn.js:134
    VueJS 47
    <anonymous> index.js:44
    setTimeout handler*runDelay index.js:41
    onMouseEnter VHover.js:23
    VueJS 3
vue.runtime.esm.js:1897:12
    VueJS 16
    setUpdateBooks store.ts:108
    k vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    dialogUpdateBooks store.ts:209
    M vuex.esm.js:851
    dispatch vuex.esm.js:516
    dispatch vuex.esm.js:406
    editSingleBook BrowseSeries.vue:896
    editItem ItemCard.vue:357
    click ItemCard.vue:3
    VueJS 4
    click VBtn.js:134
    VueJS 47
    <anonymous> index.js:44
    (Async: setTimeout handler)
    runDelay index.js:41
    onMouseEnter VHover.js:23
    VueJS 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Bug introduced by #1113
