### ISSUE TITLE
JarLauncher has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by miszterx** [gotson/komga#1140]
### Steps to reproduce

simple start the komga:

/usr/bin/java -jar komga.jar -Xmx256m --server.port=8081
Error: LinkageError occurred while loading main class org.springframework.boot.loader.JarLauncher
	java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

### Expected behavior

Should start. At least until 0.165 it worked with this java version;

### Actual behavior

Doesn't start. See the error. Seems to be java 11 is not enough, but I haven't found info about it.
On the official site java 8+ is written:

https://komga.org/installation/jar.html#run-with-the-jar-file

TIP
You need Java version 8+ (or 1.8+) to run Komga. Check your version with java -version.

### Logs

/usr/bin/java -jar komga.jar -Xmx256m --server.port=8081
Error: LinkageError occurred while loading main class org.springframework.boot.loader.JarLauncher
	java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

### Komga version

1.0

### Operating system

ubuntu 22.04

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by kattjevfel** [comment]
> target JDK 17: Java 17 or above is now required ([9569c5b](https://github.com/gotson/komga/commits/9569c5b))
from the 1.0.0 changelog

**Comment by gotson** [comment]
The release note points to the upgrade guide, the minimum java version is now 17.
