### ISSUE TITLE
Version 1.0.0 default port change breaks network connection for automatically updated Docker Komga images that do not update settings

### ISSUE THREAD

**Issue by rasalomx** [gotson/komga#1141]
### Steps to reproduce

Update Komga in Docker with Watchtower to version 1.0.0 or manually update and then try to navigate to Komga.

### Expected behavior

Komga should work by passing information on port 8080.

### Actual behavior

New version of Komga now changes default port to 25600 without anticipating updaters will likely NOT pass that change in on their own. Required user intervention to fix, missing bed time.

### Komga version

1.0.0

### Operating system

Synology NAS DSM 6.0

### Other details

How I noticed this and fixed it:
1. Komga reporting website error when browsing from any PC in network
2. Check Docker, Watchtower has automatically updated docker image = 1.
3. Watchtower had updated Komga to version 1.0.0
4. Read Komga documentation, see new feature: default port was set to 25600.
5. Check my settings in Docker > Container > Komga (Turn it off first) > Edit > Port Settings (Default port is still set to 8080)
6. Change value to to 25600 (https://i.imgur.com/XtsnZEs.png). 
7. Save changes. Restart Komga.
8. Komga works as expected.

You may want to broadcast the need to update settings on your site when upgrading. Otherwise, expect noise.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> You may want to broadcast the need to update settings on your site when upgrading. Otherwise, expect noise.

It has been announced over 3 months ago, on Discord, and on the website https://komga.org/installation/upgrade.html

**Comment by darthmooguy** [comment]
> First thing I do is look at logs when there's a problem...
> 
> ____ **. | |/ _|_**_ _____ _________ | < / _ \ / \ / _____ | | ( <_> ) Y Y / /_/ > __ _ |__**|__ _**_/|__|_| /___ (____ / / //_____/ / Version: 1.1.0 **Listening on port: 25600** (insert other good diagnostic info here)
> 
> ...would have saved me some time figuring this out.

It is in the logs, just a bit further down.
```log
2023-07-07T11:15:07.881-04:00  INFO 1 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 25600 (http) with context path ''
2023-07-07T11:15:08.014-04:00  INFO 1 --- [main] org.gotson.komga.ApplicationKt           : Started ApplicationKt in 15.732 seconds (process running for 16.673)
```
