### ISSUE TITLE
Unable to start latest versions (1.0.0 / 1.1.0) through docker

### ISSUE THREAD

**Issue by SR-G** [gotson/komga#1144]
### Steps to reproduce

Update from old KOMGA version through docker image to 
- either gotson/komga:1.1.0 (latest)
- either gotson/komga:1.0.0 (downgrade, just in case)

### Expected behavior

Application should be starting normally

### Actual behavior

and encounter :
- application not starting anymore
- thousands of thousands of messages like "2023-06-29T22:52:46.596Z  WARN 1 --- [mpl$9@72ceafeb)] o.apache.activemq.artemis.core.server    : AMQ222029: Could not locate page transaction 58220628957, ignoring message on position PagePositionImpl [pageNr=134, messageNr=3429, recordID=-1] on address=domain.events queue=domain.events
^C"

### Komga version

1.1.0

### Operating system

docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment]
With your container stopped, go to your mounted storage and delete the artemis folder. It will rebuild it when komga starts back up.

**Comment by gotson** [comment]
Please post the full log file from startup for troubleshooting.

**Comment by DCS-MANGO** [comment]
Please check the container port NUM. It changed 8080 to 25600

**Comment by tombatti** [comment]
Ok work for me!

**Comment by SR-G** [comment]
Well i had to restart from scratch, and delete / reconfigure everything :(
Logs were several hundreds of MB (as several rotated docker JSON files), i had to also delete all of them, and before that it was difficult to browse them due to the number of repetitive events.
