### ISSUE TITLE
The new added books can not be scanned

### ISSUE THREAD

**Issue by DCS-MANGO** [gotson/komga#1145]
### Steps to reproduce

1. Added new books to Komga data folder

2. Push the  "Scan Library files"

### Expected behavior

The new added books will be shown.

### Actual behavior

The "Scan Library files" button doesn't  work. 

### Komga version

1.1.0

### Operating system

Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> The "Scan Library files" button doesn't work.

Can you check if the browser is making the API call in the dev tools, network tab?

You also need to provide logs from startup until the attempted scan.

Has it worked before? Or never?

**Comment by DCS-MANGO** [comment]
> > The "Scan Library files" button doesn't work.
> 
> Can you check if the browser is making the API call in the dev tools, network tab?
> 
> You also need to provide logs from startup until the attempted scan.
> 
> Has it worked before? Or never?

Thank.
But I don't know how the Komga Sever work. I just follow the install instruction.

In previous version, it did work well. (I mean, showed the newly added book, when I pushed the scan library button. 
[komga.zip](https://github.com/gotson/komga/files/11912685/komga.zip)
)

Here is my log I attach.

**Comment by gotson** [comment]
your have issues with the Artemis broker. Try to stop Komga, delete the `artemis` directory, and start it again.

**Comment by DCS-MANGO** [comment]
> your have issues with the Artemis broker. Try to stop Komga, delete the `artemis` directory, and start it again.

thanks
It works!!!!
