### ISSUE TITLE
"Auto-Delete Remaining" button for Duplicate Pages

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1147]
### Describe your suggested feature

A new button like the "Ignore Remaining" button added in v1.1.0 but for quickly setting all shown hashes to auto-delete

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I am not very inclined to add this. There's gonna be much more pages to ignore than pages to delete i believe.

**Comment by PhilippKammann** [comment]
I know that it is niche but it would be very helpful for my workflow and I don't think it would be detrimental for anyone else

**Comment by gotson** [comment]
it's just a bit more risky IMO, mass ignoring doesn't have side effects, misclicking on auto delete by error and getting 50 pages in auto delete is a bit more dangerous.

why can't your workflow work with first choosing the pages to delete, then ignore the rest ?

**Comment by PhilippKammann** [comment]
Manga/manwha scanlators normally add a unique credit page with a chapter number as the first page. 
My downloader duplicates the first page of a new chapter so I can use Komgas duplicate pages feature to delete the credits.

My workflow is then to ignore the 1 or 2 duplicates that are not credit pages and auto-delete everything else.
Probably niche but most  effective way I found to delete the credit pages.

Misclicking would be a problem, but Komga only deletes after the next scan so there is sitll a failsafe. Maybe add a some kind of conformation for auto-delte remaining?

**Comment by gotson** [comment]
> My downloader duplicates the first page of a new chapter so I can use Komgas duplicate pages feature to delete the credits.

why doesn't it delete it instead ? 🙃 

> Maybe add a some kind of conformation for auto-delte remaining?

probably need yes

**Comment by PhilippKammann** [comment]
> why doesn't it delete it instead ? 🙃
Sometimes they _don't_ put in a credit page as the first page and short of training a neural networks for image recognition I have no idea how to check that.
So I use the duplicate-pages tab to check before deleting
