### ISSUE TITLE
Import raw images

### ISSUE THREAD

**Issue by schklom** [gotson/komga#1154]
### Describe your suggested feature

Currently, I have a few mangas stored in this format
```
├─── Name
|    |    ├─── Page 1.png
|    |    ├─── Page 2.png
|    |    └─── Page 3.png
|    └─── ...
```
because I have read them by simply opening the first page for years.
Now that I have discovered Komga, I would like to import them, but currently Komga only accepts certain archives.

Could you make Komga be able to read folders with png, jpg, etc files?

### Other details

I did not find a similar issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That won't happen. You should zip your images in a `cbz` file instead.

**Comment by DieselTech** [comment]
For reference, `cbz` is just a zip file renamed to .cbz

There is plenty of scripts out there that could easily zip up your images and rename the files. Then it would be supported in komga
