### ISSUE TITLE
User Registration and Uploading Files

### ISSUE THREAD

**Issue by WindyCloudCute** [gotson/komga#1157]
### Describe your suggested feature

Are there plans to allow users to build their own libraries and upload their own media files?
For example, the library created by the user is not allowed to have the same name as other libraries, and the uploaded files will go through HASH verification to prevent duplication with files uploaded by other users.
It is hoped that MySQL can be used as the database of the server.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There's no plan for such features.
