### ISSUE TITLE
 cannot be encoded as it is outside the permitted range in 1.2.0

### ISSUE THREAD

**Issue by acer1204** [gotson/komga#1161]
### Describe your suggested feature

i update the komga 1.2.0. i scan library.
it show this problem.
java.lang.IllegalArgumentException: The Unicode character [ふ] at code point [12,405] cannot be encoded as it is outside the permitted range of 0 to 255.

and i find another problem.
if i enter the book to read, then use upper left corner return button. it will show not thing.

http://ooxxxoox:8083/series/0CZM64WDPG62B   ==>list folder path
http://ooxxxoox:8083/book/0CZM64WDTG7QR/read?page=1&incognito=false    ==>read image  path
http://ooxxxoox:8083/book/0CZM64WDTG7QR    ==>upper left corner return will become an error path.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please provide full log and details on how it's installed.

**Comment by acer1204** [comment]
cht interface log.
[cht.txt](https://github.com/gotson/komga/files/12065459/chs.txt)
en interface log.
[en.txt](https://github.com/gotson/komga/files/12065460/en.txt)

the return looks on log to show.
i test it, it only use cht interface will cause this problem.

**Comment by gotson** [comment]
Please provide details on how you run Komga

**Comment by acer1204** [comment]
> Please provide details on how you run Komga

my env is windows docker,
i use it to build komga.
i try the poroblem in many os.
ubuntu docker and synology docker has this problem in cht interface.
(return btn error path). and the unicode problem . include java version.

**Comment by gotson** [comment]
You probably have a locale problem where your JVM is not running properly in Unicode.

Try to set an environment variable called `LC_ALL` to the value `en_US.UTF-8` and see if that fixes it.

**Comment by gotson** [comment]
Can you confirm that the only symptom is some exceptions in the logs and that the reader works fine ?
