### ISSUE TITLE
Cannot search for publishers with commas in name

### ISSUE THREAD

**Issue by kattjevfel** [gotson/komga#1169]
### Steps to reproduce

1. Add a publisher with a comma (like _Seven Seas Entertainment, LLC._) to a series
2. Click on the publisher name from the series page
3. Get _The active filter has no matches_

### Expected behavior

Komga should find series from that publisher

### Actual behavior

Komga can't find anything

### Komga version

1.2.1

### Operating system

Arch Linux

### Other details

This metadata was imported via [AnisearchKomga](https://github.com/Pfuenzle/AnisearchKomga/), in case you're normally not supposed to be able to even enter commas, and this tool just happened to break everything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Full text search works with tokens, not actually the full text. Just typing "seven seas" would work. Commas are stopped by the tokenizer of the search library.

**Comment by gotson** [comment]
This is a tricky case. Filters are passed to the backend via query parameters. Query parameters can be passed on different ways in case there are multiple values, either a single parameter with comma separated values `a=b,c`, or a repeated parameter each with a value `a=b&a=c`.

Spring is smart enough to handle various cases, however when you pass a single value that is comma separated, it throws the logic off.

If you were to filter on that publisher and another one, it works as expected.

**Comment by gotson** [comment]
I've spent a decent amount of time today trying to fix this, and unfortunately there is no good solution for the moment. Changing the logic used for splitting parameters with the `,` would introduce more problems elsewhere.

The best course of action would be to move from a GET request with request parameters to a search object in the body of the request.

**Comment by Mahesh-Vemula** [comment]
@gotson  Adding below method inside controlled fixed this issue.

```
@InitBinder
	public void initBinder(WebDataBinder binder) {
		binder.registerCustomEditor(List.class, new CustomCollectionEditor(List.class));
	}
```

**Comment by gotson** [comment]
> @gotson Adding below method inside controlled fixed this issue.
> 
> ```
> @InitBinder
> 	public void initBinder(WebDataBinder binder) {
> 		binder.registerCustomEditor(List.class, new CustomCollectionEditor(List.class));
> 	}
> ```

it tried this but it breaks other stuff
