### ISSUE TITLE
Komga container restarting constantly

### ISSUE THREAD

**Issue by beskeen** [gotson/komga#1172]
### Steps to reproduce

1. Create to Komga container using the following command:

docker create \
  --name=komga \
  --user 1000:1000 \
  -p 25600:25600 \
  --mount type=bind,source=/Users/plexkeen/Library/Application\ Support/Docker\ Komga,target=/Docker\ Komga\
  --mount type=bind,source=/Volumes/Media/Comics,target=/Comics \
  --restart unless-stopped \
  gotson/komga

2. Start the container.
3. Wait 5 seconds.

### Expected behavior

Container is created and runs without restarting.

### Actual behavior

Container is created and runs for a couple seconds, then restarts. Does this until stopped.

### Logs

[Komga Logs.txt](https://github.com/gotson/komga/files/12165496/Komga.Logs.txt)

### Komga version

1.2.1

### Operating system

MacOS 13.1

### Other details

This is my first time trying to set up Komga, it has never worked properly for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You need to provide a mount for `/config`

**Comment by beskeen** [comment]
Wow. Kinda embarrassed that it was that easy. That worked. Thanks!!
