### ISSUE TITLE
1.2.1 Won't Load WebUI Anymore

### ISSUE THREAD

**Issue by whatinthenameofgod** [gotson/komga#1174]
### Steps to reproduce

Hello! So I am having a similar issue with my Synology / Docker set up that I saw posted with the WebUI is not showing up at all anymore.

It worked great for along time with zero issues but now, nothing.

Logs attached.

Any help is appreciated!

### Expected behavior

WebUI would open.

### Actual behavior

This site can't be reached / This page isn’t working.

### Logs

[komga.csv](https://github.com/gotson/komga/files/12189774/komga.csv)

### Komga version

1.2.1

### Operating system

Windows 11 / Synology / Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by surfwave** [comment]
The default port of web ui in version 1.2.1 is 25600. You can modify the port from 8080 to 25600.

**Comment by whatinthenameofgod** [comment]
I think that fixed it. Thank you so much! Really appreciate the support.
