### ISSUE TITLE
Http response header causing an exception

### ISSUE THREAD

**Issue by Restil1789** [gotson/komga#1176]
### Steps to reproduce

Hello, i think the problem is with having a file with special characters as ","

### Expected behavior

Removed of the specials chars to not provocked any Exception

### Actual behavior

Generete an exception, and a warn.

### Logs

Removed - attach a file instead

### Komga version

1.2.1

### Operating system

Docker windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please don't put thousand lines of log in the body of the issue, attach a file instead. Also please provide details on what you have been doing to get into that state, there is no details at all in your issue.

**Comment by Restil1789** [comment]
I just open the online reader.
As i can see each pages got an header with the name of the file + num of the file.
If the file contains characters who are not approved in the header that provoked an exception as printed in the log

**Comment by Restil1789** [comment]
[header.log](https://github.com/gotson/komga/files/12208969/header.log)

**Comment by gotson** [comment]
Looks like java is not running in unicode or something.

What's your java version?

**Comment by Restil1789** [comment]
$ java --version
Picked up JAVA_TOOL_OPTIONS: -Xmx4g
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

**Comment by gotson** [comment]
similar to #1161

**Comment by gotson** [comment]
Can you confirm that the only symptom is some exceptions in the logs and that the reader works fine ?

**Comment by Restil1789** [comment]
Yes, but it's a normal bug unicode (> 255 ) are not permited in header value.

Normally you should have only 

The value of the HTTP request header you want to set can only contain:

Alphanumeric characters: a-z, A-Z, and 0-9
The following special characters: _ :;.,\/"'?!(){}[]@<>=-+*#$&`|~^%

**Comment by gotson** [comment]
> Yes, but it's a normal bug unicode (> 255 ) are not permited in header value.
> 
> Normally you should have only
> 
> The value of the HTTP request header you want to set can only contain:
> 
> Alphanumeric characters: a-z, A-Z, and 0-9 The following special characters: _ :;.,/"'?!(){}[]@<>=-+*#$&`|~^%

Yes, it used to work on older tomcat versions, they seem to have enforced it in more recent ones.
