### ISSUE TITLE
Pop-up in Metrics Pie shows IDs

### ISSUE THREAD

**Issue by Rabenherz112** [gotson/komga#1177]
### Steps to reproduce

1. Go to Server Settings 
2. Navigate over to Metrics
3. Hover over the white dividing line in the pie chart

### Expected behavior

In the best case, there shouldn't be a pop-up when hovering offer the divider lines.

### Actual behavior

Pop-up shows all Libary IDs with 0 bytes.

### Komga version

v1.2.1-master

### Operating system

Debian 11 (bullseye)

### Other details

Here an image of the Bug:
![2023-07-30-13-09_256](https://github.com/gotson/komga/assets/66558576/74221006-6fe1-4398-8c2a-753a924b100e)

This is related to the closed issue #1159

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Make sure you're on the latest version as this has been solved already.

**Comment by Rabenherz112** [comment]
Hey there, as far as I can see, I am on the latest version.
![2023-07-30-16-07_257](https://github.com/gotson/komga/assets/66558576/c22b8fc2-9944-43e2-83be-b542f29d6974)

**Comment by gotson** [comment]
Clear your browser cache, or try in incognito.

**Comment by gotson** [comment]
It's also very weird that it shows all libraries as zero bytes in size.

**Comment by gotson** [comment]
OK now that I reread your issue I see that you hover on the lines in between. I reproduce, but honestly this is minor and not important.

The charting library is not supported anymore in that version if I recall correctly.
