### ISSUE TITLE
Issue template links to the wrong Webpage

### ISSUE THREAD

**Issue by Rabenherz112** [gotson/komga#1178]
### Steps to reproduce

Upon generating an issue and pressing on the Link embedded in the "I have checked the FAQ." check, it directs me to an incorrect URL.

### Expected behavior

It should be linked to https://komga.org/docs/faq

### Actual behavior

It currently links to https://komga.org/faq/

### Komga version

N/A

### Operating system

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Thank you !
