### ISSUE TITLE
I can't update to 1.3.0

### ISSUE THREAD

**Issue by DCS-MANGO** [gotson/komga#1182]
### Steps to reproduce

1. The Komga server is installed on synology (Ver. 7.2)with Docker.
2. I always updated through Docker in the same way, but only version 1.2.1 was installed and version 1.3.0 was not installed.
3. The command that I used is as follow.

docker run -d --name=komga \
-p 8341:25600 \
-e PUID=1024 \
-e PGID=100 \
-e TZ=Asia/Seoul \
-v /volume7/docker/komga/config:/config \
-v /volume7/docker/komga/data:/data \
--restart always \
gotson/komga

4.  Only installed Ver. 1.2.1
    

### Expected behavior

When I use above command lines, It should be updated.

### Actual behavior

Not updated. Only installed Ver. 1.2.1 

### Logs

[komga.log](https://github.com/gotson/komga/files/12259122/komga.log)

### Komga version

1.2.1

### Operating system

Synology 7.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
docker images are not yet published for 1.3.0
