### ISSUE TITLE
Select Series in import list doesnt return any results

### ISSUE THREAD

**Issue by aqsd91** [gotson/komga#1186]
### Steps to reproduce

1. Import a .cbl read list
2. Try to select a series for unmatched books
3. Search a series

### Expected behavior

When searching series the results should show up

### Actual behavior

Instead the search returns no results "No Series found" message appears

### Logs

https://gist.github.com/aqsd91/ee08255d87f19d75fd1e1417b6df0d43

### Komga version

1.3.0-master

### Operating system

Docker desktop (running WSL 2)

### Other details

The FAQ page returns 404 btw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Do you have series in your library already?

**Comment by aqsd91** [comment]
I have 210 series and most of the list is matched, some of it isn't matched so i have to manually select it but the search doesn't return any results (for anything).

**Comment by gotson** [comment]
Please provide a HAR file for investigation

**Comment by aqsd91** [comment]
Here's the Har file and a screenshot (note you can see a series with daredevil exists below)
[localhost_Archive [23-08-06 11-44-02].
![Screenshot 2023-08-06 114557](https://github.com/gotson/komga/assets/73997602/ee55bb1b-b065-465c-93d7-c433fd5c30ea)
zip](https://github.com/gotson/komga/files/12269112/localhost_Archive.23-08-06.11-44-02.zip)

**Comment by gotson** [comment]
Does it work when you search series from the search bar at the top?

**Comment by aqsd91** [comment]
It does.
