### ISSUE TITLE
Add Tags but not show my book.

### ISSUE THREAD

**Issue by acer1204** [gotson/komga#1187]
### Steps to reproduce

This is my Structure.

Comic Library
  --AComic (4 Book)
  ----UUC-DDD01
  ----UUC-DDD02
  ----UUA-DDD01
  ----UUA-DDD02

I Add UUC and UUA tag in AComic folder by web edit.
The AComic's TAGS will show my tag. (Like UUA,UUC)
but if i click the TAGS, it show the AComic(4 BOOK),not show UUA-DDD01 and UUA-DDD02.
![1691297081172](https://github.com/gotson/komga/assets/6522774/46a42b18-607c-41a2-b5b7-c88c172d03d9)

but if click right menu tags to select, it work...
![1691297161091](https://github.com/gotson/komga/assets/6522774/b5c086c9-29a2-44f6-a455-470cc3c2cb6d)
It's a bug?

### Expected behavior

It's should be show the book, when i click tags.

### Actual behavior

It's not show the book, just show the root folder.

### Komga version

1.3.1

### Operating system

Windows Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Series tags and book tags are different. Tag the books if you want to filter books by tags.

**Comment by acer1204** [comment]
all book i have add tag,
them the series tags is auto create, not i edit it.
when i add tag in book. the series tags auto show it.

**Comment by gotson** [comment]
i'm sorry but i have a very difficult time understanding anything you write, and the videos showing a very little portion of the screen do not help.

**Comment by acer1204** [comment]
> i'm sorry but i have a very difficult time understanding anything you write, and the videos showing a very little portion of the screen do not help.

This is test video.
https://www.youtube.com/watch?v=a7Ma6mWXesM

Step 1.
the root folder in library tags only have "Aaaa" and "Bbbb".
Step 2.
I edit a book with add tag CCCC, them the  root folder tags auto add Cccc.
Step 3.
In left menu, if i select Aaaa or Bbbb tag, the list only show book with the same tag. it's work fine.
Step 4.
If i select the root folder tags, like click "Aaaa" or "Bbbb". it will show the all book, not Step 3 result.

sorry, my english is not good. you can see the video.

**Comment by gotson** [comment]
Thanks for the video, so what's the issue then?

**Comment by gotson** [comment]
I think you misunderstand what each action does.

The filter menu on the right will filter books in the series.

Clicking the tag in the series view will go to the parent library, and filter on series tags.

It works as expected.

**Comment by acer1204** [comment]
> I think you misunderstand what each action does.
> 
> The filter menu on the right will filter books in the series.
> 
> Clicking the tag in the series view will go to the parent library, and filter on series tags.
> 
> It works as expected.

ok, it's my misunderstand...

i think clicking the tag in the series and only show this series book with same tag is a good ideal...
it's relatively intuitive.

if go to the parent library, them the tag in the series is no difference.
because the tag is add in book, not in series or parent library.
that is my confused.

**Comment by gotson** [comment]
> if go to the parent library, them the tag in the series is no difference. (PS: click "Aaaa" and "Bbbb" show the same result)
> 
> because the tag is add in book, not in series or parent library. that is my confused.

yes, book tags are also aggregated at series level, and can be searched that way in the library view
