### ISSUE TITLE
How can I open more than six tabs? 

### ISSUE THREAD

**Issue by misakamisaka10086** [gotson/komga#1188]
### Describe your suggested feature

When I open five Komga comic tabs, the sixth tab fails to load the comic and only displays a Komga icon. However, when I close one of the first five tabs, the sixth tab starts to load the comic.
I wish to be able to load comics even when having more than five tabs open. Is there a solution to this issue?Do I need to configure certain parameters myself? Can anyone help me with this? Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Probably linked to the max number of SSE (server sent events) connection to the same domain allowed by your browser.
