### ISSUE TITLE
Support for comics in epub format

### ISSUE THREAD

**Issue by gotson** [gotson/komga#119]
For ebooks, please see #69: no support for ebooks in the foreseeable future.

---

Some people have comics in `epub` format, Komga could support those (Tachiyomi does in local mode for instance).

@The7thSage would you be able to share one of those comics with me ? Ideally one with pages out of order (you mentioned using Calibre to sort the pages), so i could address that directly if possible.

**Comment by reesink93** [comment]
I could share a file if it is still needed

**Comment by gotson** [comment]
> I could share a file if it is still needed

Yes please!

**Comment by reesink93** [comment]
Please tell me when you have it so I can disable the link. I don't want it shared more than needed.
https://cloud.reesink93.nl/s/ZGC7Z52Y6JffNHD

**Comment by gotson** [comment]
> Please tell me when you have it so I can disable the link. I don't want it shared more than needed.
> https://cloud.reesink93.nl/s/ZGC7Z52Y6JffNHD

Downloaded, thanks a lot. You can disable the share.

**Comment by reesink93** [comment]
Thanks, good luck

**Comment by gotson** [comment]
The `epub` format looks interesting. I had a look at the code from Tachiyomi, it's simple and easy.

The `epub` files also contain metadata, it would be interesting to be able to read that too and use it as a metadata provider.
