### ISSUE TITLE
Default account will be generated during scoop installation

### ISSUE THREAD

**Issue by protonXyz** [gotson/komga#1190]
### Steps to reproduce

1. scoop install komga. To install komga
2. open database.sqlite by SQLiteStudio.
In the user table, there are root@gamil.com field. The password is $2a$10$FRfBZ1xgJW50iLP5GibkwOtLZe7MUzufR5gpRCDhBw9gVZsH7NYNu
3. open http://localhost:25600 via chrome. Only login, no administrator account created

### Expected behavior

There is a button to create an administrator account when opening it for the first time.

### Actual behavior

The first time it is opened, there is only a login interface, such as changing the browser, deleting data, and reinstalling

### Komga version

1.3.0

### Operating system

Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
scoop is a 3rd party integration, not supported
