### ISSUE TITLE
option to disable password login if SSO login option(s) implemented

### ISSUE THREAD

**Issue by ckhordiasma** [gotson/komga#1197]
### Describe your suggested feature

I thought it would be nice if there was an option to completely disable password-based login if you have a single sign-on method configured and working. The option would preferably be exposed somewhere like `application.yml` so that the admin can undo the change if something isn't working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It would effectively cutoff all 3rd party apps as well as opds, since none of them support oauth2 login.

**Comment by BrianCArnold** [comment]
I'm kind of assuming a bit here, but apps don't actually use the login screen itself, do they? So as long as the API can still support simple auth, the login screen might still be able to just assume OAuth for every user?

**Comment by gotson** [comment]
I don't quite understand what you want to achieve. Disabling password Auth would prevent all 3rd party apps to use the api, effectively breaking them.

**Comment by ckhordiasma** [comment]
I think the other guy is saying that maybe an alternative is just to remove password based login as an option from the web login UI, but leave it enabled as an authentication method via API

**Comment by gotson** [comment]
> I think the other guy is saying that maybe an alternative is just to remove password based login as an option from the web login UI, but leave it enabled as an authentication method via API

But what would that achieve really?

**Comment by ckhordiasma** [comment]
The reason I was asking for this was to have the option to eliminate an entry point for brute force attacks ( I don't use any third party apps, only the web client). Having the login disabled but api still enabled doesn't really address that issue since the attacker could just use the api. 

However, it could still be useful for a different use case of wanting to force your users to use a certain authentication type to login to the web UI.

**Comment by gotson** [comment]
To handle brute force you should use specialized tools like cloudflare or fail2ban.

I understand that reducing the attack surface is part of it, but with the current state of the architecture it would imply a lot of work for not much gain.

**Comment by ckhordiasma** [comment]
No worries! Thanks for considering
