### ISSUE TITLE
Normalize sort title from comicinfo.xml

### ISSUE THREAD

**Issue by sonostrass** [gotson/komga#1199]
### Steps to reproduce

Before, thanks so much for this incredible tool I use for nearly 2 years 

Step 1 - add files with series title containing accents 
Step 2 - See how it's sorted. in Komga

### Expected behavior

I wrongly assumed this was solved in 0.109.1 version.
I would have liked the alphabetic order being respected as if there where no accent:

- é or É considered as E
- î or Î considered as I
- ç or Ç considered as C

And better, a feature to manage characters sorting (like force ignoring # as first title character)?

### Actual behavior

Wrong order in cards:
![image](https://github.com/gotson/komga/assets/63546790/a8ede312-40f2-4b83-b889-0e9f4ce0165e)

or in classification:
![image](https://github.com/gotson/komga/assets/63546790/7454fc4e-8009-4964-8d1f-e5c47117c139)

### Komga version

1.3.1

### Operating system

Windows 11

### Other details

Jar execution

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The name displayed on the card is not used for sorting. Check the sort title field.

**Comment by sonostrass** [comment]
Hi Gotson, 
Thanks for your hint.

All  my metadata comes from Comicrack comicsinfo.xml. Since this tag does not seem available, _Sort_ field in Komga is the same as title (Serie or book itself). 
I don't have any tool to mass change my whole collection, and even so, it seems imho pretty logic from here that alphabetical order is not impacted by accent...

All my gratitude again for your involvment!

**Comment by sonostrass** [comment]
Or I do a mass update directly in SQLite to update all sorting first letter based on my own rules.
Yeah. That's somehow a solution. I can manage this, but it's not very user-friendly.
And I hope I won't break something with such a database manipulation.

**Comment by gotson** [comment]
That's a comicinfo.xml limitation indeed, as it doesn't have a field for the sort title Komga uses it as is. I guess we could strip accents, similarly to what we do in folder names.

**Comment by sonostrass** [comment]
thanks a lot!
