### ISSUE TITLE
[Bug] Losing Authors information on update

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#120]
### Komga environment
- **OS**:  QNAP NAS Linux
- **Komga version**: v0.24.6
- [ ] **I am running Komga from the `jar`**
  - Java version: Java 8 installed
- [ ] **I have a problem in the web interface**
  - Browser (with version): Edge Chromium Canary and Chrome, both latest version

### Describe the bug
If Authors information have been set and you update later the Summary field, Authors information disappear. All fine if the information are set the other way around (summary first, then Authors). It doesn't happen only when filling up, but also when updating the Summary field...

### Expected behavior
Keep all Metadata information at any time even when other fields are updated

### Actual behavior
Loosing existing Authors Metadata when filling or updating Summary info after Authors information

Keep on doing the good job here !

Regards,

**Comment by gotson** [comment]
Confirmed on my end. It seems to be a problem on the backend, as the frontend is only sending modified fields (and all lock fields also). The authors field is not sent but still the information is considered present and empty, as such the backend removes it.
