### ISSUE TITLE
KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS not working

### ISSUE THREAD

**Issue by HeuristicPerson** [gotson/komga#1200]
### Steps to reproduce

I'm using a docker composer file with the following content about ignore directory patterns:

    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS="#recycle,@eaDir,@Recycle,noindex"

Then, I add the directory with my magazines. In there, I have directories with real files organised like:

    MAGAZINE_TITLE [noindex]
        YEAR
            Issues 001.pdf
            ...
            
For Komga, each magazine must be contained in a single directory. So, I create another directory in the same location without the "noindex" tag and I place there symlinks to all the files of the original directory. Hence, at the end of the process if have something along:

    magazine a
    magazine a [noindex]
    magazine b
    magazine b [noindex]
    ...

Then, I create a new library in Komga and I add the parent directory of all these magazine dirs as the root directory.

### Expected behavior

After the scan, only the contents of directories without [noindex] tag should be added to Komga library.

### Actual behavior

After the scan, Komga shows all contents, even the sub-dirs from noindex directories. The documentation for KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS states:

> A list of patterns to exclude directories from the scan. **If the full path contains any of the patterns, the directory will be ignored**. If using the environment variable you need to use a comma-separated list.

So, my understanding is the sub-directories inside the noindex directories should be ignored, hence this is a bug.

### Komga version

1.3.1-master

### Operating system

Docker image running under Linux.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can try to enable TRACE logs to see what's happening during the scan.

**Comment by HeuristicPerson** [comment]
Many thanks, gotson, the problem was in a very silly mistake... the quotes around the environment variable in the docker compose file. The log shows that by using quotes, the entire "list" is considered as a single pattern:

    2023-08-20T08:55:00.080Z  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Excluded patterns: ["#recycle, @eaDir, @Recycle, [noindex]"
    
By removing the quotes you get:

    2023-08-20T09:00:48.326Z  INFO 1 --- [org.springframework.jms.JmsListenerEndpointContainer#1-1] o.g.k.domain.service.FileSystemScanner   : Excluded patterns: [#recycle, @eaDir, @Recycle, [noindex]]]
    
And everything works as intended. I just read the .yaml documentation about quotes and it says that, in principle, quotes around values are not required in general but they should be used when, for example, square brackets are part of the value, which is my case.

**Comment by gotson** [comment]
> And everything works as intended. I just read the .yaml documentation about quotes and it says that, in principle, quotes around values are not required in general but they should be used when, for example, square brackets are part of the value, which is my case.

This is about yaml, not necessarily true about environment variables though. Glad you worked it out!
