### ISSUE TITLE
Scan all library (normal) VS (Deep) Cron problem

### ISSUE THREAD

**Issue by crocobc** [gotson/komga#1201]
### Steps to reproduce

Install and use last version of Komga.

Set a cron to scan library

### Expected behavior

New books should be added

### Actual behavior

No books adds

### Komga version

1.3.1

### Operating system

Ubuntu

### Other details

Hi there,

I update to last version of Komga.

I'm using a cron to add new books.

Like

`java -jar /opt/Komga/komga-0.162.0.jar --komga.libraries-scan-cron="0 0 * * * ?"`

But with the last version it's not working anymore.
I notice that i need to launch "Scan library (Deep)" for books to be added...

Is there a command line option i'm missing with this new version ?

How to perform deep scan with cron command line ?

Regards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You should try to understand why the books are not added. Most likely what you need is [force modified time](https://komga.org/docs/guides/libraries#force-directory-modified-time), but you should check the last modified time of your folders to make sure that is the root cause.

**Comment by crocobc** [comment]
Thanks for the reply.

Folders dates are not updated when i add books in it.
I tried with this option but no change. 

It's only happening when i add book to an existing serie...new folder with new serie is working great.

The only change i made are:

- update komga from 0.162 to 1.3.1.
- files were on an NTFS share and now are on Exfat share. (with full permission)

Any ideas ?

Thanks (this app is very good)

**Comment by gotson** [comment]
> I tried with this option but no change.

can you provide some details on what you did ?

**Comment by gotson** [comment]
can you check what is the last modified time of the book you added ? Does it actually reflect the data the book was added or not ?

**Comment by crocobc** [comment]
Ok maybe i found a hint.

Does the book i want to add must have a superior modified date then the last book added for the serie ?

I made 2 simple tests:

- Go to a serie copy/paste last book => SCAN ALL LIBRAIRIES => do not add the book
- Go to a serie add a book with superior modified date then the last one added =>Working !!!

Never add to check the last modified date with the previous versions...

**Comment by gotson** [comment]
If you used deep scan it forced a full update everytime, but it's costly and should only be used in specific cases.

If your filesystem does not put a last modified date as of now when you create or copy a file, you probably have a filesystem issue.

Similarly the parent folder should have its last modified date changed when a file within is created or modified. Specific cases for which this is not the case are cloud mounts like Google drive or Dropbox, or mergerfs.

You should really ensure your filesystem behaves properly.

**Comment by crocobc** [comment]
> If you used deep scan it forced a full update everytime, but it's costly and should only be used in specific cases.
> 
> If your filesystem does not put a last modified date as of now when you create or copy a file, you probably have a filesystem issue.
> 
> Similarly the parent folder should have its last modified date changed when a file within is created or modified. Specific cases for which this is not the case are cloud mounts like Google drive or Dropbox, or mergerfs.
> 
> You should really ensure your filesystem behaves properly.

OK i think i found the problem. Directory modified date is not updating when i put new books in it....

I will reformat partition with NTFS and get back to tell you (it's quite big). (it seems exfat is know to have this "bug"...)

**Comment by crocobc** [comment]
Hi there,

After formatting in NTFS all is working perfectly !

Thank you for helping me and for your responsiveness.

Best wishes
