### ISSUE TITLE
[Feature Request] Guest/Kiosk Mode

### ISSUE THREAD

**Issue by zachstultz** [gotson/komga#1202]
### Describe your suggested feature

An optional mode that the server owner can toggle that puts a "guest" button next to the sign in button, when clicked the guest is presented with the exact layout that a logged in new user is presented with, except they can't download or read anything.

It would allow a server owner to show a potential new user that is considering using your server what you have in your library and how komga works.

### Other details

Could be achieved by use of a global guest account, where the read and download buttons are automatically disabled, and such an account is shared by all users that use the guest button. (though this might not be the most proper implementation)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
No interest in doing so
