### ISSUE TITLE
Trouble running JAR behind Apache reverse-proxy subfolder

### ISSUE THREAD

**Issue by Gargravarr2112** [gotson/komga#1206]
### Steps to reproduce

This issue is related to #44, I think.

1. Configure Apache per issue #44 with subfolder "/komga" setting `ProxyPass/ProxyPassReverse` to localhost default port (25600), with or without Rewrite instruction
2. Configure Komga with `server.servlet.context-path="/komga"`
3. Attempt to access `<base URL>/komga`

### Expected behavior

Login/first setup page appears

### Actual behavior

Java HTTP 404 error appears (i.e. from Komga itself, not from Apache).

Attempting to navigate to <base URL>/komga/komga/ results in the page title being set to 'Komga' as expected (returns HTTP 200), but assets cannot be loaded as the context-path is set to '/komga', so all assets return HTTP 404.

This is confusing behaviour as (like the author of #44) I have set up many Apache reverse-proxy configurations and this does not happen.

Leaving out ProxyPassReverse does not change the behaviour.

### Logs

Komga produces no useful logs even when setting DEBUG log level, or when using /komga/komga/ as the URL. Log ends at 'Completed initialization'.

Apache logs:

```
<IP ADDRESS> - - [27/Aug/2023:12:47:45 +0100] "GET /komga/ HTTP/1.1" 404 1000 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0"
<IP ADDRESS> - - [27/Aug/2023:12:47:53 +0100] "GET /komga/komga/ HTTP/1.1" 200 1274 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0"
<IP ADDRESS> - - [27/Aug/2023:12:47:54 +0100] "GET /komga/css/chunk-vendors.2de540b6.css HTTP/1.1" 404 676 "https://<BASE URL>/komga/komga/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_
64; rv:109.0) Gecko/20100101 Firefox/117.0"
<IP ADDRESS> - - [27/Aug/2023:12:47:54 +0100] "GET /komga/js/chunk-vendors.e2a91e5e.js HTTP/1.1" 404 676 "https://<BASE URL>/komga/komga/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64
; rv:109.0) Gecko/20100101 Firefox/117.0"
<IP ADDRESS> - - [27/Aug/2023:12:47:54 +0100] "GET /komga/js/app.796e3a4d.js HTTP/1.1" 404 1000 "https://<BASE URL>/komga/komga/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.
0) Gecko/20100101 Firefox/117.0"
<IP ADDRESS> - - [27/Aug/2023:12:47:54 +0100] "GET /komga/css/app.d3e183d9.css HTTP/1.1" 404 1000 "https://<BASE URL>/komga/komga/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:10
9.0) Gecko/20100101 Firefox/117.0"
```

### Komga version

1.3.1

### Operating system

~~Devuan 4 (Debian 11)~~
Devuan 5 (Debian 12)

### Other details

Apache version 2.4.57-2
Java version 17.0.7

Accessing Komga via `http://<base URL>:25600` works as expected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga is working being different reverse proxies, with or without subfolder.

You haven't shared your komga config nor your apache config.

You should first try to get the setup working without the reverse proxy. 

You are saying:

> Accessing Komga via `http://<base URL>:25600` works as expected.

But that's contradictory with what you are trying to achieve.

**Comment by Gargravarr2112** [comment]
> You are saying:
> 
> > Accessing Komga via `http://<base URL>:25600` works as expected.
> 
> But that's contradictory with what you are trying to achieve.

You are correct, I realised that just now. If I have `server.servlet.context-path="/komga"` and try to access it directly on port 25600, then it does the same thing, HTTP 404. If I then navigate to http://<base URL>:25600/komga/ then it works as expected, the first-run page appears.

I have not added a Komga config file. I am running it via `java -jar komga-1.3.1.jar --server.servlet.context-path="/komga" --komga.config-dir=/srv/komga/store` (JAR file in `/srv/komga`).

Apache config basically matches that in #44 except for the default port. I have tried:
```RewriteRule ^/komga$ /komga/ [R]
<Location "/komga/">
    ProxyPass "http://localhost:25600/"
    ProxyPassReverse "http://localhost:25600/"
</Location>```

as well as

```ProxyPass /komga/ "http://localhost:25600/"
ProxyPassReverse /komga/ "http://localhost:25600/"```

Same behaviour with either.

**Comment by Gargravarr2112** [comment]
I just had a flash of inspiration and tried
```
RewriteRule ^/komga$ /komga/ [R]
<Location "/komga/">
    ProxyPass "http://localhost:25600/komga/"
    ProxyPassReverse "http://localhost:25600/komga/"
</Location>
```
Which does work as expected, I see the first-run page behind the reverse-proxy.

This is still not really the behaviour I expected.

**Comment by gotson** [comment]
> This is still not really the behaviour I expected.

Can you clarify?

**Comment by Gargravarr2112** [comment]
> > This is still not really the behaviour I expected.
> 
> Can you clarify?

All other `ProxyPass` directives I am using do not require passing the subfolder to the proxied application (i.e. `http://localhost:25600/komga/`), it is passed as the root (i.e. `http://localhost:25600/`).

**Comment by gotson** [comment]
> > > This is still not really the behaviour I expected.
> > 
> > 
> > Can you clarify?
> 
> All other `ProxyPass` directives I am using do not require passing the subfolder to the proxied application (i.e. `http://localhost:25600/komga/`), it is passed as the root (i.e. `http://localhost:25600/`).

That's honestly a question for the Apache community. If Komga works well on `http://localhost:25600/komga/` then it's not a Komga issue.

**Comment by Gargravarr2112** [comment]
Very well. Could you add this to the documentation please? Then I'll consider this issue closed.
