### ISSUE TITLE
[Bug] Number and Sort Number not kept when adding books into a Serie

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#121]
Komga environment
OS: QNAP NAS Linux
Komga version: v0.24.6
 I am running Komga from the jar
Java version: Java 8 installed
 I have a problem in the web interface
Browser (with version): Edge Chromium Canary and Chrome, both latest version

### Describe the bug
When adding a book to a Serie where Metadata have been set, the new book get Number and Sort Number one and move all others number by +1. This happens even if the Number and Sort Number are locked (another possible bug ?).

### Steps to reproduce
Add a book in a Serie where Metadata have been set

### Expected behavior
New book to be added as the last of the Serie not the first

### Actual behavior
New book added as the First of the serie. This change the whole numbering by 1 up

Best regards,

**Comment by gotson** [comment]
Could you provide the list of files in the folder before, and the name of the file you add?

Also if you could provide the json of `/api/v1/series/<seriesId>/books` before and after the operation.

**Comment by Flyingfufu** [comment]
At work right now, will provide something later today.

**Comment by Flyingfufu** [comment]
Let me try to put all in sequence.

I used an exiting serie of 3 books :
![Komga original](https://user-images.githubusercontent.com/45739159/77335871-08fa6080-6d27-11ea-964b-f0318480dc75.png)

Here  you can see that the numbering is locked (only the 1st one shown as exemple):
![Komga original locked](https://user-images.githubusercontent.com/45739159/77335939-262f2f00-6d27-11ea-85f0-231c50321de6.png)

I then removed the book #3 
![Komga intermediate](https://user-images.githubusercontent.com/45739159/77336993-98ecda00-6d28-11ea-82d6-58a73a416b53.png)

 Waited the server to update the list of books and put it back. The result is as follow :
![Komga after](https://user-images.githubusercontent.com/45739159/77336269-8f16a700-6d27-11ea-85c5-a8b1490d9514.png)

As requested, you have also the 2ea JSON files :
[Json before.txt](https://github.com/gotson/komga/files/4370470/Json.before.txt)
[Json after.txt](https://github.com/gotson/komga/files/4370472/Json.after.txt)

Did the same again but with both books numbering unlocked prior loading back the 3rd one, and here the result :
![Komga after unlocked](https://user-images.githubusercontent.com/45739159/77338804-25000100-6d2b-11ea-8e00-550683360a89.png)

and the associated JSON files :
[Json before unlocked.txt](https://github.com/gotson/komga/files/4370658/Json.before.unlocked.txt)
[Json after unlocked.txt](https://github.com/gotson/komga/files/4370644/Json.after.unlocked.txt)

Hope all is clear otherwise, feel free to ask for more details.

Best regards,

**Comment by gotson** [comment]
This is the expected behavior.

Your files are not sorted in directory, so when Komga performs a scan, the number is generated by alphabetical order of the file name, starting at 1. If the metadata.number and metadata.numberSort are not locked, they are updated also.

Your files in directory:
```
1940 Et si la France avait continue la guerre T3-iBooker.cbz
1940 Et si la France avait continue la guerre v1.cbr
1940 Et si la France avait continue la guerre v2.cbr
```

So the volume 3 gets number `1`.

Number and Sort Number are here to help with issues that cannot be properly ordered by filenames (for example Les Chroniques De La Lune Noire - Tome 0, which is to be read between Tome 14 and Tome 15, so using a Sort Number like `14.5` solves the issue).

For your case it would be much simpler to rename the files, and use the default behaviour of Komga, instead of trying to update the Sort Number manually.

Later on where there will be metadata providers from external sources, the metadata number will be retrieved from those sources and will override the number generated from the index of the file in the directory.

**Comment by Flyingfufu** [comment]
Right, got it... I was thinking that the latest addition date was taken into account somehow, not just the file name.
However, how to explain that the order go from ...v1 -> ...v2  to ...T3 -> ...v2 -> ...v1 ? Shouldn't' it go to ...T3 -> ...v1 -> ...v2 instead ?

This is a detail, so don't spend more time on it then, will wait on further development of the Metadata and make sure the file name will be correct in the folder in the meantime.

Appreciate your hard work.
Regards,

**Comment by gotson** [comment]
The order is correct.

Check the `number` field at the root of each book in the `json`, it's the index in the directory:
```
"url": "/share/Documents/Mes eBooks/BD/1940 Et si la France avait continue la guerre/1940 Et si la France avait continue la guerre T3-iBooker.cbz",
"number": 1

"url": "/share/Documents/Mes eBooks/BD/1940 Et si la France avait continue la guerre/1940 Et si la France avait continue la guerre v2.cbr",
"number": 3

"url": "/share/Documents/Mes eBooks/BD/1940 Et si la France avait continue la guerre/1940 Et si la France avait continue la guerre v1.cbr",
"number": 2
```

Looks correct to me.

---

On your first example, only the `V2` has the `numberSortLock` set to `true`, so the number is not updated and remains `1`. Number for the `V1` is computed at `2`, and updated in metadata. `T3` gets number `1`.

In your unlocked example, the `V2` gets number `3` and `V1` gets number `2`.

**Comment by Flyingfufu** [comment]
Got the whole mechanism understood now... Thanks for your time. As said, I will change the way I handle the storage and associated file naming convention on the server until the metadata importation is implementing.

Again, thanks a lot !
