### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Xsatc77** [gotson/komga#1212]
### Steps to reproduce

Installed using docker-compose script that is on the documentation page
Tried to open the webpage with port and it gave me an Unable to connect

### Expected behavior

I expected to see the new user login screen on the webUI

### Actual behavior

It opens an Unable to Connect error

### Logs

Attached log
[_komga_logs(5).txt](https://github.com/gotson/komga/files/12551577/_komga_logs.5.txt)

### Komga version

3.3

### Operating system

Ubuntu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment]
> FileNotFoundException: /config/artemis/journal/server.lock (Permission denied)

You have some kind of permissions error with your mounted storage. Need to fix that so that the application can write to the folder.

**Comment by Xsatc77** [comment]
It was the actually the user: 1000:1000 line in my compose
