### ISSUE TITLE
[Feature Request] Add reading direction to the OPDS feed

### ISSUE THREAD

**Issue by foux** [gotson/komga#1216]
### Describe your suggested feature

There exists [readingProgression](https://github.com/readium/webpub-manifest/tree/master/contexts/default#reading-progression-direction) in the default context of Readium Web Publication Manifest.
It would be great to add it to Komga OPDS feed, so that readers can retrieve reading direction set in Komga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's implemented in the new opds 2 feed, it will be available in the next release.
