### ISSUE TITLE
Take into account the mime types accepted by the page API via the Accept header.

### ISSUE THREAD

**Issue by hgourvest** [gotson/komga#1219]
### Describe your suggested feature

This request only concerns the following end point: /api/v1/books/{bookId}/pages/{pageNumber}

I would like this API to be able to return a page in PDF format if the document is a PDF and the mime type "application/pdf" appears first in the list of mime types accepted by the client in the Accept header.
for example:

`Accept: application/pdf, image/*`

This will allow me to continue to communicate with older versions of the server.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
