### ISSUE TITLE
[Feature Request] Redirect previous page after login

### ISSUE THREAD

**Issue by SaraSmiseth** [gotson/komga#122]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I go to a bookmark of a page (localhost/book/23413/read?page=81) and I'm not logged in. I get redirected to the login page. When I login I get to the mainpage.

### Describe the solution you'd like
Instead of redirecting to the mainpage I would like to be redirected to the page I initially wanted to see: localhost/book/23413/read?page=81

**Comment by gotson** [comment]
Which version are you using? It should be done already.

**Comment by gotson** [comment]
Actually it works when you are auto logged in using remember-me, not after going through the actual `/login` page.

Can you confirm you don't use remember me, and you have this behavior after you input the login/password on the login page?

**Comment by SaraSmiseth** [comment]
> Actually it works when you are auto logged in using remember-me, not after going through the actual `/login` page.
> 
> Can you confirm you don't use remember me, and you have this behavior after you input the login/password on the login page?

Yes. New version works. Thanks. That was very fast :+1:
