### ISSUE TITLE
Installation with installer fails on Windows

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1220]
### Steps to reproduce

1. Downloade Windows installer `komga.exe` from https://download.komga.org/
2. Run `komga.exe`
3. Allow it through Microsoft Defender SmartScreen
4. Let installer run

### Expected behavior

Komga should be installed without error

### Actual behavior

Get error

"Failed to install https://github.com/gotson/komga/releases/latest/download/komga.appinstaller due to error: Fehler 0x800B0109: Das Stammzertifikat der Signatur im App-Paket oder -Bündel muss vertrauenswürdig sein."

Translation 

"Failed to install https://github.com/gotson/komga/releases/latest/download/komga.appinstaller due to error: Fehler 0x800B0109:
The root certificat of the signature in the app-packet or -bundle needs to be trustworthy."

### Komga version

1.4.0

### Operating system

Windows 11

### Other details

![grafik](https://github.com/gotson/komga/assets/56667539/d652e5b8-9e41-4549-bcbd-0768e4d02bc8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Arwalk** [comment]
Can report the same error here, on windows 10

**Comment by DieselTech** [comment]
Just a few questions to help troubleshoot @PhilippKammann @Arwalk 

When you first run the .exe does a UAC prompt come up asking you to run powershell as admin? 

Are you using a microsoft account?

Do you have admin on the computer your trying to install komga on?

**Comment by PhilippKammann** [comment]
> When you first run the .exe does a UAC prompt come up asking you to run powershell as admin?
- No prompt. Running the .exe as Admin directly gives the same error
> Are you using a microsoft account?
- Yes
> Do you have admin on the computer your trying to install komga on?
- Yes 
> As a test, can you try using the .appinstaller version and see if you still get the same error?
- Get a different certificate error (0x800B010A)
![grafik](https://github.com/gotson/komga/assets/56667539/2d4ccd98-8632-4237-8bef-4a91b93d63b9)

**Comment by gotson** [comment]
@PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.

There are 2 possible workarounds:
1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
2. Set your computer to English and try again, the installer should work.

**Comment by DieselTech** [comment]
Also note an easy way to install the cert is by downloading the MSIX file and going to file properties, then the digital signatures tab. Click on signature in the list, then details. Click on `View Certificate` and then `Install Certificate`. The install wizard will pick where it needs to go.

**Comment by Arwalk** [comment]
> @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> 
> There are 2 possible workarounds:
> 
> 1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> 2. Set your computer to English and try again, the installer should work.

Installing the cert did not fix the problem for me.

**Comment by gotson** [comment]
> > @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> > There are 2 possible workarounds:
> > 
> > 1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> > 2. Set your computer to English and try again, the installer should work.
> 
> Installing the cert did not fix the problem for me.

please share details of what the symptom is, what you have done, and what is the symptom afterwards. Are you using a non-English locale ?

**Comment by mwnu** [comment]
> > @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> > There are 2 possible workarounds:
> > 
> > 1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> > 2. Set your computer to English and try again, the installer should work.
> 
> Installing the cert did not fix the problem for me.

Try this: 
- Click "Install Certificate"
- Storage location Select "Local Computer" and click Next
- Select "Place all certificates in the following store" and then click "Browse"
- Select "Trusted Person" and click "OK", then click "Next" button
- Click the Finish button to perform the certificate installation

**Comment by PhilippKammann** [comment]
> @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> 
> There are 2 possible workarounds:
> 
>     1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> 
>     2. Set your computer to English and try again, the installer should work.

Solution 1 worked for me, but I think it should "just work" for the general user

**Comment by gotson** [comment]
> > @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> > There are 2 possible workarounds:
> > ```
> > 1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> > 
> > 2. Set your computer to English and try again, the installer should work.
> > ```
> 
> Solution 1 worked for me, but I think it should "just work" for the general user

Yeap, once conveyor fixes the bug it will work fine.

**Comment by Arwalk** [comment]
> > > @PhilippKammann it is a bug in Conveyor, the tool used to package the desktop app. The installer should install the certificate, but doesn't because your locale is set to something else than English.
> > > There are 2 possible workarounds:
> > > 
> > > 1. Download and install the [cert](https://github.com/gotson/komga/releases/download/v1.4.0/komga.crt) yourself. Install it to Trusted People.
> > > 2. Set your computer to English and try again, the installer should work.
> > 
> > 
> > Installing the cert did not fix the problem for me.
> 
> please share details of what the symptom is, what you have done, and what is the symptom afterwards. Are you using a non-English locale ?

Don't mind me, i'm retarded and can't read, i didnt install it in "Trusted People". This fixed it now. Thanks for your support.

**Comment by SoccerNerd** [comment]
I've installed the certificate but am still getting the Smartscreen dialog and am not even given the option to run the program

<img width="398" alt="image" src="https://github.com/gotson/komga/assets/61528248/ef3f2d6b-e07e-447b-af84-69d01e2dcd6a">

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
