### ISSUE TITLE
OPDS Errors with Panels iOS app since v1.4.0

### ISSUE THREAD

**Issue by tevd** [gotson/komga#1221]
### Steps to reproduce

Follow the guide at https://komga.org/docs/guides/panels.
Notable difference: my server runs behind a reverse proxy, so traffic runs through HTTPS.

### Expected behavior

I should be able to browse the catalog and stream a CBZ file.

### Actual behavior

When attempting to browse the library beyond the initial overview, the app is unable to fetch the required data.
Instead, a log message is generated with a PageNotFound error. (see attached sanitized log excerpt)

Note that this issue is resolved by downgrading to 1.3.1, so it seems unlikely that the Panels app is actually sending an invalid request.

### Logs

WARN 1 --- [io-25600-exec-4] o.s.web.servlet.PageNotFound             : No mapping for GET /opds/v1.2/https:/example.com/opds/v1.2/series
WARN 1 --- [io-25600-exec-9] o.s.web.servlet.PageNotFound             : No mapping for GET /opds/v1.2/https:/example.com/opds/v1.2/libraries

### Komga version

1.4.0

### Operating system

Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This needs to be reported to panels and checked by them.

Opds can use a mix of urls, absolute or relative, and relative url are quite complex and can be relative to the current browsing url.

The opds client needs to handle this complexity at their end.

I am closing this as the opds feed is valid, but if panels dev find anything incorrect with the feed I'll happily look into it.

**Comment by gotson** [comment]
It should be safe to downgrade Komga from 1.4.0 to 1.3.1 until Panels can respond / fix.

**Comment by foux** [comment]
> It should be safe to downgrade Komga from 1.4.0 to 1.3.1 until Panels can respond / fix.

I confirm that I did this morning (even several time to reproduce the issue) without problems.

**Comment by tevd** [comment]
The downgrade does indeed work, I also switched a bunch of times to initially troubleshoot the issue.

I have seen some posts come by on the Panels community forum, but no official response yet. If there is no response soon I'll send them an email about it, as the issue appears to be in the way they build the request url. (The single slash after https: seems to indicate that they're trying to use the entire URL as the path component of the request)

**Comment by apastuszak** [comment]
I tried this in Chunky also and I cannot get the OPDS to work. But I never tried an older version in Chunky, so I can't say that it wokred with 1.3.1.

**Comment by foux** [comment]
> I tried this in Chunky also and I cannot get the OPDS to work. But I never tried an older version in Chunky, so I can't say that it wokred with 1.3.1.

It works with Chunky with 1.3.1. But as chunky isn't maintained anymore, don't expect any changes.

**Comment by azwildcat11** [comment]
Sorry as I'm a bit new to this, how do you find the old version 1.3.1 download file?  I have 1.4 installed, and it's broke my feed to Panels.  Thanks.

**Comment by gotson** [comment]
> Sorry as I'm a bit new to this, how do you find the old version 1.3.1 download file? I have 1.4 installed, and it's broke my feed to Panels. Thanks.

Depends how you installed it?

**Comment by foux** [comment]
Just as an FYI, some OPDS clients works totally fine with 1.4.0. FOr example FBReader has no issue.

**Comment by victorBaro** [comment]
We will take a look as soon as possible, totally seems like a client issue 👍 

@tevd thanks [for this](https://github.com/gotson/komga/issues/1221#issuecomment-1714244444), very helful

**Comment by victorBaro** [comment]
Yesterday I released a couple of testflight versions that should fix this issue. Will release publicly to the store as soon as it's reviewed & approved by apple
