### ISSUE TITLE
Publish Desktop app as Flatpack on Linux

### ISSUE THREAD

**Issue by ntimo** [gotson/komga#1224]
### Describe your suggested feature

Currently the desktop app is only avaible as .deb file which makes it hard to uninstall on other distros e.g. Fedora. Publishing the app as flatpak will make it easier to update and also possible to install on multiple distros:

https://flatpak.org/

Docs: https://docs.flatpak.org/en/latest/first-build.html

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This depends on Conveyor, which doesn't support it. You can vote for it here: https://github.com/hydraulic-software/conveyor/issues/4
