### ISSUE TITLE
rar / cbr files are not counted in total book count.

### ISSUE THREAD

**Issue by sukarn-m** [gotson/komga#1230]
### Steps to reproduce

1. Add non-solid cbr files to a series.
2. Check that the files are added in Komga, Komga can analyse the file, generate cover, and no issues are reported in Media Management.
3. Check the number of books reported in the series.

### Expected behavior

The number of files should be counted if they can be read by Komga.

### Actual behavior

Komga ignores all cbr files even if they can be read using Komga, and even if page streaming works. If a series contains only cbr files, Komga reports "No book" in place of the number of books that are present. If the total book count is set manually, Komga reports the number of books as "0 / [total number of books]".

### Komga version

1.4.0-HEAD

### Operating system

Docker on Linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Logs or screenshots?

**Comment by sukarn-m** [comment]
Screenshots attached. I'm trying to manually create a rar4 file that would result in this same output. Komga has been installed and running on this home server for over a year now, and has gone through multiple updates in that time period. The problematic files and series have existed throughout that time in the library. But, I've only recently started organizing the library, so I never noticed it before.  

Series and book identification has been redacted in the screenshots.

Screenshots showing "No book":
![Screenshot 2023-09-19 220324](https://github.com/gotson/komga/assets/10946339/57b9d901-2c11-4b95-bfa2-b8b90d58cb83)

Screenshot showing "0 / [total book count]":
![Screenshot 2023-09-19 220354](https://github.com/gotson/komga/assets/10946339/fd57158c-bed7-4b09-9ab3-69cf253f1ea6)
  
Screenshot showing information about a sample rar file (obtained from WinRAR):
![Screenshot 2023-09-19 220952](https://github.com/gotson/komga/assets/10946339/e7d6a66c-f827-4bdb-a94f-92d68aecce44)

**Comment by protofolius** [comment]
Try running a deep scan of your library , after the deep scan has finished , restart komga .
