### ISSUE TITLE
Rather want to see chapters instead of books

### ISSUE THREAD

**Issue by miitchel** [gotson/komga#1233]
### Describe your suggested feature

I have a comics library, and a manga library. For comics library I want to see books when I click on the series, but for manga I want to see the chapters of the volumes/books when I go into the series.

What I have now:
Manga library:
     Manga 1:
          Volume 1
          Volume 2
          Volume 3
     Manga 2:
          Volume1
          etc..

What I want:
Manga library:
     Manga 1:
          Chapter 1
          Chapter 2
          Chapter 3
          Chapter 4
          Chapter 5
     Manga 2:
          Chapter 1
          Chapter 2
          Chapter 3
          etc..

I have looked through many different settings, but I just can't find anything like it that does what I want.
I want this because on Tachiyomi all the manga libraries let you read in chapters instead of volumes/books, but my library lets you read in volumes/books.

I would really appreciate the help.

### Other details

I run komga v1.4.0-HEAD using docker.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by PhilippKammann** [comment]
If the book file you put in the folder is `Manga Volume 1`, then Komga will show `Manga Volume 1` and if it's `Manga Chapter 1`, then Komga will show `Manga Chapter 1`. So providing the files you want is up to you.

**Comment by miitchel** [comment]
So if most of my files are volumes, will there be no way for me to tell komga to read it as chapters inside the volume?

**Comment by PhilippKammann** [comment]
For Komga 1 File = 1 book. It can't split up a volume file into multiple chapter entries

**Comment by gotson** [comment]
> So if most of my files are volumes, will there be no way for me to tell komga to read it as chapters inside the volume?

How would Komga do that if your files don't have this information to begin with? Magic?

**Comment by noaione** [comment]
If you get your manga volume from a certain website, I have a script/tools that can auto split a volume into each chapters according to their filename.

https://github.com/noaione/nao-manga-rls#autosplit

There is also a manual version that use your own regex/page numbering if it does not follows Daiz/Madokami naming schema.

**Comment by miitchel** [comment]
Thank you so much, I'll look into this in a bit
