### ISSUE TITLE
"Unread" filter should only show unread series and not "in progress" series

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1234]
### Describe your suggested feature

If you activate the "Unread" filter in the series view, Komga will show unread series and "in progress" series. 
I would like if it only showed actually unread series as "in progress" has a it's own filter, that you can activate.

In API terms:

- Currently the filter to this
  - Unread: `/api/v1/series?read_status=UNREAD&read_status=IN_PROGRESS`
  - In Progress: `/api/v1/series?read_status=IN_PROGRESS`
  - Unread & In Progress: `/api/v1/series?read_status=IN_PROGRESS&read_status=UNREAD&read_status=IN_PROGRESS`

- And I would like
  - Unread: `/api/v1/series?read_status=UNREAD`
  - In Progress: `/api/v1/series?read_status=IN_PROGRESS`
  - Unread & In Progress: `/api/v1/series?read_status=UNREAD&read_status=IN_PROGRESS`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Is that a dashboard question or an api question?

**Comment by PhilippKammann** [comment]
Dashboard. About the filtered view in the Series Browse tab.

The api calls I wrote are what the Dashboard calls for these filters

**Comment by gotson** [comment]
This is actually a feature and done on purpose.

**Comment by PhilippKammann** [comment]
But then checking the box "Unread" shows the same as checking "Unread" & "In Progress". Shouldn't two different filter settings do something differently? And there is no possible way to filter "unread, but not in progress" in the webui browse tab currently

**Comment by gotson** [comment]
it was done as part of #526, the behaviour is modelled around other apps of the same kind.

For example in Plex, if you select "unplayed" as the filter, it would still show all the series for which you have watched some episodes.

**Comment by PhilippKammann** [comment]
My request would be to have a filter to show only totally unread series. Currently thats not possible in the series browse view.

"In progress" is already a separate toggle in the ui, so it would be nice of I could toogle its inclusion in the "unread" filter and not have it always be part of it.

The api already works that way, meaning `api(unread) ≠ webui(unread)` which adds further confusion for me

**Comment by gotson** [comment]
> My request would be to have a filter to show only totally unread series. Currently thats not possible in the series browse view.

what's the use case ?

**Comment by PhilippKammann** [comment]
I wanted to read someting _fresh_ and filtered for "unread", but still needed to manually shift trough all my "in progress" series. 
If I had wanted to read them, I would had just resumed them from On Deck

**Comment by gotson** [comment]
I did some git archeology, and #526 was implemented at the time there was only a single "Unread" filter in both the book and series views. The "In Progress" and "Read" filters have been added later on.

Let's harmonize the filters in the webui :)

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
