### ISSUE TITLE
an error occurred while trying to retrieve directory listing 

### ISSUE THREAD

**Issue by barto107** [gotson/komga#1235]
### Steps to reproduce

when i'm trying to add a new library but i've got this message "an error occurred while trying to retrieve directory listing ", the files are stored on a second HD called « DATA »

### Expected behavior

a new library should have been created. It works well when i'm adding a libray with files stored on my imac HDD.

### Actual behavior

When I want to create a new library with files on a second HD called « DATA » I’ve got a message « an error occurred while trying to retrieve directory listing » . Do you know how to solve this problem ?

### Komga version

1.4.0 (2023-09-11)

### Operating system

OS: Mac OS 13.2

### Other details

* [ x] I am running Komga from the jar
    * Java version: jre-8u381-macosx-x64
*   I have a problem in the web interface
    * [ x] Browser (with version): Google Chrome Version 117.0.5938.88 (Build officiel) (arm64)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please provide logs

**Comment by barto107** [comment]
here my logs hope it will help to find a solution to this issue because Komga is a great application and it works very well on my windows PC but not on my imac unfortunetaly
[komga.log](https://github.com/gotson/komga/files/12708063/komga.log)
[komga.log.2023-09-23.0.gz](https://github.com/gotson/komga/files/12708064/komga.log.2023-09-23.0.gz)

**Comment by gotson** [comment]
> here my logs hope it will help to find a solution to this issue because Komga is a great application and it works very well on my windows PC but not on my imac unfortunetaly [komga.log](https://github.com/gotson/komga/files/12708063/komga.log) [komga.log.2023-09-23.0.gz](https://github.com/gotson/komga/files/12708064/komga.log.2023-09-23.0.gz)

nothing useful in there unfortunately.

usually the issue you mention will be related to folder permissions

**Comment by barto107** [comment]
I tried to play with the permissions but nothing conclusive for the moment

**Comment by barto107** [comment]
Figured it out. The issue comes from the way mac treats programs. Just go to "Apple Logo" --> "System Preferences" --> "Security and Privacy" --> "Full Disk Access"

**Comment by barto107** [comment]
komga has been installed on external drive, and mac trats programs was the issue.
