### ISSUE TITLE
Support for sidecar covers in WEBP format

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1238]
### Describe your suggested feature

Similiar how you can add a `cover.png` or `cover.jpg` to a series folder to set a poster for the series, it would be nice if `cover.webp` would be supported as well.

In the same vein, support for `book 123.webp` to set a poster for a book through a sidecar file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
