### ISSUE TITLE
Multiple Alternate Series Management

### ISSUE THREAD

**Issue by phatalx** [gotson/komga#1239]
Komga seems to be unable to use the AlternateSeries tag properly. 

### Steps to reproduce

Steps to reproduce:
1. Use ComicRack to fetch ComicVine metadata on an issue that is part of two different story arcs.
2. The AlternateSeries stores the two titles as a string separated by a comma.
3. Import your issue in Komga

### Expected behavior

Komga should be able to recognize that the field contains two different entries separated by a comma and place the issue in the respective read lists. 

### Actual behavior

However, it currently creates a new read list with the full AlternateSeries tag with the multiple titles concatenated.
![image](https://github.com/gotson/komga/assets/15606205/9a2febbb-2498-4016-a2e7-c48ffac77ae8)

### Komga version

1.4.0

### Operating system

Tested on both Windows 11 Pro and on Linux truenas 5.15.107+truenas

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is [expected behaviour](https://komga.org/docs/guides/scan-analysis-refresh/#read-lists):

> The AlternateSeries or StoryArc elements will be used to create a read list with that name, or add the book to an existing read list with that name.

> If the AlternateNumber element is set, it will be used to position the book in the read list.

That field is not supposed to contain multiple series.
