### ISSUE TITLE
Server to client communication

### ISSUE THREAD

**Issue by gotson** [gotson/komga#124]
This is a meta issue to list all the areas where being able to send events from the server to the clients would bring value.

The mode of transport/communication is not defined at this stage.

- [x] library is added/removed/updated: to update the sidebar of the webui if a library is added from another client
- [x] series or book is added/removed/updated: to update the dashboard or browsing grid dynamically, would be mostly useful while an analysis is running
- [x] background tasks like scan, analysis or metadata fetching are running: to give visual feedback in the webui
- [x] for background tasks started by a user action, show a toast when it is finished (book import)

**Comment by ethanpil** [comment]
Also: Last read page. To keep all readers in sync, internal and external

**Comment by gotson** [comment]
> Also: Last read page. To keep all readers in sync, internal and external

This will be covered in #25
