### ISSUE TITLE
Is it possible to read the contents of metadata.opf when scanning libraries to be able to import calibre libraries?

### ISSUE THREAD

**Issue by skyrim663** [gotson/komga#1243]
### Describe your suggested feature

First of all, I would like to thank the author for developing the software which provides a great online reading experience.

I used calibre-web to import and manage my books before moving to komga. Calibre saves the original title in the metadata.opf in the same directory as the .cbz when creating the library, i.e., the <dc:title></dc:title> field, and after importing the .cbz filename is changed so that komga uses the modified title when scanning.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
No, calibre is not supported. You should export the calibre metadata into the epub files, which komga can read.

**Comment by gotson** [comment]
For cbz you should use something like comicinfo.xml

**Comment by skyrim663** [comment]
> 对于 cbz，您应该使用类似 Comicinfo.xml 的内容

Should Comicinfo.xml be placed in the same directory as .cbz or does it have to exist in the .cbz file?

**Comment by skyrim663** [comment]
Can komga read Comicinfo.xml in the same directory as .cbz?

My books are stored in a cloud drive and exporting them all would be a huge disaster. If it is possible to read Comicinfo.xml in the directory that would make metadata editing much faster.

**Comment by gotson** [comment]
> Can komga read Comicinfo.xml in the same directory as .cbz?

No, that doesn't exist in the wild.

---

You could use something like komf to add metadata to your books directly in Komga.
