### ISSUE TITLE
Komga doesn’t scan according to application.yml on MacOS

### ISSUE THREAD

**Issue by DaveAlton** [gotson/komga#1244]
### Steps to reproduce

Set the application.yml file in the config directory. The file is in the same directory as the db file. 

```
komga:
  libraries-scan-cron: "0 0 * * * *"
```
  
Restart Komga, and it still only scans every 8 hours. 

### Expected behavior

Komga should automatically scan every hour. 

### Actual behavior

It scans every 8 hours, the default amount. 

### Komga version

1.4.0

### Operating system

MacOS 12.6.9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That property is going away in the next release, will be replaced by a library setting.

**Comment by DaveAlton** [comment]
I'm really happy to hear that. I saw a merged pull request for adding settings but I didn't see anything for the scan frequency. I'm happy to have that migrated there now. Any estimate for the next release?

**Comment by gotson** [comment]
Hopefully this week :)
