### ISSUE TITLE
Support for PDF Hyperlinks

### ISSUE THREAD

**Issue by wellspokenman** [gotson/komga#1246]
### Describe your suggested feature

Request for a feature to support self referencing links in PDF books. Many technical and cooking books refer to other sections and provide hyperlinks to these sections. Support for this in the komga web reader and the tachiyomi komga extension would make working with these book types much easier. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
As of now pdf are processed only as image. There's no plan to have a full pdf viewer for now.

**Comment by gotson** [comment]
> the tachiyomi komga extension

Tachiyomi also have no plans for supporting PDF

**Comment by wellspokenman** [comment]
That's a pity, for my use case. The alternative would be ePub support, which I think is just images only with no plans of change for the same reason of comic focus.

**Comment by gotson** [comment]
> That's a pity, for my use case. The alternative would be ePub support, which I think is just images only with no plans of change for the same reason of comic focus.

epub will actually come at some point, i have been working on the various pieces to support it in the past months. Tachiyomi won't support it though.

For your PDF, you're probably better off just downloading the file and reading with the system PDF reader.
