### ISSUE TITLE
Make prefixing number on books in a series optional

### ISSUE THREAD

**Issue by FlyveHest** [gotson/komga#1247]
### Describe your suggested feature

This has been somewhat discussed before in #686, but i'd like to "re-open" the request, as my usecase is not the same as the previous poster.

I have a large-ish collection of primarily european books, and all relevant files (books) already have a prefixed number in the filename.

This is due to two things, the first, and most important, I have a couple of friends that access the files directly, and secondly, I just like having the numbering be part of the filename.

Seeing that the numbes is actually a string in the metadata, and I can type more or less what I want, an easy solution would be to just leave it blank, but this isn't possible.

So, having a toggle on the series, possibly in the General part, that disables showing the number would be a great quality-of-life improvement for me, and I can see that at least a couple of people chimed in on the original request.

In the end, this is more of an aesthetic thing, but I do have multiple series where I am missing a book or two, and the numbering compared to the files are off, which looks somewhat silly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by FlyveHest** [comment]
No, I found out about the one-shots, and I have multiple one-shot folders and they work great.

But ahh, I hadn't considered editing the name of the book directly.  This is quite a task, though, is there a possibility for some bulk editing actions, maybe directly in the database if I stop the server?

**Comment by gotson** [comment]
> But ahh, I hadn't considered editing the name of the book directly. This is quite a task, though, is there a possibility for some bulk editing actions, maybe directly in the database if I stop the server?

There's an API, so you can script whatever you need.

> It might be an idea to be able to skip prefixed numbers when adding a library to start with? Or maybe be able to supply a regex that could filter the filename? (^\d{1,} ) for instance.

That's too much of an edge case in my opinion.

**Comment by FlyveHest** [comment]
> There's an API, so you can script whatever you need.

Looks like everything I need to batch-change booknames are available there, i'll make a script to remove the imported numbering from the names in Komga.

I still think it would be nice to be able to apply some form of transformation logic on library creation, I can't be the only one who was used numbering on the filenames prior to using Komga, but I can accept that its probably not all that common (or, peoples files have metadata from some other source, which none of mine had)
