### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by DaveAlton** [gotson/komga#1248]
### Describe your suggested feature

I would love to have my libraries scanned when Mylar adds new files. If Komga added a webhook I could call, then I could put the URL into Mylar and have everything scanned each time a book is downloaded. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by PhilippKammann** [comment]
There is an API for Komga. Just send a POST request to the `/api/v1/libraries/{libraryId}/scan` endpoint to make a scan

**Comment by DaveAlton** [comment]
Thanks. I had read through the documentation and found that, but I don’t see a way to authenticate in the same URL. Do I need to add a URL parameter with a token or something?  On Wed, Oct 4, 2023 at 2:12 PM, Philipp Kammann ***@***.***> wrote:  
There is an API for Komga. Just send a POST request to the /api/v1/libraries/{libraryId}/scan endpoint to make a scan

**Comment by gotson** [comment]
https://komga.org/docs/api/rest/#authenticating

**Comment by DaveAlton** [comment]
Right. And that’s what I’m asking for. A singular URL with minimal authentication. www.mykomgainstance.com/scan?auth=mytoken  On Wed, Oct 4, 2023 at 2:30 PM, Gauthier ***@***.***> wrote:  
https://komga.org/docs/api/rest/#authenticating

**Comment by DaveAlton** [comment]
Ultimately I want one URL I can insert into whatever comic fetcher, and have it scan my libraries. I can’t do headers or cookies.   On Wed, Oct 4, 2023 at 2:34 PM, Dave Alton ***@***.***> wrote:     Right. And that’s what I’m asking for. A singular URL with minimal authentication. www.mykomgainstance.com/scan?auth=mytoken  On Wed, Oct 4, 2023 at 2:30 PM, Gauthier ***@***.***> wrote:  
https://komga.org/docs/api/rest/#authenticating

**Comment by gotson** [comment]
https://serverfault.com/a/371918 check this out

**Comment by DaveAlton** [comment]
Amazing! Thanks so much. I added the authenticated URL in the Slack URL form in Mylar. It scanned my library as soon as it downloaded a new comic! So appreciated.   On Wed, Oct 4, 2023 at 5:37 PM, Gauthier ***@***.***> wrote:  
https://serverfault.com/a/371918 check this out
