### ISSUE TITLE
Can not read ComicInfo.xml in subfolder in cbz archive

### ISSUE THREAD

**Issue by FlyveHest** [gotson/komga#1250]
### Steps to reproduce

Have a cbz comic where images are stored in a folder in the cbz archive.

Place ComicInfo.xml file in same folder.

### Expected behavior

Komga should be able to parse ComicInfo.xml

### Actual behavior

Komga doesn't detect ComicInfo.xml.

If I move the ComicInfo.xml file to the root of the archive, Komga can the file as expected.

### Komga version

0.150.0

### Operating system

Docker

### Other details

Komga has no problem reading the images in the subfolder in the cbz file, so the comic can be read just fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by PhilippKammann** [comment]
A `ComicInfo.xml` has to be at the root of the archive. That is part of the specification and not a bug. Otherwise you run into problems like having two `ComicInfo.xml`s in one archive

**Comment by gotson** [comment]
@PhilippKammann is right, that's part of the spec.
