### ISSUE TITLE
wrong parsing collections from Group Series metadata with comma

### ISSUE THREAD

**Issue by sonostrass** [gotson/komga#1251]
### Steps to reproduce

1. In a book metadata, insert a Book Series with a comma
![image](https://github.com/gotson/komga/assets/63546790/68f74d1f-10fb-4314-a936-f889169f975d)
2. import into Komga
3. Collections are duplicated based on comma
![image](https://github.com/gotson/komga/assets/63546790/6f7db6a4-8d42-4147-9d30-8c8ff11e9568)

### Expected behavior

Only one Collection should be created here: "Before Comma, After comma"
Character used in Comicrack to add multiple entries is the semi-colon.

Therefore, comma shouldn't be used as separator for collection parsing

Let's suppose we need to create collections per author.
Bedetheque scrapper retrieve author names as first + last: René Goscinny
For easiest sorting, best practices leads to write last name then first name, separated by a comma: Goscinny, René

### Actual behavior

2 collections are created instead of one.

### Komga version

1.5.1

### Operating system

Windows 11

### Other details

Jar version

By the way, the link to FAQ in Issue report template is broken
![image](https://github.com/gotson/komga/assets/63546790/f8b4a242-cbfb-4021-9e82-05dde7b803cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Character used in Comicrack to add multiple entries is the semi-colon.

This is the first time I ever hear about this.

The accepted standard is the comma : https://anansi-project.github.io/docs/comicinfo/documentation#seriesgroup

**Comment by gotson** [comment]
> Let's suppose we need to create collections per author.

Side note but that's not really the best use case. Komga supports author filtering, creating collections for an author is not the right way to filter by author.

**Comment by sonostrass** [comment]
Mmmm.

It seems I'm awfully wrong here. Let's forget about this issue which is not one.
But, the filtering does not give a visual list of available author occurence (what I tried to achieve).
I suppose I'll have to find another way.

Thanks for your wise notice.
