### ISSUE TITLE
I can't use my domain with port in opds

### ISSUE THREAD

**Issue by meishild** [gotson/komga#1254]
### Steps to reproduce

1. use opds to opds/v2/catalog or opds/v1.2/catalog url。
2. return data with port.

### Expected behavior

Can you customer config or get url port to return opds？
like: http://test.com:3322/pds/v2/catalog 
return: 
"links": [
        {
            "rel": "self",
            "href": "https://test.com:3322/opds/v2/libraries"
        },
        {
            "title": "Home",
            "rel": "start",
            "href": "https://test.com:3322/opds/v2/catalog",
            "type": "application/opds+json"
        },
        {
            "title": "Search",
            "rel": "search",
            "href": "https://test.com:3322/opds/v2/search{?query}",
            "type": "application/opds+json",
            "templated": true
        }
    ],

### Actual behavior

With out port only have domin.

### Komga version

v1.5.1-master

### Operating system

Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Do you have a reverse proxy in front?

**Comment by meishild** [comment]
No, I can't use nginx as the frontend, because my domain name needs use port，Can you add a configuration to set the external port?

**Comment by gotson** [comment]
it works on my tests, so i guess there must be something different in your setup.

Can you clarify how the whole thing is setup on your side, including router / dns etc ?

In the sample you provide, you are using https, how is this configured for Komga if you are not using a reverse proxy ?

**Comment by meishild** [comment]
Oh, by the way, I'm using a Synology NAS DS1621+ and have configured a proxy. I have configured it to use the HTTPS port 4333. The content returned after requesting the address is as follows:
https://comic.test.com:4333/opds/v1.2/catalog

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<feed xmlns="http://www.w3.org/2005/Atom">
<id>root</id>
<title>Komga OPDS catalog</title>
<updated>2023-10-17T10:20:33.832633579+08:00</updated>
<author>
<name>Komga</name>
<uri>https://github.com/gotson/komga</uri>
</author>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="self" href="https://comic.test.com/opds/v1.2/catalog"/>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="start" href="https://comic.test.com/opds/v1.2/catalog"/>
<link type="application/opensearchdescription+xml" rel="search" href="https://comic.test.com/opds/v1.2/search"/>
<link type="application/opds+json" rel="alternate" href="https://comic.test.com/opds/v2/catalog"/>
<entry>
<title>Keep Reading</title>
<updated>2023-10-17T10:20:33.832792781+08:00</updated>
<id>keepReading</id>
<content>Continue reading your in progress books</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/keep-reading"/>
</entry>
<entry>
<title>On Deck</title>
<updated>2023-10-17T10:20:33.832816262+08:00</updated>
<id>ondeck</id>
<content>Browse what to read next</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/ondeck"/>
</entry>
<entry>
<title>All series</title>
<updated>2023-10-17T10:20:33.832832092+08:00</updated>
<id>allSeries</id>
<content>Browse by series</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/series"/>
</entry>
<entry>
<title>Latest series</title>
<updated>2023-10-17T10:20:33.832846982+08:00</updated>
<id>latestSeries</id>
<content>Browse latest series</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/series/latest"/>
</entry>
<entry>
<title>Latest books</title>
<updated>2023-10-17T10:20:33.832862162+08:00</updated>
<id>latestBooks</id>
<content>Browse latest books</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/books/latest"/>
</entry>
<entry>
<title>All libraries</title>
<updated>2023-10-17T10:20:33.832879742+08:00</updated>
<id>allLibraries</id>
<content>Browse by library</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/libraries"/>
</entry>
<entry>
<title>All collections</title>
<updated>2023-10-17T10:20:33.832897133+08:00</updated>
<id>allCollections</id>
<content>Browse by collection</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/collections"/>
</entry>
<entry>
<title>All read lists</title>
<updated>2023-10-17T10:20:33.832911703+08:00</updated>
<id>allReadLists</id>
<content>Browse by read lists</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/readlists"/>
</entry>
<entry>
<title>All publishers</title>
<updated>2023-10-17T10:20:33.832947473+08:00</updated>
<id>allPublishers</id>
<content>Browse by publishers</content>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://comic.test.com/opds/v1.2/publishers"/>
</entry>
</feed>`

it't not port with href.

**Comment by gotson** [comment]
It seems your reverse proxy may not be sending the proper forwarding headers to Komga, to handle the port the request would need to contain a `X-Forwarded-Port` header.

**Comment by meishild** [comment]
Thank you, I have enforced the X-Forwarded-Port on Synology, and it is now working.
