### ISSUE TITLE
PDFs streaming PDF binary pages instead of images

### ISSUE THREAD

**Issue by DaveAlton** [gotson/komga#1262]
### Steps to reproduce

It looks like the server is not behaving like expected. 

This is an example of a streaming URL 
`https://[server_domain]/opds/v1.2/books/0BSERXJ3JF6AW/pages/0?zero_based=true`

M Komga server is returning 

```json
{
  "timestamp": "2023-10-20T17:37:04.182+00:00",
  "status": 400,
  "error": "Bad Request",
  "message": "Page number does not exist",
  "path": "/opds/v1.2/books/0BSERXJ3JF6AW/pages/0"
}
```

When it's a PDF. I tried tweaking the URL to  `https://[server_domain]/opds/v1.2/books/0BSERXJ3JF6AW/pages/1?zero_based=true`
and it responds, but the response is not an image. It returns binary data that seems to be a PDF binary becuase the data starts with 
```
%PDF-1.4
%öäüß
1 0 obj
<<
/Type /Catalog
/Version /1.4
/Pages 2 0 R
>>
...
```

[OPDS PSE](https://github.com/anansi-project/opds-pse/blob/master/v1.2.md) only accepts `jpeg`, `png` and `gif` as a response. So even if the page index issue is solved, the returning data is still wrong. 

### Expected behavior

PDF page streaming should return `jpeg`, `png` or `gif`

### Actual behavior

Seems to be streaming a PDF binary

### Komga version

1.6.2

### Operating system

MacOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Which client are you using, and what request headers is it sending?

**Comment by DaveAlton** [comment]
I’m using Panels. I’m unsure what the headers are. I initially filed a ticket with them and they were actually the ones that did this troubleshooting. They then referred me to file a ticket with you.   On Fri, Oct 20, 2023 at 9:32 PM, Gauthier ***@***.***> wrote:  
Which client are you using, and what request headers is it sending?

**Comment by gotson** [comment]
Thanks for the details, I'll look into it.
