### ISSUE TITLE
"LocalizedSeries" Title for a Series in Manga Manager not Appearing in Komga

### ISSUE THREAD

**Issue by obsidiest** [gotson/komga#1263]
### Describe your suggested feature

The LocalizedSeries Title in Manga Manager does not appear in Komga:

![Untitled-1](https://github.com/gotson/komga/assets/147662259/20d8ee1a-73f2-472d-84b0-2cd254cfa783)

![Screenshot 2023-10-20 at 14-53-23 Komga - NARUTO](https://github.com/gotson/komga/assets/147662259/0da5d72f-f570-48d1-8f0f-66fdf687f66f)

In contrast the localizedseries title for the same series/files do appear in Kavita:

![Screenshot 2023-10-20 at 14-53-38 Kavita - NARUTO Details](https://github.com/gotson/komga/assets/147662259/1652993f-45ee-4d58-bb3d-0124e15479e4)

(to be clear the localizedseries title I assigned for this series is just for testing)

### Other details

At the moment it appears one would need to manually add an alternative title in Komga for series with different original language and localized names.

Please add the ability to use localizedseries title instead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you elaborate on what Manga manager write in the (I suppose) comicinfo.xml?

**Comment by obsidiest** [comment]
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo>
  <Series>NARUTO</Series>
  <LocalizedSeries>Ninja Story</LocalizedSeries>
  <AgeRating>X18+</AgeRating>
  <Title>Unison Sign</Title>
  <Web>https://manga4life.com/read-online/Naruto-Digital-Colored-Comics-chapter-699.html</Web>
  <Number>699</Number>
  <Manga>Yes</Manga>
  <LanguageISO>en</LanguageISO>
  <PageCount>21</PageCount>
</ComicInfo>


As you can see in the photos as well, Komga doesn't show the  "LocalizedSeries" information, while Kavita does.

**Comment by obsidiest** [comment]
> <?xml version='1.0' encoding='utf-8'?>
<ComicInfo>
  <Series>NARUTO</Series>
  <LocalizedSeries>Ninja Story</LocalizedSeries>
  <AgeRating>X18+</AgeRating>
  <Title>Unison Sign</Title>
  <Web>https://manga4life.com/read-online/Naruto-Digital-Colored-Comics-chapter-699.html</Web>
  <Number>699</Number>
  <Manga>Yes</Manga>
  <LanguageISO>en</LanguageISO>
  <PageCount>21</PageCount>
</ComicInfo>

**Comment by obsidiest** [comment]
![Untitled-1](https://github.com/gotson/komga/assets/147662259/bd95cc79-871e-4312-90fb-b9cb3d33fbf6)

**Comment by gotson** [comment]
> ` <LocalizedSeries>Ninja Story</LocalizedSeries>`
> 
> As you can see in the photos as well, Komga doesn't show the "LocalizedSeries" information, while Kavita does.

Because that's not part of the spec, see https://github.com/anansi-project/comicinfo/issues/6
