### ISSUE TITLE
Configuration file suggestions

### ISSUE THREAD

**Issue by kofzhanganguo** [gotson/komga#1264]
### Describe your suggested feature

I am a Windows user. I hope that the Windows version can set some configuration parameters in the console of the web page, such as port number, URL, etc. I created the application.yml file and placed it in C:\Users\Administrator\AppData\Local\Komga In the folder, the port number I modified also doesn't work.

### Other details

![image](https://github.com/gotson/komga/assets/32073931/61bfcac9-477a-4221-96bf-e24642720ef1)

For example, in this server option, you can set detailed parameter settings such as port number and custom URL, instead of letting users create configuration files themselves. The main reason is that most users will not create specific configuration files.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you provide your custom configuration file, and which komga version you are on?

**Comment by gotson** [comment]
Also what do you mean by "custom url"?

**Comment by kofzhanganguo** [comment]
komga-1.6.2-windows-amd64

![image](https://github.com/gotson/komga/assets/32073931/70ee7280-045c-4bf4-8190-35f086dcf68e)

For example, parameter settings like Kavita can be set in the web console.

![image](https://github.com/gotson/komga/assets/32073931/90561a04-935e-4e05-be4a-aa0a06580fd3)

**Comment by kofzhanganguo** [comment]
It would be great if our Komga could set detailed parameters through the web console.

**Comment by gotson** [comment]
Your config file appears incorrect.

**Comment by kofzhanganguo** [comment]
Therefore, I hope that the web console can set the parameters of the configuration file, which will be simpler and more intuitive. Otherwise, most users will not know how to operate the configuration file.

**Comment by gotson** [comment]
> Therefore, I hope that the web console can set the parameters of the configuration file, which will be simpler and more intuitive. Otherwise, most users will not know how to operate the configuration file.

Well you need to read the page and follow what it says.

**Comment by kofzhanganguo** [comment]
How should I change my port number on Windows? How should the configuration file be created? Even if I follow the official help document, I still cannot modify the port number.
