### ISSUE TITLE
Tachiyomi Extension incorrectly throwing 401 HTTP code on successful logins

### ISSUE THREAD

**Issue by rg9400** [gotson/komga#1266]
### Steps to reproduce

1. Install Tachiyomi and Komga's extension for it
2. Open up Komga to API connections
3. Set up logging for Komga's HTTP Connections
4. Configure the right credentials for Komga
5. Access Komga via Tachiyomi
6. Validate the HTTP status codes as 401 in the logging even if the authentication is successful for Komga

### Expected behavior

HTTP codes should not be 401 as this can trigger various security measures such as fail2ban. 

### Actual behavior

I noticed my IPs suddenly getting banned because my logs thought this successful authentication was actually unauthorized

### Logs

NGINX logs
```
<REDACTED> - - [24/Oct/2023:17:57:37 -0500] "GET /komga/api/v1/tags HTTP/2.0" 401 134 "-" "TachiyomiKomga/0.14.6-6116"
<REDACTED> - - [24/Oct/2023:18:11:49 -0500] "GET /komga/api/v1/libraries HTTP/2.0" 401 139 "-" "TachiyomiKomga/0.14.6-6116"
```

Komga logs for same time
```
2023-10-24T17:57:36.204-05:00  INFO 1 --- [task-136] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=<redacted>, email=<redacted>, ip=<redacted>, userAgent=TachiyomiKomga/0.14.6-6116, success=true, error=null, dateTime=2023-10-24T17:57:36.204445510, source=Password)
2023-10-24T17:57:37.241-05:00  INFO 1 --- [task-133] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=<redacted>, email=<redacted>, ip=<redacted>, userAgent=TachiyomiKomga/0.14.6-6116, success=true, error=null, dateTime=2023-10-24T17:57:37.241241050, source=Password)
```

### Komga version

v1.6.2-master

### Operating system

Docker

### Other details

Komga extension version: 1.4.50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's normal. The Tachiyomi extension uses an interceptor to send basic Auth only when unauthorized is received.

There aren't any proper hooks in the extension framework to perform authentication before the extension will start calling the API.

**Comment by rg9400** [comment]
> That's normal. The Tachiyomi extension uses an interceptor to send basic Auth only when unauthorized is received.
> 
> There aren't any proper hooks in the extension framework to perform authentication before the extension will start calling the API.

Thanks, this makes sense. I will carve out Komga from this log and use the Komga log itself to determine failed authentications
