### ISSUE TITLE
Feature not working properly

### ISSUE THREAD

**Issue by taiwan-king** [gotson/komga#1268]
### Steps to reproduce
Account Setting & Server Setting Authentication Activity

Traditional Chinese will always fail to display.

### Expected behavior

The Traditional Chinese should display properly, not show a spinning circle constantly.

### Actual behavior

The Traditional Chinese should display properly, not show a spinning circle constantly.

### Komga version

v1.6.4

### Operating system

win10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
What do you mean by a spinning circle ? Can you share a screenshot or video ?
