### ISSUE TITLE
[Feature Request] Add postgres database engine

### ISSUE THREAD

**Issue by foux** [gotson/komga#1269]
### Describe your suggested feature

If I'm not mistaken, today Komga can only use an sqlite database.

It would be great to also be able to use other database engines, for exemple Postgres

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is not in the plans.
