### ISSUE TITLE
[Bug] Chrome (specifically) Pages in comic only displays white screen

### ISSUE THREAD

**Issue by The7thSage** [gotson/komga#127]
### Komga environment
- **OS**: 
   - *Server*: Ubuntu 19.10 (whatever is latest)
   - *Client*: Windows 10
* **Komga version**: v0.24.10
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: OpenJDK version "11.0.6" 2020-1-14
- [X] **I have a problem in the web interface**
  - Browser (with version):  
    - Problematic: Chrome, Version 80.0.3987.162 (Official Build) (64-bit)
    - Working: *New* (Chromium) Microsoft Edge,  Version 83.0.472.0 (Official build) canary (64-bit)
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:  N/A Phone Screen Damaged
  - Tachiyomi extension version: N/A

### Describe the bug
Every page procs a ``No mapping for GET (/page here)`` message

 Primary User Account Displays a white screen on read.   ``No mapping for GET /book/6408/read`` appears on the command-line, 
alternate and guest accounts just end up with an "ERR_CONNECTION_REFUSED" Message.
Of course, Chromium Edge, (and alternate users) acts as the above, expected Behavior

### Steps to reproduce
This happened when I updated, skipping multiple minor versions versions (from 0.24.6 to 0.24.10). 

### Expected behavior
1. Enter Login screen
2. Find book to read
    b. Click page icon
3. First page, UI (including back button) and settings appear.

### Actual behavior
1. Enter Login Screen
2. Find book to read
    b. Click page icon
3. Delivered to a page without anything, just default site background color

### Additional context
Any other user, including Incognito, works just fine.

#### I have attached Html code for the problematic and asymptomatic  pages, Don't judge the comic title, might even modify it too.
[Komga Working HTML.html.txt](https://github.com/gotson/komga/files/4418296/Komga.Working.HTML.html.txt)
[Komga Problem HTML.html.txt](https://github.com/gotson/komga/files/4418365/Komga.Problem.HTML.html.txt)

**Comment by gotson** [comment]
All the logs of the following form are normal, if they refer to a resource from the webui (so nothing that starts with `/api` or `/opds` etc).

```
2020-04-01 19:38:17.806  WARN 5187 --- [http-nio-8080-exec-3] o.s.web.servlet.PageNotFound             : No mapping for GET /login
```

There is no resource handler on the server side for those paths, and the server forwards those errors to `/` instead, which serves the `index.html` which is what's required to load the SPA in the browser.

Howerver those logs should only appear when you are not navigating within the SPA, meaning:
- pressing <kbd>F5</kbd> to reload the page in your browser
- opening a link in a new tab, or duplicate a tab
- input an address different from `/` directly in the browser URL bar

Are you doing anything of that kind?

Before going any further, can you try in Incognito mode in the browser that doesn't work?

Could you set the `logging.level.web` to `DEBUG`, and try to perform a few actions? For each action, i would need:
- the Komga logs
- record from the Chrome dev tools Network tab, and then export the HAR file

Actions:
- find a book to read, and click the read icon
- from the page `/book/<id>/read`, perform a page refresh

The HAR file may contain sensitive data, you can encrypt it with a password and provide the password via DM to me on Discord.

Thanks

**Comment by The7thSage** [comment]
## Solution:
It appears that some older cached data, (ie, SessionID, reading direction, fit, fitheight, rtl, etc.) must have broken the Javascript SPA (and, thus the reader) when loaded.  Clearing site cache allows for newer, working data to be created.
### Clearing your site-specific cached data
#### Steps:
1. Copy the IP address of your Komga server
2. Go to `chrome://settings/siteData`  which controls data cache per-site
   - (not `chrome://settings/content/cookies` which _wipes out everying for a period of time_ **you have been warned**)
3. Paste IP into search bar
   - Click the entry for IP
5. Click either "Remove All" or individually click every x under this site
6. Reload Komga Client
