### ISSUE TITLE
Cannot unpack sqlite libraries to temp on windows 11 virtualized app

### ISSUE THREAD

**Issue by bulletproof2k** [gotson/komga#1282]
### Steps to reproduce

Launching the application.

### Expected behavior

org.springframework.context.ApplicationContextException: Unable to start web server   @ org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164)

### Actual behavior

![Без имени (1)](https://github.com/gotson/komga/assets/1818579/d13d71ed-efe8-42e0-91c8-c5b8cb890c87)

### Komga version

1.7.1

### Operating system

Windows 11

### Other details

The same error occurred during the first installation, but from the second time the application began to run normally. Apparently, after today's update, something broke. 
Reinstalling did not solve the problem.
Tried several official installation methods the same error.

used KomgaInstaller.exe

[komga.log](https://github.com/gotson/komga/files/13252241/komga.log)

Today the application was working fine, but after restarting it began to give this error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by bulletproof2k** [comment]
[komga.log](https://github.com/gotson/komga/files/13252241/komga.log)

**Comment by gotson** [comment]
Thansk for the logs, it's very useful.

The issue comes from the sqlite library which unpacks the dll to the temp directory. On windows 11 the windows app is virtualized, and its temp directory apparently does not exist by default, so the unpack fails.

I'll try to find a fix. In the meantime if you create the temp directory it should work: `C:\Users\victo\AppData\Local\Packages\Komga_fj8s550zp45ee\LocalCache\Local\Temp`

**Comment by bulletproof2k** [comment]
At the moment, the problem has been solved, I am grateful for the hint with its solution.
