### ISSUE TITLE
Komga for Windows cannot be started anymore after the latest update.

### ISSUE THREAD

**Issue by Jamerrone** [gotson/komga#1283]
### Steps to reproduce

Start the application.

### Expected behavior

The application should start up like it used to.

### Actual behavior

It crashes on start-up:
![Screenshot 2023-11-04 120621](https://github.com/gotson/komga/assets/16142485/c8b74bac-9e7e-4d20-af46-576cdcd6db58)

### Komga version

1.7.1

### Operating system

Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you get the full logs?

Also check #1282

**Comment by Jamerrone** [comment]
@gotson Ok, I somehow missed that issue, and yes, that did solve the issue for me. Kind of strange because I have used the Windows version since the first release without any issue, so I guess it can randomly break? Do you still need the logs, or is it enough that the tip fixed the issue?

**Comment by gotson** [comment]
I have the logs from the other issue so I know what's wrong.

However I don't know why it worked before. It could be that the java temp dir previously did not point toward the virtualized folder. That could be a change introduced by Conveyor, the tool that packages Komga desktop.
