### ISSUE TITLE
application/x-7z-compressed

### ISSUE THREAD

**Issue by FrenchGithubUser** [gotson/komga#1285]
### Describe your suggested feature

I have some files that generated this error : 

`Media type is not supported | application/x-7z-compressed`

Is this planned to be supported or should I convert the files I have ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
See FAQ: https://komga.org/docs/faq/#media-type-applicationx-7z-compressed-is-not-supported

This is not planned.
