### ISSUE TITLE
Collection covers are small

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#1288]
### Steps to reproduce

I'm unclear on what's causing it but I can see it on the Collections page

### Expected behavior

![image](https://github.com/gotson/komga/assets/32607317/d1e3c24a-4907-443b-bf15-40879655618e)

### Actual behavior
The images aren't taking up the full space. They are served this way from the server.
![image](https://github.com/gotson/komga/assets/32607317/54371895-592b-4fc1-91a8-4dcac6dac727)

### Logs

Happy to provide logs, but I'm not sure which part is useful or which parts to post. Do you just want my full latest log file?

### Komga version

1.7.1

### Operating system

Win 11

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Check the size of the thumbnails composing the mosaic. You can see the sizes in the book/series edit dialog, poster tab.

What's you configured thumbnail size? 

Komga will not upscale images, and will use the configured thumbnail size to generate mosaics.

So if you have configured the thumbnail size at 1200, and you have a series thumbnail that is 300px wide, it could be smaller than the required 600px wide image to be placed in 1 corner.

**Comment by kanjieater** [comment]
It would be nice to address this if we could make them all flush regardless of the thumbnail size but I realize then you might have to force small images to be too big or big images to be smaller. I'll close this non-bug for now that I get what's going on, thanks for the explanation.
