### ISSUE TITLE
Add batch size or queuing 

### ISSUE THREAD

**Issue by kctec** [gotson/komga#129]
For large libraries and under powered servers the current thread model creates many hibernate objects.  With no way to dispose of these objects until the process completes hibernate holds on to them creating a memory issue.  You should set the batch size on how many object to take async at a time or better yet use an in memory queue to work on each incoming object discreetly  and not doing them in the primary handler.  Let the handler queue the work.

**Comment by gotson** [comment]
First, could you please use the issue templates when creating issues?

Second, i don't understand what you are saying. You are pointing at a solution instead of a problem. Please explain the problem in detail, i will decide which solution is best to solve it.

**Comment by kctec** [comment]
Sure feel free to delete this issue.  Sounds like you guys got this covered.  Just I noticed that hibernates object cache it was managing never cleared and processing slowed as it did a library scan.  Once it hits the JVM max memory it slows to a crawl.  But you guys handle this any way you want.

**Comment by kctec** [comment]
Also sorry I didn't follow the process just started playing with the source the other day.

**Comment by gotson** [comment]
If you are talking about the hibernate second level cache, it's managed by hibernate. There are some limits, but with large libraries they get exhausted and entries evicted. That shouldn't particularly slow the analysis process though.

Changing the way the async works wouldn't change that anyhow. 

If you have more details of an issue, please share.
