### ISSUE TITLE
Windows Intallation Error

### ISSUE THREAD

**Issue by king0mar** [gotson/komga#1291]
### Steps to reproduce

Just downloaded it from Microsoft Store and Opened

### Expected behavior

Komga should be installed without error

### Actual behavior

![image](https://github.com/gotson/komga/assets/104761523/0daede18-ee65-46f2-9b37-4a4534232088)

### Komga version

1.7.2

### Operating system

Windows 11

### Installation method

Microsoft Store

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by king0mar** [comment]
> Did you actually check the link provided in the error message ? From what i've seen It's a microsoft issue with delta updates.

I got "App installation failed with error message: Deployment Add operation with target volume C: on Package Komga_1.7.2.0_x64__fj8s550zp45ee from:  (komga-1.7.2.x64.msix)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)"

**Comment by gotson** [comment]
Can you clarify whether the app is installed from download.komga.org? It seems to be the case from the log error, but you mentioned the Microsoft store in the ticket.

**Comment by king0mar** [comment]
> Can you clarify whether the app is installed from download.komga.org? It seems to be the case from the log error, but you mentioned the Microsoft store in the ticket.

It's from MS Store

**Comment by gotson** [comment]
If it was from the ms store it would download from the Microsoft hosted files not from github.

**Comment by king0mar** [comment]
> If it was from the ms store it would download from the Microsoft hosted files not from github.

The initial error is what got from the MS Store installation

**Comment by gotson** [comment]
Well that's weird.

This error is DO_E_DOWNLOAD_NO_PROGRESS (0x80d02002). Download of a file saw no progress within the defined period.

Nothing we can do about it, files are hosted on github, and github is slow.

Best you can do is retry. Normally the ms store app will download from Microsoft but it seems for you it's not, though I have no idea how/why.

**Comment by king0mar** [comment]
> Well that's weird.
> 
> This error is DO_E_DOWNLOAD_NO_PROGRESS (0x80d02002). Download of a file saw no progress within the defined period.
> 
> Nothing we can do about it, files are hosted on github, and github is slow.
> 
> Best you can do is retry. Normally the ms store app will download from Microsoft but it seems for you it's not, though I have no idea how/why.

I've tried that about 4 times now, same error

**Comment by gotson** [comment]
you can try to disable [delta updates](https://learn.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-settings#allow-clients-to-download-delta-content-when-available)

**Comment by gotson** [comment]
The files are now hosted on Backblaze B2 which should be faster than Github.
