### ISSUE TITLE
Parameter readDate API read-progress

### ISSUE THREAD

**Issue by suppo77** [gotson/komga#1292]
### Describe your suggested feature

at the moment the API for updating the reading status of a book allows the passage of only two parameters (number of pages read, and whether reading has been completed). Would it be possible to add an additional parameter to specify the date the reading was completed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I have implemented the Readium Progression API to mark epub progress in 20799ad1964d84a88a535124087506057822a34e. It is compatible with Divina and PDF books, you can use the following minimal payload to mark progress:

`PUT /api/v1/books/{bookId}/progression`

```json
{
  "modified": "2022-12-15T08:39:59.682Z",
  "device": {
    "id": "string",
    "name": "string"
  },
  "locator": {
    "href": "",
    "type": "",
    "locations": {
      "position": 124
    }
  }
}
```
