### ISSUE TITLE
Wrong Colors when using WEBP images in cbz

### ISSUE THREAD

**Issue by IndySE** [gotson/komga#1294]
### Steps to reproduce

I try WEBP images inside a CBZ. The Thumbnail and the OPDS Stream have wrong Colors. Everything has a yellow shade. The Webreader shows the right Colors. 

[JPG.zip](https://github.com/gotson/komga/files/13341693/JPG.zip)
[WEBP.zip](https://github.com/gotson/komga/files/13341694/WEBP.zip)
![Example](https://github.com/gotson/komga/assets/122036677/845e8b38-7de4-463d-8dc8-ec5c35127e52)

### Expected behavior

The JPG and WEBP Image should look the same

### Actual behavior

The WEBP Images show weong colors

### Komga version

1.7.2

### Operating system

Linux with Docker

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Thanks for the report. I have raised this in https://github.com/haraldk/TwelveMonkeys/issues/864 as Komga is using a third-party library for WebP.

The NightMonkeys webp plugin decodes the images correctly. I may include the NightMonkeys webp plugin in Komga, and use it if the native library is present, and else fallback to TwelveMonkeys.

**Comment by gotson** [comment]
Komga will now use the native library if present, however i could not bundle the lib in the docker image, as the Ubuntu repo only have an outdated version dating before the critical WebP CVE.
