### ISSUE TITLE
Add mysql support / migrate flyway to liquibase

### ISSUE THREAD

**Issue by kctec** [gotson/komga#130]
So I really didn't dig the in memory H2 approach.  I modded the project to include the MySql connector and set Hibernate to synchronize the  DDL.  Now the project running on 1 pi uses a mysql running on another basically halving the memory footprint making it viable for undersized server deployments.  The fly migration script is not ideal and we  may want to think about utilizing a DB agnostic apporach like liquibase.

**Comment by gotson** [comment]
I have no plan to support MySql or to use Liquibase
