### ISSUE TITLE
add multiple tags at once

### ISSUE THREAD

**Issue by shionryuu** [gotson/komga#1304]
### Describe your suggested feature

Input multiple tags separated by spaces like `異世界 冒険 集英社` and press enter can add 3 tags.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please provide more details, this is not sufficient.

**Comment by gotson** [comment]
press `TAB` instead of space, that will add 3 tags
