### ISSUE TITLE
[Feature Request] Preview when share a book 

### ISSUE THREAD

**Issue by Dragoopai** [gotson/komga#1305]
### Describe your suggested feature

When I share a link to a book on social media (Discord, twitter, Signal) I get no preview of the book. I was expecting the cover and the title in the preview. In general a share button would be  nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That kind of feature is up to the place where you share it, not to Komga.

**Comment by chrgue** [comment]
I think there are two things missing to allow this with Komga:
* set proper meta data according to https://ogp.me/
* allow site to fetch this meta data even there are unauthorized

The "place" you are referring already has the feature but Komga is not compatible with it.

Hope it make more sense now.

**Comment by gotson** [comment]
All of Komga's apis are behind Auth and there's no plan to change that.

**Comment by chrgue** [comment]
It would may work even the APIs is protected. But I realized something else. Komga uses a SPA approach, right? It does not render that much on the server side. So even you would like to at the meta data into the page for unauthorized users you would have a hard time to do to so.

Anyway, thanks for your time.

**Comment by gotson** [comment]
> It would may work even the APIs is protected. But I realized something else. Komga uses a SPA approach, right? It does not render that much on the server side. So even you would like to at the meta data into the page for unauthorized users you would have a hard time to do to so.
> 
> Anyway, thanks for your time.

yes, the fact that the API is behind auth, and that the client is a SPA would make it difficult. It would need to have a dedicated shared URL, which would not be behind auth, and would be static HTML.

TBH i don't see the use case for that, since Komga is about your own collection, or sharing with a limited number of people in your inner circle.

**Comment by Dragoopai** [comment]
Oh I have this very often. I share a links with my wife on Signal Messenger. Actually I am her notificator if I added new books. 😁

What would also be very nice if this notifications found be sent by the app itself. I know huge feature request but now at least you know my use case.
