### ISSUE TITLE
On Deck / Keep Reading sections

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#131]
I saw that you've referenced Plex as a source on inspiration. Is something similar to the "on deck" and "keep watching" sections planned for Komga?
- [x] Keep Watching - (Keep Reading?) Comics that have been started and not finished yet. I assume this is linked with the "reading progress" feature (#25 ).
- [x] On Deck - Showing what is the next comic in any series that have been started.
This is something that was well implemented in Kuboo maybe something to review and try to implement in Komga.

BTW - Great work and really appreciate all your effort. It's good to have this great alternative to Ubooquity.

**Comment by gotson** [comment]
Yes, i would like to implement those features.

Keep reading will be linked to read progress indeed.

For On Deck i will have to find what's the best way to pick what to show.

**Comment by gerroon** [comment]
I was just going to suggest this too. Having a list of recently opened/read books on the dashboard would be so great. Sometimes it is harder to find the book again and again. 

Jellyfin has these for movies like keep watching, recently watched thing and it is very useful.
