### ISSUE TITLE
Better EPUB web page turning and general suggestions for future

### ISSUE THREAD

**Issue by wanestar** [gotson/komga#1310]
### Describe your suggested feature

From what I can tell there is no next page button yet on the webUI. It would be quite nice to be able to click the dark space to move to the next page.  (PC and Mobile Browser)

- Also on IOS Swiping seems to move to the next page, but this is quite awkward as it often moves the page up and down, before moving. Again Making a tap or click on the left or right side screen(left to go back, right advance)  would be awesome! like Apple Books or the Kindle apps. 

- Also If it's possible I think scrolling the entire EPUB at once would be a cool option, even though I know it's not conventional it would make reading the books far easier. 

- Another cool feature that's probably pretty simple would be how many pages are left in the chapter, I quite like seeing this on the Apple books app.

Thanks for supporting EPUB! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> From what I can tell there is no next page button yet on the webUI.

There is:
<img width="399" alt="Screenshot 2023-11-29 at 11 21 36" src="https://github.com/gotson/komga/assets/2139133/b7ac05e3-1dcf-45c7-8b49-591c219cd2a0">



> * but this is quite awkward as it often moves the page up and down

I don't quite understand, can you provide some kind of video of that behaviour?

> * Again Making a tap or click on the left or right side screen(left to go back, right advance)  would be awesome! like Apple Books or the Kindle apps.

It's planned for future versions.

> * Also If it's possible I think scrolling the entire EPUB at once would be a cool option, even though I know it's not conventional it would make reading the books far easier.

It's not really possible. Epubs are made of multiple "resource" files (HTML files), so there's a need to move to the next one, which needs to be loaded from the server too.

You can use the Vertical Scroll mode for something closer to that.

> * Another cool feature that's probably pretty simple would be how many pages are left in the chapter, I quite like seeing this on the Apple books app.

It's already showing at the bottom, see first screenshot.

**Comment by gotson** [comment]
Fixed in 2f0f94dc531ca8eb1633018e2c6ecd3c2e1a5151
