### ISSUE TITLE
Option to Lock Posters

### ISSUE THREAD

**Issue by RWoof** [gotson/komga#1313]
### Describe your suggested feature

I use komf to fetch posters/covers, but sometimes it picks the wrong one, or picks an English cover for a Japanese book, even though the library is set to Japanese language. For the most part it works well and does help, so I'd like the ability to continue using komf to fetch covers, but to lock those covers that I later replace manually. Right now, if I add manual covers after komf, then I add a new file to the directory (new chapter or volume was released), komf will scan again and reset all the covers back to the ones it finds, undoing the manual ones I selected. Other metadata settings have locks but I'd like to be able to lock posters as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Seems to be a komf issue tbh.

**Comment by RWoof** [comment]
> Seems to be a komf issue tbh.

I can repost the issue there but if we can lock other metadata, why not posters as well? Let me know if you prefer I close this and open an issue with komf instead (or as well as). Thank you for the quick reply!

**Comment by gotson** [comment]
Once a poster is manually selected, Komga will not change it. Which is a similar behaviour to metadata locking.

I suppose komf is not looking at the poster type and always set the new one. Instead it should check the poster source and act accordingly.

**Comment by RWoof** [comment]
> Once a poster is manually selected, Komga will not change it. Which is a similar behaviour to metadata locking.
> 
> I suppose komf is not looking at the poster type and always set the new one. Instead it should check the poster source and act accordingly.

Thank you for explaining the process, I wasn't sure if komf had a way to check if a poster was manually set or automatically set. I'll post the issue in the komf github.
