### ISSUE TITLE
WebReader don't track my progress

### ISSUE THREAD

**Issue by BeeTwenty** [gotson/komga#1315]
### Steps to reproduce

1. start a new book
2. exit 
3. reopen
4. starts from start

### Expected behavior

start from where i left

### Actual behavior

starts from start

### Komga version

1.8.2

### Operating system

win 10 and android

### Installation method

Docker

### Other details

komga:
    image: gotson/komga
    container_name: komga
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Oslo
    volumes:
        - /home/xxxx/mediaserver/data:/config
        - /home/xxxx/mediaserver/books:/books
        - /home/xxxx/mediaserver/comics:/comics
        - /home/xxxx/mediaserver/files:/files
    ports:
      - 25600:25600
    user: "1000:1000"

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
If you're talking about epub books that's normal, it was written in bold in the release notes and announcement.

**Comment by BeeTwenty** [comment]
Oh ok, im new to Ebooks but is there a format i can use with Ebooks? also then maybe there should be a feature to add a "bookmark" or some way to note where you stoped so you remember where to begin next time

**Comment by gotson** [comment]
It seems you still haven't read the release notes or announce. That feature is planned, but doesn't exist yet.

**Comment by BeeTwenty** [comment]
Im sorry i did read it but must have missed thanks for your help

ons. 29. nov. 2023, 13:22 skrev Gauthier ***@***.***>:
