### ISSUE TITLE
Windows Store version not updating

### ISSUE THREAD

**Issue by Rumik** [gotson/komga#1319]
### Steps to reproduce

I have recently started using the Windows Store version, but it is still on 1.8.0 - it is not updating as updates are released.

### Expected behavior

I would expect that the Windows Store version is kept up to date with the other versions.

### Actual behavior

 Windows Store reports no updates available.

### Komga version

1.8.0

### Operating system

Windows 10

### Installation method

Microsoft Store

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
the submissions on the store need to be validated and it can take some time
