### ISSUE TITLE
Parse chapter number from file name

### ISSUE THREAD

**Issue by FenTheFox** [gotson/komga#1320]
### Describe your suggested feature

with files like so
![image](https://github.com/gotson/komga/assets/4973633/74aab92a-3da6-468f-8cf3-ae67d412fbcc)
rather than the last two files being imported as chapters 7 and 8, they should be imported as 6.5 and 6.6. as is the real chapter 7 gets labeled as chapter 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There will not be any filename parsing.
