### ISSUE TITLE
Web reader doesn't full load images until they are shown despite preloading

### ISSUE THREAD

**Issue by JerwuQu** [gotson/komga#1323]
### Steps to reproduce

This is most noticeable in Firefox, especially with high resolution images (or spreads).
A spread where the issue was very prominent had the resolution of 3620x2560 for example.
To reproduce, open the reader and switch to a high resolution image.
After the image has been shown once, it will remain cached in the browser and you need to either Ctrl+F5 or fully close the browser to be able to reproduce the issue for that image again.

### Expected behavior

Displays the image instantly.

### Actual behavior

What happens in Firefox is that images are shown as complete black until they have been rendered.
In Chromium, it seems to instead "freeze" the browser page until the image has rendered, resulting in some delay but an overall better experience.
With the example spread mentioned above, it would result in a black image for ~0.5s in Firefox, and a delay of ~0.5s in Chromium.

This caused me to first believe that Komga didn't have preloading at all. On inspection though, I can see that the image *has* been loaded through a network request, but when switching to said image (same page numbers), I still see the loading lag.

### Komga version

v1.8.3-master

### Operating system

Debian 12

### Installation method

Docker

### Other details

Looking at the code and network inspector, it caches the image properly with [`:eager="eagerLoad(i)"`](https://github.com/gotson/komga/blob/a8e2cc98eb4625f37af0efd136b37510491ec424/komga-webui/src/components/readers/PagedReader.vue#L22), but because the item still has `display:none;` it doesn't actually get loaded for rendering.

As an example, applying the following userstyle which overrides the `display:none;` style, while completely breaking the reader, also fixes the preloading issue for the first few images before breaking.
```css
div.v-window-item {
    display: block !important;
}
```

[One person on StackOverflow](https://stackoverflow.com/a/63026806) claims that using `eager` for the `v-carousel` is not enough and that it might also require having a `v-img` with `eager`.

While I don't have a Komga development setup right now, I would be willing to help solve this issue.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by JerwuQu** [comment]
Sure! Here's an example: https://www.youtube.com/watch?v=CXAa-pcYABk

For this I used very high resolution images (6000x10000) to make it really prominent, but I can see it with normal manga too.
Notice that when going to the next page, it goes completely black before showing the page, and how it is instant when going backwards.

**Comment by gotson** [comment]
And that symptom only happens on Firefox, is that right?

**Comment by gotson** [comment]
Could you share that test cbz you're using? That would save me some time finding / building one for testing.

**Comment by JerwuQu** [comment]
The black image can only be seen on Firefox, yes. On Chromium browsers it seems to slightly lag the browser instead.

Here is the cbz: https://drive.google.com/file/d/1HXYs7N0e3lK_V9PYOnvy8DUFOXttoRgm/view?usp=drivesdk

**Comment by gotson** [comment]
Thanks for the file. I can reproduce on both Chrome and Firefox. Most of the development of Komga was done on Chrome, until a few weeks ago, which explains why this was never spotted. Chrome handles this slightly better than Firefox in my opinion.

We don't use `v-img` though, so i need to find another way to render the images before showing them.

**Comment by JerwuQu** [comment]
I tested it locally on the `master` branch and it works great in Firefox
