### ISSUE TITLE
EPUB comic/manga books now have a very poor UX

### ISSUE THREAD

**Issue by radonmiser** [gotson/komga#1324]
### Steps to reproduce

open any EPUB books that's composed of images
1. images now are not extended to the page margin
2. rtl mangas unreadable
3. double pages not working 
4. pages not pre-loading...etc

### Expected behavior

there should be a heuristics to detect image based EPUB books and use the old reader for these books instead

or an option to disable epub reader on a book/series/library/server level

or efforts could be made to improve the EPUB reader so that image based books have a proper UX

### Actual behavior

1. images now are not extended to the page margin
2. rtl mangas unreadable
3. double pages not working 
4. pages not pre-loading...etc

### Komga version

1.8.3

### Operating system

win11

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by radonmiser** [comment]
Actually I can't even use the old reader url to manually open a epub book with the old reader
half of my collection is almost unreadable now, how do I downgrade

**Comment by gotson** [comment]
I'm curious as to where those epub come from. Epub for comics is not very widespread.

You could consider converting your field to cbz as there's really no upside to using epub for image only content.

**Comment by radonmiser** [comment]
> You could consider converting your field to cbz 

That would mean losing progress on half of my library with no upsides since I didn't intent to use Komga for text contents. 

> If not, maybe converting them to cbz is the best thing to do.

They come in epub after the drm removal, for users who have no intention of consuming text contents in Komga they are demanded an extra step for something that worked perfectly.

**Comment by gotson** [comment]
If à publisher publishes epub, it's kinda implied that the content needs to be read by an epub reader.

Komga was handling a subset of epubs at the time, but that's not the way the publisher intended to.

Time marches on as we say, Komga now handles full epub.

Epub manga probably render the same (ie poorly as you put it) on other epub readers, since epub is mostly geared towards text content.

**Comment by noaione** [comment]
Most manga that are taken from Kobo would be in EPUB and RTL layout. Here is some mini sample with images replaced (to avoid copyright)

[mini_epub_manga_rtl.zip](https://github.com/gotson/komga/files/13540962/mini_epub_manga_rtl.zip)

The RTL layout is mainly defined in `spine`.

**Comment by gotson** [comment]
> Most manga that are taken from Kobo would be in EPUB and RTL layout. Here is some mini sample with images replaced (to avoid copyright)
> 
> [mini_epub_manga_rtl.zip](https://github.com/gotson/komga/files/13540962/mini_epub_manga_rtl.zip)

ideally i need an untouched book from a publisher. 

> The RTL layout is mainly defined in `spine`.

I know.

**Comment by gotson** [comment]
> pastebin.com/XECpC8Rd

Got it, thanks



> side note: if you run the books through Calibre the fixed layout info gets destroyed and the books no longer render properly.

That's a Calibre problem. EPUB do have 2 possible layout, and if `pre-paginated` is not present, the default is reflowable. Calibre removing this attribute makes the book reflowable, which would break the display on any reader.

**Comment by gotson** [comment]
@radonmiser can you provide more details on this:
> double pages not working

I will add support for RTL, i did a quick test and it seems to work fine.

**Comment by radonmiser** [comment]
> @radonmiser can you provide more details on this:
> 
> >
I tested the 2 I sent you on 1.8.4 docker
The one from kobo was detected as epub but the reader displays it one page at a time and loaded slowly
![image](https://github.com/gotson/komga/assets/61794107/a59299ea-2221-42a6-aa64-d0f40f3f3b00)

the one from bw is was detected as cbz and was opened by the old reader

both were detected as fixed layout epub in the ios reader

**Comment by gotson** [comment]
I can't extract the kobo one:
<img width="460" alt="image" src="https://github.com/gotson/komga/assets/2139133/fadd5c90-d730-4cad-8f32-886e88f6f179">

The one from bookwalker has an invalid mimetype signature, meaning the epub is broken. The `mimetype` file should be the first file in the zip. You can use `unzip -l` on the file, and the `mimetype` is the last file in the zip.
