### ISSUE TITLE
FixThumbnailsWithoutMetadata crashes system

### ISSUE THREAD

**Issue by giuanpadan74** [gotson/komga#1325]
### Steps to reproduce

1. Start Komga - automatic start "FixThumbnailswithoutMetadata"
2. Komga creates 35GB tomcat.docbase.xxxxx.xxxxxxxxxxx
![Tempdata](https://github.com/gotson/komga/assets/114602321/df7f303e-4b4e-4a53-8460-3f4e482d6691)
Impossible to kill the task

### Expected behavior

Komga start and task "FixThumbnailsWithoutMetadata" completed successfully

### Actual behavior

I have a large quantity of jxl ebooks in my nvme disk 100GB
system crash

### Logs

[komga.log.2023-12-02.1.txt](https://github.com/gotson/komga/files/13538309/komga.log.2023-12-02.1.txt)

### Komga version

1.8.3

### Operating system

Container Ubuntu

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It seems the app stops every time trying to handle the same pdf file "Nathan Never 370".

Therwse nothing in the logs about the thumbnails fixing task going wrong.

Since you have scan in startup enabled, it keeps crashing. And you probably have setup your container to auto restart, hence the crash loop.

**Comment by giuanpadan74** [comment]
Thank you so much
