### ISSUE TITLE
Add support for other databases (ex. PostgreSQL)

### ISSUE THREAD

**Issue by asoluter** [gotson/komga#1327]
### Describe your suggested feature

With large library scan Komga starts chugging with the following logs: (especially with 20k+ pending tasks)
```
SqliteTaskPool - SqliteTaskPool Connection is not available, request timed out after 30000ms.
```
It may be helpful to allow usage of a more scalable than SQLite database to possibly solve this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Not planned. Use wal mode or store the database on ssd.
