### ISSUE TITLE
[Feature Request] Read button displayed on book thumbnail

### ISSUE THREAD

**Issue by KillahB33** [gotson/komga#133]
### Is your feature request related to a problem? Please describe.
Mainly just to make the tool easier to use, would be nice if their was a read button on the thumbnail instead of me having to click on the issue then clicking on the read option.
I thought I saw it mentioned in another request but it says it's completed but it's not there.

### Describe the solution you'd like
Read button like there is a play button in plex (saw you mention plex was your inspiration)

**Comment by gotson** [comment]
This was indeed an idea floating around.

If there was a read icon in the middle, we would need to still be able to click on the book to go to the details page. Maybe via the bottom of the card or by clicking in the thumbnail but outside the button.

**Comment by KillahB33** [comment]
Yeah I like the idea of clicking outside of it takes you to details page
