### ISSUE TITLE
[Feature Request] Improved Tag Filtering Logic and Exclusion Feature

### ISSUE THREAD

**Issue by Dragoopai** [gotson/komga#1331]
### Describe your suggested feature

Dear Komga team,

I am an avid user of komga and appreciate the feature that allows filtering series based on tags. However, I have identified an opportunity to enhance the filtering functionality that could significantly improve the user experience (at least mine) .

Currently, when selecting multiple tags, komga appears to employ an "or" logic, expanding the results. My suggestion is to implement an "and" logic for tag selections. This would effectively narrow down the displayed series, showing only those that contain **all** selected tags, making the search more precise.

Additionally, it would be incredibly beneficial to introduce an exclusion feature. Users would gain the ability to filter out series that explicitly do not contain a specific tag. This would provide a more comprehensive and refined search experience, ensuring users find exactly what they are looking for.

Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Sounds like #887?

**Comment by Dragoopai** [comment]
> Sounds like #887?

Absolutely! Just with the addition "books shouldn't contain tag A, but they should contain tag b".
