### ISSUE TITLE
Microsoft Store does not have the latest version

### ISSUE THREAD

**Issue by HNQX** [gotson/komga#1332]
### Steps to reproduce

I see 1.8.3 released, but do not contain windows release

I found release log say:
>komga-tray
> -add native heif library for Windows ([a3439dd](https://github.com/gotson/komga/commits/a3439dd))
>added the native HEIF/AVIF library for Windows app

So i wonder if forget or something 

### Expected behavior

1

### Actual behavior

0

### Komga version

1.8.3

### Operating system

windows11

### Installation method

other (please provide more details below)

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The Microsoft folks are not validating the latest versions, so they are not pushed to the Microsoft Store. I have contacted them, but they have not replied.

**Comment by HNQX** [comment]
> The Microsoft folks are not validating the latest versions, so they are not pushed to the Microsoft Store. I have contacted them, but they have not replied.

Thanls for u'r reply. Got it

**Comment by gotson** [comment]
I managed to fix a bug that would probably only happen on Windows, the latest version is now in the Microsoft Store 🎉
