### ISSUE TITLE
Overlaping pages with a "4 page wide" page in ajusted to heigth 

### ISSUE THREAD

**Issue by Mirgolth** [gotson/komga#1339]
### Steps to reproduce

"House of X 04 (of 06) (2019) (Digital)" has a "4 pages wide" page that seem to be causing problem to the webreader.

It starts show 2 page early in "ajusted to height" mode taking the whole right half page and keep showing on several pages.

Here is a screenshot :
![Overlaping pages](https://github.com/gotson/komga/assets/15908911/4000805b-ce74-450f-84c6-32bb61fbbf05)

 

### Expected behavior

Page should not take half the screen :)

### Actual behavior

Page show in incorrect order and incorrect ratio

### Komga version

1.8.4-master 

### Operating system

Docke image running on Synology

### Installation method

Docker

### Other details

Dont hesitate to contact me for the file to reproduce.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Do you have analyze page dimensions on?

**Comment by gotson** [comment]
Additionally, can you provide the file, or some equivalent file with non copyrighted images but same dimensions?

**Comment by gotson** [comment]
This is probably introduced by #1323

**Comment by gotson** [comment]
I managed to reproduce using some of my files
