### ISSUE TITLE
How do I set up anonymous access

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [gotson/komga#1340]
### Describe your suggested feature

There doesn't seem to be anything in the Settings that would allow anonymous access
I want users to be able to see relevant content without logging in
![image](https://github.com/gotson/komga/assets/87591236/83fd82c9-9e24-44fb-b348-78615714474a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There is no such thing as anonymous access.
