### ISSUE TITLE
Desktop app doesn't launch "internal error"

### ISSUE THREAD

**Issue by profzelonka** [gotson/komga#1343]
### Steps to reproduce

1. Download and run installer for Version 1.8.4 from https://download.komga.org/
2. Run Installer. Installer ends without any prompts.
3. Open Komga App from start menu shortcut.

### Expected behavior

Komga opens 

### Actual behavior

Giant error message prompt with "ok" button to dismiss. (attached screenshot of error message)
![Screenshot 2023-12-11 203404](https://github.com/gotson/komga/assets/38406652/c5784cdb-b95a-43da-a27f-dc9231047b02)

### Komga version

Desktop 1.8.4

### Operating system

Win 11

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's fixed but not yet delivered.

**Comment by gotson** [comment]
The Microsoft version already has the fix, in case you can't wait.

**Comment by gotson** [comment]
Fixed in 1a30bf9a05a01175f0805c18786e36c981c3769b
