### ISSUE TITLE
Komga prevents stand-by

### ISSUE THREAD

**Issue by Dragoopai** [gotson/komga#1344]
### Steps to reproduce

* start Komga
* disable automatic library scan
* observe system/OS is not able to go into stand-by

### Expected behavior

I expect that if I disable the automatic library scan there are not background processes running when not using Komga.

### Actual behavior

My Komga is running on an NAS with docker. When stopping the container the system goes into stand-by when I not use it. With Komga running it is running 24/7 even I not use it. This process additional energy costs.

My assumption is that this is related to the usage of @Scheduled annotations:
https://github.com/search?q=repo%3Agotson%2Fkomga %40Scheduled&type=code

Would be nice to be able to configure that.

### Komga version

1.8.4

### Operating system

DSM (Synology)

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Dragoopai** [comment]
Hi, I am really curious about your thoughts behind the "wontfix". Could you please share it?

**Comment by gotson** [comment]
Most daemon like programs will do stuff on a schedule. If your system goes to sleep komga cannot serve http requests anymore.

If you don't want it running, stop it.

**Comment by Dragoopai** [comment]
That is not completely true. I have other http services running. And maybe the wording "stand-by" or "sleep" is a bit misleading. At least on Synology NAS it is still active, but HDD are turned off. As soon I request the NAS it starts them again and the http request will be served. Sure it takes then a bit longer for the first one but the NAS is not waisting power in that situations.

**Comment by Dragoopai** [comment]
Now I am really wonder if I am right with this statement. I will check it and come back.

**Comment by Dragoopai** [comment]
I did a few experiments. And I can confirm I have no problems with other http server applications. I installed a very basic application on my NAS and it was always able to power of the HHDs when the service was not in is. I assume that this as something to do that the Scheduled-jobs use the disc in any way.

[Here](https://hub.docker.com/r/dmportella/expressjs) is the image I used.

Is there a way to make those features somehow optional/configurable?

**Comment by gotson** [comment]
Unless you can pinpoint what/why is preventing your NAS to go to sleep, nothing will be worked on for this.

**Comment by Dragoopai** [comment]
As I tried to explain: With running Komga the NAS can not turn off the HDDs. With other http servers it is able. Can you help me out and explain what should I pinpoint now?

**Comment by gotson** [comment]
> As I tried to explain: With running Komga the NAS can not turn off the HDDs. With other http servers it is able. Can you help me out and explain what should I pinpoint now?

i cannot help you, i have no idea why your NAS would or would not go to sleep. If you cannot provide any elements about what is happening on your system, i have no idea what to change in Komga.

**Comment by Dragoopai** [comment]
I really tried to debug it. Also with installing another a http server. At least my assumption is that because Komga runs scheduled task where it uses HDDs resources the NAS is not able to let them sleep even nobody is using Komga. Can you provide a docker image from a dev branch and push it to docker hub? In this you can maybe just comment out the Scheduled jobs, I can install this image on my NAS and give you feedback? Or are there other background processes I maybe miss?
