### ISSUE TITLE
Data table not loading when language is traditional chinese

### ISSUE THREAD

**Issue by taiwan-king** [gotson/komga#1345]
### Steps to reproduce

Account Setting & Server Setting Authentication Activity
Traditional Chinese will always fail to display.

### Expected behavior

The Traditional Chinese should display properly, not show a spinning circle constantly.

### Actual behavior

The Traditional Chinese should display properly, not show a spinning circle constantly.

### Komga version

v1.8.4

### Operating system

win10

### Installation method

Docker

### Other details

![01](https://github.com/gotson/komga/assets/24381898/be32453b-e335-4932-9572-a9234f88c372)
![02](https://github.com/gotson/komga/assets/24381898/a10772c6-12ba-4b1e-9560-a551fb2ba68f)

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand what you mean. Can you explain?

Does it work in English or other language?
