### ISSUE TITLE
Tray options are garbled

### ISSUE THREAD

**Issue by kofzhanganguo** [gotson/komga#1349]
### Steps to reproduce

Tray options are garbled

### Expected behavior

Tray options are garbled

### Actual behavior

![image](https://github.com/gotson/komga/assets/32073931/1dbc9d84-a384-43a8-b65e-86a6e9a42c17)

I am using a Chinese system, selected the Chinese language, and am using the software version komga-1.9.0-windows-amd64. The tray menu options are now all garbled squares. I hope the next version can solve this problem.

### Logs

[komga.log](https://github.com/gotson/komga/files/13687933/komga.log)

### Komga version

v1.9.0-master

### Operating system

Windows 10

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The properties file were not set to UTF-8 in weblate. It's been changed now.

**Comment by kofzhanganguo** [comment]
> weblate 中的属性文件未设置为 UTF-8。现在已经改变了。

Okay, I'm going to translate the language into Chinese now.
