### ISSUE TITLE
Downloaded readlists don't start at 1

### ISSUE THREAD

**Issue by Shakahron** [gotson/komga#1350]
### Steps to reproduce

Download a readlist.

### Expected behavior

Files start at 1

### Actual behavior

Files start at 2

### Komga version

1.8.4

### Operating system

Windows 10

### Installation method

from download.komga.org

### Other details

This isn't functionality I use, I just noticed it messing around and thought I should mention it.
Here's a screenshot:
![7zFM_Evu7wxvoDs](https://github.com/gotson/komga/assets/106402227/672cc090-68b3-473b-b7e6-eedc5c1be2b5)

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Is this an auto-generated read list, or manually created ?

**Comment by Shakahron** [comment]
> Is this an auto-generated read list, or manually created ?

Auto-generated

**Comment by gotson** [comment]
> > Is this an auto-generated read list, or manually created ?
> 
> Auto-generated

then it's normal. Auto-generated readlist do not necessarily start at 1.
