### ISSUE TITLE
ePub reader doesn't show page number

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1353]
### Steps to reproduce

1. Open epub with the web reader

### Expected behavior

In the corner see e.g. "Page 2 of 5" or similar

### Actual behavior

In the corner you see "Page of (Current chapter)" with no numbers
![grafik](https://github.com/gotson/komga/assets/56667539/86963be3-ee35-461a-9641-1a2afed35447)

### Komga version

v1.9.0-master

### Operating system

Docker

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
it seems the npm package was not properly pulled during the release, it works well on local dev

**Comment by gotson** [comment]
don't know why, still doesn't work
