### ISSUE TITLE
[Bug] Lost Mount, Lost Metadata

### ISSUE THREAD

**Issue by KillahB33** [gotson/komga#136]
### Komga environment
- **OS**: CoreOS Docker
- **Komga version**: latest
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
Upgraded my nas box and lost the mounts, komga appears to have purged everything now.

### Expected behavior
Was hoping as soon as I fixed the mount we would be good to go, now it appears to have to rebuild everything.

### Actual behavior
Lost everything

Anyway I can get it back? Or do I just have to wait for the analysis to finish on everything?

**Comment by gotson** [comment]
Do you have logs of when a scan happens while the mouth was lost?

Can you explain what kind of mount it is, and in which state the mount was exactly when it was "lost"?

**Comment by KillahB33** [comment]
I wish I could help with logs, but I restarted the container as that fixed plex so figured it might help with komga.

This is an unraid nfs mount.
192.168.0.212:/mnt/user/Comics          /opt/Comics/            nfs     auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0

**Comment by gotson** [comment]
I suppose your Komga library root is pointing to the root folder of the mount ?

What i suspect is that when the mount is not available, the mount root exists, but is empty. If your Komga library points to that root directly, then the folder will appear empty, and Komga will delete your library content.

However, if Komga could not reach a folder while scanning, it would abort the scan. What you can do is to add a Komga library root path that is _not_ a NFS root, that way when the scan starts, the folder is not reachable, and Komga will abort.

**Comment by GlassedSilver** [comment]
This is when (supplementary) sidecar files truly shine.

Issue #82.

It also provides extensive peace of mind (beyond my example of switching software solutions and having the data portable) in cases like this, where you would just scan and "create a new library" in the worst case all while prioritizing meta data from local asset sources like the sidecar files.

Also storing reading progress,bookmarks and anything else I guess there would come in handy for obvious reasons. Maybe not all of it in the same formats. Guess issue #135 is a good place to take it to.

**Comment by KillahB33** [comment]
That's correct gotson.

Also correct. Ok I guess that makes sense, as you can probably guess I prefer the marked an unavailable like plex does.

I'll dig into how to do that, thanks.

Agree with GlassedSilver, some portability would be nice!

**Comment by gotson** [comment]
From Komga's point of view there is no way to distinguish an empty directory because you deleted everything, from an empty mount because it was not available.

If you use a subdirectory of the mount, then i would be able to mark files as unavailable, like Plex does.

I'll close the issue since it's clarified.

**Comment by KillahB33** [comment]
So my mount would need to be /opt/files/ and then komga wouldn't even see /opt/files/comics and then would just mark as unavailable?

**Comment by gotson** [comment]
as of now it would just stop the scan, you would see an exception in the logs. I could add a feature later on to mark media as unavailable.

Please try it and let me know how it goes (Discord is fine too).
