### ISSUE TITLE
Can't remove some series in a library --> SQLITE_CORRUPT_INDEX

### ISSUE THREAD

**Issue by oznxzar** [gotson/komga#1362]
### Steps to reproduce

Hi guys, 

I have 4 libraries created into my komga instance. A few days ago I noticed that some series in my library could not be deleted and the logs showed the following error. "SQLITE_CORRUPT_INDEX"

do you know how I could fix it or manually delete these entries to fiz SQL database status?

### Expected behavior

fix the issue with that library or hace teh abilty to fix the issue.

### Actual behavior

books get stuck and can't be removed.

### Logs

`2023-12-18T17:48:29.964+01:00  INFO 1 --- [askProcessor-12] o.g.komga.domain.service.BookLifecycle   : Delete book ids: [0D82FH3CHY8SW, 0D8H1432SYCGD, 0D8H1432SYCGE, 0D8H1432SYCGF, 0D8H1432SYCGG, 0D8H1432SYCGH, 0D8H1432XY82F, 0D8H1434SY4TF, 0D8H1434SY4TG, 0D921TXSNYA72, 0D921TXVNY67T, 0D921TXVNY67V, 0D921TYASY6VF, 0D921TYASY6VG, 0D921TYASY6VH, 0D921TYASY6VJ, 0D921TYASY6VK, 0D921TYAXY1A8, 0D921TYC9Y88X, 0D921TYC9Y88Y, 0D921TYC9Y88Z, 0D921TYC9Y890, 0D921TYC9Y891, 0D921TYC9Y892, 0D921TYC9Y893, 0D98EMHZD51W5, 0D98EMHZH506N, 0D98EMHZH506P, 0DMYNPR20TPHQ, 0DMYNPR2GTVP4, 0DMYNPR2MTPZG, 0DMYNPR3CTVVX, 0DMYNPR3CTVVY, 0DMYNPR40TM3J, 0DMYNPR40TM3K, 0DMYNPR40TM3M, 0DMYNPR70TJZV, 0DMYNPR74TTNP, 0DMYNPR78TMN8, 0DMYNPR7CTQ5A, 0DMYNPRA4TYJC, 0DMYNPRA4TYJD, 0E4JHFFMJXN8V, 0ED3T2JWV3F75, 0ED3T2JWZ374T]
2023-12-18T17:48:30.096+01:00 ERROR 1 --- [askProcessor-12] o.g.komga.application.tasks.TaskHandler  : Task EmptyTrash(libraryId='0D7PDJQNXY2C8', priority='6') execution failed

org.jooq.exception.DataAccessException: SQL [delete from MEDIA_PAGE where MEDIA_PAGE.BOOK_ID in (select TEMP_STRING_LIST.STRING from TEMP_STRING_LIST)]; [SQLITE_CORRUPT_INDEX] SQLite detected an entry is or was missing from an index (database disk image is malformed)`

### Komga version

1.9.2

### Operating system

Docker

### Installation method

Docker-compose

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment]
If your database is corrupt you need to restore a working copy from your backups. There isn't an automated way to fix bad databases.

**Comment by gotson** [comment]
What Diesel said. This is out of scope of Komga if your database is corrupt.
