### ISSUE TITLE
ePub Progression API returns date conflict after initial call

### ISSUE THREAD

**Issue by edwinbadillo** [gotson/komga#1363]
### Steps to reproduce

Open an epub, go to first page, then go to the next page. Observe progression api fails with conflict after initial call.

### Expected behavior

Progression should be recorded since the date on the latest api payload is later than the date on the initial call's payload.

### Actual behavior

progression api returns conflict due to date.

### Komga version

1.9.2

### Operating system

Unraid 6.12.1

### Installation method

Docker

### Other details

Webreader is on latest Chrome in Windows 11.

Reader is on UTC-5 TZ
Docker is on UTC TZ

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please provide the API details of the initial PUT, and the subsequent GET

**Comment by gotson** [comment]
I managed to reproduce using a different timezone on the server, will look into it
