### ISSUE TITLE
Komga desktop application - Start with windows

### ISSUE THREAD

**Issue by Bazzu85** [gotson/komga#1366]
### Describe your suggested feature

Hi,
I installed komga as a desktop application as described here:

https://komga.org/docs/installation/desktop/

and moved the configuration to 
C:\Users\xxxxxxxxx\AppData\Local\Packages\Komga_fj8s550zp45ee\LocalCache\Local

I cannot find a way (in komga settings or windows 11) to start it automatically with windows.
Seems like the app is store app so I can't create a shotcut to put in shell:startup.

suggestions? thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga does not provide a way to do that. You can ask on StackExchange how to set an application to start with Windows, i do not have a Windows machine thus cannot help. Or ask on Discord, some people have done it.
