### ISSUE TITLE
Adding a different View Theme for the ebook reader

### ISSUE THREAD

**Issue by archziac** [gotson/komga#1367]
### Describe your suggested feature

"Color code: #1A1A1A" for the background and "Color Code: #F4F4F4" for the text... 

### Other details

Full dark and the full white text color hurts the eyes when reading for a long time so this should be easier on the eyes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Use Sepia ?

The epub reader is using https://readium.org/readium-css/ and the themes are provided by Readium CSS.

**Comment by archziac** [comment]
Not a fan of light modes. And I mainly want a grey viewing theme it doesn't have to be the same particular color codes that I gave.
