### ISSUE TITLE
No covers (thumbnails) at all

### ISSUE THREAD

**Issue by Stooovie** [gotson/komga#1369]
### Steps to reproduce

1.) install
2) add folder with comics

### Expected behavior

see thubnails/covers

### Actual behavior

no covers
![Screenshot 2023-12-23 at 14 44 31](https://github.com/gotson/komga/assets/10572373/e1e60af9-b28b-4f59-b585-65a22653f0d4)

### Logs

[komga.log_153806.zip](https://github.com/gotson/komga/files/13759501/komga.log_153806.zip)

### Komga version

1.9.2

### Operating system

Linux

### Installation method

from download.komga.org

### Other details

running in a Proxmox LXC (Debian 11), installed from the .deb as per official instructions. Tested with a single CBZ file, same issue. Waited 2 hours to see any results, no dice. Restarting the app and/or the container didn't help.

Actual reading and other features do work.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by billsargent** [comment]
Have you checked the permissions on your directories?

**Comment by Stooovie** [comment]
Yes, it's drwxr-xr-x, so AFAIK R/W to everyone.

**Comment by gotson** [comment]
logs do not contain any exceptions 🤷🏻

**Comment by Stooovie** [comment]
too bad... can't use Komga then :(

**Comment by DieselTech** [comment]
Try changing your proxmox CPU type to something other than `x86-64-v2-AES` You'll have to pick something that more closely matches your physical CPU. 

I've seen this before in other projects where proxmox masks too many of the CPU features and prevents the VM's from using them.

**Comment by billsargent** [comment]
I would also try not using the deb and installing just the jar file. Thats how I do it.

**Comment by Stooovie** [comment]
> Try changing your proxmox CPU type to something other than `x86-64-v2-AES` You'll have to pick something that more closely matches your physical CPU.
> 
> I've seen this before in other projects where proxmox masks too many of the CPU features and prevents the VM's from using them.

this is a LXC, not a VM. You can't specify CPU type on a LXC, it runs off the host's kernel. Thank you though, good point. I always set the type to "host".

**Comment by gotson** [comment]
try to enable debug logs and get some logs from when you Analyze a book.

**Comment by Stooovie** [comment]
> I would also try not using the deb and installing just the jar file. Thats how I do it.

good idea. It seems to fix my issue. Thanks!

**Comment by Stooovie** [comment]
It's also quite prone to crashing. But that's for a different bug report.

**Comment by billsargent** [comment]
> It's also quite prone to crashing. But that's for a different bug report.

The jar? Or the deb?

**Comment by Stooovie** [comment]
The jar. I'm not adept in Java and I don't know how to restart it after failure.

**Comment by DieselTech** [comment]
The jar version is quite stable and has been for some time now. Constant crashing would most likely be a config issue on your end. Most likely due to messing with the memory settings or not having enough RAM.

**Comment by billsargent** [comment]
`#!/bin/bash

JAVA_PATH="/path/to/your/java"
JAR_PATH="/path/to/your/komga-1.8.3.jar"
JAVA_OPTIONS="-Xmx2g"
KOMGA_OPTIONS="--komga.remember-me.key=asdfgh --logging.file.name=komga.log"


restart_komga() {
    echo "Restarting Komga..."
    $JAVA_PATH $JAVA_OPTIONS -jar $JAR_PATH $KOMGA_OPTIONS &
}

restart_komga

# Monitor Komiga and restart should it crash
while true; do
    sleep 5
    if ! pgrep -f "java.*$JAR_PATH" >/dev/null; then
        echo "Komga has crashed. Restarting..."
        restart_komga
    fi
done`

Something like this as a bash script should keep it restarting but honestly, you should figure out why its crashing. Keeping a full log like above will help in diagnosing why it's crashing. This is how I run it on my NAS which has very little RAM.

**Comment by gotson** [comment]
Closing as it seems related to the install method used, not the code.
