### ISSUE TITLE
Multi-select Items in Collection to Remove From Collection

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#1370]
### Describe your suggested feature

It would be convenient from the collection main view to be able to select multiple series and remove them from that collection

![image](https://github.com/gotson/komga/assets/32607317/673c74d3-3b84-41a2-8f68-334c0fef605e)

Instead right now I have to click the Edit Elements which resets the filters & sort.

Ideally I could hit a delete button from the main view, just like I would if I wanted to delete the series permanently. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Complex to implement, because items are not removed from a collection, but instead the complete list of elements, without the ones to be removed, is sent to update the collection.
