### ISSUE TITLE
Cannot open ebook when using Nginx

### ISSUE THREAD

**Issue by marcdieters** [gotson/komga#1371]
### Steps to reproduce

I've published my Komga instance through Nginx. When I open a book the following is shown in the browser console.

```
Failed to load resource: the server responded with a status of 404 ()
/comics/api/v1/books/0EMR6HBKX6TD8/thumbnail:1 
        
Failed to load resource: the server responded with a status of 404 ()
/comics/api/v1/books/0EDQE00ZRAYAA/next:1 
        
Failed to load resource: the server responded with a status of 404 ()
/comics/api/v1/books/0EDQE00ZRAYAA/previous:1 
        
Failed to load resource: the server responded with a status of 404 ()
/comics/api/v1/books/0EDQE00ZRAYAA/next:1 
        
Failed to load resource: the server responded with a status of 404 ()
/comics/api/v1/books/0EDQE00ZRAYAA/previous:1 
```
        
After a while, the following is shown:
```
Uncaught (in promise) TypeError: Failed to fetch
    at e.precessContentForIframe (index.js:63041:11)
    at e.navigate (index.js:63881:14)
    at async e.loadManifest (index.js:62414:57)
    at async e.start (index.js:62035:12)
    at async e.create (index.js:61653:5)
    at async e.load (index.js:65742:13)
    at async r.setup (EpubReader.vue:424:12)
komga-books.service.ts:104 

GET http://<my_external_url>/comics/api/v1/books/0EDQE00ZRAYAA/next 404 (Not Found (anonymous) @ xhr.js:256
```

When I open the book directly, so no Nginx, it opens fine. 
So there's something wrong with my Nginx config but I don't know what.
I found an issue posted but I couldn't get that solution to work.

My Nginx config:
```
location /comics/ {
                proxy_http_version 1.1;
                auth_request off;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  Upgrade $http_upgrade;
                proxy_set_header  Connection "Upgrade";
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;

                proxy_pass        http://192.168.1.54:25600/comics/;
                chunked_transfer_encoding off;
                proxy_buffering off;
                proxy_cache off;
                }

                location /comics/api {
                        auth_request off;
                        proxy_pass http://192.168.1.54:25600/comics/api;
                }
                location /comics/opds {
                        auth_request off;
                        proxy_pass http://192.168.1.54:25600/comics/opds;
                }
        }

```

It would be great if someone could help out. Adding ebooks to Komga is a dream come through  :)

### Expected behavior

I expect the ebook the open just like comics do.

### Actual behavior

Ebooks do not open like comics when using Nginx

### Komga version

1.9.2

### Operating system

Ubuntu 22.04

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
the errors mentioned are normal if there is a single book in a series, your problem must be somewhere else, most likely botched header management on nginx side. You should consider using something like Caddy which can handle all of that in one line of config.

**Comment by marcdieters** [comment]
After upgrading to 1.10, this issue doesn't occur anymore.
