### ISSUE TITLE
Support For Series Metadata From ComicInfo.xml

### ISSUE THREAD

**Issue by austin-joseph** [gotson/komga#1372]
### Describe your suggested feature

Currently Komga will determine Series metadata based on the of the constituent Books and the rules here [Scanning, Analyzing and Refreshing Metadata](https://komga.org/docs/guides/scan-analysis-refresh/).

It would be nice to import from a Series wide ComicInfo.xml which would supersede the data present Books themselves. 

The below fields are part of the [anansi-project/comicinfo](https://github.com/anansi-project/comicinfo/tree/main) spec and I think could be useful.

<Summary> - is currently not imported at all. This would correlate directly to the Series summary field.
<Series> and <Title> - The name of the Series where the following logic determines the priority.
<Series> > <Title> > Title from constituent books > Series Folder Name
<AgeRating> - The highest of the Series metadata or all Books metadata would take priority.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga already imports series fields from books. There's no such thing as `ComicInfo.xml` for series itself, nor any place to put them anyway.
