### ISSUE TITLE
OPDS feed no longer includes issue number

### ISSUE THREAD

**Issue by narayandesai** [gotson/komga#1373]
### Steps to reproduce

Setup komga, connect OPDS reader, look at series listing. 

### Expected behavior

Issues were previously listed by number, with issue title information added on.

### Actual behavior

Only issue title info (not issue number) is shown, which makes it hard to navigate a series.

### Komga version

1.9.2

### Operating system

Arch Linux

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
What's your OPDS client ? the issue number was only ever included for Chunky, which doesn't work anymore with Komga.

**Comment by narayandesai** [comment]
Yeah, this is with Chunky. What is the story with the incompatibility? I just saw the note on the docs, but there aren't any details. It seems to work, fwiw.

**Comment by gotson** [comment]
> Yeah, this is with Chunky. What is the story with the incompatibility? I just saw the note on the docs, but there aren't any details. It seems to work, fwiw.

can't remember, but many people reported this on Discord. Anyhow, Chunky never implemented OPDS properly, and is not updated anymore. You should probably switch to some other OPDS client.
