### ISSUE TITLE
Question about the background color when reading - gray looks a lot like black

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gotson/komga#1376]
### Describe your suggested feature

Don't worry, this is a very minor issue.
The first image looks like when I open the PDF in Komga. The Komga reading background is set to gray.
In the second image, I opened the PDF in Edge browser. The Edge browser reading background is the default light background.
I think the colors in the Edge browser are more like gray.
![image](https://github.com/gotson/komga/assets/112467275/f07c6fba-0553-45bb-9bdb-273702fe42a0)
![image](https://github.com/gotson/komga/assets/112467275/c9f2e68d-dc34-4347-a2da-5ec54b03ab0d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand, can you clarify?

**Comment by gotson** [comment]
It's a dark grey, rgb(33,33,33). Looks similar on all browsers i tested.

**Comment by gotson** [comment]
i did understood, i pointed out to what it is.
