### ISSUE TITLE
Automatic database backups

### ISSUE THREAD

**Issue by gotson** [gotson/komga#138]
Database can get corrupted and unusable, backups should be done on a regular basis to allow recovery.

H2 doesn't recommend to copy the database file while it's open and running, hence classic backup solutions are not always working, as no one stops the server before running the backup tool. H2 proposes a `BACKUP` command that can perform backups while running.

There is also lots of people who have no idea about backup tools.

Implementing a proper native backup, scheduled regularly, would help.

**Comment by binyaminyblatt** [comment]
+1 for that

**Comment by ethanpil** [comment]
+100
