### ISSUE TITLE
Add konf menu

### ISSUE THREAD

**Issue by taos15** [gotson/komga#1380]
### Describe your suggested feature

Add a tab with for configure conf. Prett much the same tab that gets added with tampermoney, but build into the main UI

### Other details

Using tampermonkey konf implementation requires you to intall it in every browser, this become a challenge for mobile devices.
![image](https://github.com/gotson/komga/assets/122130728/f17c81a3-dda8-4a37-bcdf-ade084a10c45)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by farahnur42** [comment]
Just FYI Komf is third-party software, it isn't part of Komga itself.

**Comment by taos15** [comment]
I know that. That why is it more like a feature to `integrate` komf. The tab dont even need to show all the time and just show based on a variable like `KOMF_INTEGRATION: true/false`
