### ISSUE TITLE
Support HTML text tags in the description 

### ISSUE THREAD

**Issue by wanestar** [gotson/komga#1381]
### Describe your suggested feature

 A source I use for metadata uses HTML text tags for the description of books, and Komga doesn't seem to support them. This issue has made it challenging to maintain a clean library for new books, as the HTML tags are displayed as part of the text, disrupting the readability of the descriptions. 

If it isn't possible to support this maybe consider a hide option that hides known html tags? It is far to much work to manually descriptions for 100's of books.

Thanks!

Examples

![Screenshot 2024-01-06 184937](https://github.com/gotson/komga/assets/59542068/81c13a88-e45e-4e26-88ea-5a637541e8b6)

**What it should look like:** 

**<p><em>As the battle between Luffy and Kaido enters the final round, everyone in Wano puts their lives on the line to protect their home. But even if Luffy can actually secure victory, will there be anything left for a new shogun to rule?</em></p><h2>Chapter Titles</h2><ul><li>Chapter 1047: The Sky over the Capital</li><li>Chapter 1048: Twenty Years</li><li>Chapter 1049: The World That Should Be</li><li>Chapter 1050: Honor</li><li>Chapter 1051: Shogun of Wano, Kozuki Momonosuke</li><li>Chapter 1052: A New Morning</li><li>Chapter 1053: New Emperors </li><li>Chapter 1054: Flame Emperor</li><li>Chapter 1055: The New Era</li></ul>**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't think that form should be contained within metadata, it makes metadata less portable.
