### ISSUE TITLE
Manually specifying the reader for epub

### ISSUE THREAD

**Issue by TianZerL** [gotson/komga#1385]
### Describe your suggested feature

Does it possible to specify reader for epub manually? 
All of my mangas are epub, but the new version of komga uses an ebook reader to open them, which is terrible for reading mangas. The old reader is really great.

I have seen #1324, and I guess "Divina Reader" is what I want.
Release 1.9.0 and newer is not working for my epubs.I think this is because there are other things in my epubs besides images.

those epub mangas also cannot be opened on Tachiyomi or other OPDS readers with new version of Komga, so they are almost unreadable now.

Please add an option to switch reader for epub manually if possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you provide a sample epub that is being read by the epub reader ?

**Comment by TianZerL** [comment]
@gotson 

[sample epub](https://file.io/NPzjhK6c2K0a)

**Comment by gotson** [comment]
Thanks. The book was not detected as fixed layout because it was using an older declaration: https://readium.org/readium-css/docs/CSS21-epub_compat.html#fixed-layout

**Comment by gotson** [comment]
When a new version with this commit will be available, you can analyze your books again and it will fix the issue.
