### ISSUE TITLE
https://download.komga.org/ Unable to download the latest version

### ISSUE THREAD

**Issue by kofzhanganguo** [gotson/komga#1388]
### Describe your suggested feature

Can't download the latest version from the website?

### Other details

![image](https://github.com/gotson/komga/assets/32073931/19ccb267-def6-4626-afb8-e8d90f85986e)

Can't download the latest version from the website?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
can you provide more details, like error message or browser console logs?

**Comment by kofzhanganguo** [comment]
> can you provide more details, like error message or browser console logs?

How should I download Komga-1.10.0 version, the 1.9.2 version on the Komga.org website.

**Comment by gotson** [comment]
> > can you provide more details, like error message or browser console logs?
> 
> How should I download Komga-1.10.0 version, the 1.9.2 version on the Komga.org website.

thanks, that was not very clear from your first message.

The release workflow was incorrect, so that version did not get uploaded. For the next one it should be fine.
