### ISSUE TITLE
[Feature request] Support "application/x-tar" file types

### ISSUE THREAD

**Issue by Anskrevy** [gotson/komga#1394]
### Describe your suggested feature

Hello. I use the tar/bsdtar utilities to zip chapters as it is actually a lot faster than the standard zip utility on my system. The resulting files have the mime type "application/x-tar" but I have no problem reading them like normal cbz files in zathura, or sioyek. I realize not all "application/x-tar" files are actually cbz files so it may not be desirable to support this mime type by default. If it is possible to support, it would be greatly appreciated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The problem with TAR is that it does not allow random access, meaning if you access a file in the middle of the archive, you need to go through all the ones before. Not very efficient.

If you zip without compression it should be as fast as tar.
