### ISSUE TITLE
Ability to associate special issues and annuals with a main series

### ISSUE THREAD

**Issue by thatsnumberwang** [gotson/komga#1401]
### Describe your suggested feature

I've been really impressed with Komga so far. One of the things which seems unintuitive is the way annuals and special issues seem completely unlinked to the comics they relate to.

Similar to how you have the One-Shot handling for whole libraries, I think it would be helpful if each series could have a "Specials" folder which could contain annuals and other special editions in. Then when you displayed the list, these issues could be displayed alongside the main series in date order (e.g. 12 standard issues displayed, then an annual, then back to the standard issues). That way if they include elements of an ongoing story they aren't read out of order.

Thanks for listening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can do different ways:
- place the annuals within the same folder as the series, and use the number sort to place them where they need to be. For example an annual between issues 15 and 16 can have a sort number of 15.5
- use collections
- use readlists
