### ISSUE TITLE
how to change bulk poster

### ISSUE THREAD

**Issue by arr111** [gotson/komga#1402]
### Describe your suggested feature

bulk change poster
![IMG_20240122_133603](https://github.com/gotson/komga/assets/126553612/ceba8596-4915-447b-bbc7-02a36c26be6f)
how to change all poster book, same as poster on cover series without change manual.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You can't from the UI. You could script it with the API.

**Comment by arr111** [comment]
> You can't from the UI. You could script it with the API.

can u teach me how to do??
im beginner

**Comment by gotson** [comment]
> > You can't from the UI. You could script it with the API.
> 
> can u teach me how to do?? im beginner

I don't have time for this unfortunately. Google / stackoverflow / Discord should help you.
