### ISSUE TITLE
docker 1.10.2 not working for some people

### ISSUE THREAD

**Issue by Jisagi** [gotson/komga#1404]
### Steps to reproduce

The latest release docker container does not seem to be able to start the java application and just spams this error.
```
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher
```

### Expected behavior

Docker starts the application

### Actual behavior

Docker does not start the application

### Komga version

1.10.2

### Operating system

docker on linux

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by darthmooguy** [comment]
Someone in the discord mentioned it happening on a raspberry pi 4, it's also happening on my x64 machine.

**Comment by Draknars** [comment]
Happening to me as well on Docker on Linux Debian x86_64 bullseye

![image](https://github.com/gotson/komga/assets/40360399/c19fc6a2-8412-4d74-a41d-4636addb013f)

Reverting to 10.0.1 works for me 
![image](https://github.com/gotson/komga/assets/40360399/81af944f-9fe7-4484-978f-9c7456428ac8)

**Comment by gotson** [comment]
It's working for me on the Docker x86_64. Try to recreate the container from scratch.

**Comment by Jisagi** [comment]
Release 1.10.3 fixed the issue for me

**Comment by Metaman99** [comment]
Release 1.10.3 does not start on my Docker (on Synology DSM 7.2) and shows the same error messages from the first post by Jisagi. (Updated from 1.10.1)
