### ISSUE TITLE
[Feature Request] Self Update

### ISSUE THREAD

**Issue by binyaminyblatt** [gotson/komga#141]
I run komga as a windows service using nssm and would like if when a new version comes out it could shut down the service replace the jar file and start up again

**Comment by gotson** [comment]
This would be difficult, as i am not the one providing the package for the windows service.

All releases are available in Github releases, so it's easy to have a script that would check new releases.

If you want to help and contribute on the Windows service part, i would gladly review your work and find a way to package it or distribute it.

I am also looking for help to document the use of Windows service: https://github.com/gotson/komga-website/issues/3

**Comment by gotson** [comment]
Closing this as it is very specific to each installation method.

For example Docker installs can be updated automatically via tools like [watchtower](https://github.com/containrrr/watchtower) or [ouroboros](https://github.com/pyouroboros/ouroboros).

The best solution for Windows would be to leverage on Chocolatey and write a `komga` package, and use chocolatey to update it.

**Comment by binyaminyblatt** [comment]
thanks
