### ISSUE TITLE
Docker update from 1.x

### ISSUE THREAD

**Issue by SylvainDx** [gotson/komga#1413]
### Steps to reproduce

Hi,

I just update the docker image from 1.X to the latest
the container wont start anymore

On a Synology DS918+ DSM 7.2.1-u3

### Expected behavior

Container start 'n run

### Actual behavior

container crash

### Logs

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher

### Komga version

latest

### Operating system

DSM 7.2.1-u3

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by SylvainDx** [comment]
I'll be damned, I searched twice before creating this issue....
once done I finally found #1404 witch is the exact same thing but this time for 1.10.3

**Comment by SylvainDx** [comment]
A forced reset of the container ix the boot trooble

**Comment by gotson** [comment]
Recreate the container from scratch. What you describe looks like some issues when updating with Watchtower.

**Comment by Metaman99** [comment]
Same Problem here after update from 1.10.1.
@SylvainDx : Can you please advise me, how to do a "force reset"? Will I loose my current komga database content? I run a Synology DS918+ with DSM 7.2.1-u4. Thank you.
