### ISSUE TITLE
Edit file name

### ISSUE THREAD

**Issue by giuanpadan74** [gotson/komga#1416]
### Describe your suggested feature

when I open the edit I can change not only the Title but also the name of the file, both for the collection and for the single title
![After](https://github.com/gotson/komga/assets/114602321/d5bcd6fc-d646-491a-81ca-4b070737dec1)
![Before](https://github.com/gotson/komga/assets/114602321/40a90b2e-074c-4235-b986-7c97723810cf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga does not touch the files for organization, only when removing duplicate pages or changing the file format. There's no plans to add such feature.
