### ISSUE TITLE
Ability to recognise different comic formats and organise them

### ISSUE THREAD

**Issue by abiud254** [gotson/komga#1420]
### Describe your suggested feature

I've always really liked how in apps like DC Universe Infinite they show the trade paperbacks and hardcovers an issues belonging to a series under that series but separated using tabs.

Do you think it's doable. to organise your library such that when you go to a series you can have tabs for issues, Trade Paperbacks, Hardcovers, Annuals, Specials if you have those formats in your local disk?

I was thinking using metadata but with how comic vine has organised these tpbs belonging to series, it makes it unconventional. 

Using name convention for subfolders seems better.

For example I could have a series and comics put in the series folder are recognised as issues. In the series folder I can have a Trade Paperback folder where I have the tpbs and have komga recognise them as tpbs belonging to that series, likewise with other formats like Specials, Hardcovers, Annuals.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Do you think it's doable. to organise your library such that when you go to a series you can have tabs for issues, Trade Paperbacks, Hardcovers, Annuals, Specials if you have those formats in your local disk?

There's no plans for that. You can use collections to organize different formats of the same series, or tags.
