### ISSUE TITLE
Volumes should support Genre fields

### ISSUE THREAD

**Issue by KevinTyrrell** [gotson/komga#1421]
### Describe your suggested feature

It's very common for a genre of a series to swap wildly between volumes. This is especially true of books/manga etc that are Anthologies (completely different story each volume). E.g. if Volume 1 was Genre: `Fantasy`, but Volume 2 has no such theme, calling the entire series as a Genre: `Fantasy` is a bit nonsense.

Solution: Add new field to `Volume` which behaves exactly like `Tags`, inheriting from the series by default.
E.g. If you had [Series X], you add Genre: `Fantasy` to X, you go to X -> Volume 1, edit, genres, you should be able to see `Fantasy`. You should then be able to override and remove `Fantasy`, such that each individual.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Solution: Add new field to `Volume` which behaves exactly like `Tags`, inheriting from the series by default.
> E.g. If you had [Series X], you add Genre: `Fantasy` to X, you go to X -> Volume 1, edit, genres, you should be able to see `Fantasy`. You should then be able to override and remove `Fantasy`, such that each individual.

I don't quite understand what you are proposing here. Komga does not have a `Volume` field.

**Comment by KevinTyrrell** [comment]
> > Solution: Add new field to `Volume` which behaves exactly like `Tags`, inheriting from the series by default.
> > E.g. If you had [Series X], you add Genre: `Fantasy` to X, you go to X -> Volume 1, edit, genres, you should be able to see `Fantasy`. You should then be able to override and remove `Fantasy`, such that each individual.
> 
> I don't quite understand what you are proposing here. Komga does not have a `Volume` field.

Sorry by `Volume` I mean `Number`, or at least that's what displays when I click on a book inside of a series:

![image](https://github.com/gotson/komga/assets/12791400/216bd661-3c79-458e-b02b-38efcb4b0832)

**Comment by gotson** [comment]
You can set tags per book also, see on the left.

**Comment by gotson** [comment]
Re-reading, it seems you would like to have Genre on Books. Your use case is very specific, and i am dubious about series changing genre entirely between volumes.

I'll be closing this, as i have no plans to implement this.
