### ISSUE TITLE
CBL incorrect match - same title, same volume different publishers

### ISSUE THREAD

**Issue by flips22** [gotson/komga#1424]
### Steps to reproduce

I don't know the root cause, but for this specific example it was brought up by a user of one of our CBL files, and I was able to re-create it on my system. Perhaps this is unique since it is the same volume name from two different publishers, but I'm guessing there.
I have series.json from mylar enabled.
I added two series to my library, both named Harbinger:
https://comicvine.gamespot.com/harbinger/4050-49539/
https://comicvine.gamespot.com/harbinger/4050-4827/
Import this CBL file:
https://github.com/DieselTech/CBL-ReadingLists/blob/main/Other/unsorted/Valiant%20Universe.cbl

### Expected behavior

The matching should be for the (2012) volume

### Actual behavior

It is matching to the (1992) volume.

I am able to get the correct match if I modify the series.json files see in the other details section

### Komga version

1.10.3

### Operating system

Docker, windows 10 web browser

### Installation method

Docker

### Other details

The series.json file has volume = 1 for both volumes, which makes sense I supposed because they are both different publishers in comicvine, I manually edited the json file for the 2012 volume to say volume 2 instead of 1.  I refreshed metadata and imported the CBL and it correctly matchined to the 2012 volume.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The `series.json` is not the reference, and depending on which options you chose in your library, the resulting metadata in Komga may differ.

Without knowing what was the metadata of each series in Komga, it is difficult to say what is happening.

If you look at https://komga.org/docs/guides/readlists/#import-read-lists-from-comicrack you can see how the matching works:

> Komga will try to match each book in the list in the following way:
> - part of a series named Series or Series (Volume)
> - where the number matches

The priority matching will be on a series name with the volume in brackets, and if not found will default to the series name without the volume.

Since your volume is 1, it won't be added in the series title, so the series are both called `Harbinger`, and thus the match is done on one or the other at random (depending on the sqlite rowid probably).

This is expected behaviour.

**Comment by flips22** [comment]
gotson, Thanks for taking a look.  I do have the library set to use import mylar metadata option selected. I checked the volume in the comicinfo.xml and the volume is set to the year.  I'm not sure exactly how to see the metadata that komga is using, but regardless, your description matches the behavior that I see.

Since both volumes are 1, no date is shown, so the CBL matches wrong, since there it doesn't have knowledge of the volume year.  Once I change the volume to two, then komga does look at the year and then the correct series is selected. Just as you describe.

I'm working with Diesel on the CBL repo, It doesn't sound like there is anything we can do at the present to help the users get the correct matches. I know there are discussions about a new  CBL format,maybe that will help address this issue in the long  term.

**Comment by gotson** [comment]
> I'm not sure exactly how to see the metadata that komga is using

just open the series in Komga :)

> It doesn't sound like there is anything we can do at the present to help the users get the correct matches. I

The CBL import is now using a 2-step approach, so it can get corrected. There is no silver bullet for this, there will always be conflicts and incorrect matches, and the user has to check the data before import.

**Comment by flips22** [comment]
Just for completeness here is what I see when I open the series in komga.  When I say I don't know what metadata it is using is because the year is showing in both instances, but based on your description the only year that is in parenthesis is being used for the matching.. 

When volume is set to 1 in series.json:

![Screenshot 2024-02-05 10 31 31 PM](https://github.com/gotson/komga/assets/1898114/6c51363f-0f68-4d57-8322-c8a1aff25581)

![Screenshot 2024-02-05 10 32 46 PM](https://github.com/gotson/komga/assets/1898114/f15f3c9e-ae51-44c2-9f0e-57cea201b73f)

After changing volume to 2 in series.json:
![Screenshot 2024-02-05 10 31 51 PM](https://github.com/gotson/komga/assets/1898114/c3e3bf6b-2a73-4c14-8932-53b9539877f7)
