### ISSUE TITLE
Infinite Pending task "GenerateBookThumbnail: 1"

### ISSUE THREAD

**Issue by DCS-MANGO** [gotson/komga#1426]
### Steps to reproduce

1. Generated new books DB (abot 5gb DB file)
2. finishing every books in the root folder "DATA", it still shows me  "1 pending task GenerateBookThumbnail: 1" on the left top corner (Under Komga Logo)
3. I tried to "Scan library files (deep)" and just Scan Scan library files", respectively.

### Expected behavior

I think when the scanning task is over, the moving yellow bar should not be shown.

### Actual behavior

Still shows me the moving yellow bar.

### Komga version

1.10.3-master

### Operating system

Docker in Synology

### Installation method

Docker

### Acknowledgements

- [x] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Logs don't show anything abnormal, but seems like tasks may still be running. For such a big DB from scratch you will need to wait a few days for all tasks to finish.

**Comment by gotson** [comment]
> However, I've waited for almost 2 months to generate DB.

specifying that information in the original ticket would have helped.

Can you get logs from the startup ?
- stop komga
- delete or rename the log file
- start komga
- wait for the symptom to appear
- get logs

**Comment by DCS-MANGO** [comment]
it solved. just file loading failure. sorry to bother you.
