### ISSUE TITLE
Custom Themes 

### ISSUE THREAD

**Issue by CodeeToasty** [gotson/komga#1427]
### Describe your suggested feature

Would be possible/feasable to add the possibility to customize the web-ui appearence? 
Maybe with some custom css edited by the user or with some input in the settings.

### Other details

For my personal use i would like the thumbnails to be bigger, maybe change font, stuff like this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is not possible with the current UI framework (Vuetify).
