### ISSUE TITLE
request for adult field

### ISSUE THREAD

**Issue by SebastianAviles** [gotson/komga#1429]
### Describe your suggested feature

I want a field to mark adults comix, and filter for the same field.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by PhilippKammann** [comment]
You can already set an age rating for a series, filter for the age rating and even restrict access according to the age rating.

**Comment by gotson** [comment]
As @PhilippKammann mentioned, there's already multiple ways to handle this. You can also use tags.
