### ISSUE TITLE
Mark a page for auto deletion while reading

### ISSUE THREAD

**Issue by mcoutinhof** [gotson/komga#1436]
### Describe your suggested feature

On Komga Web, while reading a book, let me mark a page for auto deletion, so I can easily remove trash pages from my library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Duplicate of #800
