### ISSUE TITLE
Frequent WARNs for Controller Endpoints With No Mappings

### ISSUE THREAD

**Issue by shin-go** [gotson/komga#1437]
### Steps to reproduce

1. Start up komga on an older version such as 1.8.4, 1.9.0, etc.. Preferably via docker.
2. Add a library with a few entries
3. Stop komga and update to 1.10.3 (current stable)
4. Start komga back up
5. After all startup routines complete, access komga while tailing the container logs (e.g.: `tail -f /var/lib/docker/containers/<ID>/<ID>.log`).
6. Perform normal activities in komga such as selecting a Library, selecting a Series within the library, etc. while observing the container logs

### Expected behavior

Controllers should not produce WARNs for mappings.

### Actual behavior

Event logs for komga produce messages that follow the pattern of:
```
{"log":"2024-02-23T18:21:12.049Z  WARN 1 --- [io-25600-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /series/09TS2H3Z2QWW2\n","stream":"stdout","time":"2024-02-23T18:21:12.146017254Z"}
```

There are also similar no mapping warns for non-resource paths like `/dashboard` and `/login`. While these are don't seem to be breaking anything, it is odd to see them occur.

### Logs

```
{"log":"2024-02-23T18:16:15.195Z  WARN 1 --- [io-25600-exec-3] o.s.web.servlet.PageNotFound             : No mapping for GET /series/09XVQGJ8EQNS4\n","stream":"stdout","time":"2024-02-23T18:16:15.252331004Z"}
{"log":"2024-02-23T18:21:12.049Z  WARN 1 --- [io-25600-exec-1] o.s.web.servlet.PageNotFound             : No mapping for GET /series/09TS2H3Z2QWW2\n","stream":"stdout","time":"2024-02-23T18:21:12.146017254Z"}
```

### Komga version

1.10.3

### Operating system

CentOS 7

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's how Spring works, you should not concern yourself about any kind of warning any application raises.
