### ISSUE TITLE
There is a problem that Chinese pictures cannot be displayed in epub

### ISSUE THREAD

**Issue by wushuo894** [gotson/komga#1442]
### Steps to reproduce

![Xnip2024-03-11_13-33-27](https://github.com/gotson/komga/assets/46311469/5722724b-039c-4b3a-9d51-4c2ee1abc513)

### Expected behavior

Normal display

### Actual behavior

Unable to display

### Komga version

1.10.3

### Operating system

ubuntu

### Installation method

jar

### Other details

[龙王的工作.zip](https://github.com/gotson/komga/files/14554413/default.zip)

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Thanks for the test file, there is a missing url decoding in the href elements of the spine and manifest.
