### ISSUE TITLE
For the Chinese index list, you can use Chinese Pinyin initials

### ISSUE THREAD

**Issue by wushuo894** [gotson/komga#1444]
### Describe your suggested feature

![Xnip2024-03-12_11-32-52](https://github.com/gotson/komga/assets/46311469/f0b0b486-b04f-4dce-a5fb-20996fd30b26)
For example, the Chinese pinyin for 魍魉之匣 is "wang liang zhi xia".

![Xnip2024-03-12_11-38-50](https://github.com/gotson/komga/assets/46311469/4d9672d6-5ca6-44f7-a70f-39e267d5d274)
Code implementation

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by wushuo894** [comment]
[人间系列01 零崎双識的人間試験.epub.zip](https://github.com/gotson/komga/files/14566942/01.epub.zip)
I have provided some Chinese epub for testing

**Comment by gotson** [comment]
Komga is agnostic to the language of publications. If you want to use Pinyin, edit the metadata in the files or in Komga directly.
