### ISSUE TITLE
[Feature Request] Webreader fit to screen

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#145]
I noticed this few days ago when using my other comic combination: kuboo+ubooquiti. Honestly I think once the "reading progress" is implemented I'll switch to Komga but anyway :).
Kuboo has the following options for the comic reader:
- Aspect Fill - in Komga Fit Heigth
- Aspect Fit
- Fit Width - same in Komga.

This situation presents when there are double pages in a comic otherwise "Full Width" works pretty good. 
For example in Kuboo it will look like this below:

![Screenshot 2020-04-25 at 21 05 38](https://user-images.githubusercontent.com/16859916/80294915-d97eaf80-873b-11ea-8acf-2b331f2f1a9f.png)
![Screenshot 2020-04-25 at 21 05 49](https://user-images.githubusercontent.com/16859916/80294917-dd123680-873b-11ea-90cf-643e62e87b51.png)
![Screenshot 2020-04-25 at 21 30 18](https://user-images.githubusercontent.com/16859916/80294950-442feb00-873c-11ea-8f73-b3e7f7d7c9b1.png)

You can see that each page is shown in their totality, no need to scroll to get full page. It seems that is doing a "Full Width" but  zooming the height so it fits in a single page. 

In Komga, the best option to accomplish this is "Fit to width" and it will look like this below: 

![Screenshot 2020-04-25 at 21 35 55](https://user-images.githubusercontent.com/16859916/80295061-5eb69400-873d-11ea-9245-5d1708fc5462.png)
![Screenshot 2020-04-25 at 21 36 02](https://user-images.githubusercontent.com/16859916/80295064-6ece7380-873d-11ea-8d6f-6c2016c15ec4.png)
![Screenshot 2020-04-25 at 21 36 08](https://user-images.githubusercontent.com/16859916/80295070-7ee65300-873d-11ea-9cc2-0a22c8d68078.png)

Not sure if you can appreciate the detail but page 1 and 3 need a little bit (maybe 5%) of scroll down to get the whole thing, page 2 doesn't need any scroll.
Probably this is no a big deal but wondering if Komga could have a similar mode in the scaling.

**Comment by gotson** [comment]
On Android you should give a try to Tachiyomi.

**Comment by cesalo** [comment]
I have tachiyomi installed and tried to use it when installed komga but there are many things that I don't like or just don't get used to:

- Having to to go to catalogue / komga. I wish there was a way to go into komga directly.
- Having to bookmark the comics that shows up in my library.
- The fact then when I go to a series the issues are listed and there are no thumbnails.
- etc

Maybe I just need to use it more and learn how to tweak it or my case (I own my library don't use all those manga services available in tachiyomi) is not ideal.
To be honest the komga web interface is perfect for me, once the reading progress is implemented I'll be able to switch 100% to it.
