### ISSUE TITLE
Rename a file in edit mode (pencil)

### ISSUE THREAD

**Issue by giuanpadan74** [gotson/komga#1457]
### Describe your suggested feature

Gotson is patient but I find this very important

Rename file vs rename comic in archive

using the pencil (edit) function you can change the name of the comic in the archive but not the name of the file

From the Import menu this function is available but you cannot work on folders that are already in a library

why don't you add the rename destination file function in the pencil (edit?)

It would be Columbus's egg, right?
![Immagine 2024-03-29 120352](https://github.com/gotson/komga/assets/114602321/d2659255-30fc-410b-8697-8d0b0892cf5d)
![Screenshot 2024-03-29 120132](https://github.com/gotson/komga/assets/114602321/c9b8aa4a-7682-4195-b53e-d36aae5cc2a6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There's no plans to modify filenames on disk.
