### ISSUE TITLE
Ability to customize logo within server settings page

### ISSUE THREAD

**Issue by arcastro** [gotson/komga#1458]
### Describe your suggested feature

It would be cool to have the ability to personalize the logo with any admin-uploaded image within the server settings page.

My current workaround is to replace the file in the docker image at:
* `/app/BOOT-INF/classes/public/img/logo.5a9779c6.svg`

But it would be good to officially support this sort of customization.

<img src="https://github.com/gotson/komga/assets/4576794/0b834d6c-5201-46d8-a715-bf614fb4e4c2" width="300px"/>
<img src="https://github.com/gotson/komga/assets/4576794/e6a0966c-081e-409c-9262-3c9eb1a3b2aa" width="300px"/>

But it's not too important, since the workaround works well enough. 
Feel free to close this issue if you feel strongly about all instances using the official logo.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
No plans for such feature.
