### ISSUE TITLE
Cannot delete files from Web UI

### ISSUE THREAD

**Issue by jcruiser89** [gotson/komga#1459]
### Steps to reproduce

I cannot delete files from either the library or from the media management duplicate files section.  When I click delete nothing happens and when I look at the console output it says path is not writable.  I am running just the jar in CMD.  I have tried as administrator and even installed the desktop app and copied over my config.  It still does the same thing.  The user I am logged in as has write access to the folder as I can open the folder and manually delete the items.  I was also running the latest sun java 8 JRE, I have changed to adoption 22 JRE and still the issue persists.

### Expected behavior

the file should delete

### Actual behavior

nothing happens and the log says the path is not writable.

### Logs

2024-03-31T19:54:04.542-07:00  INFO 7444 --- [taskProcessor-5] o.g.komga.application.tasks.TaskHandler  : Executing task: DeleteBook(bookId='07A9C8XZXSMEX', priority='8')
2024-03-31T19:54:04.549-07:00  INFO 7444 --- [taskProcessor-5] o.g.komga.domain.service.BookLifecycle   : Cannot delete book file, path is not writable: Z:\Manga - Comics\To Aru Majutsu no Index\To Aru Majutsu no Index # 143.cbz
2024-03-31T19:54:04.549-07:00  INFO 7444 --- [taskProcessor-5] o.g.komga.application.tasks.TaskHandler  : Task DeleteBook(bookId='07A9C8XZXSMEX', priority='8') executed in 5.938400ms

### Komga version

1.8.3 and 1.10.4

### Operating system

Windows 11

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Read the error message:

Cannot delete book file, **path is not writable**: Z:\Manga - Comics\To Aru Majutsu no Index\To Aru Majutsu no Index # 143.cbz

**Comment by jcruiser89** [comment]
> path is not writable

I did read the error message.  I am running komga as a user that has access to delete the file.  I can navigate there and delete it.  Komga just wont do it.  What are you telling me to do?
