### ISSUE TITLE
[Feature Request] Restrict page streaming feature by user

### ISSUE THREAD

**Issue by gide0n** [gotson/komga#146]
Hello,

I request the next feature for Komga, and that is to have the option to disable the "read" button on the interface so that users can only download the comic but not use the "web reader".
I requested this option via Discord talking to Gotson and he asked me to include it in Github.

Thank you very much!

**Comment by gotson** [comment]
Adding profiles by user for page streaming and download would probably be the best solution, with visual cues in the ui
