### ISSUE TITLE
parse volume from comicinfo.xml

### ISSUE THREAD

**Issue by FenTheFox** [gotson/komga#1467]
### Describe your suggested feature

for cbz files, komga correctly extracts title, chapter number, publish date, etc from the comicinfo.xml file. manga additionally can have a volume number and it would be nice to have that added to the metadata in komga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There is no such thing as volume field in Komga. Also, you misunderstand what Volume is in ComicInfo.xml, it is not the volume of the current manga, but an additional identifier of the series. See https://anansi-project.github.io/docs/comicinfo/documentation#volume
