### ISSUE TITLE
Bug Report: Admin User Receives 403 Error When Accessing Library

### ISSUE THREAD

**Issue by Kuan-Lun** [gotson/komga#1470]
### Steps to reproduce

1. Utilize two libraries, named `A` and `B`.
2. Create a user account named `alice` who is not an administrator.
3. Modify the access restrictions for library `A` but not for library `B`.
4. Append authorization using the URL [komg-url]swagger-ui/index.html.
5. Change the user role of `alice` to an administrator.
6. Attempt to use the REST API to retrieve information from library `B`.
7. Observe a 403 Error, indicating forbidden access to library `B` despite `alice` now being an administrator. **This error is unexpected as admin rights should grant full access.**
8. Change the user role of `alice` back to a non-administrator.
9. Modify the access restrictions for both libraries `A` and `B`.
10. Change the user role of `alice` to an administrator.
11. Successfully access library `B` after the access restrictions modification.

### Expected behavior

See step 7.

### Actual behavior

See step 6.

### Komga version

v1.10.4-master

### Operating system

Linux

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand what you are doing tbh

**Comment by Kuan-Lun** [comment]
Granting any account administrator permissions should allow the account to access all libraries. However, in practice, the libraries accessible are limited to those set for access before the administrator permissions were granted. I think this might be a bug.

**Comment by gotson** [comment]
can you provide which endpoints you tried that returned that error ?

**Comment by Kuan-Lun** [comment]
```
import requests  # type: ignore
from requests.auth import HTTPBasicAuth  # type: ignore

url = f"[komga-url]/api/v1/books/0FR5EDTZ1XAKA/metadata"
response = requests.patch(
    url, auth=HTTPBasicAuth("test@example.com", "test123"), json={"title": "new title"}
)
response.raise_for_status()
```

`requests.exceptions.HTTPError: 403 Client Error:  for url: [komga-url]/api/v1/books/0FR5EDTZ1XAKA/metadata`

I think `post` and `get` are fine.
