### ISSUE TITLE
Statistics pie in metrics tab showing no color or only 2 colors

### ISSUE THREAD

**Issue by Tonic8** [gotson/komga#1471]
### Steps to reproduce

just open the statistics tab, all pies are not colored as expected

### Expected behavior

multicolored pie allowing  a better visualisation

### Actual behavior

this is the result
![2024-04-14 15_49_36-Komga](https://github.com/gotson/komga/assets/18634390/80d9de4b-eff9-45b2-8464-e0209f722045)

### Komga version

1.10.2

### Operating system

windows10

### Installation method

Docker

### Other details

using chrome and edge on windows same effect.
i tested on firefox with linux, same result

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Works for me. This is very difficult to troubleshoot. Unless you can figure out what's going on yourself, this will not be worked on.

**Comment by Tonic8** [comment]
noted.

will try to check few things.

thanks.

**Comment by Tonic8** [comment]
noted.

will try to check few things.

thanks.
