### ISSUE TITLE
Suggest field values when entering a search field

### ISSUE THREAD

**Issue by zpaolo11x** [gotson/komga#1479]
### Describe your suggested feature

For search field values like "reading_direction", "status" etc that have a predefined number of options ("ongoing", "ended" etc) it would be great to have a menu popup with the choices, as it happens when filling the "Author" fields.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You should be using the filter panel for that kind of advanced search.
