### ISSUE TITLE
A way to integrate an integral between 2 volumes?

### ISSUE THREAD

**Issue by Lordingard** [gotson/komga#1480]
### Describe your suggested feature

Hello, I'm looking for a way to get Komga to correctly order a series containing both volumes and integrals. For example, a series of which I have the complete volumes 10 to 15 which I wish to place between volume 9 and volume 16. For the moment, Komga does not really seem capable of correctly ordering the books in this type of scenario. Maybe a feature to add (or maybe I miss something ?)?
Thanks !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Use the sortNumber at book level
