### ISSUE TITLE
List one-shots together with Series in search results

### ISSUE THREAD

**Issue by zpaolo11x** [gotson/komga#1481]
### Describe your suggested feature

If you search, for example, by author one shots are not shown in the "Series" result panel, but only in the "Books" list, where they can easily get lost in the number of volumes from regular series. It would be nice to have one shots listed together with series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
One shots are books not series, thus this makes sense.

**Comment by zpaolo11x** [comment]
I understand the semantics, and for sure it makes sense, but one-shots are listed together with Series in the main view, therefore I thought it would be consistent to show them in the results too. Well not a big deal, I'll just go back to put one-shots in their own one volume series.
