### ISSUE TITLE
[Bug] epub manga does not load any pages on windows

### ISSUE THREAD

**Issue by mutsumi63** [gotson/komga#149]
### Komga environment
- **OS**: Windows
- **Komga version**: 0.28.0

COMMENT Show
Book does not contain any pages

**Comment by gotson** [comment]
please share the complete `epub` file with me via Discord so i can have a look

**Comment by mutsumi63** [comment]
https://mega.nz/file/FxxzUTqK#PyzLYhq0nG-buNAk74Sd6asSIMeam9G9SK8e8AhQJlE
