### ISSUE TITLE
Refresh metadata does not update removed metadata from files

### ISSUE THREAD

**Issue by qx6ghqkz** [gotson/komga#1498]
### Steps to reproduce

Example 1:
1. Remove a metadata value for a book/series, e.g. remove `<Web>https://www.comixology.com/...</Web>` from a `ComicInfo.xml` file inside a `cbz` file, or simply set it to `<Web> </Web>`.
2. Refresh the metadata for that particular book.
3. The book still shows `www.comixology.com` in links.

Example 2:
1. Remove the `belongs-to-collection` meta property from every `epub` file in a series or set it so that it is empty.
2. Refresh the metadata for that series.
3. The name of the series that was overwritten via the meta property remains and does not revert back to the folder name. It has to be changed back manually.

### Expected behavior

If the metadata is removed from a file, I would expect that change to be reflected in Komga.

### Actual behavior

Refreshing metadata only works if a new value is provided for a particular metadata field, e.g. `<Web>example.org</Web>`. Simply removing the field or providing no value means the old value will be retained in Komga. It can be changed/removed in Komga manually of course, and it will not return upon refreshing the metadata once again as the metadata is no longer present in the file, but it is too much work to edit every single book individually to remove orphaned metadata entries.

### Komga version

1.11.0

### Operating system

Docker on Raspberry Pi OS Bookworm

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Expected behavior. `ComicInfo.xml` does not have a reliable way of expressing whether information is missing or is explicitly not present.
