### ISSUE TITLE
Allow decimal number usage for StoryArcNumber element in ComicInfo.xml

### ISSUE THREAD

**Issue by Shakahron** [gotson/komga#1500]
### Describe your suggested feature

Currently if you try to use a decimal number in the StoryArcNumber field, the book just won't be added to the readlist. It would be very helpful if books in readlist could be sorted with decimals numbers too, instead of having to renumber other books in the readlist, if this is possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
`StoryArcNumber` was made for Mylar, which generates the data. Can you clarify how you are using it?

**Comment by Shakahron** [comment]
> `StoryArcNumber` was made for Mylar, which generates the data. Can you clarify how you are using it?

Sure. I don't know anything about Mylar, I've never interacted with it for Komga. I'm using it in ComicInfo.xml files with the StoryArc and StoryArcNumber tags.
![Code_rnH2isCuzR](https://github.com/gotson/komga/assets/106402227/2336d6a3-4595-43b5-a4e7-1da96885a11f)

**Comment by gotson** [comment]
ultimately Komga uses integer based position for readlist items, and there's no plans to change that
