### ISSUE TITLE
Deletetion Issue

### ISSUE THREAD

**Issue by loli067** [gotson/komga#1510]
### Steps to reproduce

1. Add any manga to komga
2. Delete a chapter from that manga
3. It will remove the file but won't remove it from the list even if you refresh metadata, refresh library or close komga it will still be in the manga list.

4. Also if you add a manga, delete a chapter manually so by not using komga like using explorer it'll still be there and you can't remove it, it'll just say "Unavailable" if you try.

### Expected behavior

It should disappear.

### Actual behavior

It says "Unavailable" 
![image](https://github.com/gotson/komga/assets/133435955/fb76ce6c-9f7c-46ad-8bdb-6cc8d9989d00)

### Komga version

v1.11.1-master 

### Operating system

Windows 10

### Installation method

from download.komga.org

### Other details

I don't really know how to search for duplicates since this is pretty complicated, and there isn't a good keyword to search for. So if there is already a issue made, I'm sorry....

I will say tho I did check by typing "delete" and looking for issues and none were relevant.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by loli067** [comment]
Ahhhh... ALso if I'm just stupid, and there is a way to delete it please say the method.

**Comment by kiriya-aoi** [comment]
https://komga.org/docs/guides/trash/

**Comment by loli067** [comment]
Thanks kiriya-aoi
