### ISSUE TITLE
[Announcement] Now in the AUR

### ISSUE THREAD

**Issue by rhysperry111** [gotson/komga#155]
Hi, I have added komga to the aur as https://aur.archlinux.org/packages/komga/. This allows all users on Arch-based linux distros to install it easily. 
All this package does is download the jar and dependencies. It also provides an executable in `/usr/bin/komga` which has the contents:
```
#!/bin/sh
exec /usr/bin/java -jar '/usr/share/java/komga/komga.jar' "$@"
```
I would appreciate if you mentioned this package in order to make it easier for new user to get it downloaded

**Comment by gotson** [comment]
Thanks, that's great! Could you give me some more details on how that is used from a user standpoint?

I'd like to add a little bit of guidance for people on how to install that using your package. I also don't know anything about arch Linux, so if you could wrote a little paragraph that would fit in the documentation then I'll add it.

Also, since Komga is usually always running, is there a way to install your package as a service on arch? That would be great so it would start on boot.

**Comment by gotson** [comment]
I was also wondering, how does that work when there is a new Komga version available? Do you need to do something on your side, or the recipe will always fetch from github?

**Comment by rhysperry111** [comment]
From a user standpoint all people need to do is run `yay -S komga` (or any other AUR package mamanger). From then on they do everything normally, but instead of `jar -jar path/to/komga` they can just use `komga`.

I can create a systemd unit file if you want it to run at boot, but I am not to familiar with the application. What command would you want run to start it?

As for updates, I am watching this repo, so I will push an update whenever you do. If they are using an AUR package manager they should see this when they check for updates

**Comment by gotson** [comment]
Thanks, I'll add that to the doc and let you know once done so you can review if it makes sense or not.

**Comment by rhysperry111** [comment]
That looks great.

Do you still want me to include a SystemD unit file? The only problem that with that is it will be run as root by default - which is a bad idea.

**Comment by gotson** [comment]
I don't know if it's a thing on AUR packages to have them installed using SystemD, so i think for now it's OK. Thanks!

**Comment by rhysperry111** [comment]
Just thought I'd leave something here.

The speed of development with this is amazing! As an AUR maintainer I see every release and they are coming so quick. Well done
