### ISSUE TITLE
UpgradeIndex execution failed on every restart

### ISSUE THREAD

**Issue by lambdareader** [gotson/komga#1603]
### Steps to reproduce

deleted lucene folder
started komga.jar
restarted
restarted again

### Expected behavior

no exception / error in log

### Actual behavior

every restart komga throws an exception.
It says it failed to upgrade the series index and throws it again next restart.

EDIT:
i downgraded to 1.11.0 and it works.
After letting the index rebuild and restarting there are no errors.
so i started it with 1.11.1 and it works, but as soon as i delete the lucene folder the same error happens.

1.11.0 deleted lucene folder: rebuilds with no problems
1.11.1 deleted lucene folder: 'java.lang.IllegalStateException: do not share IndexWriterConfig instances across IndexWriters' on every restart

EDIT 2:
tried again deleting and rebuilding (with original database) on 1.11.0 and now it does throw errors.
sometimes just one time. and sometimes every restart.
It is very confusing since i use the same original database.

EDIT 3:
deleted lucene folder again but did not replace the database with the original. it is now fixed more or less. no error messages anymore. but if i try it again with the original database it throws errors.

### Logs

https://pastebin.com/jUWWEXJM

### Komga version

1.11.1

### Operating system

Linux

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
in the meantime you can delete the `lucene` folder and restart.
