### ISSUE TITLE
Errors related to an OPDS V2 client using Let's Encrypt certificates.

### ISSUE THREAD

**Issue by Tiny66** [gotson/komga#1607]
### Steps to reproduce

1.open cantook
2.add https domain
3.login site
4.download books
![70965787738e5e4ac684cf23dcb3231](https://github.com/gotson/komga/assets/48283218/991d814d-1efe-49c1-bc87-5604ad66bea9)

### Expected behavior

download complete

### Actual behavior

The provided request was not vaild

### Komga version

1.11.1

### Operating system

Linux

### Installation method

Docker

### Other details

https used Let's Encrypt certificates.
http is normal。

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Most likely an issue with your reverse proxy.

Do you have logs from Cantook or Komga ?

**Comment by Tiny66** [comment]
I see the komga logs,There are only visit records there，no any error logs。
and I access the api address,find this
![image](https://github.com/gotson/komga/assets/48283218/e5aefd45-0708-4128-b08f-28e74555c25e)
Is this normal? Accessing an SSL port via HTTP

**Comment by gotson** [comment]
that's typically a reverse proxy issue, you are most likely missing [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) in your configuration

**Comment by Tiny66** [comment]
It's work.Salute
