### ISSUE TITLE
When can komga support  Mobi format files ?

### ISSUE THREAD

**Issue by evetc824** [gotson/komga#1608]
### Steps to reproduce

When can komga support  Mobi format files ?

### Expected behavior

When can komga support  Mobi format files ?

### Actual behavior

When can komga support  Mobi format files ?

### Komga version

1.11.1

### Operating system

centos

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Never. mobi format is dead.
