### ISSUE TITLE
[Bug] Cannot login on remote (works on local)

### ISSUE THREAD

**Issue by mpedrero** [gotson/komga#161]
### Komga environment
- **OS**: Ubuntu Server
- **Komga version**: 0.29.1

- [X] **I am running Komga from the `jar`**
  - Java version: 1.8.0_201
- [X] **I have a problem in the web interface**
  - Browser (with version): Firefox/Chrome/IE/Edge (Latest)

### Describe the bug
I have a home server running Ubuntu Server 16.04 with nginx as reverse proxy and certbot to deploy https certs. If I launch the application (JAR) I can see the login page, but it refuses my credentials. If I access from local (i.e. Local Port Forwarding by using ssh) I can login without any issue. I have the same issue when using /swagger-ui.html to claim the user. Unreachable on remote, works on local.

### Additional context
Entry for nginx:
```

server {
    server_name komga.myremoteaddress.xxx;
    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:8080;
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }

    listen 80; # managed by Certbot

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/komga.myremoteaddress.xxx/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/komga.myremoteaddress.xxx/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

```

**Comment by gotson** [comment]
You have a reverse proxy with basic auth, and Komga also uses basic auth. 

You need to configure your proxy to not forward the basic auth headers of its own authentication to the apps behind.

**Comment by mvanlijden** [comment]
> configure your proxy to not forward the basic auth headers

And how does one do this in Swag/Nginx? 
I've tried options like:
proxy_set_header Authorization "";
or
proxy_pass_request_headers off;

None of these have had any effect...

**Comment by gotson** [comment]
> > configure your proxy to not forward the basic auth headers
> 
> And how does one do this in Swag/Nginx?
> I've tried options like:
> proxy_set_header Authorization "";
> or
> proxy_pass_request_headers off;
> 
> None of these have had any effect...

I don't know swag, with other reverse proxy like caddy it works. Check thd doc or Google it. It's not a Komga problem.

**Comment by mvanlijden** [comment]
> > > configure your proxy to not forward the basic auth headers
> > 
> > 
> > And how does one do this in Swag/Nginx?
> > I've tried options like:
> > proxy_set_header Authorization "";
> > or
> > proxy_pass_request_headers off;
> > None of these have had any effect...
> 
> I don't know swag, with other reverse proxy like caddy it works. Check thd doc or Google it. It's not a Komga problem.

That is a very easy answer and frankly very blunt. Komga is a media server (for manga, comics and books). If you look at people having media servers the most used combination are matched with Plex and many *arr search tools and Mylar for Comics. Common practice is also to have a combined web frontend using Swag(Nginx&LetEncrypt) with Organizr for access and Plex based SSO/Auth. This is not an odd one out, but something that many many user have and use with much ease. Also all tools withing this media server ecosystem try to work together and be compatible together. You it seem are trying hard to do the opposite. You tool is never a standalone, but always works within an ecosystem. You should try at least to support your users in being able to use your tool within the larger ecosystem.

I have tried to setup Caddy to work with all my services, but there is just not enough documentation and examples available to be able to fully get all my services working, like I almost instantly have with Swag/Organizr. Yes there is documentation on Caddy on their, but this is aimed for very different goals. I have yet to find a proper example of a server with complete proxy forwarding of subdomain a and subfolders to the many media servers with a combined Plex based auth structure.

**Comment by Kussie** [comment]
> > > > configure your proxy to not forward the basic auth headers
> > > 
> > > 
> > > And how does one do this in Swag/Nginx?
> > > I've tried options like:
> > > proxy_set_header Authorization "";
> > > or
> > > proxy_pass_request_headers off;
> > > None of these have had any effect...
> > 
> > 
> > I don't know swag, with other reverse proxy like caddy it works. Check thd doc or Google it. It's not a Komga problem.
> 
> That is a very easy answer and frankly very blunt. Komga is a media server (for manga, comics and books). If you look at people having media servers the most used combination are matched with Plex and many *arr search tools and Mylar for Comics. Common practice is also to have a combined web frontend using Swag(Nginx&LetEncrypt) with Organizr for access and Plex based SSO/Auth. This is not an odd one out, but something that many many user have and use with much ease. Also all tools withing this media server ecosystem try to work together and be compatible together. You it seem are trying hard to do the opposite. You tool is never a standalone, but always works within an ecosystem. You should try at least to support your users in being able to use your tool within the larger ecosystem.
> 
> I have tried to setup Caddy to work with all my services, but there is just not enough documentation and examples available to be able to fully get all my services working, like I almost instantly have with Swag/Organizr. Yes there is documentation on Caddy on their, but this is aimed for very different goals. I have yet to find a proper example of a server with complete proxy forwarding of subdomain a and subfolders to the many media servers with a combined Plex based auth structure.

Expecting the author to know how Komga fits into everyone's use case and support it like you are suggesting is frankly ridiculous. There is so many possibilities and so many different tools out there that it is nigh on impossible.  

At the end of the day he told you what is causing your problem and how to work around it, the solution of which is completely outside of Komga's sphere of influence. 

My non swag nginx config for my reverse proxy is:
https://gist.github.com/Kussie/264269ff892654eaac2bea1feec534cc

If SWAG/Nginx is too complicated for you, i suggest trying the nginxproxymanager to handle your reverse proxies.

**Comment by mvanlijden** [comment]
This isn't one of the many exotic setups. And I am not requesting to support all of these. But the services I'm using (Swag with Plex SSO linked to Organizr basic auth) are very common. Therefore there is a lot of information on it and on the combination of all these services.

At the end of the day the reply he gave me sounded more like a "get lost" and not an answer.

Looking at your config, the main difference is that use a subdomain and not a subfolder. I dislike subdomains because myself, but I will look into this. This might avoid the auth header being passed on by Organizr. Nginx (especially Swag) is not that complicated and the buildup is very logical. I do get forwarded to Komga as I see the big logo, but because of the auth headers messing with the login system I have no login field to continue. The redirect in startup to dashboard therefore do not work.

**Comment by gotson** [comment]
@mvanlijden I was gonna let that pass, but you keep pushing. First, there's no commenting on old issues that are already closed. Second, it's is not a Komga issue. Third, it's is NOT a Komga issue. Fourth, Google. Fifth, get that to the swag support, not here. We already told you what the problem is. So now you're getting that "get lost" answer.

Ask around, or come check on Discord, we always help people, if they ask nicely, when we can and when it's in the scope of this project.

You don't want to spend 1h to search for a solution for YOUR PROBLEM, because of YOUR SETUP? Fine. Get lost.
