### ISSUE TITLE
Files won't open in CDisplayEX ver 1.3.81

### ISSUE THREAD

**Issue by Tzuriel25** [gotson/komga#1619]
### Steps to reproduce

Add library per documented process
After syncing, try to open a file

### Expected behavior

After syncing, books should open when clicked

### Actual behavior

Syncing is successful and I see my libraries and all the books, but when I click the screen, it kind of flashes and that's it. nothing opens.  .cbr .cbz .epub

### Logs

2024-07-10T03:05:17.397Z  INFO 1 --- [task-223] o.g.k.i.security.LoginListener           : AuthenticationActivity(userId=0GKPW6N6Y5E4Z, email=xxxxx@x.com, ip=x.x.x.x, userAgent=com.progdigy.cdisplay/1.3.81 (6281; Android), success=true, error=null, dateTime=2024-07-10T03:05:17.397815460, source=Password)

### Komga version

Most current available on PikaPods

### Operating system

Android 13 Samsung S20 Ultra

### Installation method

other (please provide more details below)

### Other details

PikaPods

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please contact CDisplayEx support
