### ISSUE TITLE
Some .cbr files fail to be analyzed

### ISSUE THREAD

**Issue by Stack5453** [gotson/komga#1621]
### Steps to reproduce

1.  Add CBR files in library

### Expected behavior

Files should be scanned and analyzed correctly

### Actual behavior

Scan detects the file but there is an error that says:
"Unknown error while getting book's entries"

And I am unable to read the comic

### Komga version

1.11.1

### Operating system

Ubuntu

### Installation method

Docker

### Other details

The files are normal as far as I can tell - they are CBR files that work fine in CDisplayEx. If there are diagnostics I can run on the files happy to provide any information you need. In the Media Analysis errors section, it describes the files as:
"application/x-rar-compressed; version=4"

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The rar library may not work with all the files, suggest to convert to zip.
