### ISSUE TITLE
[Bug] Can't login, no default account

### ISSUE THREAD

**Issue by CyniKal007** [gotson/komga#163]
### Komga environment
- **OS**: Win 10
- **Komga version**: Latest 0.29.1
 

### Describe the bug
When launching the jar, it opens up fine and then I go to the localhost: <port number> throughmy browser and reach Komga site. But to sign in, it won't let me. This is a fresh install on this computer, and there's no admin user or passwordof any kind in the logs, at all, no matter what. 

### Steps to reproduce
1. Running jar file
2. Accessing port through browser
3. Try logging in/finding log in info

### Expected behavior
To log me in/find log in info and access site

### Actual behavior
No log in info or signing in, whatsoever

**Comment by gotson** [comment]
You probably launched one time before, the default users will be created only if no users exist. Delete the database and try again.

**Comment by CyniKal007** [comment]
The database comes up in the folder marked ~, yes? ive tried that. deleting the whole folder, even. nothing. same result

**Comment by gotson** [comment]
It depends on your configuration. On Windows it will be inside your User Profile directory.
