### ISSUE TITLE
'"/login?redirect=%2Fdashboard" to "/dashboard" via a navigation guard.' popup

### ISSUE THREAD

**Issue by Canttuchdiz** [gotson/komga#1630]
### Steps to reproduce

1. Go to your site
2. Login

### Expected behavior

There should be no popup and instead go smoothly to the dashboard.

### Actual behavior

There is a popup briefly before the dashboard loads once you login.

### Komga version

1.11.1

### Operating system

Windows 10

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
i don't quite understand what kind of popup you are talking about, can you maybe share a video of what's happening? The only popup that happens is when logging with OAuth2, is that what you are using ?

**Comment by Canttuchdiz** [comment]
![IMG_4212](https://github.com/user-attachments/assets/3badfa6c-4471-4547-a20a-3e932538993b)
This occurs the second I press sign in. And no, its not oauth2 just standard login.

**Comment by gotson** [comment]
can you get logs from the server and from the browser's console ?

**Comment by Canttuchdiz** [comment]
I've taken a couple of days to see if it happens again and so far it hasnt been replicated.
