### ISSUE TITLE
Can't load EPUBs under HTTPS

### ISSUE THREAD

**Issue by DCS-MANGO** [gotson/komga#1638]
### Steps to reproduce

can read epubs in HTTP, but can't in HTTPS

### Expected behavior

setup nginx or, caddy as you said, can not load in HTTPS.

### Actual behavior

I also found the similar issue "https://github.com/gotson/komga/issues/1453"
but i could not solve that.

### Komga version

1.11.2

### Operating system

synology linux

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
most likely a reverse proxy issue, please provide browser console logs, server logs, reverse proxy configuration or additional details

**Comment by DCS-MANGO** [comment]
Thanks a lot. 
Here are my logos.
![browser console log](https://github.com/user-attachments/assets/140c52c4-7d5c-4a2e-b034-6c0fc0d19921)
![reverse proxy setting](https://github.com/user-attachments/assets/f0dee9ae-a365-4365-bbdb-ca5ec7f8869f)

**Comment by gotson** [comment]
i can't read korean, but it seems there is some issue with CORS and 2 ports being used, 8342 and 8341. What are those 2 ports ?

**Comment by DCS-MANGO** [comment]
8342 is for HTTPS and 8341 is for HTTP. 

I made komga server on HTTPS and redirect to HTTPS.

**Comment by gotson** [comment]
> I made komga server on HTTPS

so the Synology reverse proxy connects to local Komga via HTTPS ? that kinda nullifies the need for a reverse proxy

**Comment by DCS-MANGO** [comment]
so, what should I do? I don't have any kinds of knowledges about network. 
Should I try with kind of Nginx(caddy) step by step?

**Comment by gotson** [comment]
the reverse proxy can normally handle TLS termination and use plain HTTP locally. You might need to lookup for some guides about how to do this with Synology's built in feature.

**Comment by DCS-MANGO** [comment]
Thanks for your help. 
I fixed the issue by just changing port 8342 to 443 for HTTPS.
It works!!
