### ISSUE TITLE
[mihon extension] library filters broken again

### ISSUE THREAD

**Issue by plumber-craic** [gotson/komga#1645]
### Steps to reproduce

1. open mihon
2. Browse
3. Sources
4. Komga
5. Filter
6. Libraries
7. <---- no libraries appear

### Expected behavior

It should list the libraries, and they should work as filters. 

### Actual behavior

Libraries are not listed. 

### Komga version

tachiyomi-all.komga-v1.4.57.apk, komga 1.11.1-master

### Operating system

Android 13

### Installation method

Docker

### Other details

(i know the instructions say extension issues should go on [this repo](https://github.com/keiyoushi/extensions) but they do not allow new issues or discussions)
This works in tachiyomi-all.komga-v1.4.51.apk. It was a bug previously - I reported a year or two back. [Here](https://github.com/gotson/komga/issues/417) is a feature request of someone experiencing what looks like the same bug. 

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment]
The issue template here points to the wrong repo, issues go to https://github.com/keiyoushi/extensions-source instead of https://github.com/keiyoushi/extensions
(which should be obvious from the ReadMe of the https://github.com/keiyoushi/extensions repository)
