### ISSUE TITLE
Search cleared on click away/change tabs

### ISSUE THREAD

**Issue by nstephenh** [gotson/komga#1655]
### Steps to reproduce

Type a query into the search field, then click out of the search or switch tabs in your browser.

### Expected behavior

I would expect the query to not be cleared, particularly when switching tabs. 

### Actual behavior

The search tab is cleared when clicking out of the search pop-up, including when switching tabs.

### Komga version

1.11.2-master

### Operating system

FreeBSD 13.1-RELEASE-p9 amd64 via TrueNas

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is the expected behaviour. Since the search box displays search results in a dropdown, when you click outside the searchbox, it clears. Else the results would remain.

If you need to switch tabs while searching, press enter or click "search all" to go to the search results page.

**Comment by nstephenh** [comment]
From the search result page, you can't edit the search query without re-typing it. 
I realize my use case is niche but I am occasionally browsing with a reading order in another tab, I type the series title, then forget the issue number, switch to the reading order, then switch back. It would be nice if it didn't clear when switching tabs, leaving the dropdown open.

**Comment by gotson** [comment]
> From the search result page, you can't edit the search query without re-typing it. I realize my use case is niche but I am occasionally browsing with a reading order in another tab, I type the series title, then forget the issue number, switch to the reading order, then switch back. It would be nice if it didn't clear when switching tabs, leaving the dropdown open.

this is not planned
