### ISSUE TITLE
[Bug] Short description

### ISSUE THREAD

**Issue by mathi54** [gotson/komga#166]
### Komga environment
- **OS**: Synology
![EPUB NOK](https://user-images.githubusercontent.com/61603812/82848049-e4bb2b80-9ef1-11ea-8d61-a52fc25c1315.jpg)

- **Komga version**: 29.1
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug

Hello, I currently have a problem, When I add an EPUB file, like a book.

The server only shows me the images not the text of the book, you must absolutely convert the EPUB file to PDF for this to work.

Thank you

### Log file
[EPUB NOK.txt](https://github.com/gotson/komga/files/4679237/EPUB.NOK.txt)

**Comment by gotson** [comment]
Ebooks are not supported in Komga, and will not be in a foreseeable future.
