### ISSUE TITLE
[Feature Request] Progressive Web App or fullscreen view

### ISSUE THREAD

**Issue by tahngarth** [gotson/komga#167]
### Is your feature request related to a problem? Please describe.
I love the web app version of Komga over the android and ios clients (and will especially want to use it once read tracking is implemented), but the web browser UI gets in the way.

### Describe the solution you'd like
I realized while using https://turnipprophet.io/ that another option exists, it seems to be Progressive Web App, https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs  This hides the web browser UI and make the experience a lot better.

**Comment by gotson** [comment]
This is something i considered, but it's quite complex to setup. A PWA is much more than just a full screen app. It needs to be able to work completely offline.

**Comment by tahngarth** [comment]
So I was messing around some more (read tracking! Thank you!) and stumbled across this: https://developers.google.com/web/fundamentals/native-hardware/fullscreen

I put 
<meta name="mobile-web-app-capable" content="yes">
into index.html and it actually seemed to do what I want in android! Samsung's browser especially was nice, chrome worked well enough, though it didn't disable the status ribbon a the top. I added the equivalent iOS meta tag and either it didn't work or I don't know what I'm doing (more of an android guy)

Progressive would still be preferable so comics can be read offline, but that looks to be a shit ton of work for an improvement that would likely only benefit a handful of people. This is appears to be a easy to implement middle ground.

**Comment by cesalo** [comment]
@tahngarth I'm currently using Komga in a Chomeos tablet (Pixel Slate). I did the following in Chrome: "More Tools"/"Create Shortcut" and enable the option "Open as Window" and pretty much works like any other app, full screen. etc. What you found, does it bring other features as well? If that's so I'd be very interested.

**Comment by tahngarth** [comment]
@cesalo Just tried this in my old toshiba chromebook, and that works pretty much spot on how I'd want it to. In android there's "add to homescreen", but by default it's basically just a shortcut to the site. With the above mentioned things, it will hide all of the browser UI elements (and even the top bar if using samsung browser) to make it fairly close to full screen, which is important on a phone, not much screen going on there.

**Comment by gotson** [comment]
Note for fullscreen: https://www.thewebflash.com/toggling-fullscreen-mode-using-the-html5-fullscreen-api/#:~:text=Simply%20call%20the%20requestFullscreen(),call%20the%20exitFullscreen()%20method

**Comment by gotson** [comment]
> Note for fullscreen: https://www.thewebflash.com/toggling-fullscreen-mode-using-the-html5-fullscreen-api/#:~:text=Simply%20call%20the%20requestFullscreen(),call%20the%20exitFullscreen()%20method

That doesn't work on iPhone though.

**Comment by DustbinK** [comment]
I would love to see progressive web app compatibility. It’s the only thing I’m missing in Komga! It’s so nice when web services support this - makes it feel like a native application and importantly for comics lets you use the full screen (minus notification bar.) Not as essential but related to make it feel native would be login persistence so I can just tap on the Home Screen icon and I’m in.
