### ISSUE TITLE
Cannot connect to Komga server locally, on device other than the host machine

### ISSUE THREAD

**Issue by cmdkev** [gotson/komga#1672]
### Steps to reproduce

1. Get IP address of host machine
2. On a different device on the same network, I am entering the following: `http://<ip-addr>:25600/opds/v1.2/catalog` or `http://<ip-addr>:25600/dashboard`

### Expected behavior

On the host machine, both of these resolve and show the intended pages.

### Actual behavior

On other devices, the requests resolve.

### Logs

I have no log files that show anything relevant. I cannot figure out how to enable debug for the logs (I have tried adding `logging.level.org.gotson.komga: DEBUG` to the top of my `application.yml`  in `%LOCALAPPDATA%/Komga`), but since the request is timing out, I'm not sure this would help anyway.

### Komga version

v1.11.3-master

### Operating system

Windows 11

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Looks like a networking issue on your LAN, nothing to do with Komga
