### ISSUE TITLE
Copy API-Key button not working

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#1675]
### Steps to reproduce

1. Generate new API Key
2. Click the "Copy to clipboard" button

### Expected behavior

Key gets copied to clipboard

### Actual behavior

Nothing happens and the browser console throws an error:

`TypeError: navigator.clipboard is undefined
    copyApiKeyToClipboard ApiKeyAddDialog.vue:90
    VueJS 4
    click VBtn.js:134
    VueJS 3
vue.runtime.esm.js:3049:16
`
![grafik](https://github.com/user-attachments/assets/467e0655-8673-4dff-8749-cea33857d397)

### Komga version

v1.12.0-master

### Operating system

Firefox on Windows 11

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you try another browser ?

**Comment by gotson** [comment]
Looks like you need to be on `https` website to use the clipboard API. Can you confirm whether you were using local `http` site, and can you try in `https` ?

**Comment by PhilippKammann** [comment]
I am on `http` and can't easily change to `https`

This is the error on Edge
![grafik](https://github.com/user-attachments/assets/ee0aeff1-8635-4cd7-8736-a496b1faf12f)

**Comment by gotson** [comment]
It seems this API is only available for https, and i suppose localhost. Not sure how to take this forward.

It seems there's hacks to use a hidden textarea to copy text, or i could just remove the copy button if the clipboard API is not available.

WDYT?

**Comment by PhilippKammann** [comment]
I would just remove the button if the API is not supported. A user can just copy it by hand; not like they have to do that often

**Comment by Bart274** [comment]
@gotson I use this code to copy values from a webpage to the clipboard:
```javascript
function copyToClipboard() {
  /* Get the text field */
  var copyText = document.getElementById("coords");

  /* Select the text field */
  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

  /* Copy the text inside the text field */
  document.execCommand("copy");

  /* Alert the copied text */
  //alert("Copied the text: " + copyText.value);
}
```
It's independent of the OS, browser & it works on both http and https.

**Comment by gotson** [comment]
> @gotson I use this code to copy values from a webpage to the clipboard:
> 
> ```js
> function copyToClipboard() {
>   /* Get the text field */
>   var copyText = document.getElementById("coords");
> 
>   /* Select the text field */
>   copyText.select();
>   copyText.setSelectionRange(0, 99999); /* For mobile devices */
> 
>   /* Copy the text inside the text field */
>   document.execCommand("copy");
> 
>   /* Alert the copied text */
>   //alert("Copied the text: " + copyText.value);
> }
> ```
> 
> It's independent of the OS, browser & it works on both http and https.

i don't really want to add that kind of workaround code if possible
