### ISSUE TITLE
Collection - Back Button Missing?

### ISSUE THREAD

**Issue by navidhegan** [gotson/komga#1678]
### Steps to reproduce

1. Create a Collection
2. Open the Collection
3. Attempt to return to the previous screen

### Expected behavior

Expectation that there be a 'back' button similar to the one provided when entering a series, allowing a return to the previous screen using a mouse click:

![image](https://github.com/user-attachments/assets/daee1e31-247e-4507-a944-994d7126dad4)

### Actual behavior

In a collection there is no back button, so returning to the previous screen is either by pressing back on the browser, or returning to the top level 'Library' using the navigation tree structure on the left (that may be closed).

![image](https://github.com/user-attachments/assets/e49657f0-6b6d-43aa-9bcd-3bfe5b4afd26)

I realise this may be by design, but hear me out, up until entering a Collection all navigation can be completed seamlessly simply clicking with the left navigation panel hidden... 

A typical User experience (arguably) is that clicking back on a browser is undesirable as it can cause issues reloading a page, so returning to a previous page requires the left navigation panel and a return to the top level navigation for the library, introducing several clicks if you prefer to keep the left navigation hidden.

### Komga version

v1.11.3-master

### Operating system

Ubuntu 24.04 LTS (GNU/Linux 6.8.0-39-generic x86_64)

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by navidhegan** [comment]
Apologies, this seems pretty petty reading it back, am hoping it will enhance the user experience

**Comment by navidhegan** [comment]
I should add that the back button would return the user to the list of Collections

**Comment by trois-six** [comment]
Maybe we could have a button to see the collections directly in the menu?

**Comment by gotson** [comment]
the arrow is not a back button, it's an upper level button:
- If you are in a book, it brings you back to the series
- If you are in a book but from a readlist, it brings you back to the readlist.
- If you go into a series from a collection, the button will bring you back to the collection you came from.

Collections and readlists are top level items, they don't belong in a particular library.

If you want to go back, use your browser's back button.

**Comment by navidhegan** [comment]
Wouldn't the list of collections be the top level item, so a return from the collection to the list of collections makes sense.

If you're using a touch interface switching from it to having to use the browser controls is jarring.

**Comment by gotson** [comment]
> When you're in a collection you're missing the controls to switch between 'recommended, browse, collections, read lists', so it acts as a dead end.

those are Library level controls, when you are in a collection those don't make sense in the current context anymore

**Comment by navidhegan** [comment]
I think maybe I'm using Collections incorrectly, at the moment I'm using it to represent what used to be my folder structure on a harddrive (i.e. grouping together comics relating to Aliens, Avengers, Venom, etc), I need to embrace using the metadata to perform the same task... though might mean I need to investigate adding tags to my collection or something.

If you think there doesn't need to be a back button that's okay, just thought I'd ask/explain my thinking. Thanks for hearing me out :)
