### ISSUE TITLE
[Feature Request] Tachiyomi Extension Update to Show Chapter Numbers with Titles

### ISSUE THREAD

**Issue by flips22** [gotson/komga#169]
Following up on our conversation on discord.  When we originally spoke, I thought it was more of an issue than it really is.  I had some issues with my library that was causing some headaches where I had some books in a series as limited and some as main series. I still think it is a good idea

### Is your feature request related to a problem? Please describe.
When I open up a series in Tachiyomi with the source title display mode it is difficult to tell where in the series I am, or even if I am looking at the list as ascending or descending.  You can switch to chapters, but then you loose the title visibility. 

### Describe the solution you'd like
I would like to see an option in the Komga extension that will concatante issue number with title.  Such as: ### - [title] (file size)
010 - Toil and Trouble Part 1 (88.4MB)

It seems like if the title is blank (from comicvine) the display is the filename.  I think putting the issue number if front of the file name would be fine:
009 X-Men Blue 009 (2017) (Digital) (Zone-Empire) (86.5 MB)

### Describe alternatives you've considered or other apps that can do what you want
You are able to switch to just chapter view to see the list of issue numbers, but you lose the view to the title which is nice.

### Additional context
Here's a sample view with titles:
![Screenshot_20200523-194840](https://user-images.githubusercontent.com/1898114/82900961-e0f3cd00-9f22-11ea-951f-9b962580c66a.png)

Here I have a random issue 57 showing up first.  I think this is something up with my library, but this was part of the reason I thought this was a bigger issue than it is.
![Screenshot_20200517-123001](https://user-images.githubusercontent.com/1898114/82901171-2e703a00-9f23-11ea-9b7e-c37fdf3831fd.png)

Here's an example of how another extension does it.  They don't show the title, but they do show the issue number.  I think showing the title is a very nice feature as it gives you some orientation as to where you are in the series as you aren't able to see the cover images.

![Screenshot_20200523-195036](https://user-images.githubusercontent.com/1898114/82901317-5b245180-9f23-11ea-85b8-b56220d124d5.png)

Thank you again for all your efforts on this project.

**Comment by gotson** [comment]
Thanks, it is a simple change in the extension code. I do something similar already on the OPDS feed for Chunky.

Regarding your issue 57 it's most likely coming from the `comicinfo.xml`.

**Comment by prysme01** [comment]
+1 it would be nice to have the chapter number concat with the title and also have a consistant sort order between series

**Comment by gotson** [comment]
In Tachiyomi the sort order is independent from the title. Books are sorted by _sortNumber_ already.
