### ISSUE TITLE
[Feature Request] Tachiyomi support for libraries

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#171]
Hello, 

First of all, I would like to thank you for Komga, this is awesome, I was searching and waiting for this for long time ! So thank for your work and for your time.

Then, I am using tachiyomi , which has great features, and even if komga integration is not very neat (due to the nature of tachiyomi extension) , this is fine so far.

So I move my +5K books (BD, comic, manga) right after discovering Komga , I naturally use the libraries to store Manga , BD and Comic separately, I've also using user right management to create account for my kids to specific library for their ages BUT Tachiyomi and the komga extension do not manage libraries. everything is mixed up. 

So I was wondering if this was a limitation with the extension API or a missing feature in the extension ?

Thanks.

**Comment by gotson** [comment]
Tachiyomi supports the libraries of Komga natively through the extension, you can use the filter function to filter by library, and also by series status.

![Screenshot_20200528-081559](https://user-images.githubusercontent.com/2139133/83084432-7de96e00-a0bb-11ea-8d6e-6122717ae50b.jpg)
