### ISSUE TITLE
Trying to open an EPUB from a collection fails

### ISSUE THREAD

**Issue by KarolS** [gotson/komga#1718]
### Steps to reproduce

1. Have a library containing oneshots in EPUB format
2. Create a collection containing one of those EPUBs
3. Navigate to the collection
4. Navigate to the book inside the collection
5. Try reading the book (by clicking either of the READ buttons)
The URL looks like this: http://localhost:25600/book/0HE82G5HZK5RV/read-epub?context=COLLECTION&contextId=0HE96QSRZK9JZ

### Expected behavior

The book opens and can be read.

### Actual behavior

- A request is sent to http://localhost:25600/api/v1/readlists/0HE96QSRZK9JZ yielding 404
- Screen goes blank.
- The browser console shows the following stacktrace:
```
Uncaught (in promise) Error: An error occurred while trying to retrieve readList: 404 NOT_FOUND
    getOneReadList komga-readlists.service.ts:49
    setup EpubReader.vue:415
    mounted EpubReader.vue:148
    VueJS 18
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    t vue-router.esm.js:2084
    t vue-router.esm.js:2091
    Ge vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2397
    t vue-router.esm.js:2084
    t vue-router.esm.js:2088
    c vue-router.esm.js:2384
    Ue vue-router.esm.js:2162
    c vue-router.esm.js:2362
    t vue-router.esm.js:2087
    t vue-router.esm.js:2091
    t vue-router.esm.js:2088
    c vue-router.esm.js:2384
    88691 router.ts:312
    c vue-router.esm.js:2362
    t vue-router.esm.js:2087
    t vue-router.esm.js:2091
    t vue-router.esm.js:2091
```

### Komga version

v1.14.0-master

### Operating system

Windows 10

### Installation method

from download.komga.org

### Other details

- Opening the same EPUB from the BROWSE tab works fine.
- Manually removing contextId from the URL allows reading the book.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
thanks, it was fixed for the Divina reader but not the Epub reader.
