### ISSUE TITLE
Bulk edit metadata number sort increment

### ISSUE THREAD

**Issue by calcul0n** [gotson/komga#1727]
### Steps to reproduce

1. Select several books and click bulk edit metadata. 
2. Change the value in any of the sort number fields.
3. Click the 'increment all by 1' icon.

### Expected behavior

The number in the edited sort field should have been numerically incremented by 1.

### Actual behavior

The number 1 has now been appended to each of the fields edited rather than +1 being numerically added, it seems the value here is being treated as a string and not a number.

### Komga version

v1.14.0

### Operating system

Windows 11

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
sounds like a Javascript quirk, everything is typed as `number`
