### ISSUE TITLE
[Bug] Books not showing properly in the webui

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#174]
### Komga environment
OS: QNAP NAS Linux
Komga version: v0.32.0
 I am running Komga from the jar
Java version: Java 8 installed
 I have a problem in the web interface
Browser (with version): Edge Chromium Canary and Chrome, both latest version

### Describe the bug
Since version 31, series with high amount of books don't appear correctly, nor completely anymore. A full installation done from scratch, I could see the full list of books appearing, but once the full load completed, next time going into a serie I have the same issue again

![image](https://user-images.githubusercontent.com/45739159/83574416-bd85df00-a52d-11ea-84d5-304ee82eddaf.png)

Hovering the mouse on the "not visible" one show a loading icon forever. The missing one don't even display the empty book placeholder.

### Expected behavior
See all books

### Actual behavior
See only few books, with empty placeholders in the visible list. Every serie stop around the 20th book

**Comment by gotson** [comment]
In order to troubleshoot the problem, could you provide:
- full logs of the server when the problem happen
- a HAR extract from the browser ([here is a tutorial](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) on how to generate one)

**Comment by Flyingfufu** [comment]
Right, will do so this evening when I have access to the server again.

Envoyé de mon iPhone
________________________________
De : Gauthier <notifications@github.com>
Envoyé : Wednesday, June 3, 2020 2:14:02 AM
À : gotson/komga <komga@noreply.github.com>
Cc : Flyingfufu <fabien.fuster@sfr.fr>; Author <author@noreply.github.com>
Objet : Re: [gotson/komga] [Bug] Books not showing properly in the webui (#174)


In order to troubleshoot the problem, could you provide:

  *   full logs of the server when the problem happen
  *   a HAR extract from the browser (here is a tutorial<https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting> on how to generate one)

**Comment by gotson** [comment]
Hi, i just released [v0.33.0](https://github.com/gotson/komga/releases/tag/v0.33.0) which brings pagination, this should remove your problem altogether.

I let you give it a try, and close the issue if everything works with that new version.

**Comment by Flyingfufu** [comment]
Ok, i ´ll advise back later today.

Thanks

Envoyé de mon iPhone
________________________________
De : Gauthier <notifications@github.com>
Envoyé : Wednesday, June 3, 2020 10:46:11 AM
À : gotson/komga <komga@noreply.github.com>
Cc : Flyingfufu <fabien.fuster@sfr.fr>; Author <author@noreply.github.com>
Objet : Re: [gotson/komga] [Bug] Books not showing properly in the webui (#174)


Hi, i just released v0.33.0<https://github.com/gotson/komga/releases/tag/v0.33.0> which brings pagination, this should remove your problem altogether.

I let you give it a try, and close the issue if everything works with that new version.

**Comment by gotson** [comment]
probably linked to #177

**Comment by gotson** [comment]
Please give a try to `0.33.1`, it should fix your issue.

**Comment by cesalo** [comment]
It fixed it for me. Thanks.

**Comment by Flyingfufu** [comment]
Confirmed here also as fixed. Thanks for the quick action !
