### ISSUE TITLE
cannot scan library for new series

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [gotson/komga#1742]
### Steps to reproduce

1. Have a library set up
2. Put a new series in the library folder or add a book to existing series folder
3. Scan library files

### Expected behavior

New series is added to the library or new book is added to an existing series.

### Actual behavior

A new series with no books is created.
In case of existing series, the series page has no books but all the series metadata is visible. Number of books displayed does not include the new book.

### Logs

```
ERROR 1 --- [io-25600-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: getCreatedDate(...) must not be null] with root cause

java.lang.NullPointerException: getCreatedDate(...) must not be null
        at org.gotson.komga.infrastructure.jooq.main.BookDtoDao.toDto(BookDtoDao.kt:516) ~[classes/:1.14.1]
        at org.gotson.komga.infrastructure.jooq.main.BookDtoDao.access$toDto(BookDtoDao.kt:49) ~[classes/:1.14.1]
```
Rest skipped; I will provide the log if needed.

### Komga version

1.14.1-master

### Operating system

Manjaro Linux

### Installation method

Docker

### Other details

Making the null `CREATED_DATE` and `LAST_MODIFIED_DATE` fields in `BOOK_METADATA` not null helps. All the numbers and sort numbers are 0, but rescanning the library fixes the numbers and adds the page count for every book.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
please provide the full log

**Comment by papaj-na-wrotkach** [comment]
[komga.log](https://github.com/user-attachments/files/17457633/komga.log)

First 4 exceptions are from when the library is scanned. The last one is from when I tried to enter the broken series page in web ui.

**Comment by gotson** [comment]
there must have been some issues prior to that, the database is in a state where it should not be. Those columns are set with a default when rows are created.

Without details of what happened there's not much to be done. If you are keen to try and fix it, i can help you through the steps, else you could just delete the library and start again.

**Comment by papaj-na-wrotkach** [comment]
After examining the `BOOK_METADATA` table schema, I think I may have accidentally deleted keys, foreign keys, indexes, and other things from the `BOOK_METADATA` structure.

I restored the structure from one of my backups using DataGrip's structure diff tool.

Sorry to bother you with a problem not caused by Komga application.
