### ISSUE TITLE
[Feature Request] Tachiyomi komga password field

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#175]
Is it possible to hide the password in the password field in tachyomi ?

When you have set up komga account by entering all the address/username/password, if you go again in the setup komga account you can see the password in plain text. Kind of unpleasant when you give your tablet to your kid :)

**Comment by gotson** [comment]
It is not possible at the moment, this is a Tachiyomi limitation.

**Comment by gotson** [comment]
This has been addressed here : https://github.com/inorichi/tachiyomi-extensions/issues/3539
