### ISSUE TITLE
[Feature Request] Tachiyomi komga chossing a name for 3 differents accounts

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#176]
I see that you can add 3 komga server/account (komga EN, komga 2 EN;, komga 3 EN), would it be possible to rename at least a part of the account ?
I don't like the way the plugin in handlind the komga librairie (filtering), it could be much convenient to play with the 3 differents account to split my manga, BD and comic libraries.

**Comment by gotson** [comment]
_Please use the issue templates for next time._

This is a Tachiyomi limitation, sources need to have a hardcoded name. I have submitted a [pull request](https://github.com/inorichi/tachiyomi/pull/2196) to handle that kind of configuration, but it is a complicated change which has impacts on all extensions, and hasn't been integrated yet.
