### ISSUE TITLE
Komga Java no system tray to manage it

### ISSUE THREAD

**Issue by molitar** [gotson/komga#1762]
### Steps to reproduce

I run komga.jar but it has no system tray icon.  Where is the system tray icon?

### Expected behavior

I expect to see the system tray running for Komga. 

### Actual behavior

No system tray icon showing for ease of management of Komga

### Komga version

1.14.1

### Operating system

WIndows 10

### Installation method

jar

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You need to use the Desktop Application if you want a system tray icon, see https://komga.org/docs/installation/desktop
