### ISSUE TITLE
Image epub reading becomes very slow

### ISSUE THREAD

**Issue by Konne06** [gotson/komga#1763]
### Steps to reproduce

Since the support of text epub files, it has become very difficult to read epub files of images (e.g. manga epub) online. Each page needs to be loaded separately, which makes each page turn take quite a long time.

### Expected behavior

It seems that the new version of the analysis file will analyze all files as text epub.

### Actual behavior

The epubs analyzed before the version update don't seem to have this problem.

### Komga version

1.14.0

### Operating system

WIN11

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
it depends on the files. Komga uses a heuristic to determine whether the epub only contains images or not. Can you share some of the files not detected as image epubs ?

**Comment by Konne06** [comment]
https://drive.google.com/file/d/1SIBylYYXMyoTpgCb_bpGUsG7vECbkRGG/view?usp=sharing
You can try this epub.
In older versions of komga, which don't yet support text epubs, manga epubs are read properly.But now in the current version the manga epub seems to get loaded page by page, one by one, which makes it very difficult to read. It takes several seconds of waiting each time you turn the page.

**Comment by gotson** [comment]
that book is not pre-paginated, thus it cannot be rendered using the Divina reader. I see it's coming from Calibre, and the EPUB metadata is wrong.

For a comic/manga in EPUB, the book should be marked as pre-paginated / fixed layout.

In EPUB3 there should be a `<meta property="rendition:layout">pre-paginated</meta>` under the `<metadata>`.
