### ISSUE TITLE
White updating Custom Roles through the API the same "Name" can be added multiple time

### ISSUE THREAD

**Issue by donotos** [gotson/komga#1778]
### Steps to reproduce

1. Create a custon role with the API.
2. Send the same role/name combo a second time

### Expected behavior

The same name should not be added twice.

### Actual behavior

the same name is added multiple time in the name field
![Capture d'écran 2024-11-29 212035](https://github.com/user-attachments/assets/a6b91175-c037-4ef4-ba44-fb6dc028e6c5)

### Komga version

1.14.1

### Operating system

Debian 12

### Installation method

Docker

### Other details

some other fields accepting multiple entry like genre or tags are behaving as expected, ignoring duplicate entry.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by donotos** [comment]
exemple of a payload that will add 5 time the same name:
{
  "authors": [
    {
      "name": 48962893190,
      "role": "MU_ID"
    },
    {
      "name": 48962893190,
      "role": "MU_ID"
    },
    {
      "name": 48962893190,
      "role": "MU_ID"
    },
    {
      "name": 48962893190,
      "role": "MU_ID"
    },
    {
      "name": 48962893190,
      "role": "MU_ID"
    }
  ],
}

**Comment by gotson** [comment]
> The same name should not be added twice.

there is no such control, whether for custom roles or default roles. It's up to you to send correct metadata.
