### ISSUE TITLE
The application has experienced an internal error and must quit

### ISSUE THREAD

**Issue by Shortround1897** [gotson/komga#1783]
### Steps to reproduce

Try to launch the application

### Expected behavior

Application launches

### Actual behavior

![image](https://github.com/user-attachments/assets/ca3b6b9f-9dd2-415b-a877-a3840b31bd29)

### Logs

No logs

### Komga version

Unknown, downloaded today

### Operating system

Windows 11

### Installation method

Microsoft Store

### Other details

I've tried the microsoft store, and the download version, both give the same error

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
can you provide the logs ?

**Comment by Shortround1897** [comment]
There were no logs, I think it didn't have permission to modify the folder it was trying to create in, but I ran as administrator and it would start up properly.
