### ISSUE TITLE
Cannot import Google QR code

### ISSUE THREAD

**Issue by deanfourie1** [gotson/komga#1785]
### Steps to reproduce

1. export QR code from google
2. attempt to import it to 2fauth

### Expected behavior

for it to import the 2fa codes.

### Actual behavior

I get the error.

Invalid or Unreadable Google Authenticator data.

### Logs

I cant see any logs in docker compose.

### Komga version

honestly I cannot find it but its latest stable docker image

### Operating system

Debian 12

### Installation method

Docker

### Other details

Just let me know what else you need.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga does not integrate with 2FA. I don't know what you are trying to do, but i doubt it has anything to do with Komga.

**Comment by deanfourie1** [comment]
Oh shit sorry I posted on the wrong repo.
