### ISSUE TITLE
Download into zip instead of cbz

### ISSUE THREAD

**Issue by bebeidon** [gotson/komga#1788]
### Steps to reproduce

1. Using Iceraven or Chrome on Android 14
2. Download cbz book
3. Iceraven downloads as *.zip; Chrome downloads in *.cbz.zip

### Expected behavior

I expect original file format cbz. No problems with .cbr files.

### Actual behavior

wrong filenames ending in *.zip and *.cbz.zip

### Komga version

1.14.1

### Operating system

Android

### Installation method

Docker

### Other details

Installed on Synology NAS used with Android Client. Komga is running on http in my LAN only. This Issue seems to be opened before but with no solution 3 years ago.

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Most likely a browser issue.

Komga sets the following response headers when you download a file:

`Content-Disposition: attachment; filename="=?UTF-8?Q?Space=5FAdventures=5F01.cbz?="; filename*=UTF-8''Space_Adventures_01.cbz`

`Content-Type: application/zip`

**Comment by bebeidon** [comment]
The issue is not fixed, why just close? So there is just no browser on Android able to download cbz files?

**Comment by gotson** [comment]
> The issue is not fixed, why just close? So there is just no browser on Android able to download cbz files?

the HTTP headers are correct. The browser is at fault.

**Comment by bebeidon** [comment]
No, I can download cbz files from other websites without problem and correctly, so this is not a browser issue, it's a komga issue.

**Comment by gotson** [comment]
> No, I can download cbz files from other websites without problem and correctly, so this is not a browser issue, it's a komga issue.

unless that translates into something actionable, like explanations from the browser's developer about why they can't download the file properly, it will remain as is.

**Comment by bebeidon** [comment]
Oh so now the Iceraven and Chrome developers have to step up to you and explain to you, why YOUR download is not working? Or how does this work? Usually you should try to fix issues like this and not just close them and point fingers when it's clearly not the browser's issue when other cbz downloads work just fine.

**Comment by gotson** [comment]
> Oh so now the Iceraven and Chrome developers have to step up to you and explain to you, why YOUR download is not working? Or how does this work? Usually you should try to fix issues like this and not just close them and point fingers when it's clearly not the browser's issue when other cbz downloads work just fine.

Komga follows the HTTP standards. A quick google search shows that Android had issues following this standard, and it is still not fixed.

**Comment by gotson** [comment]
@bebeidon i have deleted the second issue you created, while totally ignoring that i closed this one. Create one more duplicate and you will be blocked.
