### ISSUE TITLE
[Feature Request] Dark Theme

### ISSUE THREAD

**Issue by kenjidev** [gotson/komga#179]
Hello,
It is possible in a future version have a  dark theme ?
At  night, white background is little violent for eyes with web ui :)
thank for you very good job

**Comment by edwinbadillo** [comment]
I'm going to second this. I've never worked with VueJS  but It seems that the default dark theme for Vuetify isn't half bad. I recompiled with it and a quick update to the toolbar and got this.

https://imgur.com/a/a8DhCEo

On another note,  I really appreciate the time you are dedicating to this project. Thank you very much!
