### ISSUE TITLE
Error: Could not find or load main class org.springframework.boot.loader.launch.JarLauncher

### ISSUE THREAD

**Issue by grosejon** [gotson/komga#1792]
### Steps to reproduce

Updated to latest release 1.15.0, container starts but logs just say 
Error: Could not find or load main class org.springframework.boot.loader.launch.JarLauncher

### Expected behavior

No errors

### Actual behavior

Receive repeated error message
Error: Could not find or load main class org.springframework.boot.loader.launch.JarLauncher

### Komga version

1.15.0

### Operating system

Docker

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The container image entrypoint has changed, you need to recreate the container.

**Comment by jdzido** [comment]
I had this same problem and this was first result on google.

I'm using Portainer for managing docker. For me recreating image was not fixing problem and I had to manually update entrypoint on container config.

That was the old ENTRYPOINT:
`java --enable-preview --enable-native-access=ALL-UNNAMED org.springframework.boot.loader.launch.JarLauncher --spring.config.additional-location=file:/config/`

This is new working ENTRYPOINT for gotson/komga:1.15.1
`java --enable-preview --enable-native-access=ALL-UNNAMED -jar application.jar --spring.config.additional-location=file:/config/`

**Comment by grosejon** [comment]
@jdzido How did you manually update that? I don't see entrypoint in the documentation as something I can change in the compose file.
