### ISSUE TITLE
[Bug] JVM crash on fresh container

### ISSUE THREAD

**Issue by artyte** [gotson/komga#1808]
### Steps to reproduce

1. Using mac mini m4
2. Spin up a komga container (see compose file)
[docker-compose.yml.txt](https://github.com/user-attachments/files/18266583/docker-compose.yml.txt)

### Expected behavior

Container to run

### Actual behavior

See logs file

### Logs

[hs_err_pid1.log](https://github.com/user-attachments/files/18266585/hs_err_pid1.log)

### Komga version

1.15.1

### Operating system

Mac OS Sequoia 15.2

### Installation method

Docker

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by chantalgo** [comment]
I had exactly the same issue on a mac mini M4 with sequoia 15.2, even running a tag that was running on my previous intel mac (1.14.0)

**Comment by artyte** [comment]
> I had exactly the same issue on a mac mini M4 with sequoia 15.2, even running a tag that was running on my previous intel mac (1.14.0)
> 
> Some maybe related info: [corretto/corretto-21#85](https://github.com/corretto/corretto-21/issues/85)
> 
> Using `JAVA_TOOL_OPTIONS="-XX:UseSVE=0"` on the docker-compose allows it to run

This works! Thank you!
