### ISSUE TITLE
[Feature Request] Display aggregated books information on Series browsing screen

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#181]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like
As Komga group book by series and use the first book picture as the series picture, we can also have the description of the serie displayed on the serie screen taken from the first tome description if it exists. also have a small bunch of information about the series grabbed from the different books that compose the series.
Number of book, count, date of the publication (first and last date), name of authors/sceneraist/colorist publisher, genre

Today the serie page is quite empty (STATUS ongoing) , so maybe having few consolidated information could be interresting.

Also having a link by scenarist/penciller that lead to a page with all the books linked could be nice.

**Comment by gotson** [comment]
This is a list of fields that should be aggregated from books to series, and how:
- Authors: merge all authors from all books, removing duplicates. The list could get very long for a big series, the client will be responsible of showing only part of the data for example. We may omit Cover artists.
- Release year: the earliest year from the release dates from all books.
- Summary: The first non-empty summary found, starting from the first book in the series.

The aggregated Summary will only be used if the Series has no Summary itself.

**Comment by cesalo** [comment]
I was going to open a feature request but maybe here is the best place. Can the list of "Reading Lists" and Collections be added too?

**Comment by gotson** [comment]
> I was going to open a feature request but maybe here is the best place. Can the list of "Reading Lists" and Collections be added too?

I don't see how it's related. Collections the series is part of are already displayed on the series screen.

Open a new one if you think you have something.

**Comment by cesalo** [comment]
You're right. I meant showing the reading lists associated with the series
as well. Sure I'll open a new issue.
