### ISSUE TITLE
Touchscreen enhancements

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#183]
I'm using pretty much a tablet (High Def 11') to read my comics, not my laptop so much, I guess that's the reason I found the need for this.
At the moment this is the workflow I need to do to start reading a comic:
- Long click on the comic (this is similar to a right click so a secondary browser menu open: back - forward - etc). This will also show the red icon to read the comic.
- Click on a different place to hide this secondary menu.
- Click on the red icon and open the comic (Sometimes I missed it and need to start from scratch)

Not sure what would be the best option to fix this but maybe having the read icon always present or a sub-menu when clicking (open or read) but only on tablet mode.

**Comment by gotson** [comment]
<img width="243" alt="Screenshot 2020-06-06 at 08 53 06" src="https://user-images.githubusercontent.com/2139133/83932150-30fc4a80-a7d3-11ea-9be9-a814ea8fc958.png">

You can use the red (previously blue) book icon located under the cover on the book details screen to start reading a book.
