### ISSUE TITLE
[Feature Request] WebUI Alphabetical navigation

### ISSUE THREAD

**Issue by hot22shot** [gotson/komga#186]
### Is your feature request related to a problem? Please describe.
I have some large libraries with more than 250 entries.

### Describe the solution you'd like
I'd like to be able to navigate with an alphabetical shortcut : pressing a letter would navigate to the first item of the letter in my library.

### Describe alternatives you've considered or other apps that can do what you want
For example Plex libraries.

**Comment by gotson** [comment]
That's indeed something I wanted to do, now the question is more about whether I can manage to do the UI part as nicely as plex did!
