### ISSUE TITLE
[Feature Request] UI Translation

### ISSUE THREAD

**Issue by hot22shot** [gotson/komga#187]
### Is your feature request related to a problem? Please describe.
UI is only in English (or maybe I missed how to set it up in another lang).

### Describe the solution you'd like
An option (drop down list maybe ?) to set the interface lang globally and per user, the latter having precedence.

**Comment by gotson** [comment]
The UI doesn't have much content, I'm not sure if it's worth having internationalisation. Would probably require a signifiant effort to setup, and to organize all the translations.

**Comment by whalehub** [comment]
Just in case this is ever implemented, I'd volunteer to translate it into German.

**Comment by Polypete** [comment]
Just in case this is ever implemented, same for me for translate in French !

**Comment by gotson** [comment]
The translation is done using Weblate, you can contribute here: https://hosted.weblate.org/projects/komga/webui/
