### ISSUE TITLE
[Bug] Komga totaly stuck with []

### ISSUE THREAD

**Issue by cyberbad** [gotson/komga#193]
Komga environment
- **OS**: 0.35.1
- **Komga version**: 
- [ ] **I am running Komga with Docker**
  

I made a folder name   :   Karakai Jouzu No Takagi-San [scantrad]
with this files : Karakai Jouzu No Takagi-San - T01 [scantrad].cbz

it's appear like that : 
![image](https://user-images.githubusercontent.com/48301304/83983630-3b802680-a930-11ea-970c-6c5cd5d78e1f.png)

i try stop the container, delete the folder, the file, rename it, add new serie, but all is stuck no update and no delete .

**Comment by gotson** [comment]
Can you provide log files?

**Comment by cyberbad** [comment]
It's seem my problem i make another komga it's work,
i made a clean, i will see it tonight
