### ISSUE TITLE
[Feature Request] Custom cover upload

### ISSUE THREAD

**Issue by MEGAMENE** [gotson/komga#194]
### Describe the solution you'd like
An option do upload a custom cover to a series, that gets stored in the Komga data.

### Describe alternatives you've considered or other apps that can do what you want
The feature would work like it does in Plex.

**Comment by gotson** [comment]
Good complement to #63

**Comment by andrelopesmrx** [comment]
In addition to upload a custom cover, it would be good to pick a cover directly from comicvine. Specially for issues with multiple covers.

**Comment by grim7reaper** [comment]
That sounds rather US comic-centric, and thus reduce the usefulness of it.
I mean, I'm not sure that ComicVine is good to pick covers for European comics, mangas, manhuas, manhwas, …

**Comment by gotson** [comment]
It's out of topic and would be covered by #11

**Comment by andrelopesmrx** [comment]
you could abstract it to: "fetch cover (or alternative cover) from metadata provider". 
but it is even better if #11 covers it.
