### ISSUE TITLE
[Bug] Artemis data-directory configuration field is not properly expanded

### ISSUE THREAD

**Issue by PichetGoulu** [gotson/komga#195]
### Komga environment

- **OS**: Debian GNU/Linux 10 (buster)
- **Komga version**: 0.37.0
- **I am running Komga from the `jar`**
    - Java version: openjdk 11.0.7 2020-04-14 (build 11.0.7+10-post-Debian-3deb10u1)

### Describe the bug

`artemis.data-directory` configuration field is not properly expanded.

The default value `~/.komga/artemis` create a `~` directory instead of expanding to `$HOME`
Artemis then create files in `\~/.komga/artemis/` instead of `$HOME/.komga/artemis/`

### Steps to reproduce

1. Start Komga with the default configuration
2. See the directory `~` created in the current working directory

### Expected behavior

Expand `~` to the `$HOME` value

### Actual behavior

A `~` directory is created in the current working directory

### Additional context

The `komga.database-backup.path`, with a default value of `~/.komga/database-backup.zip`, is properly expanded.

### Log file

```
2020-06-08 12:54:38.470  INFO 31492 --- [main] org.apache.activemq.artemis.core.server  : AMQ221000: live Message Broker is starting with configuration Broker Configuration (clustered=false,journalDirectory=~/.komga/artemis/journal,bindingsDirectory=~/.komga/artemis/bindings,largeMessagesDirectory=~/.komga/artemis/largemessages,pagingDirectory=~/.komga/artemis/paging)
[...]
2020-06-08 12:54:58.555  INFO 31492 --- [DefaultMessageListenerContainer-1] o.g.k.i.h2.DatabaseBackuper              : Executing command: BACKUP TO '~/.komga/database-backup.zip'
```

**Comment by gotson** [comment]
This is a Spring Boot configuration property, which is binding to an Artemis configuration. I checked the Spring Boot code and it doesn't handle any expansion (and shouldn't). The bug is probably on Artemis side. I will try to open an issue with them.

In the meantime you can override the configuration by using an absolute path. This is not platform independent, and should be done on user side depending on the OS.

**Comment by gotson** [comment]
I have created an issue on Artemis' Jira: https://issues.apache.org/jira/browse/ARTEMIS-2796
