### ISSUE TITLE
[Feature Request] Creation of labels and the ability to use them for sharing content

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#201]
### Is your feature request related to a problem? Please describe.
- **Sharing with Kids:**
As of now my way to share my comics with my kids is to create symbolic links or duplicate them (the series I want to share) to a different directory, create a library pointing to this location and share it with my kids. Generally I create an rsync script (not if they are symbolic links) to keep this folder up to date. This is something I've been using pre-Komga.

- **Sharing specific Series:**
I also use this method when I want to share a specific group of my comics. It may sound weird but some times sharing all my comics (500 Series or so) is not needed few friends are just interested in a specific series like Walking Dead, The Dead of Superman, etc.

- **Don't share series that are not complete:**
Let's say I'm working on a specific series and there missing issues all over the place. I wouldn't want to share this with my friends until is ready.

### Describe the solution you'd like
In the same way Plex does this (and more):
- Create and assign a label to the Series or even at book level.
- Share this label to any of the users created in Komga.
- The users will only be able the stream/download the books or series with this label.
- A new feature would be to allow "negative" sharing so actually the opposite - to not be able to access a specific label (This is not available in Plex).

At user creation level there should be an option to restrict access per label and library. For example: 
- UserA to access the whole Library1 and only items that have label "share" in Library2.
- UserC won't be able to access items with label "not-share" in Library3 and everything in Library1.

**Comment by gotson** [comment]
For kids, you could use #178.

For incomplete series, you could tell your friends to filter on Series Status = ENDED.

I understand the requirement, i'm not so sure about real life use cases though. I don't use that particular feature in Plex.

**Comment by cesalo** [comment]
@gotson It seems my comics don't have the value of "Age Rating", in my case Mylar is creating this xml directly from comicvine. Regardless, it seems you are planning to let the user modify this value so I could set a customized value to the Series I want to share with my kids and force or remove their ability to see these comics .. right?

**Comment by gotson** [comment]
You can already set the age rating by book. To set for one series, maybe #114 would help. Or maybe we would need to set up a default age rating per series that would be overwritten if there's one for a specific book.

**Comment by cesalo** [comment]
Yes, I think that would be great, having the setting at series level and customize it at book level if needed. Now what happen with comics that don't have this value .. if the account has an age rating associated it shouldn't be able to see comics with no age rating defined.

**Comment by gotson** [comment]
Indeed, but if the book doesn't have one, but the series has a default, it should apply the default. If the series doesn't have the default, this user wouldn't be able to see this comic.

**Comment by gotson** [comment]
Released in https://github.com/gotson/komga/releases/tag/v0.153.0
