### ISSUE TITLE
[Bug] logging.file.name configuration field is not properly expanded

### ISSUE THREAD

**Issue by grim7reaper** [gotson/komga#203]
### Komga environment
- **OS**: Archlinux
- **Komga version**: 0.39.0
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk 14.0.1 2020-04-14

### Describe the bug

Like what happen in https://github.com/gotson/komga/issues/195 but for `logging.file.name`.

### Steps to reproduce

1. Set `logging.file.name` to `~/.local/share/komga/komga.log`
2. Start komga
3. See the directory `~` created in the current working directory

### Expected behavior

Expand `~` to the `$HOME` value

### Actual behavior

A `~` directory is created in the current working directory

### Additional context

Can be worked around by specifying an absolute path, but it's less portable and it's not consistent with the behavior of the other paths (like `komga.database-backup.path`) which are properly expanded.

**Comment by gotson** [comment]
This is a Spring Boot property, refer to [their documentation](https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/spring-boot-features.html#boot-features-logging-file-output) before assuming functionality.

I close this because, contrary to #195 I do not provide a default configuration that uses `~`, hence this is a user configuration issue.

**Comment by grim7reaper** [comment]
> This is a Spring Boot property, refer to their documentation before assuming functionality.

You're right, but it's a bit rude :confused: 

You can't assume your user will know the subtleties of Spring Boot (which properties are expanded, which aren't (BTW, I see nothing about `~` being expanded or not in the doc you've linked…)) to use Komga…

Seeing that some paths are expanded, one would expect the others would too.
If it's not the case, it's not a big deal, but it would help the user a lot if this was mentioned in Komga's user doc (I could do a PR for that if you want), like "~ are not expanded in this property".

**Comment by gotson** [comment]
I'm sorry, i didn't meant to be rude. The Komga documentation specifies that it relies heavily on Spring Boot's properties and configuration.

I am not sure that the documentation needs updating, and users could set an absolute path instead of using `~` when setting this configuration.

**Comment by grim7reaper** [comment]
It's ok, written communication is easier to misinterpret :slightly_smiling_face: 

Using an absolute path is indeed an acceptable solution (and that's what I'm doing now).

About the doc, I think you have three paths in the configuration right now. Two of them accept (or will accept, once Artemis issue is fixed) `~`, while the third one doesn't.
Because the third one behave differently, I thought it could help to mention it. That would reduce the risk of others doing the same mistake as me (and avoid future bug reports on the matter ^^).

**Comment by gotson** [comment]
Feel free to send a PR for the doc then :)

**Comment by gotson** [comment]
I have created an issue on Spring Boot's github to request this feature: https://github.com/spring-projects/spring-boot/issues/21899
