### ISSUE TITLE
Books not showing in the web interface

### ISSUE THREAD

**Issue by alphat5** [gotson/komga#21]
Hi,

I just upload 12 PDF in a library. It's been 6 hours that those comics are on the server. I can see them using an OPDS app on my phone (Librera) but not on the web interface. I can't even click on the library tab (it does nothing). I tried on Chrome and Brave and still don't see it. I

Thanks in advance,
Cheers,

**Comment by gotson** [comment]
That's normal! 🙂

If you are running docker `latest` then it's not implemented yet.

You can follow #18 and milestone `0.9.0` to know when it will be ready.

Some features are already available in the `master` branch and in the `beta` docker image, but it's not deemed stable so use it at your own risk (I personally run 2 Komga instances, one `latest` and one `beta`).

**Comment by alphat5** [comment]
Happy to hear that !! 😄

Is it planned to have the ability to upload directly through the web interface? 

Is there an ETA on the 0.9.0 milestone?

Thanks dude!!

**Comment by gotson** [comment]
No plans to offer an upload feature. What would be the use case for you?

For the 0.9.0 no firm ETA, I'm on holidays until the 8th of December, so hopefully a week or two after that!

**Comment by alphat5** [comment]
For I will see as use case the following: Sharing Komga with my family who isn't that friendly with IT stuff. They want to adds books to a library on Komga. They just need to login on Komga and upload it straight in the concerned library.

No problems, enjoy your holidays!

Cheers,
________________________________

**Comment by gotson** [comment]
I see. I'm this case it would need to handle where to drop the file also, and maybe how to name it properly.

I'm wondering if people who are not very IT aware would less likely come around comic books, making this feature really niche.

I'll keep it in mind, there are lots of more important features that are needed first 😉
