### ISSUE TITLE
Trash bin - handle file moves, and restore after delete

### ISSUE THREAD

**Issue by gotson** [gotson/komga#217]
At the moment Komga identifies files from their full path. Upon a library scan, all series and books that are not present on disk will be deleted from the database, along with their metadata and read progress. 

This is impractical in a few use cases:

- moving or renaming files or folders
- inadvertently deleting files or folders, then restoring after a rescan (either from backup or from the OS trash bin)
- when the root of a library is also the root of a network mount that becomes available (thus becoming an empty folder, deleting the whole content of the library)

---

A solution would be to handle those deletions as soft deletions, like placing the deleted items into a trash bin. Upon a rescan, new items could be compared to the ones in the trash, and in case of a match, partially restored (metadata, read progress). 

The trash could be automatically deleted after a certain amount of time, or manually emptied. 

In addition, there is a need to identify uniquely a file in order to match it with the deleted items in the bin. Comparing the file size along with a file hash could be a potential solution. It would require a fast hashing algorithm, as all files in the library would need to be hashed in the first place.

---

Acceptance criteria:

1. rename file within folder
  - book media is kept, analysis is not rerun, thumbnails are not re-generated
  - book name is changed. Book metadata `title` is changed if not locked. Book metadata is refreshed for `title`.
  - read progress is kept
  - series should be sorted again. In case the book has changed number, its metadata will be refreshed (only for `number` and `numberSort`)
  - local artwork should be refreshed for the book, in case a sidecar file with the new name exists
  - series aggregation should not have changed
2. move file from one folder to another
  - book media is kept, analysis is not rerun, thumbnails are not re-generated
  - book name is not changed
  - read progress is kept
  - source and destination series should be sorted again, and their metadata and aggregation refreshed
  - local artwork should be refreshed for the book, in case a sidecar file with the new name exists
3. restore all books from a series
  - book media is kept, analysis is not rerun, thumbnails are not re-generated
  - read progress is kept
  - series should not be sorted again
  - series aggregation and metadata should not have changed
4. A collection containing a soft-deleted series is updated
  - the UI should not show deleted items
  - the UI will send a list of `seriesId` without the deleted elements, effectively removing the deleted series from the collection
5. A read list containing a soft-deleted book is updated
  - the UI should not show deleted items
  - the UI will send a list of `bookId` without the deleted elements, effectively removing the deleted book from the read list
6. Rename or move folder
  - all books media is kept, analysis is not rerun, thumbnails are not re-generated
  - read progress is kept
  - series name is changed. Series metadata `title` and `titleSort` is changed if not locked. Metadata is refreshed for `title` and `titleSort`.
  - series should not be sorted again
  - series aggregation should not have changed

**Comment by ncmtl** [comment]
I second this request. My network drive disconnected two times this week. All my reading history has been lost, because when the drive did reconnect data has been lost. I believe it would make Komga more resilient to these kind of problem.

Btw Komga is awesome.

**Comment by Snd-R** [comment]
Would it not be better to still display deleted series and books, but show some kind of icon over them to show that they are not available?
I think this would make it less confusing compared to when the whole library would just disappear. And I believe that implementing it in this way would not require changing the collection and readlist updates handling

**Comment by gotson** [comment]
> Would it not be better to still display deleted series and books, but show some kind of icon over them to show that they are not available?
> I think this would make it less confusing compared to when the whole library would just disappear. And I believe that implementing it in this way would not require changing the collection and readlist updates handling

That's 2 different things. If the file is not available indeed we could display something, like Plex does. That would work when network drives are unaccessible. 

The original idea is to handle file moves or temporary deletion.

**Comment by Kussie** [comment]
Just in relation to the closed ticket #405 (Since you don't like comments on deleted tickets),  Both `BOOKS` and `SERIES` tables store the full paths to the file/folder of the book or series.

You also store the path for each Library, could a potential solution for migrations/easy backups be to store the relative paths to the files folder based on their library and concat them together to make the full path?

For example say i have the following file structure: `/books/action/Some Series/Chapter 1.cbz`
The Library path would be: `/books/action`
The Series path would then be `/Some Series`
The Book Path would be `/Some Series/Chapter 1.cbz` or even `/Chapter 1.cbz`

I'm guessing the reason for storing the full path everywhere is speed and ease of use (Especially in the API) which would make sense.  Thankfully though Docker makes migrating/moving the location fairly straight forward.   Just some of my thoughts based on reading #405

**Comment by gotson** [comment]
relative paths would still be different in Windows/Linux system, so that wouldn't solve the problem. Computing a relative path from 2 full paths is also very easy.

**Comment by Kussie** [comment]
Java is smart enough on Windows that it can automatically translate backslashes for windows path.  Ie: `file:/C:/books/action/Some Comic/chapter 1.cbz` would still work fine.

**Comment by gotson** [comment]
yes, but there's lots of good reasons to have the full path there. Anyway, that's off topic.

**Comment by elit3ge** [comment]
Any news on the Trash Bin being implemented? I can see there is a pull request.

**Comment by gotson** [comment]
I've got it almost finished, so soon.

**Comment by gotson** [comment]
> Would it not be better to still display deleted series and books, but show some kind of icon over them to show that they are not available?
> I think this would make it less confusing compared to when the whole library would just disappear. And I believe that implementing it in this way would not require changing the collection and readlist updates handling

Hi @Snd-R , it's been long overdue, but i finally found some time to work on this feature. You PR #383 helped me a lot, and i am very thankful for that. You were right about the fact that it would be easier to handle items being unavailable, that's what i ended up doing when i started implementing the feature, it felt more natural.
