### ISSUE TITLE
[Feature Request] User Name Not As Email Address?

### ISSUE THREAD

**Issue by cilise** [gotson/komga#220]
I'm currently testing Komga (yay active development) as a replacement for Ubooquity (lack of active development).
I have several users that access my content and I don't want/need to keep up their email as the login.  I was wondering if there was a way we create users using a username with email address being an optional field for those who don't mind the email login.

**Comment by gotson** [comment]
Email is convenient, because it can later be used for more features (#143 #101 ). I have no plans to change the login to use something else than email.

Most internet services will require a valid email address nowadays, this is no different.
