### ISSUE TITLE
[Feature Request] Add option to disable snackbar and double press in webreader

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#222]
### Is your feature request related to a problem? Please describe.
I recently read the series "These Two Will Be Married In 100 Days" using the webreader. Since the 100 books of that series are very short (1 to 2 pages per book), I had to constantly click/press next again to got to the next book in the series. The snackbar obviously also appeared every single time I reached the end of each book. 
In this particular case the constant clicking/pressing-next-twice and the snackbar showing up, while working as intended, where rather annoying.

### Describe the solution you'd like
I would like the option to disable the snackbar and the need to press next/previous twice to go to the next or previous book in the webreader. This option could be toggled with a switch put with the other webreader options.

**Comment by gotson** [comment]
Seems like a very edge case.
