### ISSUE TITLE
[Feature Request] Disable image selection in webreader

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#223]
### Is your feature request related to a problem? Please describe.
Maybe more of a bug, I'm not sure. This problem cropped up while I was clicking very fast through a book in the webreader. I accidentally selected the image which resulted in the typical selection highlighting.

### Describe the solution you'd like
I think disabling selection would be the best option, since I don't see a use case for selecting an image in the webreader. This could probably be done via a CSS as described here https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting

### Describe alternatives you've considered or other apps that can do what you want
Maybe instead change the color of the selection highlighting to transparent, if disabling it isn't possible. Or add a switch to the options of the webreader to toggle the ability to select the images, if someone needs that.

### Additional context
Example image of the selection
![image](https://user-images.githubusercontent.com/44478004/86295527-16ad6500-bbf7-11ea-86a1-a58218795b99.png)

**Comment by gotson** [comment]
Just click again anywhere to remove the selection?
