### ISSUE TITLE
[Feature Request] Filter on read books

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#225]
Hi, thanks a lot for your amazing project. It's better and better.

A simple feature that I would like have it's be able to filter on read books. Not only unread ones like it's the case.
Mainly to share and advice the ones that I like. That would help me to find them more quickly.

**Comment by gotson** [comment]
It was in the first version of the filters, but it was very confusing for people. I decided to follow what Plex is doing, only show the unread filter.

I think a better feature would be a screen showing the history of what you have read, ordered by date of reading?

**Comment by Kiwi-13-plo** [comment]
A new screen or a collection of read Book. It Can also make the job.
Or a sort option, date added, updated and readed.

**Comment by Kiwi-13-plo** [comment]
I juste check Plex and there is a sort option like this.

**Comment by gotson** [comment]
> I just checked Plex and there is a sort option like this.

Where? Could you share the doc or screenshot?

**Comment by Kiwi-13-plo** [comment]
![image](https://user-images.githubusercontent.com/66436124/86439784-801d9880-bd09-11ea-92e9-b1720d73ae30.png)

**Comment by gotson** [comment]
OK, that's only a sort, not a filter. Thanks.

**Comment by Uthred** [comment]
A possible issue with having a history screen ordered by date is that it would show individual volumes but not series. At the moment there's actually no way to see what you've read that I can see. If the read filter is causing confusing perhaps have it turned off by default but allow the admin to turn it on in server settings?

**Comment by gotson** [comment]
There is no such thing as a read series per se, it's considered read when all books have been read. Add a new book to a series and it's now unread.
