### ISSUE TITLE
[Bug] No page and display option in a collection

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#226]
### Describe the bug
In a collection I can't see more than 20 series. (4 lines of 5 element).
Maybe because I don't have the option to show more and it's blocked on 20 per default.
Moreover I don't have the page option inside the colletion.

### Steps to reproduce
1. Go to a collection with more than 20 series

### Expected behavior
Be able to show more or have the ability to change pages.

**Comment by gotson** [comment]
There's a button on the top right in the toolbar to change the page size : 
![Screenshot_20200705-075350](https://user-images.githubusercontent.com/2139133/86522717-d1a65e80-be94-11ea-90cd-db33bf08d738.jpg)

**Comment by Kiwi-13-plo** [comment]
Like I said I don't have the button when I'm inside a collection. I'm on Chrome.
A collection with 67 series : 
![image](https://user-images.githubusercontent.com/66436124/86527137-4df07000-be9c-11ea-9428-13ef14fe2476.png)

**Comment by gotson** [comment]
I'm sorry, i misread your first post, indeed it's a bug, it should show all the series in a collection, unpaged.
