### ISSUE TITLE
[Feature Request] Full Screen (almost) on mobile via home screen icon

### ISSUE THREAD

**Issue by beville** [gotson/komga#227]
(NOTE: This overlaps slightly with #167, but is really a different, smaller, request)

I'm super impressed by the reader page, but would love to remove the browser elements when I launch from a 'home screen' icon on my tablet, since the browser UI takes up a lot of real estate on a mobile device.

Here's a simple example that seems to work for both Safari on my iPad , and Chrome on my Android phone:

```
<html>
<head>
	<title>Web App Test Page</title>
	<link rel="apple-touch-icon" href="foo-touchicon.png"/>
	<link rel="icon" href="foo-favicon.ico" />	

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name = "format-detection" content = "telephone=no">
</head>

<body>
THIS IS A TEST!
</body>
</html>

```
First I type in the URL in the browser app, use menu to "Add to Home Screen", and then when I launch from the icon, no browser UI clutter. 

Not sure if this will work for Komga, but it should be pretty easy to test when you get a chance.

(There may be some extraneous cruft in the above, as I didn't try to pare it down to the minimum.)

**Comment by gotson** [comment]
Can you walk me through what exactly in the above snippet is triggering the full screen behavior?

**Comment by beville** [comment]
I pulled that chunk of HTML from a simple project I did years (and years) ago.

As I understand it,  it's the line:

`<meta name="apple-mobile-web-app-capable" content="yes">`

in conjunction with being launched by the home screen icon.

If you just go to the URL in iPad Safari directly, you will still see the menu and tabs and bookmark bar. 

It's _only_ when you create a home screen icon from the mobile browser menu, _and then_ launch the "web app" from the icon that you get the full screen.  (Actually not quite full screen, since you still see the device status bar on top).

Also my observation is that:

`<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">`

will keep the page from being pinched and zoomed (also in conjunction with being launched by the home screen icon).  I am not sure how it will react with the pinchy-zoomy part of the Komga reader, though.  Ideally it would work to keep the UI part of Komga page from being zoomed, but would not affect the zooming feature of the reader.

It should be quite easy for you to experiment with this, I guess.  I'm not a java guy, so I didn't even attempt to pull apart the jar file.

**Comment by gotson** [comment]
The webui is in VueJS and Vuetify, no Java/Kotlin :)

**Comment by cesalo** [comment]
@beville Hi - Can you maybe post a screenshot about what you want to accomplish? I see you mentioned #167 - What are the browser elements you want to eliminate? When using what I posted in #167 I don't see any browser elements so I think I'm missing something.

**Comment by beville** [comment]
No prob. The UI elements of the URL bar, bookmark bar, and tab bar are still present in Komga no matter how I launch it on my iPad.  Here’s screen shots of my above html example when I view it In Safari directly, and then when I view it by home screen icon.

![7188AFDE-5C34-4CE3-9C30-2E267A212A95](https://user-images.githubusercontent.com/7294848/86789538-45bf3e80-c01c-11ea-9323-e30a6a14c0f9.jpeg)
![8C99D551-FB2B-4883-B41F-C553DF415238](https://user-images.githubusercontent.com/7294848/86789548-48219880-c01c-11ea-87a0-eca6e40d0699.png)

Additionally, when I create a home screen icon for Komga, I get a blank icon on the iPad. Using a line the below can fix that.

`<link rel="apple-touch-icon" href="foo-touchicon.png"/>`

**Comment by beville** [comment]
Additionally, I wanted to make a request that was distinct from #167 (since that was specifically for a PWA), and have an issue that was focused on the much simpler meta tag header solution.

**Comment by cesalo** [comment]
@beville - I see then this is something specifically to Safari. I'm not a Mac person (never used an IPad) so not sure if Chrome in your IPad will solve this for you.
In my case I don't see any Browser Elements using the steps I put in #167, in my Tablet, Komga behaves like any other App (full screen, no elements from Chrome at all, etc).
I believe the intention of #167 was to accomplish that using a PWA but he was able to get the same results using the "Create Shortcut" + "Open as a Window" in Chrome in Android.

**Comment by beville** [comment]
@cesalo From what I read, @tahngarth only got it working when he hacked his Komga source to add a metatag like above, and _then_ launching the site from a home screen icon.

Adding these tags don't affect desktop browsers, but _do_ change the behavior on Android and iOS when launched from from a home screen icon.  It's a very simple, effective change that is a significant quality-of-life thing when on a mobile platform.

**Comment by cesalo** [comment]
@beville - that seems to be inaccurate at least in my experience in Chrome. I just tested in my laptop to see how it behave in a desktop browser, see below:

![Screenshot from 2020-07-07 11-11-34](https://user-images.githubusercontent.com/16859916/86802362-f3dddf00-c042-11ea-9a78-0b9a32fcdd43.png)

Now in my tablet I don't even see the black line with the Komga icon at the top, is all full screen experience. No hacks or any other CSS changes, just the "Create Shortcut" + "Open as a Window" in Chrome.

**Comment by tahngarth** [comment]
From what I could gather, <meta name="apple-mobile-web-app-capable" content="yes"> isn't properly supported any more.  They seem to want it to be done like my pull request #209 . 
Other notes: Back when i added the meta tag to the code, the fact that the meta tag was there during shortcut creation was all that was needed. I am running an unmodified version of Komga at the moment and the shortcut on my phone still is launching like that meta tag is there.

**Comment by tahngarth** [comment]
> Also, I wanted to make a request that was distinct from #167 (since that was specifically for a PWA), and have an issue that was focused on the much simpler meta tag header solution.

Also want to note that the pull reqeust #209 actually is attempting to do exactly what you want. It's all I really want too, I don't care about the offline behavior of PWA, just the full screen app mode behavior you're after.

**Comment by beville** [comment]
@tahngarth  Cool, I wasn't aware that there was a pull request in place for this already!

**Comment by DustbinK** [comment]
I would love to see progressive web app compatibility. It’s the only thing I’m missing in Komga! It’s so nice when web services support this - makes it feel like a native application and importantly for comics lets you use the full screen (minus notification bar.) Not as essential but related to make it feel native would be login persistence so I can just tap on the Home Screen icon and I’m in.
