### ISSUE TITLE
[Feature Request] Show/Hide libraries from "Home" view

### ISSUE THREAD

**Issue by stonechitlin** [gotson/komga#229]
### Is your feature request related to a problem? Please describe.
I have some library sections that I personally don't use, but have them for other users, for which I would like to hide from my own view.

### Describe the solution you'd like
The option to select what libraries show on the "home" section.

### Describe alternatives you've considered or other apps that can do what you want
Plex has this exact functionality for comparison.

### Additional context
I would also say, having both "Home" and "Libraries" (which shows all library's) is kind of redundant, or at least have it follow the same show/hide pattern as the requested one here for "Home"

**Comment by Kussie** [comment]
bump

**Comment by gotson** [comment]
> bump

I don't mind the duplicate if the other one was closed stale 😃
