### ISSUE TITLE
[Feature Request] Show collections in line, hide series that are in that collection

### ISSUE THREAD

**Issue by stonechitlin** [gotson/komga#230]
### Is your feature request related to a problem? Please describe.
In an effort to de-clutter my library, I have made what series I can into collections for this.

### Describe the solution you'd like
When series are in collections, give the option to show that collection in line and hide the individual comics.

### Describe alternatives you've considered or other apps that can do what you want
Plex does this behavior currently.

**Comment by gotson** [comment]
Quite difficult to achieve unfortunately given the data/API model.
