### ISSUE TITLE
Komga Docker Image - Forcing port 8080 instead of defined values

### ISSUE THREAD

**Issue by kingss46** [gotson/komga#232]
Using Synology Docker application to add Komga, I set the port properties to use 8081:8081 (also tried other ports like 7080:7080). The docker container seems to start fine, but I am unable to access the web UI using http://<host:8081>. Checking the logs it shows that the embedded tomcat is still starting on port 8080 instead of the defined port values for docker. 

I already have another container using port 8080, so I need to be able to adjust the port value. 

[komga.log](https://github.com/gotson/komga/files/4904987/komga.log)

Starting Servlet engine: [Apache Tomcat/9.0.33]
 Starting service [Tomcat]
 Tomcat initialized with port(s): 8080 (http)

Even if I stop the other container running on port 8080, i am still unable to access the web UI. I'm assuming because docker has that container configured to use port 8081 instead.

**Comment by kingss46** [comment]
To follow-up, if I set the Local Port in docker to 8081 and the Container Port to 8080, it seems to allow me to connect successfully to the web ui page.

**Comment by gotson** [comment]
The whole point of docker is to map the external port to the internal port. You don't need to change the internal port, just map 8081 externally to 8080 internally.
