### ISSUE TITLE
[Bug] The Docker Image is using a lot of Ram (Synology Nas)

### ISSUE THREAD

**Issue by Hebusing** [gotson/komga#236]
### Komga environment
- **OS**: Synology Nas DS1019+ DSM 6.2.3-25426 (latest one available)
- **Komga version**: v0.45.2-master
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: gotson/komga:lastest

### Describe the bug
The image is using a lot of Ram (even when it is idle): between 700MB and 2.5GB

### Steps to reproduce
Nothing specific: just launch the image and wait.

### Expected behavior
Calibre is using 60MB, Calibre-Web is using 14MB, COPS is using 3MB and Ubooquity is using 10MB. 
So I was expecting Komga to use around the same amount of Ram when it is idle.

### Actual behavior
The application is using a lot of Ram as I've shared above.

### Additional context
I've got 124 series of books (didn't count how many books total) but I've seen this wrong behavior from the beginning when I had only a few books to try and test the application.

### Log file
I looked at the logs but didn't find anything in particular except that every 15 minutes a scan is done for 3 seconds.
I'm happy to provide any logs or any more information if needed. Let me know if you want me to test anything in particular as well!

A massive thanks for this application: it is by far the best comics web reader I've tried (compared to COPS, Calibre-Web or Ubooquity)!!! Kudo to the dev team  ;-)

**Comment by gotson** [comment]
You can limit the ram used, see the doc https://komga.org/installation/docker.html#increase-memory-limit

Ubooquity definitely doesn't use 10 b, it's written in Java and has a default of 512mb in the docker image provided by Linux server. 

Other applications cannot be compared, they are not using Java.

**Comment by Hebusing** [comment]
Thanks Gotson for your answer. What I don't understand though is that your documentation says that it uses a maximum of 1GB of Ram, where for me it could be way above this without changing the setting.

As you can see below the amount of Ram taken by Ubooquity and Komga:
![image](https://user-images.githubusercontent.com/63528742/87497056-578d8b00-c687-11ea-9249-674d4aaa5239.png)


I've just stopped the image, added an environment variable JAVA_TOOL_OPTIONS with the value -Xmx500m:
![image](https://user-images.githubusercontent.com/63528742/87497491-3aa58780-c688-11ea-97f6-412da484d13a.png)

However it is still using more than 500MB:
![image](https://user-images.githubusercontent.com/63528742/87497940-388ff880-c689-11ea-8630-8560bd296dcd.png)

Have I done anything wrong here?

Again: thanks a million for this amazing application!  :-)

**Comment by gotson** [comment]
The documentation doesn't say that it uses a max of 1gb. It tells you how to configure the JVM to limit the amount of ram allocated to it. By default there is no limit, and depending on your version of Java and your total amount of ram it will use a different default, but usually that's 1/4 of your total ram.

I dont know about docker on synology, but I would take those numbers with a pinch of salt. There's no way ubooquity can use 10 mb. I have seen the code and I know how it works, it cannot be using 10mb.

One more thing, checking those numbers when you don't have an issue are meaningless. Java will only give back memory if the OS requests it, not by itself. If you system is running fine, don't bother looking at those figures (ram). Cpu is different and you should care, but if all your apps are running fine, let it go l. 

You can check #17 for more insight on ram consumption in the jvm and docker.

**Comment by Hebusing** [comment]
Hi Gotson, thanks again for your prompt support! Really appreciate your help.

The reason why I've started looking into this is because I had the following warning message from Synology: "Indexing suspended due to low memory. To continue indexing, close other running applications to release memory". So in my case it seams that the system needs some memory taken by Komga but is not able to get it.

By the way, if I open the same comic in Ubooquity, the RAM taken by Ubooquity is raising to 530MB.

Maybe I would have to upgrade the RAM on my Nas to 16GB instead of 8GB.

**Comment by Hebusing** [comment]
For your information, the RAM usage with the latest version v0.51.1-master is way less: around 550MB when I'm reading a comic instead of more than 2GB. Probably something changed between those versions.
Thanks again for the work!
