### ISSUE TITLE
[Bug] Failure Migrating to SQLite

### ISSUE THREAD

**Issue by bryanmcain** [gotson/komga#237]
### Komga environment
- **OS**:  Mac OS 10.14.6
- **Komga version**:  45.2 -> 48.0
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [ x] **I am running Komga from the `jar`**
  - Java version: openjdk version "13.0.1" 2019-10-15
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug

SQLite migration is failing with the attached errors.    

[error.txt](https://github.com/gotson/komga/files/4928972/error.txt)

**Comment by bryanmcain** [comment]
Not terribly surprisingly, I had to restore my DB from one of the backups in order to get 45.2 running again, so I'm glad you included that in the upgrade process.

**Comment by gotson** [comment]
You may have used one version in the past that had a bug where the page numbers were not properly inserted in DB.

You can try 2 things:

Simple one but will take more time:
- rollback to `0.47.0`
- re-analyze your whole library, that will fix the page numbers that would be incorrectly set
- delete the `/config/database.h2.mv.db.migrated` and `database.sqlite` files
- run the `0.48.0`

More complex, but probably faster. You need to be comfortable with SQL.
- rollback to `0.47.0`
- go to `/h2-console` and input the following:
  - JDBC url: `jdbc:h2:/config/database.h2`
  - user name: `sa`
  - no password
- You will have access to a web SQL console. Type the following query: `select distinct b.* from media_page p, book b where p.book_id = b.id and p.number is null`. This will list the books that have incorrect page numbers.
- you can re-analyze those books only
- delete the `/config/database.h2.mv.db.migrated` and `database.sqlite` files
- run the `0.48.0`

Else if you do not care about your existing db, you can delete the old/new databases and start from scratch on `0.48.0`

**Comment by bryanmcain** [comment]
I went with option 1.  I didn't actually need to delete any files - I think because it crashed before they were created last time.  Migration seems to have worked correctly this time.  Thanks.
