### ISSUE TITLE
[Bug] Migration Failed

### ISSUE THREAD

**Issue by chinjinson** [gotson/komga#239]
FreeBSD12.1
Komga v0.48.0

Upgrading to Komga v0.48.0, I get the following error.
-----
INFO 33983 --- [main] o.g.k.i.datasource.DatabaseMigration     : Migrate table: MEDIA_PAGE
ERROR 33983 --- [main] o.g.k.i.datasource.DatabaseMigration     : Migration failed
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: MEDIA_PAGE.NUMBER)

My H2DB MEDIA_PAGE Table

apeear the NUMBER field is null records
![image](https://user-images.githubusercontent.com/66656299/87750302-08398d00-c836-11ea-8ba0-21ee57af1620.png)

Pls help me.

**Comment by gotson** [comment]
You can roll back to the previous version, re analyze your whole library, and attempt the migration again.

**Comment by chinjinson** [comment]
Thank you!

**Comment by gotson** [comment]
I will close this issue, please reopen if you still have issues.
