### ISSUE TITLE
[Bug] Performance down

### ISSUE THREAD

**Issue by chinjinson** [gotson/komga#241]
### Komga environment
FreeBSD12.1

Database migration is complete.
but very slowing down performance.

My Libraries exist 20000 series.
Komga 0.47 DIsplay speeds 2.5 sec.
Komga 0.48 DIsplay speeds 7.5 sec.

thanx.

**Comment by gotson** [comment]
A trade-off was necessary to enhance robustness and remove the risk of database corruption.

You can reduce the amount of series displayed to enhance loading time.

**Comment by chinjinson** [comment]
I understood this is a specification instead of problem.
I will continue to use v0.47.0.

**Comment by gotson** [comment]
Up to you but you will miss all the new features going forward.

What's your hardware?

**Comment by chinjinson** [comment]
Unfortunately, speed is important.
My hardware is xeon e3 3.5GHz. mem 16GB

**Comment by gotson** [comment]
What year is that? My Google search says it's from 2012.

**Comment by chinjinson** [comment]
its 2014 
Xeon E3-1231 v3

**Comment by gotson** [comment]
What is the storage used for your books ? Spin drive ? SSD ? Network drive ?
Are you running Komga in Docker or with the Jar ?

2.5s in 0.47.0 seems awfully slow already.

**Comment by chinjinson** [comment]
8TB hdd x 4 ZFS Raid with SSD L2ARC
Im using jar

**Comment by chinjinson** [comment]
V0.4.8 is page feed very slowly
MEDIA PAGE table is over 10000000 records now

**Comment by gotson** [comment]
10M record is nothing for a SQL database.

What's your java version?

**Comment by chinjinson** [comment]
JDK 8.252.09
![image](https://user-images.githubusercontent.com/66656299/87870420-ddd90280-c9e2-11ea-847a-f812ac935782.png)

**Comment by gotson** [comment]
From Oracle or AdoptOpenJDK ? Can you past the output of `java -version` ?

The table MEDIA_PAGE is indexed, i checked the query plan, it's quite fast on queries.

**Comment by chinjinson** [comment]
# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Comment by gotson** [comment]
you could try OpenJDK 11, but on x86 architecture there shouldn't be much difference.

**Comment by chinjinson** [comment]
im not dissatisfied with the current v0.47.0 speed.   i understood bit slow depending on the number of series.
