### ISSUE TITLE
[Feature Request] anisearch.de/anisearch.com for Manga Scraping ?

### ISSUE THREAD

**Issue by Ruffyop** [gotson/komga#246]
Hey there, any chance we can get anisearch.de/anisearch.com as addition for Manga Scraping ? 
because i have huge issues with recognition of names in german

**Comment by gotson** [comment]
I close this, it's part or #11

**Comment by Pfuenzle** [comment]
You could take a look at https://github.com/Pfuenzle/AnisearchKomga
I wanted to same so I made a script to get the Metadata from AniSearch
