### ISSUE TITLE
[Feature Request] keyboard navigation in searchbox results

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#250]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like
while searching, typing a name, a dropdown appear with suggestion, i would like to be able to use UP and DOWN keyboard to browse and select the suggestion item. It would be convenient to no have to take the mouse to select an item in the dropdown suggestion. 

### Additional context
finding an item by using the search bar without dropping the keyboard to use the mouse.

**Comment by Kussie** [comment]
This currently works by default.  You do need to press tab twice first, but after that navigating through the menu options with the arrow keys and enter to select works.

**Comment by gotson** [comment]
It should work without tab, we can probably listen to the up/down events and route them to the list.
