### ISSUE TITLE
[Bug] /opds not existing

### ISSUE THREAD

**Issue by SeNeOEH** [gotson/komga#255]
### Komga environment
- **OS**: 
- **Komga version**: v0.51.0-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [x] **I have a problem with an OPDS client application**
  - OPDS Application (with version): Chunky 2.5.9
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When i try to connect through Chunky I see the following logs for my docker container after getting a conneciton error:
>2020-08-02 14:02:36.334 WARN 1 --- [nio-8080-exec-1] o.s.web.servlet.PageNotFound : No mapping for GET /opds
>2020-08-02 14:02:36.346 WARN 1 --- [nio-8080-exec-6] o.s.web.servlet.PageNotFound : No mapping for GET /opds-comics

and on an web browser http://\<myserveraddress>/opds give me an error 404

### Additional context
I'm using docker in an unraid server, and trying to connect through it's IP address.

**Comment by gotson** [comment]
That's normal if you don't use the correct url. Check the documentation : https://komga.org/guides/opds.html

**Comment by SeNeOEH** [comment]
Hum, a classic case of RTFM on my part. Thanks for the quick answer.
