### ISSUE TITLE
[Feature Request] Bring back the Settings icon

### ISSUE THREAD

**Issue by Hebusing** [gotson/komga#261]
### Is your feature request related to a problem? Please describe.
On iPad, the keyboard is not displayed, so since the introduction of the "Information" icon and the removal of the "Settings" icon, we can't anymore toggle the settings menu which is very annoying.
Fyi, there are no issues for the Toolbar (just touch the screen to display it) or the Explorer (as there is an icon).

### Describe the solution you'd like
Please bring back the Settings icon as we had in v0.45.2-master.

### Describe alternatives you've considered or other apps that can do what you want
Another option would be to make all the values in the "Information" menu clickable (so when touching on the "Home" icon for ex, it will simulate the press on the "Home" key.

Thanks a lot for your support!  :-)

**Comment by gotson** [comment]
It's been fixed in the latest version. The icon was not showing but the button was there, and clickable.

**Comment by Hebusing** [comment]
Thank you Gauthier!
Are you French by the way?
