### ISSUE TITLE
[Bug] Ratio of the page is not respected on iPad

### ISSUE THREAD

**Issue by Hebusing** [gotson/komga#262]
### Komga environment
- **OS**: Synology Nas DS1019+ DSM 6.2.3-25426 (latest one available)
- **Komga version**: v0.52.1-master
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: gotson/komga:lastest

### Describe the bug
On iPad (I don’t have this issue on Windows 10, it might be due to the resolution of the screen I use), the ratio of the page is not respected wether it is a PDF, CBR or CBZ file.

### Steps to reproduce
Open any file on an iPad and play with the scale type and rotate your iPad to go from portrait mode to landscape mode.

### Additional context
It was working fine with the v0.45.2-master.

### Screenshots
Close to the original ratio, displayed on iPad in portrait mode with scale type « Fit to height »:
![IMG_0140](https://user-images.githubusercontent.com/63528742/89551200-3f9bc800-d83d-11ea-9862-06d250a74a73.jpeg)

Quite awful, displayed on iPad in landscape mode with scale type « Fit to width »:
![IMG_0139](https://user-images.githubusercontent.com/63528742/89551291-60fcb400-d83d-11ea-822f-73dabf0c0252.jpeg)

Even worse, displayed on iPad in portrait mode with scale type « Fit to width »:
![IMG_0138](https://user-images.githubusercontent.com/63528742/89551320-69ed8580-d83d-11ea-9a0d-beb2ed8d5bb2.jpeg)

**Comment by gotson** [comment]
I confirm the issue is with **Fit to width** on Safari.

**Comment by Hebusing** [comment]
I confirm that the v0.52.2-master release fixed it!
Thank you!!!
