### ISSUE TITLE
[Feature Request] Paperback extension

### ISSUE THREAD

**Issue by h-wb** [gotson/komga#263]
### Is your feature request related to a problem? Please describe.
There’s this new app called [Paperback](https://github.com/Paperback-iOS/app) on IOS. It seems quite new and it looks like it’s heading to be the IOS Tachiyomi. It starting to have some [extensions](https://github.com/Paperback-iOS/extensions) and maybe Komga could be one of these extensions.

### Describe the solution you'd like
I don’t know if you can make something at this point but it would be cool to have a Komga extension on Paperback as there is on Tachiyomi.

### Describe alternatives you've considered or other apps that can do what you want
I opened an issue here first, but maybe you don’t have to make an extension at all and I should ask the Paperback dev to implement an OPDS support.

**Comment by gotson** [comment]
That's interesting, however I do not own any iOS devices. The Komga API is public and documented, and better suited than opds for implementation. The Tachiyomi extension can be used as a model.

I suggest you open a source request on their extensions repository, and link it back here, so people interested could contribute.

**Comment by h-wb** [comment]
Hey @gotson,

As you suggested I opened a source request on the extensions repository !
Someone who's willing to help has the [following question](https://github.com/Paperback-iOS/extensions/issues/103#issuecomment-671318425) : 

> After reading Komga documentation, I have a question: how are mangas stored in Komga?
> If I understood correctly a `series` would be used to represent a manga and the series `books` to represent the manga chapters. That would mean a manga can not have a description or an author… These information would have to be found in the chapters (`books`) of the manga (`series`) in question.

**Comment by gotson** [comment]
They can come and discuss on our Discord if they need to.

And they are correct in their understanding, for now it's not possible, and that's how the Tachiyomi extension works too. 

There are planned features to address those, like #170 and #181

**Comment by gotson** [comment]
Closing this since it's tracked here: https://github.com/Paperback-iOS/extensions/issues/103
