### ISSUE TITLE
[Bug] Not possible to scale webtoon reader (way too big on desktop browser)

### ISSUE THREAD

**Issue by Sheigutn** [gotson/komga#264]
### Komga environment
- **OS**: Windows 10, version 2004
- **Komga version**: 0.52.3
- [x] **I am running Komga from the `jar`**
  - Java version: 1.8.0_261-b12
- [x] **I have a problem in the web interface**
  - Browser (with version): Google Chrome 84.0.4147.105

### Describe the bug
Title, basically.

### Steps to reproduce
1. Open a book with reading direction webtoon set
2. Webtoon way too big on my 24" desktop screen

### Expected behavior
It should be possible for me to adjust the scaling.

### Actual behavior
Book is automatically made to fit to width.

### Screenshots
Desktop behavior: ![image](https://user-images.githubusercontent.com/5239767/89663738-4b879880-d8d6-11ea-8993-a9c3415acf84.png)
Phone behavior (still fit to width, but I guess that's why it looks good): https://media.discordapp.net/attachments/494795764480868386/741326402883682455/Screenshot_20200807-180607.jpg

### Example file
Here's the webtoon I used for the screenshot: https://we.tl/t-5euneojFO3

**Comment by gotson** [comment]
Shrink your browser window.

**Comment by gotson** [comment]
To give you a bit more details, this is not a bug, at best à feature request. There's an open PR to add side padding to webtoon.

**Comment by Sheigutn** [comment]
Yeah, I figured that was the case. I was gonna start working on my own PR yesterday when I saw that someone had already opened one.
