### ISSUE TITLE
[BUG] Insertion failed because database is full (SQLITE_FULL)

### ISSUE THREAD

**Issue by Inervo** [gotson/komga#267]
Hi,

I'm using the last version of Komga (v0.52.3-master)
I've tried to mark as read all my book collection, and i've encounter an error, stating that the database is full.
My hard drive still have more than 1TB available, and the database is currently at 89 MB.

Did i do something wrong, or is there an issue somewhere?

Thank you in advance, and for this great software :)

[komga-error.log](https://github.com/gotson/komga/files/5047073/komga-error.log)

**Comment by gotson** [comment]
Do you have multiple partitions or volumes?

you didn't follow the template so I don't know which version, method, and OS you are running...

**Comment by Inervo** [comment]
Sorry for that :/

I'm only running on a single volume.
### Komga environment
- **OS**: Synology (only 1 volume, 2 TB are free on it)
- **Komga version**: v0.52.3-master
- **I am running Komga from the `jar`**
  - Java version: 1.8.0_212

### Steps to reproduce
This happened will I tried to mark as read my books.
Now, even a single book to mark as read throw this exception, and the book isn't marked as read

**Comment by gotson** [comment]
Which Unix user is running Komga?

Do you have a custom `application.yml`?

**Comment by Inervo** [comment]
I have a custom application.yml, only modifying the server port to 8082. That's all.

The Unix user running Komga is a dedicated user (that I named Komga), who is the owner of all Komga files and have read/write access to the books files and folders. 
The database (sqlite and previously h2) are owned by this "komga" user

**Comment by gotson** [comment]
Can you check the synology quotas for that user?

Can you also perform a `du -h` and `df -h` with the `komga` user and provide the details here?

Can you also `ls -al` in the folder `~/.komga/` of the `komga` user and paste the details here?

**Comment by Inervo** [comment]
Ooops, sorry, found the issue... it was me ^^

I had the `~/.komga/` folder in a synology filesystem volume and not my volume1, and this filesystem volume was full.
I have changed the volume, and no more issues.

Sorry for bothering you with that issue, thanks for your help :)
