### ISSUE TITLE
[Bug] Komga not reading certain settings from application.yml

### ISSUE THREAD

**Issue by mmacdonell** [gotson/komga#268]
### Komga environment
- Windows 10
- Komga 0.52.3
- I am running Komga from the `jar`
  - Java version: 1.8.0_261
- I have a problem with the application.yml file

### Describe the bug
I'm using the application.yml (located in the same folder as the jar file) to set the following settings: 

- server.port to 9090
- database.file
- spring.datasource.url
- logging.file.name

However, the **server.port** and **logging.file.name** settings are not applied during the startup. Komga will start up with server port 8080 and then error out, as another application has 8080 set.  Similarly, the logging file is created in the default location, i.e. ~/.komga/komga.log

Setting the **server.port** variable through the command line, i.e. java -jar -Dserver.port=9090 komga-0.52.3.jar, will work but this is not ideal.

### Steps to reproduce
1. Create an application.yml file to set the **server.port** setting to a different value than 8080.
2. Start Komga through the java -jar command.
3. Application fails to start on the specified port.

### Expected behavior
Komga should respect the defined settings, i.e. start on the given port (9090) and using the defined log file location.

### Actual behavior
Komga failed to start, using port 8080 and not the defined port setting (9090). Given port 8080 is already in use by another app, it failed.  In addition, log files were dropped into the default folder, not the folder defined in the application.yml file.

### Additional context
Other settings, like **database.file** and **database.file** are used as expected.

application.yml file attached.
[application.yml.txt](https://github.com/gotson/komga/files/5048032/application.yml.txt)

### Log file
Log file attached.
[komga.log](https://github.com/gotson/komga/files/5048026/komga.log)

**Comment by gotson** [comment]
The doc mentions where the file must be located:

> by using an application.yml file located in the current directory when you start Komga

Can you provide the absolute path of where you jar is, where you yml file is, and from which folder you start komga, and the exact command line used?

**Comment by mmacdonell** [comment]
Everything was run from the same directory, C:\ProgramData\Komga.

The jar file and application.yml file are in that directory.

Command was run from that directory.

java -

I did notice your comment, re: spacing.  My bad, 1st time using an application.yml file; my Java days (Enterprise) pre-date all this Spring stuff.  Looking at it now with your comment in mind, that makes sense.  I will retry with the proper spacing and update the issue accordingly.

Cheers,

Marc



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mmacdonell** [comment]
Thanks gotson! Once the indentation was corrected, the settings were properly applied.
