### ISSUE TITLE
[Feature Request] Bulk download of a serie

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#273]
### Describe the solution you'd like
Possibility to have download button for a serie as a zip

### Additional context
Exploring a komga library from a friend, the temptation is very high to grab a bunch of book for myself.

Don't know if the feature is reasonable or even possible to create on the fly a zip of a serie and serve it.

**Comment by sam5558** [comment]
Lol, i had the same "temptation" when browsing your library also....

I had to download manually but yeah, i wish it could be possible to bulk download.

**Comment by gotson** [comment]
Bundling a zip is feasible, though it would be stored on a temp directory, which could be a problem for small hosting systems.

Downloading a huge zip would probably not be efficient, and the current download doesn't handle resume from what I can tell.

**Comment by prysme01** [comment]
So we will have to wait for the multi-instance collaboration then :)

**Comment by prysme01** [comment]
suggestion : adding a download in the Series view on each tome, under the more icon (allowing to not click on each tome to be able to download)

**Comment by Pfuenzle** [comment]
You could look into how h5ai (a file index server) manages their zip file downloads. 
It allows to zip multiple files to stream them to the client, and from what ive seen it does not create a temp file, so it should be fine for small systems.

**Comment by gotson** [comment]
> You could look into how h5ai (a file index server) manages their zip file downloads.
> It allows to zip multiple files to stream them to the client, and from what ive seen it does not create a temp file, so it should be fine for small systems.

If not a temp file it would need to fit in memory, which is even a bigger problem for small systems.

**Comment by Pfuenzle** [comment]
Right, didn't think about that.
The webserver should know, which parts have been already sent, right? So would it be possible to for example create 50MB steps, and then after the first 50MB has been sent, dispose of the first 50MB, as the client already has them and create/send the next 50MB.
50MB ist Just an example, could be configurable, if this even works at all.

**Comment by prysme01** [comment]
works perfectly ... great feature thanks !

**Comment by gotson** [comment]
> works perfectly ... great feature thanks !

all the credit goes to @Snd-R !

**Comment by sam5558** [comment]
Thanks @gotson @Snd-R 
This is a time-saving feature, love it !
