### ISSUE TITLE
[Feature Request] subfolders and series.

### ISSUE THREAD

**Issue by zFerry98** [gotson/komga#275]
Hi, I'm new and maybe that's why I may not understand. The description says it supports manga, so if I have a folder structure like this:

![image](https://user-images.githubusercontent.com/17975351/90322425-1fae8780-df54-11ea-885b-41812ecf4826.png)

Which is a basic structure for manga (since they are released in chapters and not in volumes, see jump android and VIz)
Why does Komga see volume 01 as if it were a manga?

Basically, Komga sees each folder called "volume" inside the manga folder (eg manga folder = Fairy Tail) as if it were a manga. The library is filled with a series in progress with the name "volume 01 02 03 ... 96 etc" with the various ".zip" contents inside.
Please don't tell me that it is enough to create a zip called volume 01 with all the .jpg of the various chapters inside because only hajime no ippo are 1200 chapters and only 1 series out of another 50 from a bunch of chapters with even more than 80 pages inside by chapter.
The fact is that the description says that it also acts as a Manga reader and if so you expect it to read the basic structure of the manga in chapters as for other webserver readers (mango, Tachiyomi, mangaeden, mangafox).
I apologize for English and this is not meant to be an offensive comment.

**Comment by gotson** [comment]
Hi,

Please check the [documentation](https://komga.org/guides/scan-analysis-refresh.html) de to understand how it works.

You can also check #46.

**Comment by gotson** [comment]
What would you expect to see in terms of series / books, given your example above?

**Comment by zFerry98** [comment]
### What do you expect: 

https://i.imgur.com/nGKjTfA.mp4


### What happens instead:

https://i.imgur.com/rAEZCwM.mp4

I can understand this case where the folder is called 02 - House of Evolution (which would be volume 02 of the aforementioned series).
This is right because without separate chapters. But it is not fair, the manga work in chapters (the paper versions obviously do not come out in chapters but in volumes, the digital versions Come su S. Jump for android are in chapters).
I know it reads ".xml" inside ".zip" but those only work for volume series.

https://i.imgur.com/XB1Zy1b.mp4

<details>
  <summary>Images</summary>
  
What do you expect:
![image](https://user-images.githubusercontent.com/17975351/90330380-b1e27a00-dfac-11ea-9c1a-b2aeb677129b.png)
![image](https://user-images.githubusercontent.com/17975351/90330405-c292f000-dfac-11ea-8e82-cad3becbc09b.png)
![image](https://user-images.githubusercontent.com/17975351/90330410-cd4d8500-dfac-11ea-8563-7f02f351624f.png)
![image](https://user-images.githubusercontent.com/17975351/90330418-da6a7400-dfac-11ea-8450-e1c0b1e31e2a.png)
----------------------------------------------------------------------------------------------------------------------------------------------
What happens instead:
![image](https://user-images.githubusercontent.com/17975351/90330699-1272b680-dfaf-11ea-8011-e68ac9ad360f.png)
![image](https://user-images.githubusercontent.com/17975351/90330703-1ef70f00-dfaf-11ea-8645-a7fbd66732fa.png)
I can understand this case where the folder is called 02 - House of Evolution (which would be volume 02 of the aforementioned series).
![image](https://user-images.githubusercontent.com/17975351/90330725-69788b80-dfaf-11ea-9374-a21284aa1c41.png)
![image](https://user-images.githubusercontent.com/17975351/90330734-7a290180-dfaf-11ea-98a0-1c9e88db0924.png)
This is right because without separate chapters. But it is not fair, the manga work in chapters (the paper versions obviously do not come out in chapters but in volumes, the digital versions Come su S. Jump for android are in chapters).
I know it reads ".xml" inside ".zip" but those only work for volume series.
----------------------------------------------------------------------------------------------------------------------------------------------
Folder structure:
![image](https://user-images.githubusercontent.com/17975351/90330441-fd952380-dfac-11ea-975f-4f47f9c9e7ea.png)
![image](https://user-images.githubusercontent.com/17975351/90330449-0980e580-dfad-11ea-9a86-16c22784d489.png)
![image](https://user-images.githubusercontent.com/17975351/90330453-10a7f380-dfad-11ea-8633-812ef4f1c31f.png)

</details>

**Comment by sam5558** [comment]
Hi @zFerry98 ,
In komga, **one** directory means **one** series. In your case you put multiple directories in the same manga which causes komga to create as much "series" as it finds of "directories".

I saw in one of your captures the manga one punch man, so i'll show you an example of how i handle it.
This is the structure of my one punch man directory : 
```
.
├── One Punch Man T01.cbr
├── One Punch Man T02.cbr
├── One Punch Man T03.cbr
├── One Punch Man T04.cbr
├── One Punch Man T05.cbr
├── One Punch Man T06.cbr
├── One Punch Man T07.cbr
├── One Punch Man T08.cbr
├── One Punch Man T09.cbr
├── One Punch Man T10.cbr
├── One Punch Man T11.cbr
├── One Punch Man T12.cbr
├── One Punch Man T13.cbr
├── One Punch Man T14.cbr
├── One Punch Man T15.cbr
├── One Punch Man T16.cbr
├── One Punch Man T17.cbr
├── One Punch Man T18.cbr
└── One Punch Man TXX.cbr
```
And here's how komga handles it : 

![image](https://user-images.githubusercontent.com/26897744/90331379-ab9fce00-dfab-11ea-8d27-b8b1b7ef7053.png)


You can either have chapters or volumes, personally i prefer to have volumes because it's cleaner and more usable for me.
Also, with volumes i can put the metadata in xml inside a cbz or cbr and voilà !

Hope it does help you a little bit.

**Comment by gotson** [comment]
Given chapters have absolute number, why not put all the chapters inside the manga folder? What's the point of your "volume" directories?

**Comment by zFerry98** [comment]
Why is this the way manga is, otherwise they are stupid to draw the covers of the volumes?
Because if you have 16 series of 40 pages each for 8 chapters with volumes =
x16 times, create "One punch - Volume 01.zip", Rename with BulkRename each .jpeg inside the various Chapter.zip from 01 02 03 04 ... 40 to the number 99999 ... and then? Cap 8000 comes out tomorrow, repeat step x16 for all the times a chapter of a series comes out ...
The volume advantage seemed obvious to me.
Plus it's sorted, Another> Volume 01> its chapters.
If you buy Another, do you buy 4 volumes or a tome of the lord of the rings?

I don't want to force and I don't want to be offensive, I wanted to understand if I was wrong to put things in the folders or name.
If the policy of this application is that you must use the structure for Comics (series without chapters) or style (illegal to own them outside the host platform) digital amazon, ebok then fine.
I keep using Tenma, LANraragi and Mango which are suitable for their various purposes.
I asked, why a friend of mine preferred your image reader for the "front-end" over those of the competition.

Thanks for the support anyway.

![image](https://user-images.githubusercontent.com/17975351/90331795-a3e62680-dfb7-11ea-800a-7866289933b0.png)
![image](https://user-images.githubusercontent.com/17975351/90331801-ba8c7d80-dfb7-11ea-9cf2-d9c1c071926e.png)

**Comment by gotson** [comment]
You misunderstand something though, mangas do not have covers until they are released in tankobons. So if they are already out in tankobon, there's no need to have chapters anymore they already have been collected. 

Mangas are not solely distributed in chapters, but also on tankobon. 

Basically if you are using covers on a bunch of chapters you could as well package them in a cbz, since all the chapters for that volume are already out.
