### ISSUE TITLE
Add/rearrange metadata fields for Series and Book

### ISSUE THREAD

**Issue by gotson** [gotson/komga#276]
I have some plans to add metadata fields to Series/Books, and rearrange some fields from Books to Series. This issue is to centralize those improvements.

# Series metadata
- Publisher: to be moved from Book to Series
Migration: the Series will inherit the first non-null Publisher from its books in descending order (starting from the last book)
- Age Rating: to be moved from Book to Series
Migration: the Series will inherit the ~~smallest~~ highest non-null Age Rating from its books.
- Reading Direction: to be moved from Book to Series (mentioned in #116)
Migration: the Series will inherit the most-present value in its books.
- Summary: a new field to store a small description of the Series (mentioned in #170)
- Language: the language of the publication, using an [IETF language code](IETF language tag)
- Genres: a list of tags, chosen either from a list of default values, or custom values.
- Tags: a list of tags. Will be helpful for various use cases (mentioned in #280).

# Book metadata
- Publisher: will be moved to Series
- Age Rating: will be moved to Series
- Reading Direction: will be moved to Series
- Tags: a list of tags. Will be helpful for various use cases (mentioned in #280)

The webreader will need to be adjusted to get the Reading Direction from the Series instead of the Book.

**Comment by prysme01** [comment]
I would like that every metadata already displayed in book  (publisher/penciller/colorist/cover and summary) to be inherit from the first non null book to the Serie. That make a lot of sense for BD will only one book. All my book are tagged and I almost get nothing in the serie :(

**Comment by gotson** [comment]
> I would like that the serie inherit from all metadata already displayed in the first non null book (publisher/penciller/colorist/cover and summary), That makes a lot of sense for BD will only one book. All my book are tagged and I almost get nothing in the serie :(

That's a different issue, see #181

**Comment by prysme01** [comment]
ok I thought it was related this work.

**Comment by grim7reaper** [comment]
> Migration: the Series will inherit the smallest non-null Age Rating from its books.

Why the smallest instead of the highest?
It looks safer to me to fallback on the highest: if we have a mix of 12 and 16, it's better to prevent 12 years old people to access the books tagged 16+, no ?

**Comment by gotson** [comment]
> > Migration: the Series will inherit the smallest non-null Age Rating from its books.
> 
> Why the smallest instead of the highest?
> It looks safer to me to fallback on the highest: if we have a mix of 12 and 16, it's better to prevent 12 years old people to access the books tagged 16+, no ?

Thanks for noticing this one, indeed that's what i wanted to do, and I mixed things up 👍

**Comment by gotson** [comment]
As part of this I will change the way the metadata from various books is applied at series level.

**Current behaviour:** _title_ and _status_ would only be applied if the value was unique among all books.

**New behaviour:** for _title_, _status_, _publisher_, _language_, and _reading direction_ the most frequent value among the books will be used.

**Comment by GlibTongue** [comment]
Can you also add the fileds, Theme, Tags, Demographic Protagontist.

Theme, Tags & Demographic: best example would be how mangadex does. For example check out this sieres on mangadex ID: 36284

Protagonist: This field to display If there Single Protagonist, Multiple Protagonist, If male or female or both (Though the tags field can also be used for this)

**Comment by grim7reaper** [comment]
+1 for having a tag field.

Demographic looks manga-centric.
If the concept also exists for comics and European BDs why not, otherwise I think it can be a tag.

Ditto for Protagonist, looks super specific and I'm not sure everyone would want/need to have this kind of hardcoded field. IMHO, a tag is better for this kind of information.

For theme, I'm not sure how different it is from a tag?

**Comment by gotson** [comment]
> Can you also add the fileds, Theme

There will be a Genre list, what is the difference with a Theme?

**Comment by GlibTongue** [comment]
> > Can you also add the fileds, Theme
> 
> There will be a Genre list, what is the difference with a Theme?

Well genre is like a category like Action, Fantasy etc, while a theme is like an Idea, topic, subject etc such as Reincarnation, Vengeance etc.

**Comment by gotson** [comment]
> I think having Demographics would be useful if the server is shared with multiple users (That's what I eventually want to do). Will just help users into finding things aimed at them easier.
> 
> >

What's demographics ? Do you have an example?

**Comment by GlibTongue** [comment]
> > I think having Demographics would be useful if the server is shared with multiple users (That's what I eventually want to do). Will just help users into finding things aimed at them easier.
> > >
> 
> What's demographics ? Do you have an example?

This comes from manga. So before manga is published in to volumes they are in most cases are published in magazines as chapters as the come out. Those magazines are in a way a collection of chapters of different manga series.

And there are different magazines aimed for different audience, for example: 

```
Kodomomuke or Kodomo - young children, under about 10
Shonen - boys, roughly 12-18
Shoujo - girls, roughly 12-18
Josei - younger women, roughly 18-40
Ladies Comics - The female equavelent to Ero manga
Seinen - younger men, roughly 18-40
Seijin (Adult) or Ero - men's pornographic (see Hentai)
Mina - or "Multiple Demographic Appeal" in troper
Alternative or Uncategorized - includes Gekiga

[taken from tvtropes.org]
```

**Comment by gotson** [comment]
That would better fit in a tag IMHO.

**Comment by Sheigutn** [comment]
I think it'd also be nice to have fields in the series for author and artist so Tachiyomi could show those, for now it still shows unknown author for each series.

**Comment by gotson** [comment]
> I think it'd also be nice to have fields in the series for author and artist so Tachiyomi could show those, for now it still shows unknown author for each series.

That's part of #181
