### ISSUE TITLE
[Feature Request] Add option to tag a serie and a book

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#280]
### Describe the solution you'd like
I would like to be able to delete a specific book (bad quality for example) or serie (i don't like it).

### Describe alternatives you've considered or other apps that can do what you want
An alternative would be to at least be able to mark as "to be deleted" and been able to list thoses file/serie to manually delete them in the library filesystem

**Comment by gotson** [comment]
Komga has a no touch policy. You need to delete the files on your filesystem directly and rescan to remove them in Komga.

**Comment by prysme01** [comment]
I am fine with the policy, but having a way to tag series or book and a filter on this tag to retrieve it would be nice.

**Comment by gotson** [comment]
superseded by #276
