### ISSUE TITLE
[Feature Request] From a book going up to the serie

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#281]
### Describe the solution you'd like
From a book page, it would be nice to have a UP button somewhere to go to the serie page.

Actually there is no way to go to the parent serie of a book except the search bar.

**Comment by gotson** [comment]
Just click the Series name.

<img width="461" alt="Screenshot 2020-08-21 at 09 20 24" src="https://user-images.githubusercontent.com/2139133/90841581-8fc37000-e38f-11ea-83d6-cd5ac3ea6654.png">
