### ISSUE TITLE
Tachiyomi Extension 1.2.15 - Not displaying all chapters

### ISSUE THREAD

**Issue by TSedlar** [gotson/komga#284]
For whatever reason the latest update to the plugin is only displaying the first 20 chapters on all series.

It worked perfectly fine until I updated to version 1.2.15.

**Comment by gotson** [comment]
Please follow the issue template. Are you using a Komga server minimum version of `0.56.0` as indicated in the [CHANGELOG](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/all/komga/CHANGELOG.md) ?

**Comment by TSedlar** [comment]
Apologies, that fixed it.

Didn't even know about changelogs for extensions -- would be nice if Tachiyomi had a way to view them in the app.

Thanks.

**Comment by gotson** [comment]
Tachiyomi's extensions are mostly fixing bugs, that kind of dependency with the server side component is really specific to Komga, maybe Lanraragi also.

**Comment by atomicwrites** [comment]
@gotson Huh, I'm having the same issue but I'm on Komga 0.62.5 (latest Docker image).

**Comment by gotson** [comment]
> @gotson Huh, I'm having the same issue but I'm on Komga 0.62.5 (latest Docker image).

Do not comment on closed issues, please open a new one.
