### ISSUE TITLE
OPDS paginated feed

### ISSUE THREAD

**Issue by frameset** [gotson/komga#285]
### Komga environment
- **OS**: Ubuntu
- **Komga version**: 
- [✔] **I am running Komga with Docker**
  - latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [✔] **I have a problem with an OPDS client application**
  - OPDS Application (with version): Chunky (latest stable app store)
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When a series has a large number of items (in my case around 2200) it can take so long for Komga to serve the request that the client times out.

### Steps to reproduce
1. Have a series with a large number of items
2. Note the series ID
3.  Navigate to `/api/v1/series/{id}/books?unpaged=true` for API or `/opds/v1.2/series/{id}` for OPDS
### Expected behavior
Komga to return the response within a time frame that the average client will accept.

### Actual behavior
With the API requst, testing in Firefox gave a time of 1.35 minutes, and for the OPDS 1.75 minutes.

### Screenshots
OPDS timings:
![image](https://user-images.githubusercontent.com/559869/91172661-6f1f5100-e6d4-11ea-99a7-fc02530f0af0.png)
API timings:
![image](https://user-images.githubusercontent.com/559869/91172675-76def580-e6d4-11ea-8122-3bb12a9476de.png)

**Comment by gotson** [comment]
Not really a bug, requesting heaps of data will be slow. That's why the REST API has a pagination mechanism.

The OPDS spec also supports pagination, which could be implemented in Komga to mitigate this behaviour.

**Comment by gotson** [comment]
Solved via 41f3e8dc638178846f37da21f17d2a314692b33e which increased performance by a factor of 60 (!)
