### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by gotson** [gotson/komga#29]
At the moment the search results are limited, and displayed in the popup under the search box.

Expected behavior:

- when pressing <kbd>Enter</kbd> in the search box, the user should be redirected to the Search Results page
- a link to the search results page should be shown in the popup if there are too many results
- the search results page should show all results

**Comment by anderaith** [comment]
The more I use Komga, the more this becomes a necessity.
I have a big collection and I cannot always refine my search to get under 10 results.

**Comment by gotson** [comment]
This is a first implementation for the search results screen.

Akin to Plex Web, the results are displayed in a horizontal scroller. Results are limited to 50 items.
