### ISSUE TITLE
[Feature Request] Better select options

### ISSUE THREAD

**Issue by keinezeit8** [gotson/komga#291]
When editing a lot of series (e.g. adding a whole new library, first setup) every series has to be edited, or at least selected for editing, separately.

### Solutions
When selecting the first series, buttons for selection (i.e. Select All/Select None/Invert selection) should appear, to make selection easier.

### Alternatives
Keyboard shortcuts:

- CTRL + a (select all)
- CTRL (Add clicked series to selection)
- CTRL +SHIFT (Selects all series between two clicked series)

### Additional context
Icons:
Select all: https://www.flaticon.com/free-icon/select-all_60833

Keyboard shortcuts work in most text editors, browsers, file explorers ...

**Comment by gotson** [comment]
What's the use case exactly? What kind of mass edits would you do on multiple series?

**Comment by keinezeit8** [comment]
- Adding a new library for example "Fantasy" and adding the tag fantasy to all of them.
- Wanting to marking all of them as completed. (Old comic collection)
- Setting language of all books.
  - Most people only read in one language and have to edit every entry
- Setting many series' age limit
- ...
