### ISSUE TITLE
[Bug] Series are duplicated when books are not in the same folder

### ISSUE THREAD

**Issue by goodevilgenius** [gotson/komga#292]
### Komga environment
- **OS**: Fedora Linux
- **Komga version**: 0.59.0
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk version "1.8.0_265"

### Describe the bug

I don't have books from the same series in a single folder. I assumed that since Komga uses the series from the `ComicInfo.xml`, that they would be combined. Instead, I have a separate series with the same name for each issue.

### Steps to reproduce

1. Create a folder structure like the following:
    ```
    /Root
      /Author
        /Book1
          Book1.cbz
        /Book2
          Book2.cbz
    ```
2. Add the library to Komga
3. Wait for all books to be scanned
4. Look at library, and see two series with the same name, instead of Book1 and Book2 under a single series

### Expected behavior

Series with the same name should be collapsed into a single series, instead of multiple series

### Actual behavior

Series is duplicated

### Additional context

For further information, my folder structure is organized in this way because I'm currently using Calibre, and wanted to try to use Komga and Calibre together by just adding my Calibre library root as a library in Komga.

### Screenshots

![2020-08-26_09 10 48_Komga](https://user-images.githubusercontent.com/254662/91314698-7437db00-e77c-11ea-94df-e9f194652c24.png)

Each of these series have a single book in them.

**Comment by gotson** [comment]
That is the expected behaviour.

From the [documentation](https://komga.org/guides/scan-analysis-refresh.html#what-happens-during-a-scan):
> Komga will create a Series for each subfolder of any library, whatever the depth of this subfolder in your directory structure

And for the [metadata](https://komga.org/guides/scan-analysis-refresh.html#import-metadata-for-cbr-cbz-containing-a-comicinfo-xml-file):
> The `Series` tag will be used to overwrite the title of the Series. If multiple values are present, the most frequent value from all books will be used.

**Comment by goodevilgenius** [comment]
I think the documentation should explicitly state this, if that's the intended behavior.

I read the documentation prior to using the software, including both of those quoted sections. It was not obvious to me that this would happen.

I've used a few different ebook management applications. Based on my experience with other software, my expectation was that books belonging to series with the same name would actually be grouped in the same series. It should probably be explicitly stated that that's not the behavior here. Something like:

> The Series tag will be used to overwrite the title of the Series. If multiple values are present, the most frequent value from all books will be used. This will result in duplicate series in the library, if books of the same series are in different folders.

**Comment by gotson** [comment]
It's the same as plex really, you can rename items it doesn't merge them together. It's folder driven.

![Screenshot_20200827-230630](https://user-images.githubusercontent.com/2139133/91460257-34770d80-e8ba-11ea-9e4a-bc2dfc47981b.jpg)

And it's also common in books to have different series that have the same name, but are different series nonetheless. It wouldn't make sense to merge them on something that is not recognized as a unique identifier.

**Comment by grim7reaper** [comment]
> And it's also common in books to have different series that have the same name, but are different series nonetheless. It wouldn't make sense to merge them on something that is not recognized as a unique identifier.

:+1:

An example I came across recently : there are two (and maybe more…) manga adaptation of "No Longer Human" from Osamu Dazai (one by [Junji Ito](https://www.viz.com/read/manga/no-longer-human/product/6126), and another one by [Usamaru Furuya](http://www.vertical-inc.com/books/archive/nolongerhuman.html)).

**Comment by goodevilgenius** [comment]
It's up to you obviously to do whatever you think is best for your software.

But, I do think it would be better to explicitly state this in the documentation. Yeah, someone might conclude this from what the documentation already says, but if it was explicitly stated, there would be no guessing.

And since there's not even a way to combine duplicate series, it makes it even more problematic.

I wasted a lot of time waiting for Komga to parse my library. It took an entire day for it to go through all of my books. And it bumped up my CPU usage from my usual idle usage of about 5% to around 90%.

Had I known ahead of time that this software wouldn't work for my needs, I wouldn't have bothered wasting my time and electricity.
