### ISSUE TITLE
[Bug] Book does not contain any pages

### ISSUE THREAD

**Issue by goodevilgenius** [gotson/komga#293]
### Komga environment
- **OS**: Linux
- **Komga version**: 0.59.0
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk version "1.8.0_265"

### Describe the bug

Some ePubs are being incorrectly parsed. A number of books in my library show zero pages, and in the media analysis, there's an error that says "Book does not contain any pages". Those books open in other epub readers just fine, and show all pages.

### Expected behavior

Books should be parsed correctly

### Actual behavior

Pages not recognized. Sometimes, "Book does not contain any pages". Sometimes only three pages are shown.

### Examples

Here's a Project Gutenbook ePub I have that has this problem: https://www.dropbox.com/s/vdt473do54d0df1/Memoirs%20of%20Sherlock%20Holmes%20-%20Arthur%20Conan%20Doyle.epub?dl=0

The problem is not only found in Gutenberg books. Many others I have from various sources have this same issue.

https://www.dropbox.com/s/afnxhqeqc8hn206/Fairy%20Tales%20of%20Hans%20Christian%20Andersen%20-%20Hans%20Christian%20Andersen.epub?dl=0

This one shows only three pages: the cover image, and two more images. The actual pages are not shown at all.

**Comment by gotson** [comment]
eBooks are not supported, only comics containing images.

See the [documentation](https://komga.org/guides/#komga-supports-these-media-file-types), and also #221
