### ISSUE TITLE
[Feature Request] limit upload bandwidth

### ISSUE THREAD

**Issue by Machin77** [gotson/komga#297]
Hello,

I would like to have more user management if possible.

=> Possibility of being able to limit the bandwidth used during a user download.
=> Vision of users who connect to komga (IP address) in the logs or via a screen like on Tautulli.

I think other features could be added but nothing really useful immediately.

Thanks to you for komga.

**Comment by gotson** [comment]
> => Vision of users who connect to komga (IP address) in the logs or via a screen like on Tautulli.

This is already logged as #160 I believe
