### ISSUE TITLE
[Feature Request] Addition of number of books per series in the metadata

### ISSUE THREAD

**Issue by Machin77** [gotson/komga#298]
The idea would be to add a field that will identify the total number of books in a finished series.
This field will allow to know the progress of the series compared to what the user has on komga.

**Comment by gotson** [comment]
reopen for theotocopulitos

**Comment by theotocopulitos** [comment]
Thanks for reopening this.

Having a counter (specially for finished series, but could work for all), that displays the total number of issues released in a series vs the actual number in the user's collection would be a great addition, helping to easily identify series with missing issues.
