### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by gotson** [gotson/komga#30]
Ability to group Series into Collections.

Those collections could be used for different purposes:

- group related Series, for example from the same universe
- curate lists, for example reading lists or favorites

~~Collections should be manually managed by each user.~~

~~Collections could also be shareable, but the details of this need to be refined.~~

Expected behavior:

- [x] Only admin users can create, update, and delete collections
- [x] All users can see collections, limited by the libraries they are authorized on
- [ ] When refreshing metadata, the _SeriesGroup_ field from `ComicInfo.xml` should be used to generate a collection if it doesn't exist, or add the series to an existing collection

**Comment by nbo21** [comment]
It would be great if collections could be created automatically from metadata fields.

I would like to use the Series Group field from ComicRack metadata (https://github.com/gotson/komga/issues/54) to group related series.

**Comment by gotson** [comment]
> It would be great if collections could be created automatically from metadata fields.
> 
> I would like to use the Series Group field from ComicRack metadata (#54) to group related series.

There's no Series Group in ComicInfo as far as the [spec](https://gist.github.com/gotson/29ebdbc7e4a21c127889f065864a363b) says.

**Comment by nbo21** [comment]
That file seems to be an old version. There are a number of missing fields: Characters, Teams, Locations, ScanInformation, StoryArc, SeriesGroup, AgeRating

This one looks accurate: https://github.com/wyldphyre/ComicArchive/blob/master/ComicArchive/ComicRack/ComicInfo.xsd

**Comment by gotson** [comment]
Thanks, that's very useful. How does this `SeriesGroup` work or is expected to behave then? You just put a `string` key, and then you can see all the Series that have the same key?

**Comment by nbo21** [comment]
Yes, but I mainly thought about the issue of displaying Series located in subfolders as mentioned here: https://github.com/gotson/komga/issues/46

I would like to see Series grouped under SeriesGroup:

~~~
Manga
├── Series A
├── Series B
├── SeriesGroup C (Collection)
│   ├── Series C1
│   ├── Series C2
...
~~~

**Comment by gotson** [comment]
Once collections are there I plan to add a helper to easily create collections from subfolders, and I could have one that would create collections from the SeriesGroup field in ComicInfo too.

**Comment by gotson** [comment]
> Yes, but I mainly thought about the issue of displaying Series located in subfolders as mentioned here: #46
> 
> I would like to see Series grouped under SeriesGroup:
> 
> ```
> Manga
> ├── Series A
> ├── Series B
> ├── SeriesGroup C (Collection)
> │   ├── Series C1
> │   ├── Series C2
> ...
> ```

I just added `Sort Title` for series, so for now at least you can see series grouped together, even if the title is very different, without changing your folder names.

**Comment by cesalo** [comment]
Just thinking out loud here: Why not something similar to what Plex does? At library level there could be available all the different characteristics/properties of series/books and sorting details .. then you choose what ever you want: Publisher and/or Series and/or StoryArc plus order by name or date added plus series ended or ongoing plus series that are unread or in-progress .. and then an option to create a collection from it (In Plex is a Playlist or Smart Playlist).

![Screenshot from 2020-06-08 14-50-48](https://user-images.githubusercontent.com/16859916/84068801-841efa80-a997-11ea-8d94-7b2a5683c870.png)

**Comment by gotson** [comment]
That's an entirely different feature. Plex has collections, that's what I want to replicate here. Feel free to open a feature request for smart playlists.
