### ISSUE TITLE
[Feature Request] When double pages is enabled, allow the cover to be shown on its own, or alongside the next page 

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga#300]
### Is your feature request related to a problem? Please describe.
How it appears now 
![image](https://user-images.githubusercontent.com/65789901/91646334-809e8b00-ea3d-11ea-97f7-bea343e1a18d.png)

### Describe the solution you'd like

The option id like 
![image](https://user-images.githubusercontent.com/65789901/91646335-8d22e380-ea3d-11ea-86c4-0079e6eb5a6c.png)
### Describe alternatives you've considered or other apps that can do what you want
Cover has this option, laid out like this, 
![image](https://user-images.githubusercontent.com/65789901/91646357-c0657280-ea3d-11ea-9ac6-dc520d34c49d.png)

**Comment by gotson** [comment]
This is already implemented (see #103)
