### ISSUE TITLE
[Bug] OPDS - Latest series sorted by date ascending, instead of descending

### ISSUE THREAD

**Issue by claym** [gotson/komga#301]
### Komga environment
- **OS**:  Ubuntu 18.04.5 LTS
- **Komga version**: v0.62.1-master
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: Latest, installed via Cloudbox/Community

### Describe the bug
It appears that the order in the Latest Series in oldest -> newest, whereas one would expect it to be sorted descending (newest -> oldest)

### Steps to reproduce
1. Go to https://<domain>/opds/v1.2/series/latest

### Expected behavior
The most recently updated series is displayed first

### Actual behavior
The most recently updated series is displayed last

Pretty straight forward. Having it sorted old -> new kind of defeats the purpose of "Latest series" :)

**Comment by gotson** [comment]
Looks like this has gone unnoticed since `0.31.0` !

**Comment by claym** [comment]
Looks good. Thank you!
