### ISSUE TITLE
[Feature Request] Strip leading and trailing spaces from tags and genres

### ISSUE THREAD

**Issue by grim7reaper** [gotson/komga#302]
### Is your feature request related to a problem? Please describe.

Yesterday I spent some time troubleshooting what I thought was a duplicated genre issue (I was seeing two genre `Supernatural` in the filter menu).
After a while, I went to have a look directly into the SQLite DB and I realize that some genre, including one of the "duplicate", had one or more trailing spaces (which were invisible from the Web UI).
I then proceeded to remove the rogue spaces with some SQL queries.

### Describe the solution you'd like

Genre and tag should be stripped before they are saved into the DB.
This would avoid this kind of confusion (and having to deal with SQL to fix it).

**Comment by gotson** [comment]
Genres are stripped when imported from epub or comicinfo.xml.

If you input manually and add space, IMO it's a pbkac.

**Comment by grim7reaper** [comment]
I usually copy/paste them from some website, and depending what the double-click has selected, I may end up with trailing spaces.
I don't enter those rogue spaces manually :stuck_out_tongue: 

If we already strip them from epub and comicinfo, why not strip them from user input for the sake of consistency?
I can't think of a use case where we would want leading/trailing spaces in them, so it would be a UX improvement :slightly_smiling_face: 

And I think some fields, like `summary` are already stripped, even when coming from the user.

**Comment by gotson** [comment]
Fair enough 🙂

**Comment by gotson** [comment]
> And I think some fields, like `summary` are already stripped, even when coming from the user.

Indeed, see [here](https://github.com/gotson/komga/blob/29d97266137a4f38497e75f1a1f24fbf9ae96f46/komga/src/main/kotlin/org/gotson/komga/domain/model/BookMetadata.kt#L29).

I'll do the same things for collections, so the elements are trimmed when creating a domain object.

I'll throw in a migration script to update the DB ;)
