### ISSUE TITLE
[Bug] Performing an action on selected books does not fully unselect them

### ISSUE THREAD

**Issue by rouhannb** [gotson/komga#303]
### Komga environment
- **OS**: Linux
- **Komga version**: v0.62.2
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: OpenJDK 14.0.2
- [x] **I have a problem in the web interface**
  - Browser (with version): Firefox 80.0
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
On the series page, selecting books and then performing an action (marking it as read/unread, or making edits and then saving them) will appear to not affect the selection at all, but then trying to unselect the books will select them again. In other words, the list of selected books isn’t cleared properly.

### Steps to reproduce
1. Go to any series page.
2. Select any number of books.
3. Mark them as read or unread, or edit them and save the changes.
4. Now, click on the books you previously selected.
5. The books will be selected twice. The only way to actually unselect them is to cancel the selection as a whole.

### Expected behavior
Either the selection will be cancelled after performing the action, or clicking on the books will unselect them.

### Additional context
This does not seem to occur when selecting series on the library page.

**Comment by gotson** [comment]
Not removing the selection is the intended behavior, but I also observed some quirks.

It's also not in line with other applications, where the selection is cleared after an action. 

I'll probably clear the selection after an action to make it simpler.
