### ISSUE TITLE
[Feature Request] add navigation at the bottom of paged browsing screens

### ISSUE THREAD

**Issue by cwhits** [gotson/komga#305]
### Is your feature request related to a problem? Please describe.
I'm frustrated when I'm on a paged browsing screen and have to scroll back to the top of the page to get back to the page navigation.

### Describe the solution you'd like
It'd be nice to have the navigation buttons duplicated on the library navigation page so I don't need to scroll back up to the top of the page to get to the next one.

### Describe alternatives you've considered or other apps that can do what you want
Infinite scrolling would be nicer and that there's already an open issue for it, but this seems not-as-difficult of a request.

### Additional context
None.

**Comment by gotson** [comment]
Please use the template issues they are here for a reason.

Duplicating navigation should be done only when there are scrollbars, else it clutter the UI.

**Comment by cwhits** [comment]
> Please use the template issues they are here for a reason.
updated

**Comment by wyldphyre** [comment]
Count me as another vote for this feature. It’s very annoying to have to reverse all the scrolling I just did in order to move to the next page.
