### ISSUE TITLE
[Feature Request] Disabled/anonymous authentication?

### ISSUE THREAD

**Issue by strig** [gotson/komga#306]
### Is your feature request related to a problem? Please describe.
I don't need authentication for my purposes. The app only runs on my home network and isn't exposed to the internet. 

### Describe the solution you'd like
A way to disable authentication or allow for public/unrestricted access so that I don't have to login.

**Comment by gotson** [comment]
Some core features of Komga like read progress require user accounts, it's not feasible to remove authentication.

**Comment by GlibTongue** [comment]
> Some core features of Komga like read progress require user accounts, it's not feasible to remove authentication.

Hey, I am also up for this. This is actually pretty good. Not everyone wants or even needs an account. For example, those using tachiyomi have no need for any account or any features that come along with it. Also, if you have a massive amount of people who you would like to share the server with it would be a pain to create an account for all the individuals or any at all.

**Comment by mihailim** [comment]
@GlibTongue Easy to work around, create a dummy account and distribute those credentials, exactly like it's done for the [demonstration website](https://komga.org/guides/#demo).
