### ISSUE TITLE
Misleading OpenAPI spec

### ISSUE THREAD

**Issue by grim7reaper** [gotson/komga#308]
### Komga environment
- **OS**: ArchLinux
- **Komga version**: 0.62.3
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk 14.0.2

### Describe the bug

A lot of object's fields (most of them in fact…) are optionals. This makes the API awkwards to use because you need to handles a lot of "field may be missing" cases.

And for several object's fields, I think it doesn't make sense to have them optionals.

For instance, the `LibraryDto` object have all of its field optional, but I would expect `id`, `name` and `root` to be required: `name` and `root` are required in `LibraryCreationDto`, and every objects stored in DB have an `id` => I don't see how they could be missing from `LibraryDto`.

Same for `UserDto` (`email` and `id`) and other objects.

I'm wondering if those `optional` are here on purpose, or if it's because the tooling that generate the OpenAPI spec considers `optional` as default and `required` as opt-in?

### Expected behavior

Have required fields specified as such.

### Actual behavior

Most of the fields are `optional`.

### Additional context

When you use the OpenAPI code generator it translates the optional fields into [Option type](https://en.wikipedia.org/wiki/Option_type) for languages that support them (which makes sense), and having to deal with those even for basic things like `id` and `name` results in a cumbersome API.

**Comment by gotson** [comment]
Not a bug.

**Comment by gotson** [comment]
[Springdoc](https://github.com/springdoc/springdoc-openapi) probably doesn't handle non-nullable Kotlin types properly, or maybe it does but Komga may not be using the latest version.

I don't have time to either test the latest version, nor setup a reproducible example and lodge an issue there.

**Comment by gotson** [comment]
Turns out there is a kotlin module for non-nullable types. I don't think it will handle the Spring types like `Page` though.

**Comment by grim7reaper** [comment]
Thanks for the quick fix :pray: 

> Turns out there is a kotlin module for non-nullable types. I don't think it will handle the Spring types like `Page` though.

That's already a big improvement :slightly_smiling_face:
