### ISSUE TITLE
[Feature Request] Generate series cover from the latest book

### ISSUE THREAD

**Issue by kiriya-aoi** [gotson/komga#312]
### Is your feature request related to a problem? Please describe.
Komga generates a series cover from the cover of the first book in that series, which is fine for things I haven't started but for things I am actively reading it's less desirable (especially in Tachiyomi, where the series cover is the only cover).

### Describe the solution you'd like
An option to generate a series cover from the latest volume in a series (based on sorting number or by release date metadata field).

### Describe alternatives you've considered or other apps that can do what you want
When books are added to my server, I could instead yoink the cover from the new latest volume as the new custom cover manually.

**Comment by kiriya-aoi** [comment]
Thanks stale bot, but I'm still interested in this.

**Comment by kiriya-aoi** [comment]
Does a comment from me not count as further activity?

**Comment by gotson** [comment]
> Does a comment from me not count as further activity?

I think that works only before it's closed. You can reopen the issue if you want.

**Comment by kiriya-aoi** [comment]
Hi bot, still interested.

**Comment by gotson** [comment]
> ### Describe the solution you'd like
> An option to generate a series cover from the latest volume in a series (based on sorting number or by release date metadata field).

Where would that option sit ? Would an option per library work for you?

**Comment by kiriya-aoi** [comment]
> > ### Describe the solution you'd like
> > An option to generate a series cover from the latest volume in a series (based on sorting number or by release date metadata field).
> 
> Where would that option sit ? Would an option per library work for you?

I imagine it sitting either as a library setting or a server config, but I think putting it in the Edit Library menu makes the most sense.
