### ISSUE TITLE
[Feature Request] Support for Annuals

### ISSUE THREAD

**Issue by omgthegreenranger** [gotson/komga#313]
### Is your feature request related to a problem? Please describe.
not really a problem as much as a convenience. Currently there is no way to indicate an Annual (especially on the Tachiyomi extension)

### Describe the solution you'd like
Some way to indicate Annuals on the interface (Mylar will add "Annual" to the naming convention, for instance). Perhaps pulling the publishing date and/or some other logic, put in the sort order at the correct position in reading the comic run (i.e. "Justice League 11, Annual 1, Justice League 12 in order).

### Describe alternatives you've considered or other apps that can do what you want
Include the Annual flag or name in the display name.

**Comment by gotson** [comment]
There's no need for that, you can use book metadata to achieve the same result:
- change the _number sort_ to `11.5` to place the book between 11 and 12
- change the `number` to `Annual 1`
