### ISSUE TITLE
Question about Sort Number

### ISSUE THREAD

**Issue by RoyNewo** [gotson/komga#314]
TL.DR:
I see that komga fills sort number when get metadata from comicinfo.xml but i dont know if only uses number tag from xml, or uses another tag, o ther is one particular tag that i could use to fill this metadata field

Some context:

Hello, I'm making a script in python that basically makes cbz files from folders with images, names the cbz and move the cbz to another folder, and this folder is scan by komga. 
I made this script because I started to download with an emulator Comics and Mangas with Tachiyomi

But I also have in my komga library, mostly comics that i downloaded from another sources and already have comicinfo,xml with numeration and another info. So i'm mixing cbr and cbz, some with comicinfo.xml some of then without it, because of that some librarys are a mesh, and for exmaple I have this library about batman (2016) which still growing and already have more than 100 issues.

I'm a busy person and in part I'm making the script to try to automate the download process and use this time in read instead, so i dont have the time to change manually all the metadata from the 100 issues of batman, and i want to be sure that future downloaded number are going to be well sorted

Reading another issues in this github, and check the automatic metainfo that gathers Komga and the information from comicinfo.xml i think that something that might help me its to create my own comicinfo.xml with data like series, volume, publisher, and most important issue number, I almost have this done because in the script with the renaming I'm parsing the issue number from the original name downloaded from tachiyomi.

I see that komga fills sort number when get metadata from comicinfo.xml but i dont know if only uses number tag from xml, or uses another tag, or there is one particular tag that i could use to fill this metadata field

**Comment by gotson** [comment]
All the info is in the documentation.

**Comment by gotson** [comment]
It's not recommended to create your own comicinfo.xml, use proper tools like comic tagger or mylar for automation, especially for comics which have Comic Vine has datasource.
