### ISSUE TITLE
[Feature Request] Way to change default port for DOCKER

### ISSUE THREAD

**Issue by golserma** [gotson/komga#315]
Is there a way to change the default port for the docker image? I'm using docker-compose

**Comment by whalehub** [comment]
@golserma You can control the default port via the `SERVER_PORT` environment variable, e.g. `SERVER_PORT=8080`.

**Comment by whalehub** [comment]
You can control the default port via the `SERVER_PORT` environment variable, e.g. `SERVER_PORT=8080`.

**Comment by gotson** [comment]
Read the documentation.
