### ISSUE TITLE
[Bug] Series name taken from issues within folder, instead of folder name

### ISSUE THREAD

**Issue by claym** [gotson/komga#316]
### Komga environment
- **OS**: Ubuntu 18.04.5 LTS
- **Komga version**: v0.62.2-master
- [X ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
The media scanner seems to determine the comic series name by picking a file from within a folder, ignoring the name of the folder.

This means if you're putting multiple titles within a story arc folder, or a weekly release folder, it won't use the assigned name of the folder - for instance, "Empyre Saga" or "2020-36". Instead it will use the name of an issue within that folder - which means if there's duplicate items (you might actually have the issue in it's own series folder, as well as your story arc or weekly folder) you'll end up with multiple series with the same name.

**Comment by gotson** [comment]
This is not a bug, it's by design.

You can disable metadata import for series in your library option. 

Komga's directory folder is to be one series per folder. For story arcs you can use read list feature.
