### ISSUE TITLE
Ability to start Komga at system startup

### ISSUE THREAD

**Issue by SecretAgentAgentX** [gotson/komga#317]
I'm not finding any way to have Komga start at systen startup, or am I finding any command that I can enter into Konsole to start it's service and allow me to close Konsole without ending the Komga session.

EndeavourOS - Arch based - with KDE Plasma desktop

**Comment by grim7reaper** [comment]
If your OS is Arch-based, you can install [the AUR package](https://aur.archlinux.org/packages/komga/): it comes with a systemd service.

**Comment by SecretAgentAgentX** [comment]
I opened your link and the link in my software manager and they are the same, so what I have installed is the one you linked to. It does not stay running when the terminal is closed, and I actually get asked if I want to close terminal.

**Comment by grim7reaper** [comment]
You need to start the systemd service, not komga directly, i.e. use `systemctl start komga.service` to start it.
And if you want komga to be started automatically at startup, then use `systemctl enable komga.service` (only need to do this once).

Configuration is located in `/etc/komga.conf`.

**Comment by SecretAgentAgentX** [comment]
Thanks very much. I could not find those. Much appreciated

**Comment by gotson** [comment]
Komga is like any other application, it depends on your os. Ask on stackoverflow.com.
