### ISSUE TITLE
[Feature Request] Order books by Release Date when browsing series

### ISSUE THREAD

**Issue by phatalx** [gotson/komga#318]
When reading comics from a shared universe (or different versions of a specific comic), it's difficult to figure out the correct order to read them is. This also applies to issues lists with unconventional numbering (some issues have numbers such as -1).

It would be great to have the possibility to order series, readlists and issue lists by release date.

The Series and Readlists release date would take the smallest issue release date within them.

**Comment by gotson** [comment]
Please follow the templates for feature requests. 

You can use the number sort in book metadata to order issues with unconventional numbering.

Series do not have a release date, so how do you want to order them by release date? 

Read lists are ordered by specific order, so not applicable. 

For books within a series, why not.

**Comment by phatalx** [comment]
Yeah, sorry. I used the template for feature requests but removed the title.

So the idea would be to deal with it the way plex orders tv series by airing date. It uses the smallest air date for all episodes of a series.

**Comment by gotson** [comment]
Small doesn't mean anything for a date. Can you clarify with an example?

**Comment by phatalx** [comment]
I meant small as in the earliest date.

Example:
The Amazing Spider-Man #-1, Date: July 01, 1997
The Amazing Spider-Man  #424, Date: June 01, 1997
The Amazing Spider-Man #425, Date: August 01, 1997

The ascending order by release date would go 424, -1 and 425. Then the series (The Amazing Spider-Man) would be attributed the earliest date: July 01, 1997 in the series page assuming those 3 issues are the only ones in the serie.

The release date order would be the most useful for readlists. Example: 
Readlist: Avengers/Defenders War
Avengers #115; Sept 30, 1973
Avengers #116; Oct 31, 1973 
Avengers #117; Nov 30, 1973 
Avengers #118; Dec 31, 1973 
Defenders #8; Sept 30, 1973
Defenders #9; Oct 31, 1973
Defenders #10; Nov 30, 1973
Defenders #11; Dec 31, 1973

They currently appear in the order above, following the convention: Series by alphabetical order > then by Issue number by alphabetical order. So you can see it would be really beneficial to order them through release date ascending.

Avengers #115; Sept 30, 1973
Defenders #8; Sept 30, 1973
Avengers #116; Oct 31, 1973 
Defenders #9; Oct 31, 1973
Avengers #117; Nov 30, 1973 
Defenders #10; Nov 30, 1973
Avengers #118; Dec 31, 1973 
Defenders #11; Dec 31, 1973

**Comment by gotson** [comment]
Readlists have specific ordering, you can reorder them manually in whatever order suits you. That way you can do complex ordering like cross-over story arcs.

For series I'm not sure using the earliest date of its books is the right way to do. For instance if you order series by descending release date, you would probably want to see first the ones with a book released recently.
