### ISSUE TITLE
[Feature Request] Set default reader settings for new users/loging

### ISSUE THREAD

**Issue by michpas** [gotson/komga#321]
### Is your feature request related to a problem? Please describe.
Preference Settings and sorting options are not remembered and cannot be set set default by admin.

When logging in, I would like to reader remember the preferences settings and sorting options of a user.

For example: Settings as: Gesture off/on; Page layout. or even sorting preferences (sort by date-added + number of items on page)
For example when a user makes setting change and than login via another browser/system, the systems are back to default.

I would also be nice to have the admin be able to set a default for these values (preferences and sorting order) for users to improve the experience.
For example, I would also like to ensure page layout is double page (no cover) on any new account.
This to make it easier for new users.

**Comment by gotson** [comment]
Those settings are very personal, and also depend on the device. Forcing double page would be meaningless for someone logging on a mobile for instance.
