### ISSUE TITLE
[Feature Request] Run custom script when importing new file

### ISSUE THREAD

**Issue by michpas** [gotson/komga#322]
### Is your feature request related to a problem? Please describe.
A functionality to start a custom script when a new book/comic is added.
There can be many use cases, but for me it's the fact that some pdf materials have the backcover as 1st page and I would like to run a script on importing that extracts the 2nd pdf page as the image for the book.  Building a bit on: 
pdfimages -f 2 -l 2 -j "/books/[name of file.pdf]" /books/   

### Describe the solution you'd like
A menu option where a script can be stored. This script is to start when Komga imports a new file to the library.

### Describe alternatives you've considered or other apps that can do what you want
Running this script in download engines; but this is much more complicated, due to sometimes many books in one-zip download.
Scheduling as a cron-job, but cron is not available in docker and is not as efficient.

**Comment by gotson** [comment]
I have mo interest in adding such features, this is a very niche feature.
If your files have issues, you need to fix it outside komga.

**Comment by michpas** [comment]
Ok. Thanks for considering.
Sharing my solution, with the people whom have the similar challenge that certain PDF's need a cover image that is the 2nd page of the PDF and not the first.
Below is how I solved it.

Create a post-processing script in the download program (SABNZBD in my case)
Install pdfimages (apt install) in the download (docker)

This script called : create_image_from_2nd_pdf_page.sh
and pieces of the titles of the PDF files in the string; for these it will generate .jpg files of the 2nd pdf page; which will be stored besides the pdf file. Komga will pick this up as images.

Hope this is helpful to others as well.


SCRIPT:

#!/bin/bash

declare -a StringArray=("CarWeek" "Nautique")

 find /media/books_and_magazines/Magazines/ -iname "*pdf" | \
  while read I; do
   echo "$I"
   
if [ -f "/media/books_and_magazines/Magazines/$(basename -- "$I" .pdf).jpg" ]; then
    echo "$FILE exists. do nothing"
else 
    echo "$FILE does not exist. Creating jpg"

 # Iterate the string array using for loop
    for val in ${StringArray[@]}; do
      if [[ $I == *$val* ]]; then
           pdfimages -f 2 -l 2 -j "$I" "/media/books_and_magazines/Magazines/$(basename -- "$I" .pdf)"      
         mv "/media/books_and_magazines/Magazines/$(basename -- "$I" .pdf)-000.jpg" "/media/books_and_magazines/Magazines/$(basename -- "$I" .pdf).jpg"
      fi
        echo "not part of list"
     done
 fi
  done
