### ISSUE TITLE
[Feature Request] remember sorting order

### ISSUE THREAD

**Issue by michpas** [gotson/komga#323]
### Is your feature request related to a problem? Please describe.
When selecting sort by date-added and I go in/out of the library or application is defaults back to  sort by number.

### Describe the solution you'd like
It would be great if it remebers the sorting parameters, so when a user open the library it shows the last chosen sorting.
For example,the default sort by number for me is not so useful as it's kindof random. I do add new items, which I would prefer to always see at the top of the library. So my filter I would default set to date-added.

### Describe alternatives you've considered or other apps that can do what you want
There is none. Just to set the filter everytime the library opens.

**Comment by gotson** [comment]
The sort is saved in cookies already and restored when you go to the library.

Which version are you running?

**Comment by michpas** [comment]
I use the latest gotson-komga docker, which comes with the lastest git pull.

Note the website does remember settings as 'number of books' per page.

But it doesnt seem to remember the ordering preference of a library. Tried it out on browsers on various ( devices (chrome pc, android, ios). Behavior is all the same.

Maybe this helps?

**Comment by gotson** [comment]
It's working properly, see : http://imgur.com/a/U8ICchh

**Comment by michpas** [comment]
Hi Gotson
First of all. Great app !. I love the ease of use and the webserver including a viewer. 

and thanks for showing me what you ment in the video. 

I now understand better the the challenge.
I can indeed see that the 'top layer'of the library the sort is remembered. This is also the case on my version. 
But I also have 'collections/subfolders'under one library with many files in each.
These sublevels also have a sort icon on the top-right and you can select:  sort by date. This works perfectly.

But when you click back to the home screen or top-library; and later click again on the previous selected collection/sub-folder you will see the earlier selected sort is gone and it defaults back to 'the default'.

Maybe this is by design; but as these 'collections/subfolders' can be very large having the system remember the last sort (latest first is my preference :-) ) would be a great experience. Evertime when a 'collection is opened, the previous set sort is active'.

Thanks for the consideration,.

M

**Comment by gotson** [comment]
Please try to use the Komga concept wording for better understanding.

I think you are talking about series, and you also mentioned in the first post that the sort number is kinda random. 

I surmise that your folders do not contain only issues from a single series, but a bunch of issues from here and there. That's probably why your sort number is all wrong, especially if it's comics with a comicinfo.xml and you imported the metadata in the library. 

Komga is series oriented, so a folder should be a series. You shouldn't have a folder with all the comics from week 25 for instance, that won't work.

Komga doesn't remember the sort for each series, that's usually unnecessary as series are browsed by number. 

I suggest you reorder your files and folders to follow the recommended directory structure, and have one series per folder.
