### ISSUE TITLE
[Feature Request] Allow rich text formatting for summaries of books and series

### ISSUE THREAD

**Issue by rouhannb** [gotson/komga#324]
### Is your feature request related to a problem? Please describe.
It’d be nice to be able to more finely control how these summaries appear. ~~I’m personally asking this so I can distinguish between paragraph and line breaks, but~~ I’m sure that many people would like to be able to add bold/italic text, links, lists, tables (#184 would definitely benefit from this), etc.

### Describe the solution you'd like
Interpret the text in the summary field as formatted in some sort of way and convert it into HTML in the web app. Markdown is preferable because it’s human readable even when unformatted, so I can’t see how anything in the API or the metadata editor would break.

### Describe alternatives you've considered or other apps that can do what you want
[Calibre](https://calibre-ebook.com/) does this (although it uses HTML, not Markdown).

**Comment by gotson** [comment]
I don't quite understand what you mean by distinguish between paragraphs and line breaks, would you care to explain or provide an example?

#184 is different, right now it's storing metadata in unstructured text, the solution would be to take that out into specific fields.

**Comment by rouhannb** [comment]
Here is a line
break, and here is a paragraph

break. It’s the same as the difference between `<br>` and `<p>`. It’s not too important, but Markdown (and most other similar formats, as far as I know) makes the distinction. I personally want it so I can easily adjust the inter‐line and inter‐paragraph spacing.

Comparing this to #184 is a stretch, but it does exemplify how tables could be useful. A better example that wouldn’t normally be found in structured metadata is different artists working on different pages; it’d be useful to record which artist drew which page, but coming up with a structured format for something so uncommon, detailed, and specific would likely be a waste.

**Comment by gotson** [comment]
Line breaks and paragraphs are already working, see:

![Screenshot_20200913-153522](https://user-images.githubusercontent.com/2139133/93012956-ed398e00-f5d6-11ea-8b3e-10213dd265d0.jpg)

**Comment by rouhannb** [comment]
Sorry, I don’t think I was being clear enough.

First, as far as I know Komga does not represent line/paragraph breaks in the DOM, making them impossible to style.

More importantly, while line/paragraph breaks are the main reason I want this feature right now, I can see other, more general types of formatting being useful in the future for me, and I think that many other people would find them useful too. The point of this issue was to introduce formatted summaries in general; the line/paragraph breaks are a detail I added for context, and in retrospect that detail is not necessary.

**Comment by gotson** [comment]
I fail to understand your point, why do you want them in the dom?

**Comment by rouhannb** [comment]
We’re going off topic here. The point of this feature request is so people can use Markdown in the summary field. Ignore the other stuff about line and paragraph breaks, it’s not important.

**Comment by gotson** [comment]
You are going off topic 😅. The issue is talking about too much things and you are not detailed enough in what you want and keep changing your mind.

Rich text will not happen, the webui is one of the clients of the Komga API, but there are other clients like tachiyomi or opds readers. Adding rich formatting would force those clients to perform a rendering of that rich text, or be forced to show raw markdown or html which would be ugly.

Adding rich text without control is also proven to lots of side effects, and could lead to a variety of possible injections of code etc. That's why forums have bbcode and not pure html. 

Lastly, the metadata sources do not have that feature, and down the road the metadata should mostly come from external sources.
