### ISSUE TITLE
[Bug] ios gesture and zooming doesnt go well together

### ISSUE THREAD

**Issue by michpas** [gotson/komga#325]
### Komga environment
- **OS**:  ios 13.5.1
- **Komga version**: 
- [ ] **I am running Komga with Docker**
  - Docker image tag [latest,]:  gotson/komga
- [
- [ ] **I have a problem in the web interface**
  - Browser: safari latest and chrome latest
 
File: pdf

### Describe the bug
When gesture is on, zooming in on a page with fingers/pinch results in page swap. This makes zooming in impossible. 

### Steps to reproduce
1. Select pdf. Read.
 Have gesture on
Try to zoom in or out with fingers.
In allmost all case the page swaps to next or prev page

### Expected behavior
A zooming action with 2 fingers should never lead to a page turn.

### Actual behavior
Page swap

**Comment by gotson** [comment]
You can disable gestures in the webreader in you want to use the iOS zoom.

**Comment by michpas** [comment]
Thanks. Yes, that option works well.
It would be just a bit more easier for this usergroup of Ipad users if the gesture mode is by default turned off instead of on. I was initially trying to find out what I was doing wrong. Took some time to realize I needed to turn of gestures.

It's possible to detect the usage of an IPAD browser logging in; maybe this can be an user-experience enhancement?
https://davidwalsh.name/detect-ipad

Thanks for your consideration

**Comment by gotson** [comment]
Feature detection is never really working properly unfortunately.
