### ISSUE TITLE
[Feature Request] OPDS - Latest Issues

### ISSUE THREAD

**Issue by claym** [gotson/komga#327]
When I log into Komga through the web interface, the home page has a "Recently Added Books" section.

Could we get a "Recently Added Books" or "Latest Comics" in the OPDS feed?

Thank you!

**Comment by frameset** [comment]
Great idea, it would be good for new comic day reading.

**Comment by claym** [comment]
> Great idea, it would be good for new comic day reading.

exactly what i was thinking!

**Comment by barbequesauce** [comment]
This please!

**Comment by virtualadept** [comment]
Would love this feature
