### ISSUE TITLE
Older iOS Devices

### ISSUE THREAD

**Issue by MaestroJAL** [gotson/komga#328]
First of all, thanks for making this app. It is the best solution I've found for streaming educational PDFs to my classes. I'm an educator and have a classroom set of iPads gen 4. They're running iOS 10.3.3 (maximum OS). Safari shows only a blank page when accessing the Komga login page. I'm wondering if it may be SSL related? Just looking for some help. If I can get this working, this would greatly help me and my classes.

Thanks for your time!

**Comment by gotson** [comment]
Please use the templates provided next time.

Can you advise what's the version of Safari on those devices?

**Comment by MaestroJAL** [comment]
Sure! As far as I can tell, Safari on iOS 10.3.3 was version 603.2.4.

**Comment by gotson** [comment]
Are you able to install a more recent browser from the app store on those ipads, for example the latest Chrome, and test with that?

**Comment by lucasmenno** [comment]
I got the same problem, my iPad mini only loads a white page. I can see the favicon but nothing else.
