### ISSUE TITLE
[Feature Request] Make Book Metadata persistant & independant from library

### ISSUE THREAD

**Issue by sam5558** [gotson/komga#329]
### Is your feature request related to a problem? Please describe.

I'm using two "manga" libraries, one for ongoing mangas and the other for finished mangas. What i noticed is that the metadata i had disappeared after moving one manga from a library to another one.

### Describe the solution you'd like
I would like metadata to be only linked to the book name itself, so that a user doesn't loose all his metadata (and you know how much time it can take :D ) when moving a book from one library to another.

### Describe alternatives you've considered or other apps that can do what you want
I've considered having one library with all my content, which will solve the issue. But i believe it's interesting to have this flexibility on Komga. Can be useful for other cases.

### Additional context
R.A.S

**Comment by prysme01** [comment]
A sidecar file would be nice to store the metadata at the book and the serie level.

**Comment by grim7reaper** [comment]
> metadata to be only linked to the book name itself

Book names are not unique, so we couldn't use that.

For instance, there are two (and maybe more…) manga adaptation of "No Longer Human" from Osamu Dazai (one by [Junji Ito](https://www.viz.com/read/manga/no-longer-human/product/6126), and another one by [Usamaru Furuya](http://www.vertical-inc.com/books/archive/nolongerhuman.html)).

---

I've had the case where I wanted to move a book or series on disk without losing the metadata: for now I have a script to export the metadata into JSON files and then reinject them.

Not sure if this could be made simpler.

**Comment by gotson** [comment]
Closing this as it's covered by #217 for your specific use case, and by #82 more generally.

**Comment by sam5558** [comment]
@grim7reaper I think it's possible to use a unique ID, like the series ID
![image](https://user-images.githubusercontent.com/26897744/93578128-d909de00-f994-11ea-9ed1-e5b84fde6e75.png)
