### ISSUE TITLE
After initial scan of rclone Google Drive mount, library is missing many chapters and metadata

### ISSUE THREAD

**Issue by gryphonmyers** [gotson/komga#330]
### Komga environment
- **OS**: Ubuntu 18.04
- **Komga version**: 0.62.6
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: 11.0.8
- [x] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
After setting up server and allowing first scan to run, series are picked up but very few chapters are found, and no covers or metadata are discovered. 

### Steps to reproduce
1. Install Komga
2. Add library pointing at directory in rclone Google Drive mount (using expected file structure of {Series}/{Chapter}.cbz).

### Expected behavior
Folders with cbz files in them should be discovered as series with chapters for each file, and found cbz files should be readable with metadata.

### Actual behavior
Some found chapters have file sizes, but according to the web interface have "0 pages." The files (cbz) can be downloaded using the interface, but the browser reading feature is greyed out. Under format it has a question mark. There are no covers for any chapters or series whatsoever.

### Additional context
Manually running analyze and / or refresh metadata on individual series or chapters doesn't seem to do anything. Nothing obvious showing up in the logs. Configuration is:
```
komga:
  libraries-scan-cron: "0 0 6,19 * * ?"
  database-backup:
    path: ~/.komga/database-backup.zip
    schedule: "0 0 7,20 * * ?"
    enabled: true
    startup: true
```

**Comment by gotson** [comment]
Did you wait enough time for the analysis to run? The initial analysis can take many hours depending on the number of files you have.

You need to tail the logs to ensure it has finished running. 

You also need to setup rclone properly and enable the force modified time as explained in the [documentation](https://komga.org/faq/#can-i-use-komga-with-a-google-drive-mount).

**Comment by gryphonmyers** [comment]
Well it's been a few days and I hadn't noticed any observable change, but maybe I do just need to wait longer. 

Have you considered adding support for importing directly from a ComicRack xml file? Then you might not need to go through such a time-consuming and resource intensive scanner process

**Comment by gotson** [comment]
The comicinfo.xml is already supported and imported as metadata.

**Comment by gotson** [comment]
Read the doc to understand what happens during a scan, and what follows : https://komga.org/guides/scan-analysis-refresh.html

**Comment by gryphonmyers** [comment]
I understand that. I actually meant ComicDb.xml - the file containing information about all comics in your library. Hypothetically you wouldn't really need a scanner process to attain metadata if you had this file available.

**Comment by gotson** [comment]
Never head of that file, but it wouldn't bring anything regarding the analysis time. Komga cannot trust external information about files, as such it needs to verify the format of the file itself, but also of all the images contained (in case of an archive), as well as check each image for dimensions.

The scan itself is usually fast, the analysis and thumbnail generation takes more time. Metadata refresh is also usually fast. 

I would suggest you try with a subset of your files, first locally, then with rclone.

**Comment by gryphonmyers** [comment]
> Never head of that file
It's typically in User/AppData/Roaming/cYo/ComicRack - have a look!

> Komga cannot trust external information about files
For analysis, I get that - the db doesn't have information about the archive contents anyway. But I don't understand how metadata refresh could be fast and reliably up to date if we're talking about hundreds, possibly thousands of text files stored inside of archive files (and in my case on a network drive). As an alternative, the user could, at their discretion, opt to source metadata from a (in my case) trusted database file rather than bothering with all the file access. And if metadata changes in your library, getting that information again would be cheap - just rescan the db file, as opposed to the relatively intensive task of going out and peering into archive files again.

Additionally, how critical is it that the server perform comprehensive analysis of all files in advance and / or regularly? Have you considered a "lazy analysis" setting where it would perform these actions once the archive was opened for reading?

**Comment by gotson** [comment]
I never used ComicRack and never will, I don't own a windows machine and the software is long dead anyway.

If you're so attached to your trusted database, you might want to stay on ComicRack. 

Komga does not aim to provide integration with whatever people want to do or believe is right to do. It's modeled around how Plex works, and requires to perform its own analysis of files to be able to serve them in a consistent way. 

Analysis is critical, without analysis it's impossible to know that the file is a proper comic book archive, epub, or pdf file. It's also impossible to know in advance how many pages are in the book without analysis. Analysis is performed when a file is added or modified, and on demand. It's a usually a one time thing.

Unless you can provide proper logs of an error behavior, I'll close this issue. And I would recommend again to start with a small set of local files so that you get acquainted with how Komga works, then properly setup your rclone mount according to the doc to get good performances.

**Comment by gryphonmyers** [comment]
> If you're so attached to your trusted database, you might want to stay on ComicRack.

No offense is intended - I'm just trying to help you improve your software. If you're not open to feature suggestions I'd at least suggest providing feedback to the user as to the status of running scanner jobs. But you know, this is your thing so do whatever you want I guess.

**Comment by gotson** [comment]
I'm open to features that have an interest for the majority, but you don't seem inclined to either read the doc or trust what the developer is telling you.
