### ISSUE TITLE
[Feature Request] Publisher view in ODPS catalogue

### ISSUE THREAD

**Issue by jt196** [gotson/komga#332]
### Is your feature request related to a problem? Please describe.
It's not possible to see publishers in the ODPS view

### Describe the solution you'd like
A publisher view in the ODPS catalogue

### Describe alternatives you've considered or other apps that can do what you want
n/a

### Additional context
n/a

**Comment by gotson** [comment]
What kind of navigation do you expect in the opds feed?

Root > By publishers > list of all publishers > series?

**Comment by gotson** [comment]
> It's not possible to see publishers in the ODPS view

This is very different from what you request. Seeing publishers would mean that from a series you could see its publishers. 

Navigating by publisher is what you actually seem to request.

**Comment by jt196** [comment]
> Root > By publishers > list of all publishers > series?

Apologies if my request wasn't specific enough. This is what I meant. 

I assumed as this is the way the filter by publisher in the web view works, this would be clear. 

As the data is all there, it would be nice to browse through say all Marvel, DC, Image, Vertigo stuff in my collection on my mobile device.

**Comment by jt196** [comment]
Great you got it in the latest release! 

FYI @gotson this is broken on Chunky comic reader for iOS. I can enter the list of publishers, but if I enter into a publisher, the app crashes.

**Comment by jt196** [comment]
The other new additions work btw.

**Comment by gotson** [comment]
> Great you got it in the latest release!
> 
> FYI @gotson this is broken on Chunky comic reader for iOS. I can enter the list of publishers, but if I enter into a publisher, the app crashes.

I tried with Librera on Android and it works fine. 

Try to get some logs and open a new issue.

**Comment by gotson** [comment]
Other users confirmed Chunky is working well for publishers, so it's probably just you!

**Comment by jt196** [comment]
Gonna see if I can dig the logs out, and I'll make sure it's restarted/updated etc.

**Comment by jt196** [comment]
@gotson it's still happening. Weirdly, not on every publisher, which may be why some of your colleagues are showing working configuration. Up to date Chunky running on an iPad with 13.5.1 iOS version on it. 

Quick question, do you know what to do with IPS crash logs on iOS? I think you need XCode to view them as they're binary files. If you already have the capability to open them, I'll post them here, if not I'll need to figure out how to de-binary them/install Xcode. 

Do you know if they contain sensitive data - if yes, I'll pm them if you don't mind. 

If this is enough to figure it out, I'll leave it at posting the logs, if more debugging needs to be done, I'll start a new issue.

**Comment by gotson** [comment]
I have zero knowledge with iOS and its crash logs, you would have better luck with the chunky dev.

What you can do is send me the xml of the opds publisher section that make chunky crash, I can try to spot some weird characters or try to make it go through the opds validator. 

Please open a new issue.

**Comment by jt196** [comment]
@gotson where might I find that?

**Comment by gotson** [comment]
The opds feed can be navigated from any browser, just go to `/opds/v1.2/publishers` then find the publisher that's causing problem and follow that link. The browser will display the xml, which you can check for sensitive information and post either here or send to me directly via discord PM.

**Comment by jt196** [comment]
OK figured it out - it's the publishers with spaces in the titles. Marvel works, Avatar Press doesn't.

Here's the entry: 

<entry>
<title>Avatar Press</title>
<updated>2020-09-29T09:32:14.554965+01:00</updated>
<id>publisher:Avatar Press</id>
<content/>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="/opds/v1.2/series?publisher=Avatar Press"/>
</entry>

**Comment by jt196** [comment]
OK opened this up as [issue 335](https://github.com/gotson/komga/issues/335).
