### ISSUE TITLE
[Bug] Multiple series in folder defaults to random series title 

### ISSUE THREAD

**Issue by jt196** [gotson/komga#333]
### Komga environment
- **OS**: Linux/Synology
- **Komga version**: 0.6.26
- [x] **I am running Komga with Docker**
latest docker image

- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome/Edge

### Describe the bug
In the manual the folder structure is described thus:

Komga will create a Series for each subfolder of any library, whatever the depth of this subfolder in your directory structure
Komga will create a Book for each file found, and **place it inside the Series corresponding to the parent folder of the file**
#

While the first runs true, when a book is in a folder with multiple series, Komga chooses one of the series of the books in the folder (rather than the folder name) to show the series in the main view. 

e.g. I have a structure:

- Author1 (folder)
   - book1 - series1.cbr
   - book2 - series2.cbr
   - book3 - series3.cbr

As the manual is currently, I'd expect the series these books to belong to would be 'Author1', however, it shows up as 'series2' - or 'series3', I don't see any logic to the naming, it's just one of the series tags of the books inside the folder. 

This would be for example, a folder containing a series of one-shots or books by the same author. The alternative to this is making folders for each book in the folder so they show up as individual series on the library view.

### Steps to reproduce
Create a folder and add books with different series tags. 

### Expected behavior
either:
a) Komga to separate books inside folders containing multiple series into different series. Folders containing the same series as current behaviour.
or
b) Folders with different series in root to form a series with the same name as the parent folder - 

I'd assume as currently, this rule would only apply to files inside the top level of the folder, not subfolders.

I realise everybody has different folder structures, but either of these would allow the user to have a bit more control over series display in Komga without having to spend time sorting one-shots/tpbs into individual folders. 

### Actual behavior
Books inside folders containing different series have a random series name based on one of the books inside the folder.

**Comment by gotson** [comment]
You probably have metadata in those books that are imported and change the series name.

- Try with a library that does not import metadata.
- check the comicinfo.xml file in your archives 
- provide logs when you raise a bug

**Comment by jt196** [comment]
All of the files are tagged properly with comicinfo.xml files. I've observed this behaviour in multiple folders in my library. The issue is that when files in the root of a folder have multiple series in the metadata, Komga chooses a random one of them as the series. 

Just tested this with a library that doesn't import metadata and the parent folder is named after the actual folder. So this is Komga behaviour. It's reading the series of the books in a folder and choosing one of them at random for the parent series.

So currently I have several options to avoid this:

1. I put books in separate folders if I want them displayed as separate series. 
e.g. 
Author1dir
   Book1dir
      Book1.cbr
   Book2dir
      Book2.cbr
2. I add certain folders to a different library that doesn't scan in the metadata. 

I'm not such a fan of option 2 as it means that I can't scan the metadata into the library. Maybe something like my b) suggestion above would be a good compromise? A consistent series tag would result in Komga choosing that, in case of different series tags, a different behaviour would choose how the series names are chosen for files in a folder. 

Re logs, I'm not sure exactly how they're going to help here as this is more of a functional issue than a program bug. 

Hope this makes sense.

**Comment by gotson** [comment]
It's the expected behavior, the most frequent series found in the books metadata will be used to override the series title ([doc](https://komga.org/guides/scan-analysis-refresh.html#series-metadata)).

If you want to stick to a non recommended directory pattern, then you can manually edit the series metadata, update the title, and lock it. That way it won't change the next time you add a book in that folder.
