### ISSUE TITLE
[Bug] Fatal crash in Chunky when entering publisher with space in name

### ISSUE THREAD

**Issue by jt196** [gotson/komga#335]
### Komga environment
- **OS**: Docker
- **Komga version**: latest (0.63)
- [x] **I am running Komga with Docker** 
- [x] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
Chunky iOS (up to date)

### Describe the bug
Opening the publisher menu via ODPS crashes when there's a space in the publisher name

### Steps to reproduce
1. Go to Chunky
2. Open Komga ODPS catalogue
3. Go to Publishers
4. Go to a name with a space in e.g. "Avatar Press"
5. App fatal crash

### Expected behavior
Entry to list of series under publisher 

### Actual behavior
Fatal crash

**Comment by jt196** [comment]
```
<entry>
<title>Avatar Press</title>
<updated>2020-09-29T09:32:14.554965+01:00</updated>
<id>publisher:Avatar Press</id>
<content/>
<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="/opds/v1.2/series?publisher=Avatar Press"/>
</entry> 
```

Here's a fatal ODPS entry. Most likely `publisher=Avatar Press"` section causing the issue.

**Comment by gotson** [comment]
Thanks for the report and investigation. Other opds readers don't have the problem, but I'll try to url encode the parameter and see if that works better.

**Comment by jt196** [comment]
Bravo!

**Comment by jt196** [comment]
Can confirm that's fixed it.
