### ISSUE TITLE
[Bug] Empty read lists (deleted content) still appear 

### ISSUE THREAD

**Issue by jt196** [gotson/komga#336]
### Komga environment
- **OS**: Linux
- **Komga version**: latest
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
After deleting various comics, the read lists (autogenerated from tags) are still present on the read list page/add to read list menu. Haven't tested this with manual read list addition. 

### Steps to reproduce
1. Add books with AltSeries tags
2. Check they've been added as read lists
3. Delete books from hard drive
4. Check read list page

### Expected behavior
Removing books from library removes empty read lists. 

### Actual behavior
Read lists are not removed. 

### Screenshots

![Screenshot 2020-09-29 at 13 15 17](https://user-images.githubusercontent.com/8290163/94557342-574c6700-0256-11eb-956f-d1ab7e8ecec0.png)

**Comment by gotson** [comment]
This is a normal behavior, modeled over Plex collection behavior.

You may have customized your collection title, and even though you removed some content, you may want to add more content later on.

**Comment by jt196** [comment]
So maybe some sort of batch deletion?  Manual deletion of 140 or so empty playlists after a big library cull, at 4 clicks per read list is gonna leave my mouse finger a mite sore.

**Comment by gotson** [comment]
There's an api, you can script your own solution for those kind of corner cases.

**Comment by gotson** [comment]
What could probably help would be a muliselect for deletion on collection and readlists. You can create a feature request for that if you want and if you think it would help you.

**Comment by jt196** [comment]
So until @gotson adds the multiselect to the code, I made a script to delete any empty readlists:

https://github.com/jt196/komga_delete_readlists

As with any batch deleting process, be careful with this, might be worth running on a test installation first. This is tested and working on my instance though.

**Comment by jt196** [comment]
Opened the multi select as a feature request [337](https://github.com/gotson/komga/issues/337).
