### ISSUE TITLE
[Feature Request] Option to configure the default pagination number for the server and/or the user

### ISSUE THREAD

**Issue by Krylanc3lo** [gotson/komga#338]
### Is your feature request related to a problem? Please describe.
It is not a problem whatsoever but it could be nice to be able to configure the default paginatiion and change the current one (20 volumes per page)

### Describe the solution you'd like
Either an option in the application.yml file (for the default server value) or an option in the setting page for the user

**Comment by gotson** [comment]
You can change the pagination via the ui, it is persisted per user per device via cookies.

Having a default per user is not advisable, as pagination depends on the kind of device used. You probably don't want the same pagination on your phone and on your desktop.

20 is a good sensible default for all users and devices, thus I'm not willing to develop something to change the default.

**Comment by Krylanc3lo** [comment]
ok thanks a lot for the quick feedback and the tips :)
