### ISSUE TITLE
[Feature Request] Add the ability to use authors information for filter/group/list

### ISSUE THREAD

**Issue by thampp** [gotson/komga#339]
### Is your feature request related to a problem? Please describe.
I have authors metadata (writer, penciller etc.) available in most of my comics. And sometimes I would like to so search or browse by that information. But it looks like in the current version of Komga this information is not actionable within the Komga UI.

### Describe the solution you'd like
The ability to search for authors information would be a start. But the results would have to work like the full text search on top which shows hits across the whole library and on the result level of books (as opposed to series, collections or reading lists). Given the current behaviour it would not help just adding authors to the filter drop down on the left since that only filters on the level of series (or is restricted to filter within a series).

### Describe alternatives you've considered or other apps that can do what you want
An alternative solution for the search use case would be smart "playlists" (read lists) as discussed in other feature requests. 
That would require to manually define a smart read list for each author search. That is acceptable, but a likely a bit of a a setup overhead.

The browsing / grouping use case is a bit different. It would require to show an auto-grouped view by writer, inker, ... Chunky reader which I use on iOS does. But the results need to show more compact than Chunky does them as there will be many results. It could be like read lists: one icon per distinct author, with multiple results per row.

**Comment by gotson** [comment]
I want to add filtering at series level on authors, but for that I need to aggregate the books individual information at series level (that's part of #181).

The search is yet another piece of work, and would require to search by authors first (everything is available to do that already), then display a new search result page for a single author, showing all of his series and books.

**Comment by thampp** [comment]
Sounds good. 
I assume the aggregation of authors information at the collection level would be a bit different from the current logic for attributes like publisher etc. which are single valued: Authors is already a multi-valued field and I would assume the value at the collection level would just be the union of all the values from all books/comics in the collection. That would be best for search as no author is missed. But it can be a lot of values in a collection then.

For me the search is a feature that would also provide value because for individual Graphic Novels that are lumped together in a collection it's more about seeing all individual books/comics of a specific author, not about identifying the collections they are in.

In any case let me say how much I appreciate the work you are putting into this. Komga has a great set of functionality and user experience already.

**Comment by gotson** [comment]
Multiple graphic novels into a generic collection is not a supported pattern. The best way to represent them is to move them to a series of their own, containing a single book.
