### ISSUE TITLE
Request:  Group by Publisher

### ISSUE THREAD

**Issue by DarkSir23** [gotson/komga#34]
Just got my library scanned, and I like the layout.  I'm going to check the OPDS feed out shortly, but I am looking forward to seeing the web reader.

I noticed you mentioned Collections as a work in progress, but I'd also like to suggest that you make it possible to group by publisher, both for browsing on the web and as an opds category.

I was also wondering, I'm using the docker installation.  Are the thumbnails being stored in the database directly, or are they being saved as a file somewhere?

**Comment by gotson** [comment]
Hello, glad you like the layout, I tried my best at material design, even though that's not my strong point! 

About grouping by publishers, we would need the publisher information first. As part of #11 I plan to get metadata from somewhere, but it's not gonna be an easy one. 

If you already have your comics organized by publisher, for example in your directory structure, then indeed Collections could be a good candidate. Once we have collections it will be at first a manual action to add a series in a collection, so you could create one collection by publisher. I am also thinking of providing UI cues to more easily add collections, but nothing started yet. Your input is welcome! 

The thumbnails are stored in the H2 database directly (`/config/database.h2` by default in the docker image I provide).

**Comment by gotson** [comment]
Could you share a bit more information about your current setup, like how those publishers are managed for now?

**Comment by DarkSir23** [comment]
Currently the publisher information is saved in ComicInfo.xml, as well as being the parent folder of the series.  So /comics/Marvel/Deadpool (2016) -- For example.

**Comment by gotson** [comment]
> Currently the publisher information is saved in ComicInfo.xml, as well as being the parent folder of the series. So /comics/Marvel/Deadpool (2016) -- For example.

I am working on something to import `ComicInfo.xml`, so you should have the information, then I'll add some filtering capabilities to filter by metadata fields, so by publisher if you want to.

For the comics without the correct `ComicInfo.xml` you will have to edit the metadata manually.

That should be sufficient, you can keep the directory structure as it is, but the information from the directory will not be used. 

However since everything is available by API it would be quite easy to implement a small script that would look at all the books, get the publisher from the file path, and set the metadata.

**Comment by DarkSir23** [comment]
Nice.  Thanks.

**Comment by hubbcaps** [comment]
A temp solution for this might be to allow adding children of an upper directory as a new library?

I added my whole collection, but then when attempting to add a "new library" with the name of the publisher pointed at the publisher folder it complained that the publisher folder was a child of an existing library.

Might be redundant once collections come, but would be a good half measure.

**Comment by gotson** [comment]
That would cause lots of issues, because of duplicates, as the full path of files is used to update series and books at rescan.

**Comment by gotson** [comment]
@DarkSir23 we now have Publisher available in the metadata, however i am not sure how to offer this criteria for navigation.

Plex uses a criteria menu with sub-menus:
<img width="228" alt="Screenshot 2020-03-17 at 16 25 03" src="https://user-images.githubusercontent.com/2139133/76836574-018d1000-686c-11ea-8e82-db5bd84d271a.png">
<img width="232" alt="Screenshot 2020-03-17 at 16 25 12" src="https://user-images.githubusercontent.com/2139133/76836579-03ef6a00-686c-11ea-9b78-93c06d93c2e5.png">

However Vuetify doesn't support that yet :(

**Comment by DarkSir23** [comment]
For me, the two main places I'd like to see it as an option are in OPdS feeds (scrolling through hundreds of titles to get to the Ts every time I want to add a folder is fun :) ), and in the web interface.

**Comment by gotson** [comment]
At which level in the opds feed? Since the structure is kind of hierarchical I can either set it somewhere, like at the root for libraries, or I need to build some kind of criteria filtering system that can apply to any opds location.

For the webui without nested menus I will need to find another way.

**Comment by gotson** [comment]
@DarkSir23 quick question on Publishers and Imprints. How do you categorize Imprints like Vertigo, which is part of DC?

**Comment by flips22** [comment]
If you look at comiXology they have Vertigo under DC.
https://www.comixology.com/DC/comics-publisher/1-0?ref=YnJvd3NlL3B1Ymxpc2hlci9kZXNrdG9wL2xpc3QvRmVhdHVyZWRQdWJsaXNoZXJMaXN0

My opinion would be to keep them separate as I would be more likely to associate a Vertigo title to Vertigo, not to DC.

I'm a old Comic Rack user, and I follow the "The Organizer" process detailed here:
https://www.reddit.com/r/comicrackusers/comments/e0l28i/documents_and_scripts/

It uses data manager which will create a series group i.e. DC/Gotham CIty/Batman or Marve/Spider-Man/ Main Series/The Amazing Spider-Man (1963) I would say I don't do a real good job with the format so I have a mess of a bunch of smaller series at the same level as the Main Series separator. At some point I could set up a rule that a series with more than X is a main series and less than X is a limited series, or that could be part of what komga does.

It doesn't look like comiXology has this figured out yet either, as you go to Marvel there are 90 pages (3,238 series) to scroll through. :)  Comicvine is also rough to browse as I've never found a way to go from series to series (i.e. V1 to V2, to V3) other than in the text of the wiki entry.  But to no fault of comicvine its seldom black, as a series changes its name.  For example Green Lantern goes to Hal Jordan and the Green Lantern Corps and then to Green Lanterns and The Green Lantern.  Here's the text from the Hal Jordan series:
Preceded by Green Lantern Volume 5. Coincides with The Green Lanterns Volume 1. Both series were replaced by The Green Lantern Volume 1 when they ended.
Huh?  This is why I just organize by year of the series start (v2005) as that is a little more clear cut and you can kind of get the flow from one series to the next.

Another nice feature would be to link to comicvine based off the CVDB number in the .xml, so you can easily sort that all out outside of Komga.

Plex is a one example. I'm looking at kodi right now that they sort movies by:
Genre, Title, Year, Actors, Directors,Studios, Sets, Countries, Tags and Recently Added. I've only really every used Year and Recently Added and title, and title you can easily skip to a letter, so it's pretty quick to scroll through a lot of titles.

Keep up the great work, this product really in a good spot.

**Comment by gotson** [comment]
This needs work on #181 first to aggregate data per series
