### ISSUE TITLE
[Feature Request] Add option for volume in the title of each series

### ISSUE THREAD

**Issue by dankles** [gotson/komga#343]
A series like "Batman" will have that series name for multiple volumes. 
* Example: [Batman, volume 2 issue #1](https://dc.fandom.com/wiki/Batman_Vol_2_1) and [Batman, volume 3 issue #1](https://dc.fandom.com/wiki/Batman_Vol_3_1)

The "series" for both of those is "Batman", so the only way to distinguish them is to separate by volume. 

In the ComicRack metadata exists a volume tag, which is usually the start year of a given volume. So an option to add that tag as part of a title would help distinguish what look like duplicate series. "Batman" "Batman" "Batman" might become "Batman (1940)" "Batman (2011)" "Batman (2016)".

I can think of at least two ways to implement this:
1. Add a check box to add volume to the series title
2. Add a text field where a user would enter some sort of template string like "%series% (%volume%)"

**Comment by gotson** [comment]
I don't think any of those 2 options will provide a sensible default, and adding configuration like you propose will clutter the UI for not much added value.

I propose to always set the volume in brackets if it's available, so "Batman (2011)".

What do you think?

**Comment by dlsmif** [comment]
I think gotson's suggestion is the better option. If it's there display it.

**Comment by dankles** [comment]
That sounds fine.
