### ISSUE TITLE
All Series have a (1) appended to their titles.

### ISSUE THREAD

**Issue by silentArtifact** [gotson/komga#347]
### Komga environment
- **OS**: Synology DSM
- **Komga version**: 
- [X] **I am running Komga with Docker**
  - Docker image tag: latest

### Describe the bug
Any new series has an (1) appended to the end of its title, as well as the sorting title.

### Steps to reproduce
1. Create a library, or add a series to an existing library

### Expected behavior
Have just the series title displayed.

### Actual behavior
Any new series has an (1) appended to the end of its title, as well as the sorting title.

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/11065620/97473277-cf22b580-1918-11eb-9ab5-44ad4e578804.png)

**Comment by gotson** [comment]
It's the volume number, you probably have comics with a comicinfo.xml inside, containing the volume name.

See #343

**Comment by gotson** [comment]
Just thought more about this, I think we could safely ignore the volume if it's 1 when refreshing metadata.

I'll try to cook up a fix.

**Comment by gotson** [comment]
You should be able to get rid of the `(1)` by refreshing metadata with the version including the fix.

**Comment by silentArtifact** [comment]
Holy cow, thanks for this!

**Comment by verbumfeit** [comment]
Sorry to barge in like that, but could you add a 'Vol.' in front of the number, like: Action Comics (Vol. 5)?

**Comment by gotson** [comment]
> Sorry to barge in like that, but could you add a 'Vol.' in front of the number, like: Action Comics (Vol. 5)?

Please don't comment on closed issues.
