### ISSUE TITLE
[Bug] custom thumbnails for series

### ISSUE THREAD

**Issue by kimhomo** [gotson/komga#351]
### Komga environment
- **OS**: synology OS
- **Komga version**: 0.64.3
- [O] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest 0.64.3

I put the .webp file for thumbnail in the Series folder, but it doesn't apply.

thanks for being so helpful.

**Comment by gotson** [comment]
Webp are not a valid format for custom covers. Check the documentation.
