### ISSUE TITLE
To add in documentation (nginx reverse proxy and systemd service file)

### ISSUE THREAD

**Issue by cabusar** [gotson/komga#353]
Hi,

First a huge thank for Komga, it's really an amazing tool, it handle a 350GB directory with 7000+ comics without any problem.

I suggest you add two little things in the documentation.

-----------------------

First thing : How to reverse proxy when using the "jar" version with nginx : 

Let say you have a working install exposed on port 8080 (default) but you want SSL on another port, like https://your_server:8443, here is a working nginx config

    location /komga/ {

      proxy_set_header   Host $host;
      proxy_pass          http://your_server_url:8080;
      proxy_http_version 1.1;

    }

But it need one thing that is not really documented and that i have to find by trying and guessing : 

You have to launch the jar with an option to change the base url for matching this common reverse configuration : 

java -jar -Xmx4g komga-latest.jar **--server.servlet.context-path="/komga/"**

And this is the point, i didn't find this information and had to guess it after a long time trying to rewrite url (yes i'm that stupid ^^') and googling things.

So, my 2 cents, add a little line explaining that it's possible to specify this as an option when lauching the jar, here : https://komga.org/installation/configuration.html#optional-configuration

--------------------
Thing 2 : 

Here is the service file for systemd that i use, it may help some user.

```
[Unit]
Description=Komga server

[Service]
WorkingDirectory=/path_to_komga_jar/
ExecStart=/path_to_java/java -jar -Xmx4g komga-latest.jar --server.servlet.context-path="/komga/"
User=komga
Type=simple
Restart=on-failure
RestartSec=10
StandardOutput=null
StandardError=syslog
[Install]
WantedBy=multi-user.target
```

So, my path to a full working komga server on Debian9 (but nothing really specific) : 

```
apt update && apt upgrade
apt install default-jre
readlink -f $(which java) -> to find the directory where java binary is on your system
cd /opt/komga/ -> working directory
wget https://github.com/gotson/komga/releases/download/v0.64.4/komga-0.64.4.jar
mv komga-0.64.4.jar komga-latest.jar
groupadd -r appmgr
useradd -r -s /bin/false -g appmgr komga
chown -R komga:appmgr /opt/komga/
nano /etc/systemd/system/komga-server.service -> add and adapt the lines above
systemctl daemon-reload
systemctl start komga-server.service
systemctl enable komga-server -> for starting when the server boot
```

I don't know if you want to document distribution specific install, but at least it will leave a mark on github and maybe help others. :)

Have a nice day and keep up the good job. ;)

**Comment by mihailim** [comment]
Here's a more locked-down (but more complicated) systemd unit.

```
[Unit]
Description=Komga server
After=network.target

[Service]
User=komga      # Set homedir to /PATH/TO/KOMGA/DBDIR (e.g. /var/lib/komga)
Group=komga     # and don't forget to chown to komga:komga and chmod to 0750
Type=simple
RuntimeDirectory=komga
RuntimeDirectoryMode=0770
WorkingDirectory=/PATH/TO/KOMGA/DBDIR
# Logging below is set to /var/log/komga/komga.log -- this is just an example; make sure user and/or group komga can write there.
ExecStart=/usr/bin/java \
        -Xmx1g \
        -jar /PATH/TO/komga.jar \
        --server.address=localhost \
        --server.port=YOUR_LOCALHOST_PORT_HERE \
        --logging.file.name=/var/log/komga/komga.log \
        --spring.artemis.embedded.data-directory=./artemis \
        --komga.database.file=/PATH/TO/KOMGA/DBDIR/database.sqlite \
        --komga.libraries-scan-cron="17 03 * * * ?" \
        --komga.remember-me.key="RANDOM_LONG_ASCII_KEY_HERE" \
        --komga.remember-me.validity=LOGIN_VALIDITY_IN_SECONDS_HERE
Restart=on-failure
RestartSec=10
TimeoutSec=90
LockPersonality=true
NoNewPrivileges=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
PrivateDevices=true
PrivateTmp=true
PrivateUsers=true
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
ProtectSystem=strict
ReadOnlyDirectories=/
ReadWriteDirectories=/proc/self
ReadWriteDirectories=/PATH/TO/KOMGA/DBDIR
ReadWriteDirectories=/var/log/komga

[Install]
WantedBy=multi-user.target
```

**Comment by gotson** [comment]
Thanks @cabusar for your report.

The configurations are described [here](https://komga.org/installation/configuration.html) and the page contains the `server.servlet.context-path` entry. It does not however explain how to use the `--` form to pass configuration via command line. I will add it.
