### ISSUE TITLE
[Feature Request] Extention for Sub Grouping and get a general title.

### ISSUE THREAD

**Issue by 10lalib** [gotson/komga#355]
### Is your feature request related to a problem? Please describe.
I have a series that have 1 name but several titles with different releases and online the titles are registered without the name. ex: Aincard-(and its chapters)

### Describe the solution you'd like
If possible to have it as following based on the example in the previous paragraph Sword art online - Aincard-(and its chapters).

### Describe alternatives you've considered or other apps that can do what you want
I don't think there is any.

### Additional context
N/A

**Comment by gotson** [comment]
I am sorry but I don't understand what you mean. Can you explain differently, and maybe provide screenshots of what you think is a problem?

**Comment by 10lalib** [comment]
I have a series called Sword Art Online.
In the sub folders i have titles related to each release. You could say they more like different arcs.
And then in each arc i have the chapters.
When adding the series to komga i am getting only the arcs with the chapters without the name of series.
The structure that i would like to have is as following:
Sword  Art Online > Aincard (example) > Chapter #
While i am getting only:
Aincard > Chapter #

So any way to fix that?

**Comment by gotson** [comment]
You can either rename your folder, or manually edit the title or the series in Komga to name it the way you want.
