### ISSUE TITLE
[Bug] Docker Container Fails to Start [x86_64]

### ISSUE THREAD

**Issue by seastones** [gotson/komga#356]
### Komga environment
- **OS**: OMV 4.1.36-1 [Debian Stretch 9.13]
- **Komga version**: 0.64.4
- [X ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
The container fails to launch, seemingly due to an SQLite error. Similar to #345, #349, and #354 but on x86_64.

`java.sql.SQLException: Error opening connection`
is followed by a string of references.

Before ultimately stopping execution is...
`Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367) ~[sqlite-jdbc-3.32.3.4.jar:na]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67) ~[sqlite-jdbc-3.32.3.4.jar:na]
	at org.sqlite.core.NativeDB.load(NativeDB.java:59) ~[sqlite-jdbc-3.32.3.4.jar:na]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.32.3.4.jar:na]
	... 83 common frames omitted`

### Steps to reproduce
1. Pull latest image.
2. Start latest image.

### Expected behavior
Pretty sure a fresh run should spit me out a password and maybe user to log in. Been a while since I ran through startup.

### Actual behavior
See log.

### Additional context
Running from the docker interface in OMV.
/config directory has proper permissions.
Will supply any additional information. Not familiar with Docker by any means, sorry if this is stupid.

### Log file
Link to full log at https://gist.github.com/seastones/29c2859fecc93e052e00474b974867af

**Comment by gotson** [comment]
What's your hardware and cpu info / architecture?

**Comment by gotson** [comment]
After a bit of googling it seems the issue is that your host `/tmp` folder is not accessible or writable, maybe because it's full.

The sqlite native lib is extracted to the temp folder, but in your case it doesn't work.

**Comment by seastones** [comment]
Odd issue to have, but now that I'm thinking I might not have recursively set the permissions. However, letting Docker create a volume of its own for the /tmp directory did in fact allow it to start.

**Comment by gotson** [comment]
Good to close then?

**Comment by seastones** [comment]
I'd say so, thank you for the really quick support!
