### ISSUE TITLE
[Feature Request] Tooltip for previewing synopsis

### ISSUE THREAD

**Issue by Cissoubaka** [gotson/komga#359]
### Is your feature request related to a problem? Please describe.
When looking for a new serie to read, you have to open the serie page to have a look on the synopsis.

### Describe the solution you'd like
I think a good solution is to show the synopsis in a tooltip when the cursor stay on the cover.

**Comment by wyldphyre** [comment]
Ideally there would also be something visible to tap on for those using a device where hover state won't work.
