### ISSUE TITLE
[Feature Request] collect metadata for info.txt generated by Hitomi-Downloader

### ISSUE THREAD

**Issue by lukemin** [gotson/komga#362]
Komga is really amazing app.
I downloaded my comics by [Hitomi-Downloader](https://github.com/KurtBestor/Hitomi-Downloader/).  Would you like to add the function to collect metadata from the info.txt generated by Hitomi-Downloader?

The language of info.txt is as the same as the setting in General Preferences. So for one comic, There may have several different info.txt.
Take Chinese and English as example:
Chinese :
[info.txt](https://github.com/gotson/komga/files/5699916/info.txt)
**图库 id**: 1172760

**标题**: 【中國語】NanoCore「納米核心」2018.1月Ｒ１８の絵のコレクション②

**艺术家**: N/A

**分组**: N/A

**类型**: imageset

**系列**: nano core

**人物**: N/A

**标签**: female:anal, female:mother, female:stockings, female:x-ray, incest

**语言**: Chinese
------------------------------------------------------------------------------------
English:
[info.txt](https://github.com/gotson/komga/files/5699986/info.txt)

Gallery ID: 1172760

Title: 【中國語】NanoCore「納米核心」2018.1月Ｒ１８の絵のコレクション②

Artists: N/A

Groups: N/A

Types: imageset

Series: nano core

Characters: N/A

Tags: female:anal, female:mother, female:stockings, female:x-ray, incest

Language: Chinese

**Comment by gotson** [comment]
I have no interest in adding this. They should instead use existing standards like comicinfo.xml instead of adding their own.

They can also join the anansi project and contribute towards a better standard: https://github.com/anansi-project/rfcs
