### ISSUE TITLE
[Bug] OPDS entries are duplicated for each collection an item is in

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#363]
### Komga environment
- **OS**: Ubuntu
- **Komga version**: v0.64.6-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [x] **I have a problem with an OPDS client application**
  - OPDS Application (with version):  Any application (Including viewing raw OPDS XML api)

### Describe the bug
Comics appear listed multiple times in many of the different views in OPDS, the number times an item is duplicated corresponds with how many collections an item is in.  For example adding a comic to three different collections, will result in that comic being listed 3 times in /opds/v1.2/libraries/<library_id>

### Steps to reproduce
1. Go to the web interface and add a comic to any number of collections
2. Go to that libraries interface in an OPDS client or via the API (/opds/v1.2/libraries/<library_id>
3. See the comic listed the same number of times for each collection that comic is in.

### Expected behavior
Comic should only appear once.

### Actual behavior
Comic is listed multiple times

### Screenshots
![Screenshot 2020-12-17 13 40 10](https://user-images.githubusercontent.com/4960791/102441162-7b596080-406d-11eb-8606-e4f558058349.png)

See the item RWBY is listed twice, because it is in two different collections.
This is the  /opds/v1.2/libraries/<library_id> endpoint, so collections should have no impact here.

**Comment by gotson** [comment]
You only mention a single opds path with the error, but there may be more as you suggested in the issue description. I haven't found any others, but if that was the case please let me know.

**Comment by Kussie** [comment]
Yep all looks to be working fine now! 👍
