### ISSUE TITLE
[Feature Request] Import metadata by analyzing filename or folder structure

### ISSUE THREAD

**Issue by rosystain** [gotson/komga#364]
### Is your feature request related to a problem? Please describe.
After I organized my mangas according to the artist information, I still need to go to the dashboard of Komga to add the artist information again. 
Maybe Komga should know some information by itself.

### Describe the solution you'd like
Some rules can help Komga read metadata from the filename or foldername. 
Take my directory structure as an example:
```text
/Artist A
  - Series 1
     Vol 1.cbz
     Vol 2.cbz
  + Series 2
/Artist B
  + Series 3
```
Then Komga can set "A" as Publishier(Artist is better) for Series 1-2, set "B" for Series 3.

### Describe alternatives you've considered or other apps that can do what you want
Lanraragi can read tags from filename directly if the comic's filename match the format like:
(Event)[Group(Artists)]Title(Series)[Language].zip

**Comment by gotson** [comment]
This would be too complex, as everyone has a different folder structure and different filenames.

Komga has an api which can be used to implement custom scripts.

There is also import of commonly used metadata formats like ComicRack which can help on that front.
