### ISSUE TITLE
[Feature Request]  Add Reverse Proxy authentification

### ISSUE THREAD

**Issue by aaaldo** [gotson/komga#366]
### Is your feature request related to a problem? Please describe.
I have several services running on my home server, including Komga and I'm using Nginx to reverse proxy them. All are under a simple login/password authentification, and i'd like to be able to use this same authentification method for Komga too. The problem is that Komga already has its own login page, that can't be disabled or bypassed, leading to a duplicate login process.

### Describe the solution you'd like
Nginx Reverse proxy (and others like Traeffik i believe) can pass some custom headers to pass along some authentification detail to theirs proxied hosts. My feature suggestion is to provide a way for Komga to read those headers in order to bypass the mandatory login page.

### Describe alternatives you've considered or other apps that can do what you want
Calibre-web provide this way to authenticate and directly log in a user.

**Comment by gotson** [comment]
Please use the template for requests, and explain a bit more your requirement.

**Comment by aaaldo** [comment]
Hello @gotson thanks for the updat. I've properly updated the feature request following the aforementionned template.

**Comment by gotson** [comment]
This seems very outdated compared to more recent authentication schemes like oauth2. We already have a feature request for oauth2 (#143) and I want to move away from basic Auth at some point. Trusting a reverse proxy that uses basic Auth would defeat the point.

**Comment by aaaldo** [comment]
Indeed, thanks for the update !
