### ISSUE TITLE
[Feature Request] Use the comicvine volume tag for titles.

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga#368]
### Is your feature request related to a problem? Please describe.
Since there's the "vol" tag, it makes sense to leave the titles of multi vol series blank, and just adding the number in the vol tag, komga doesn't use that tag as a title.

### Describe the solution you'd like
If there's no title in a book, but a vol tag number, title the book "(series name, vol ##)

Example of tags: ![Screenshot 2020-12-24 212810](https://user-images.githubusercontent.com/65789901/103120990-03dd8f80-4672-11eb-82a6-3cf6ef79327e.png)

Example of what I want to happen with that provided data (manually edited to get what I want): 
![Screenshot 2020-12-24 212936](https://user-images.githubusercontent.com/65789901/103121027-3dae9600-4672-11eb-8f9c-c44f2f138d52.png)

**Comment by gotson** [comment]
The screenshot you show is not `series name, vol ##`, but `Volume #`

**Comment by gotson** [comment]
Moreover, volume is related to a series not to a book. Volume is used in conjunction with a series name to disambiguate a series with the same name in the world fo us comics.

For example a series like "Batman" has many volumes.

I don't know where you got your comicinfo.xml tags, but they don't follow the accepted standard. If you want to get your tags straight, you should use the title tag and set it to "Volume 1".
