### ISSUE TITLE
[Feature Request] handle books in multiple file formats

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#371]
### Is your feature request related to a problem? Please describe.
For some readers it is easier to handle with PDF than with CBR/CBZ.
I have nearly all Comics in 2 Formats: CBR/CBZ and PDF. 
In Komga screen I see now booth Books but not the format. e.g.: Superman 1972 01.cbr and Superman 1972 01.pdf is always shown as Superman 1972 01 twice.

### Describe the solution you'd like
It would be greate to have on the left side an icon with the Format (PDF/CBR/CBZ/EPU..).

### Describe alternatives you've considered or other apps that can do what you want
Alternatives could be to see only one book when everything is identicly and only the format is different.
And then we have a download buttons for every existing format. In my example to downloads are possible Like "Download PDF" and "Download CBR".

An other alternative could be that you write in the last line the format. 
Example:
Superman 1972 01
32 pages   PDF

**Comment by gotson** [comment]
I have no plans to handle multiple formats. Pdf is less capable than cbz, and keeping both is a niche requirement, especially when Komga can serve any format as images for different kind of readers, and handle conversion of image formats on the fly.

**Comment by MKH-42** [comment]
![From_Hell](https://user-images.githubusercontent.com/76835223/103471851-d71e2c00-4d85-11eb-969b-edaab2420617.jpg)
One Example how it could look like.

**Comment by MKH-42** [comment]
![From_Hell_01](https://user-images.githubusercontent.com/76835223/103471887-56abfb00-4d86-11eb-9301-69d7f8c4405b.jpg)
Alternative solution.

**Comment by MKH-42** [comment]
One solution way could be to read from media.media_type the type and map this information.
Examples:
application/pdf ==> PDF
application/zip ==> CBZ
application/x-rar-compressed; version=4 ==> CBR

**Comment by MKH-42** [comment]
Calibre has the option for different downloads. One Book has different download buttons. 
But this solution is a premium implementation.

![From_Hell_02](https://user-images.githubusercontent.com/76835223/103472805-1b172e00-4d92-11eb-8893-c68f507334cf.jpg)
