### ISSUE TITLE
[Bug] Can't access web interface (Docker on Synology)

### ISSUE THREAD

**Issue by otravers** [gotson/komga#372]
### Komga environment
- **OS**:  Synology 

- **Komga version**: 0.64.8
 
- **I am running Komga with Docker**
  - Docker image tag: latest from https://hub.docker.com/r/gotson/komga

- [ ] **I have a problem in the web interface**
  - Browser (with version): tried with the latest Edge (Chromium) and Chrome on Windows 10
 
### Describe the bug

Can't load http://192.168.1.29:8282, I get ERR_EMPTY_RESPONSE

### Steps to reproduce

Install the container, wait a while, try to load the web UI, wait some more, try again.

I installed the container twice (once from Portainer, once from the Docker UI in Synology DSM), I was careful with volumes and ENV variables. Still got the same exact outcome so don't know what else to do at this point.

### Expected behavior

Works!

### Actual behavior

Doesn't work!

### Log file

The database file is successfully created (I checked in the file system too) but two things don't seem right:

1. Tomcat started on port(s): 8080 (http) with context path '' - that's not the port I set in the container's settings as I already use 8080 for another service.

2. A bunch of "Skipping unloadable jar file" warnings related to files in the /app directory.

https://gist.github.com/otravers/93c5e96868257ff66819783864bf4457

**Comment by gotson** [comment]
Please provide a complete log file from startup.

Can you share your docker configuration? With port and drive mappings, running user etc.

What nas do you have?

**Comment by otravers** [comment]
I edited the gist with a fresh log from startup:
https://gist.github.com/otravers/93c5e96868257ff66819783864bf4457

I have a Synology DS920+

Here's the config:
![image](https://user-images.githubusercontent.com/3731532/103493992-6b82a000-4e13-11eb-9a7a-380aa5fe1dbd.png)

**Comment by gotson** [comment]
Your docker config redirects host port 8282 to container port 8282, but the container listens on 8080.

**Comment by otravers** [comment]
@gotson Oh, I see. Fixed, and I'm up and running. Thank you so much for such prompt support on a Sunday night on January 3!
