### ISSUE TITLE
[Feature Request] Add Button Size Option

### ISSUE THREAD

**Issue by kimpig** [gotson/komga#375]
### Is your feature request related to a problem? Please describe.
When I watch all the cartoons and turn them over to the next book, encounter a browser.
![image](https://user-images.githubusercontent.com/61234733/103564321-a5ca6b00-4f01-11eb-8b08-54f92f9e5861.png)

### Describe the solution you'd like
In books with few pages, a long progress bar is just a distraction. So, I want to add an option to adjust the size of the next volume button, or modify the layout a little bit. currently, I think the button is too close to the edge.
The picture below is an additional option that I thought.

![image](https://user-images.githubusercontent.com/61234733/103565540-d4e1dc00-4f03-11eb-9520-d362c0aff39b.png)

**Comment by gotson** [comment]
I don't really see the point of such customization.
