### ISSUE TITLE
[Feature Request] Text filter for the add comics to readlist dialog box

### ISSUE THREAD

**Issue by frameset** [gotson/komga#378]
### Is your feature request related to a problem? Please describe.
I would like a filter to make it easier to find the readlist to which you want to add a comic.

When you have a large number of readlists, it can be time consuming to reach the one you want

### Describe the solution you'd like
Perhaps a text entry box could be added below the new list text box in the screenshot below.

### Describe alternatives you've considered or other apps that can do what you want
An alternative could be to collect the book id numbers of the books I want to add and use the API to add them all to the list at once.

### Additional context
![image](https://user-images.githubusercontent.com/559869/103646044-e8fffa80-4f50-11eb-96eb-3ccb5e7c066c.png)

**Comment by gotson** [comment]
That's a fair request, I think the existing text field could be used to filter also. So when you don't know if you already have a readlist (or collection) with a particular name, you can type it, and if you find it you can select it, else you can create one.
