### ISSUE TITLE
[Feature Request] Read out the ISBN Number of a comic and store in meta information

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#381]
### Is your feature request related to a problem? Please describe.
It would be nice to read the ISBN Numbers from the comics by analyzing the images.

### Describe the solution you'd like
In best case it is possible during the analyzis phase to read out the ISBN Number from the image.
There are 2 kinds of ISBN Numbers: 10 digets or 13 digits.
Store the found ISBN Number in the meta dataset (see request #380 )
This feature should be put on / off via configuration because the scan would be need much time.

### Describe alternatives you've considered or other apps that can do what you want
-

### Additional context
-

**Comment by rurickdev** [comment]
This could be amazing, We could added manually so the app could fetch the data from any public db

**Comment by gotson** [comment]
I've been testing https://github.com/zxing/zxing but without success. Even when cropping the image around the barcode, it cannot detect it. The same barcode is detected easily with some online decoders.

The library is in maintenance mode, so i don't think it's a good idea to use it anyway.

ZBar via JNI could be an option, but haven't looked at it yet.

**Comment by gotson** [comment]
I tried with other images and actually got some results. I might spend a bit more time on zxing and see if i can get more from my own collection.
