### ISSUE TITLE
[Feature Request] Add Reading List information to Series Summary

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#384]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Include in the series summary section all the reading lists associated with the issues of the series.

### Additional context
This would be very useful specially to identify Reading Lists associate to a series. Right now I need to go over all the issues to identify the reading lists.

**Comment by gotson** [comment]
The whole point of reading lists is to group books outside series.

Could you maybe expand on how you use the reading lists and why you would want to discover reading lists from a series, so I get a better understanding on the use case?

**Comment by cesalo** [comment]
In my case I have Komga picking up Reading Lists automatically and even though I've been cleaning it up a bit but there is a lot of Reading Lists that I wasn't even aware of.
For example 1 use case would be:
- Go from Reading List to Series and then discover and pick up another Reading List.
At the moment we can search for Reading Lists but we can't search for Reading Lists within a specific Series or multiple Series.
Another example: I was starting to read "King in Black" and looking for information of this event found a related Reading List: "Absolute Carnage" that has its own Series but involves the Series Venom.
If this information was included in the series Venom I'd have found it and then probably would have found its relationship with "King in Black" as well. Also once I found this one I started to go over all the Venom Series issues and and also found the reading list "Venom Beyond". All of this would have been easier and more user friendly if the Series would contain this information.
In general I think that by adding this information at Series level it will allow us to discover in a different way our libraries and start to dig on events that may be related with events we are actively reading but were unknown.

**Comment by gotson** [comment]
Series and reading lists have no link at all, apart from containing books.

If you want to explore reading lists you can use the reading list screen.

**Comment by cesalo** [comment]
Ok .. then is there a way that a search can be added in the reading list
view? Specifically by a series or a group of series? Just trying to make to
make sense of this idea 😀.

**Comment by gotson** [comment]
I think your use case is biased by the information imported, unknown to you, by metadata from `ComicInfo.xml`. If you had done your read lists yourself you probably wouldn't have a problem.
