### ISSUE TITLE
[Feature Request] Grouping options other than 'by series'

### ISSUE THREAD

**Issue by LucidusAtra** [gotson/komga#385]
I like to read comic books within the context they were released. I like to be able to look around at the other books released during a particular month and year. Plus, there are often stories that run through several different concurrently running series (For example, a cliffhanger in Superman might resolve in that month's Action Comics or vice versa). However, the way Komga is currently structured, books are always grouped by series first. When I open my Spider-Man collection, I see a list of series containing Spider-Man, not a list of books. There's so much extra navigation involved in finding the correct series, finding the correct book in the series, and then doing it all again to find the issue where the story you started continues.

The solution? Allow different types of subgroupings. Or allow no subgroupings: make it so I can just see a list of every book on my server. Or make it so I can click on that Spider-Man collection and see years as the subgroups instead of the different series. 

This would all work better with some better library sorting options as well (i.e. order list by date released, date modified, issue number, etc), but that's a separate issue. This issue is just about removing those mandatory series groupings and allowing several different books from several different series to coexist in the same list.

**Comment by grim7reaper** [comment]
> allowing several different books from several different series to coexist in the same list.

That's exactly the use case for [read lists](https://komga.org/guides/readlists.html), have you tried them?

**Comment by gotson** [comment]
Please follow issue template next time, they are here for a reason. As grim7reaper mentioned, you can use Read lists to group books in story arcs or crossovers.

**Comment by PapaiJarda** [comment]
> As grim7reaper mentioned, you can use Read lists to group books in story arcs or crossovers.

It would help if it had at least an option to mark all files at once. It's not easy to build a reading list with 300+ comic issues when we are forced to mark one by one.

**Comment by gotson** [comment]
> > As grim7reaper mentioned, you can use Read lists to group books in story arcs or crossovers.
> 
> It would help if it had at least an option to mark all files at once. It's not easy to build a reading list with 300+ comic issues when we are forced to mark one by one.

That's incorrect, you can select multiple books at once to add them in the reading list.
