### ISSUE TITLE
[Feature Request] improve search capability

### ISSUE THREAD

**Issue by lbesnard** [gotson/komga#386]
### Is your feature request related to a problem? Please describe.
I have a One Shot album named "S" from the Author "Gippi". This album (cbz) is under a folder also named "S". All my other One Shots follow the same structure.

The issue is about searching for this album. If I type "S", I can't find it. This is obviously a rare and extreme occurrence,  however other albums with titles containing few characters fall under the same scheme.

### Describe the solution you'd like
It would be great to improve the search functionality to order results so that the overall matching of albums/series is ordered by the highest results. If I type "S" in the search, I expect the matching album "S" to be 100%, hence being at the top of the results. On the other end, an album named for example "Serre" should probably be 20%.

Fuzzy search capability could maybe solve this issue. (this would also solve issues with searching with/without accent characters).

Related to https://github.com/gotson/komga/issues/24

**Comment by gotson** [comment]
Part of #24
