### ISSUE TITLE
[Bug] Komga failing to scan folder

### ISSUE THREAD

**Issue by hobhobuk** [gotson/komga#393]
### Komga environment
- **OS**:  Debian Buster
- **Komga version**: v0.68.1-master
- [ ] **I am running Komga from the `jar`**

### Describe the bug
Unsure why, any folder scans fine, however one folder stopped scanning at all.
I tried to remove, reinstall etc, and yet the issue remains.
No scan even begins for this one folder, which use to be fine..

### Steps to reproduce
1. Add folder
2. Wait for anything to happen - nothing
3. Manually click scan, nothing happens (waited around 8 hours)
4. Scan other folders, they update instantly.

### Additional context
Recently added a series of comics, however unsure why this would cause any issue.  Ubooquity did also have issues, but has since managed to scan without issues.   Could it be file names?  Too many comics?  Does Komga have a limit?

Unsure what to do.. or how I can try and fix this.  happy to provide additional info :) (unsure where Komga l;og would be)

**Comment by gotson** [comment]
Please provide log files.

**Comment by xx255q** [comment]
Yes I also noticed this, it either does not pick up new issues or takes hours. Also ever since running 69.1 the drive it rules on is constantly in use 60-80%

**Comment by gotson** [comment]
> Yes I also noticed this, it either does not pick up new issues or takes hours. Also ever since running 69.1 the drive it rules on is constantly in use 60-80%

Pease do not randomly comment on open issues. Open one with details of your problem if needed.
