### ISSUE TITLE
[Feature Request] Save the tags in a table dedicated to them

### ISSUE THREAD

**Issue by zFerry98** [gotson/komga#394]
### Is your feature request related to a problem? Please describe.
Related to problem: #390
As explained in this issue, tags do not have their own membership table. This means that they are associated with the book / series and if this is removed the related tag is also removed from the suggestion list.

### Describe the solution you'd like
Save the tags in a table dedicated to them so that this table (s) is used for suggestions when adding tags to a book.
Obviously also add the possibility of being able to edit this list of tags from the WebUI (from the browser) in case there are tags written incorrectly or to be removed (problem that is already present and therefore to solve it you have to remove the wrong tags from the book that uses it ).

### Additional context
Ability to define which tags to show in specific libraries? With a simple system of flags and IDs where with 0 and associated with the ID of a specific library the tag in question is hidden by the suggestions
(always leaving the possibility to add it by writing it by hand ... an easter egg let's say😆).

Another possibility is to create groups of tags which can in turn be hidden with the aforementioned method.

There are two examples ("extras") not necessarily to be implemented / included now in this feature request (pluses beyond the feature request itself).
Maybe some other users can improve this concept and add more.

**Comment by gotson** [comment]
No interest in over complexifying something that works as most people expect it to.

**Comment by zFerry98** [comment]
> No interest in over complexifying something that works as most people expect it to.

I hope you're joking?

complexifying? If anything, SIMPLIFY!

### People have not had this problem and therefore it seems to you that it is not necessary ... Open a DB of a manga server (eg Mango) and you will see that ALL use the specific table for tags (for the suggestion function). But let's not joke please. Load the suggestions from the tags saved by the metadata from a fucking book in the library and load them from a table saved in the DB which is even easier to manage (I also wrote you the most basic logic for this system)...
