### ISSUE TITLE
[Feature Request] Resume Read List from Keep Reading

### ISSUE THREAD

**Issue by reverendj1** [gotson/komga#399]
### Is your feature request related to a problem? Please describe.
If you are reading from a read list and stop, you have to re-select the read list to continue within it.

### Describe the solution you'd like
I'd like to be able to continue a read list from the Keep Reading section on the home page. The way I imagine it would be that if you started a book from a read list, when it shows up in Keep Reading, it would keep the context of the read list.

**Comment by gotson** [comment]
That's interesting. However at the moment the context only exist on the client side, it's unknown to the server. That would require storing read progress along with reading context.
