### ISSUE TITLE
Dual page splitting

### ISSUE THREAD

**Issue by gotson** [gotson/komga#40]
It would be convenient to have a dual page splitting functionality server side, since not all readers are able to perform split (Tachiyomi for instance cannot).

It should:

- [ ] be optional, and disabled by default
- [ ] be requested via api
- [ ] play nicely with both LTR and RTL
- [ ] be mindful of image dimensions to reduce false positives as much as possible

**Comment by WilliamPrvz** [comment]
i'm very interested in this feature, what android reader can perform the split ?

**Comment by gotson** [comment]
> i'm very interested in this feature, what android reader can perform the split ?

I would implement the client side logic in Tachiyomi.

**Comment by WilliamPrvz** [comment]
the new dual page splitting is nice, but is it possible to have them stick together ? so it look even more like a real manga. thanks

**Comment by gotson** [comment]
> the new dual page splitting is nice, but is it possible to have them stick together ? so it look even more like a real manga. thanks

What you mention is here: #72 

Page splitting is to split landscape images in 2 portrait images, server side, so that client can display them separately.

**Comment by KillahB33** [comment]
I think this would be great because I would love to use dual page reading on web but when a dual page come up then it shows all three

**Comment by gotson** [comment]
> I think this would be great because I would love to use dual page reading on web but when a dual page come up then it shows all three

This is a different issue and logged in #123
