### ISSUE TITLE
[Bug] No Read Lists

### ISSUE THREAD

**Issue by bryanmcain** [gotson/komga#400]
### Komga environment
- **OS**: MacOS 10.15.7
- **Komga version**: 0.69.2
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: 13.0.1
- [X] **I have a problem in the web interface**
  - Browser (with version):  Firefox 85.0, Mobile Safari 14.4
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
I don't see an option to add comics to a Read List - I only see collections

### Steps to reproduce
1. Go to any comic, 
2. Click on 3 dots
or
4. Select multiple comics from main list

### Expected behavior
I expect to see options to add books to read lists.

### Actual behavior
No options to add to read lists.

### Additional context
I've double checked - the option in the library is set correctly.  Also, when I click on Libraries in the sidebar I can see an option for read lists next to browse & collections, but when I click on the specific library that button is gone.

FWIW - this library has been used since version .10 or so.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

**Comment by gotson** [comment]
Series can be added to collections, books can be added to readlists. If you see the option "Add to collection", you are on a series, not on a book, and that's a normal behaviour.

**Can you provide screenshots or video, _as requested in the template_ ?**

> I've double checked - the option in the library is set correctly.

Readlists can't be disabled. The option is for importing metadata as readlists.

> Also, when I click on Libraries in the sidebar I can see an option for read lists next to browse & collections, but when I click on the specific library that button is gone.

The tabs are contextual, when browsing a library without collections or readlists, the tabs won't show up.

**Comment by bryanmcain** [comment]
Could have sworn i tried it both on a series and a book, but it looks like i didn't.  Thanks  for getting  back, sorry to bother you.
