### ISSUE TITLE
[Feature Request] Add possibility to drill down in folder structure

### ISSUE THREAD

**Issue by smorkin** [gotson/komga#401]
### Problem
My comics folder structure is not really suited for how Komga works right now. My problem is that I have e.g. folders like "Heavy Metal/1986/<each separate issue for 1986>", or deeper like "Manga/Rumiko Takahashi/Maison Ikkoku/Collector's Edition/<each separate book>". In Komga this results in a lot of series with names such as "1986", "Collector's Edition", etc, with no clue what the actual content is. It also means that my library right now consists of 2636 different series, which makes it cumbersome to find anything by browsing.

### Suggested solution
If possible I'd like something like how Ubooquity handles comics in a library: One entry / top-most file or folder, click on a folder to drill down to get yet another entry / file or folder, and so on.

Obviously, this way of looking at a Komga library would not be the best for every user or every library, so maybe a setting for how to show books in a specific library.

### Alternatives
Renaming and restructuring my comics would help a bit, but I suspect I wouldn't get all the way even by doing that. And searching doesn't get me want I want either; e.g. there is no way I could find everything by Rumiko Takahashi since that is just the name of a folder containing other folders -> search in Komga won't show these.

I also really like browsing the comics, Komga's default look is very nice and entices me to read, so that I can't really use that browsing feature (due to a few thousand series with sometimes nonsensical names) is a bit sad; a good UI is to be treasured, and I really like how Komga looks.

### Additional context
In general I much prefer Komga's look and feel, features, etc compared to e.g. Ubooquity, but this issue is problematic for my use case. I'm not that fond of micro-managing my comics since I have so many of them (a few TBs) so I just want to be able to read them in a quick but a the same time pleasant way, so aesthetics matter a lot, but also not having to make metadata XML files for everything I add to my discs.

**Comment by gotson** [comment]
I have no plans to support directory browsing, for the simple reason that directories are only one way to represent data, while there are various facets to explore data, and that's where Komga steps in with Collections, Read Lists etc.

---

Now let me try to help you with your current situation.

You can edit a series' name directly in Komga, so you don't have to change your existing directory structure. You could rename `Collector's Edition` to `Maison Ikkoku (Collector's Edition)` for example.

Else you could rename the last folder to have the necessary information, for example rename the directory `Manga/Rumiko Takahashi/Maison Ikkoku/Collector's Edition/` to `Manga/Rumiko Takahashi/Maison Ikkoku/Maison Ikkoku (Collector's Edition)/`.

For your `Collector's Edition`, do you actually have multiple editions of the same manga?

For `Heavy Metal`, is that one folder by year of publication ? If yes, what's the point of separating them in a year folder, if i may ask?

---

About your thoughts:

> e.g. there is no way I could find everything by Rumiko Takahashi since that is just the name of a folder containing other folders -> search in Komga won't show these.

We plan to have #339 which will probably include a search by author.

**Comment by smorkin** [comment]
Understood, and expected; I agree with the idea to not care about the folder structure in general since it is a nice approach. In this particular case I personally would prefer a folder-based approach due to a couple of reasons (laziness / not wanting to have thousands of series / no generally accepted file naming convention and nothing like TheTVDB for auto-grabbing of info), but I know there are (good) arguments against it :-)

And thanks for the suggestions, I have been (slowly) doing a few things like those suggested over time since they are good suggestions. As for Heavy Metal, reason is mainly because that's how I got them, sub-folders and all, and the separate books don't have unique names so I'd need to rename them all if I put them in a common folder (currently, looks like "Heavy Metal/1986/01.cbz", etc) and the current names have no standard of naming so can't batch rename them either. With Takahashi, I do have a bunch of e.g. different Maison Ikkoku editions (there have been flipped, non-flipped, and different translations), all with their different positives/negatives which is why I save them, and having to rename all folders for any books to have names which completely tells me everything is, well, too much work for me. And of course I'm not complaining about Komga, I know my use case is very much my own, and probably not relevant to many others. Plus, not my software so no complaints :-)

**Comment by gotson** [comment]
If you need help in changing your directory structure, or for some scripts to handle that kind of stuff, you are welcome to join the Discord server, many people are willing to help :)

I will close this as i don't intend to add this feature, but again, don't hesitate to reach out if you need help (via Discord).

**Comment by smorkin** [comment]
Thanks for the help, might drop in at Discord. And/Or perhaps learn Kotlin; I'm a C/Obj-C/C++ guy mostly, but I've developed a few algo trading systems in Java so should probably learn Kotlin as well, might be fun!
