### ISSUE TITLE
[Feature Request] Device Migration

### ISSUE THREAD

**Issue by kiriya-aoi** [gotson/komga#405]
### Is your feature request related to a problem? Please describe.
Komga can only be moved to a different device if the library path can be mimicked. This is tedious but doable within the confines of the same OS, but prohibits migration from e.g. Linux to Windows.

### Describe the solution you'd like
The ability to change the root folder path without destroying the database as long as the relative paths of content are the same, such that a Komga database can be copied with a library to a different device without needing to exactly replicate the path.

### Describe alternatives you've considered or other apps that can do what you want
The addition of a "backup" of sorts that would store the metadata I've input via the WebUI to make rebuilding everything I've done with my library easier. That could be along the lines of https://github.com/gotson/komga/issues/82, which would handle book metadata, but the ability to store read progress and reading lists and collections would be ideal to go with it.

**Comment by gotson** [comment]
Not something i am willing to implement, this is probably a very edge case. However #217 would probably solve this.
