### ISSUE TITLE
[Bug] While reading from ComicInfo.xml in UTF-8 I receive an ERROR 9480

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#409]
### Komga environment
- **OS**:  Windows
- **Komga version**: 0.69.2
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: java version "1.8.0_271" 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Komga has in some situations problems with UTF-8 ComicInfo.xml files.

### Steps to reproduce
I will add a sample file

### Expected behavior
It should be possible to read UTF-8 files.

### Actual behavior
I receive following error: ERROR 9480

### Additional context
I also tried to start Komga with option -Dfile.encoding=UTF-8.
This doesn't help.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

2021-02-16 00:57:30.567 ERROR 9480 --- [enerContainer-1] o.g.k.i.m.comicinfo.ComicInfoProvider    : Error while retrieving metadata from ComicInfo.xml

com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x74 (at char #257, byte #37)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:690) ~[jackson-dataformat-xml-2.11.3.jar!/:2.11.3]
[ComicTest.zip](https://github.com/gotson/komga/files/5984923/ComicTest.zip)

**Comment by Kussie** [comment]
Your ComicInfo.xml file is not valid UTF-8 hence the error.

```
simplexml_load_string(): Entity: line 6: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE4 0x74 0x74 0x65
```

**Comment by MKH-42** [comment]
Thanks!
It looks like the file format is wrong.
