### ISSUE TITLE
[Feature Request] Read List download

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#411]
### Is your feature request related to a problem? Please describe.
Now that we can download directely a full serie, it would be great to be able to download a full read list at once. Especially to share it.

### Describe the solution you'd like
The same way that the serie download.

**Comment by gotson** [comment]
if @Snd-R is up to it, why not?

**Comment by bareheiny** [comment]
As a Windows user, I have been unable to find comic readers that support OPDS or connect to Komga.

While Komga's web reader is good, reading double page spreads on a smaller screen (specifically a Surface Go) is problematic without a way to zoom easily.  Zomming can be done by exiting the full screen mode, but is fiddly and often triggers a page change.

As there are other readers available (such as Cover), I would like to be able to download all comics in a reading list.  I could then use another application to read the comics.

To make this function useful, the comics would need to be named in a way that meant they could be sorted by their place in the reading list.  The comic readers I have tried previously all parse, and allow sorting by, embedded metadata - as well as allowing sorting by file name.

This means that for a reading list, files named sequentially based on their place in the reading list will be ideal - the reading application of choice should allow users to display the filename or the metadata.
