### ISSUE TITLE
[Bug] Scroll Bar always on via CSS in web interface, even when not needed

### ISSUE THREAD

**Issue by cityeyes** [gotson/komga#414]
### Komga environment
- **OS**: Windows 10
- **Komga version**: 
- [x] **I am running Komga from the `jar`**
  - Java version: 
- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome, firefox, edge, all newest stable versions

### Describe the bug
The scroll bar never goes away on my windows tablet - even when it's unnecessary. 

### Steps to reproduce
1. Go to web interface in a browser at a resolution large enough to see the entire page.
2. Notice scrollbar greyed out on right.

I've found it kind of distracting trying to read on a Windows 10 tablet - obviously not world-ending, but it was enough of a nuisance always seeing the little bar instead of a full-screen comic that I took the time to get rid of it.

It's easily fixable, and I've even made a tampermonkey script to deal with it in the meantime. The problem (if this is in fact a bug and not a feature), is that the overflow-y: scroll is set, which means it will always appear, even if a page can't scroll. Change that to "auto" and the scrollbar goes away when it isn't needed and still pops up when it's needed.

**Comment by gotson** [comment]
It's a Windows problem, it doesn't happen on other OSes.

**Comment by gotson** [comment]
Also, screenshots would help to make it clear what you are talking about :)

**Comment by gotson** [comment]
> It's easily fixable, and I've even made a tampermonkey script to deal with it in the meantime. The problem (if this is in fact a bug and not a feature), is that the overflow-y: scroll is set in the CSS, which means it will always appear, even if a page can't scroll. Change that to "auto" and the scrollbar goes away when it isn't needed and still pops up when it's needed.

If you can send a PR i will have a look, i do not have access to any Windows device to fix this.

**Comment by cityeyes** [comment]
It's hard to illustrate remotely, and I'm away from my computer so I had to remote into it, but this is what I mean. 

![Screenshot_20210219-024402_Remote_Desktop~2](https://user-images.githubusercontent.com/8008991/108481015-429c5a00-725d-11eb-9068-72d879b4dcc0.png)

The basic issue is that the scrollbar on the Y axis, along the right side of the screen (denoted with the arrow), is always present, even when the screen can't be scrolled. The behavior is present on both desktops I tested, but not my phone.

I haven't messed with Github in ages and honestly just did a bunch of googling until I figured out enough about CSS to fix the issue, but I'll give it a shot.

If there's a specific CSS file, it should be as easy as changing:

overflow-y: scroll

To

overflow-y: auto

Since the "scroll" option results in an always-present scrollbar, and auto makes it go away when it isn't needed. I'll take a look at it tomorrow and see if I can figure it out!

**Comment by cityeyes** [comment]
Okay, I looked at the project and I have pretty much no idea what I'm doing. I THINK that editing the global CSS file would fix it, but there has to be something underlying that's changing the behavior in the first place and I don't know the first thing about tracking it down. I don't want any changes that I make to be bandages, or to make it worse for someone else, so let me know if you have any ideas.

I was also able to get a screenshot of the issue on my desktop in vertical. You can see what it looks like here:

![VerticalScrollbar](https://user-images.githubusercontent.com/8008991/108536246-d3952480-72a1-11eb-88d7-d8e6417b55d9.jpg)

As you can see, the comic has "fit to page", but the scrollbar is still there even though it's useless in that situation. Not the end of the world, but distracting.

**Comment by cityeyes** [comment]
Found it, I think. In tabbed-dialog.sass, there are two references to overflow-y: scroll, I THINK we can change those to either "auto" or "hidden" and it should get rid of that scrollbar. I'll try to make a PR, but I've only done a few things on Github in the past.

**Comment by gotson** [comment]
That class should only be used when showing dialogs, so probably not the right culprit, but we never know!

**Comment by cityeyes** [comment]
Ah, my mistake. I just made a guess since it was the only file in the repository that I could find that contained overflow-y:scroll. 

Checking the developer console, it seems that the interface is pulling the overflow-y:scroll property from the file "chunk-vendors.20cf6f20.css". I'm not sure where that file inherits the scroll properties from, but it seems to be where the culprit resides.

Sorry I can't be of more help, I'm not very familiar with CSS, or any of this, really.

**Comment by Kussie** [comment]
This is the expected behavior of the Vuetify package that normalizes the display.  However this particular behaviour is hotly debated ( [See here](https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#scrollbar-overflow) ) but i agree it would be nice to have it only show when needed as that is what users have come to expect these days.

I have created a PR ( https://github.com/gotson/komga/pull/421 ) that solves this issue, if @gotson agrees.

**Comment by cityeyes** [comment]
I guess I was on the right track asking to add overflow-y: auto; to the global CSS file, although I had no idea why. I really appreciate your work on it, thank you!
