### ISSUE TITLE
[Feature Request] Provide a way to stop the service via the web UI

### ISSUE THREAD

**Issue by wyldphyre** [gotson/komga#416]
### Is your feature request related to a problem? Please describe.
I find it frustrating and inconvenient that the only way to stop or restart the Komga service is to find and kill the java process on the computer running it. I don't need to do this often, but I need it whenever I upgrade the service with a new release, and killing a process should never be the only way to stop something from running.

### Describe the solution you'd like
It would be great if there was a simple way to tell the service to stop or restart (both options) via the web UI. You could have a section/option in the server settings, or even at the bottom of the left hand panel. This would presumably be restricted to Admin users, but it might be nice to have the option to make it available to everyone.

### Describe alternatives you've considered or other apps that can do what you want
I haven't really considered any alternatives to finding and killing the java process, as I don't think there are any. As an example of how this could be done, I use Mylar and have always appreciated that it has an option to stop or restart the service at the bottom of each page.

**Comment by cityeyes** [comment]
If you start it with a bat file, I believe you can close the window to stop the service. That's how I've been doing it, at least. I admit, it'd be handy to have the controls in the UI, though.

**Comment by wyldphyre** [comment]
The .bat file thing would probably work, but I'd really rather have a clean way to stop the app to avoid corrupting anything.

**Comment by gotson** [comment]
@wyldphyre is your request about restarting the service, or about upgrading?

Also, which OS are you using?

Depending on how you install it (https://komga.org/installation/) there are some ways to automate what you want. It mostly depends on the integration you use. 

---

Restarting involves stopping the current process and starting a new one, while upgrading also requires to use a new jar file (when using jar). This depends completely on how you installed and how you run Komga.

When you use docker those things are irrelevant, because hidden by docker itself. Using something like Watchtower can automatically upgrade your containers for example.

If you use any kind of daemon integration (via systemd for example), then the procedure is again different. 

All in all it's not really a Komga concern, but an integration/distribution concern.

**Comment by wyldphyre** [comment]
- I think most of the time I'd want to stop the service it would be because of upgrading, so having a Stop option would be more useful that a Restart. 
- I'm running the jar raw on Windows at the moment, but also run a Mac, so that might be something I do in the future.

While I can appreciate your angle on it not being a Komga concern, it still seems reasonable to provide a clean mechanism for stopping the app/service when it is running standalone, rather than in something like Docker.

FYI, I tried Docker but it was wasn't happy with the paths I was trying to give it, and I eventually gave up.

**Comment by gotson** [comment]
On any reasonable os, stopping the process with a stop signal will perform a graceful shutdown. If using a kill signal, then any process or any kind would be abruptly stopped.

I am not sure what happens on windows, hadn't had a windows OS for many years now. 

When in saying it's not a Komga concern, I mean at code level. Could still be packaged within this repo, or in an official method. For windows we've been waiting for contributions for a good way to install it as a windows service which would be the cleanest. Integrating it in package managers like chocolatey would also probably be a good idea. For Mac it could be integrated in homebrew probably. 

Stopping from the ui should be easy to add though, and could be a good middle ground for the time being, while integrations are catching up on windows and Mac.

**Comment by wyldphyre** [comment]
Ok. 

On a side note, I'd be happy to use Docker if I could work it out. All of the examples seem to assume you know Docker. I'm a dev, but I don't know Docker so the examples are not all that clear. I've got an image now, but I don't see how to set the paths up to point to my existing data

**Comment by gotson** [comment]
For docker I would suggest reading some tutorials to understand how volumes work. Note that there's no windows docker image, they are only available for Unix based systems, but you could run it on wsl though.

I checked a but about stopping processes on windows, a simple `taskkill` without the `/F` option should send a stop signal, the app would gracefully shutdown. If running in console, a CTRL+C should also gracefully shutdown the app.

I'll look into adding a stop button within the ui, I know for sure that Spring Boot has an endpoint ready for that already.

**Comment by wyldphyre** [comment]
I have WSL 2, etc. I just need to work out the config settings for the volumes. Thanks.

**Comment by Kussie** [comment]
This is my configuration from my docker-compose file for Komga:
```
  # Manga Server
  komga:
    image: gotson/komga
    container_name: komga
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${MEDIA_SHARE}/Manga:/books
      - ${MEDIA_SHARE}/Comics:/comics
      - ${APP_DATA_DIR}/komga:/config
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9015:8080"
    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#.yacreaderlibrary
      - KOMGA_LIBRARIES_SCAN_CRON=0 0 * * * ?
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
```

It uses an environment variable called MEDIA_SHARE that sets where my media files are located on my machine.  And APP_DATA_DIR is a path to a location where i store the config related stuff.

In this case the ENV values for these that i use are:
APP_DATA_DIR=/docker/appdata
MEDIA_SHARE=/mnt/Media

**Comment by wyldphyre** [comment]
@Kussie Thanks. I'll try to put this to use at some point.
