### ISSUE TITLE
[Feature Request] Libraries in Tachiyomi

### ISSUE THREAD

**Issue by valdearg** [gotson/komga#417]
When opening the Komga Tachiyomi plugin, you can filter by various factors (genres/tags/publishers/etc). 

Currently the Libraries however doesn't give any filter options.

Ideally it would be great to have a listing of libraries from Komga in this list

View within Komga:
![image](https://user-images.githubusercontent.com/2789033/108628434-dd11be80-7452-11eb-9829-e255f7972527.png)

In Tachiyomi, the Libraries doesn't load anything.
![Screenshot_20210221-144145_Tachiyomi](https://user-images.githubusercontent.com/2789033/108628454-016d9b00-7453-11eb-9abe-5dbdcf4fc7cb.jpg)

**Comment by gotson** [comment]
![Screenshot_20210222-072620](https://user-images.githubusercontent.com/2139133/108642309-5e169780-74df-11eb-9528-394ba6517751.jpg)

That feature already exists.

**Comment by valdearg** [comment]
Any idea why it isn't working in my setup? Libraries doesn't expand for me.

**Comment by gotson** [comment]
> Any idea why it isn't working in my setup? Libraries doesn't expand for me.

Please open an issue at https://github.com/tachiyomiorg/tachiyomi-extensions and flag it as `[Komga]`, and mention me @gotson so i can help you there.
