### ISSUE TITLE
[Feature Request] Ignore trailing whitespace in email field when logging in

### ISSUE THREAD

**Issue by wyldphyre** [gotson/komga#429]
### Is your feature request related to a problem? Please describe.
I just had trouble logging in before realising I'd accidentally added a space to the end of my email address. Easy enough to fix, but took several goes before I realised my mistake.

### Describe the solution you'd like
I think it is reasonable for the authentication mechanism to trim whitespace from the end of the email field, as I don't think it would ever be relevant.

### Describe alternatives you've considered or other apps that can do what you want
Alternatively, perhaps the UI could indicate the trailing space in some fashion as a warning to the user

**Comment by gotson** [comment]
I've added validation for the form fields, like in other forms, so if the email is not valid it will raise an error.
