### ISSUE TITLE
Numbering for series with unusual issue numbering

### ISSUE THREAD

**Issue by DarkSir23** [gotson/komga#43]
I noticed that a series with either missing issues, strange issue numbers (like the 1.MU books) or series that didn't start with #1 (G.I. Joe ARAH) are numbered 1-XXX inconsistently from their actual issue number.  

Wasn't sure if this was intended behavior.

**Comment by gotson** [comment]
At the moment the numbering is quite simple, it uses a natural sort algorithm to order the files in the folder. The natural sort helps to avoid having `12` after `013`.

The obvious downside is that if you don't have all the books in a series, the numbering is wrong.

Going forward Komga should be able to retrieve metadata for books from sources like Comicvine (see #11), and then the number of a book in a series will not be computed anymore.

In the short term I will probably offer to edit the number from the UI (along with other metadata fields), which should help to correct some mismatches.

What are `1.MU` books exactly ? I've never heard of that.

**Comment by DarkSir23** [comment]
Marvel just has a habit of doing weird non-numeric issue numbers, they did a series bunch of #.AU issues during Age of Ultron, for example.

**Comment by gotson** [comment]
When #48 is done you will be able to override the issue number with whatever suits you, would that work?

**Comment by gotson** [comment]
I just re-read your comment, and for the moment the number is a `Float`. You are saying that there are issue numbers that are not purely numerical?

With a numbering like `#.AU`, is the `AU` part relevant ? Or could we just use the number instead for the sake of ordering?

**Comment by DarkSir23** [comment]
Yeah, there is a #1.AU and a #1, separate issues.  They have also used the infinity symbol as an issue number, as well as a few other weird things.

**Comment by gotson** [comment]
> Yeah, there is a #1.AU and a #1, separate issues. They have also used the infinity symbol as an issue number, as well as a few other weird things.

But those issues are not part or the same series, right?

**Comment by DarkSir23** [comment]
I so wish I could tell you they weren’t. But they were.  Usually released in consecutive weeks

**Comment by gotson** [comment]
> I so wish I could tell you they weren’t. But they were. Usually released in consecutive weeks

Could you share sone links about those issues like comic vine or official marvel website so I get a better idea?

I haven't set the model for metadata yet, so if I need to use `string` instead of a numerical value, better do it now than later.

**Comment by DarkSir23** [comment]
https://comicvine.gamespot.com/spider-man-deadpool/4050-87182/?page=2
https://comicvine.gamespot.com/fantastic-four/4050-53921/

Avengers Assemble turned their books 13 and 14 into 13.AU and 14.AU, but Fantastic Four had both 5 and 5.AU

**Comment by DarkSir23** [comment]
I know Mylar had to do some weird wrangling with issue numbers, for those very reasons.

**Comment by gotson** [comment]
Thanks a lot, it is very useful!

Do you know how the sorting works, for example between Fantastic Four 5 an 5.AU, which is first? Is there a generic rule, or it will depend case by case?

**Comment by DarkSir23** [comment]
Well, Spider-Man Deadpool 1.MU was actually released a year after 1.  But the .AU titles released at the same number as the current issue.  Consistency is an anathema to the comic industry, and the bane of comic aficionado programmers.

**Comment by DarkSir23** [comment]
So really, there's no wrong answer, cause there's no right one

**Comment by gotson** [comment]
> So really, there's no wrong answer, cause there's no right one

That's something we can work with, I'll just need to build the flexibility for people to choose what they want. 

I could always implement a sort order field, that is used only for sorting. Plex has this, it's super useful, and very flexible.

**Comment by GlassedSilver** [comment]
There's also other oddities. With mangas there will sometimes be series that get scanlated by different groups and their filenames may differ greatly.

Some will number like this:

Ch. 009

Then there's these ones that also happen:

Chapter 9
`#098` (using code wraps as to not trigger linking to an issue)
Vol. 2 Ch. 12

And various alternations of those. Really funky stuff can happen, like my Umaru manga Chapter 162 being the first item in the list in Komga.
(filename: Ch. 162 - Umaru And Reception [Heisei-Scans].cbz)

Chapter 161 for example looks like this:
Vol. 09 Ch. 161 - Umaru and Indoor Pools [Heisei-Scans].cbz

EVEN THE SAME BLOODY SCANLATION GROUP I JUST REALIZED! 😨 

I'm sure there's other wrapping words and the like...

Tachiyomi's sorting of Mangadex entries is godlike though, no issues so far.

Oh and let's keep in mind that chapter 16 and chapter 16.5 are "one chapter" and chapter 17 shouldn't become 18. :)

Those sorts of extra chapter pages are quite common in the manga world.

**Comment by gotson** [comment]
The actual numbering of an issue or chapter and the filename are 2 different things.

For manga in particular, they have absolute chapter number, and are sometimes grouped in volumes. In which case it's up to you to decide if you want one big series with all chapters, or multiple series per volume. It's been discussed in #46. 

Komga now has metadata for series, so you can update the title of a series without having to rename the folder on disk. 

For the problem you mention about sien files having prefix in the filename, it's up to you to fix the filename so they all sort the same way. Anyhow it's not just a Komga problem since the files would also be out of order on disk. 

Hope that's not the clear.

**Comment by gotson** [comment]
@DarkSir23 this is ready, you can now edit a book metadata and set both the **Number** and **Sort Number**.

- **Number** is a _String_ and can accommodate issue number like `4.AU`.
- **Sort Number** is a _Float_, and can help to order an issue like `4.AU` in-between 4 and 5 by setting a Sort Number to `4.5` for example.

<img width="657" alt="Screenshot 2020-03-17 at 11 08 12" src="https://user-images.githubusercontent.com/2139133/76818164-d42a6d00-683f-11ea-916d-82d253b88b3e.png">

**Comment by GlassedSilver** [comment]
In case any fellow weebs need a solution for volumes sometimes being in the filename and sometimes not and not being overly keen on scripting a hacky solution, but rather having the post-processing being done by the software doing all downloading and saving (FMD in my case): https://github.com/fmd-project-team/FMD/issues/893

**Comment by gotson** [comment]
Please do not comment on closed issues, thanks.
