### ISSUE TITLE
[Feature Request] Make author chips clickable to filter parent collection

### ISSUE THREAD

**Issue by thampp** [gotson/komga#431]
The new ability to filter for author information is a great start. But with hundreds of authors it's the current UI interaction is not really usable. It takes to long to find the author to filter for.

One partial solution to this would be to extend the support to make publisher, status, language, ageRating chips clickable that was introduced in v0.74.0 to. author information. Ideally this would work both at the series and the book level.

It would be a quick way to filter for other series containing books of the same author.

Beyond that it would be great if writers would be searchable via the search bar which currently only searches for titles of books/series/collections/readlists.

**Comment by gotson** [comment]
> Beyond that it would be great if writers would be searchable via the search bar which currently only searches for titles of books/series/collections/readlists.

that's an entirely different feature, feel free to create a request for that.

> But with hundreds of authors it's the current UI interaction is not really usable. It takes to long to find the author to filter for.

I have hundreds of authors and the scrolling if fine for me 🤷🏻

**Comment by Kussie** [comment]
I think the biggest issue to overcome is that the list of authors/writers etc on a series could be quite lengthy.  The First thing that should probably be addressed is making the list of them work somewhat similar to the expandable summary.  Ideally using something smaller then the button, possibly a collapsible panel or a text link.

From there can look at making the authors and such clickable.

Might have a bit of a play with some ideas after the weekend.

**Comment by thampp** [comment]
Wow, this was a quick reply. I will create a separate request for that author search as you suggested.

But let me also take the time to say how much I appreciate the great work you are doing here with Komga. It was great to start with but it's really becoming better every week!

And obviously you better at scrolling through filter lists than I am :-)
