### ISSUE TITLE
[Feature Request] Make authors searchable via the search bar

### ISSUE THREAD

**Issue by thampp** [gotson/komga#432]
Finding all books from a given author is currently supported filtering.
But it would be great to have a keyboard-based, search way to dot this as well. One way to do this could be to extend the search bar which currently only searches for titles of books/series/collections/readlists to also search for authors.

There are some challenges on how the grouping would work in that case (currently search groups by books/series/collections/readlists).

This feature request is a spin-off from issue #431

**Comment by gotson** [comment]
Plex has this feature, the actors/directors appear as a separate category, and clicking on an item brings you to the library view, filtered by that actor/director.

<img width="363" alt="Screenshot 2021-03-01 at 17 04 05" src="https://user-images.githubusercontent.com/2139133/109475141-4bd4c480-7ab0-11eb-91ec-80d75bcca860.png">
