### ISSUE TITLE
[Bug] Invalid Email & Unable to Change

### ISSUE THREAD

**Issue by meowmix3** [gotson/komga#434]
### Komga environment
- **Debian**: 
- **0.75.1**: 
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [x] **I have a problem in the web interface**
  - Browser (with version): qutebrowser v2.0.2
 
### Describe the bug
Hey!  Love Komga, thanks for all the work.  So I upgraded to the latest version via Docker from .75 , and it locked me out of my account, saying "Invalid Email".  The email I use is `alex@localhost`, since I'm the only user on my instance.  I downgraded to .75 to change my email, but there doesn't seem to be a way to change it if you are the only user on the account. 

### Steps to reproduce
1. Use @localhost email
2. Upgrade to .75.1
3. Try to log in

### Expected behavior
A way to change the email, or a bypass for @localhost non-emails

Thanks for reading!

**Comment by gotson** [comment]
Hi, thanks for bringing that up. It seems that the default server side validation for emails accepts domains without extensions, I was not aware of that. I will fix the server so that domains without extension cannot be registered.

For the moment there is no way (API or UI) to update a user's email address, but you can update directly in the SQLite database:
1. stop Komga
2. locate the database `database.sqlite` in the config folder
3. open with any SQLite browser or client
4. update your email in the `USER` table

Let me know if you have any issues doing so, I will guide you trough.

**Comment by meowmix3** [comment]
> Hi, thanks for bringing that up. It seems that the default server side validation for emails accepts domains without extensions, I was not aware of that. I will fix the server so that domains without extension cannot be registered.
> 
> For the moment there is no way (API or UI) to update a user's email address, but you can update directly in the SQLite database:
> 
> 1. stop Komga
> 2. locate the database `database.sqlite` in the config folder
> 3. open with any SQLite browser or client
> 4. update your email in the `USER` table
> 
> Let me know if you have any issues doing so, I will guide you trough.

Hey!  Thank you so much for replying.  I think I'm going to take you up on your offer--since I'm not that familiar with sqlite3 commands.  Would you mind telling me what to do after opening up the database with `sqlite3 database.sqlite`?

Really appreciate it, thanks again for taking the time to help.

**Comment by gotson** [comment]
I think the best if your are not familiar with SQL is to use something like https://sqlitebrowser.org/

That way you can see better what's in the DB, and edit more easily.

**Comment by meowmix3** [comment]
> @meowmix3 did you manage to update your email in the db via a gui tool ?

Yes!  Just got around to messing with it, thanks for reminding me.  I edited the DB and updated to the latest docker image successfully.  Thanks for all the help!
