### ISSUE TITLE
[Feature Request] When clicking on metadata chips (author, publisher etc.) change search result display to display both series and books

### ISSUE THREAD

**Issue by thampp** [gotson/komga#439]
This is a follow-up request upon #431 
The current search result only shows the series that contain the clicked metadata element.
But often a series contains a mix of authors and the real search interest on the level of individual books. Metadata on the series level is only a projection of the metadata on the book level anyway.

When using the global search bar the result list already shows a very helpful way to display both series and book results.
It would be great if that search result display would also be supported for searched initiated by clicking on metadata chips.

The same behaviour would also be helpful when the search is initiated by clicking on a filter on the right.

![image](https://user-images.githubusercontent.com/13353725/109858967-baef1c00-7c5c-11eb-877d-b76597dbb90c.png)

**Comment by gotson** [comment]
Blocked by #432 for authors

For other metadata it's only at series level, so probably irrelevant unless you can explain more?

**Comment by thampp** [comment]
If/when #432 is implemented this is no longer a high priority.

The main values comes from situations where a click on an author shows a series where that author only contributed as minor co-author of one book in a large series. The series then does show up in the search result but it's hard to understand why that series shows up until you look through all books to understand where that one minor contribution occured. Visiting cover artists create a lot of such variation and only seeing the series they contributed to is not that helpful.

I guess that situation is much rarer for other metadata like publisher. These are more uniform for all books in a series.

**Comment by gotson** [comment]
Publisher is a series level field, so books don't have a publisher. So it can't happen at all.

**Comment by gotson** [comment]
Could i rephrase your request as: "I would like to be able to find BOOKS authored by specific people" ? And this is mostly a cover artist problematic, correct?

**Comment by Kussie** [comment]
It could also be when clicking on an author chip, rather then going back to the series or book list with the author clicking being a selected filter.  Perform a search for that author and show the search results page instead.

**Comment by gotson** [comment]
That's what i want to clarify indeed. Right now the search results screen does not support search by anything else than a search string.

I want to clarify this requirement, because it seems #432 and this issue are related, and the requirement is not very clear. I want to understand the exact use case, so I can come up with the right solution, instead of a solution being requested.
