### ISSUE TITLE
[Bug] half chapters in the .zips shown before the main

### ISSUE THREAD

**Issue by zFerry98** [gotson/komga#442]
### Komga environment
- **OS**: WS2019
- **Komga version**: 0.77.3
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: Java 11.0.9.101-hotspot
- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome 89
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Since subfolders are not supported, you need to zip the volume folders (which contain the chapter folders). The problem is that Komga reads chapters .5 (or .1 / .2 / .3 etc.) BEFORE the chapter they belong to.

### Steps to reproduce
1. Take a folder named "volume 01" which contains 5 folders named: "chapter 01", "chapter 02", "chapter 03", "chapter 03.5", "chapter 04", which will contain .jpg with pads 3-digit (000);
2. Compress the "volume 01" folder in a zip that will contain the "volume 01" folder and the various subfolders;
3. Move the "volume 01.zip" file to a komga library
4. Open the volume on the web player (chrome 89);
5. Browse to chapter 03 and find that you see the .jpg pages of chapter 03.5 before chapter 03.

### Expected behavior
See chapter 03 before 3.5

### Actual behavior
See chapter 03 after 3.5

_...it didn't seem like a bug report issue..._

**Comment by gotson** [comment]
Folders are ignored in archives, only filename is used. If you want this to work you also need to rename the files in each subfolder by prefixing them with the volume number.

For example prefix all files in volume 3 with `volume 3 -` and all files in volume 3.5 with `volume 3.5 -`.

**Comment by zFerry98** [comment]
LOL, instead of changing the rearview mirror, you make me put the American tape to keep it on...
Fortunately, the .5 is not my problem.
We consider solved that you are just a waste of time.



----------------------------------------------------------------------------------------------------------------------------------------------
https://docs.github.com/en/github/managing-your-work-on-github/creating-an-issue
![image](https://user-images.githubusercontent.com/17975351/110120469-61eac980-7dbd-11eb-89d0-cb9a15d887f9.png)
