### ISSUE TITLE
[Bug] Blank screen when loading pages

### ISSUE THREAD

**Issue by raider-com** [gotson/komga#444]
### Komga environment
- **OS**: Ubuntu 20.04.2 LTS
- **Komga version**:  v0.71.4-master
- **I am running Komga with Docker**
- Docker image tag [e.g. latest, beta]: latest
- **I have a problem in the web interface**
- Browser (with version): Chrome 64bit 89.0.4389.72, ereader custom browser

### Describe the bug
When loading books from Komga, some pages are blank/black.  Might effect every 1/100 pages, sometimes it is one single page in a book, sometimes it might be 3/4 in a row.  No commonality between pages that are effected

### Steps to reproduce
1. Open a book, start browsing through. 
2. Repeat until hit by the bug.

To fix, either full reload the page, or exit the book, and go back in.

### Expected behavior
Page should load, as the other pages do.

### Actual behavior
Black screen shows for some pages.
Console shows: net::ERR_FAILED
Nginx never receives the call.

### Additional context
- This is behind a reverse proxy with nginx (host header is what redirect to the container)
- reverse proxy config as below (tried with and without the proxy buffering.  Added that to see if that was related to the issue, seems like not)
        location / {
                proxy_request_buffering off;
                proxy_buffering  off;
                proxy_pass      http://komga:8080;
        }

### Screenshots
![image](https://user-images.githubusercontent.com/44126295/110218369-827f5600-7e87-11eb-8251-e777cbb0076e.png)

**Comment by gotson** [comment]
Please update issue title and provide some server logs.

**Comment by raider-com** [comment]
I've been messing around for about 2 weeks with this issue.  Might have found a fix for it this afternoon.
Not sure why, but this set of options so far, seems to have fixed the issue within nginx.  Not sure why.  

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

Unfortunately, there are no server logs for this issue, since not even nginx gets the calls.

Will update tomorrow, if the issue seems to remain fixed with these settings.

**Comment by gotson** [comment]
Please try without nginx. If you don't have the issue without nginx, it's not a komga issue.

If the request doesn't reach komga because of nginx, it's probably not a komga issue either.

**Comment by mrfragger** [comment]
In LTR double pages I got blank pages a lot at 1GB.  Once I started jar with 2GB it was much less frequent but still got heap memory exceptions.  Bumping it up to 3GB has solved the problem completely.

java -jar -Xmx3g komga-0.77.3.jar

**Comment by gotson** [comment]
What kind of books do you have? Cbz/r or pdf? If pdf, are teyy very big in size?

Also, please provide logs.

**Comment by raider-com** [comment]
I did a bunch more experimentation, including the upping of the RAM (thank you mrfragger).
I think I found out what is causing it.  I think it is a bug in Chromium and how it responds to http2 requests.  I don't get the issue when I use firefox.  Only with Chromium based browsers, and only with http2 enabled within nginx.  disabling http2, or using non-chromium based browsers fixes the problem.  This is really confuising to me, since none of the other containers I run through the same nginx instance have this issue.  :shrug:
Sorry to falsely report this.

**Comment by gotson** [comment]
> I did a bunch more experimentation, including the upping of the RAM (thank you mrfragger).
> I think I found out what is causing it. I think it is a bug in Chromium and how it responds to http2 requests with regards to nginx. I don't get the issue when I use firefox. Only with Chromium based browsers, and only with http2 enabled within nginx. disabling http2, or using non-chromium based browsers fixes the problem. This is really confuising to me, since none of the other containers I run through the same nginx instance have this issue. 🤷
> Sorry to falsely report this.

Thanks for posting clarifications. I did some digging up about HTTP/2 within Spring Boot, and it is not enabled by default. Even if it was, `h2c` (HTTP/2 over cleartext, so without SSL/TLS) cannot be enabled just by configuration, and needs code change.

However, your reverse proxy should be smart enough to understand that the server behind is not using HTTP/2, and should be doing the downgrade of the connection automatically, at least that's the case with Caddy.

I'll close the issue, please reopen or open a new one if you have another problem.

**Comment by raider-com** [comment]
in nginx's configs, this seems to have fixed the issue without turning off http2
proxy_http_version  1.1;
