### ISSUE TITLE
[Feature Request] Interprete accents in search and sort

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#446]
### Is your feature request related to a problem? Please describe.
When I use the search function and i'm looking for a book with accent it canno't fin it if I don't write the accent.

For exemple 
I search "Batman : Noel" no results but "Batman : Noël" work with correct accent.
Same, if I'm looking for the serie "Âge d'or", it can't find it if I write "Age d'or".

Moreover, it's not sorting correctly words with accents.
For exemple : the serie  "Âge d'or" is at the end (after Z words) and should be at the beginning with A words.

### Describe the solution you'd like
It would be nice to be able to search for a word without writing accents (especially with keybord without the good ones, rare ones).

Same for the sort, a letters with an accent should be consider the same than without. (In series/ book list but also in the filter list on the right)

Thanks for the great job!

**Comment by gotson** [comment]
Duplicate of #24
