### ISSUE TITLE
[Feature Request] Add Page size for 1000

### ISSUE THREAD

**Issue by Nexyssify** [gotson/komga#448]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Add Page size for 1000.

**Comment by gotson** [comment]
Not sure to understand, can you clarify what this is about, and provide screenshots if possible?

Also, motivations?

**Comment by Nexyssify** [comment]
Hey, 

I have more than 500 comics and wanted to show all in one page :-). For now I change the 'pagesize' cookies but i things this will be good for other people and mobile devices. 

![Capture d’écran du 2021-03-11 08-50-42](https://user-images.githubusercontent.com/4687266/110753481-ec607c80-8246-11eb-8cb1-6a814ecb6214.png)

**Comment by gotson** [comment]
Displaying more than 500 is most likely to kill your browser's performance. Chrome on Android is particularly sensitive, and displaying too many items will freeze the browser.

500 is already plenty :)

**Comment by Nexyssify** [comment]
Ok, thanks to concidering my request ;-)
