### ISSUE TITLE
Add metadata for a bunch of volume in a serie

### ISSUE THREAD

**Issue by Ludo9743** [gotson/komga#453]
### Is your feature request related to a problem? Please describe.
One problem I have when manually adding metadata is that I can't edit the metadata for an entire series.

### Describe the solution you'd like
I would like, if it's possible, to apply, for example, the synopsis of a series to all the volumes at once, especially with the scriptwriter, the designer and the tags. Often, in manga, the same people are in charge of a complete series. For example if I take Naruto, I don't want to apply to the 72 volumes, the name of the author and my tags. It would be appreciate to add the possibility to apply this modification to the number of volumes that we want. Maybe in adding a button "Apply to all".

### Describe alternatives you've considered or other apps that can do what you want
Add an "Edit" button that allows to make a selection of the volumes we want to modify at once.

Thank you for all you work.

**Comment by gotson** [comment]
> the synopsis of a series to all the volumes at once

What's the point of that ? Each book has a different synopsis, and the series has its own.

> scriptwriter, the designer and the tags

You can already edit multiple books at the same time

**Comment by grim7reaper** [comment]
> You can already edit multiple books at the same time

But some series have a lot of volumes (or chapters, for Webtoon) and this requires a lot of click to select them all.
Sure, you can script it with the API but it's a bit overkill for such a basic tasks (set the same author on every book/chapter of a series).
But there is already https://github.com/gotson/komga/issues/291 for that.

**Comment by Ludo9743** [comment]
Hi gotson!

Yes, you're right, each book has its own synopsis and the series has a global one indeed. Nevermind.

For the writer and the artist, you say that we can already modify several books at the same time? Can you tell me how, because I haven't seen this possibility?

Thank you.

**Comment by gotson** [comment]
> Hi gotson!
> 
> Yes, you're right, each book has its own synopsis and the series has a global one indeed. Nevermind.
> 
> For the writer and the artist, you say that we can already modify several books at the same time? Can you tell me how, because I haven't seen this possibility?
> 
> Thank you.

When you hover a card (series or book or other) you will see a selection ring in the top left. Click it, and it will enable multi selection. A toolbar at the top will appear where you can perform actions on all selected items at once.

**Comment by gotson** [comment]
Note also that the series will display aggregated information from its books. So if your end goal is to display the writer / artist on the series page, then you only need to add the authors on any book, and that will work.

**Comment by Ludo9743** [comment]
OMG! Sorry, I really didn't notice that the feature already exists. I didn't pay attention to the purpose of the circle on the top left of each volume. This is exactly what I wanted.

Thank you.

**Comment by gotson** [comment]
I'll close this then 😉
