### ISSUE TITLE
[Bug] Tagging for a mixed series directory

### ISSUE THREAD

**Issue by akiracuracao** [gotson/komga#454]
### Komga environment
- **OS**: Debian (Docker)
- **Komga version**: v0.71.4-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
I have a "Graphic Novels" directory with multiple unrelated comics. Komga sees them as a series and attempts (with bad results) to tag them. Is there a "magic directory name" that I can use for directories with mixed content in terms of titles?

### Expected behavior
Recognize the titles within the directory as unrelated or the ability to exclude the directory from tagging.

### Actual behavior
Comics labeled incorrectly.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

**Comment by Kussie** [comment]
Your best way around this right now will require you to change your file structure.  Best way for Komga is

- Library root folder
— Series Folder
—- Book files

Reorganizing your files into this layout should solve your problem, though it will probably be a bit of a pain.  Could script it or Filebot might even work for it.

Though it could be a feature Gotson may look at in the future.  Perhaps a toggle when creating a library that could flag Komga to treat all files in the library as stand alone.  But that starts to get complicated.

**Comment by gotson** [comment]
> Komga sees them as a series and attempts (with bad results) to tag them.

What do you mean by that ? What does "tagging" mean for you ?

> Comics labeled incorrectly.

What does that mean exactly ?

---

Can you please clarify what is your problem ? The description you gave is vague and unhelpful to understand the problem. Please provide screenshots to clarify.
