### ISSUE TITLE
Replace cookie storage by localstorage

### ISSUE THREAD

**Issue by gotson** [gotson/komga#456]
Cookies are sent with every request, which is inefficient. Local storage should be used instead.

**Comment by Kussie** [comment]
Just be ware there is some issues with local storage.  Granted they shouldn't be an issue for most use cases.  But the biggest issue i have come across with local storage is in Private Browsing mode in Safari.  The browser reports that local storage is enabled and available, but you are unable to actually write anything to it and when attempting to do so it will cause an error.  

Thankfully if you use a library/package to handle the writing to local storage (One that can naturally fallback to cookies if it cant use local storage) should work around the issue depending on the package.

**Comment by gotson** [comment]
thanks, i will do some tests in private/incognito mode to make sure that doesn't crash. However, if you are running on incognito, and local storage is not available, it makes sense not to store anything. I don't want to fallback on cookies for that reason.

**Comment by Kussie** [comment]
It would appear this issue has actually been fixed for a while :) We were still still running into it because we had to support older iOS devices that no longer received updates, which included this particular fix.
