### ISSUE TITLE
[Bug] Chips editors and cover at book level

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#457]
### Komga environment
- **OS**: qnap
- **Komga version**: v0.79.1

### Describe the bug
Since v0.79.1, editors and cover are not available at serie level. And when I use the chip (at book level), it only filter on the actual book serie  and not on all the library like it used to be when I clicked on chips at serie level.

### Steps to reproduce
1. Go to a book
2. Click on chips
->the filter is on the book serie

1. Go to a serie
2. Click on chips
->the filter is on the library

### Expected behavior
I see 2 options, change the behaviour to filter on all the library and not only the actual serie.
Or show again Cover and Editors at serie level.

ps : I don't know if it's a bug or an expected feature.

Thanks for the great job.

**Comment by gotson** [comment]
> Since v0.79.1, editors and cover are not available at serie level

That's a feature. All those authors were bloating the Series page.

> And when I use the chip (at book level), it only filter on the actual book serie and not on all the library like it used to be when I clicked on chips at serie level.

Nothing new there, it was always like this.

---

What you are meant to say is that you can't search by authors from a series, for roles that are not writers/pencillers, by clicking on the chips. That's correct. Use the filter panel in that case, or wait for #432

**Comment by Kiwi-13-plo** [comment]
Thanks for the quick answer. 

> What you are meant to say is that you can't search by authors from a series, for roles that are not writers/pencillers, by clicking on the chips. That's correct. Use the filter panel in that case, or wait for #432

Yes that what I meant.  When using the panel it's working well ! (just not as friendly that chips)
I wiil wait for #432 :)
