### ISSUE TITLE
[Bug] Filter Options initially unavailable

### ISSUE THREAD

**Issue by KyleWayneLaCroix** [gotson/komga#458]
### Komga environment
- **OS**: Windows
- **Komga version**: v0.71.0-master

- [x] **I am running Komga from the `jar`**
  - Java version: 8.281
- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome and Firefox (both latest version)

### Describe the bug
Every filter except unread and status is greyed out and unselectable until I toggle one of those two options, then every other filter begins to work. This happens every time.

Screenshots:
![image](https://user-images.githubusercontent.com/6764562/111856806-44f4e100-88fb-11eb-81b0-749fddae0196.png)
![image](https://user-images.githubusercontent.com/6764562/111856813-5211d000-88fb-11eb-8ea7-4b9f71f0d737.png)

**Comment by gotson** [comment]
Please indicate your komga version, and provide screenshots or video of the symptom.

**Comment by KyleWayneLaCroix** [comment]
Updated initial report with requested information.

**Comment by gotson** [comment]
Please update to the latest version, this should have been fixed already.
