### ISSUE TITLE
[Feature Request] Add a sort option in library for number of books in a series

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#459]
### Is your feature request related to a problem? Please describe.
When viewing a library i would love to be able to sort the list by the number of books a series has.

### Describe the solution you'd like
An additional sort option would be nice, Sadly it would appear the API doesn't appear to support sorting by `booksCount`

**Comment by gotson** [comment]
There's a mapping to be done in the Dao between the name passed in the sort options and the database column.
