### ISSUE TITLE
Request: Don't separate subfolders into their own series

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#46]
The typical library folder structure looks like this:

```
- Manga
-- Naruto
--- Volume 1
--- Volume 2
--- Volume 3
...
-- One Piece
--- Volume 1
--- Volume 2
--- Volume 3
...
```

Komga displays each folder in a library as its own series just like Ubooquity. So far so good.

![vivaldi_2020-01-01_21-56-55](https://user-images.githubusercontent.com/44198148/71646062-affbcd00-2ce1-11ea-8463-692a3f971bb9.png)

The problem is that Komga does not honor the folder structure of folders that have one or multiple subfolders. For example, the manga Kaiji has several parts which are separated into different subfolders like this:

```
- Manga
-- Kaiji
--- 01. Part 1
---- Volume 1
---- Volume 2
---- Volume 3
...
--- 02. Part 2
---- Volume 1
---- Volume 2
---- Volume 3
...
```

Instead of displaying Kaiji as one series with one folder icon and showing you the five subfolders when you click on the icon the way Ubooquity does it, each subfolder is displayed as if it were its own series in the library overview:

![vivaldi_2020-01-01_22-13-47](https://user-images.githubusercontent.com/44198148/71646192-46c98900-2ce4-11ea-8092-91a45593fa09.png)

This leads to a messy overview, especially if you have multiple series with subfolders:

![vivaldi_2020-01-01_22-18-30](https://user-images.githubusercontent.com/44198148/71646210-a58f0280-2ce4-11ea-9194-2fe6055f7be9.png)

**Comment by gotson** [comment]
You can prefix the intermediate folder with the name of the series, for example replace `01. Part 1` with `Kaiji - Part 1`.

---

This is a design choice, the hierarchical structure of a file system is not adapted to represent the multiple dimensions of the various metadata books can have. Every people will want to have their folders in a different way, so it will never work for everyone.

Regarding your particular manga, it could be considered as different series from what i gather from [Wikipedia](https://en.wikipedia.org/wiki/Kaiji_(manga)#Manga), as they don't even have the same title.

Then you may wonder how to visualize those 6 different series together, since they are part of the same "universe". That's where Collections could help (see #30).

**Comment by whalehub** [comment]
@gotson Thanks, that solution works for me.

![vivaldi_2020-01-02_15-17-51](https://user-images.githubusercontent.com/44198148/71671348-2694db00-2d73-11ea-811a-97ddb65e9d5e.png)

**Comment by jfml** [comment]
Hi, I'm struggling with this, is there documentation on how this works? I can't even replicate the solution pointed to above:

![Screen Shot 2020-01-07 at 17 52 41](https://user-images.githubusercontent.com/4312909/71913073-eec4d380-3176-11ea-9e35-13ec14096d5f.jpg)

Leads to:

![Screen Shot 2020-01-07 at 17 52 57](https://user-images.githubusercontent.com/4312909/71913093-fa17ff00-3176-11ea-97a3-2cd325ea761a.jpg)

Shouldn't it just become one series called `Kaiji`?

**Comment by gotson** [comment]
> Shouldn't it just become one series called `Kaiji`?

No. Each folder is a series. If you want to have books in the same series, but them in the same folder.

Documentation here: https://github.com/gotson/komga#what-does-it-do

**Comment by jfml** [comment]
Ok.

So just to clarify in case someone else is as slow on the update as me: 

**Every folder** with a cbr/cbz/zip inside it will be made a `Series` no matter where in your folder-structure it is buried (or if there are other subfolders with more files inside it (which in turn will again be made a `Series`)). 

Folder with one ore more files inside it = `Series`.

Coolio.

**Comment by gotson** [comment]
@whalehub I just added `Sort Title` for series, so  now you can use that to see series grouped together, even if the title is very different, without changing your folder names. It's available in the series edit dialog.

**Comment by whalehub** [comment]
@gotson Thanks!
