### ISSUE TITLE
[Feature Request] Strip or parse windows style line breaks in summary

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#460]
### Is your feature request related to a problem? Please describe.
At present if Komga imports a summary that has line breaks you end up with them being output as text instead of actual line breaks in the web reader.

### Describe the solution you'd like
They could be run through a simple function that converts `\r\n` and `\n` to `<br />` tags

![Screenshot 2021-03-13 19 18 17 (2)](https://user-images.githubusercontent.com/4960791/111025624-052c8600-8431-11eb-8ea5-e8476aff13b6.png)

**Comment by Kussie** [comment]
https://github.com/gotson/komga/pull/461

**Comment by gotson** [comment]
The actual question is why are there line breaks in the data you import? Where is it coming from?

**Comment by Kussie** [comment]
It’s coming from where the books are sourced (which is mostly MangaDex) and then directly from the ComicInfo.xml (which has actual line breaks and not just plain text \r\n)

It is probably better suited to be handled on display IMO.  Which would allow for multi line text or be displayed correctly depending on where it’s being shown, HTML/web versus app for example which most of the time should be able to handle line endings naturally however when it comes to web that won’t be the case.  Any line breaks would be lost on the web reader. The other option would be to wrap the summary in ‘<pre>’ tags.

**Comment by gotson** [comment]
Line breaks are not lost, and displayed correctly on the web ui. You can test by editing a summary manually and adding line breaks.

For ComicInfo it should probably be converted at import time.

For mangadex it's added via the api, so should either be managed by the writer or the script, or the api.

There's no reason to store platform specific line ends, because else each client would need to have its own logic to replace the various possible line ends at display.

**Comment by Kussie** [comment]
So is the issue purely because it’s got windows style line endings instead of Unix style ones? (\r\n vs \n)

**Comment by gotson** [comment]
Could you provide the faulty comicinfo.xml maybe?

**Comment by Kussie** [comment]
It's not just one or two, it's every ComicInfo.xml for me that has line breaks in it.  But I've attached the one from the screenshot above

Sadly had to zip it because GH doesn't allow XML attachments
[ComicInfo.zip](https://github.com/gotson/komga/files/6134745/ComicInfo.zip)

**Comment by Kussie** [comment]
As discussed in Discord, unable to replicate and may just be old data possibly
