### ISSUE TITLE
[Feature Request] Additionnal Series & Books metadata 

### ISSUE THREAD

**Issue by bdjPenguin** [gotson/komga#466]
I'm used to scrapping my book from online sites (mainly a french one ;)). 
After retrieving those data using my own dirty python scripts, I'm importing the data in Komga using the REST API.
Unfortunately, I can't import all of them. 
The ISBN was one of them solved recently.
It would be great if Komga would offer a way to store the following type of additional metadata:

By priority, for the books:
 - Rating: Initiate the rating from the online source (eg: 3.2/5) (linked with the #58 )
 - URL: Possibility for a link to an external website (a clickable url), link to the scratched sources for example.
 - Origin:  region of the world for the book origin (France, Asia,...)
 - Format: size of the page (Format normal, 
For those two last points, maybe a more generic system could be possible by allowing the creation of 'Key':'Value' pairs on demands. This would offer a flexible approach to allow extensions.

By priority, for the series:
 - URL: Possibility for a link to an external website (a clickable url), link to the scratched sources for example.
 - Number of published albums: Not the number of albums in the library, but the one really published.
 - Origin (similar to the books)
 - Period: dates of publication (from - to)
Same remarks as for the books, the two last could be implemented in a generic way by a key:value approach.
 
For information, before the implementation of the translation, I was 'hacking' the author's list to introduce 'roles' not existing by default.  I add a screenshot of the result, that was not perfect (URL unclickable for example), but it doesn't look bad.
![image](https://user-images.githubusercontent.com/80747293/111282428-4645b580-863e-11eb-91ca-c457757ac71b.png)
Maybe this could give some ideas for the implementation.

**Comment by gotson** [comment]
> * Origin:  region of the world for the book origin (France, Asia,...)

This can be achieved using tags. You could add tags `Origin:France`, `Origin:Asia`.

> * Format: size of the page (Format normal,

You can also use tags here.

> * Number of published albums: Not the number of albums in the library, but the one really published.

This is already requested in #298 

> * Period: dates of publication (from - to)

This is not required. If you have books which have their publication date, then the publication range of the series can be computed by the ones from the books. The oldest and most recent.

> For information, before the implementation of the translation, I was 'hacking' the author's list to introduce 'roles' not existing by default. I add a screenshot of the result, that was not perfect (URL unclickable for example), but it doesn't look bad.

The backend does not limit authors, as you've experienced, but at the moment the frontend does.

**Comment by gotson** [comment]
You should also have a look at https://github.com/anansi-project/rfcs and contribute if you think something is missing!
