### ISSUE TITLE
[Feature Request] Add "Download current page" button in the web reader UI

### ISSUE THREAD

**Issue by frameset** [gotson/komga#469]
I would like a simple button in the web reader UI to allow the downloading of the current page. This would be handy for sharing panels or pages after downloading.

It is currently possible to grab the page using the API, or by using the browser inspector to get the image.

I understand if you feel this might clutter the UI too much though.

**Comment by MaestroJAL** [comment]
This new feature seems to not honor turning off the "File Download" option under users. Users who are supposed to not be able to download files can download each page one by one.

**Comment by gotson** [comment]
If you can stream the pages you can download one by one via the api. File download is only to download original files. Please don't comment on closed issues.
