### ISSUE TITLE
[Bug] Komga no longer generates covers

### ISSUE THREAD

**Issue by Darkwolf1515** [gotson/komga#471]
### Komga environment
- Synology
- 0.81
  - Docker image tag: latest

### Describe the bug

Ever since updating to 0.82, I have been unable to scan new images in, I have even tried a fresh install, nothing.
### Expected behavior
Images to appear

### Actual behavior
No images

### Screenshots
![image](https://user-images.githubusercontent.com/65789901/111449855-037eee80-86cd-11eb-9ae8-e8f34757f5a4.png)

**Comment by gotson** [comment]
Can you elaborate? What happened to your existing library after upgrading? Which version were you running before? Can you attach some logs?

**Comment by Darkwolf1515** [comment]
The existing library kept its images, but new ones would not generate, 0.79, 
[komga.log](https://github.com/gotson/komga/files/6159399/komga.log)

**Comment by Darkwolf1515** [comment]
Left it overnight, no change, made a whole new container and left it for awhile and now it seems fine. Ill close it for now since im no longer effected by it, but I have no idea what I did to fix it.

**Comment by gotson** [comment]
> The existing library kept its images, but new ones would not generate, 0.79,
> [komga.log](https://github.com/gotson/komga/files/6159399/komga.log)

Was that the log of the upgrade, or the log of the new container?

**Comment by Darkwolf1515** [comment]
Log of container 2, which was not upgraded, but it also did not work.

**Comment by gotson** [comment]
it's weird because it shows that it's applying all the database migrations since the H2 to SQLite migration, which was done in `0.48.0` IIRC.
