### ISSUE TITLE
[Feature Request] Add "Search for new chapters"

### ISSUE THREAD

**Issue by Grimstonsd** [gotson/komga#472]
### Is your feature request related to a problem? Please describe.
The problem is when a manga has many chapters it can take an hour for new chapters to appear

### Describe the solution you'd like
So the best solution would be to add an option to search only for new chapters

**Comment by gotson** [comment]
You don't seem to understand how Komga works. Have a good read at the [documentation](https://komga.org/guides/scan-analysis-refresh.html) first.
