### ISSUE TITLE
[Feature Request] Collection custom thumbail

### ISSUE THREAD

**Issue by IoneGregH** [gotson/komga#473]
Series thumbnails can be customized by putting in a folder.jpg file in the series folder.  But since there's no Collection folder there's currently no way to use a custom thumbnail for Collections.

I would like to have an option in the Edit Collection screen to upload a custom thumbnail or use a image URL, similar to what Plex does for Collections.

Thank you

**Comment by gotson** [comment]
_Please use the issue templates, they are here for a reason._

Kind of linked to #194
