### ISSUE TITLE
[Bug] Reader doesn't mark as watched when book has one page

### ISSUE THREAD

**Issue by FallenGuardian** [gotson/komga#475]
### Komga environment
- **OS**: Windows 10
- **Komga version**: v0.82.0
- [x] **I am running Komga from the `jar`**
  - Java version: Version 8
- [x] **I have a problem in the web interface**
  - Browser (with version): Firefox 86.0.1 & Chrome 89.0.4389.90

### Describe the bug
When I read a comic using the webreader which has just one page it doesn't mark as watched.

Also when using the webtoon mode when there is just one page in a chapter and you go to the next chapter it doesn't start at the beginning of the next chapter but it starts at the location the last chapter ended. For example, it starts at mid chapter.

### Steps to reproduce
1. Go to a chapter with just one page
2. Go to the next page

### Expected behavior
Mark the chapter as watched.

And start at the beginning of the next chapter when in webtoon mode.

### Actual behavior
Goes to the next chapter but doesn't mark the previous chapter as watched.

In webtoon mode it starts the chapter at the location where the last chapter ended.

**Comment by gotson** [comment]
Komga doesn't mark progress for the first page of a book. If it was the case, opening any book on the first page would mark it as in progress. Sometimes you just want to open the book to check the cover, or check the thumbnails, but not mark it as in progress.

Books of 1 page are probably a very exceptional case. You can mark it as read manually in that case.

**Comment by gotson** [comment]
Could you maybe share one of those files with a single page ? I suppose it's a webtoon with a very long image. Thanks.

**Comment by PythonCoderAS** [comment]
I ran into the same error. Re-duplicable with https://pokestarfan.ftp.sh/komga/series/04GZT1KZTXEVA. (user: guest@example.com; pass: guest)

**Comment by gotson** [comment]
> I ran into the same error. Re-duplicable with https://pokestarfan.ftp.sh/komga/series/04GZT1KZTXEVA. (user: [guest@example.com](mailto:guest@example.com); pass: guest)

That's unreachable. Would you be able to post the file on any temp file share maybe?

**Comment by PythonCoderAS** [comment]
@gotson Try this: https://drive.google.com/drive/folders/1Ov-n1R-CbQBPwUpLNMlUUWZBidPcc_4L?usp=sharing

**Comment by gotson** [comment]
Looks like it also breaks the paged reader, showing twice the same page.
