### ISSUE TITLE
[Feature Request] Collections displayed in home page

### ISSUE THREAD

**Issue by moisesbelda** [gotson/komga#482]
### Is your feature request related to a problem? Please describe.
No, it is not a problem

### Describe the solution you'd like
Currently, the access to collections screen, you need to go to the Library, and inside the library screen , the top bar option Collections. It will be more accesible and nice to have the collections displayed in the home screen.

### Describe alternatives you've considered or other apps that can do what you want
If it is not possible the solution described before, a possible alternative will be to have a link to collections in the home screen.

### Additional context
Thanks and Congratulations for this amazing app.

**Comment by gotson** [comment]
What's the "home screen" for you? Are you referring to the dashboard showing the recently added books etc?

**Comment by moisesbelda** [comment]
Yes, this is called home, no?

**Comment by gotson** [comment]
It's referenced as the dashboard, but that's fine, thanks for clarifying.

That screen is not for browsing, but to show recent items or items of interest (keep reading, on deck..).

If you are primarily browsing via collections I think you would be interested in #190

**Comment by moisesbelda** [comment]
I usually share my comics collection with some colleagues. 

Since my wat to organize comics is based on collections, I have to specify to each one "go to comics library, and then go to collections in the top bar", it is not a problem of course, but I think it will be more clear if the there will be a direct link to collections in the first screen.

Or maybe in the side bar. I think calibre-web has a similar feature.

Thanks

**Comment by gotson** [comment]
In that case #367 should fit the bill. You would click on Libraries and be taken to collections directly.

**Comment by gotson** [comment]
Side bar is not relevant, collections are dependant on Libraries. If you explore collections from one library or another, or from all libraries, you don't see the same thing.

I'll close this in favor of #367
