### ISSUE TITLE
[Feature Request] Sending nofication and monitor users reading 

### ISSUE THREAD

**Issue by mouzzampk2014** [gotson/komga#486]
### Is your feature request related to a problem? Please describe.
Sending notification to admin when someone start reading anything from Komga with date, time, title, username and would be great if this includes device name. 

### Describe the solution you'd like
Apprise support/includes very large of notification providers and i think adding this will be a great feature. Apprise dev also very active and more important very friendly and has its own discord.

### Describe alternatives you've considered or other apps that can do what you want
Hydra2 recently integrated apprise, but tautulli utilise plex api to monitor user usage and send notification. 

### Additional context
N/A

Thank you

**Comment by gotson** [comment]
That would mean one notification for every page read? That's probably a bit too much.

**Comment by mouzzampk2014** [comment]
> That would mean one notification for every page read? That's probably a bit too much.

No I meant only when someone open the book/comics and at that time komga trigger the notifications

**Comment by gotson** [comment]
What do you mean by "open the book" ?

**Comment by mouzzampk2014** [comment]
> What do you mean by "open the book" ?

Basically we have mylar, tautulli or any other service. So in case tautulli when user play a video it send notification to admin with all the details. 

Same with komga if any user start reading comics/book then it trigger thr notification. 

One of the thing about tautulli is you get notification about users ip so in case someone start sharing their details with someone else and then you can remove or limit the user with on single ip.

Its more of a control feature.

**Comment by gotson** [comment]
You didn't answer the question.

There's no such thing as opening one book in Komga. You can access pages of any number from any book in an api call. There's no easy way to know if someone is reading one book, or accessing a single page. It's completely different from a video server like Plex.

**Comment by mouzzampk2014** [comment]
I think answer it here
```Same with komga if any user start reading comics/book then it trigger thr notification.```

This was just a thought. Its a first time I'm sharing any of my collection with anyone so just thinking about all these little features. But if its difficult to implement or no easy way then definitely we can close this feature :)
