### ISSUE TITLE
[Feature Request] artwork / background for series and books 

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#487]
### Is your feature request related to a problem? Please describe.
At the moment the background in the series view is empty.
It would be nice like in emby or kodi to have background pictures.

Actual:
![Screenshot_2021-03-28 Komga - Test](https://user-images.githubusercontent.com/76835223/112768461-7ddc3680-901c-11eb-9cf0-6d7c1fa1e5f2.png)

Future:
![Komga_Backround](https://user-images.githubusercontent.com/76835223/112768491-92b8ca00-901c-11eb-8c58-8013f3a93428.jpg)

### Describe the solution you'd like
It should be possible to store a file in every directory which can use as background picture.
names could be:
background.jpg
artwork.jpg

### Describe alternatives you've considered or other apps that can do what you want
It could also a solution to have an upload function to drag&drop the picture.

### Additional context
Maybe in future is a function to rotate the pictures :-)

**Comment by AniUrbz** [comment]
I apologize in advance for opening a closed thread but this seems to me a feature that would give a great design to the content you have in the library.

I made a mockup of how it could be done, using a gradient that goes from the color of the theme being used (either dark gray or white) and reduce the opacity to 50% to hide part of the background image.

![batman](https://user-images.githubusercontent.com/83618189/136307115-d20e1614-0fa0-407e-87d2-30f155497821.png)

![batman1](https://user-images.githubusercontent.com/83618189/136307097-48c8a8fa-66d6-44ae-9688-279ed5e68dcb.png)
