### ISSUE TITLE
[Feature Request] Add feature to search by library in ODPS

### ISSUE THREAD

**Issue by edwinbadillo** [gotson/komga#491]
### Is your feature request related to a problem? Please describe.
Using Komga with different libraries for Comics, Manga and Books which might have series with the same title.

### Describe the solution you'd like
Have a search feature in ODPS per library that way there isn't an overlap between the same series title in each library. 

### Describe alternatives you've considered or other apps that can do what you want
Prefixing series name with "(Comic)" or "(Novel)" if I know they have an alternative source.

### Additional context
For web there should probably be some indicator in the web ui search results to know on which library it was found in. But that would be a different request all together.

**Comment by gotson** [comment]
What is your opds client? Opds does have ways of refinining search or search results but it's not supported by all clients.

**Comment by edwinbadillo** [comment]
Marvin 3 (iOS). I see, in my case there is no search anywhere except the main catalog page and no refinement options. Could very well be the implementation here on the app side then.

**Comment by gotson** [comment]
Unfortunately it doesn't really support search nor facets.

https://github.com/Feedbooks/opds-test-catalog/wiki

**Comment by marek-lach** [comment]
Related to #497 .
