### ISSUE TITLE
[Bug] referential data is not filtered by access rights

### ISSUE THREAD

**Issue by DragonBolta** [gotson/komga#492]
### Komga environment
- **OS**: Windows 10, Android 11
- **Komga version**: 0.83.0
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: Version 8 Update 271 (build 1.8.0_271_b09)
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [X] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: r3185
  - Tachiyomi extension version: 1.2.23

### Describe the bug
Genres from libraries the user does not have access to are not hidden.

### Steps to reproduce
1. Set up the extension with an account with restricted access to libraries.
2. Check genres in the filter.

### Expected behavior
Genres not present in libraries the account has access to do not appear.

### Actual behavior
Genres not present in libraries the account has access to appear.

### Additional context
Not sure if this was supposed to be a bug or feature request.

**Comment by gotson** [comment]
This is true for all referential data, so authors, tags, genres etc. It should be filtered by the libraries accessible by the user.
