### ISSUE TITLE
[Bug] Error importing reading list with non-numerical number

### ISSUE THREAD

**Issue by Kiwi-13-plo** [gotson/komga#499]
### Komga environment
- **OS**: on QNAP
- **Komga version**: 85.1

### Describe the bug
I'm trying the list import functionnality and got some issues "Error while deserializing ComicRack ReadingList".
After several trials with just some book, it's seems the issue is when the book number is not real number like INT,HS1,...
I don't know if it's a bug or not?

### Steps to reproduce
1. Try to import a reading list with a book with number INT

### Expected behavior
Be able to import all kind of book number.

### Actual behavior
"Error while deserializing ComicRack ReadingList"

**Comment by gotson** [comment]
Was this `.cbl` file generated by ComicRack ? Can you provide it ?

**Comment by Kiwi-13-plo** [comment]
[ComiRack.zip](https://github.com/gotson/komga/files/6283522/ComiRack.zip)
Two file, one working and the other one not.
