### ISSUE TITLE
Sorting/Collation uses accent sensitive order which is not a good default for international use

### ISSUE THREAD

**Issue by thampp** [gotson/komga#500]
### Komga environment
- **OS**: Linux on Synology NAS
- **Komga version**: v0.86.0-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [x] **I have a problem in the web interface**
  - Browser (with version): I use Chrome but this should occurs in all browsers.

### Describe the bug
Sorting/Collation uses accent sensitive order in all places I checked (series sorting, book sorting, filter value sorting).
Strictly speaking this is not a bug. Binary sorting (what used to be called ASCII sorting in pre-Unicode days) is a well defined sorting. No single collation order is perfect for all countries and cultures. But for a product that manages Comic with relevant contributions from countries like France and Japan the default collation order could better match sorting expectations for most countries.
- It looks like the default collation is **case insensitive**. In my opinion is a good match.
- In my opinion the default collation should uses **accent insensitive** sorting. 
- For Japanese I think the default should be **width-insensitive** and **Kana-insensitive** (but I am not a native speaker).

Some SQL sources support collations that allow to specify this:
https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15

### Steps to reproduce
Just enter a series name, book name or author name in regular and in an accented form e.g. "Eric" and "Éric".

### Expected behavior
They should be sorted next to each other.

### Actual behavior
Accented variant is sorted at the end

### Additional context
Ideally the collation order is something that can be configured separately.
In theory collation could be changed with the UI language. But that may not be practical: Often there is more than one collation variant for a given country/language. 
But even for English/default language the default collation order should better be accent-insensitive and width-insensitive and Kana-insensitive. So per-language settings are not an either/or but another level of collation support. One reasonable default collation may be absolutely sufficient.

### Screenshots
Authors with accents sorted last instead of next to the unaccented variants
![image](https://user-images.githubusercontent.com/13353725/114558300-d0e3f980-9c6a-11eb-9b0f-954d52a38e1c.png)
Series with accents sorted last instead of next to the unaccented variants
![image](https://user-images.githubusercontent.com/13353725/114558431-f53fd600-9c6a-11eb-98f1-c07a4c127a40.png)

**Comment by gotson** [comment]
Komga is using SQLite, which comes with only [limited collation](https://www.sqlite.org/datatype3.html): `BINARY`, `NOCASE`, and `RTRIM`. The Android version does come with `LOCALIZED` and `UNICODE` collation though.

At the moment i don't know how to define or add new collations with the current setup (Sqlite > JNI > JDBC > jOOQ).

Series have a `sort title` field to handle such cases (and others). By default, the accents will be stripped when creating a Series from its folder name. If you modify the `sort title` manually and add accents, then it will sort using the accents.

Books are sorted by their `sort number`.

For Authors and other referential data like Publishers, Genres, Tags, indeed it doesn't work.

> Ideally the collation order is something that can be configured separately.
> In theory collation could be changed with the UI language.

Collation of the data within Komga and the UI language is unrelated. You may have Japanese books, but be a French speaker, in which case the collation depends on the data, not the display language.

The Unicode collation may be the best bet, but i haven't tested it.

**Comment by thampp** [comment]
Just tried out the new version with the enhancement. Works like a charm. 
Thank you very much for this!
