### ISSUE TITLE
[Bug] JMS Connection Cannot connect to server(s)

### ISSUE THREAD

**Issue by LadghemSaid** [gotson/komga#501]
### Komga environment
- **OS**:  Ubuntu 18.04.5 LTS
- **Komga version**: gotson/komga:latest
- [ ] **I am running Komga with Docker**
  - Docker image tag [latest]: 

### Describe the bug
The docker container is consuming a lot of ram on my server even when idle (and not analysing)

### Steps to reproduce
1. Docker compose up -d

### Expected behavior
It should be doing nothing when idle and not using 20% of my cpu

### Actual behavior
The docker container is consuming a lot of ram on my server even when idle (and not analysing)

### Additional context
Im using a reverse proxy nginx by jwilder to expose the application (on the port 8080)
ihave no issue accessing the front app
Here is my docker-compose file :
` komga:

    image: gotson/komga:latest
    container_name: komga
    volumes:
      - type: bind
        source: ./config/komga/
        target: /config
      - type: bind
        source: /var/www/media_center/data/mangas
        target: /books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    expose:
      - ${PORT_KOMGA}
    user: "${UID}:${GID}"
    environment:
      LETSENCRYPT_HOST: ${URL_FRONTEND_KOMGA}
      VIRTUAL_PROTO: http
      VIRTUAL_HOST: ${URL_FRONTEND_KOMGA}
      KOMGA_REMEMBERME_KEY: ${KOMGA_COOKIE_KEY}
    restart: on-failure:5
    networks:
      - nginx_main`

### Screenshots
![image](https://user-images.githubusercontent.com/39403972/114713972-f12abb80-9d31-11eb-9ec4-56392a1ede5e.png)

### Log file
Here is the error looping :
 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'tasks.background' - retrying using FixedBackOff{interval=5000, currentAttempts=273, maxAttempts=unlimited}. Cause: Failed to create session factory; nested exception is ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]

**Comment by gotson** [comment]
Please provide complete log file.

**Comment by LadghemSaid** [comment]
Nevermind it was related to my proxy configuration, thanks you for the fast answer and for maintaining this good project !
