### ISSUE TITLE
[Bug] Full House Keeping for every library scan

### ISSUE THREAD

**Issue by japeberg** [gotson/komga#502]
### Komga environment
- **OS**: Ubuntu 20.04.1
- **Komga version**: v0.86.0-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
After starting a library scan on a small library (5 files) Komga starts "House keeping thumbnails for series: XYZ" for seemingly all series in all libraries on the server. This leads to running my home with 100% load with performance issues for Komga itself (slow loading speed in the webUI, hangups while trying to open/convert a file)

### Steps to reproduce
1. Starting a library scan for a specific library

### Expected behavior
Complete Scan of the specific library

### Actual behavior
Full scan of every series on the server, regardless of corresponding library.

### Log file
 
> 2021-04-14 18:32:38.271  INFO 1 --- [o-8080-exec-170] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:38.275  INFO 1 --- [o-8080-exec-171] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.168  INFO 1 --- [o-8080-exec-170] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.297  INFO 1 --- [o-8080-exec-173] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.298  INFO 1 --- [o-8080-exec-157] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.311  INFO 1 --- [o-8080-exec-172] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.340  INFO 1 --- [o-8080-exec-174] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>
> 2021-04-14 18:32:39.391  INFO 1 --- [o-8080-exec-155] o.g.k.domain.service.SeriesLifecycle     : House keeping thumbnails for series: <redacted>

**Comment by gotson** [comment]
Please provide a complete log file.

**Comment by japeberg** [comment]
Could not reproduce again to get a complete log file. I will reopen this issue if the problem occurs again.
