### ISSUE TITLE
[Bug] Files seemingly deleted through import process 

### ISSUE THREAD

**Issue by cityeyes** [gotson/komga#508]
### Komga environment
- **OS**: Windows 10
- **Komga version**: 0.87.1
- [ X] **I am running Komga from the `jar`**
  - Java version: OpenJDK 11.0.8.0
- [X ] **I have a problem in the web interface**
  - Browser (with version): Edge 90.0.818.41, but I don't think it matters

### Describe the bug
I saw the "Import" dialogue and thought maybe it'd solve a few issues I was having with sorting, so I started re-importing a few series to see what it did. Got through a few problem series, then was puzzled to find they didn't exist in the library any longer. I think my first issue is that I misunderstood what "import" did, but I assumed it was simply updating files I'd already scanned in, because it said they'd be "updated" after I manually typed in the series and issue number. That said, I assume even in my use case, file deletion is a pretty extreme result. Luckily, I have my files backed up.

### Steps to reproduce
1. Click "Import" in left bar
2. Import folder that has already been scanned into the library. Hit Scan. Wait for files to validate.
3. Add series and issue numbers.
4. Keep "Hardlink/Copy Files" selected
5. Click "Import"

### Expected behavior
Either files in the library are updated, or files are copied into some central library.

### Actual behavior
All imported files were deleted from my comics server hard drive.

**Comment by gotson** [comment]
Please attach log files.

**Comment by cityeyes** [comment]
I had a 10MB log file, but narrowed it down to what looks like where the issue arose. Seems the copy/hardlink failed, but the server deleted the original fine anyway.

Obviously, I misunderstood the meaning of import, but I think something went wrong along the way anyway. Hope this helps!
[logsnippet.txt](https://github.com/gotson/komga/files/6340656/logsnippet.txt)

**Comment by gotson** [comment]
Please attach the full log file if you can.

**Comment by cityeyes** [comment]
Here's the full file that snippet came from.
[komga.log.2021-04-19.4.gz](https://github.com/gotson/komga/files/6340923/komga.log.2021-04-19.4.gz)

**Comment by gotson** [comment]
You basically tried to import a file to itself, so source and destination are the same.

I will add a safeguard to the import feature to prevent importing files that are part of a Komga library

**Comment by gotson** [comment]
version `0.87.2` will prevent such cases and add a warning on the Import screen on usage.
