### ISSUE TITLE
[Feature Request] Add dual page split mode

### ISSUE THREAD

**Issue by karlos4936** [gotson/komga#509]
Some files has two pages in one picture.

When I see books on mobile web, It's hard to see this.

So [Dual page split] mode needed.

Tachiyomi has [Dual page split] mode.

Example)

**Original**
![005](https://user-images.githubusercontent.com/12794062/115497474-b16e5180-a2a6-11eb-90cd-1194f3dc2317.jpg)

**To be**
![1](https://user-images.githubusercontent.com/12794062/115498053-c7c8dd00-a2a7-11eb-896b-90726343ba59.png)
![2](https://user-images.githubusercontent.com/12794062/115498056-c8fa0a00-a2a7-11eb-8103-439e1470b35b.png)

**Comment by gotson** [comment]
duplicate of #40

**Comment by karlos4936** [comment]
Is not possible on WebReader?

**Comment by gotson** [comment]
The issue exists already. This is a duplicate.
