### ISSUE TITLE
[Feature Request] Aggregate book tags at series level, and add ability to filter on it

### ISSUE THREAD

**Issue by donotos** [gotson/komga#513]
### Is your feature request related to a problem? Please describe.
One of my library contain books that are not meant to be series. they are single books sorted by author, so, when i want to use the filter feature it is not usable since it only filter series metadatas and i did not put metadatas on series (author folders) since it's irrelevant.

### Describe the solution you'd like
It would be great if the filter pannel in the library could search metadatas from books too.

### Describe alternatives you've considered or other apps that can do what you want
Not sure what to put here but since you can add metadatas on books you should be able to filter them across your entire library. The search bar give you result on books and series so why not filter?

### Additional context
I want to filter Tags on all the books in the library no mater in what serie they are.

Thanks

**Comment by gotson** [comment]
At the moment the way to add one shots is to put them in their own folder, so they get their own series.

**Comment by donotos** [comment]
Indeed it is the way to do it, but since it is possible to put metadata on books i think the filter should be able to use them, the same as the search bar give you results on books too. And it is possible that the books of a series could have different metadatas/tags

**Comment by gotson** [comment]
The search bar and the filter when browsing a library can't be compared. The library show series, not books.

**Comment by donotos** [comment]
I see what you mean, so if filtering is not possible how about searching like some online reader do, something like:
tag:scifi + tag:space
who would find everything that contain both.

**Comment by gotson** [comment]
what is it you are trying to accomplish exactly ? You propose solutions, but explaining your problem clearly would help me find the right solution.

**Comment by donotos** [comment]
well my problem is that i have hundreds of books, be it one shots or series that contain books that does not follow each other like anthologies or collections, and i have like 15-20 years of mangas/comics/BD on my nas. I can't remember every title. that's why i put tag on them, to be able to find something while just remembering some of it's tags, so yes i could put tags on the series and it would work for most of them but it's not possible for the rest, it would be too messy to put every file on a subfolder just to create a serie for all of them

**Comment by gotson** [comment]
> it would be too messy to put every file on a subfolder just to create a serie for all of them

That's just a mental thing. Having a folder with 100 files, or 100 folders with 1 file each is almost the same thing.

> that's why i put tag on them, to be able to find something while just remembering some of it's tags,

So if I understand correctly, you want to be able to filter a Library by tags, but using tags that are set on Books instead of Series. By filtering by such tags, the view would show all Series having at least 1 book with the given tag. Is that a correct understanding ?

**Comment by donotos** [comment]
> So if I understand correctly, you want to be able to filter a Library by tags, but using tags that are set on Books instead of Series. By filtering by such tags, the view would show all Series having at least 1 book with the given tag. Is that a correct understanding ?

Yes exactly!

**Comment by gotson** [comment]
Komga already aggregates some metadata from books at series level to offer some filtering and display aggregated information. We could aggregate book tags and allow filtering on the union of the series tags and its book tags.

**Comment by donotos** [comment]
still interested in that feature
