### ISSUE TITLE
[Feature request] Start reading / Discover / Random books

### ISSUE THREAD

**Issue by soliemad** [gotson/komga#514]
### Is your feature request related to a problem? Please describe.
With a large library, I would like to have random books suggested to me to read.

### Describe the solution you'd like
A view similar to Plex's Start watching view or Calibre-web's Discover page which generates a random list of books/shows to read/watch. Integration with the Tachiyomi extension is a nice to have

### Describe alternatives you've considered or other apps that can do what you want
I run the following code snippet to find random books that could be hacked into a button. However, It's front-end only though and fetches the entire library which is pretty intense:
```javascript
async function getSeries() {
    var content = (await fetch('/api/v1/series?page=0&size=2500').then(j=>j.json())).content
    var series = content[Math.floor(Math.random() * content.length)];
    window.location =  `/series/${series.id}`
}
getSeries()
```

### Additional context
Plex view
![image](https://user-images.githubusercontent.com/16485457/116339203-04666e00-a7ab-11eb-861c-8a8da254692f.png)
Calibre-web view:
![image](https://user-images.githubusercontent.com/16485457/116340146-ac306b80-a7ac-11eb-9179-4430a2359efc.png)

**Comment by shrublet** [comment]
Bumping this to see if it's still a possibility :)
