### ISSUE TITLE
[Feature Request]It would be interesting to have the functionality of being able to merge several series

### ISSUE THREAD

**Issue by tomandocubatas** [gotson/komga#515]
### Is your feature request related to a problem? Please describe.

Sometimes when loading into Komga comics that have been tagged automatically using comicrack / comicvine (that is, the ComicInfo.xml file is generated), repeated series are created, although in reality they are the same series. This is due to how these series are created / loaded in comicvine.

### Describe the solution you'd like
The idea would be to have a functionality that allows merging several series into one..

### Describe alternatives you've considered or other apps that can do what you want
When selecting two or more series in the browse tab, include next to the option "Add to collection" an option that would be "merge series"

### Additional context
![imagen](https://user-images.githubusercontent.com/36165495/116389694-8abb9800-a81d-11eb-9568-a80433a7549c.png)

**Comment by gotson** [comment]
A series is created by folder. It's not a comicvine thing, it's just because you put files in a different folder.

The feature exists, just move files to the same folder.

**Comment by tomandocubatas** [comment]
Hello,
Indeed it is as you say.
Sorry for the mistake.
In any case, would it be possible to take into account the information related to the series contained in the ComicInfo.xml file (if any) to position the comic in the appropriate series?
![imagen](https://user-images.githubusercontent.com/36165495/116402215-6d41fa80-a82c-11eb-89fd-4727ca7be1b4.png)

**Comment by gotson** [comment]
No. A series name does not uniquely identify it. Plenty of series share the same name, despite being a completely different series.

If you have files that are part of the exact same series, move them in the same folder.

**Comment by tomandocubatas** [comment]
ok.
Anyway I belive thas is a goog idea de possibility of merge serios/collections, etc.

Thanks.
