### ISSUE TITLE
Single page chapters, mark as read on next chapter

### ISSUE THREAD

**Issue by raider-com** [gotson/komga#516]
### Is your feature request related to a problem? Please describe.
When reading chapters that have a single page, the status isn't marked as read when going to the next chapter,  This means that when you stop reading, you need to note the chapter, then go back and mark any chapters previously read as 'read'.

### Describe the solution you'd like
Ideally, I'd like the web reader to mark the chapter as read, even for single page chapters when browsing to the next chapter.

### Describe alternatives you've considered or other apps that can do what you want
Only manual noting of the chapter, and marking chapters as read.  This is especially annoying on slow refresh screen devices such as e-readers.

I didn't see another issue raised that addressed this.  If there is, I'm sorry.
Glad to provide more details if needed.

**Comment by gotson** [comment]
Did you try the latest version? It's been fixed. See #475

**Comment by raider-com** [comment]
I'm running v0.86.0-master in a docker container, and have the issue.

**Comment by gotson** [comment]
It's been fixed in https://github.com/gotson/komga/releases/tag/v0.87.5

**Comment by raider-com** [comment]
Sorry, thought the other post showed it fixed in 82.  Pulling gotson/komga fixed the issue.
Thank you!
