### ISSUE TITLE
[Feature Request] Add option to disable “Download this page”

### ISSUE THREAD

**Issue by MaestroJAL** [gotson/komga#517]
I use Komga in an educational setting allowing curated access to PDF documents. For many documents, I have permission to allow viewing but not downloading. I do realize that semi-resourceful  and determined students can easily figure out how to download documents. The problem for me is that I have to provide “reasonable security” for access. The ability to simply download each page one by one means I no longer can use Komga in this manner. 

Could this option be disabled either by privilege for users or simply a global option? I totally understand the usefulness of the feature. It just defeats my purpose for using Komga. Which, by the way, has been excellent and remains so.

**Comment by gotson** [comment]
The option in the front-end is using the api, which serves image. It is not possible to allow viewing only.

**Comment by MaestroJAL** [comment]
I don't believe you are understanding my issue. Maybe I'm not understanding you. ![image](https://user-images.githubusercontent.com/12278867/116501865-f33b6100-a87f-11eb-9634-d6ffdbf7f1a8.jpeg)

This "option" is part of the GUI of Komga. It wasn't present in previous builds, now it is. I can certainly revert if necessary and I guess I will but this is not about how the image is being retrieved via the API, but rather an added feature in the GUI that wasn't present before.

**Comment by gotson** [comment]
I completely understand. What I mean is that option is just a gimmick in the front-end, the backend serves images, and whether it's displayed or downloaded, the backend doesn't care.

There is no way to limit Komga in display only, because everything you can see, you can download as well.

Removing this option would not prevent anyone from downloading the images.

**Comment by MaestroJAL** [comment]
Thank you for the clarification and I understand it is just a gimmick. Unfortunately, for me and my setting, this will remove my "reasonable security" as I cannot have an option anywhere for downloading available to the user. I'll rollback if I can.

Thanks for your work on this. It has made teaching remotely a little easier this year.
