### ISSUE TITLE
[Bug] when going back in a library from a series remember last position

### ISSUE THREAD

**Issue by xtra-be** [gotson/komga#521]
### Komga environment
- **OS**: Synology
- **Komga version**: v0.90.0-master
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I have a problem in the web interface**
  - Browser (with version): safari / chrome /edge

### Describe the bug
I have several library's with many series inside.
for example a library with 300 series
on the top in the library the library is divided into several pages (for ex : 7 pages)
when I go into a series in a library and then move back to the library it always jumps to page one instead of the current page when using the back arrow on the top of the page.

### Steps to reproduce
1. Go to a library
2. make sure you have multiple pages
3. go to another page than 1
4. go into a series
5. select the back button of the series
6. you are back on page 1

### Expected behavior
expected behaviour would be to go back to page where you where

### Actual behavior
you move back to page 1

**Comment by gotson** [comment]
Use the browser's back button, it will keep your history and go back to the page you were at.
