### ISSUE TITLE
[Bug/Feature Request?] Books filtered by unread should include in-progress books

### ISSUE THREAD

**Issue by darthmooguy** [gotson/komga#526]
### Komga environment
- **OS**: 
- **Komga version**: 
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest (v0.91.1-master)

### Describe the bug
When filtering books with the "Unread" filter, books that are in progress should be included in the list, since they are not "Read" (or 100% done).

### Steps to reproduce
1. Start a book
2. Go to it's series page
3. Activate the "Unread" filter

### Expected behavior
Started books should be there. It makes sense to hide read books, but not "in progress" books. I think it would be better UX! Personnaly, if I want to see my unreads, I also want to see the book I'm currently reading, and not see the ones I've already read.

### Actual behavior
In progress books are not listed.

### Screenshots
Unread filter off:
![image](https://user-images.githubusercontent.com/10374678/117060120-92cc7980-acee-11eb-99a0-63678e49fcde.png)

Unread filter on:
![image](https://user-images.githubusercontent.com/10374678/117060156-9d870e80-acee-11eb-960f-3002b7dc468e.png)

**Comment by gotson** [comment]
I don't necessarily agree, plus you can see the books in progress on the dashboard.

**Comment by darthmooguy** [comment]
Yes, it's true, you can see the books in progress from the dashboards!

However, keeping in progress stuff with the "unread/watched" filter on is the behavior of most apps I used, so when my in progress stuff disappeared in Komga I was a bit surprised :stuck_out_tongue: 

For example, in Plex:
![Screenshot_20210504-232138](https://user-images.githubusercontent.com/10374678/117094229-3cccf580-ad31-11eb-9657-5d52c63b560e.png)

In Tachiyomi:
![Screenshot_20210504-232644](https://user-images.githubusercontent.com/10374678/117094081-c62ff800-ad30-11eb-90e3-2304a26b8545.png)

And Prologue (iOS app for audiobooks with Plex):
![File](https://user-images.githubusercontent.com/10374678/117094098-d3e57d80-ad30-11eb-9b31-b3186b37c92b.jpg)

I'm not saying that this is a must fix, but I think it would be beneficial for the user experience.

On another note, thanks for the great project!

**Comment by gotson** [comment]
Thanks for replying and pushing, I may have been to fast to close this.

**Comment by darthmooguy** [comment]
No problem! I really like this project, so I wanted to help make it a bit better 😁

**Comment by darthmooguy** [comment]
Thanks a lot!
