### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by Mastersam07** [gotson/komga#527]
Is the api still available? I tried hitting https://komga.org/swagger-ui.html but i was greeted with a 404

**Comment by Kussie** [comment]
if you are running Komga you can access it locally as well.

Ie:  127.0.0.1:8080/swagger-ui.html

**Comment by gotson** [comment]
The one from the demo is here: http://demo.komga.org/swagger-ui.html

But as Kussie mentioned, it's better to use the local one from your own instance.
