### ISSUE TITLE
[Feature Request] Option to add specific metadata to entry names

### ISSUE THREAD

**Issue by hwwilliams** [gotson/komga#528]
### Is your feature request related to a problem? Please describe.
Comic book series with the same name are confusing as they show up in the GUI and OPDS with either a year or no year, volume number or no volume number, or neither.

### Describe the solution you'd like
The main thought I had which at least would solve it for my case of comic books where I already have usable metadata is the option, a toggle or some kind in a settings menu maybe, where it would always add the publication year to the title of each entry shown within the GUI as well as OPDS.

Overall it would be useful to have the ability to set what metadata is used to build each entry title that is shown in the GUI and OPDS.

The inconsistency as shown below is what I mean

![image](https://user-images.githubusercontent.com/20447447/117100163-0c8d5300-ad41-11eb-8076-b7621238c4eb.png)

**Comment by gotson** [comment]
It is explained in the [documentation](https://komga.org/guides/scan-analysis-refresh.html#series-metadata):

> The Series and Volume tags will be used to overwrite the title of the Series, in the form <Series> (<Volume>), or just <Series> if the Volume tag is not present or if the Volume is 1. If multiple values are present, the most frequent value from all books will be used.

Your books have inconsistent metadata, where the volume is either a simple number (1, 2, 3), or the year (2013). That is why you get inconsistent results. Garbage in, garbage out, as we say.

If you want to consistently display the volume as year in the series title, you need to consistently use the volume as year inside your `ComicInfo.xml` metadata. There is an option for that in Mylar 3 for instance.

**Comment by hwwilliams** [comment]
I didn't say I wanted to use the year as volume information, I asked to show the year in addition to the name. In OPDS there is very few ways to see what each comic is. 

Not every comic is going to have a volume number. Every comic will have a publication year.

**Comment by gotson** [comment]
You want an out of the box solution that fits your particular needs, with your particular metadata. That will not happen. Edit the metadata in Komga if you need.

**Comment by hwwilliams** [comment]
I don't think I'll ever understand how only having the volume number in a title name is more useful than the publication year and volume but thanks anyway.

I ended up using the API with a script to just rename them on import.
