### ISSUE TITLE
KUDOS

### ISSUE THREAD

**Issue by kingfenix** [gotson/komga#529]
Just KUDOS for this excellent web application!! This is a very slick/smooth way to organize and read, and well on its way to including management features as well. One might think there is finally a product that may be able to replace the now defunct ComicRack. THANK YOU!!!!!

**Comment by kingfenix** [comment]
oh and by the way, for me you have already replaced Ubooquity, so more KUDOS. Question do you have a blog or somewhere where you inform of your future plans or roadmap for this? Would love to know if you plan to include any features from comicrack, mylar, chunky, etc...this could be a one stop shop!!! so exciting of a product and would love to know your own personal goals for it.

**Comment by gotson** [comment]
I don't discuss future plans, ETAs, nor roadmap. It's still a one-man project, so it goes along with my free time and my mood. We do have some discussions about future features on Discord, but that's it.

**Comment by gotson** [comment]
I will be closing this, since you've joined the Discord and brought ip some good ideas 👍🏻
