### ISSUE TITLE
Plex theme

### ISSUE THREAD

**Issue by Na0mir** [gotson/komga#533]
Hello

Thank you for your awesome project and all the work about it!
I noticied you often compared Komga to Plex, I suggest you to have a look to the **caliBur!** theme of calibre-web project: https://github.com/janeczku/calibre-web

It's really nice, maybe you can take some part of the code for inspiration
![2021-05-12 08_29_33](https://user-images.githubusercontent.com/6453724/117905901-822b8d00-b306-11eb-8ccf-0e0452db7384.png)
Na0mir

**Comment by gotson** [comment]
Komga is indeed inspired by Plex, mostly for the functionalities, slightly for the UI organization. However, it uses [Material Design](https://material.io/design) for the UI framework, via [Vuetify](https://vuetifyjs.com/en/).

Plex does not follow Material Design, and uses its own UI language. I have no plan on changing the UI theme for now.

Thanks for the tip though!
