### ISSUE TITLE
[Bug] Reading Lists for a Library not deleted when the library is deleted

### ISSUE THREAD

**Issue by kennethAndrewIves** [gotson/komga#534]
### Komga environment
- **Windows 10**: 
- **Komga 0.93**: 

-**I am running Komga from the `jar`**
  - Java version: 8.0.25
- [ x] **I have a problem in the web interface**
  - Browser (with version): Firefox 88

### Describe the bug
When a library is deleted, the reading lists associated with that library are still present in the database. This leads to the inability to create a reading list with the same name in a new library due to a duplicate error. It's impossible to access the reading lists from the deleted library in the UI, they must be deleted through the database. 

### Steps to reproduce
1. Create a library with at least one comic and create a reading list in it 
2. Delete the library
3. Create a new library with at least on comic in it 
4. Attempt to create a reading list with the same name as the one from the deleted library

### Expected behavior
Reading list is created

### Actual behavior
Error creating reading list, this list already exists.

**Comment by gotson** [comment]
> When a library is deleted, the reading lists associated with that library are still present in the database

Read lists are not associated with a library, only with books. They can include books from any library.

> It's impossible to access the reading lists from the deleted library in the UI, they must be deleted through the database.

You can see them from the _Read lists_ tab from the _All Libraries_ view

**Comment by kennethAndrewIves** [comment]
Thanks (y)
