### ISSUE TITLE
[Feature Request] allow artemis path configuration

### ISSUE THREAD

**Issue by ted46045** [gotson/komga#535]
### Is your feature request related to a problem? Please describe.
I run the jar as 'daemon' user, which doesnt not have a vlaid home dir path (or one that shouldnt be written to, ie: /usr/sbin)  when starting up it will show an error like
``` AMQ222141: Node Manager can not open file /usr/sbin/.komga/artemis/journal/server.lock```

### Describe the solution you'd like
Add another configuration override to change the default path for all the artemis related content (default looks to be ${user.home}/.artemis)

### Describe alternatives you've considered or other apps that can do what you want
I tried looking through the artemis docs and saw there was some overrides that could be set via broker.xml or the java options (-Djournal-directory=foo) but it didnt work as I had hoped
https://activemq.apache.org/components/artemis/documentation/latest/configuration-index.html

**Comment by gotson** [comment]
It's already available but not documented, it's a Spring Boot configuration property: `spring.artemis.embedded.data-directory`

**Comment by ted46045** [comment]
Awesome, thanks.  Found the source file for refrence (should of grepped source first) https://github.com/gotson/komga/blob/master/komga/src/main/resources/application.yml
