### ISSUE TITLE
[Feature Request] Better Chapter Special Number Recognition

### ISSUE THREAD

**Issue by valdearg** [gotson/komga#537]
Currently I name my files in a specific format, for example:

Futaribeya - c011.5 (v01) [MangaDex, Girls in Boxes]

OR

Futaribeya - c011x5 (v01) [MangaDex, Girls in Boxes]

(this is due to some sorting issues in some apps)

When imported into Komga this is added as chapter 12, this then means that the next chapter is marked as chapter 13:

Futaribeya - c012 (v02) [MangaDex, Girls in Boxes]

This unfortunately means that when using with a manga tracker source in things like Tachiyomi will update the read chapter incorrectly.

Would it be possible to recognise these "specials" and mark them as the decimal point release in Komga?

Naturally this can be corrected manually within the Komga site, but it's a bit of a nightmare for so many manga.

**Comment by gotson** [comment]
There is no parsing or filenames, and there will never be any. It is way too complex, and there are no accepted standards for comics Manga etc like there is for TV shows for example.

Also, please use the templates next time.
