### ISSUE TITLE
Allow for cors configuration

### ISSUE THREAD

**Issue by antoinerey** [gotson/komga#540]
### Komga environment
- **OS**: Ubuntu
- **Komga version**: 0.95.3
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug

I'm playing a bit with the REST API, but I'm struggling using it from another domain than the one it's hosted from. 

- My libraries are accessible from `https://comics.abc.com`.
- So, the associated API are accessible from `https://comics.abc.com/api/*`.
- I'm trying to call the REST endpoints from `http://localhost`.

Nothing super fancy here, just a simple distant API I would like to call. However, I keep getting CORS errors, and God knows that CORS are a PITA.

So, in order to get HTTPS and co. ([and as suggested in the documentation](https://komga.org/installation/configuration.html#https)), I've setup Caddy as a reverse proxy between the external world, and the Komga instance. And I've configured it so that the HTTP response includes `Access-Control-Allow-Origin: *`.

Here is my Caddy configuration:

```
comics.abc.com {
  reverse_proxy {
    header_down Access-Control-Allow-Origin *
    to komga:8080
  }
}
```

And still, I keep receiving failures from the API. Here the error message:

```
Access to fetch at 'https://comics.abc.com/api/v1/libraries' from origin 'http://localhost:3000' has 
been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does 
not have HTTP ok status.
```

And the according preflight request returns as 403 HTTP error.

_Note that I've properly setup the Basic authentication credentials. I've tested the credentials through the login form, and they work as expected._

**Do you have any idea what might be the solution?** 🙏

### Expected behavior

Based on the above configuration, I believe CORS should not be a problem. Or, at least, get a way to configure them properly so that I could use the REST API from another domain.

### Log file

I've set `LOGGING_LEVEL_ORG_GOTSON_KOMGA=DEBUG` and yet, no access logs are displayed from the Docker image when hitting the API.

**Comment by Kussie** [comment]
You may need to add the following headers:
`Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS`
`Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token` Though the option on this header you will probably need to change to suit you.

**Comment by gotson** [comment]
Can you give a bit of context on what you are doing on localhost in the browser, what is calling the api and how?

**Comment by antoinerey** [comment]
@Kussie, I've tried adding the headers to my configuration, as you suggested, but that does not change anything I'm afraid. Here is what it looks like now:

```
comics.abc.com {
  reverse_proxy {
    header_down Access-Control-Allow-Origin  "*"
    header_down Access-Control-Allow-Headers "*"
    header_down Access-Control-Allow-Methods "GET, POST, PATCH, PUT, DELETE, OPTIONS"

    to komga:8080
  }
}
```

---

@gotson The application is a Vite application I just generated through `yarn create @vitejs/app`. And I'm using axios to fire the HTTP request from a browser. Here what to code looks like:

```js
axios.get('/api/v1/libraries', {
  baseURL: 'https://comics.abc.com',
  auth: {
    username: import.meta.env.VITE_USERNAME,
    password: import.meta.env.VITE_PASSWORD,
  },
})
```

I'm not familiar with Kotlin or any Java ecosystem, but I was wondering if there were any configuration on Komga server itself that would prevent me from hitting the API from another domain. Something like a whitelist that would basically allow nothing.

When investigating the code, I saw this (https://github.com/gotson/komga/blob/3834d415aea2d61067c7b428468d5b7531f9c964/komga/src/main/kotlin/org/gotson/komga/infrastructure/security/SecurityConfiguration.kt#L96-L109), could it be related in any way?

**Comment by gotson** [comment]
Cors is there to avoid cross origin requests, you can look it up. It's applied only in browsers, so you can't integrate Komga into another website for instance. You can however use normal tools to interact with the rest api (curl, or any programming language that would not run inside a browser).

That's why I was asking what you are trying to do with it. You mention Vite, so you're trying to do a website or web app?

Cors is controlled on server side. You may be able to trick the Komga server by modifying the headers in the reverse proxy, but I am not very versed in that. I'm sure you can find plenty of resource on stackoverflow.com about it, given cors is widespread.

**Comment by antoinerey** [comment]
I was more wondering if the Komga server includes CORS-related security. If that's the case, I believe a way to control/turn it off would be appreciated. Something like an environment variables for example?

Anyway, I'll keep looking for how to trick the server from my reverse proxy. Thanks 🙂

**Comment by gotson** [comment]
> I was more wondering if the Komga server includes CORS-related security

Yes, it's done here: https://github.com/gotson/komga/blob/0e42806ab4464e2bdd022cf8319f31fa28e3c8f3/komga/src/main/kotlin/org/gotson/komga/infrastructure/security/SecurityConfiguration.kt#L36



> I believe a way to control/turn it off would be appreciated

At the moment it's not possible. Cors is quite complex so simply turning it off is probably not an option.

Controlling it would probably be a better option. For instance that's what's done for local development environment to allow connection from the webui hosted on a separate node process: https://github.com/gotson/komga/blob/0e42806ab4464e2bdd022cf8319f31fa28e3c8f3/komga/src/main/kotlin/org/gotson/komga/infrastructure/security/SecurityConfiguration.kt#L102

I will modify your issue to make it a feature request to make cors configurable.

**Comment by gotson** [comment]
@antoinerey the latest version will include configuration properties for the allowed origins.

To run in Docker you will be able to add the following environment variable: `KOMGA_CORS_ALLOWED_ORIGINS=http://localhost:8081`
