### ISSUE TITLE
[Bug] Web reader progress no longer updating

### ISSUE THREAD

**Issue by nx6** [gotson/komga#543]
### Komga environment
- **OS**: FreeBSD 12.2
- **Komga version**: v0.96.1-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk version "11.0.10" 2021-01-19
- [x] **I have a problem in the web interface**
  - Browser (with version): Firefox 88.0.1
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Reading progress is not updating. Last night I read up to the middle of volume 11 in a manga. Today I upgraded from 0.95.4 to 0.96.1, and picked back up reading through the end of volume 11. But when I exited out of the reader a few pages into volume 12, Komga is still listing me as at the same position in the previous book as when I went to bed last night. I've also tried manually marking volume 11 as read to move the next one to On Deck, but it's still hanging onto the exact same position I was at before tonight.

### Steps to reproduce
1. Go to any page in the middle of a book
2. Exit out of the book.
3. Home screen will not register your progress.

### Expected behavior
Progress should be saved at page left off on.

### Actual behavior
Home page maintains old info on reading progress.

### Additional context
I was using my (Windows) tablet for this. Now I'm on my desktop PC and I can reproduce the behavior in Firefox there, too. However, when I use my normal main browser (Waterfox Classic 2021.04.2) the progress *does* still get saved there. Also have found progress is not saving when I tried on Chrome (90.0.4430.212).

**Comment by gotson** [comment]
Can you provide log files?

**Comment by gotson** [comment]
Which button did you press to read? There's an incognito button (grey color with incognito icon) that doesn't mark progress. Maybe you used that to read instead of the red read button?

**Comment by nx6** [comment]
Not sure how to get those (logs) immediately. I actually need to go to bed (its 5:12am here).

I just now changed my rc.local to load the old jar for 0.95.4 and restarted the server. Read progress working again.
Also, there's an issue with the interface icons not loading on Microsoft Edge/Chrome (getting empty boxes in place of them) on this new version.

I can play around on this again tomorrow night.

**Comment by gotson** [comment]
Sure. Nothing has changed in the webreader between those 2 versions, so problem may be somewhere else.

**Comment by nx6** [comment]
Okay. I've made an important discovery on this. The issue only happens when I am using the reader through my reverse proxy. On local LAN IP reading the progress is still saved. Also that icon issue I mentioned at the end is dependent on my using the reverse proxy as well.

Are these the logs you are looking for? I went through a book and flipped some pages exited out, and then tried to return back in a few times.
[komga.zip](https://github.com/gotson/komga/files/6525810/komga.zip)

**Comment by gotson** [comment]
If it's your reverse proxy then can you check the network xhr calls done from your browser's developer tool, network tab?

**Comment by nx6** [comment]
Okay. That is illuminating.

> filename | /manga/api/v1/books/03V0TV7XYYWEC/read-progress

```
Status403
VersionHTTP/1.1
Transferred314 B (20 B size)
Referrer Policystrict-origin-when-cross-origin

	
Connection
	keep-alive
Date
	Sat, 22 May 2021 05:46:19 GMT
Server
	nginx/1.18.0
Transfer-Encoding
	chunked
Vary
	Origin
Vary
	Access-Control-Request-Method
Vary
	Access-Control-Request-Headers
X-Content-Type-Options
	nosniff
X-Frame-Options
	DENY
X-XSS-Protection
	1; mode=block
```

**Comment by gotson** [comment]
Thanks. There was a recent change in cors, but it's weird that some calls are working and others not. Can you share your reverse proxy configuration?

**Comment by nx6** [comment]
```
# Proxy for Komga

location /manga {
	proxy_pass http://192.168.9.224:8080;
	proxy_redirect off;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP 		$remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
```

**Comment by gotson** [comment]
Please try with `0.96.2` and let me know if you still have the problem.

**Comment by nx6** [comment]
That looks good! :+1: 

- Progress saving working on Firefox again.
- Icons issue is also gone on Chrome and Edge now.
