### ISSUE TITLE
[Feature Request] api search books by file path or filename

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#545]
### Is your feature request related to a problem? Please describe.
As a User I want to automate a lot of changes on Book Level. 
In the most cases I have only the filename (path+filename).

For a better implementation and automation it would be greate to have the possibility to hand over the path+filename over the API and receive the BookId. 
With the BookId I can use the standard APIs to go forward with my changes.

### Describe the solution you'd like
A good way could be to have an API Request under the book section like /api/v1/books/search4FileName with the simple parameter of path+filename to be unique and receive the BookId.

### Describe alternatives you've considered or other apps that can do what you want
At the moment I use the Database and a SQL script to get what I want. But this is not supported.

### Additional context
Maybe it is an good idea to make it case sensitive to be on the safe side for unix / linux users.

**Comment by kanjieater** [comment]
Also expressing interest in this. Currently what are the alternatives? 
1. You would have to add the archive to the library
2. Tell komga to refresh the files (not sure where that's at in the API?)
3. Request via the book title (just the file name, no extension)
4. Match the results `url` field with your local path to confirm the `id` (in case you have multiple books in different series with the same name)
5. Make an api request with the id
6. ??
7. Profit


Alternatively with a feature like this:
1. Give komga file path
2. Komga give you an `id`
3. Make an api request with the id
4. ??
5. Profit

It's a much shorter path for external tools to use the API. I'm a little concerned about the 2nd step "refreshing and waiting" and how to automate that without already knowing the id.

**Comment by kanjieater** [comment]
still interested
