### ISSUE TITLE
Display total number of books per library

### ISSUE THREAD

**Issue by Na0mir** [gotson/komga#548]
Hello

Is that possible to display the total number of books for each library?
Maybe near the name change the current number of series by :

<number of series in this library> series | <number of books in this library> books

Thanks !
It would be easier to made it consistent for those who also use their libraries with ComicRack

**Comment by gotson** [comment]
You mean the number of books you have or the total number of books in that series?

**Comment by Na0mir** [comment]
> 
> 
> You mean the number of books you have or the total number of books in that series?

Total number of books I have
I my case I have 3 libraries: Comics, Mangas and BD. 
Knowing how many books I have for each would be interresting

**Comment by gotson** [comment]
Ah you want to see the total number of books per library?

**Comment by Na0mir** [comment]
> 
> 
> Ah you want to see the total number of books per library.

Yes 😁
Thanks
