### ISSUE TITLE
Docker image for ARM/Raspberry Pi

### ISSUE THREAD

**Issue by null-von-sushi** [gotson/komga#55]
Sorry if this is not the place to ask, just close this issue.
I was hoping to try out komga and install it in a recently aquired raspberry pi. I have not actually used docker before, but I thought I would give it a try.

The issue is I am getting errors.
`2020-01-04T12:26:48.727237849Z standard_init_linux.go:211: exec user process caused "exec format error`

I am going to take a guess and assume this is due to komga only being made for x86 platforms? From the readme I got the impression that komga is writtein in Java, so shouldn't this work on ARM as well?

**Comment by gotson** [comment]
Hello,

Java works on ARM and Raspberry Pi. You need to use OpenJDK 11 though, else the performances are awful (see #23).

For docker it's another story, the docker image needs to be built for ARM. Docker now has some tools in beta to build multi-arch versions from a single machine, but i have found no easy way (yet) to integrate that in my CI setup.

You can run it from the `jar` in the meantime.

**Comment by null-von-sushi** [comment]
Oh okay, I didn't know docker was architecture specific. Thank you for clearing this up, I will try running it myself with OpenJDK 11!

**Comment by basdp** [comment]
I have created a Docker image that should work as a direct stand-in for the official image:
https://hub.docker.com/repository/docker/basdp/komga_pi

This is just a workaround, until the official komga repo has arm images. But it works flawless for me on a Pi 4.

In the long term, we should upload arm builds along the amd64.

**Comment by gotson** [comment]
> I have created a Docker image that should work as a direct stand-in for the official image:
> https://hub.docker.com/repository/docker/basdp/komga_pi
> 
> This is just a workaround, until the official komga repo has arm images. But it works flawless for me on a Pi 4.
> 
> In the long term, we should upload arm builds along the amd64.

Thanks ! Would you be able to share details on how you build it ?

Even if i cannot get multi-arch to work with manifest lists, i could have an official image with a `-arm` suffix on all tags maybe.

**Comment by gotson** [comment]
Multi-arch images are now available ! 🚀
