### ISSUE TITLE
[Feature Request] Import Series metadata from series.json (Mylar)

### ISSUE THREAD

**Issue by kingfenix** [gotson/komga#550]
Reminder to please import from series.json file which mylar provides now if available.

**Comment by gotson** [comment]
Mylar can optionally generate a `series.json` file inside the folder of each series ([sample](https://gist.github.com/gotson/d222218a1e3ab447393204aa53371009)).

**Comment by gotson** [comment]
Schema can be found here: https://github.com/mylar3/mylar3/wiki/series.json-schema
