### ISSUE TITLE
[Feature Request] Add metadata attributes to Series

### ISSUE THREAD

**Issue by kingfenix** [gotson/komga#552]
Please add attributes to the series metadata to store the foillowing
1. Volume (Release Year) - Not always the same as the year from the first issue.
2. Imprint
3. Summary (not the description from first issue)

These can also be imported from the series.json provided by mylar.

**Comment by gotson** [comment]
Please fill the template next time, it's here for a reason.

1. Not sure to understand. Do you want the volume, or the release year? In what case would the release year of a series not be the earliest year from any of its books? 
2. You can add the imprint inside the publisher field. 
3. There's already a field for summary by series.

**Comment by kingfenix** [comment]
Hi gotson,
1. I believe that most people along with myself want to use release year as the volume, and a example case would be Avengers - release year 2012, first issue is in 2013.
2. imprint should not replace publisher. For ex. Publisher "Marvel", Imprint "Max"
3. In the GUI, why does the series summary seem to always say "from the 1st issue" then?

**Comment by Kussie** [comment]
> 3. In the GUI, why does the series summary seem to always say "from the 1st issue" then?


Because you need to set the series summary manually.  I don't believe there is a way to currently import this from metadata (Though the docs may prove me wrong).  But once set it wont say from 1st issue any more and will apply to the series and not the books

**Comment by kingfenix** [comment]
series.json from mylar has a description in it, so importing that for #3 will satisfy the request then :)

**Comment by gotson** [comment]
we don't delete stuff :)
