### ISSUE TITLE
[Bug] Java in Docker container is maxing CPU

### ISSUE THREAD

**Issue by stevethepirate88** [gotson/komga#553]
### Komga environment
- **OS**: Debian 9
- **Komga version**: v0.99.1-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
Earlier today the CPU usage on the server spiked to utilizing 100% of the available CPU compared to the ~3% it normally was.

Upon investigation the java service is the culprit. 
```
armedgamer@comics:~$ top
top - 05:10:07 up 16 min,  1 user,  load average: 0.32, 0.26, 0.29
Tasks: 111 total,   1 running, 110 sleeping,   0 stopped,   0 zombie
%Cpu(s): 24.5 us,  2.0 sy,  1.0 ni, 66.8 id,  5.6 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  2052428 total,   542924 free,   237896 used,  1271608 buff/cache
KiB Swap:   524284 total,   523980 free,      304 used.  1653836 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 8082 armedga+  20   0 2525176  84636  18904 S 99.9  4.1   0:03.23 java
    1 root      20   0   57124   6928   5328 S  0.0  0.3   0:01.27 systemd
    2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S  0.0  0.0   0:00.07 ksoftirqd/0
    5 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H
    7 root      20   0       0      0      0 S  0.0  0.0   0:00.28 rcu_sched
    8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh
    9 root      rt   0       0      0      0 S  0.0  0.0   0:00.00 migration/0
```
I powered the server down, restored from a backup taken 24 hours ago, and booted the server up. Same ordeal. I turned off the docker container, removed it, updated the docker image, then started it back up and once again java is at 99% CPU. The docker logs show the server booting up, scanning the logs, and everything looking okay.

### Steps to reproduce
1. Power server on
2. Start komga docker container
3. ???
4. What's the opposite of profit?

### Expected behavior
The server should run as it has for the past 6 months: at ~3.4% CPU

### Actual behavior
The java service uses the entirety of my CPU.

### Additional context
Nothing new has been added to the server or updated for ~6 months.

### Screenshots
<img width="530" alt="Screen Shot 2021-06-11 at 1 11 25 AM" src="https://user-images.githubusercontent.com/22171718/121634159-18f88000-ca52-11eb-8c6c-ce9278bd4be1.png">

### Log file
[komga-logs.txt](https://github.com/gotson/komga/files/6636004/komga-logs.txt)

**Comment by willfanguy** [comment]
Same issue is happening here. Gonna try to run it natively on the Pi to see if it's just a Docker-related issue.

**Comment by silasfelinus** [comment]
Confirming the same issue: running through Docker with Unraid.
