### ISSUE TITLE
[Bug] query param parsing doesn't allow comma in values

### ISSUE THREAD

**Issue by nx6** [gotson/komga#557]
### Komga environment
- **OS**: FreeBSD 12.2-RELEASE-p6 amd64
- **Komga version**: 0.99.4-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: OpenJDK build 11.0.10+9-1
- [x] **I have a problem in the web interface**
  - Browser (with version): Waterfox Classic 2021.06 / Firefox 89.0.1 / Chrome 91.0.4472.106
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug

I've realized the reason clicking a name in the metadata for a title has never worked for me is because I enter the names in the format "lastname, firstname". I recently clicked on an author who uses a single word for their pen name and the filtering worked. Playing around further I found changing the metadata to a plain western "firstname lastname" format worked, and even having an exclamation point at the end of a name still allowed the feature to function (hey, there could be someone out there who has a pen name like that).

### Steps to reproduce
1. Have a comic on your server where you have entered the name info with a comma in it.
2. View the landing page for the title with the genre, tags, and people listed.
3. Click the name with the comma.

### Expected behavior
Getting a page displaying other titles for the individual in the role from the original work (writer, or penciller, etc)

### Actual behavior
You get a results page saying "The active filter has no matches. Use the filter panel to change the active filter", even though you literally just clicked from a match to get here.

**Comment by gotson** [comment]
The problem is in the parsing of the query parameters, which are used to restore filters from url. Searching the author with a comma inside from the filter panel works as expected.
