### ISSUE TITLE
[Feature Request] Mark required fields for /api/v1/books (GetAllBooks)

### ISSUE THREAD

**Issue by jeremydouglass** [gotson/komga#562]
### Is your feature request related to a problem? Please describe.
In the swagger-ui.html interface, /api/v1/books (GetAllBooks) is surprisingly hard to understand through the Try It mode. It either times out on "execute" or else returns an Internal Server Error 500, or else returns an 200 with an empty set.

It took quite a while to figure out what was going on:

1. the field read_status is required. That really surprised me -- I would expect filtering a search on whether a book was in progress or not to be advanced, but not providing one generates an undocumented internal server error 500.
2. the media_status field must be passed as e.g. READY -- if it isn't, the search returns a 200 empty set, even if there are matches in komga. Again, I was really surprised by this.

### Describe the solution you'd like

The minimum solution would be to mark the UI elements that are required in order to generate a valid search response, e.g. using [required](https://stackoverflow.com/questions/40113049/how-to-specify-if-a-field-is-optional-or-required-in-openapi-swagger).

### Describe alternatives you've considered or other apps that can do what you want

Another solution would be to change search so that the read_status defaults to "any" and the media_status defaults to "READY" if not provided. I honestly think that would be a more expected search interface, and would prefer it -- it means that I don't have to do three queries for READ, UNREAD, and IN-PROGRESS just to find a single book -- but there may be internal reasons why you don't want this implementation.

**Comment by gotson** [comment]
No parameters are required on this endpoint, you can try it with `curl`, it works as expected.

**Comment by jeremydouglass** [comment]
Apologies -- I assumed this was not a bug and tried to do detective work. Instead I'll just submit a separate reproducible bug report.
