### ISSUE TITLE
[Feature Request] Extend cookie/session length

### ISSUE THREAD

**Issue by elit3ge** [gotson/komga#563]
### Is your feature request related to a problem? Please describe.
When reading on my iPad, I constantly get prompted to sign back into Komga, I can get halfway through a comic and it seems to stall and I have to login again.

### Describe the solution you'd like
Option to extend the session or cookie.

**Comment by gotson** [comment]
Did you enable remember me? https://komga.org/installation/configuration.html#komga-rememberme-key-komga-remember-me-key-key

**Comment by elit3ge** [comment]
That did the trick! Cheers.

**Comment by freshyill** [comment]
@gotson This is exactly what I'm looking for, but I'm not sure what the key should be. The account's email address? True/false? Something else?

**Comment by Kussie** [comment]
They key should be a random string.
