### ISSUE TITLE
[Bug] swagger-ui interface to /api/v1/books/ hangs on Loading

### ISSUE THREAD

**Issue by jeremydouglass** [gotson/komga#566]
### Komga environment
- **OS**: Synology DSM 6.2.4
- **Komga version**: 
- **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: gotson/komga as in the documentation, which I believe defaults to latest
- **I have a problem in the web interface**
  - Browser (with version): Chrome Version 91.0.4472.114 (Official Build) (x86_64)

### Describe the bug

On a new komga install, the /swagger-ui/ interface to /api/v1/books/ (getAllBooks) fails with an infinite spinning "Loading" when passed an empty query or a simple search term. It also sometimes displays an Error 500 internal server error or a 200 when configured with various parameters.

### Steps to reproduce

Setup:

1. Install a new komga via docker compose:

```
version: '3.3'
services:
  komga:
    image: gotson/komga
    volumes:
       - /volume1/docker/komga2/config:/config
       - /volume1/docker/komga2/data:/data
    ports:
      - 8976:8080
    user: "1026:100"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g
      - TZ=America/Los_Angeles
    restart: unless-stopped
```

2. create a library folder 'test'
3. add a single test cbz to the library -- in this case, I used the top downloaded copyright free cbz file from digitalcomicmuseum "Wanted" https://digitalcomicmuseum.com/index.php?dlid=21158
4. from the web toolbar, trigger indexing so that the comic appears in the web interface
5. type "Wanted" in the komga web search bar. The correctly matching search result appears immediately.

Demonstrating the bug:

6. navigate to http://yourserverhere:8976/swagger-ui.html
7. navigate to /api/v1/books/
8. click "Try it out" then "Execute" -- the interface displays a "Loading" wheel animation, then never updates (after minutes, hours).

Even more bug

9. click "Cancel" then "Try it out". The displayed loading wheel is stuck, there is no execute button, so cancel failed.
10. hard refresh the page
11. navigate to /api/v1/books/
12. click "Try it out" and provide a query term "Wanted" then "Execute" -- the interface displays a "Loading" wheel animation, then never updates

When I keep hard refreshing the page and trying different combinations of entries on /api/v1/books/, I sometimes get Internal Server Error 500 displayed instead of just a spinning wheel, occasionally a 200. It was possible for me to get a valid response after repeatedly changing settings, but it isn't clear why that happened -- I already speculated on that in #562 and it wasn't helpful so I won't speculate further.

13. At any time, navigate back to the komga web interface and try searching "Wanted". Search still works just fine -- so whatever happened on the API page probably didn't make the search service fall down?

### Expected behavior
The swagger Execute for /api/v1/books/ generates a result and an example curl statement.

### Actual behavior
An infinite loading wheel. Sometimes and Internal Server Error 500.

### Screenshots
<img width="954" alt="Screen Shot 2021-06-30 at 1 35 58 PM" src="https://user-images.githubusercontent.com/798570/124028179-8e4bd680-d9a8-11eb-974d-6d0414f77b6a.png">

### Log file
https://gist.github.com/jeremydouglass/a3a12ba888cea4cde5cf7f5062bf15a4

**Comment by gotson** [comment]
Related to https://github.com/swagger-api/swagger-ui/issues/7160

I found a workaround, will release a fix.
