### ISSUE TITLE
[Feature Request] Per user customizable home screen and new filters

### ISSUE THREAD

**Issue by kingfenix** [gotson/komga#569]
### Is your feature request related to a problem? Please describe.
As discussed in discord, I voiced a wish for a new view in the "Home" area showing books/series by release date, so that filling holes in older series wouldnt cause me to not see the current weeks books.

### Describe the solution you'd like
gotson described a scenario where user specific settings could be used to control views/widgets/ordering on the home screen.

### Describe alternatives you've considered or other apps that can do what you want
Plex was the inspiration for this scenario and how it might work.

### Additional context
one quick idea might be to just add a row "Recently Released Books" to current home screen as is, while development of the rest takes place.

**Comment by MagikarpLaCarpe** [comment]
If Gotson add this, maybe he should add per library permissions so some user may access to certain library while other couldn't.

**Comment by gotson** [comment]
I ended up adding a _Recently Released Books_ section on the dashboard, that shows books released in the past month.
