### ISSUE TITLE
Rar archives with crc errors could be partially handled

### ISSUE THREAD

**Issue by gotson** [gotson/komga#57]
> It seems there is an issue with some of my comics files. I've tested two of the ones Komga complains about, and for both of them one of the JPGs inside has a CRC error. The files are too big to upload here, but here's an example output from `unrar`s test:
> 
> ```
> UNRAR 5.61 beta 1 freeware      Copyright (c) 1993-2018 Alexander Roshal
> 
> Testing archive Realm_of_Kings_One-Shot.cbr
> 
> Testing     Realm_of_Kings_001-017.jpg                                OK 
> Testing     Realm_of_Kings_001-018.jpg                                OK 
> Testing     Realm_of_Kings_001-019.jpg                                OK 
> Testing     Realm_of_Kings_001-020.jpg                                OK 
> Testing     Realm_of_Kings_001-021.jpg                                OK 
> Testing     Realm_of_Kings_001-022.jpg                                19%
> Realm_of_Kings_001-022.jpg - checksum error
> Testing     Realm_of_Kings_001-023-24.jpg                             OK 
> Testing     Realm_of_Kings_001-025-26.jpg                             OK 
> Testing     Realm_of_Kings_001-027.jpg                                OK 
> Testing     Realm_of_Kings_001-028.jpg                                OK 
> Testing     Realm_of_Kings_001-029.jpg                                OK 
> Testing     Realm_of_Kings_001-030.jpg                                OK 
> Testing     Realm_of_Kings_001-031.jpg                                OK 
> Testing     Realm_of_Kings_001-032.jpg                                OK 
> Testing     Realm_of_Kings_001-001.jpg                                OK 
> Testing     Realm_of_Kings_001-002.jpg                                OK 
> Testing     Realm_of_Kings_001-003.jpg                                OK 
> Testing     Realm_of_Kings_001-004.jpg                                OK 
> Testing     Realm_of_Kings_001-005.jpg                                OK 
> Testing     Realm_of_Kings_001-006.jpg                                OK 
> Testing     Realm_of_Kings_001-007.jpg                                OK 
> Testing     Realm_of_Kings_001-008-09.jpg                             OK 
> Testing     Realm_of_Kings_001-010-11.jpg                             OK 
> Testing     Realm_of_Kings_001-012.jpg                                OK 
> Testing     Realm_of_Kings_001-013.jpg                                OK 
> Testing     Realm_of_Kings_001-014.jpg                                OK 
> Testing     Realm_of_Kings_001-015.jpg                                OK 
> Testing     Realm_of_Kings_001-016.jpg                                OK 
> Total errors: 1
> ```
> 
> My comics reading app just shows a blank page with an error icon and keeps going. Maybe Komga can be a bit more tolerant in these cases?

I could try, but I'll need one of the files to understand where is the problem and how to get around. @sardaukar Can you post it somewhere else?

_Originally posted by @gotson in https://github.com/gotson/komga/issues/49#issuecomment-570837495_

**Comment by sardaukar** [comment]
Hope this link works http://ge.tt/2K5J9X03

**Comment by gotson** [comment]
Got it, thanks. Will have a look.
