### ISSUE TITLE
[Feature Request] Database Backup

### ISSUE THREAD

**Issue by elit3ge** [gotson/komga#570]
### Describe the solution you'd like
The ability to automatically backup your database.

### Additional context
Long story short, Komga on a Docker Swarm the secondary node came online but lost access to the network share for my comics, it looks like it dumped all my comics and was blank. Had to fix the network problem, restarted the container but there are no comics there now, it has done a scan on the network share readded all the comics back to the library (and has to re-fetch all the metadata) and I have lost my read progress on all my comics.

**Comment by gotson** [comment]
#217 should help in that regards.

As for the backup, you just have to keep a copy of the sqlite database, you can use any tool you want to do so.

**Comment by gotson** [comment]
Here are some more advice :
- do not use a mount as a library root. If the mount fails, the directory appears empty, and the library will be deleted. Use a subfolder of the mount instead. That way the folder is inaccessible and the scan will fail without deleting anything.
- don't run multiple replicas of Komga. The database is not designed for concurrent access.

**Comment by elit3ge** [comment]
- So instead of mounting in docker as /comics mount it as /mount/comics
- There is only every one process running at once, I just have different nodes distribute out the containers.
