### ISSUE TITLE
[Feature Request] Show in book view the information includes the book a comicinfo.xml

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#574]
### Is your feature request related to a problem? Please describe.
As a user I want to see in Komga is in a book a comicinfo.xml.

### Describe the solution you'd like
In the book view should be a field with the information there is a comicinfo.xml in the book.

### Describe alternatives you've considered or other apps that can do what you want
---

### Additional context
![request_comicinfo xml](https://user-images.githubusercontent.com/76835223/126235112-67092f3b-cd50-4558-995f-9eede599a091.png)

**Comment by gotson** [comment]
Can you describe a bit more what is the use case ? _Seeing_ something is not a compelling enough use case.

**Comment by MKH-42** [comment]
The use case is for me:
a) I want to know which book has a comicinfo.xml included. I autofill the most metada over comicinfo.xml. so it would be nice to see which book has a comicinfo.xml.
b) when I see the metada in Komga I want to see fast what is the source. Sometimes it is hard to find out why komga show me specific data. In the most cases it comes from a comicinfo.xml. Now I have to go to every book and open it with zip to search the comicinfo.xml. But Komga knows this already, because during a scan it looks for comicinfo.xml
c) special when you have a big series with 10 or more files, but only one file has a comicinfo.xml, it is hard to find out in which one it is.
d) when I see a book without a comicinfo.xml I want to update and add comicinfo.xml that komga can use it with the next scan :-)

**Comment by tomandocubatas** [comment]
It could be possible to modify  manually the comicinfo.xml from here? To change some values if is neccessary.

**Comment by gotson** [comment]
> It could be possible to modify manually the comicinfo.xml from here? To change some values if is neccessary.

No. If you need to change metadata from within Komga, you need to use the edit metadata screen.

To edit Comicinfo.xml you would need to use other external tools.

**Comment by tomandocubatas** [comment]
Yes I know it, really my idea was obtain the data os a comic from a service like comixology :P
Using the ISBN per exemplo.

**Comment by gotson** [comment]
> Yes I know it, really my idea was obtain the data os a comic from a service like comixology :P
> Using the ISBN per exemplo.

That's completely different, and covered under #11

**Comment by tomandocubatas** [comment]
Perfect!!! :)
This functionality will be great!! i will wait it with illusion.
Any way, thank a lot for your effort and patiente!!
