### ISSUE TITLE
[Bug] Comics deleted from the file system appear as "Unavailable"

### ISSUE THREAD

**Issue by valdearg** [gotson/komga#576]
### Komga environment
- **OS**:  Ubuntu 20.04
- **Komga version**: v0.109.0-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x] **I am running Komga from the `jar`**
  - Java version: openjdk 11.0.11 2021-04-20
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
I swear in a previous version, if I removed a file from the base file system it removed the comic in the web interface. 

Generally this is done when I find a higher quality copy of the comic in question.

### Steps to reproduce
1. Delete comic file from the file system
2. Allow the system to rescan

### Expected behaviour
Record in the system for the deleted file should be cleaned up and removed from the interface.

### Actual behaviour
Item appears as "Unavailable"

**Comment by Kussie** [comment]
The trash can feature was implemented recently.  There are options per library on how this is handled automatically, and the trash bin can be emptied manually

**Comment by valdearg** [comment]
Oh damn, you're absolutely correct. Set these options now and works perfectly, thanks for this.

Closed!
