### ISSUE TITLE
[Bug] Scan Library Files Crashes Docker Container

### ISSUE THREAD

**Issue by tonytonytoan** [gotson/komga#577]
### Komga environment
- **OS**: Docker Container on Windows machine
- **Komga version**: v0.109
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When I try to run `Scan Library Files` on my library, the running instance fails and I get this error:

```
mango  | Unhandled exception: UNIQUE constraint failed: titles.path (SQLite3::Exception)
mango  |   from Mango/lib/sqlite3/src/sqlite3/statement.cr:84:13 in 'exec:args'
mango  |   from Mango/src/storage.cr:327:13 in '->'
mango  |   from usr/share/crystal/src/primitives.cr:255:3 in 'start_and_block'
mango  |   from Mango/src/mango.cr:48:3 in '->'
mango  |   from usr/share/crystal/src/hash.cr:867:45 in '__crystal_main'
mango  |   from usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
mango  |   from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
mango exited with code 1
```

### Steps to reproduce
1. Go to `localhost:9000`
2. Click on `Admin` -> `Scan Library Files`

**Note:** These steps won't replicate for yourself, I imagine it has to deal with my local collection

### Expected behavior
Scanning my library is a success and I can see my collection under `Library` tab

### Log file
```
mango  | Unhandled exception: UNIQUE constraint failed: titles.path (SQLite3::Exception)
mango  |   from Mango/lib/sqlite3/src/sqlite3/statement.cr:84:13 in 'exec:args'
mango  |   from Mango/src/storage.cr:327:13 in '->'
mango  |   from usr/share/crystal/src/primitives.cr:255:3 in 'start_and_block'
mango  |   from Mango/src/mango.cr:48:3 in '->'
mango  |   from usr/share/crystal/src/hash.cr:867:45 in '__crystal_main'
mango  |   from usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
mango  |   from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
mango exited with code 1
```

**Comment by gotson** [comment]
You are using Mango, not Komga.

**Comment by tonytonytoan** [comment]
Agh! Sorry gotson, wrong repo 😂
