### ISSUE TITLE
Question about Docker, Paths, and Komga

### ISSUE THREAD

**Issue by shimizurei** [gotson/komga#578]
I have a very defined file and folder structure. Very similar to https://github.com/roboyoshi/datacurator-filetree.

I have all my manga, manhwa, and manhua housed under respective folders in the literature section. Can I use that as my data folder:

```
source: /synobox/literature
target: /data
```

(then import each type (manga, manhwa, manhua) into the app) or will it duplicate or erase all my content if I do that? I'm not very good with docker, so it's a bit confusing to me. I don't want to test it out and lose everything (100s of gigs)...

**Comment by Kussie** [comment]
The file config literally just maps the source path you specify to what it will be inside the docker container.

For example if you specify the source as "/synobox/literature"  and the target as "/data" it means that inside of the docker container, the path `/data/` inside the container will be the same as `/synobox/literature/` is locally.  

Not sure what your folder structure is like beyond the folders you specified, but i am assuming they are subdirectories for your different types ie manga, manhawa etc.  You could then setup three libraries in Komga, "Manga" (/data/manga/), "Manhwa" (/data/manhwa/), "Manhua" (/data/manhua/)

**Comment by shimizurei** [comment]
Cool. I think I'll try getting it all set up then. Thanks!
