### ISSUE TITLE
Favourite/rating system

### ISSUE THREAD

**Issue by waz1500** [gotson/komga#58]
Would it be possible to to add a rating system (possibly something like out of 5 stars) that we could use on certain manga/books and to sort via that rating. Or the alternative is to have custom lists for that purpose.

**Comment by gotson** [comment]
Custom collections #30 will cover series (I think, haven't started it).

There will be reading lists at some point too. 

I'll keep this one, it's interesting.

**Comment by Naatan** [comment]
Please consider reopening. So far this is the only feature I'm realling missing.
