### ISSUE TITLE
[Bug] Cut off some pixels in Web Reader on ipadOS

### ISSUE THREAD

**Issue by sdsd4564** [gotson/komga#581]
### Komga environment
- **OS**: ipadOS
- **Komga version**: 
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [x] **I have a problem in the web interface**
  - Browser (with version): Safari, Chrome (both on ipad)
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
The bottom of the screen is cut off even when set to fit the screen height.
120~130px seems to have been cut off. See the diff 2 uploaded pictures.
The resolution of the first picture is 2732*2048(ipad pro 3rd).

### Steps to reproduce
Reader Settings - Scale type to 'Fit height' or 'Screen'

### Screenshots
![ipad-pro-res](https://user-images.githubusercontent.com/20009099/127166472-63deb214-e60a-479e-a858-bcb06c37571f.png)
![ipad-pro-screenshot](https://user-images.githubusercontent.com/20009099/127166476-bfa7c383-b9be-4aa3-9acc-5218bf66bd01.png)

**Comment by gotson** [comment]
Could you provide:
- the version of iOS
- the version of webkit / Safari / Chrome

**Comment by sdsd4564** [comment]
> Could you provide:
> 
> * the version of iOS
> * the version of webkit / Safari / Chrome

ipadOS v14.6
I don't know how to see the safari version. Chrome is v92.0.4515.90 and 
webkit is check on www.whatismybrowser.com. 
Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1

**Comment by gotson** [comment]
Looks like it's a feature from Apple. 

I managed to find an iPad to test, seems like if you scroll down a bit to hide the address bar then the image shows in full. Can you confirm it's also the case on your iPad pro? 
https://user-images.githubusercontent.com/2139133/127799708-9b398c39-d90c-4102-a929-6d5623c71c70.mp4

**Comment by gotson** [comment]
You could try the latest `0.114.0` which has full screen support when added to home screen, that way the top bar will not change height and will not mess the css.

**Comment by sdsd4564** [comment]
> Looks like it's a [feature](https://medium.com/@susiekim9/how-to-compensate-for-the-ios-viewport-unit-bug-46e78d54af0d) from Apple.
> 
> I managed to find an iPad to test, seems like if you scroll down a bit to hide the address bar then the image shows in full. Can you confirm it's also the case on your iPad pro?
> https://user-images.githubusercontent.com/2139133/127799708-9b398c39-d90c-4102-a929-6d5623c71c70.mp4

Yep. Exactly the same situation. 
and I tested the version released today (0.114). It has improved a bit, but it seems that about 40~50px is still cut off. 
I don't know what to say... but Thank you so much for your hard work in fixing the function👍

![image](https://user-images.githubusercontent.com/20009099/127847108-6d447969-5cfa-4c23-b52a-11fbd6adc700.png)

**Comment by gotson** [comment]
> I tested the version released today (0.114). It has improved a bit, but it seems that about 40~50px is still cut off.

You mean when used after adding to home screen? I tested on the iPad I have and it fixes it completely, but different ipads may produce different results I suppose.

**Comment by sdsd4564** [comment]
> You mean when used after adding to home screen? I tested on the iPad I have and it fixes it completely, but different ipads may produce different results I suppose.

yes. above screenshot is the entered through the home screen.
I think that the fullscreen doesn't work except for the dashboard, as all of the toolbars are visible except the dashboard(all libraries, settings, viewer).

![image](https://user-images.githubusercontent.com/20009099/127854251-ee060f78-493b-438f-90e7-b8484919c864.png)

**Comment by sdsd4564** [comment]
I just checked the updated version (0.115). It works flawlessly😍
