### ISSUE TITLE
[Feature Request] Sort series by "release date"

### ISSUE THREAD

**Issue by theotocopulitos** [gotson/komga#582]
### Is your feature request related to a problem? Please describe.
Not a problem, but a desired feature: it would be great for chronological reading, if the library view (or collections for that matter), allowed to sort the series using the release date of the first book in each series…

### Describe the solution you'd like
In the library browse or collections view, when displaying  the filter/sort menu, a new option could appear under "sort", "Date released" (along with date added or date updated), so that all series in that view would be sorted according to the "Release date" of that series (i.e. the release date of the first book in the series)

**Comment by gotson** [comment]
Not included in collections, because there's no filtering at all available.
