### ISSUE TITLE
File hashing can't be disabled

### ISSUE THREAD

**Issue by smorkin** [gotson/komga#583]
I recently updated to a version where file hashing was introduced (for trash bin handling), and since I have an old server (2012 Mac mini) and a lot of files, I wanted to disable the file hashing.

Tried using command line disabling, tried using application.yaml disabling, but no matter what I try, I can't seem to disable file hashing using the documented komga.file-hashing configuration option set to _false_.

I'm running Komga using the jar file, no Docker.

**Comment by gotson** [comment]
please use the templates provided and provide all required information, including the command line you use and the `application.yml` file in full.
