### ISSUE TITLE
[Feature Request] Webreader scale: Fit to Width (shrink only)

### ISSUE THREAD

**Issue by mastafrooper** [gotson/komga#584]
### Describe the solution you'd like
Not an issue. Just quality of life. Basically, I would like a Fit to Width (Large Only) option where it would keep the normal the normal scaling of the pages until one ends up wider than the screen size then fit it to screen for just that image.

Some of the manga/comics I read will randomly throw in a double-page spread and I have to manually adjust the scaling for that page before changing it back after.

**Comment by gotson** [comment]
> I have to manually adjust the scaling for that page before changing it back after.

can you clarify which scaling you use before and after?

**Comment by mastafrooper** [comment]
> 
> 
> > I have to manually adjust the scaling for that page before changing it back after.
> 
> can you clarify which scaling you use before and after?

I normally have it set to original. When it hits the wide image set it to fit to width. Then switch back original once past the double-page spread.

**Comment by kiriya-aoi** [comment]
Fit to Width (enlarge only) sounds like: If image width is less than viewport width, enlarge it to fit width. Do nothing otherwise.

It seems like the request is actually for: If image width is greater than viewport width, shrink it to fit width. Do nothing otherwise.

Under the same scheme I would call it "Fit to Width (shrink only)".

**Comment by mastafrooper** [comment]
> 
> 
> Fit to Width (enlarge only) sounds like: If image width is less than viewport width, enlarge it to fit width. Do nothing otherwise.
> 
> It seems like the request is actually for: If image width is greater than viewport width, shrink it to fit width. Do nothing otherwise.
> 
> Under the same scheme I would call it "Fit to Width (shrink only)".

Yeah. Thats what I was after. I was just using the terminology XnView uses for its mode. I assume they meant it as it would only fit to width for large images only.

**Comment by gotson** [comment]
Anyone knows how to do that in pure css? If yes we could add this quite easily.
