### ISSUE TITLE
[Feature Request] Auto Updater

### ISSUE THREAD

**Issue by Vegeth-Blue** [gotson/komga#586]
### Is your feature request related to a problem? Please describe.
Every 3 hour an update is released... it's boring every time to open github, download the update, stop the server, replace old .jar and then restart the server.

### Describe the solution you'd like
An automatic update function. The software checks every X days (or hours) for future releases and then auto updates to the new version.
Maybe with the possibility only to notify and let the admin choose whether to update or not (some just prefer to know that there is an update instead of the software updating itself.

To update, it would be enough to start a script inside the software that does a replace of the old .jar with the one it downloaded previously (before stopping the server).
There are currently no easy-to-use scripts that do NOT require you to install 3rd party tools to download from github and shut down a .jar server.

### Additional context
It also wants to be a complaint to this system of updating builds every 3 seconds for a ridiculous bugfix. People can't stand every 3x1 reading 1 bug fix line and then update every single time. And please ... don't tell me "don't update then" because that's a ridiculous and IMMATURE answer!

**Comment by gotson** [comment]
Already requested in #141 

You could switch to using Docker, some tools like https://containrrr.dev/watchtower/ will auto update containers when a new version is released.

> It also wants to be a complaint to this system of updating builds every 3 seconds for a ridiculous bugfix. People can't stand every 3x1 reading 1 bug fix line and then update every single time. And please ... don't tell me "don't update then" because that's a ridiculous and IMMATURE answer!

Who's immature here? Don't update if you don't want to.

**Comment by Vegeth-Blue** [comment]
> You could switch to using Docker

Good answer!
Hey, I'd like to add the radio to my car ... Could we add it?
No! Switch to a Ferrari!


> Who's immature here? Don't update if you don't want to.

You don't even need to answer. Your immaturity led to that ridiculous previous answer.



> Already requested in #141

Complain to GitHub that when you search for Auto update or Autoupdate it DOES NOT come out as "SELF"

**Comment by gotson** [comment]
Clearly you have nothing to do here if you can't be respectful and polite.
