### ISSUE TITLE
[Feature Request] Numbering problem of DC comics

### ISSUE THREAD

**Issue by powerslave666** [gotson/komga#587]
### Is your feature request related to a problem? Please describe.
I do not know if it's a bug or done on purpose but I have a problem with the numbering of some comics. I have some series (ie The Flash, Wonder Woman) which change numbering within the volume but Komga does not use the numbering from the comics and use its own.
All my comics are sorted and organized using Comicrack and the information are in the ComicInfo.xml files

Let me clarify with an example:
-  The Flash was numbered 1 to 88. The one which should be issue 89 was numbered 750 and onward.
-  However, Komga numbered the issue from 1 to 88 and the 750 and onward are numbered 89.

### Describe the solution you'd like
Is there a way to force Komga to use the correct numbering?

### Additional context
Here is a screenshot.

<img width="1440" alt="Capture d’écran 2021-07-29 à 13 01 55" src="https://user-images.githubusercontent.com/79415415/127481789-d466dca0-c509-4fb0-91ed-ad292a4e26ce.png">

**Comment by gotson** [comment]
Can you activate debug logs, then perform a refresh metadata on that particular book, and attach the logs here?

**Comment by gotson** [comment]
It looks like your 89 here has a title that looks like a filename, are you sure it has a proper comicinfo.xml?

**Comment by DieselTech** [comment]
It must be either a filename or metadata issue. Running the latest release it shows the proper numbering for me

![image](https://user-images.githubusercontent.com/30128380/127918585-04d40ce3-90d4-46a1-bd09-e07953e6b830.png)
