### ISSUE TITLE
[Feature Request] Ajout d'une option pour signaler une série comme "complète"

### ISSUE THREAD

**Issue by MagikarpLaCarpe** [gotson/komga#588]
### Le soucis : 
J'ai quelques séries qui sont complètes et d'autre non, actuellement il y a une « solution » qui consiste à simplement ajouter « ( Complet) » à la fin du nom ce qui en soit modifie le nom de la série. Malheureusement sans ça, il est difficile de voir quelle collection et/ou série il nous reste à compléter et sans modifier le titre de la série il est difficile de voir rapidement et facilement les séries complétés (et aussi filtrer du coup pour voir uniquement les séries complètes).

### Solution(s) : 
Ajout d'une option dans les séries qui permettent de marquer la série/collection comme complète, et d'afficher par exemple une pastille sur la cover et/ou de l'ajouter à la catégorie "série/collection complète").

**Comment by gotson** [comment]
Tu peux deja mettre le status de la series a `En cours`, `Terminée`, `Hiatus` et `Abandonnée`.

Est-ce que par `Complet` tu veux dire que la serie est terminée, et que tu as tous les tomes ? Et une series incomplete, c'est une serie terminée, mais dont tu n'as pas tous les tomes ?

Si c'est ca alors https://github.com/gotson/komga/issues/298 devrait pouvoir t'aider, tu pourras dire qu'une serie compte au total 6 tomes par exemple, et si tu n'en as que 5 alors tu verra `5 / 6`.

Sinon tu peux aussi utiliser les tags plutot que de changer le titre.

**Comment by MagikarpLaCarpe** [comment]
`Est-ce que par Complet tu veux dire que la serie est terminée, et que tu as tous les tomes ? Et une series incomplete, c'est une serie terminée, mais dont tu n'as pas tous les tomes ?`
Oui c'est exactement ça


`Si c'est ca alors #298 devrait pouvoir t'aider, tu pourras dire qu'une serie compte au total 6 tomes par exemple, et si tu n'en as que 5 alors tu verra 5 / 6.`
D'accord ça serait l'une des solutions mais je vois que ça utilises les metadata ma demande aurait plutôt été directement avec komga et que ça soit put dans la DB. Mais la solution alternative peut aussi être une bonne solution

**Comment by gotson** [comment]
Qu'est ce que ça veut dire "directement avec komga" pour toi ? Les metadata font partie intégrante de Komga.

Avec #590 tu pourra voir les séries finies mais incomplètes. Par contre il faudra que tu renseignes le nombre total de livres pour tes séries pour que ça marche.

**Comment by MagikarpLaCarpe** [comment]
J'entends de fonctionner sans metadata et pouvoir facilement mettre une série en complète via l'interface web, mais je pense qu'au final j'utiliserais ce système via les metadata, ça évitera des ajouts semi utile

**Comment by gotson** [comment]
Oui, complet n'a de sens que si la série est finie et si tu as autant de livres que le total. Du coup ça passera par les metadata forcément.

**Comment by MagikarpLaCarpe** [comment]
Oui je pensais à ça, marquer une série comme étant "complète" dans notre bibliothèque. Je pense qu'on peut donc clore l'issue, merci pour la réponse !
