### ISSUE TITLE
[Bug] search doesn't work well with CJK

### ISSUE THREAD

**Issue by v1006945671** [gotson/komga#592]
### Komga environment
- **OS**: SYNOLOGY DMS7.0
- **Komga version**: 1.1.3
- [ latest] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Some file names cannot be searched. Only the full name is OK.

### Steps to reproduce
1. Put comic books in the library,
2.  search for some names，Click search

### Screenshots
![路径](https://user-images.githubusercontent.com/22139286/127760153-0f9a0807-def0-4b96-98e7-cb7eb8af6f05.jpg)
![搜索不出结果](https://user-images.githubusercontent.com/22139286/127760155-7bba6487-80de-4333-93fd-661506611dfe.jpg)
![全称正常](https://user-images.githubusercontent.com/22139286/127760273-a4bcf7ae-5ecd-4103-bdfa-ae7bf5d7c1e5.jpg)

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

**Comment by gotson** [comment]
Could you paste here :
- the filename of one of those files
- the search text you used

I can't type Chinese, so using your text will be easier for me to reproduce and test.

**Comment by v1006945671** [comment]
Path：\\DS220\comic\library\连载\不道德公會
file name：不道德公會

**Comment by v1006945671** [comment]
> Could you paste here :
> 
> * the filename of one of those files
> * the search text you used
> 
> I can't type Chinese, so using your text will be easier for me to reproduce and test.

**Comment by azuki126-aa** [comment]
The same phenomenon occurs even if the file name is Japanese.  Also, if there is an English or symbol after Japanese in the file name, it will be recognized by the characters up to that point.

**Comment by gotson** [comment]
> The same phenomenon occurs even if the file name is Japanese. Also, if there is an English or symbol after Japanese in the file name, it will be recognized by the characters up to that point.

Yes, CJK stands for Chinese Japanese Korean, it will impact any language without separators (space or others).
