### ISSUE TITLE
[Feature Request] Set Library Creation Default Settings

### ISSUE THREAD

**Issue by Budlyte** [gotson/komga#593]
- Issue:
Currently when creating a new library, the system uses the same set of default checkboxes each time. This becomes extremely cumbersome if adding dozens of libraries that all need the same set of boxes checked on or off.

- Proposed Solution:
Allow setting a new Default in the Server Settings menu.

**Comment by gotson** [comment]
You don't add a library everyday, and we're talking about 10 clicks max. That doesn't seem worth it.
