### ISSUE TITLE
[Feature Request] Automatic Library Creation

### ISSUE THREAD

**Issue by Budlyte** [gotson/komga#594]
- Issue:
If libraries are created from separate directories, such as creating individual libraries for each Publisher, it will become cumbersome to create a new library each time a new Publisher is added.

- Proposed Solution:
Create an option to automatically create libraries for each subfolder in a main directory, ignoring selected folders or patterns (IE "@eaDir"), and create new libraries in the future when new directories are found and following settings that are determined in the "Scheduler".

Yes, I understand that the library organization used in this project isn't built so that each publisher should have its own library but doing so fixes the issue of some comics having incomplete metadata then not showing up using the filter on the right.

Some of this may tie into Issue #593

**Comment by gotson** [comment]
Looks like a really niche feature.

**Comment by Budlyte** [comment]
Is there currently a way to filter to comics that have no publisher? Such as an "Unassigned" category?  Currently adding each publisher as a separate library seems like the best way to ensure that comics that have incomplete metadata land in the appropriate publisher.  And since each needs its own library, then adding new publishers requires creating a new library.

**Comment by gotson** [comment]
> Is there currently a way to filter to comics that have no publisher? Such as an "Unassigned" category? Currently adding each publisher as a separate library seems like the best way to ensure that comics that have incomplete metadata land in the appropriate publisher. And since each needs its own library, then adding new publishers requires creating a new library.

not at the moment, no.
