### ISSUE TITLE
[Feature Request] My list feature on dashboard

### ISSUE THREAD

**Issue by simian** [gotson/komga#595]
### Is your feature request related to a problem? Please describe.
Dashboard has "Keep Reading" for issues in progress and "On deck" for series in progress but nothing for series wanted to be read but not yet started.

### Describe the solution you'd like
An example of this is Netflix it has the continue watching row and also the My list row. 
For Komga we could have a My List or similar name row. You could add an entry on the drop down menu for a series to add to My List which would make the series appear in the list. Then for series already in that list the entry could change to remove from my list. See image for example of My List section on Dashboard.
![Komga My List Example](https://user-images.githubusercontent.com/4390855/127922228-3c219c26-5686-474a-bd8e-92456fa6a226.png)

### Describe alternatives you've considered or other apps that can do what you want
Netflix, disney have a similar system

### Additional context
Why is it needed? When a new series comes out that I might want to read if there is no reminder system then you have to regulary look in teh library to try and determine what to read. This allows you to keep on the Dashboard more. Check the recently released section for new stuff, add it to my list.

**Comment by gotson** [comment]
> Netflix, disney have a similar system

I never used any of those, could you maybe post screenshots or videos of the whole flow of adding things to that list, removing, or the dashboard?

Some other questions I have :
- does those list show series or episodes?
- how are they removed? Only manually, or after being watched, or both?

**Comment by simian** [comment]
Here is a video of how it works on Netflix

https://user-images.githubusercontent.com/4390855/127950000-f8923ee0-ffb0-4634-ba60-3341822862d6.mp4

Ì think it makes most sense for only Series to be added - you wouldn't want to add say 50 issues for the same series all showing separately as it would be an unmanageable list.

Normally an item would only be removed from the list if you manually remove it - its kind of your list, you add to it you remove from it, you look after it.

For adding in Komga I think the easiest way would be to add to the drop down menu to a series just like you have for collections - quick mock up:
![Add to my list](https://user-images.githubusercontent.com/4390855/127950386-e48acde5-5076-4b3c-b4a4-4347ebb12b79.png)

Then to remove you would have the entry change to "Remove from my list".

That way when on the dashboard I would be looking at the recently added series row for anything I think could be good, use the menu to add it to my list. as few months later when there is say 3 or 4 issues I might start reading and its waiting there in my list. I would probably remove it from "my list" once I started reading as it will be in the on deck section then.

You could have the list viewable on a separate screen as well for management (like the Netflix example) but probably not needed.

**Comment by gauthier-roebroeck-mox** [comment]
In Netflix, could you add a season, or an episode to My List ? For example i want to start watching Top Gear, which has a bazillion of seasons, but i want to start at Season 10. Can i do that? Or even add episode 5 of season 8 ?

**Comment by gotson** [comment]
In Netflix, can you add a season or an episode to My List? For instance if you want to start watching a show at season 5, or at a specific episode?

**Comment by simian** [comment]
You can only add a series so all seasons and episodes will be under that but you can choose what you want to watch as when you click on the item it takes you to the series page which lists the episodes by season. You cant add individual seasons or episodes by themselves to the list. The series will stay there even if you finished all current seasons, then when a new season is added to netflix you can click back on it and it will show on the series page.

You can add individual movies to your list. They also stay there until you manually remove them even if you have watched them.

**Comment by gotson** [comment]
Thanks for clarifying.

Someone else floated around the idea that the On Deck section could become a bit more dynamic, in a way where you could add or remove stuff from On Deck. This is quite similar to what you are requesting, but a bit more flexible too, because On Deck also would have some business logic built-in, like if you read something, it gets removed from On Deck, but the next unread item from that series would be added instead.

**Comment by simian** [comment]
Yeah a more dynamic on deck would acheive the same sort of thing I want - but with a bit more smarts behind the scenes!
