### ISSUE TITLE
[Feature Request] Show books when filtering by tags match tags on a book

### ISSUE THREAD

**Issue by donotos** [gotson/komga#596]
### Is your feature request related to a problem? Please describe.
When i filter by tags, it only show the series even when the tags are on a book.

### Describe the solution you'd like
It would be more logical that when you filter by tags, the results would show the book if the matching tags are on a book and the serie if they are on a serie.

### Additional context
for exemple , if i have the harry potter serie in my library and that i filter the tag "children" komga will show me the harry potter entire serie but the tag "children" is only on the first 2 books.

**Comment by gotson** [comment]
What view/screen are you referring to?

**Comment by donotos** [comment]
when i'm in the root of the library (browse)

**Comment by gotson** [comment]
That view show series, not books. The grid view only show one kind of item. It's not possible to show books in that view, and wouldn't make sense.

You can drill down in the series shown, and in the series view you can filter books by tags.

**Comment by donotos** [comment]
it's not ideal when you want to filter between all your series. i'm thinking about anthologies or sagas where sometimes the books are their own story or are loosely related to each other. I do understand the logic of komga when it comes to series>books but i find limitations in it. it's a specific need, but maybe creating a view dedicated to books regardless of their respective series could be a way to do it.

**Comment by gotson** [comment]
You can use the advanced search keywords to achieve this.

There's no plan to add a book view outside of series / readlists for now.
