### ISSUE TITLE
[Feature Request] Search by tags in the search bar

### ISSUE THREAD

**Issue by donotos** [gotson/komga#597]
### Is your feature request related to a problem? Please describe.
Add the possibility to search by tags in the Full Text Search

### Describe the solution you'd like
the same pattern as the existing one for publisher.
ex: tags:your_tag
with the ability to use the AND, OR and NOT operators.
ex: tags:your_tag AND tags:your_2nd_tag

### Describe alternatives you've considered or other apps that can do what you want
anything that can be user to search on tags

**Comment by gotson** [comment]
The problem with this is that the search is done on all indexed fields, so searching by a tag like `hero` will also match all the titles matching `hero`.

There is also the issue of context, ie why the results are shown. Adding more and more index fields will result in broad searches, reducing the relevance of results because too many fields are matching.

**Comment by donotos** [comment]
there already is a "publisher" search where you restrict your search to a specific field using "publisher:". i think it should be done the same way for tags.

**Comment by gotson** [comment]
> there already is a "publisher" search where you restrict your search to a specific field using "publisher:". i think it should be done the same way for tags.

But if you search for `dc` it will match all series published by DC comics.

**Comment by gotson** [comment]
I'm currently rewriting the whole full text search because of limitations (#592). It seems like we could set some fields as default fields (ie title, publisher, isbn), while others would have to be specified explicitly (tags for instance). 

I need to test it out, see if that works.

**Comment by donotos** [comment]
looks good to me.

**Comment by thampp** [comment]
I was wondering about the ability to (full text) search for author information. I guess the approach discussed here could cover that as well: Among the list of tags that would have to be specified explicitly it would be great to also have writers, pencillers etc.

**Comment by gotson** [comment]
> I was wondering about the ability to (full text) search for author information. I guess the approach discussed here could cover that as well: Among the list of tags that would have to be specified explicitly it would be great to also have writers, pencillers etc.

that's also something i want to test.
