### ISSUE TITLE
[Bug] The number of tasks is always more or less the same.

### ISSUE THREAD

**Issue by tomandocubatas** [gotson/komga#598]
Hi, 
I have a problem that i've detected from the las versions of Komga. I don't know if the problem is only en my Komga,
The number of taks is always more or less the same. Yo can see the image attached.

![imagen](https://user-images.githubusercontent.com/36165495/128005463-c1c65448-f8d4-40b4-b1e7-7bba00d367e0.png)

My impresion is that the process dosen't finish never, sometimes there are a little less tasks, but 5 minutes after we have the same. The server is running from 2 day ago and the number of task is similar all the moments. I dont know if there are some bucle, my library is very large.
Are there any option to see which is the problem?

If  is necessary to aport more info let me know it.

Thanks in advance.

**Comment by gotson** [comment]
Please use the templates, they are here for a reason. Logs would also help.
