### ISSUE TITLE
[Feature Request] Removal from On Deck Section

### ISSUE THREAD

**Issue by foinse** [gotson/komga#599]
### Is your feature request related to a problem? Please describe.
The Home dashboard has an On Deck section. There have been times that I would start reading a comic book, but after a couple of issues decide to drop the series. This series will continue to show up in On Deck until I manually set the unread comics to read or vice versa. 

### Describe the solution you'd like
An option to remove from On Deck, similar to Plex's "Remove from Continue Watching"

### Describe alternatives you've considered or other apps that can do what you want
Plex's "Remove from Continue Watching" option

### Additional context
I would prefer not to have to artificially mark issues as read or unread when I am no longer interested in reading the comic or volume and I think having comics in On Deck that I don't want to continue makes the On Deck section less concise and useful.

**Comment by Kussie** [comment]
This would be nice, i have the same use cases as well.
