### ISSUE TITLE
komga displaying wrong format for content

### ISSUE THREAD

**Issue by waz1500** [gotson/komga#60]
Running version which is v0.11.0-master in docker format. 

I know metadata scraping is still in it's infancy. I've noticed komga is displaying the wrong format for my test content.

- It's displaying the format as `CBZ` for manga that is zipped and ending in `.zip format`. I was expecting to see the "zip" label instead.  

- It's displaying the format as `CBR` for manga that is rar'd and ending in `.rar format.` I was expecting to see the "rar" label instead.  

My manga are compressed in .zips or .rar and all in it's own subfolders which is usually the title name and contain the images in jpeg's.
```
├── Manga Title.zip/
Manga Title
│   ├── 1.jpeg
│   └── 2.jpeg
│   └── 3.jpeg
and so on. 
```

**Comment by gotson** [comment]
Those are the same.

It's not displaying the extension (which you have in the filename just under), but a projection of the mediatype to something people understand better. 

Actually the format is something like `application/zip`, but I prefer to display CBZ in the interface.

It's still a comic book archive, and it's zipped, so it's a cbz 😉
