### ISSUE TITLE
[Feature Request] Ability to exclude certain libraries from the Recommendations/carousels on the main Home screen

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#600]
A thought occurred to me whilst reading an earlier ticket and prompted me to raise this as a separate ticket.

### Describe the solution you'd like
At the moment every single library is included in the "On Deck" and Recent lists on the "Home" screen.  The ability to limit what appears on this screen would be a much welcome addition.  Though it would only apply to "Home" those excluded libraries would still work as they currently do when in the "Library" view.

The main use case for this would be for things such as hiding NSFW libraries from appearing on the main screen, but also allows for a bit more control even for those without NSFW content over what appears on the screen.

**Comment by gotson** [comment]
Duplicate of #229
