### ISSUE TITLE
[Feature Request] Reset zoom when going to a new page in web reader

### ISSUE THREAD

**Issue by jwm-evans** [gotson/komga#602]
I usually zoom in when reading a double page spread. This allows me to read the page easily, but when I go to a new page, I am still zoomed in and have to zoom out again.

### Describe the solution you'd like
My desired behaviour is as follows: I zoom in on a page (no necessarily a double page spread - sometimes there's a small detail I want to see better on a single page). I pan around and when I want to view the next page, I swipe until I am at the far right of the page and swipe once more. This takes me to the next page & resets the zoom to the default level.

### Describe alternatives you've considered or other apps that can do what you want
 In Tachiyomi, when I go to a new page, the view resets to my specified view mode (usually fit-to-screen), which if far more convenient. It also seems to remember that I was zoomed into a page: if I go back to the zoomed-in page, it is still zoomed in.

**Comment by gotson** [comment]
There's no zoom feature in the webreader, so if you are zooming it's using your device zoom, meaning we can't do anything about it from the app.
