### ISSUE TITLE
Editable On Deck

### ISSUE THREAD

**Issue by gotson** [gotson/komga#603]
Currently the On Deck section is a read-only view of books, per user. It shows the first unread book of any Series that is in progress (at least 1 book read).

This poses a couple of problems:
- one cannot remove anything from On Deck (#599), for example if you decide to drop a series after a couple of issues read. It would continue to show.
- if you decide to start reading a series in the middle, On Deck would always show the first unread book, not the first unread after what you have read already.
- you can't add anything to On Deck, for example to use it as some kind of bookmark, or for things you want to read later, but for which you don't want to create a read list (#595)

In order to provide those features, On Deck should become a domain entity instead of a view, and books would need to be added/removed from On Deck, per user, after certain events occur.

The On Deck lifecycle should be:
- Assumption 1: On Deck is for unread books only, it cannot and should not contain in progress or read books. In progress books are already showing in the Continue Reading view.
- after a book is marked as read:
  - that particular book is removed from On Deck
  - the next unread book in that series after this book is added to On Deck
  - Example: Book 3 is On Deck. Book 3 is marked as read. Book 4 is already read. Book 5 is unread, and is added to On Deck.
- after a book is marked as in progress, it is removed from On Deck. It will be showing in Continue Reading automatically.
- an unread book can be manually added to On Deck.
- if a series has unread books, it can be manually added to On Deck, in which case the first unread book in the series is added to On Deck.
- All books added to On Deck have an `addedTimestamp`, and On Deck is sorted by `addedTimestamp` descending by default.
- when a new book is added to a series, and if that series was completely read, On Deck should be updated to show that book. This is automatic in the current implementation, but would require specific logic in the new one. 

Open questions:
- is **Assumption 1** relevant?

**Comment by suppo77** [comment]
I think it's very interesting to have this improvement for the On-deck functionality. I would also suggest having additional reading status on the individual comic. In fact, it often happens that you want to skip reading a number that is in the collection (for example if you are following a particular reading order on a character). Something like "discarded" or "not interested". Comics marked in this way should then not be visible in the on-deck list.
