### ISSUE TITLE
[Bug] Short description

### ISSUE THREAD

**Issue by donotos** [gotson/komga#604]
### Komga environment
- **OS**: Debian
- **Komga version**: v0.116.0
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
The new full text search has incorect behavior for tags:

book_tag:my_tag > do not display matching books but the series that contain the books

### Expected behavior
only books should be displayed here.

### Actual behavior
the series containing the matching books are displayed

**Comment by gotson** [comment]
`book_tag` will match the book tags aggregated at series level, as per the documentation describes.

To search books with tags, use the `tag` field.
