### ISSUE TITLE
[Feature Request] displayed search result are too few

### ISSUE THREAD

**Issue by donotos** [gotson/komga#605]
### Is your feature request related to a problem? Please describe.
When using full text search only a small number of results are displayed (more or less 50)

### Describe the solution you'd like
a way to browse all matching content

### Additional context
it was not especially relevant before when you could only search titles which would not return a lot of result but with the full text search now able to search metadatas it is necessary to change that.

**Comment by gotson** [comment]
Search returns a maximum of 20 results per category (Series, Book, Collection, Read List).

**Comment by gotson** [comment]
One thing I thought about was to make the horixob sliders expandable. At the moment they only show x items. We could have a `+` icon at the ens of the slider to load more results.

Would that address your need?

**Comment by donotos** [comment]
the + icon is a good idea. Could you implement it so that when we click on it it display the result in multiples lines (as much as your browser window allow) instead of only one line.

thanks.

**Comment by gotson** [comment]
> Could you implement it so that when we click on it it display the result in multiples lines (as much as your browser window allow) instead of only one line.

It's not what the slider is made to do, given different kind of items are shown on each line.

**Comment by donotos** [comment]
simply adding a + button will resolve the issue and it will be good enough.
Thanks.
