### ISSUE TITLE
[Feature Request] Ability to clear/dismiss and to edit the active search expression in UI

### ISSUE THREAD

**Issue by thampp** [gotson/komga#606]
### Is your feature request related to a problem? Please describe.
When I want to either dismiss or edit a active search there is no direct UI interaction to accomplish that.
Not having an edit is especially annoying when complex queries don't work because of a typo. This is becoming more frequent with the new (great!!!) full text search.  Currently I need to select and copy the active search expression from the browser and paste it back into the search edit box to correct a typo. An edit element could do that copy/paste for me.
Dismissing a query is possible by clicking on the left but it loses context. Ideally a dismiss would put me in the context from which I a started the search.

### Describe the solution you'd like
The UI already shows the last query. For me it would be perfectly fine to have an edit icon (e.g. pencil) and a cancel icon (e..g X). There is lots of screen space to the right.

### Additional context
The edit elements could go to the right of the search expression.
![image](https://user-images.githubusercontent.com/13353725/128687791-84066edd-9db1-4a72-90c9-548dce5cbf29.png)
An alternative UI rendering I have seen is to just leave the search expression in the edit box and show x to right. Zenhub search does it like that.
![image](https://user-images.githubusercontent.com/13353725/128690936-8a2551d2-86f2-4628-81b7-ee9b21b8136b.png)
Git Issue search also leaves the search expression editable but places the clear/dismiss below
![image](https://user-images.githubusercontent.com/13353725/128691219-1189442c-2ed4-40da-bd95-54086ba653af.png)

**Comment by gotson** [comment]
The difference with github is that the search box is specific to issues, and is distinct from the top search bar. In Komga, there's only a global search box.

The edit icon next to the search text could work, however I don't quite understand the following :

> Ideally a dismiss would put me in the context from which I a started the search.

What does that mean exactly? Could you explain with an example maybe?

**Comment by thampp** [comment]
With context I mean the specific library or series or even book that is active before I initiate the search. I think that always reflected in the URL.

When I enter a search expression I am taken to the search result list screen "context" - also reflected in the URL.
Assuming I can dismiss the search in that search context  e.g. by clicking on a future X element: Where would I be taken? 
One option would be a "all results view"? The Libraries view? One specific library? ...
My current workaround without the X is to click on the Libraries view. But then I lose my old context. Often I don't mind much and I just refine my search. But when my search was triggered by something I realized when looking at a specific series or library page then I feel like taken out of context and it makes the experience less smooth.

This is nothing deep and critically important. But some well-defined landing place after dismissing a search must be defined anyway. I know perceptions vary but last active URL/context before search just feels most "natural" for me.

**Comment by gotson** [comment]
I think you may have overlooked how the search bar works. When typing text in the search bar, you are not taken anywhere. Results are showing directly under the search bar, and you can click to go to any of the item's page.

If you click "search all" or press enter, however, you are taken to the detailed search results page. Navigation happened, so you already switched "context" as you say.

If you don't want to switch context, don't press enter. The search results are updated live as you type in the list below the search bar.

**Comment by thampp** [comment]
I know how the incremental search result in the search bar works. 
But incremental search is mostly helpful for searches that target a single book or series. If you want to check out all books or series by a given author it's much nicer to look at the search result page that can give better overview of multiple results.
As I wrote above this is nothing deep and critically important.  But if you decide to implement dismissing an active search then some decision has to be made anyway what behavior to implement. I can live with an empty search result screen or being taken to the All Libraries as well. There is always the browser back button to go back in context.

Since you brought up the incremental search behavior:
It won't help when the new, more powerful full text expression are typed. When starting to type something like `author:(sean murphy)` it won't help.
Now that I think about it: Did incremental search change it's behaviour? I now end up adding wildcard * to my half completed searches to get early prefix search results. I don't remember doing that in the past. Right now the first meaningful results only come in once I completed the first full word (or by adding a * to trigger early prefix results).
Did incremental search work as prefix search in the past? If so: Will you bring that behaviour back? I tend to prefer prefix search semantics for incremental search UIs.

**Comment by gotson** [comment]
> But incremental search is mostly helpful for searches that target a single book or series. If you want to check out all books or series by a given author it's much nicer to look at the search result page that can give better overview of multiple results.

You get the exact same results, only the display is different. 

> But if you decide to implement dismissing an active search then some decision has to be made anyway what behavior to implement. I can live with an empty search result screen or being taken to the All Libraries as well.

There is nothing to implement in that regard. The search details screen _is_ a navigation point. You can't dismiss a screen you navigated to. It doesn't make sense in that context, it only makes sense to dismiss text from the search as you type bar. 

> It won't help when the new, more powerful full text expression are typed. When starting to type something like `author:(sean murphy)` it won't help.

It won't help _what_? I don't understand. 

> Now that I think about it: Did incremental search change it's behaviour? I now end up adding wildcard * to my half completed searches to get early prefix search results. I don't remember doing that in the past. Right now the first meaningful results only come in once I completed the first full word (or by adding a * to trigger early prefix results).

It has changed with the first full text search and this one also. Read the documentation : https://komga.org/guides/search.html

Full text search works on complete tokens, ie full words. Searching by prefix does not return the same results, with the same relevance, as searching by words. 

> Will you bring that behaviour back? I tend to prefer prefix search semantics for incremental search UIs.

Unlikely, on big libraries those searches do not bring very relevant results, similar to a simple _contain_. When you have 80k books it's close to useless.

**Comment by thampp** [comment]
Regarding :

> It won't help what? I don't understand.

When I type something like `author:(sean murphy)` the current incremental search behavior will show a sporadic result once I completed typing "author" -which is does not match my search intent- and nothing after that until the very end. That's OK. It just means that for complex searches with field names and operator it does not help as much as it does for simple multi-word searches.

Regarding the value of prefix search vs. token search: Sure precision and relevance won't be high on short prefixes. And it puts a burden on the search backend. I no longer work in search engine development but I did for 10+ years and I think there is clear industry and design trend towards nevertheless using incremental prefix searches even in situations where there are huge potential result sets that the prefix search may produce. It gives users a chance to shortcut to a desired earlier. 
Users today expect some immediate feedback that is updated with each character types. In most search UIs it is "just" query suggestions and not result lists. But anything that gives users a chance to not have to fully type their query is considered better than nothing. Typical relevance sorting will prioritize full token matches over prefix matches for a a wildcard search so relevance in the top 10 results is not abysmal. And as you can see from Spotify and Apple Music some popular UIs not only suggest queries but show full result lists updated with each typed query character just like Komga did in the past. Some UIs switch to use the regular tokenized search once enter is hit to allow for better relevance and precision and give users the best of both worlds (Apple Music works like that). 

![image](https://user-images.githubusercontent.com/13353725/128886445-80c3b9c3-1843-4694-9458-6a2f3b89f337.png)
![image](https://user-images.githubusercontent.com/13353725/128888703-8041fdc7-e85c-475c-91c4-75862beb2daf.png)
![image](https://user-images.githubusercontent.com/13353725/128881516-59d0d5d2-9fac-4729-9d03-5b6218a40243.png)
