### ISSUE TITLE
[Bug] High CPU usage and slow scan speed

### ISSUE THREAD

**Issue by xx255q** [gotson/komga#607]
### Komga environment
- **OS**:  Win10
- **Komga version**:  Latest

- [ ] **I am running Komga from the `jar`**
  - Java version:  0.116.0

### Describe the bug

I was using .98.0 before since the switch CPU is constantly being maxed out, the disk that has all the comics is not being maxed out. But it is taking longer to scan/detect for new updates

### Steps to reproduce
The normal scan

### Expected behavior
overall low cpu usage a fast scanning like in .98

### Actual behavior
High cpu usage and scanning taking much longer

### Log file
Many lines of this:

2021-08-10 00:12:20.554  INFO 2264 --- [org.springframework.jms.JmsListenerEndpointContainer#2-1] o.g.k.application.tasks.TaskReceiver     : Sending task: HashBook(bookId='04P8KQKW2923J', priority='0')

**Comment by gotson** [comment]
File hashing has been added to handle the trash can. See https://komga.org/guides/trash.html

Either let the hashing finish, or disable it.
