### ISSUE TITLE
[Feature Request] Make disabling hashing an button you can just click in GUI

### ISSUE THREAD

**Issue by xx255q** [gotson/komga#609]
### Is your feature request related to a problem? Please describe.
I tried to figure out how to disable it by going to here https://komga.org/installation/configuration.html#optional-configuration but I cant figure out how, I dont understand either jave or coding or both and keep failing

### Describe the solution you'd like
Just make it a button please because this hashing is killing my computer

**Comment by Kussie** [comment]
You don't need to understand java or coding...

As per the docs, you just need to add either `--komga.file-hashing=false` as a parameter if you are launching via the CLI.  Or if using Docker can add a KOMGA_FILE_HASHING environment variable
