### ISSUE TITLE
[Feature Request] Metadata Field "Translator"

### ISSUE THREAD

**Issue by GlassedSilver** [gotson/komga#614]
### Describe the solution you'd like
Pretty much what the title says. Oftentimes for manga there's one or two groups who translate a work. So maybe allow for multiple mentions.

### Describe alternatives you've considered or other apps that can do what you want
Right now the title of the chapter still contains the group(s) making said title look a bit cluttered and needlessly long. Not really a good alternative.

**Comment by gotson** [comment]
Probably relevant to use the `Authors` field with a new role.
