### ISSUE TITLE
Files not found in library on a fresh install

### ISSUE THREAD

**Issue by paynent** [gotson/komga#616]
### Komga environment
- **OS**:  Server Core 2019
- **Komga version**:  0.115.1 & 0.116.1
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [x ] **I am running Komga from the `jar`**
  - Java version: openjdk 16.0.2
- [ x] **I have a problem in the web interface**
  - Browser (with version):  Edge Chromium 92.0.902.73
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Library scan is not finding any files. Files are stored on file server. Komga is running as a service with a service account that has full access to the file server. Used unc path and junction path to try to get the files

### Actual behavior
What happened instead.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.
![image](https://user-images.githubusercontent.com/66497702/129431947-d95c03a4-5ae1-4907-aac1-d0589fe4b864.png)
[komga.log](https://github.com/gotson/komga/files/6985794/komga.log)

**Comment by gotson** [comment]
Can you give more details on the file server setup?

**Comment by paynent** [comment]
> Can you give more details on the file server setup?

What specifically?

Its on another server 2019 core. Everything is domain joined. NTFS share Domain service account that has full access to the files. Everything worked back with 0.72 a Komga extension update in Tachyomi forced me to update the server. Hence how this whole issue started.

**Comment by paynent** [comment]
@gotson 

Just to add more troubleshooting steps. As a test I ran 0.116.1 from my windows 10 desktop and pointed to the same library and the issue persisted. I then went to your releases back to 0.72 and ran it and its finding everything, no issue. Obviously there are probably a million changes between those two versions... but something is different that is preventing my domain joined NTFS file share setup from working.

**Comment by gotson** [comment]
Can you try a simpler setup without the file server, maybe just a couple of files on a local drive, so we can narrow the problem down?

**Comment by paynent** [comment]
> Can you try a simpler setup without the file server, maybe just a couple of files on a local drive, so we can narrow the problem down?

Works fine if I move some files to the local drive on the Komga server. Usually if something has an issue with a unc path creating a junction fixes it... but both have issues.

**Comment by gotson** [comment]
Can you enlighten me about what's a junction in that context?

**Comment by gotson** [comment]
Could you also enable `TRACE` logs and perform a scan, then provide the logs?

You can check [here](https://komga.org/faq/#using-the-jar-via-the-command-line) on how to do this, just replace `DEBUG` by `TRACE`.

**Comment by Kussie** [comment]
A junction is basically windows version of a symbolic link.

have you tried the ip instead of UNC path just as a further step.

**Comment by paynent** [comment]
> A junction is basically windows version of a symbolic link.
> 
> have you tried the ip instead of UNC path just as a further step.
@gotson 

Correct. So that UNC is mapped to C:\Links\ on my server as well.

Interestingly enough the IP does work. But I'm not entirely sure why the DNS or FQDN isn't working to find the files? If I put the FQDN in KOMGA sees the folders when I click the Browse button when setting up the path:
![image](https://user-images.githubusercontent.com/66497702/129445249-ea58ee3c-1183-44fc-92bb-cb35115ea258.png)

And when I am on the server itself and cd into the junction path I can see the individual files... so DNS is working.. The scan just doesn't like if for some reason?
![image](https://user-images.githubusercontent.com/66497702/129445348-ae91aeb9-653e-4074-a976-68a40092f543.png)

**Comment by paynent** [comment]
> Could you also enable `TRACE` logs and perform a scan, then provide the logs?


Also here are those Trace logs. Peeking at them the traces seem like they are seeing the cbz files in the scan... but just are not adding them to the library... Again not sure why it works with IP, but not DNS... because it can see them... and not sure what changed since 0.72

[komga.log](https://github.com/gotson/komga/files/6986426/komga.log)

**Comment by paynent** [comment]
> > A junction is basically windows version of a symbolic link.
> > have you tried the ip instead of UNC path just as a further step.
> > @gotson
> 
> Correct. So that UNC is mapped to C:\Links\ on my server as well.
> 
> Interestingly enough the IP does work. 

So... unfortunately... The IP only seemed to work once... I went back to try to get a trace with the IP instead of the FQDN and issue is now happening with the IP. 

[komga.log](https://github.com/gotson/komga/files/6986452/komga.log)

**Comment by paynent** [comment]
@gotson 

I was doing some troubleshooting today. I decided to figure out which version things stop working on. So everything works in version 0.79 and earlier, but it breaks in 0.79.1

IP doesn't seem to make a difference... IDK why it worked that one time. I've tried multiple times with both.

**Comment by gotson** [comment]
I have a hunch that the file attributes are incorrect or unavailable when accessing via the NTFS share, while the scan checks for regular files.

I'll need to add more logs and provide you a new `jar` to try out.

**Comment by paynent** [comment]
Sounds good. thanks

**Comment by gotson** [comment]
On the `dir` result in your screenshot above, the mode seems to indicate that the file is a link.

I'm not familiar with NTFS, is that normal for a junction point?

Could you perform a dir for both files and folders in the junction point, and in the unc path directly?

**Comment by paynent** [comment]
the L in mode means that that file has a junction point. Even if I viewed properties on the file form the server itself it would have that L attribute. 
![image](https://user-images.githubusercontent.com/66497702/129478018-4bb24fa1-da54-4dbf-81d9-82b695d80c2f.png)

I cannot do a dir from a UNC path in windows but i can do some powershell to get the same info. So as you can see from the hard disk on the file server and the junction path and the unc path the file attributes are all the same.
![image](https://user-images.githubusercontent.com/66497702/129478088-db3d293c-260d-4a61-9e88-61f8975eb8b6.png)

One more screenshot this is the file attributes from a desktop link to VLC. The tell for a "link" is the .lnk ending at the end of the file name where the (l) attribute just means that file has a symbolic link (not that it is one.)

![image](https://user-images.githubusercontent.com/66497702/129478133-64877c1a-6c81-43e8-bc02-27acfe46c106.png)

**Comment by gotson** [comment]
Could you try a `fsutil reparsePoint query <file>` on one of the file, and paste the output?

**Comment by paynent** [comment]
![image](https://user-images.githubusercontent.com/66497702/129478668-905f95a5-ab1b-4d2d-bf8c-1dc1d5af46ce.png)

**Comment by paynent** [comment]
@gotson 

So following your lead I did some testing. I created a new share on the same server that is not under the junction folder, I moved a couple comics over and it seems to work. It looks like it must have something to do with the L attribute. I'm not sure why. I assume it has something to do with the scanner.

That being said I don't need to use the junction for Komga. My media folder is set as a junction for purposes related to the Sonarr/Radarr. I can make a different share outside of my media folder for Komga if that is needed. But if you are wanting to get the scanner to work with those files, I'm more than willing to keep assisting you with troubleshooting.

Thank you for all your work and this wonderful product.

**Comment by gotson** [comment]
I think i know what the problem is.

It seems you have deduplication enabled on the server hosting the files, at least that's what the reparse tag shown by `fsutil` seems to indicate. Windows adds a reparse point in the files in that case.

In Komga, the scanner checks that the files are regular files ([here](https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/BasicFileAttributes.html#isRegularFile--), [here](https://github.com/gotson/komga/blob/3db31813133aced386349e099b10f7cc4c7c5266/komga/src/main/kotlin/org/gotson/komga/domain/service/FileSystemScanner.kt#L94)), but files with a reparse point would return `false` for such check, and as such, are skipped.

What i don't understand is that in the prior version before `0.79.1`, the same check was used ([here](https://github.com/gotson/komga/blob/0216cc2cf5ec59f216bd62e3962c65b8feeb7f09/komga/src/main/kotlin/org/gotson/komga/domain/service/FileSystemScanner.kt#L81)). It's not directly the same method, but after checking in the source code of the JDK, it's using the [same](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/share/classes/java/nio/file/Files.java#L2363) `BasicFileAttributes.isRegularFile()` method.

I will change the check to exclude symlinks and directories, instead of checking for regular files, which should do the trick.

**Comment by gotson** [comment]
@paynent please give a try to `0.116.2` and let me know if that works better

**Comment by paynent** [comment]
I think it works better. If its deduplication it will likely have to led a dedup job run before I know for sure as moving the files around has removed that L attribute even when moving them back to the previous directory.  I think the file has to be 3 days old before it counts it as something that can be deduped so I will keep checking it and let you know for sure.

**Comment by gotson** [comment]
From what I read, the dedup would happen nonetheless, after 3 days maybe, so it would work only for 3 days, then files would not appear in the scan again.

**Comment by paynent** [comment]
Possible. I will keep you updated. Thanks again for looking at this.
