### ISSUE TITLE
Display thumbnails with opds

### ISSUE THREAD

**Issue by kenjidev** [gotson/komga#618]
Hello 

I use panels on ios 14 on iPad 
With ubooquty , i can see cover with opds 
It si possible to have same things with komga? it's prettier with the covers
Screenshots with komga and uboouity

![0F25019F-DA97-47FF-8695-05854C583790](https://user-images.githubusercontent.com/4105515/129457671-335785e5-f20c-4ba6-9fd2-64e1179b8541.png)

![AA80387E-2E0D-4A8B-A42B-ED7E111A9785](https://user-images.githubusercontent.com/4105515/129457674-4beb42fe-c1a5-4dd4-ad8c-0ae94b38af68.png)

Thanks

**Comment by gotson** [comment]
Thumbnails work on opds, you need to check with Panels support why it's not working.
