### ISSUE TITLE
[Feature request] When Metadata available without a title komga uses the filename

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#620]
### Is your feature request related to a problem? Please describe.
I am using `comicinfo.xml` for metadata.
Some series have a series title <series> and a number <number> but don't have a book title <title>.
series name and number are unique. A title is not needed.
At the moment komga use the filename as title.
So when you have a file named `SeriesA #001 (2004) (MyPublisher)` and in `comicinfo.xml` you also ave in series "SeriesA" and in number "1" you can see in komga:
`SeriesA` as `Seriesname` and `SeriesA #001 (2004) (MyPublisher)` as filename. this looks not good.
I understand title is a mandatory field.  

### Describe the solution you'd like
2 solutions are possible:
a) title is in the combination series name and number not a mandatory field.
b) when you read the metadata from comicinfo.xml and there is no title available but a number, it should be easy to create the title with seriesname - number.

### Describe alternatives you've considered or other apps that can do what you want
Rename all files is possible but not a good solution to solve an import problem.

### Additional context
[SeriesA #001 (2021)(MyPublisher).zip](https://github.com/gotson/komga/files/6995837/SeriesA.001.2021.MyPublisher.zip)

**Comment by gotson** [comment]
This is a personal choice, not a universal rule.

Given you are already crafting a `ComicInfo.xml` file with the `Series` name and the `Number`, why don't you build the `Title` in the way you want, ie `#Series - #Number` ?

**Comment by MKH-42** [comment]
When you use comicvine as source and fill the metadata with a tool like comictagger than you have this situation that comicvine deliver the series name but not the title.

So yes, it is personal my decision to use comicvine as source for metadata. 
On the other side it is a lot of work for all people which using comicvine as source to retag it.

So maybe it is an idea to have this feature include of komga.
