### ISSUE TITLE
[Feature Request] custom tags from filename

### ISSUE THREAD

**Issue by Suwmlee** [gotson/komga#621]
### Is your feature request related to a problem? Please describe.
we got some comics from somewhere and they don't have special xml info or intro file except filename. it would be great if Komga can extract tags from filename

### Describe the solution you'd like
simply comics  naming rules :  
Title [Author][Vol/End][Publisher][Language][C.C][other tags]  or 
[Author] Title [Vol/End][Publisher][C.C][other tags]

if komga can't extract tags by current methods. it could try extract tags from filename.
tags wrapped with symbols `[]` at the end of the filename

### Describe alternatives you've considered or other apps that can do what you want
PT uses these naming rules , sources dl from internet and another app support this [LANraragi ](https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/RegexParse.pm)

**Comment by gotson** [comment]
I don't necessarily want to add each and every possible way of importing metadata. There is not enough standardization in the file names in the comics/manga scene to enable something like this without false positives. The next thing that happens is people asking for a way to edit the naming, the destination metadata, some more transforms, etc.

Komga has a REST API that lets everyone perform whatever they want. You could easily use that to update the metadata yourself, using the logic you want.
