### ISSUE TITLE
[Feature Request] During importing a Reading List (CBL) it comes no error message when a book is listed twice and faild

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#622]
### Is your feature request related to a problem? Please describe.
When you have a book twice in your CBL and you try to import nothing happens - no error message, no hint.

Example:
```xml
<?xml version="1.0"?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>MyBook Readlist</Name>
  <Books>
    	<Book Series="MyBook" Number="1" Volume="1999"></Book>
	<Book Series="MyBook" Number="2" Volume="1999"></Book>
	<Book Series="MyBook" Number="1" Volume="1999"></Book>
 </Books>
  <Matchers />
</ReadingList>
```
Error in Logfiles:
```log
2021-08-18 14:55:37.904 ERROR 1 --- [http-nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.jooq.exception.DataAccessException: SQL [insert into READLIST_BOOK (READLIST_ID, BOOK_ID, NUMBER) values (?, ?, ?)]; [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: READLIST_BOOK.READLIST_ID, READLIST_BOOK.BOOK_ID)] with root cause

org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: READLIST_BOOK.READLIST_ID, READLIST_BOOK.BOOK_ID)
```

### Describe the solution you'd like
It would be nice to have a feedback on the UI like "Import not possible one book is listed twice"

**Comment by gotson** [comment]
Can you provide a screenshot of the import screen before importing?

**Comment by gotson** [comment]
Should the import fail, or should we ignore the second instance of the duplicate book and mark it as not imported?

I think the latter would make a better user experience.

**Comment by MKH-42** [comment]
![grafik](https://user-images.githubusercontent.com/76835223/130083331-b9bd4e38-e794-4504-a3b9-ea7120851e67.png)
Screenshot

**Comment by MKH-42** [comment]
I think also the second solution would be fantastic: to ignore the error and mark the book as already imported.
