### ISSUE TITLE
[Feature Request] User Rating

### ISSUE THREAD

**Issue by WorldEntityGravity** [gotson/komga#623]
### Is your feature request related to a problem? Please describe.
I think it would be nice to have the option for each user to add a rating for each series. This can help with libary maintenance (delete series with a low rating), keeping 'master record' for ratings when syncing with sites tracking read status or just for fun.

### Describe the solution you'd like
Adding a column to the READ_PROGRESS_SERIES table or a new table for keeping track on each users rating of a series. Also adding the UI for selecting a rating on the series screen would be needed.
I think it would be best for the rating being 0-10 in the DB and then having either 0-10 or 0-5 (with half steps) in the UI with 0 being 'no rating'. This could be expanded later to include individual books and calculating a series average rating via a libary option. 
A sort option for the user rating would also be great if implemented.

### Describe alternatives you've considered or other apps that can do what you want
Plex does this for videos, but the implementation isnt great.

**Comment by gotson** [comment]
Duplicate of #58

**Comment by ncmtl** [comment]
User rating by book would be nice too. I use Komga to manage my ebook library (1 book group = 1 series) in addition to my comic books and I'd like to remember that some books are really bad.
