### ISSUE TITLE
[Feature Request] add webdav

### ISSUE THREAD

**Issue by Kolakona** [gotson/komga#625]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I read comic on remote path like a clould drive or a nas at home.

### Describe the solution you'd like
Add choice of add path of libraries.Like webdav:   http://xxxxx:8080

### Describe alternatives you've considered or other apps that can do what you want
I have used rclone to mount webdav to my pc,but the speed of analyze is very slow.

**Comment by gotson** [comment]
There's already opds, which is suitable for that kind of content.

**Comment by gotson** [comment]
It seems you refer to the path of libraries. Can you clarify what webdav would bring exactly?

Many people use rclone with various cloud providers, and it's works very well with Komga, if you configure rclone properly.

**Comment by Kolakona** [comment]
Thanks for your reply!I don't know why the analyze speed of rclone library is much slower than the local library.

It takes may be two seconds analyzing a local comic ,but  30 seconds analyzing a remote comic.I have thousands of comics and it will take too long time to analyze.The remote comic files whitch loaded by rclone can be read fastly and smoothly with local comic softwares.

I guess directly input the library path with shared network address may be better than load it with rclone.The feature of adding shared network folder in emby may be an example?
![屏幕截图 2021-08-21 192154](https://user-images.githubusercontent.com/19240323/130320185-99b5c82c-22f1-4158-901a-1103405a7b8d.jpg)


I am not very familiar with network and coding, if i say something wrong,please forgive me!
Thank you very much!

**Comment by gotson** [comment]
> I don't know why the analyze speed of rclone library is much slower than the local library.

It depends what's behind rclone. If it's in the cloud then it will obviously be slower, as komga needs to pull the files to analyze its content. There's no way it could be as fast as local disk.

> I guess directly input the library path with shared network address may be better than load it with rclone

Rclone is a specialized software for remote access of files. It has lots of knobs and settings for various use cases, and can also do local caching.

There's no way an implementation in Komga could perform better. 

> The feature of adding shared network folder in emby may be an example?

You can already add network storage in Komga, you can use nfs or ntfs or others, mounted in your filesystem.

---

Can you share a bit more where are your files located? Which cloud provider?

You should also check https://komga.org/guides/gdrive.html

You can also come and discuss on Discord, people would be happy to help you regarding that matter.

**Comment by Kolakona** [comment]
Thanks a lot!
I have already set the rclone config like https://komga.org/guides/gdrive.html
I am in china and the cloud provider is aliyundrive.com，It has more than 1T of free space.And I use a thrid package https://github.com/zxbu/webdav-aliyundriver to get the webdav address.Than I use rclone to mount it as local disk.
I will be glad to discuss on Discord,thank you very much!

**Comment by gotson** [comment]
I will close this, I won't add webdav as explained above, and this looks more like troubleshooting or general question.
