### ISSUE TITLE
[Feature Request] gdrive api instead of rclone

### ISSUE THREAD

**Issue by edgehub-cloud** [gotson/komga#627]
### Is your feature request related to a problem? Please describe.
Rclone isn't cpu friendly at all and thou using it as a middle man seems like extra steps when all the library will exist on Cloud storage anyway and most would be and assuming uses Google drive

### Describe the solution you'd like
Direct use of api, download, caching it and analysing it. I have tested it gdrive doesn't have a download limit but a upload limit of 750gb. Authentication token can be stored along with I'd and secret and can be updated monthly. 

### Describe alternatives you've considered or other apps that can do what you want
Downloading locally first, analysing it and mounting gdrive at the same location. Which is usual the way it was given in wiki.

**Comment by gotson** [comment]
There's no way a single developer could do a better job that the rclone team. Rclone already has lots of options and settings, and is a huge project already.

You also assume that everyone uses gdrive, which is completely untrue. Many people use other cloud providers.

**Comment by edgehub-cloud** [comment]
😭
