### ISSUE TITLE
Use image file in the comic folder as series thumbnail

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#63]
Would it be possible to use an image in the folder of the series/single book as a thumbnail instead of the first image of the first comic or manga, similar to how it is often done for music folders. Sometimes the first image of a comic isn't enough to show what series it is and having the option to change the displayed thumbnail this way would help with that.

A user could simply add their preferred image to the folder and komga would just have to read it, so it doesn't have to be editable from the web interface or any clients, I think.

Although it should probably be a toggle-able option, since some users might have single image files in those folders but don't want to use them as thumbnails.

**Comment by gotson** [comment]
Someone else mentioned that already indeed.

That would be for series only since books have no folder. 

Is there a common naming scheme for those images in other tools, so we can have the same convention?

**Comment by muchtea** [comment]
Music players, calibre, plex and similar generally use some or even any of these names:
"cover", "folder", "poster" and "default" in either jpg or png format.

**Comment by 10lalib** [comment]
One temporary solution until this option is available would be to actually create a compressed file with the comic image with the naming:...... chapter (or episode) 0.zip (this is an example of what i did)

**Comment by prysme01** [comment]
it would be nice to have this fonctionnality like having a filename-cover.jpg to use instead of the first picture of the book.

**Comment by HawaiianPizza** [comment]
> 
> 
> tada This issue has been resolved in version 0.54.0 tada
> 
> The release is available on:
> 
>     * `v0.54.0`
> 
>     * [GitHub release](https://github.com/gotson/komga/releases/tag/v0.54.0)
> 
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot packagerocket

Was this feature removed? I don't see an option to change the thumbnails of my series.

**Comment by gotson** [comment]
https://komga.org/guides/local-artwork-assets.html#supported-artwork-image-formats
