### ISSUE TITLE
Unable to port forward my server

### ISSUE THREAD

**Issue by bmctigue96** [gotson/komga#630]
I have it set up port forward port 8080 with my static IP but the port is not open when running the server and i can only access it on my home network can anyone help?

**Comment by gotson** [comment]
You better ask on Discord.

**Comment by Kussie** [comment]
You will probably want to ask your ISP if they are blocking that port, or your ISP might be using CGNAT (Carrier Grade NAT), which unless they let you opt out of it, will need to setup a tunnel of some sort (Such as ngrok or via a VPS)
