### ISSUE TITLE
[Bug] Volume in title in Tachiyomi extension

### ISSUE THREAD

**Issue by maxpower47** [gotson/komga#631]
### Komga environment
- **OS**: Ubuntu server 20.04
- **Komga version**: v0.118.0-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 0.118.0
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [x] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 0.12.1
  - Tachiyomi extension version: 1.2.30

### Describe the bug
This [change](https://github.com/gotson/komga/commit/25677967db255efe39834ce31fe0f048481a3067) allowed the volume to be displayed in parenthesis after the series title if it exists.  This happens correctly in the web interface, but the Tachiyomi extension shows just the series name, rather than the series metadata title.

### Steps to reproduce
1. Add a series that includes a volume in the metadata
2. View the series list in Tachiyomi

### Expected behavior
Expect the title displayed in Tachiyomi to match what is displayed in the web interface.

### Actual behavior
The title displayed in Tachiyomi reflects only the series title, rather than the metadata title.

### Additional context
Use case is for comics that are organized as {{series}}/{{volume}}/{{issue}}.cbz.  In the web interface, these are helpfully displayed like `Batman (Volume 2016)`, but in Tachiyomi they are displayed just as `Volume 2016`.

**Comment by gotson** [comment]
Tachiyomi shows the series title, not name. 

Tachiyomi does a lot of caching, you may need to check with them on how to clear the cache or force refresh it. What probably happened is that you loaded the list in Tachiyomi before the metadata was added in Komga, and tachiyomi did cache those titles before they got updated.

**Comment by gotson** [comment]
See here: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/6a1dd5636a296c4b1a6a431496f117c14789ed4c/src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt#L238

**Comment by maxpower47** [comment]
Ah yea, looks like that was the case.  I had tried deleting the app cache previously, but that apparently wasn't enough.
