### ISSUE TITLE
[Feature Request] Filter by Characters and Teams

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [gotson/komga#636]
### Is your feature request related to a problem? Please describe.
No problem.

### Describe the solution you'd like
As of today, we are able to filter by many properties, EXCEPT two of the most useful properties, which are **Characters** and **Teams**... I believe, since everything for filtering is already in place and we can already filter by many properties of the Comicinfo.xml file, allowing to filter by character and teams should be very easily implemented, right?

### Describe alternatives you've considered or other apps that can do what you want
No alternative.

### Additional context
N/A

**Comment by gotson** [comment]
I don't have any plans to add new metadata fields for teams and characters.

There is however the tags that could be used for that purpose. We could imagine importing such data from comicinfo.xml into 2 tags, like `team:x-men` and `character:cyclops`.

Not sure how that would render in search and filters though.
