### ISSUE TITLE
[Feature Request] Sort read list (not manually)

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [gotson/komga#637]
### Is your feature request related to a problem? Please describe.
No Problem

### Describe the solution you'd like
It would be nice to be able to sort a read list by publication date of the books.

### Describe alternatives you've considered or other apps that can do what you want
Didn't find any alternatives except sorting it manually

### Additional context
N/A

**Comment by diax78** [comment]
That sounds like a good idea! Sorting for 'Read List' (or even series) could be part of user settings to make it the permanent and default value. In 'Read List', especially when they are a mix of books from different series i.e. crossovers, the date of issue is the best method to sort issues so it could be read in correct order.

**Comment by Bazzu85** [comment]
Hi, can we get an update on this feature?
ty

**Comment by XenorPLxx** [comment]
Yea, that sounds like a nice idea!
