### ISSUE TITLE
[Feature Request] Metadata Field "Artist", "Character Design"

### ISSUE THREAD

**Issue by arihid** [gotson/komga#639]
### Is your feature request related to a problem? Please describe.
The now available metadata field is quite many. But many mangas often credit this three: Author (原作), Artist (漫画), and Character Design (キャラクター原案), and it is lacking the later two elements.

### Describe the solution you'd like
Author field are easily reached. As the other two, I don't think using any of current field as a replacement will appropriate. I suggest to add those two additional metadata field to editor.

**Comment by gotson** [comment]
Artist = penciller
