### ISSUE TITLE
[Bug] Web reader jumps when moving between pages

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#640]
### Komga environment
- **OS**: 
- **Komga version**: 
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: 
- [X] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Moving between pages jumps abrubtly.

### Steps to reproduce
1. Open a right to left comic, double pages, scale screen, gestures, disable animate transitions.
2. Move pages
3. A scrollbar briefly shows then disappears making the pages shift 10px or so to the left, giving a janky transition.

### Expected behavior
No animations & no jumping.

### Actual behavior
Jumpy-ness when moving pages

### Additional context
none

### Screenshots
![image](https://user-images.githubusercontent.com/32607317/131263163-033c809f-ec02-4300-9a6a-9e6d81b1f235.png)
I'll send you a gif of it, but it's over 10MB limit.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

**Comment by kanjieater** [comment]
Here's a link to the gif. It is pretty distracting to reading on single page flips.
https://imgur.com/a/7jjHUuE

**Comment by gotson** [comment]
Please provide browser version and os version. Can you try on other browsers too? Update the issue title also.

**Comment by kanjieater** [comment]
Sure, sorry about that. I'm on Chrome Version 92 (latest). I tried on Edge, where I have no extensions or anything additional, and the problem existed there too (also latest version 92).

**Comment by gotson** [comment]
What's your os? How about Firefox?

**Comment by gotson** [comment]
Can you try other reader settings to narrow down the problem? Try in single page, right to left, with transition, and other combinations.

**Comment by kanjieater** [comment]
> Can you try other reader settings to narrow down the problem? Try in single page, right to left, with transition, and other combinations.

I'm on windows 10. It happens in all browsers. Its quite easy to reproduce if you just turn the animation off. All other setting combinations seem to have the scroll bar jump in temporarily.

**Comment by kanjieater** [comment]
This shows what I'm describing with the image and too jumping: https://imgur.com/WH7uZkg

**Comment by kanjieater** [comment]
I just confirmed I could _not_ reproduce it on Chrome on Android on two devices. It seems that at least on desktop browsers more than one page set can appear at a time, but it's very brief.

**Comment by gotson** [comment]
Are you connecting to a local or remote server?

**Comment by kanjieater** [comment]
Local server

**Comment by kanjieater** [comment]
I'm going back and forth between two images and the display:none is set just a second too late, leaving both pages on the same page for an instant 
![image](https://user-images.githubusercontent.com/32607317/131346058-72b95ded-9aaf-4a9b-a5f9-cade705ae1ab.png)

**Comment by kanjieater** [comment]
If you use chrome CPU throttling you should be able to see it a little bit easier too: 
![image](https://user-images.githubusercontent.com/32607317/131347432-a895703f-e7a2-4797-a5ba-3f05dca9f28c.png)

**Comment by gotson** [comment]
> If you use chrome CPU throttling you should be able to see it a little bit easier too:
> ![image](https://user-images.githubusercontent.com/32607317/131347432-a895703f-e7a2-4797-a5ba-3f05dca9f28c.png)

What's your hardware on the client and server?

**Comment by kanjieater** [comment]
Client and server are the same, my gaming pc. 4.1GHz i7-4770k CPU, 32GB RAM, 770GTX GPU w/ latest drivers.

**Comment by kanjieater** [comment]
I made a hacky workaround by adding this:

```
.v-window-item.full-height[style=""] + .v-window-item.full-height[style=""] {
display:none;
}
```

This selector grabs the images that are adjacent that don't have style properties and hides them. All the other images have `style="display:none;"` so they won't be matched, and this only works if there are two containers image on the screen at the same time.

And just to be clear, when I'm talking about an image, i'm talking about single or double page working with this too. Two sets of pages being displayed at once is what this selector fixes.

**Comment by kanjieater** [comment]
Not sure if this is also something that logging could help with? It's still a very noticeable issue that I'm using the above hack to work around.

**Comment by kanjieater** [comment]
Unfortunately the fix did not change the behavior, as the scrollbar still jumps in when the next set of images are on the page without animation.

**Comment by gotson** [comment]
> Unfortunately the fix did not change the behavior, as the scrollbar still jumps in when the next set of images are on the page without animation. Can we reopen this?

There's a new `html-reader` css class added dynamically to the `<html>` element when you open the webreader, this class hides the scrollbars entirely, which works on webkit and Firefox. I tested on both browsers, with my Mac setup to always show scrollbars all the time (like on windows by default I think), and it doesn't show.

**Comment by kanjieater** [comment]
It must not be catching the element that has the scrollbars then because the original behavior can still be reproduced like the gif linked above originally.

**Comment by gotson** [comment]
> It must not be catching the element that has the scrollbars then because the original behavior can still be reproduced like the gif linked above originally.

can you find out which element generates scrollbars ? I can't reproduce it after that fix, so i can't help much more without more details.

Can you try to modify the DOM and remove the `display:none` of the previous or next slide, so it shows 2 at the same time ? That should make the container show a scrollbar. That's how i did the troubleshooting, and the scrollbar was coming from `<html>`.

**Comment by kanjieater** [comment]
Ok, did a little digging. So the actual scroll bar is gone - you were right, but the core issue is still present.

Try these settings:
No animation. 
Double Pages.
Scale Type: Original <- this is important, as the issue seems to be fixed on other views.

The next image appears at the bottom until the old one disappears. You can 100% manually recreate this if you remove the display:none as you suggested. It shows two images on the page, causing a flash. This is better imo than content shifting due to the scrollbar, but this is still the core issue: two images can appear at the same time when animations are disabled.

**Comment by gotson** [comment]
> Ok, did a little digging. So the actual scroll bar is gone - you were right, but the core issue is still present.
> 
> Try these settings:
> No animation.
> Double Pages.
> Scale Type: Original <- this is important, as the issue seems to be fixed on other views.
> 
> The next image appears at the bottom until the old one disappears. This makes sense when animations exist, because you have to show both images transitioning. It doesn't make sense / work well if animations are disabled though.
> 
> If you still can't get that, then you can 100% manually recreate this if you remove the display:none as you suggested.
> 
> It shows two images on the page, causing a flash. This is better imo than content shifting due to the scrollbar, but this is still the core issue: two images can appear at the same time when animations are disabled.

But this is not the issue you described above and it does not make scrollbar appears.

**Comment by kanjieater** [comment]
> > Ok, did a little digging. So the actual scroll bar is gone - you were right, but the core issue is still present.
> > Try these settings:
> > No animation.
> > Double Pages.
> > Scale Type: Original <- this is important, as the issue seems to be fixed on other views.
> > The next image appears at the bottom until the old one disappears. This makes sense when animations exist, because you have to show both images transitioning. It doesn't make sense / work well if animations are disabled though.
> > If you still can't get that, then you can 100% manually recreate this if you remove the display:none as you suggested.
> > It shows two images on the page, causing a flash. This is better imo than content shifting due to the scrollbar, but this is still the core issue: two images can appear at the same time when animations are disabled.
> 
> But this is not the issue you described above and it does not make scrollbar appears.

But it is.

1. Open a right to left comic, double pages, scale screen, gestures, disable animate transitions.
2. Move pages
3. A scrollbar briefly shows then disappears making the pages shift 10px or so to the left, giving a janky transition.

The scrollbar in 3 is gone, but the janky transition still exists, because the other image flashes on the screen. If you want me to open a new issue ticket that's fine, but this is the same root problem that your solution of hiding the scrollbar was fixing: two images can appear on the screen at the same time causing a "jump when moving between pages". The issue isn't that there's a scrollbar exclusively (but that did make the problem worse), it's that the transition flashes/jumps.

**Comment by gotson** [comment]
Please post a new video showing how it can be worse, thanks.

If there's jo scrollbar, there's no more shift of the scrollbar width for a brief moment.

Yes the 2 images will still appear at the same time, but you would only see it :
- with animations disabled
- wirh original scale 
- on a screen size or zoomed out so that you can see the whole image completely

With other scale types, given it fits the screen for one of the image, you wouldn't see the other.

**Comment by kanjieater** [comment]
I didn't say it was worse. I'm just pointing out that the root problem was not fixed and may cause unexpected behaviors. You could enable a CSS fix like I mentioned above when animations are disabled to fix this:
```
.v-window-item.full-height[style=""] + .v-window-item.full-height[style=""] {
display:none;
}
```
There's probably something cleaner though that you could do inside javascript though, as this is pretty hacky. My point isn't that you need to use this code, it's that the root issue is showing two images at once.

Make sure the play bar isn't showing so you can see the full effect of images popping in:
https://imgur.com/Xo5gAKk

**Comment by gotson** [comment]
it's a problem we need to raise at Vuetify, their component doesn't behave as expected. We would need to build a minimal reproducible sample for them to have a look at.

Yes, the root cause is still there, but the most visible symptom is gone, so i'll keep this as closed.
