### ISSUE TITLE
[Feature Request] Authentication Activity Table enhancements

### ISSUE THREAD

**Issue by Kussie** [gotson/komga#641]
### Is your feature request related to a problem? Please describe.
The authentication table can fill up pretty quickly.  My log is currently sitting at 202033 entries.

### Describe the solution you'd like
It would be nice if there was a button or ability to empty the table from within the UI.  Or alternatively apply some grouping to the table (Could be based on user agent + ip + email + date or such) so it only shows unique entries. 

In addition the table headers also show some additional text called "group" for some reason.

![Screenshot 2021-08-30 11 11 26](https://user-images.githubusercontent.com/4960791/131272367-b00617fb-01a2-48aa-a6d8-a454d1a194f9.png)

And yes all the blacked out email in the above are the same email address.

**Comment by gotson** [comment]
There's automatic cleanup everyday of entries older than 1 month.

The group button is used to perform grouping at ui level. You can first sort by criteria then group, and it will show you what you want.

**Comment by gotson** [comment]
I think the script you built to synchronize your own progress is generating all those sessions. Whenever you authenticate by setting the basic auth, it will create a new session.

What you could do to reduce the number of sessions is properly store the JSESSIONID cookie and pass it back to subsequent calls, or you can use the interceptor pattern, and only provide the basic auth credentials when you receive a 401.
