### ISSUE TITLE
[Feature Request] Display Writers etc. filters with checkboxes

### ISSUE THREAD

**Issue by shrublet** [gotson/komga#642]
### Is your feature request related to a problem? Please describe.
I don't think this is a duplicate, but apologies if it is (just started using Komga). Somewhat annoying that the only way to filter these categories is with searching unlike any of the categories above writer that use checkboxes and creates a list from all of the possible options.

### Describe the solution you'd like
Display all writers etc. with individual checkboxes like other filter options.

### Describe alternatives you've considered or other apps that can do what you want
The only good way to sort by writer etc. right now is by either searching names directly or by first going to a series and then clicking a name. This would streamline that process immensely.

**Comment by gotson** [comment]
It was the case before, but we changed it because some people have 20k authors in their library, so checkboxes don't scale.
