### ISSUE TITLE
[Bug] Demo application displays logged IPs and User Agents

### ISSUE THREAD

**Issue by TOFUFreak** [gotson/komga#643]
### Komga environment
Demo application  (demo.komga.org)

### Describe the bug
The 'Authentication Activity' section in the demo application's account settings openly lists the IPs along with the User Agents of all connected clients from the last 30 days.

### Steps to reproduce
1. Log into the demo application
2. Open the 'Account Settings' page

### Expected behavior
The 'Authentication Activity' section does not contain information about other sessions (either by filling the table with dummy info or by just leaving the current session in there).

### Actual behavior
Actual (non-dummy) Information about past connections (of other people trying the demo) is displayed, as stated in the bug description.

### Screenshots
![image](https://user-images.githubusercontent.com/16881592/131332347-e214fd91-e3ed-436d-a42b-d65c4fa84156.png)

**Comment by gotson** [comment]
What's the problem about it?

**Comment by JunkMeal** [comment]
Maybe i dont want my ip leaked when i try the demo

**Comment by gotson** [comment]
Maybe don't use the demo 😂
