### ISSUE TITLE
Scan doesn't work

### ISSUE THREAD

**Issue by CubeComming** [gotson/komga#644]
### Komga environment
- **OS**: Linux
- **Komga version**: 0.119.2
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Describe the bug
Since update to 0.119.2 Scanning for new items doesn’t work. I click the Icon and i get a long list of books and then:

[SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)

### Steps to reproduce
1. Go to your Library
2. Press 3 dots
2. Click on Scan Library

### Expected behavior
It should scan for new Items and add them

### Actual behavior
Like described above

### Additional context
After downgrading to 0.119.1 it works.

**Comment by gotson** [comment]
Please provide complete log files.

**Comment by CubeComming** [comment]
Thank you for your fast answer.
Logs:
[Logs.txt](https://github.com/gotson/komga/files/7076647/Logs.txt)
