### ISSUE TITLE
[Bug] Nothing to Show showing temporarily when there is something to show

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#648]
### Komga environment
- **OS**: 
- **Komga version**: 
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [X] **I am running Komga from the `jar`**
  - Java version: 
- [X] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When moving between pages or on initial load of the homepage you can get a "Nothing to show" shown, then content may or may not show if there actually was something to show.

### Steps to reproduce
1. Open Komga in the browser, it may flash for an instance
2. Click on one of your large libraries from the side bar. It may show then.

### Expected behavior
A loading icon or not showing anything. It would be good to distinguish between "loading" and "no results".

### Actual behavior
The app said Nothing to show temporarily when there was something to show. It made me think there was an issue for a brief second, then the content loaded.

### Screenshots
![image](https://user-images.githubusercontent.com/32607317/131543675-72d1ca0a-e8e0-4332-ae97-855d87261240.png)

**Comment by kanjieater** [comment]
The Nothing to Show is gone from most views. I still found it here though:

After I click a Keep Reading from Home, then click the back button:
![chrome_UDmPUZ7qOG](https://user-images.githubusercontent.com/32607317/132397319-7777cd9b-7806-478e-97cb-f60bde5c729d.png)


My actual home screen:
![image](https://user-images.githubusercontent.com/32607317/132397263-d2856fc7-2916-4fef-8b38-f0fd36a2844e.png)

**Comment by gotson** [comment]
> After I click a Keep Reading from Home

What does that mean?

**Comment by kanjieater** [comment]
After i click a book in the Keep Reading recommendation section, from the
Home page in the Komga app

**Comment by kanjieater** [comment]
After i click a book in the Keep Reading recommendation section, from the Home page in the Komga app

**Comment by gotson** [comment]
> After i click a book in the Keep Reading recommendation section, from the Home page in the Komga app

Fixed
