### ISSUE TITLE
Webreader conditional webp support

### ISSUE THREAD

**Issue by gotson** [gotson/komga#65]
Check for the browser capability to enable webp or not in the webreader.

**Comment by gotson** [comment]
@whalehub I found a way to enable `webp` if it's supported

**Comment by whalehub** [comment]
@gotson Thank you!

**Comment by whalehub** [comment]
@gotson I don't know why, but .webp pages now load instantly with Komga v0.12.0 rather than taking a split second like they did in v0.10.1 (the last version before support was initially removed). Thanks again!

**Comment by gotson** [comment]
I completely changed the underlying carousel that's displaying the images and providing the sliding mechanism. The previous one had a different way of lazy loading the next images. Also the new one is lazy loading 2 images n advance instead of just one (to cope with double pages), so maybe that's why you don't see a thing!
