### ISSUE TITLE
[Bug] Komga does not redirect to login page when accessed via reverse proxy

### ISSUE THREAD

**Issue by Magma2222** [gotson/komga#652]
### Komga environment
- **OS**: Unraid 6.9.2
- **Komga version**: v0.120.3-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: No tag. I assume latest is the default
- [ ] **I am running Komga from the `jar`**
  - Java version:
- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome 92.0.4515.159 but have tried many other browsers
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
Komga is currently setup and working behind a reverse proxy using nginx. It is accessible at https://domain.com/komga

When I navigate to the URL it redirects to https://domain.com/komga/startup?redirect=%2Fdashboard and hangs. All I see is the logo. This does not happen when accessing on my local network. I can navigate manually to https://domain.com/komga/login and login from there and from there everything works as intended.

### Steps to reproduce
1. Navigate to domian.com/komga when not authenticated.

### Expected behavior
Redirects to login page.

### Actual behavior
Hangs at https://domain.com/komga/startup?redirect=%2Fdashboard

**Comment by gotson** [comment]
Please input a description, and provide all the config of Komga and nginx.

**Comment by Magma2222** [comment]
Komga is set to use base url /komga and is accessed on port 8888.

Here is the Komga log: https://pastebin.com/Jdb3Jw1R
Here is the nginx entry for /komga: https://pastebin.com/m3sKg83D
Here is the nginx proxy.conf: https://pastebin.com/KgbEj1Gi

**Comment by gotson** [comment]
Why do you need rules for /opds or /api?

**Comment by Magma2222** [comment]
At this stage it's unnecessary. I was playing around with organizr handling authentication but it was interfering with opds authentication.

**Comment by MagikarpLaCarpe** [comment]
On your config you should add line 4 login at the end of `proxy_pass http://192.168.2.28:8888/komga/`
(proxy_pass http://192.168.2.28:8888/komga/login;)

To be sure thing work, and pass, you may need to pass request Header with the use of "proxy_set_header"

Komga may also not work if the host is different from its own sadly i cannot test so it's on your own but what's sure is you may need to setup header correctly.

also try to setup host and x-forwarded-for if komga refuse to authenticate user if the source IP is not the same as you use http level reverse proxy.

proxy_set_header    Host $host;
proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by Magma2222** [comment]
> On your config you should add line 4 login at the end of `proxy_pass http://192.168.2.28:8888/komga/`
> (proxy_pass http://192.168.2.28:8888/komga/login;)
> 
> To be sure thing work, and pass, you may need to pass request Header with the use of "proxy_set_header"
> 
> Komga may also not work if the host is different from its own sadly i cannot test so it's on your own but what's sure is you may need to setup header correctly.
> 
> also try to setup host and x-forwarded-for if komga refuse to authenticate user if the source IP is not the same as you use http level reverse proxy.
> 
> proxy_set_header Host $host;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

If I change that line and add /login it will always send me to the login page instead of redirecting me. Additionally all traffic to /komga would be processed through /komga/login ie: domain.com/komga/request would end up being processed at 192.168.2.28:8888/komga/login/request

proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
are both setup in proxy.conf specfically line 41 and 43.

**Comment by MagikarpLaCarpe** [comment]
In that case i have no other solution :/ Maybe setting up Transparent reverse proxy could help but i do not know :/
