### ISSUE TITLE
[Bug] Extremely high CPU and RAM usage

### ISSUE THREAD

**Issue by 123321mario** [gotson/komga#653]
### Komga environment
- **OS**: Windows 7 SP1
- **Komga version**: 0.120.3

- [x] **I am running Komga from the `jar`**
  - Java version: 8 build 1.8.0_301-b09

### Describe the bug
Komga uses all of my CPU and RAM as soon I launch the jar, if I wait some time the CPU usage drops a bit but as soon as I click on something it restarts to throttle.
I'm running it on my old server, CPU is a Core Duo 6300 @ 1.86 GHz and has 4GB of RAM, that might not be enough to run it.
Those high usages make the app crash or even make the server Blue Screen
I managed to lower the RAM usage by adding `-Xmx1g` to the command line but now the terminal display some out of memory errors...
But when it doesnt show errors the thing works mostly fine.

### Steps to reproduce
Run the jar or do anything on the web interface

### Expected behavior
![image](https://user-images.githubusercontent.com/33780173/131867282-843fca79-913a-496e-aefd-58a4b7d2718a.png)
(for comparison is my server running ubooquity, a similar program to komga, also in java)

### Actual behavior
![image](https://user-images.githubusercontent.com/33780173/131866669-2c8748a7-3868-4441-9258-f71597b40aed.png)

### Log file
where can I find them ? 
I don't see anything in the jar directory

**Comment by gotson** [comment]
Logs are in your user directory, in a folder `.komga`

**Comment by gotson** [comment]
Cpu usage is most likely related to the analysis of your library. You can hover over the moving bar under the top left logo to see whether there is server activity.

**Comment by 123321mario** [comment]
Sorry for the late reply, I checked the logs, on most crashes the last lines are basically just this 
![image](https://user-images.githubusercontent.com/33780173/133046447-623cd6d3-91eb-4b9f-b047-797ad2a7c774.png)

but in the whole logs files there's a ton of errors, all starting with one of these :
-``javax.jms.JMSException: ActiveMQConnectionTimedOutException[errorType=CONNECTION_TIMEDOUT message=AMQ219014: Timed out after waiting 30,000 ms for response when sending packet 49]``
-````javax.jms.JMSException: AMQ219016: Connection failure detected. Unblocking a blocking call that will never get a response````
-``javax.jms.IllegalStateException: AMQ219017: Consumer is closed``
-``javax.jms.IllegalStateException: Session is closed``
-``java.lang.OutOfMemoryError: GC overhead limit exceeded``
-``java.lang.OutOfMemoryError: Java heap space``

here is the full most recent log file: 
https://pastebin.com/raw/0QzdeFAx
and some from other days:
[komga_logs.zip](https://github.com/gotson/komga/files/7152778/komga_logs.zip)

also what top left logo are you talking about?
i thought it was this one but nothing happens if I hover on it
![image](https://user-images.githubusercontent.com/33780173/133052158-483d8f6b-8ff3-40e6-95d5-0a9862069796.png)

**Comment by gotson** [comment]
GC / Heap errors mean you don't have enough RAM. You could try https://komga.org/installation/jar.html#increase-memory-limit

For the activity, see https://komga.org/faq/#komga-seems-slow-how-can-i-check-what-s-going-on

**Comment by 123321mario** [comment]
okay so I tried to launch it on my main PC who has 32GB RAM with 16GB allocated to Java and komga actually uses 2.5GB 
is there any way to make it use less ram? I think it's a lot for a reader... for example my Emby server (with 8tb of video in it) barely uses 150mb of ram when streaming

also nothing happens in the server in backgroud (the loading animation stops really quick after booting the server, i just saw AnalyzeBook and Refresh something before it disappeared)

**Comment by gotson** [comment]
I already replied about the ram usage. If you have heap / GC errors, you don't have enough ram allocated to Komga, you need to increase it.

**Comment by 123321mario** [comment]
well if i increase over 1.5gb my server crashes so for now i'll close the issue since it's a problem with my old hardware and not the program itself
actually the CPU usage dropped a bit with the new updates
I might get a better server soon so that would be fixed
thank you for your help !

**Comment by gotson** [comment]
> well if i increase over 1.5gb my server crashes

How much ram total does your server has? 

> my Emby server (with 8tb of video in it) barely uses 150mb of ram when streaming

It's not the same programming language at all, we can't really compare apples to apples

**Comment by 123321mario** [comment]
the server has 4GB of RAM

i don't know much in code sorry if that was a dumb comparison ._.

**Comment by gotson** [comment]
> the server has 4GB of RAM
> 
> i don't know much in code sorry if that was a dumb comparison ._.

No problem. 4gb is a bit light, especially if you run many other services. Some people manage to run Komga on some old raspberry pi with 2gb of ram, but usually there's only this running.

**Comment by jpmenil** [comment]
Tbh, since at least a month. i can't start komga anymore without 7gb, wich is way too much, especially since java do not release memory.
