### ISSUE TITLE
[Bug] SQLite native library crash during batch insert

### ISSUE THREAD

**Issue by MagikarpLaCarpe** [gotson/komga#654]
### Komga environment
- **OS**: Raspberry PI OS
- **Komga version**: 0.120.3
- [x] **I am running Komga from the `jar`**
  - Java version: OpenJDK  (8.0_212-b01) (build 1.8.0_212-8u212-b01-1+rpi1-b01)

### Describe the bug
The server start, load, then crash. No error in komga it always crash before 10 min after the server started.

### Additional context
In 0.119.1 everything work fine, i have updated to 0.120.3 and now its crash everytime. A friend tried on his rpi the fatal error still remain.

### LOG
hs_err provided but komga has absoluty no error in the log so it's useless to attach it 
[hs_err_pid32073.log](https://github.com/gotson/komga/files/7102783/hs_err_pid32073.log)

**Comment by gotson** [comment]
Can you try to setup a new komga instance from scratch and see if it crashes during user claim, before you add a library?

**Comment by MagikarpLaCarpe** [comment]
On a complete clean installation, it's seem there is no crash. I have added a library and the scan is still running. I will post if it's crash after the scan is finished

**Comment by MagikarpLaCarpe** [comment]
after setting up a little library i do not see any other crashes

**Comment by MagikarpLaCarpe** [comment]
It also seem that putting back my db does not crash the instance anymore. My friend did not test on his raspberry pi but on my own rpi it does not crash it's weird :/

**Comment by MagikarpLaCarpe** [comment]
So its jut crash again !

**Comment by gotson** [comment]
Can you provide the log file of Komga and the crash log file?

**Comment by gotson** [comment]
Are you also able to provide the core file:
> Core dump written. Default location: /home/pi/core or core.28606

**Comment by MagikarpLaCarpe** [comment]
Alright, core dump sended !

**Comment by MagikarpLaCarpe** [comment]
All 0.120.x was crashing all the time. BUT 0.123 does not crash, i do not understand why this happen but i can confirm that the latest version does not have the fatal crash that occur in 0.120.x

**Comment by MagikarpLaCarpe** [comment]
0.120-->0.123 still crashing
