### ISSUE TITLE
[Feature Request] Support for adding covers to collections

### ISSUE THREAD

**Issue by shrublet** [gotson/komga#655]
### Is your feature request related to a problem? Please describe.
Site didn't list this as a supported feature, so I assume it's not implemented. Would be nice if collections could have covers too considering Series/Books can have their own unique covers.

### Describe the solution you'd like
The option to change cover for a collection and Komga could either cache the image or use a direct file path to find an image.

### Describe alternatives you've considered or other apps that can do what you want
N/A

### Additional context
Just would be a nice feature. I use collections to sort by magazine releases and, as stands, there's no real ways to customize a collection to the same depth as a Series. Would be nice if I could at least add the magazine covers if not further in-depth metadata customization like description, etc. but I don't know if that's within the scope of Komga or something you had planned/wanted to do. :)

**Comment by gotson** [comment]
Duplicate of #473

**Comment by shrublet** [comment]
Sorry! The keywords I used didn't come up with that 😭

**Comment by gotson** [comment]
> Sorry! The keywords I used didn't come up with that 😭

I mostly tag them so I know where to look for information. Don't worry about it, especially since the other one has been closed stale already.
