### ISSUE TITLE
[Question] Is there anyway to reset the list of pending tasks in KOMGA?

### ISSUE THREAD

**Issue by moisesbelda** [gotson/komga#658]
By my own mistake, there are more than 15.000 tasks pending in my KOMGA docker instance working.

I tried to restart and reset the docker image , but the tasks are still there, and they are being processed very slowly. Is there anyway to clean the list of pending taks? Is it stored in the sqlite database and I can remove some records?

Thanks

**Comment by gotson** [comment]
You can stop Komga, and delete the `artemis` folder which is next to the logs and the db.

**Comment by gotson** [comment]
I should probably add something in the server settings to clear pending tasks.
