### ISSUE TITLE
Remember last option settings used in the web reader

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#66]
I just read a bunch of manga chapters with the web reader and used the "Fit To Width" option for each. That worked very well, but I had to select the view setting for each chapter again since the default is "Fit To Height".

I would prefer if my last used reader settings could be saved and used automatically for whatever book I'm reading next, until I change the settings manually again.

**Comment by gotson** [comment]
I guess we could store it in cookies, so it will be device specific. I need to find a way to do that with the framework I use.

**Comment by muchtea** [comment]
Maybe it could be stored in the database and on user login the settings could be read from the db and a session cookie with the setting could be created. Depending on the browser settings or extensions, these cookies might need to be created every time Komga is opened, since they might get deleted in between.

Alternatively they could just be sent and loaded every time a book is opened as json, since so far there aren't many settings, although I don't know if that works with the way the books are currently loaded for the web reader.

**Comment by gotson** [comment]
I don't want to store them in database for the user, as the setting is related to a device, not a user. I don't have the capacity yet to distinguish and remember devices, so at the moment the best way would be a cookie. It doesn't need to be a session cookie, so it can remain there forever (= a very long time).
