### ISSUE TITLE
[Consider] feedbacks from an user

### ISSUE THREAD

**Issue by LelieL91** [gotson/komga#662]
Hi,
I want first say thanks for this awesome reader. I discovered it recently and I started testing it on my Raspberry Pi 3.
I have some thought I want share with you:
1) at the login page, after you enter the credentials, if you press "enter" keyboard button, would be nice if it will execute the login instead pressing on the login button
2) have you ever considered to make a pubblic access mode, maybe restricted to some books, without sign up?
3) I'm currently using this directory format: "Main folder (screen 1) > all volumes folders (screen 2) > inside each folder there are chapters (.cbz)"
When I click on the name library, I can use "Browse" to see the current 3 volumes that I loaded (screen 3) and that's fine, but if I click on "Libraries" I currently see the 3 volumes of the same manga instead of the main manga folder that includes those 3 volumes (screen 4)
![immagine](https://user-images.githubusercontent.com/48968075/132220242-54c3187d-4916-4ca6-a048-460451efdb83.png)
![immagine](https://user-images.githubusercontent.com/48968075/132219971-06119e19-5850-4211-ad83-9b61ecf9f03e.png)
![immagine](https://user-images.githubusercontent.com/48968075/132220629-cf89277d-6794-4ad5-963e-02ea55929c5b.png)
![immagine](https://user-images.githubusercontent.com/48968075/132220948-5b26bf3e-048b-430f-8701-82bb31c3dde1.png)

Sorry for my english, I hope you will understand what I wrote especially the 3rd point.
Thanks for your time

**Comment by gotson** [comment]
Regarding your point 3: in Komga 1 folder = 1 series. There is no folder browsing. You may need to change your folder organization to make it work with Komga. If you have many Manga in volumes and chapters, you could consider using Kavita instead, which is geared more towards Manga.

For point 2, this is not what Komga aims to be. One of the core feature is to provide read progress for each user, which is not possible in anonymous mode. Duplicate of #306

**Comment by LelieL91** [comment]
> 
> 
> Regarding your point 3: in Komga 1 folder = 1 series. There is no folder browsing. You may need to change your folder organization to make it work with Komga. If you have many Manga in volumes and chapters, you could consider using Kavita instead, which is geared more towards Manga.
> 
> For point 2, this is not what Komga aims to be. One of the core feature is to provide read progress for each user, which is not possible in anonymous mode. Duplicate of #306

Alright, got it. Thank you for you reply and support.
