### ISSUE TITLE
[Feature Request] Bulk Edit Authors

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#666]
### Is your feature request related to a problem? Please describe.
Currently you cannot set the author at the series level.

### Describe the solution you'd like
If you want to set a series to an author, you should be able to set it at the series level, any edit menu of the series should contain authors (writers, inkers, etc.). 

### Describe alternatives you've considered or other apps that can do what you want
Other media data providers provide authors at the series level (anilist)

### Additional context
Ideally you could edit authors here: 
![image](https://user-images.githubusercontent.com/32607317/132590514-1bb486b2-b71f-437b-8fbd-fb1650f7f2a0.png)
 Also in the bulk edit: 
 
![image](https://user-images.githubusercontent.com/32607317/132590573-19499cdd-083e-413f-a74b-8d34f03c118c.png)

**Comment by gotson** [comment]
Just set the author of any book in tbe series, it will then be aggregated at series level and displayed.

**Comment by gotson** [comment]
To give you some context, authors are not per series. You may have a simplistic view about Manga, but some comic series have dozens or more authors, even more for roles like colorist or cover artist.

If you want to edit _the same authors_ on multiple books, you can already do this from the normal book edit dialog (not bulk).

**Comment by kanjieater** [comment]
Yup well aware that multiple authors could be involved for individual books. Ah, yeah you are correct, you can just do what I was looking for via the edit. It is a little unintuitive that it's not on the bulk  edit metadata, though I can see it would be a lot of fields to display there. Any reason you shouldn't be able to edit the book level metadata there?

**Comment by gotson** [comment]
> Any reason you shouldn't be able to edit the book level metadata there?

What metadata, and where?

**Comment by kanjieater** [comment]
> > Any reason you shouldn't be able to edit the book level metadata there?
> 
> What metadata, and where?

In the bulk edit books dialog and the series level dialog.

**Comment by gotson** [comment]
- In the series dialog: because those fields have nothing to do with the series
- in the book bulk edit dialog: because there's not enough space

**Comment by gotson** [comment]
I'm closing this for now, as the problem you encounter is addressed.
