### ISSUE TITLE
[Feature Request] Align Double Pages According to their Reading Direction

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#670]
### Is your feature request related to a problem? Please describe.
I read comic with double pages on two vertical monitors. 

When in double page mode, Komga centers single pages. 
![image](https://user-images.githubusercontent.com/32607317/132967989-fe8800bc-08df-4193-9750-0fb43ec17581.png)

Double pages still look fine:
![image](https://user-images.githubusercontent.com/32607317/132967996-3addc8e0-1126-4acb-b713-e95909f10d00.png)

It also doesn't put the second to last page and the last page next to each other. This part may be considered a bug.

Second to last page:
![image](https://user-images.githubusercontent.com/32607317/132967997-38dca9d3-85ea-4d15-8a30-63df902d2088.png)

Last page:
![image](https://user-images.githubusercontent.com/32607317/132967999-c8c2ca17-03a5-4998-9729-b9c22254fd4c.png)

### Describe the solution you'd like
Show right to left pages aligned to the left if it's at the beginning & left to right pages at the left if it's at the beginning.

Short right to left pages aligned to the right if it's at the end, and show left to right pages the right if it's at the end. 

This should fix the natural flow of the pages.

### Describe alternatives you've considered or other apps that can do what you want
Cover does exactly this:
Right to left, first page, left aligned
![image](https://user-images.githubusercontent.com/32607317/132968013-fd55eff4-0441-4162-8bea-581ff4bfd731.png)
Last two pages:
![image](https://user-images.githubusercontent.com/32607317/132968016-eceedfc3-6c72-450e-863a-e51166025057.png)

### Additional context
This is a comic that is available freely online that you can try it out with to reproduce: https://www.dropbox.com/s/9t0khm18ivwnr09/%E9%AD%94%E5%A5%B3%E3%81%A8%E9%A8%8E%E5%A3%AB%E3%81%AF%E7%94%9F%E3%81%8D%E3%81%AE%E3%81%93%E3%82%8B%20-%20%E7%AC%AC01%E5%B7%BB.cbz?dl=0

**Comment by kanjieater** [comment]
still interested

**Comment by gotson** [comment]
For this to work, pages must have been analyzed for dimensions. If it's not the case, an arbitrary aspect ratio is used instead, which should work fine for most images.
