### ISSUE TITLE
[Feature Request] Restore/retain scroll state when navigating back to a library view

### ISSUE THREAD

**Issue by jonaballen** [gotson/komga#674]
### Is your feature request related to a problem? Please describe.

1. Navigate to the top level page of a library, say the "browse" view
2. scroll down on page
3. open a Series page 
4. Navigate back with webbrowser back button, to the "browse" view
5. Observe scroll position

Current:
The scroll position is reset and at the top of page.

Expected/Requested:
The scroll position should be restored/retained. The page should not reload/refresh. So I can keep looking for something to read without having to scroll back down every time.

Comment why I want this:
I have a few very large libraries and the above becomes a problem when I am in the "Hmm, what should I read today..." scenario and am about to look/browse for something new.
I either use the letters to filter and/or scroll to find series or issues a bit further down on the webpage. But the scroll and [#ABC ...Z] letter filter or side-scroll positions are always reset when navigating back. 

### Describe the solution you'd like
Vertical Scroll position, side scroll (in recommended view) and [#ABC ...Z] filter states should not be reset, but restored when navigating between pages

### Additional context
If you compare to the same scenario in Plex, both app and webapp restores/retains scroll state/position

**Comment by gotson** [comment]
please update the description

**Comment by jonaballen** [comment]
I updated the description, hope its clearer.

**Comment by gotson** [comment]
This feature existed long time ago, using some skeleton loaders to occupy the space before the loading of the actual elements took place. This was useful because at the time komga was using an infinite scroll.

Given we now use pagination for navigation, there is little interest for this.

**Comment by jonaballen** [comment]
Well, I can only speak for myself, but I find pagination being a chore.  I find scrolling to be much more fast and easy way of looking for something, so I always tend to maximise the number of items per page (so its 500 for me ;)), which means scrolling.

Users having large libraries I would guess is more common than uncommon.
I myself have +10k comics and over 3 500 series which makes it a pain to use 20 or 50 items per paginated page. Currently I have 187 pages if each page holds 20 items. in the "Libraries" section. My collection is divided into 7 libraries, but they are all kind of large by themselves.

Using the [#ABC ...Z] letter filter helps, of course, but that is also not restored when navigating back. It always resets to 'All'.

I guess everybody follows slightly different user patterns, but I dont see a UI design conflict of retaining scroll position together with pagination. Its not like one excludes the other. You provide the option to show up to 500 items per page, that implies that those users will scroll. IMO the benefits of pagination is more about memory consumption and load performance. Users with fast machines and connection may prefer maxing out.

**Comment by jonaballen** [comment]
I'd actually prefer infinite scroll to pagination, provided scroll position is restored :P but assume its about performance and load

**Comment by jonaballen** [comment]
This is still an issue for me, still get annoyed by it's adverse effect on basic 'back navigation'

**Comment by inverlock** [comment]
I navigate a pretty large database and when scrolling long distances either through alphabetical/all listings or sideways in the recently-updated section, I tend to go into a lot of different entries to read descriptions and see if I'm interested. Every time I back out no matter where I was I get put back to the top of the "All" section which is pretty annoying. I end up spending half of my time on just finding my way back to where I was so I can carry on. Maintaining the position I was in on the previous page for when I back out of a series description would go a long way for making navigation feel smoother.

**Comment by jonaballen** [comment]
bump, this is annoying
compared to 'plex behavior', plex remembers the scroll position (and letter filtering) when navigating back in the same scenario.
Current ux with page refresh makes basic web navigation a chore.
