### ISSUE TITLE
[Feature Request] Keep 'unread' state of a comic if still on first page(s)

### ISSUE THREAD

**Issue by jonaballen** [gotson/komga#675]
### Is your feature request related to a problem? Please describe.
If i look around for something I read in my large libraries, I usually open issues and so i can see them full-size, to check them out and often its something I dont really feel like reading so I go back and continue looking. But since this changes the read state to "ongoing" it ends up in my "keep reading" section, which gets cluttered. So I need to manually set series/comics to "unread" state. Its annoying and unnecessary.

### Describe the solution you'd like
I'd prefer that if I leave a comic when on page 1, I haven't really started reading yet. Thus it should remain in 'unread' state. 
One exception, if I read something else in a series the next 'ongoing' or 'unread' issue should remain as 'next' in the "Keep reading" section.

### Describe alternatives you've considered or other apps that can do what you want
The threshold before switching state to ongoing could even be the first 2 or 3 pages. 
It would also be nice if its possible to change the read state by clicking/tapping the read state corner or be able to tap  a state button/switch in the comic issue page, like the episode page in Plex

### Additional context
If using plex logic, a show would not appear in "Continue watching" until an episode has been watched at least a few percent, this would apply similar logic.

**Comment by gotson** [comment]
There is a read incognito button that will not mark the status as read.

**Comment by jonaballen** [comment]
But that incognito button is only available in the comic issue page, right? 
It is much easier to directly use the 'hover' read button on the thumbnail when you are looking around for something to read. I believe the hover button is much more commonly used and that the use case I describe above is a common pattern. 

My change request would make the keep reading section less cluttered and more relevant and remove redundant user actions to clean up the list without actually changing functionality. 
As it currently stands, any time i open a comic book in the reader will essentially pin it to my Home and recommended views. I dont think that is what the majority of users would expect or want. 

Using incognito read will always require that the user goes into comic issue page, adding several steps to the casual looking for something scenario.
I hope you would reconsider. 
Thanks

**Comment by jonaballen** [comment]
> There is a read incognito button that will not mark the status as read.

Hi

The incognito button is only available in the comic book page. You would have to open the series and or the comic book to open in incognito mode. Thats a few extra steps.

I believe its much more common that users open the "reader" directly via the 'hover effect' Read button/icon on the thumbnails when browsing around in the library. its just faster and simpler.

As it stands by just opening a book in the web reader, you will effectively 'pin' it to the Home page and recommended views. Just by randomly clicking an item basically. I believe there is a lot of unintentional pinning that will require user to 'clean up' the Keep reading list unnecessarily. 
I just think that you don't really start reading something until you start turning pages.  The first page is basically the same thing as picking up a book and looking at the cover. 

Furthermore, the change request would not break anything and it would improve the use of the Keep reading list or remove the need to clean up.

I hope you would reconsider.

Regardless, thank you :)

**Comment by gotson** [comment]
> Furthermore, the change request would not break anything and it would improve the use of the Keep reading list or remove the need to clean up.

It would change for all the comics that are less than 3 pages (and they are very common in some genre like webtoon).

**Comment by jonaballen** [comment]
I see, yes thats a case I dont know that much about. Only read webtoons rarely :)

But its also possible to make a conditional statement that would cover cases where the comic is say under 3, 5 or 10 pages whichever works best and keep state to unread if on page 1 for any comics with more pages.

**Comment by gotson** [comment]
> I see, yes thats a case I dont know that much about. Only read webtoons rarely :)
> 
> But its also possible to make a conditional statement that would cover cases where the comic is say under 3, 5 or 10 pages whichever works best and keep state to unread if on page 1 for any comics with more pages.

it's convoluted, the incognito button is the way to go. Anyway, i don't think that looking at the first 2 pages will give you a good glimpse of whether you want to actually read that comic or not. If we do this change, someone will complain that reading a couple pages don't mark it as read and is unintuitive, and someone else will complain that the threshold is not the good one for his/her use case.

**Comment by jonaballen** [comment]
yeah, agree it would be convoluted.
and that most likely someone else would complain, so sure I won't nag 
Thanks for taking the time to discuss it though and explain your line of thought.
