### ISSUE TITLE
[Bug] Komga do not handle French Accent

### ISSUE THREAD

**Issue by Maudissure** [gotson/komga#676]
### Komga environment
- **OS**: Docker (Synology)
- **Komga version**: v0.125.4-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest

### Docker settings : 
<html><body>

ENTRYPOINT | java org.springframework.boot.loader.JarLauncher
-- | --
ENV | JAVA_HOME                     /opt/java/openjdk                                        JAVA_VERSION                     jdk-11.0.8+10                                        KOMGA_DATABASE_BACKUP_PATH                     /config/database-backup.zip                                        KOMGA_DATABASE_FILE                     /config/database.sqlite                                        KOMGA_LUCENE_DATA_DIRECTORY                     /config/lucene                                        LANG                     fr_FR.UTF8                                        LANGUAGE                     fr_FR:fr                                        LC_ALL                     fr_FR.UTF8                                        LOGGING_FILE_NAME                     /config/logs/komga.log                                        PATH                     /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                        PGID                     101                                        PUID                     1033                                        SPRING_ARTEMIS_EMBEDDED_DATA_DIRECTORY                     /config/artemis | JAVA_HOME | /opt/java/openjdk | JAVA_VERSION | jdk-11.0.8+10 | KOMGA_DATABASE_BACKUP_PATH | /config/database-backup.zip | KOMGA_DATABASE_FILE | /config/database.sqlite | KOMGA_LUCENE_DATA_DIRECTORY | /config/lucene | LANG | fr_FR.UTF8 | LANGUAGE | fr_FR:fr | LC_ALL | fr_FR.UTF8 | LOGGING_FILE_NAME | /config/logs/komga.log | PATH | /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | PGID | 101 | PUID | 1033 | SPRING_ARTEMIS_EMBEDDED_DATA_DIRECTORY | /config/artemis
JAVA_HOME | /opt/java/openjdk
JAVA_VERSION | jdk-11.0.8+10
KOMGA_DATABASE_BACKUP_PATH | /config/database-backup.zip
KOMGA_DATABASE_FILE | /config/database.sqlite
KOMGA_LUCENE_DATA_DIRECTORY | /config/lucene
LANG | fr_FR.UTF8
LANGUAGE | fr_FR:fr
LC_ALL | fr_FR.UTF8
LOGGING_FILE_NAME | /config/logs/komga.log
PATH | /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID | 101
PUID | 1033
SPRING_ARTEMIS_EMBEDDED_DATA_DIRECTORY | /config/artemis

</body>
</html>

### Describe the bug
Komga parser doesn't seem to handle French accents in books or folders names

### Expected behavior
Parser get all folder or books names

### Actual behavior
Parsing folders or files names with French accent get error.

### Log file
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/BDs/Le cycle de Cyann/HS - La cl? des confins.cbz

Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/BDs/La Geste des Princes D?mons/La Geste des Princes D?mons - Tome 02 - Malagate le Monstre.cbz

**Comment by gotson** [comment]
We have plenty of users with accents or chinese/japanese/korean characters, so it must be something else.

Could you provide:
- a complete log file
- what is the file system of your mounted disk?

**Comment by Maudissure** [comment]
[komga.log](https://github.com/gotson/komga/files/7160820/komga.log)

The file system is BTRFS (synology)

**Comment by gotson** [comment]
Could you also provide the complete json from `<your-server>/actuator/env` ? I don't think it would contain any personal information, but you can send it to me via Discord private message if you want.

**Comment by Maudissure** [comment]
There : 
[komga.json.txt](https://github.com/gotson/komga/files/7160863/komga.json.txt)

**Comment by gotson** [comment]
I think the problem comes from the following environment variables:
```
LANG
LANGUAGE
LC_ALL
```

Could you remove those environment variables from your docker container definition, and try again ?

**Comment by Maudissure** [comment]
Done, and : 
2021-09-14 10:12:43.648 ERROR 1 --- [http-nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/BDs/Le Genie des Alpages/Le g?nie des alpages - 01 Le Genie Des Alpages.cbr] with root cause

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /data/BDs/Le Genie des Alpages/Le g?nie des alpages - 01 Le Genie Des Alpages.cbr

**Comment by gotson** [comment]
can you show how the container is configured in the Synology screen ? The table you posted shows some variables that are set by the container, and not by you.

**Comment by Maudissure** [comment]
Sure : 
![Sans titre](https://user-images.githubusercontent.com/41825213/133240132-f984e4d8-30e1-45ed-a4dc-27547c79b72e.png)

**Comment by gotson** [comment]
can you try to add the following environment variables for the container:
`LANG=en_US.UTF-8`
`LC_ALL=en_US.UTF-8`

For some reason your container inherits system properties, and ends up with the following:
```
"CONSOLE_LOG_CHARSET": {
                    "value": "US-ASCII"
                },
"file.encoding": {
                    "value": "ANSI_X3.4-1968"
                },
"FILE_LOG_CHARSET": {
                    "value": "US-ASCII"
                },
"sun.jnu.encoding": {
                    "value": "ANSI_X3.4-1968"
                },
```

**Comment by Maudissure** [comment]
Working now, thanks !

**Comment by gotson** [comment]
I will try to force it inside the docker image to avoid this kind of problem going forward.
