### ISSUE TITLE
[Feature Request] Search result preview for books should show series context not just library context

### ISSUE THREAD

**Issue by thampp** [gotson/komga#678]
### Is your feature request related to a problem? Please describe.
When searching for a keyword in the main search bar the result preview that is incrementally update with each keystroke shows for books the title and the library. The series is not shown so it's sometimes hard to judge the relevance of the suggested results. If one searches for something specific one knows to be there this is less of a problem. But for more open searches this would be great.

### Describe the solution you'd like
Add the series name in addition to the library name (e.g. just in front of it)

### Additional context
In the screen shot below the series in which the book results are contained could be shown just in front of the "in Comic Library"
![image](https://user-images.githubusercontent.com/13353725/133647385-9ba8504d-1db8-4b51-ab54-e5e75c663b2a.png)

**Comment by gotson** [comment]
Would you be able to share some mockups of how you would like it to look like?
