### ISSUE TITLE
[Bug] Can't navigate read list on book details screen

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#680]
### Komga environment
- **OS**: Ubuntu 21.04
- **Komga version**: v0.127.0-master
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version:
- [x] **I have a problem in the web interface**
  - Browser (with version): Chrome Version 93.0.4577.82, Microsoft Edge 93.0.961.47, iPadOS Safari 14
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
On the book details screen the arrows to navigate the read list are greyed out and not clickable even though there are more books on the read list than shown.

### Steps to reproduce
1. Go on the book details screen of a book in a read list with more items than fit on the page.
2. The readlist won't show all items (in my case only the first 19) and you can't change the list to see more.

### Expected behavior
A white arrow is clickable to navigate the read list.

### Actual behavior
The arrow is greyed out and doesn't allow to navigate the read list.

### Additional context
If I change the zoom level the problem seems to be fixed even if I return to normal zoom level. Reloading makes the bug reappear.
In Firefox 92.0 the arrows are also greyed out but different to the other browsers a scrollbar appears which allows to navigate the whole read list.

### Screenshots
![image](https://user-images.githubusercontent.com/56667539/133681867-c7e5f433-ae1e-41ed-9c06-6621c4fa9ff9.png)
The list ends with volume 98 in the picture even though volume 99 and 100 are part of the read list (volume 99 is currently open and has therefore be part of the read list)

**Comment by gotson** [comment]
Most likely introduced in https://github.com/gotson/komga/commit/fe78f17e5e7c0502867e7b08e4f927801b0d26f4

The scroll is working, so you can still scroll with the trackpad, touch screen, or <kbd>shift</kbd> + mouse wheel
