### ISSUE TITLE
[Bug] pdf font rendering fails

### ISSUE THREAD

**Issue by lurdan** [gotson/komga#682]
### Komga environment
- **OS**: linux 
- **Komga version**: 0.128.1
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [ ] **I am running Komga from the `jar`**
  - Java version:
- [X] **I have a problem in the web interface**
  - Browser (with version): firefox 92.0
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
Komga sometimes fails to rendering font corrrectly.

I can't find the route cause of unstability.
Some fonts display, others don't.
Some komga version has problem, others don't.
Some renders Tofu, others invalid size/style.

### Steps to reproduce
Try to read PDF books which has (CJK) font name embedded (maybe?).
ex. https://www.gakushuin.ac.jp/~881791/mathbook/MB20210216L.pdf

### Expected behavior

![ex-correct](https://user-images.githubusercontent.com/34773/133886502-43a68a79-bd70-4ff3-b834-3646fbb95fe4.PNG)

### Actual behavior

![ex-bad](https://user-images.githubusercontent.com/34773/133886511-32aa47ef-1ad0-4cc3-a1f7-9292e55d79ed.PNG)
![ex-tofu](https://user-images.githubusercontent.com/34773/133886513-9c5ef91e-5f53-42f3-99bd-0f3da307028d.PNG)

### Additional context
Are there any good way to specify / add / controll fonts?
Many of komga users won't need CJK fonts, so it would be good to care locally.

### Screenshots
If needed, I will add them later.

### Log file
docker log outputs like:
```
komga    | 2021-09-18 01:08:00.743  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2286 (CID 08ee) in font CGIITK+RyuminPr6N-Reg
komga    | 2021-09-18 01:08:00.743  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2022 (CID 07e6) in font CGIITK+RyuminPr6N-Reg
komga    | 2021-09-18 01:08:00.744  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2253 (CID 08cd) in font CGIITK+RyuminPr6N-Reg
komga    | 2021-09-18 01:08:00.744  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 913 (CID 0391) in font CGIITK+RyuminPr6N-Reg
komga    | 2021-09-18 01:08:00.744  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2520 (CID 09d8) in font CGIITK+RyuminPr6N-Reg
komga    | 2021-09-18 01:08:00.744  WARN 1 --- [io-8080-exec-14] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 3651 (CID 0e43) in font CGIITK+RyuminPr6N-Reg

komga    | 2021-09-18 01:17:20.406  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2693 (CID 0a85) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.406  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 3187 (CID 0c73) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.406  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 3899 (CID 0f3b) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.407  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 900 (CID 0384) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.407  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 2649 (CID 0a59) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.407  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 1452 (CID 05ac) in font SMYRKP+HiraMinProN-W3
komga    | 2021-09-18 01:17:20.407  WARN 1 --- [io-8080-exec-32] o.a.pdfbox.rendering.CIDType0Glyph2D     : No glyph for 1908 (CID 0774) in font SMYRKP+HiraMinProN-W3
```

**Comment by gotson** [comment]
> Some renders Tofu, others invalid size/style

What does that mean? 

> If needed, I will add them late

Please add to show the rendering difference between the pdf on a reader that renders as expected (and provide app name, version and os), and screenshot of Komga. 

> Are there any good way to specify / add / controll fonts?

I think that apache pdfbox uses the fonts on the machine.

---

Please also provide a complete log file.

**Comment by lurdan** [comment]
> > Some renders Tofu, others invalid size/style
> 
> What does that mean?
> 
> > If needed, I will add them late
> 
> Please add to show the rendering difference between the pdf on a reader that renders as expected (and provide app name, version and os), and screenshot of Komga.

I edited to add screenshots of these symptoms. (by using genuine dockerhub image)

> I think that apache pdfbox uses the fonts on the machine.

Thank you for your hint, finally I've fix it locally adding this small layer to image.
(which generates "expected behavior" shot.)

```
FROM gotson/komga:latest
RUN apt-get update && apt-get -y install fonts-ipafont fonts-ipaexfont
```

> 
> Please also provide a complete log file.

**Comment by gotson** [comment]
The problem with adding a layer is that you will need to rebuild everytime. If you know where the fonts are installed, it would be easier to install them on your host machine, and mourn the folder into the container with a bind mount.
