### ISSUE TITLE
[Feature Request] Bulk edit summary

### ISSUE THREAD

**Issue by kanjieater** [gotson/komga#683]
### Is your feature request related to a problem? Please describe.
If the wrong summary is loaded in multiple books, you have to manually go through them instead of erasing them at the series level.
### Describe the solution you'd like
Allow the summary to be edited in the bulk-edit book metadata modal

### Describe alternatives you've considered or other apps that can do what you want
none, but open to other options

**Comment by gotson** [comment]
Same as for authors bulk edit, the existing dialog is not big enough to accommodate summaries, and adding a new dialog is superfluous IMO.

**Comment by kanjieater** [comment]
Hmm, I get it. At the same time if you have a large series (50 books) it's incredibly tedious to correct it in with the current tools available.
