### ISSUE TITLE
[Feature Request] Add option to set an issue cover in a series as the series poster/cover

### ISSUE THREAD

**Issue by jonaballen** [gotson/komga#684]
### Is your feature request related to a problem? Please describe.
Sometimes the first or last comic book in a series does not have a proper cover, or it's not 'representative' for the series or a series is a collection of miscellaneous books and its best represented by another cover than is automatically selected.

### Describe the solution you'd like
Include the option to "Set as cover for series" in the 'three-dot' menu for a comic book issue

### Describe alternatives you've considered or other apps that can do what you want
Alternatively, the 'Edit series-Poster' dialog could list the various covers for issues included in the series and user could select the one (s)he prefers, similar how plex pulls alternative poster data in the edit meta data dialo (although I guess this is more complex to implement)

**Comment by gotson** [comment]
You can already use local artwork and upload your own cover for series, that should be sufficient.
