### ISSUE TITLE
[Feature Request] Option to set sort order of a series after filename or release date

### ISSUE THREAD

**Issue by jonaballen** [gotson/komga#685]
### Is your feature request related to a problem? Please describe.
A lot of the comic books in my collection lacks proper meta data, while others include it. I have managed this by editing filenames so the filesystems etc will sort them correctly. Komga also pulls meta data which is a very nice feature, and komga also uses the filename as fallback. but occasionally (quite often) a series is a mix up of both which can create conflicts with my manual sort order. 
Other sort methods would also be nice

### Describe the solution you'd like
An option to sort and set book [number] and [sort number] according to the file name or date added (other sort methods perhaps)

### Describe alternatives you've considered or other apps that can do what you want
There is a sort option in the filter menu of course, but that is not persistent and stored for a series the next time I open it.

### Additional context
I can of course choose not to use meta data when I scan a library, but its very nice to have, but all books does not include it. and its a much harder job to add all the meta data than to choose a different sort order

**Comment by gotson** [comment]
This seems very specific to your case. Fix your metadata, or use the bulk edit book dialog, or use the api to implement your own scripts.

**Comment by jonaballen** [comment]
I imagine I am not the only one, I imagine that new users would benefit, since they most likely have organised their collections according to their filesystems before discovering and trying out komga. It would be very convenient to not have to rearrange your collection too much as a ftu.

Since the library edit function already provides several options on what kind of meta data to use or not during scanning, adding a sort method seems reasonable. It would be nice to have the option to use all the meta-data but be still able to use your own file sort order.

Its a 'nice to have' :)
