### ISSUE TITLE
[Feature Request] Add json file support like info.txt/info.json

### ISSUE THREAD

**Issue by ndbiaw** [gotson/komga#688]
### Is your feature request related to a problem? Please describe.
Existing format requires users to provide metadata according to existing templates, cannot add other data fields

### Describe the solution you'd like
Supports various custom data, for example:
```
{
"Title": "Example";
"My rating": "Good";
"Recommend for": [
  "Weeb",
  "Other"
]
}
```

### Describe alternatives you've considered or other apps that can do what you want
Nothing is supported by Komga

### Additional context
This is useful for adding metadata that RFCS doesn't support.

**Comment by gotson** [comment]
Doesn't make any sense. Those fields you give in example don't even exist in Komga metadata model.

**Comment by ndbiaw** [comment]
But being forced to follow a fixed metadata can seem a bit rigid.
