### ISSUE TITLE
[Feature Request] Link to Changelog

### ISSUE THREAD

**Issue by heisarzola** [gotson/komga#691]
Could the version number at the bottom of the side menu be changed to a link to the github changelog/release? 

Watchtower updates the docker image for me, but it's hard to tell what changes have been done without checking the latest releases page.

Most would say an in-platform changelog would be ideal, but this should be a nice compromise.

**Comment by gotson** [comment]
What value would that bring, given you already now where to check for the recent changes?

**Comment by heisarzola** [comment]
It's far from optimal, and especially slow to check on mobile. 

While indeed I do know where to look at, and can even change my watchtower logs to verify that indeed a new update was uploaded, I'd still need either have the releases page bookmarked (which I don't on all my devices) or in the recent search history, else I'd have to google the github and look for the releases button, sitting through the loading of each new page. 

Of course, this is just an exaggerated breakdown, it's far from grueling or painfully slow, but it's still annoying having to check the changes externally only to find out it was a routine edge case bug fix or similar.

**Comment by gotson** [comment]
which link should it point to? The generic [releases page](https://github.com/gotson/komga/releases), or should it point to the actual release details page, for example if you are running ``0.128.0` it would link to [this page](https://github.com/gotson/komga/releases/tag/v0.128.0)?

**Comment by KucharczykL** [comment]
Not the original author but I've noticed you already have a CHANGELOG.md file so why not link to that? For example: https://github.com/gotson/komga/blob/master/CHANGELOG.md#01284-2021-09-23 That would always scroll to the correct version but also allow reading all the changes in the same spot.

**Comment by heisarzola** [comment]
Yea I'd say it'd have to be to either the full releases page, or that md file, the idea just being that you'd just scroll down to view all changes, with the ones at the top being the latest.

After looking at both on mobile and PC, the md file does look more clean for this purpose.

**Comment by gotson** [comment]
> Not the original author but I've noticed you already have a CHANGELOG.md file so why not link to that? For example: https://github.com/gotson/komga/blob/master/CHANGELOG.md#01284-2021-09-23 That would always scroll to the correct version but also allow reading all the changes in the same spot.

the problem with the header links in that changelog is that they need the date too to work

**Comment by heisarzola** [comment]
https://github.com/gotson/komga/blob/master/CHANGELOG.md should always point to the newest one without the need to make a parser for the part at the end.

**Comment by gotson** [comment]
> https://github.com/gotson/komga/blob/master/CHANGELOG.md should always point to the newest one without the need to make a parser for the part at the end.

yes that's what i will go for

**Comment by KucharczykL** [comment]
A small change but really appreciated, thanks!
