### ISSUE TITLE
[Feature Request] Samba/CIFS remote share access

### ISSUE THREAD

**Issue by maaaat** [gotson/komga#692]
### Problem
In a cloud setup where the app server running Komga and the data live on different machines it is not always trivial to connect them to one another. Essentially the mount must be managed outside of Komga. That is all fine in many situations but in the case of cloud setups, for instance docker, the host running the container might be running a stripped down OS where mounting a samba share and exposing it to the Komga container is at least impractical.

### Solution
It would be great if Komga would somehow have the ability to mount remote shares (typically samba, perhaps NFS as well) and manage them.

### Alternatives
Kodi has this feature for similar reasons and it is very convenient. The current alternatives are:
- Manage the samba mount outside of Komga: not practical for cloud deployments.
- Duplicate the entire collection: not very appealing, adds synchronisation burden.
- Modify the official docker image to mount the samba remote on container startup.

**Comment by Kussie** [comment]
Why not just mount them via SMB/NFS on the host OS and pass through to docker or wherever that way?  Thats a lot simpler then building that level complexity into the app itself.   It would also bring a wide range of issues especially for Docker, it would mean all those libraries would need to be part of the app and of the docker images even though a majority of people wouldn't be using them.

**Comment by gotson** [comment]
It seems a very convoluted solution for something that OSes are handling very well for years.

I have zero interest in doing anything remotely close to what you are proposing.
