### ISSUE TITLE
[Bug] Double pages (no cover) jumps pages when moving to next book

### ISSUE THREAD

**Issue by Daedren** [gotson/komga#693]
### Komga environment
- **OS**: Debian 11
- **Komga version**: 0.128.3
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:  0.128.3
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [x] **I have a problem in the web interface**
  - Browser (with version): Firefox 93
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
When reading a comic in "Double pages (no cover)" layout, when moving to the next book from the final page, you won't be moved to the first page of the book.

### Steps to reproduce
1. Read book
2. Go to final page (In this case 20-21)
3. Go to next book

### Expected behavior
The reader should start the next book at page 1

### Actual behavior
The reader started at page 19 out of 21

### Additional context
I believe it's related to one of the pages of the offending book being a double-spread, I can't reproduce on books without double-spreads.

### Screenshots
A screenshot of the page scroller possibly not being at the right position. It's a 21 page book, and the final two pages are being presented simultaneously. Maybe it's supposed to be like this, but this isn't the main problem anyway.
![A screenshot of the page scroller not being at the right position](https://raik.cc/s/firefox_2021-09-22_13-50-29.png?k=MQu0)

**Comment by gotson** [comment]
Probably a duplicate of #689

**Comment by Daedren** [comment]
Looks like it. I'll close this one and move onto there.
