### ISSUE TITLE
[Feature Request] Import ebooks via Internet from local PC

### ISSUE THREAD

**Issue by Letsplaybar** [gotson/komga#696]
### Is your feature request related to a problem? Please describe.
I am currently using a combination of Komga and Calibre server, the main reason why I still use both is that with Calibre I can upload ebooks without having to upload them first to the server like SFTP or similar, but can do this directly via the programme, so that I don't have to give each person who is supposed to upload ebooks their own user, etc. I can also use the Calibre server. This function is unfortunately missing with Komga. Unfortunately, it annoys me that through the Calibre DB structure each ebook is its own series and series are not combined.

### Describe the solution you'd like
The best solution would be an import from the local PC (upload via internet), if the series already exists, the ebook is uploaded into the directory of the series and recognised as a new book of the series, if there is no series yet, a new folder is created, decisions should be created automatically based on the metadata if this is not possible on request to the user.

### Describe alternatives you've considered or other apps that can do what you want
Alternatively, it would also be possible to allow a second structure of the library and orient it to that of Calibre so that you can simply upload the books via Calibre and Komga recognises that a new book has appeared in the library and on the basis of the structure of the name or the metadata, the series is recognised and combined.

Another possibility would be the manual merging of series. If the name = Equals, then the manga are displayed together in one series so that, if necessary, you can manually ensure that all the books in a series are displayed together. or similar to Plex Correct allocation and then a selection of suitable series where you can also adjust the search again.

**Comment by gotson** [comment]
Duplicate of #70

**Comment by gotson** [comment]
You describe what you do, but you don't describe what the problem is. What is is you want to achieve?

**Comment by Letsplaybar** [comment]
I would like to use Komga only if possible, but for this I would need an upload function. If this is not possible, I would like to have a function that either interprets the folder structure of calibre correctly or creates the series based on the metadata, or a possibility to combine series on the web interface so that a series is not created umpteen times from the CalibreDB folder structure, but is only present once. 


![image](https://user-images.githubusercontent.com/20257680/134756955-7dd19a4d-ec6f-47d3-9133-c4217cb10ad8.png)
As you can see on the screenshot, at the moment the solution I have for each book from a series is a separate series that I cannot merge.

The problem is that several people use the server and share their ebooks with each other and I want to automate the whole thing as much as possible (prio 1) (ie. everyone uploads their books into the database themselves, this reduces the effort and traffic and allows everyone to get to the ebooks as quickly as possible without them having to wait for me until I have time to upload them) and if possible, that the whole thing can also be displayed in a readable reader (reason why I also use Komga in addition to Calibre) and at the same time it should be as clear as possible (prio 2) and this is not the case if a separate series is still created for each book due to the folder structure that is predefined by Calibre.

**Comment by gotson** [comment]
Komga relies on the file structure, why not use something that let's you upload books to folders directly?

**Comment by Letsplaybar** [comment]
the machine on which the whole thing runs is accessible via web only via a proxy the ssh is only accessible from an internal network and this should remain so. (security) Furthermore, the users should only be able to upload the files and do themselves as little wrong as possible, here Calibre has a simple and beautiful solution with which every DAU gets along and no external program is needed to upload the files and pushes the file here even in the right folder for their structure through the metadata. In addition, for the series seems to exist a database entry, otherwise you could not change the name, which is why it should also be possible to make the whole series handling more flexible and if at all as init worth the folder structures to use and then a manual edit in the interface 2 series to unite in which you call the name bsp. in the same.

**Comment by gotson** [comment]
> every DAU

What is this?

---

I don't really get your use case tbh. You want users to upload files, but you don't want them to access the file structure directly, is that correct?

**Comment by Letsplaybar** [comment]
DAU = dumbest user to assume

**Comment by Letsplaybar** [comment]
yes it is, among other things. But above all I want to keep it as easy as possible for others to upload their series without me doing it for them, so that the e-book is available to other users as soon as possible.
