### ISSUE TITLE
[Bug] Collections Not Appearing As A Filter (Tachiyomi)

### ISSUE THREAD

**Issue by heisarzola** [gotson/komga#697]
### Komga environment
- **OS**: Android
- **Komga version**: Latest
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest on a raspberry pi 4 b (arm7l)
- [X] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: latest stable (0.12.1)
  - Tachiyomi extension version: latest (1.2.31)

### Describe the bug
The collection dropdown always appears empty, the only option being "None", while all other filters update normally.

### Steps to reproduce
Seems pretty consistent on all devices for me, just by trying to use the dropdown.

### Expected behavior
For the dropdown to be populated with the combined collections list.

### Actual behavior
The dropdown is empty.

### Additional context
I'm not sure when did it started happening, but I was only ever able to see the dropdown items once, while I was still making the komga libraries, it changed to None ever since. Tried removing all special characters on all collections (keeping it to a-zA-Z), tried only having a single library, tried adding and removing books, all these alongside the standard reboot device, force close tachi, delete cache, even a different device as described before, etc. 

Every time I made these changes, I checked the rest of the filters (tags, libraries, etc.), and those did update properly each time, as a combined lists of all items in all libraries. The only thing I haven't tried was to redo the komga libraries, but seems overkill and too time consuming for just a test. 

The only "abnormal" thing I can remember that happened at some point, was that I moved all the items of a collection to another directory, after a new scan the old collection got scrapped for now having 0 items, so I had to remake it.

Each item in the entire library is either cbz or zip files, and each item is in at least one collection, each item is readable (none are corrupted), and everything should total around 50 collections.

### Log file
I tried looking at the log files when I clean installed tachiyomi + komga extension on a different device, it didn't show anything abnormal, just the regular logins, book fetches, and the like. Same for when the filters were provided to the new device after waiting a bit, so no relevant logs were found.

**Comment by gotson** [comment]
Please open the issues at https://github.com/tachiyomiorg/tachiyomi-extensions and tag me
