### ISSUE TITLE
DB location on qnap.

### ISSUE THREAD

**Issue by jun6lee** [gotson/komga#698]
Either I've forgotten the admin password or the database has gone corrupt.
Either way, I need to get my hands on the database.

Where is it stored in a QNAP setup?
I've tried looking under the .qpkg folder to no avail.

**Comment by jun6lee** [comment]
I've found it and made a copy of the sqlite file. Although I can see the USER table, the password is encrypted.
Is this something I can decipher, replace to get access back?

If I remove the user record, would that help keep the library intact and force a fresh new admin user prompt?

**Comment by jun6lee** [comment]
Read all about the hashing, so getting my password back is out of the question.
Can I remove the one admin user so that a new one can be forcefully created/claimed?

If not, I'll have to blank, and start my library all over again.

**Comment by jun6lee** [comment]
Resolved. 

I copied the sql file elsewhere, deleted the user record (after some headbanging with foreign key restraints).
Replaced the SQL, restarted. It eventually asked me to set up a user like a new install.
Library was retained. Documenting it here in case it helps someone, some day.

**Comment by gotson** [comment]
For the record you can just replace the hashed password with a new hash. The hashing algorithm is `bcrypt`.
