### ISSUE TITLE
upload books from web UI

### ISSUE THREAD

**Issue by FrouxBY** [gotson/komga#70]
Hello,
First, thank you for this great project, this is a handy addition to calibre-web !

I know that the inspiration for this project is more plex/jellyfin, but I would have like to be able to add books from the web UI. 
I explain my use-case and let you judge if this is a good idea.
For a service like jellyfin I use a lot of automation, so I don't need users to upload content, but my book library is more an aggregation of what my family and friend can share.

Thanks again !

**Comment by gotson** [comment]
Hi,

at the moment users can't see anything related to the file structure behind Komga, which is only available to administrators. An upload functionality would require users to choose where to place books in the directory structure. Would your users be able to handle that ?

In the meantime, you could always use a file sharing service like Dropbox or Google Drive, and add a Komga library pointing to that folder. That way users deal with a tool they know and which is made exactly for this purpose, and you still reap the benefits in Komga. What do you think?

**Comment by FrouxBY** [comment]
I think my user will be able to manage that, but probably not for all user, and it's better if they don't have to think about it anyway.

However, if you choose a library and the serie (either amongst existing or new), this give you a unique path (the library folder have been chosen by an administrator) to put your imported file.

Obviously this requires a little bit more UI than just a simple uploader. 

I agree than in the meantime file sharing using Nextcloud, Drive or any other cloud services would work.

**Comment by gotson** [comment]
Indeed, choosing a series would be enough as they have unique path (don't even need the library).

File naming would be left to the admin of the server to clean up afterwards I guess 🤔

**Comment by billsargent** [comment]
I'd also like to see this as an option. It's only me and a few friends using my setup. I'd also like to see the ability to move items to different libraries both within its database and in the filesystem. :)
