### ISSUE TITLE
[Feature Request] Option to hide item in Browse if in is a collection

### ISSUE THREAD

**Issue by JamesDAdams** [gotson/komga#706]
### Is your feature request related to a problem? Please describe.
I have a big collection of Marvel and D.c comics, so, when I want to browse my library for the other comics available it is very long.

### Describe the solution you'd like
An option that could be really practical and to be able to hide in browse the comics that are present in a collection.

### Describe alternatives you've considered or other apps that can do what you want
I don"t no

### Additional context
![image](https://user-images.githubusercontent.com/20860324/136673233-61890c63-10c6-45bc-8b39-b14585ab9403.png)

![image](https://user-images.githubusercontent.com/20860324/136673285-c37d82c2-fb3a-4fca-b7e2-6d9ea6c474ec.png)

**Comment by gotson** [comment]
Duplicate of #230
