### ISSUE TITLE
[Feature Request] View the library without an account

### ISSUE THREAD

**Issue by JamesDAdams** [gotson/komga#708]
### Is your feature request related to a problem? Please describe.
I would like an option in komga so that people who view my library without having an account

### Describe the solution you'd like
1 : A system that allows you to consult libraries without an account
2 : If the first solution is too complicated/long an option that will add a default account which will be pre-filled on the login page.

**Comment by MagikarpLaCarpe** [comment]
You can already do it by seting up a reverse proxy. Browser have also auto fill option, you jutust  need to setup a trash account ^^

**Comment by gotson** [comment]
Duplicate of #306

**Comment by JamesDAdams** [comment]
> You can already do it by seting up a reverse proxy. Browser have also auto fill option, you jutust need to setup a trash account ^^

Do you have an example of how to do it please ?
