### ISSUE TITLE
Add a no-resize option to the web reader

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#71]
I just read some manga where the fit-to-height showed the images a bit too small to read and fit-to-width showed them too big and blurry.

Would it be possible to add the option to not resize the image and show it in its original size?

**Comment by gotson** [comment]
I'll have a look while i'm revamping the webreader. Could you share what was your screensize and the page original size?

**Comment by muchtea** [comment]
My screen-size is width: 1920px and height: 1080px (but only about 940px usable for the actual page height due to browser and windows toolbars).

A few different page original sizes where this issue appeared: 

- width: 870px height: 1236px
- width: 1000px height: 1400px
- width: 800px height: 7320px (this one is from some manhua/web-comic, which I just remembered might also benefit from this no-resize option)

**Comment by muchtea** [comment]
I just tried the beta release and it works, thank you very much!

**Comment by gotson** [comment]
I couldn't get it to display horizontal scrollbars if the content is wider than the screen, but i thought this was not really useful anyway, so i stopped trying :)

**Comment by muchtea** [comment]
Yes, that might be useful to have for a few cases, but I currently can't think of a comic where an image is that wide, so unless someone else has a pressing need for that, it can probably be done at some point in the future.
