### ISSUE TITLE
[Feature Request] OPDS-PSE server side sync

### ISSUE THREAD

**Issue by Hiren-Z** [gotson/komga#710]
### Is your feature request related to a problem? Please describe.
OPDS-PSE doesn't track server side or tie into "Keep reading" and track progress.

### Describe the solution you'd like
Add the ability to enable server side tracking to allow seamless transitions between devices.  

### Describe alternatives you've considered or other apps that can do what you want
While testing Kavita I discovered this feature and quite liked it.  I have been using Panels but that doesnt sync to the web interface.

**Comment by Hiren-Z** [comment]
Tired babbling,

I'm honestly not sure where I was going with any of that.  PS sorry about the late reply.

**Comment by gotson** [comment]
See https://komga.org/guides/opds.html#mark-read-progress-while-streaming-pages for usage
