### ISSUE TITLE
[Feature Request] OIDC Account Creation

### ISSUE THREAD

**Issue by Banh-Canh** [gotson/komga#716]
Hello,

### Is your feature request related to a problem? Please describe.
I tried and managed to make OIDC login work successfully (using Authentik). Thing is, local users have to exist in Komga before they can log in, I get:
"OAuth2 login error: no local user exist with that email"
Once the account is manually created in Komga with an account with an email existing in my IdP, it works but that is not ideal imo.

### Describe the solution you'd like
On OIDC login, auto-create users that don't exist locally in Komga so we can fully make use of an Identity Provider (like Authentik or Keycloak) ?

### Describe alternatives you've considered or other apps that can do what you want
Allowing LDAP user sync so user can be present before login could also help making it works as a workaround.

### Additional context
The goal would be to be able to fully manage users in an Identity Provider and allowing SSO.

Thanks,

**Comment by PoGo606** [comment]
That would be a nice to have indeed. I use oauth2 with Keycloak in order to avoid having users databases everywhere ;)

**Comment by PoGo606** [comment]
It works like a charm, thank you !
