### ISSUE TITLE
[Feature Request] More Status Choices

### ISSUE THREAD

**Issue by LeeThompson** [gotson/komga#719]
Currently, status is "Ended", "Ongoing", "Hiatus" and "Abandoned".

Status is missing a number of possibilities.
* "Limited Series" "Mini-Series" "Maxi-Series" "Event Series" (These are all more or less the same meaning but different publishers use different terms) (You can, of course, just use "Ended" for these but it would be nice to be more technically correct)
* "Special" "One-Shot"
* "Omnibus" "Collection" "Trade Paperback"

Although it supports epub books, Komga *really* isn't set up for doing ebooks very well as *none* of the current status values really handle that (well Ongoing might fit the few book series that truly are ongoing efforts).   It would also need to support nested series since many science fiction book series in particular have sub-series and you'd want a way to have those reflect a reading or continuity order.

Possible book status values:
* "Short Story"
* "Short Story Collection"
* "Omnibus"
* "Novel"
* "Trilogy"
* "Duology"
etc

**Comment by gotson** [comment]
Status defines the series at a point in time, which is now. It can change. A series that just started is Ongoing. Once finished, it's Ended.

What you describe has nothing to do with status, but describes a type of series. You can use Tags for all of those, that will work.

**Comment by gotson** [comment]
> It would also need to support nested series since many science fiction book series in particular have sub-series and you'd want a way to have those reflect a reading or continuity order.

Use collections or readlists for that purpose.
