### ISSUE TITLE
Remove blank space between pages in Double Page mode

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#72]
One of the useful applications of having a double page mode in the web reader is being able to view the two halves of a split double-page at the same time. Unfortunately, the current implementation separates the two pages with a large blank space so that it ends up looking like this

![2020-01-14 14 56 46 komga datahoarder dev c916223bc00a](https://user-images.githubusercontent.com/44198148/72350877-9003da80-36df-11ea-8a9f-a2e1b73b9cc9.png)

instead of like this

![2020-01-14 14 56 46 komga datahoarder dev c916223bc00a](https://user-images.githubusercontent.com/44198148/72351133-0accf580-36e0-11ea-947c-5407d16f48a9.png)

**Comment by gotson** [comment]
Yeah, I know, I spent some time already but can't figure out why this is happening. I need to reproduce with a simpler code pen and take it to the Vuetify devs, I suspect there could be a missing feature in the `v-img` to limit the width and prevent the responsive container to take up horizontal space, messing up the flexbox.

**Comment by muchtea** [comment]
Just tried this and it works, no more empty space between pages.
