### ISSUE TITLE
[Feature Request] Convert book from cbr (or rar) to cbz

### ISSUE THREAD

**Issue by a-camacho** [gotson/komga#720]
### Is your feature request related to a problem? Please describe.
When having a large library, Komga is not able to read .cbr files and files compressed with rar.
I created a script that automatically detects if book is :

`Unsupported | Media type is not supported | application/x-rar-compressed; version=5`

In that case, script unrars directory and zips it.
Then it renames it to .cbz and everything is working.

### Describe the solution you'd like
Could you embed unrar in docker image, and create a button to automatically convert book ?

### Additional context
I don't think the script is very interesting, but I can share it if needed.

Thanks a lot for your great product.

**Comment by gotson** [comment]
I don't want to rely on external binaries. There is already conversion from rar 4 to cbz in Komga.

**Comment by a-camacho** [comment]
Oh ok, thanks, didn't know there was for v4.

**Comment by gotson** [comment]
https://komga.org/guides/libraries.html#automatically-convert-to-cbz
