### ISSUE TITLE
[Feature Request] Webtoon reader can't trigger jump to next chapter when scrolling until the end

### ISSUE THREAD

**Issue by east-mist** [gotson/komga#722]
### Is your feature request related to a problem? Please describe.
When I read webtoons\comics on my notebook I use solely Page Up/Down buttons or direction arrows.
Reaching the end of chapter means I have to find the tiny icon with my mouse or click twice in the bottom right of page.

### Describe the solution you'd like
When you reach the end of chapter by double Right arrow or double Page\Down going to the next chapter.
Or any other combination.

### Describe alternatives you've considered or other apps that can do what you want
On Lezhin when you scroll till the end of chapter you automaticly jump to the next.
On readmanga dot io (russian website) when you reach the end of chapter and push the rightarrow button, you are redirected to the next chapter.

**Comment by gotson** [comment]
If you reach the end of a book, you can click again (mouse or keyboard shortcut) to go to the next book.

**Comment by east-mist** [comment]
> 
> 
> If you reach the end of a book, you can click again (mouse or keyboard shortcut) to go to the next book.

There isn't a keyboard shortcut for next chapter, that's the issue. At least, I looked for it in guide on website and in help section in webreader and didn't find an answer.

**Comment by gotson** [comment]
Then you were not clear, because in both the solution you would like or other apps doing so, you described exactly the double click.

So what is it you really want, and why?

**Comment by east-mist** [comment]
> 
> 
> Then you were not clear, because in both the solution you would like or other apps doing so, you described exactly the double click.
> 
> So what is it you really want, and why?

I want to be able, when I reach the end of chapter, press a button on my keyboard and go to the next chapter.
It's faster and easier than doing it with mouse.
When i read comics I use page up\down buttons on my keyboard. 
In examples I described:
1) Lezhin: I press page down and when I reach the end of chapter i automaticly go to the next
2) Readmanga: I press rightarrow on my keyboard and I go to the next chapter
I both cases i don't use mouse just my keyboard

**Comment by gotson** [comment]
This behavior already exists in Komga.

**Comment by east-mist** [comment]
> 
> 
> This behavior already exists in Komga.

What have I press on my keyboard then? I don't understand

**Comment by gotson** [comment]
If you are on the first page and press <kbd>left</kbd> or click on the left side of the screen (in left to right, inverse for right to left), or if you are on the last page and press <kbd>right</kbd> or click on the right side of the screen, a pop-up will show. If you press/click again, you will go to previous/next book (if any).

<img width="571" alt="Screenshot 2021-11-16 at 10 03 24" src="https://user-images.githubusercontent.com/2139133/141882394-a67fec18-0fcf-4570-a26d-5bb94a951a35.png">

**Comment by east-mist** [comment]
> 
> 
> If you are on the first page and press left or click on the left side of the screen (in left to right, inverse for right to left), or if you are on the last page and press right or click on the right side of the screen, a pop-up will show. If you press/click again, you will go to previous/next book (if any).
> 
> <img alt="Screenshot 2021-11-16 at 10 03 24" width="571" src="https://user-images.githubusercontent.com/2139133/141882394-a67fec18-0fcf-4570-a26d-5bb94a951a35.png">

I just checked it.  Left, right, and down works in left to right, inverse and vertical reading mode.. Thank you, it solved half of problem.
But when I am in webtoon mode, neither of above works. Is it an alternative navigation for webtoon? What have I press then?

**Comment by gotson** [comment]
> But when I am in webtoon mode, neither of above works. Is it an alternative navigation for webtoon? What have I press then?

Ah! Yes, it seems in Webtoon it only works when you press the bottom part of the screen, but not via keyboard shortcuts, as there are no keys to move pages, and the keys (space, up/down, pgup/pgdn) do make the scrollbar move, but don't do anything specific apart from that.

We would need to have a way to detect scrolling when already at the max, and trigger the same behaviour. Let me reopen that now that what's needed is clearer.

**Comment by gotson** [comment]
I've added listeners for ArrowUp/PageUp and ArrowDown/PageDown/Space, so that those keys can trigger the jump if pressed and if it can't scroll anymore.

**Comment by east-mist** [comment]
> 
> 
> I've added listeners for ArrowUp/PageUp and ArrowDown/PageDown/Space, so that those keys can trigger the jump if pressed and if it can't scroll anymore.

Thank you!
Komga the best!
