### ISSUE TITLE
[Feature Request] Ability to hide recomendation

### ISSUE THREAD

**Issue by huma2000** [gotson/komga#724]
### Is your feature request related to a problem? Please describe.
When browsing a collection, by default, Komga shows a section with recommended comics, this feature is not always useful to everyone and sometimes is preferable to browse directly the collection

### Describe the solution you'd like
Adding a toggle to switch on and off the recommendation area

### Describe alternatives you've considered or other apps that can do what you want
Alternatively, having the possibility to select which view you want each collection to open on by default will work

**Comment by gotson** [comment]
> When browsing a collection, by default, Komga shows a section with recommended comics

Could you please clarify this or show an example? Because this feature doesn't exist, so maybe you confuse with something else..?

**Comment by huma2000** [comment]
Hi,

The section I am referencing is this one:

![image](https://user-images.githubusercontent.com/9518124/141879709-07d1206e-a545-4962-af4f-ca5ef4433348.png)

**Comment by gotson** [comment]
OK, that's when browsing a library, not a collection. You can go to browse and the preference for this library will be saved, so whenever you go back to it, it will show browse instead of recommended.

I have no plans to offer an option to change that behaviour.

**Comment by huma2000** [comment]
I see, I did not realize it was saved, thanks for the support
