### ISSUE TITLE
[Feature Request] Read List Reading Order

### ISSUE THREAD

**Issue by polybius01** [gotson/komga#725]
### Is your feature request related to a problem? Please describe.
The Read Lists don't have a proper reading order.

### Describe the solution you'd like
Would it be possible to add a reading order to the Read Lists? Is that something Komga can control?

### Additional context
For example, I have all the DC One Million issues but the read list displayed is not in reading order (First Chronos 1,000,000, JLA 023 then DC One Million 1, etc... is the proper order but the read lists show all the DC One Million issues all together).

**Comment by gotson** [comment]
> The Read Lists don't have a proper reading order.

They do, it's manual. See here on [how to reorder them](https://komga.org/guides/readlists.html#edit-read-list-elements).

---

You are talking about reading orders coming from external website, this is not supported at the moment in Komga. You can however [import reading lists from ComicRack](https://komga.org/guides/readlists.html#import-read-lists-from-comicrack), and many people share ComicRack reading orders that way.

**Comment by polybius01** [comment]
Thanks!
