### ISSUE TITLE
[Feature Request] Browse settings

### ISSUE THREAD

**Issue by Mifgan** [gotson/komga#726]
### Is your feature request related to a problem? Please describe.
Currently, when you use the browse tab for a library, it will list your collection based on the folder name, calling these series. 
I use Komga not only to organise my comics but also my epub and pdf collection. 

For example, in my 'Conservation and museology' collection, I have two main folders, 'Conservation' and 'Museology'. The first one has a bunch of different folders i.e. 'Registration' or 'Literature MICR-GENT'. The second folder has only one subfolder, 'Thesauri'. Both folders have many loose files. 

In Komga all the folders are listed at the top and I can't see my individual files unless I open one of the folders, having this result:
![image](https://user-images.githubusercontent.com/13572985/142009119-0c49b83f-8dd7-44af-8bca-13eb74774411.png)

### Describe the solution you'd like
I would love an option (globally in settings or per library, I don't mind either) to switch the browse tab on browsing 'by series' (current view), by folder structure (the folder structure of the source) or by files (all files of one library in one big folder). 

Thanks!

**Comment by gotson** [comment]
> by folder structure (the folder structure of the source)

This has been [requested in the past](https://github.com/gotson/komga/issues/401), and won't be done.

---

Komga is opinionated, and is made to work with series. The recommended way to handle one-shots is to put them in their own folder.
