### ISSUE TITLE
[Feature Request] Automanual Read List and Collection Creation

### ISSUE THREAD

**Issue by omgthegreenranger** [gotson/komga#727]
### Is your feature request related to a problem? Please describe.

Read Lists are automatically generated by StoryArc metadata, or manually by searching and adding comics. The downside to this is that ALL story tags are turned in to a read list, including short two- or four-part arcs in a series.

Collections are manually created by searching your library and accessing context menus to add, but it isn't an intuitive creation process.

Currently, there is no simple way to "automanually" generate a new read list or collection FROM the Metadata, so you're either deleting dozens and dozens of read lists of two/four issues, or you're searching for specific issues in your library, which is time consuming.

### Describe the solution you'd like

Within the comic/issue information screen (or perhaps via another menu), I'd like to be able to click on any of the StoryArc tags (or any of the metadata tags for that matter, such as artist, author, character if present, etc) and quickly generate a collection or a read list from any other issues that have that tag.

Thus, you can easily create a collection of all comics drawn by Humberto Ramos, or create a reading list of Absolute Carnage, without having to do significant manual searching. This won't be perfect in all cases, but it would get most of the job done. It would also add new issues as they appear in the library.

Another additional feature would be to modify search results with a "Create collection/Read List from search" and allow for searching metadata tags.

Adding multiple filter options for the Collection/Read List generator would also help this process.

### Describe alternatives you've considered or other apps that can do what you want

Mylar kind of does it with their Story Arcs and reading lists engines, but they are glitchy and aren't very accurate or customizable.

**Comment by gotson** [comment]
> Another additional feature would be to modify search results with a "Create collection/Read List from search" and allow for searching metadata tags.

you can [already search by tags](https://komga.org/guides/search.html). You can already add series or books to collections or read lists from the search result screen.

**Comment by omgthegreenranger** [comment]
True. I was mostly thinking that if you have the mechanic to create a read list from a tag, you could add it to "add all from search results" rather than doing it by individual issues.

**Comment by omgthegreenranger** [comment]
Don't want this one to be closed, because I still think easier read-list generation is important to larger-library management.
