### ISSUE TITLE
[Feature Request] Genre/Tag filter AND operator option

### ISSUE THREAD

**Issue by WorldEntityGravity** [gotson/komga#728]
### Is your feature request related to a problem? Please describe.
When browsing a library and trying to find what to read next, one issue I'm having is how the Genre and Tag filter works. Usually, the way most webpages work, when filtering multiple genres or tags, is by having an AND operator (for example: Action AND Adventure). But in here an OR operator is used, which makes filtering on multiple genres or tags harder then what it should be. Yes, you can use FTS but it is anoying on a tablet or phone and the single-row search result view isnt great for a quick overview.

### Describe the solution you'd like
I would like if an AND operator was used when filtering multiple genres or tags. I realise that there might be some use-cases for when you'd want an OR operator (not that I know of any), so perhaps an option for it could be made on a per server, library or user basis, or even a filter option.

**Comment by gotson** [comment]
I suppose you are talking about the filter panel? Alternatively you could use the search with AND operators, see https://komga.org/guides/search.html

**Comment by WorldEntityGravity** [comment]
Yes, the filter panel, and as I mentioned Full Text Search isn't that great for a quick overview nor fast. FTS is great for when you know more or less exactly what you're looking for. But when you're just lazily browsing, the filter panel is better. Which is why it would be more usefull having it filter multiple genres and tags with AND instead of OR.
