### ISSUE TITLE
Add support for 7z / cb7

### ISSUE THREAD

**Issue by inthebrilliantblue** [gotson/komga#73]
Would it be possible to add support for 7z and cb7 files?

**Comment by gotson** [comment]
This format is not mainstream, the only ones I have seen are packaged by individuals, often who don't know the difference between zip and 7z.

The scene doesn't use that format either. 

Do you have many of those?

**Comment by inthebrilliantblue** [comment]
I mostly get them from scripts that pull from RSS feeds that, like you said, are updated sometimes by people who dont know any better. Would be a nice add, but I can make a script to automatically change them if need be.

**Comment by gotson** [comment]
I had a look, unfortunately the 7zip library available in Java (via Apache Commons Compress) does not handle random access, meaning archive entries must be processed sequentially. The code is not great, and I fear the performances will not be good either.

I will drop this for now, unless a proper library is available, but given the 7zip format is quite old, and nothing has been done on this front for years, it's unlikely.

**Comment by PoloDePoli** [comment]
Any chance to reconsider the dropping of this feature?
All of my library is in cb7 and it is so on purpose my cb7 contains my webp versions while png/jpg are in cbr/cbz and so I am able to avoid the error of reconverting an already converted comic to webp.
Even if performance is degraded to some extent it would be appreciated.

**Comment by gotson** [comment]
No, 7zip as a format does not support random access, that's incompatible with extracting a single file from the archive.
