### ISSUE TITLE
[Feature Request] Scrolling able to trigger next chapter

### ISSUE THREAD

**Issue by Seishirou101** [gotson/komga#735]
Would it also be possible to trigger next chapter action while scrolling? Issue request #722, the commit ac3d969a0f79bc1888be8d356caf364dd1e568cb added listeners to ArrowUp/PageUp and ArrowDown/PageDown/Space, but could another trigger be added to it to also trigger on scrolling when at max?

**Comment by gotson** [comment]
Please use the issue templates.
