### ISSUE TITLE
[Feature Request] Add Keep Reading and On Deck to OPDS

### ISSUE THREAD

**Issue by Hiren-Z** [gotson/komga#737]
### Describe the solution you'd like
I would like to have Keep Reading and On Deck populate inside a folder in OPDS. 

### Describe alternatives you've considered or other apps that can do what you want
Kavita offers this

### Additional context
 This will allow for continuing where you left off without tracking down what you want to read in the folder structure.

**Comment by gotson** [comment]
Regarding _Keep Reading_, bear in mind that at the moment no OPDS-PSE client could resume reading from the last page, it will always start at the first page.

I was thinking we could upgrade [the existing OPDS-PSE extension](https://vaemendis.net/opds-pse/) to add a new attribute that would indicate the last page read:

```xml
<link rel="http://vaemendis.net/opds-pse/stream"
        type="image/jpeg"
        href="/opds-comics/stream/1217?page={pageNumber}&width={maxWidth}"
        pse:count="35"
        pse:lastRead="10"
/>
```

We would obviously need the clients to add this behaviour. Panels would most likely be onboard with this, but Chunky being almost abandoned wouldn't happen.

**Comment by gotson** [comment]
Panels already added support for my suggestion, it will be available in their next release. Once the changes for #285 are merged I'll add support for Keep Reading and On Deck to OPDS, as well as the lastRead position.

**Comment by fillito** [comment]
Thanks for pushing the standard forward! This addition looks great to me 👌 

The next version of Panels (likely to be 2.10.0) will have support for it.

**Comment by Hiren-Z** [comment]
That's awesome!  Thank you all for your hard work and support!!!!

**Comment by majora2007** [comment]
@gotson If the spec is changing and apps are updating, should we consider hosting the spec like Ubooquity did so that we have a more relevant living document?

**Comment by gotson** [comment]
> @gotson If the spec is changing and apps are updating, should we consider hosting the spec like Ubooquity did so that we have a more relevant living document?

That's the plan. I already had [a mirror](https://github.com/gotson/odps-pse) of the spec on Github, which is [published](https://gotson.github.io/odps-pse/) with Github pages.

**Comment by gotson** [comment]
@fillito @majora2007 the OPDS PSE spec has a new home, under the anansi-project organization: https://github.com/anansi-project/odps-pse

The 1.1 spec is available here: https://anansi-project.github.io/odps-pse/v1.1.html

**Comment by majora2007** [comment]
Looks good, thanks goston.
