### ISSUE TITLE
Add option to disable web reader animation

### ISSUE THREAD

**Issue by MEGAMENE** [gotson/komga#74]
Hi, would it be possible to add an option to remove the animation when you change pages on the web reader?
An option for it to work like the web reader in Ubooquity would be great.

**Comment by gotson** [comment]
It's possible, but removing the transitions make it less intuitive to know what's happening. I honestly never understood why there was options in various readers to remove transitions.

Vuetify has support for custom transitions also, if you find it too slow.

**Comment by MEGAMENE** [comment]
I usually just disable transitions in most comic/book readers, I just prefer the speed and I think it's intuitive enough.
In this particular case the transaction is too distracting, if I'm reading on a widescreen display my eyes want to follow the image sliding out and the next page.

At least that's my experience with it.

**Comment by gotson** [comment]
Fair enough. 

Problem I have is there's more and more options on this reader, and not enough screen real estate to display everything!

**Comment by MEGAMENE** [comment]
Yeah, I get that.
Maybe an option outside of the reader?

**Comment by gotson** [comment]
I was thinking of an "advanced settings" button that would open a dialog with options that are not book specific.

For instance RTL, double pages, and to some extend fit width / height are specifics to books, hence it makes sense to have those easier to reach, while disabling transitions is a user specific setting, hence can be moved à bit further.

I am also thinking of a way to hide keyboard shortcuts on touch-only devices, which are the bunch of smaller screen devices. That would free up some space too.

**Comment by MEGAMENE** [comment]
Yeah, that sounds good.
I was think it could also be in a specific area for user settings.

**Comment by gotson** [comment]
Indeed that's also a good idea. We could think of this setting as a server side user setting that would apply to all the compatible clients. At the moment there's only the webreader, but later on it we have some native apps it would be nice to also honor this setting.

In this case the user preference screen would end up in the left menu bar in the user settings, where you can already change your password. 

I would need to setup some server side api to store those settings per user.
