### ISSUE TITLE
[Feature Request] Parse translators from ComicInfo.xml, and display it on the Tachiyomi extension

### ISSUE THREAD

**Issue by ToaHartor** [gotson/komga#740]
### Is your feature request related to a problem? Please describe.
Manga chapters can be translated by groups of scanlators or by official ones.
In the metadata of a chapter, the field translator can already be completed manually but not directly from the ComicInfo.xml, so it can't be automated.

### Describe the solution you'd like
When reading the ComicInfo.xml to fill the metadata of a book/chapter, also parse a `<Translator>` field which would list the translator(s) who worked on it. Then on the Tachiyomi extension for Komga, they could be displayed under the chapter name (like with the MangaDex extension) :
![Screenshot_20211207-004311_Tachiyomi](https://user-images.githubusercontent.com/41634031/144942129-5d453a71-ecf0-493d-bcf1-276a90d4185b.png)
(here `/a/nonymous` is the scanlator)

**Comment by gotson** [comment]
There's 2 different things in what you are saying:
1. you want to import the `<Translator>` element of `ComicInfo.xml` into Komga, as an author with the `translator` role.
2. you want to display the author with the `translator` role of any book as the Scanlator in Tachiyomi.

Point 1 is debatable, there is no `<Translator>` element inside the [ComicInfo schema](https://github.com/gotson/komga/blob/master/komga/schema/ComicInfo_v2.xsd). **Is that a tag you set yourself in your files?**

Point 2 is possible, I was not aware there was a [scanlator field on SChapter](https://github.com/tachiyomiorg/tachiyomi/blob/ff369010074b058bb734ce24c66508300e6e9ac6/app/src/main/java/eu/kanade/tachiyomi/source/model/SChapter.kt#L16), so we can add that.

**Comment by ToaHartor** [comment]
For the point 1, that's a tag I add in the ComicInfo. I wasn't familiar with the fields the ComicInfo schema had and I was looking for a way to add this info to the metadata. I found that in #614 the Translator field was added and since other Author fields like Writer or Penciller were parsed, I thought that this field also existed in the ComicInfo and could be filled automatically.

**Comment by BaronKrause** [comment]
> There's 2 different things in what you are saying:
> 
> 1. you want to import the `<Translator>` element of `ComicInfo.xml` into Komga, as an author with the `translator` role.
> 2. you want to display the author with the `translator` role of any book as the Scanlator in Tachiyomi.
> 
> Point 1 is debatable, there is no `<Translator>` element inside the [ComicInfo schema](https://github.com/gotson/komga/blob/master/komga/schema/ComicInfo_v2.xsd). **Is that a tag you set yourself in your files?**
> 
> Point 2 is possible, I was not aware there was a [scanlator field on SChapter](https://github.com/tachiyomiorg/tachiyomi/blob/ff369010074b058bb734ce24c66508300e6e9ac6/app/src/main/java/eu/kanade/tachiyomi/source/model/SChapter.kt#L16), so we can add that.

Would a similar thing be possible for the Komga Paperback extension if it doesn’t already? Similar to Tachiyomi it shows the scanlator groups under the chapter name on many sources (like the mentioned MangaDex).
