### ISSUE TITLE
[Bug] Decimal chapter numbers shift up the series numbering by 1 each even after being corrected in the Web Interface

### ISSUE THREAD

**Issue by BaronKrause** [gotson/komga#741]
### Komga environment
- **OS**: Pop_OS! 21.04
- **Komga version**: v0.134.1-master
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:
- [x] **I am running Komga from the `jar`**
  - Java version: OpenJDK Runtime Environment 11.0.11
- [ ] **I have a problem in the web interface**
  - Browser (with version):
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
Chapter numbers are shifted upward when there is chapters with decimal places (for example 4.5). That Chapter 4.5 will get labeled as Chapter 5, shifting everything up 1.

You can change it in the web interface and make it called chapter 4.5 and change the sorting to make it 4.5, but it still seems to reserve an additional space since the rest of the chapters are all still shifted up by 1, they don't auto correct themselves like what would happen if you simply deleted chapter 4.5.

The same happens if you have a prologue chapter 0.

If you use a ComicInfo.xml the numbering will be correct, chapter 0 being numbered as 0, 4.5 as 4.5, etc, but the numbers still seem to be reserved if you add another chapter without a ComicInfo.xml file. Alternately you can remove the numbers from the file names for those off ones and enter them in manually in the web interface, but that's not ideal.

### Steps to reproduce
1. Create test manga folder
2. Create some test chapters named something like "0 - Test 0.cbz" "1 - Test 1.cbz" "1.5 - Test 1.5.cbz"
3. Change chapter 0's Number and Sort Number to 0, do the same fix Chapter 1.5.

### Expected behavior
After changing Chapter 0 to be Listed as Chapter # 0 in the web interface I would expect Chapter 1's chapter number to fix itself automatically like what would of happened if I had deleted Chapter 0.

### Actual behavior
It does not fix itself and seems to still reserve all the full chapter numbers even after changing them in the Web interface. If a 4th chapter was to be added after called "2 - Test 2.cbz" it would be given the number of 4, even though there is no listed chapter 2 or 3.

**Comment by gotson** [comment]
Your assumption on how it works is incorrect.

Changing metadata of one book doesn't change metadata of other books.

When adding a book, if it doesn't contain embedded metadata, then the index of the file in the directory is used for the number and sort number.

**Comment by BaronKrause** [comment]
> Your assumption on how it works is incorrect.
> 
> Changing metadata of one book doesn't change metadata of other books.
> 
> When adding a book, if it doesn't contain embedded metadata, then the index of the file in the directory is used for the number and sort number.

Ahh well! Thanks for the reply!
