### ISSUE TITLE
[Feature Request] Isolated Libraries

### ISSUE THREAD

**Issue by kjboa** [gotson/komga#742]
Hi, really like Komga but one minor thing I think could be improved: currently admin accounts have access to all libraries, it would be cool if there was an option for admins to hide libraries in the web ui. In my use case I have all the sources for my thesis paper on Komga and use an own account to view these. If I then continue too read my Comics as admin on the same server, the thesis paper library is still there. I know it's a very specific problem, but it would be awesome if something like this could be implemented.

**Comment by gotson** [comment]
Please use the issue templates.
