### ISSUE TITLE
[Feature Request] Limit the number of artemis and log entry

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#745]
### Is your feature request related to a problem? Please describe.
While troubleshooting my server for high RAM usage, I found a very high number of Artemis db and log files.

For the Artemis db, I'm running right now on file "activemq-data-225.amq", each being 11MB.
For the log files, I've currently 113 files of around 1MB each

### Describe the solution you'd like
Would like to be able to set either a max size or max number of versions to retain in order to limit the size and memory consumption.

Thanks for the hard work behind this soft, I really enjoy using it !

**Comment by gotson** [comment]
For log files, see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.file-rotation

For Artemis, this is not logs, but actual messages. That may be because you have a high number of pending tasks.

**Comment by Flyingfufu** [comment]
Hi Gotson,

Thanks for your prompt feedback. I tried to configure something for the logs. Will see how it evolves... 

For the Artemis file I'm not sure I got it right. The -amq files a message journal files. They seem to be kept (few every day) forever. My oldest file is from when I've transferred the server and restarted the new one, 6 weeks ago! I don't see the link with the number of pending tasks (always around 150-200)... I still unsure if 230 file of 11MB each is linked to a normal behavior...

Any feedback here would be appreciated as it takes quite some space.

Thanks again !

**Comment by gotson** [comment]
For artemis you are right, they are data journal files, meaning they contain the messages. What can happen I suppose is that for some reason some messages are never cleaned up, for instance if the task format changed.

It's difficult to assess everyone's situation, because I have no idea what happened or may have happened with your komga. 

A safe assumption is that you can delete the complete artemis folder while komga is stopped. Best is to make sure you have no running tasks before doing so.

**Comment by gotson** [comment]
Note that for log files by default it rolls everyday and will keep 10 files max. There's no cap per file at the moment.

I just saw that there is a new option to cap the total size used, that could be a good thing to add as a default.

What did you put for the logging config?

**Comment by gotson** [comment]
Default logging config is here https://github.com/gotson/komga/blob/de78483e3d0407d30e92837bef1d38d4b482b074/komga/src/main/resources/application.yml#L3

**Comment by gotson** [comment]
I will update the default logging config to limit file size and total size.

**Comment by Flyingfufu** [comment]
Thanks a lot !
