### ISSUE TITLE
[Feature Request] hide volumes number option

### ISSUE THREAD

**Issue by Suwmlee** [gotson/komga#746]
### Is your feature request related to a problem? Please describe.
currently, Komga will always show volumes number, like 1  2  3  4 ....  If there is already a volume number inside the file name, like 01-04, it will look confusing

![vols](https://user-images.githubusercontent.com/4210529/146047427-12407af2-ffec-44ad-a106-95da69962bd8.png)

### Describe the solution you'd like
add an option that wont show Komga's volume number

### Describe alternatives you've considered or other apps that can do what you want
N/A

### Additional context
N/A

**Comment by jonaballen** [comment]
+1
This is essentially the same request as what I previously posted: https://github.com/gotson/komga/issues/686

**Comment by gotson** [comment]
As a workaround you can set the book title to an invisible character, and set the number properly (it's a string and accepts things like `1-4`).

It would also have more meaning that the current numbers.

**Comment by zerodayz1** [comment]
+1 for this too.

**Comment by Suwmlee** [comment]
@gotson  thanks for your reply

the orignal name not only contains vol number,  such as `11-15 2th fighting`

https://github.com/gotson/komga/blob/master/komga-webui/src/types/items.ts#L65
```
  title (): string {
    const m = this.item.metadata
    return `${m.number} - ${m.title}`
  }
```

I found out how Komga displays titles, forcing numbers to be added before the title. This is a good way to do it and makes sense. But it would be more compatible and user-friendly if a hidden option was added. 
we can add an attribute  in the `item`  or other place to make a distinction when it is displayed

**Comment by svew** [comment]
There could be an opportunity here to pair this with bulk renaming and custom name formatting. Looking at my scenario, I have about ~200 old batman comics, where a comic was released each month, but a few months in sequence may be part of the same storyline. Currently, my books names are shown something line this:

```
1 - Legends_of_the_Dark_Knight_001
2 - Legends_of_the_Dark_Knight_002
3 - Legends_of_the_Dark_Knight_003
4 - Legends_of_the_Dark_Knight_004
5 - Legends_of_the_Dark_Knight_005
6 - Legends_of_the_Dark_Knight_006
7 - Legends_of_the_Dark_Knight_007
...
214 - Legends_of_the_Dark_Knight_214
```

The goal would be to get the titles renamed something like:
```
Shaman Issue 1 - Legends of the Dark Knight 001
Shaman Issue 2 - Legends of the Dark Knight 002
Shaman Issue 3 - Legends of the Dark Knight 003
Shaman Issue 4 - Legends of the Dark Knight 004
Shaman Issue 5 - Legends of the Dark Knight 005
Gothic Issue 1 - Legends of the Dark Knight 006
Gothic Issue 2 - Legends of the Dark Knight 007
...
Dark Knight vs. Deadshot - Legends of the Dark Knight 214
```

So I'd propose adding a "Title formatting" field to the series editing panel, which allows one to specify how they want to show the titles in the series. By default, the series would have formatting similar to the above:

```
{Book#} - {BookTitle}
```

where `{Book#}` would be replaced with the "Number" field of the book, and `{BookTitle}` would be replaced with the "Title" field of the book. This allows future extensibility if we wanted to add additional features to name books based on release date, author, etc. Extra formatting options could also be added in the future for tags, such as `{Book00#}` to left-pad the book number with 0s (just an example, not suggesting it now). So in my case, I'd set my series' title formatting to:

```
{BookTitle} - Legends of the Dark Knight {Book#}
```

And from there I could bulk edit books to have the appropriate names for their runs. Those who don't want any numbering could change their series title formatting to:

```
{BookTitle}
```

A little informational bubble could be put on the side of the field editor to list the different formatting tags. It also allows for doing bulk renames of books that don't use the books' mangled titles, so one could change how the books titles are shown (without changing their actual title fields) just by editing a single field:

```
Legends of the Dark Knight {Book#}
```

**Comment by jonaballen** [comment]
> There could be an opportunity here to pair this with bulk renaming and custom name formatting. Looking at my scenario, I have about ~200 old batman comics, where a comic was released each month, but a few months in sequence may be part of the same storyline. Currently, my books names are shown something line this:
> 
> ```
> 1 - Legends_of_the_Dark_Knight_001
> 2 - Legends_of_the_Dark_Knight_002
> 3 - Legends_of_the_Dark_Knight_003
> 4 - Legends_of_the_Dark_Knight_004
> 5 - Legends_of_the_Dark_Knight_005
> 6 - Legends_of_the_Dark_Knight_006
> 7 - Legends_of_the_Dark_Knight_007
> ...
> 214 - Legends_of_the_Dark_Knight_214
> ```
> 
> The goal would be to get the titles renamed something like:
> 
> ```
> Shaman Issue 1 - Legends of the Dark Knight 001
> Shaman Issue 2 - Legends of the Dark Knight 002
> Shaman Issue 3 - Legends of the Dark Knight 003
> Shaman Issue 4 - Legends of the Dark Knight 004
> Shaman Issue 5 - Legends of the Dark Knight 005
> Gothic Issue 1 - Legends of the Dark Knight 006
> Gothic Issue 2 - Legends of the Dark Knight 007
> ...
> Dark Knight vs. Deadshot - Legends of the Dark Knight 214
> ```
> 
> So I'd propose adding a "Title formatting" field to the series editing panel, which allows one to specify how they want to show the titles in the series. By default, the series would have formatting similar to the above:
> 
> ```
> {Book#} - {BookTitle}
> ```
> 
> where `{Book#}` would be replaced with the "Number" field of the book, and `{BookTitle}` would be replaced with the "Title" field of the book. This allows future extensibility if we wanted to add additional features to name books based on release date, author, etc. Extra formatting options could also be added in the future for tags, such as `{Book00#}` to left-pad the book number with 0s (just an example, not suggesting it now). So in my case, I'd set my series' title formatting to:
> 
> ```
> {BookTitle} - Legends of the Dark Knight {Book#}
> ```
> 
> And from there I could bulk edit books to have the appropriate names for their runs. Those who don't want any numbering could change their series title formatting to:
> 
> ```
> {BookTitle}
> ```
> 
> A little informational bubble could be put on the side of the field editor to list the different formatting tags. It also allows for doing bulk renames of books that don't use the books' mangled titles, so one could change how the books titles are shown (without changing their actual title fields) just by editing a single field:
> 
> ```
> Legends of the Dark Knight {Book#}
> ```

This looks like a different feature altogether (albeit related to naming), maybe better to report as a separate Feature request?

**Comment by svew** [comment]
> This looks like a different feature altogether (albeit related to naming), maybe better to report as a separate Feature request?

This is probably true, I was a bit worried it'd be marked as duplicate. I'll create a new ticket for it though
