### ISSUE TITLE
[Feature Request] Sort by Random

### ISSUE THREAD

**Issue by slippy45** [gotson/komga#747]
### Is your feature request related to a problem? Please describe.
Current sorting options are only helpful if you are looking for a specific book or serialization. Libraries with many one-shot or short serializations are hard to pick from for indecisive users.

### Describe the solution you'd like
I would like a Random option under Sort when browsing libraries to see a list of random books/serializations on each page.

### Describe alternatives you've considered or other apps that can do what you want
N/A

### Additional context
The Komga plugin for Tachiyomi could also benefit from this sorting option.

**Comment by shrublet** [comment]
Not totally dissimilar to #514. Mostly mentioning it since I think that implementation would probably be cleaner/more straightforward. Or just a random button could also work. Either way, would also be interested in this feature in some fashion or another.
