### ISSUE TITLE
[Feature Request] Tachiyomi Extension should pre-load next page.

### ISSUE THREAD

**Issue by varoOP** [gotson/komga#752]
### Is your feature request related to a problem? Please describe.
I use the Tachiyomi reader in the Continuous Vertical mode. With other sources, it seems to load the next page of the manga while I am still reading the current page. However, with Komga it doesn't load the next page till I scroll down to it which creates a minor lag and wait period for next page to be available.

### Describe the solution you'd like
It would be great if Tachiyomi could just pre-load a couple of pages or all pages from that manga when I start reading it. It seems to do this in the Continous vertial mode when used with other sources.

**Comment by gotson** [comment]
The extensions have no control on what happens in the reader or what is pre-loaded.
