### ISSUE TITLE
[Feature Request] Screenshots

### ISSUE THREAD

**Issue by Daedren** [gotson/komga#753]
### Is your feature request related to a problem? Please describe.
I'd like to share screenshots of small portions of my comics' pages.

### Describe the solution you'd like
Perhaps a "Screenshot" button in the reader UI that would show a rectangular selection that the user could drag, and upon completion, would create an image that the user could download/copy to clipboard

### Describe alternatives you've considered or other apps that can do what you want
- Chunky on iOS has what I mentioned in the solution as implemented behavior.
- Tachiyomi on Android allows you to share/download a full page, though not a region of it.
- CDisplayEX on Windows allows you to copy a page to clipboard or save to disk (also no region selection)
- ShareX on Windows is a general screenshotting application with full region selection.

### Additional context
Why not just use ShareX or similar? 
One big benefit of Komga's integration would be to have proper filenames with something akin to "series-book-page.jpg", which would help with organization.

Another potential benefit would be that Komga could potentially create a screenshot at the image's native resolution, even if the user has the reader on fit-to-screen (Though I imagine the implementation difficulty would go up quite a few notches due to double-spreads and whatnot)

**Comment by gotson** [comment]
That's more of a OS concern. Most android phones have such feature, and Mac os also has an integrated screenshot tool.
