### ISSUE TITLE
[Feature Request] Book Read Date

### ISSUE THREAD

**Issue by suppo77** [gotson/komga#757]
### Is your feature request related to a problem? Please describe.
Since Komga already keeps track of the read date of a single book, it would be really useful if this information were also shown in the web interface at book level.

### Describe the solution you'd like
in the book display page it would be sufficient to add the date either after the release date (adding an explanatory label) or at the bottom as a new line together with other information such as SIZE, FORMAT, etc.).

It would also be very useful to have the possibility to change the date recorded automatically.

**Comment by gotson** [comment]
> it would be really useful if this information were also shown in the web interface at book level

What would that bring to you? Are there any similar tools that would do the same thing ? For instance Plex doesn't do it.

> It would also be very useful to have the possibility to change the date recorded automatically.

How would you use this, and why would you need it?

**Comment by suppo77** [comment]
> What would that bring to you? Are there any similar tools that would do the same thing ? For instance Plex doesn't do it.

it is true that plex does not have this function and in fact there are external platforms to manage properly this aspect. I think the most common is Trakt.tv (maybe there is also a plugin to integrate plex with Trakt.tv). Personally, I find it very useful to know when I last read a comic, even if it was only to understand the type of mood I had in a given period. Moreover, it is an info that is already traced and thus it's "just" a matter to visualize it.

> How would you use this, and why would you need it?

I am attaching some screenshots of the Trakt app showing how they handle this information.
<img width="166" alt="PNG image" src="https://user-images.githubusercontent.com/26971586/147817906-f5e7ed84-92c8-46bf-ba33-ca827ba977f8.PNG"><img width="166" alt="PNG image" src="https://user-images.githubusercontent.com/26971586/147817909-2f5b1e72-5d0b-41d8-99fa-5e16dc9f7f8d.png"><img width="166" alt="PNG image" src="https://user-images.githubusercontent.com/26971586/147817910-9bab16ed-e923-4f9a-a82f-e6956503f294.PNG">

The idea of being able to change the reading date is due to the fact that old comic archives that have already been read are often imported to Komga, so many (myself included) keep track of the reading status on excel files or other systems.
