### ISSUE TITLE
[Export Metadata] allow to export metadata

### ISSUE THREAD

**Issue by Webcr0ler** [gotson/komga#763]
### Is your feature request related to a problem? Please describe.
not a problem

### Describe the solution you'd like
permit to download a json or Xml with metadata from CBZ/CBR or from series.

### Describe alternatives you've considered or other apps that can do what you want
i only use komga, don't know others
### Additional context
none

**Comment by gotson** [comment]
> permit to download a json

this is already available via the API

---

Duplicate of #82
