### ISSUE TITLE
[Feature request] Option to delete duplicate comic/book(s) from webinterface

### ISSUE THREAD

**Issue by SlorkMan** [gotson/komga#764]
### Is your feature request related to a problem? Please describe.
I think it would be helpful if there as an option to delete one or more duplicates in the "duplicate files" section

### Describe the solution you'd like
A "delete" button could be placed on the row of the duplicate file(s) (or an icon of a big red "X")

### Describe alternatives you've considered or other apps that can do what you want
Alternative would be to delete the file in the explorer / bashprompt (not userfriendly)
![Screenshot ](https://user-images.githubusercontent.com/51154834/148056691-23cb5436-f5c0-4980-a468-48bb5aa1989c.png)

**Comment by gotson** [comment]
That's indeed a good idea, now that we have book deletion that makes sense.

**Comment by SlorkMan** [comment]
nice! thanks!
