### ISSUE TITLE
Updating form 0.139 to 0.142 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by war3zlod3r** [gotson/komga#766]
### Komga environment
- **OS**: Ubuntu Linux 21.10
- **Komga version**:
- [X] **I am running Komga with Docker**
  - Docker image tag [e.g. latest,]:Latest

### Describe the bug
Unable to start the application since updating

### Steps to reproduce
docker start komga

### Log file
https://pastebin.com/UAAyRMm8

I believe the problem is the JVM in the docker is only using  1GB and running out of memory but not sure how to fix/address it

**Comment by gotson** [comment]
What host do you run it on, how much ram does the host have?
