### ISSUE TITLE
[Feature Request] lossless covers 

### ISSUE THREAD

**Issue by edgehub-cloud** [gotson/komga#768]
### Is your feature request related to a problem? 
Covers compressed way too much 
A clear and concise description of what the problem is. Ex. I'm always frustrated when I am viewing manga and the there are compression artifacts called blocking. 

### Describe the solution you'd like
Cover.png/jpeg local art work exist I know. But it would be much better if komga does it
### Describe alternatives you've considered or other apps that can do what you want
Ran a script to extract covers from file. Didn't worked much after editing the library to use local art

### Additional context

Idk something went wrong last template didn't loaded nor I saw any option for using last time. Sorry

**Comment by gotson** [comment]
Maybe provide some sample images to illustrate what you think is wrong with the current covers, or provide numbers like dimensions or compression levels.

**Comment by edgehub-cloud** [comment]
https://slow.pics/c/pSZcer2p
![Uploading IMG_20220108_051200.jpg…]()

**Comment by gotson** [comment]
You may need to provide a bit more information, this doesn't help me at all.

**Comment by edgehub-cloud** [comment]
would u kindly tell me what kind of information are u specifying too,
all i can see as of now is the covers are way too compressed.  blocking is severally visible.

**Comment by gotson** [comment]
Your message above doesn't explain which cover is which, what format the cover used before, the dimensions or anything...

You realize that having covers of 2.5 mb is not sustainable to display on a page with 20 or 50 covers, right?

**Comment by edgehub-cloud** [comment]
https://slow.pics/c/pSZcer2p
The comparison is of uncompressed vs compressed.
Would it be possible to increase resolution / bitrate for the cover?
