### ISSUE TITLE
[Feature Request] Reading List - Detailed List View

### ISSUE THREAD

**Issue by jakem742** [gotson/komga#769]
Just want to start off my saying, Komga is incredible and I'm a big fan of where you guys are going with this!

### Is your feature request related to a problem? Please describe.
It is quite difficult to manage reading lists in the default cover-based 2D layout. 

### Describe the solution you'd like
A 1D list which has columns for all the issue details (Title, Number, Series, Publish Date etc) of all issues in the current reading list  would be fantastic. This would also provide a fast way to sort (by simply selecting a column header), and could be a useful view for series as well? It's much easier to re-order issues in a reading list when the list is 1D as it's a simple up & down slide action. The ability to multi-select issues and drag them up/down would make this even better!

**Comment by jakem742** [comment]
I have just noticed this is quite similar to #743, so my apologies for the overlap. The export feature and table mode + multiselect issues would be fantastic to have though.

**Comment by gotson** [comment]
Please open another issue for export, to keep things clean and separate.

**Comment by gotson** [comment]
Also similar to #637

**Comment by jakem742** [comment]
Created a separate issue under #770.
