### ISSUE TITLE
Wrong color on book thumbnail

### ISSUE THREAD

**Issue by MEGAMENE** [gotson/komga#77]
I've noticed that some of my manga appear in a different color instead of just black and white on the book page thumbnails.
Here's an example:
![originalPage](https://user-images.githubusercontent.com/7219991/72576062-796ba800-38c6-11ea-9fce-87049cf15b2d.png)
![thumbnail](https://user-images.githubusercontent.com/7219991/72576073-812b4c80-38c6-11ea-9246-9c7bafdc4af2.png)

**Comment by gotson** [comment]
Thanks. I did a quick test and i can confirm it's not coming from the `imageio` conversion, but from the thumbnail library in particular.

Their github repo is apparently full of issues with `png` images. I'll look for another library to replace it.

**Comment by MEGAMENE** [comment]
The new update seems to have broken some thumbnails, both in the book view and page preview.
Here's an example:
https://files.catbox.moe/mqrlj1.cbz

**Comment by gotson** [comment]
What do you mean by "broken" ?

For the book thumbnails show in the gallery, you need to regenerate them, either via the admin endpoint (available via swagger), or by analyzing the books again (from the 3 dots menu).

For all thumbnails, you also need to clear your browser cache.

**Comment by gotson** [comment]
It seems the first image of your file as alpha channels, hence the problem.

**Comment by MEGAMENE** [comment]
> What do you mean by "broken" ?
> 
> For the book thumbnails show in the gallery, you need to regenerate them, either via the admin endpoint (available via swagger), or by analyzing the books again (from the 3 dots menu).
> 
> For all thumbnails, you also need to clear your browser cache.

I analyzed all of the files after the update and some don't generate the thumbnails.

**Comment by gotson** [comment]
Both libraries have issues: the original one handles transparency channels, but generates color artefacts, the new one cannot handle alpha.

I would prefer incorrect colors to nothing, so i'll switch back to the original library.

**Comment by MEGAMENE** [comment]
> Both libraries have issues: the original one handles transparency channels, but generates color artefacts, the new one cannot handle alpha.
> 
> I would prefer incorrect colors to nothing, so i'll switch back to the original library.

Yeah, that's probably the best option of the two.
Maybe later there's another way to fix this problem, I don't know enough about java or images to be of any help.

**Comment by gotson** [comment]
From what i've gathered, generating good looking thumbnails is complex enough that people wrote libraries to do it :) I have no plans on writing my own code for that!

**Comment by MEGAMENE** [comment]
> From what i've gathered, generating good looking thumbnails is complex enough that people wrote libraries to do it :) I have no plans on writing my own code for that!

Yeah, that makes sense.
Maybe an option would be to convert png to jpeg and then create the thumbnail?
That should remove the transparency problem, no?

**Comment by gotson** [comment]
Nothing is as simple in the world of imaging, unfortunately.
