### ISSUE TITLE
[Feature Request] Readable Local Backups of Reading Lists

### ISSUE THREAD

**Issue by jakem742** [gotson/komga#770]
### Is your feature request related to a problem? Please describe.
There is currently no easy way to export reading lists from Komga. 

### Describe the solution you'd like
It would also be nice to be able to keep a local copy of reading lists in a readable (ie. text-based) file. I know Komga can import CBL's, so might make sense to use this format? I was initially thinking of an export button, but it would honestly just be nice to have a constantly updated file for each reading list which syncs with any changes to the db.

**Comment by gotson** [comment]
> There is currently no easy way to export reading lists from Komga.

There is, all the data is available via the rest api, you could use this to export into whatever file format makes sense for you.
