### ISSUE TITLE
[Feature Request] Add publisher as filter criterium to cbl

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#775]
### Is your feature request related to a problem? Please describe.
In international comics it could be that a series has the same name, year and volume but different publisher.
At the moment the CBL criterias are:
-     name of the series it is part of
-     volume of the series
-     year of the series
-     number of that book in the series

with this criteria it is not unique to find the right boo. It creates errors when you import a cbl because there are multiple matches.
Field publisher is already defined in cbl format. To use it also in komga should not be a problem to include this tag in komga also. 

### Describe the solution you'd like
In best case publisher is an optional field to find better matches during cbl analyzis when you imports cbl files in komga.
First step is to use the standard filter, when you have more than one match, komga can filter with publisher to get a golden record. 

### Describe alternatives you've considered or other apps that can do what you want
Komga can also create a unique field for every data file to store an external ID.
Than we can use this ID instead of the publisher.

**Comment by gotson** [comment]
CBL is a fixed format from ComicRack. Even if we made amendments, it wouldn't help much, only people like you crafting those files manually.

There are much better course of actions than this, which I don't want to spend anytime on.

**Comment by MKH-42** [comment]
Hello :-)

You are right, I missinterpreted a small but important thing.
In https://comictagger.forumotion.com/t27-illegal-metadata-for-cbl-tag-format-0-9-4-on-linux-windows-problem-found it looks like the definition of CBL is:
{  u'ComicBookInfo/1.0': {  u'credits': [],
                              u'genre': u'Super-Hero: Vigilantes/Ant-Heroes',
                              u'issue': u'2',
                              u'numberOfIssues': u'100',
                              u'publisher': u'Image Comics',
                              u'series': u'SPAWN',
                              u'tags': [],
                              u'volume': u'1'},
    u'appID': u'ComicTagger/0.1',
    u'lastModified': u'2013-01-16 04:33:51.873540'}73540'}

So I thought, publisher is part of cbl.
But this was a fault.

Thank you for the hint, CBL don't include publisher.
