### ISSUE TITLE
[Bug] OPDS server drops Publisher from self, previous and next links.

### ISSUE THREAD

**Issue by Nymarra** [gotson/komga#777]
### Komga environment
- **OS**:MacOS
- **Komga version**:
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]:
- [x] **I am running Komga from the `jar`**
  - Java version: openJDK 17.01
- [ ] **I have a problem in the web interface**
  - Browser (with version):
- [x] **I have a problem with an OPDS client application**
  - OPDS Application (with version): all
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version:
  - Tachiyomi extension version:

### Describe the bug
The OPDS server serves incorrect `next` and `previous` and `self` links when viewing series by publisher.
### Steps to reproduce
1. Using a browser, curl, or some other method of sending and viewing requests and responses send a `GET` to `<server address>/v1.2/series?publisher=<publisher>`
2. Observe `href` value for the `next` and `self` link.

### Expected behavior
The `href` value for the `next` link should equal `/opds/v1.2/series?publisher=<publisher>&page=1`, the second page for the results by the publisher.

### Actual behavior
The `href` value for the `next` link is `/opds/v1.2/series?&page=1`

`href` fields for the `self` and `previous` links are similarly stripped of the `publisher` query parameter. 

Note: the `previous` link requires being at the second page, which requires using the expected link(`/opds/v1.2/series?publisher=<publisher>&page=1` to observe.)

### Additional context
This issue was also present when I was running on docker on the `latest` image, and is agnostic of what opds reader I'm using, as you can observe the bug by looking at the raw responses from the server.

There may be other situations where links are generated improperly, but this is the only case where I observed them.

### Screenshots
N/A

### Log file
N/A

**Comment by gotson** [comment]
Introduced by #285 most likely
