### ISSUE TITLE
Web-reader: Make double page mode image-size-dependent

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#78]
I just tried the double page mode with this manga chapter: https://files.catbox.moe/kor5ue.cbz

Page Two (1027x750) is not the same size as page three (750x1103) which results in the following:

- Double-page-mode and Fit-to-original or Fit-to-width: page three shown with correct proportions, page two is distorted.

- Double-page-mode and Fit-to-height: Both are shown with correct proportions, but page two is bigger than page three and, depending on the window-size, it doesn't show both pages completely.
- If I have the full width of 1920px available, both pages are shown completely. If I make the browser window smaller or open the sidebar, both page get cut off on the outer edges.

Maybe checking if both images are the same width before displaying them together could help with this.

**Comment by gotson** [comment]
Don't use double pages with pages that are not the same size. That's asking for trouble.

**Comment by muchtea** [comment]
> 
> 
> Don't use double pages with pages that are not the same size. That's asking for trouble.

That's true, but the other pages in that chapter are all the same size.

I just found the chapter on mangadex and the reader there seems to check for this in double page mode, and this viewer https://github.com/kanryu/quickviewer also seems to do this somehow.

With that being said, I personally don't use double page mode and do think this is not that much of a problem, so this doesn't have to be fixed.
