### ISSUE TITLE
[Feature Request] Webtoon scroll to next book directly (like Tachiyomi)

### ISSUE THREAD

**Issue by zPilax** [gotson/komga#780]
### Is your feature request related to a problem? Please describe.
Sometimes the "double click on phone to go to the next page does not work"

PS.
This is on webtoon mode

PSS.
I am reading mostly on my phone.

### Describe the solution you'd like
I would like to be able to scroll to the next page without clicking anything

### Describe alternatives you've considered or other apps that can do what you want
It can also be a vertical transition wherein we can double click the last page to go to the next page

### Additional context
Got this idea from Tachiyomi on android

**Comment by gotson** [comment]
I don't understand what you are saying at all.

You mention you are on a phone, but you keep using the work _clicking_, that doesn't mean anything on a phone.



> I would like to be able to scroll to the next page without clicking anything

So with magic or mind reading ?

**Comment by zPilax** [comment]
https://user-images.githubusercontent.com/98472751/151345193-2fc2a95b-6e88-48f1-838a-d14a81e091d6.mp4

something like this?

**Comment by gotson** [comment]
So you want to scroll directly to the next book ? Just tap twice once you reach the end and it will go to the next book.
