### ISSUE TITLE
[Feature Request] Full Page "Recently Added Books"

### ISSUE THREAD

**Issue by claym** [gotson/komga#781]
### Is your feature request related to a problem? Please describe.
Not a problem

### Describe the solution you'd like
Currently, the "Recently Added Books" is just a panel on the Komga Dashboard. It can't be sorted, filtered, or anything else. It would be really great if we could get a full page view similar to the browse page which had the same content (maybe last 50 or 100 books) of individual books (not series) that could be manipulated, and selected to add to Read Lists.

**Comment by gotson** [comment]
> that could be manipulated

What do you mean by "manipulated" ?

> selected to add to Read Lists

This is possible from the dashboard horizontal scroller already

**Comment by claym** [comment]
Manipulate - I mean filtering, sorting, etc.

Yes, they can be added from the horizontal scroller, however you don't have the ability to sort/filter, which makes it harder to find things. Additionally, there the series name is not listed in that horizontal scroller which makes it even harder to find things.
