### ISSUE TITLE
[Bug] PDF documents not being closed correctly

### ISSUE THREAD

**Issue by svew** [gotson/komga#783]
My log files are full of this warning after ever PDF analyze task:

```
2022-01-27 13:00:23.493  WARN 1 --- [Finalizer] org.apache.pdfbox.cos.COSDocument        : Warning: You did not close a PDF Document
```

My guess is that the PDF isn't being closed after the task is complete, similar to this:
https://stackoverflow.com/questions/37410429/you-did-not-close-a-pdf-document-when-signing-in-apache-pdfbox-2-0

**Comment by gotson** [comment]
Please use the issue templates
