### ISSUE TITLE
More information in page title

### ISSUE THREAD

**Issue by SaraSmiseth** [gotson/komga#79]
The page title is always just "Komga". It should change depending on which part of the site im at. This makes it easier to navigate if I have multiple tabs open at the same time.

For example when I read a manga it could be "Komga - Naruto - Chapter 1".
When I'm at a library it should include the library name: "Komga - MyNiceLibrary".
After selecting a manga "Komga - Naruto" etc..

**Comment by gotson** [comment]
Thanks for pointing this out, I didn't thought about that! I had a quick look, should be essy enough to add.

**Comment by gotson** [comment]
Closed by #92
