### ISSUE TITLE
OPDS Server does not properly encode HTML Encode publisher names in next or previous hrefs.

### ISSUE THREAD

**Issue by Nymarra** [gotson/komga#792]
### Steps to reproduce

1. Using a browser, curl, or some other method of sending and viewing requests and responses send a `GET` to <server address>/v1.2/series?publisher=<publisher> where the publisher name includes a space and/or a special character (such as Boom! Comics) where you have more than 20 series for the publisher.
1. Observe `href` value for the `next` and self link.

### Expected behavior

Spaces and special characters will be properly URL encoded, with spaces being converted to `%20` and exclamation points converted to `%21`

### Actual behavior

The href provided does not properly encode the name of the publisher, leaving spaces and special characters as is. This results in requests for the next page to fail and serve the `/catalog` endpoint instead.

### Logs

No logs, but attached is a screenshot of the OPDS server output.

![Screen Shot 2022-02-02 at 6 45 46 PM](https://user-images.githubusercontent.com/98235487/152273046-50f3101b-9174-434b-81cc-4fe5fd748ea2.png)

### Komga version

1.48.2

### Operating system

MacOS

### Other details

It is important to note that while navigating to the non-encoded urls will still work in a browser, that is only because a browser will handle the conversion for you automatically, when making a request via a tool like curl (or an opds reader) requests to the non-encoded href values will fail.

It is also worth noting that the `self` href value does encode these properly for the most part, so this is likely a flaw in the fix implemented for [777](https://github.com/gotson/komga/issues/777). 

That being said, while it doesn't appear to be a breaking issue with my OPDS reader, the `self` href value does not appear to encode special characters, such as `!` (see the log screen shot) which may cause compatibility issues for others.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> exclamation points converted to `%21`

This is actually not required for query params.

**Comment by Nymarra** [comment]
Yeah I realized the exclamation points should stay as is after I wrote this and didn't get a chance to update. The spaces not being converted to`%20` are the issue breaking the links.

**Comment by gotson** [comment]
> Yeah I realized the exclamation points should stay as is after I wrote this and didn't get a chance to update. The spaces not being converted to`%20` is the issue breaking the links.

yes i fixed it, it's shipping today
