### ISSUE TITLE
One-Shots Management

### ISSUE THREAD

**Issue by sonostrass** [gotson/komga#793]
### Describe your suggested feature

Keeping One-shots together seems hard considering the folders oriented management in Komga.
I organized my folders by letter, then by serie name, and I keep a special folder for all One-Shot:
Comic\A\_One-Shot A

But each time I add a new book, the full folder is parsed as if they were all part of a serie. With a large number of one-shots, each scan takes a lot of time, not related to the number of book added or updated..

I'd like to have a special comic management process for one-shot: **for example a keyword in folder** so that its content is not managed with book numbers but as independant books. When scanning, if the folder has recent modification dates, comparison is made book by book to update only what's necessary.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Keeping One-shots together seems hard considering the folders oriented management in Komga.

Only because of your existing folder hierarchy, which is suited for folder browsing only.

> I organized my folders by letter, then by serie name, and I keep a special folder for all One-Shot: Comic\A_One-Shot A

The recommended way for One Shots is to place them in their own folder. You can use sub-folders within your one shot folder if you want.

> But each time I add a new book, the full folder is parsed as if they were all part of a serie.

No sure what you mean by that. I suppose you refer to the refreshing of Series metadata, that reloads the `ComicInfo.xml` in each book.

Given you don't need metadata at series level, since the series is just a placeholder, and not a real series for you, you could place the one shot folders in a specific library, and disable Series metadata import.

**Comment by sonostrass** [comment]
Yes, I probably have to change my way of storing One-Shots.
I'm gonna try something else, then.

Thank you for spending time considering my (irrelevant) request !
(but looking forward for something around #178 ticket ^^)

**Comment by gotson** [comment]
It's not irrelevant, just not the focus for now. There's #221 but that's a very long shot, and could be useful for one shots since ebooks don't have a series.

**Comment by sonostrass** [comment]
I personally separate comics (I convert everything as cbz) and ebooks (I convert everything in epub).
By the way, eBooks can be part of a serie of books. I probably don't get what you meant, or we don't talk about the same thing.

Have a nice day.

**Comment by gotson** [comment]
> By the way, eBooks can be part of a serie of books

Yes, but it's the exception more than the norm, which is the inverse for comics.

**Comment by sonostrass** [comment]
> Yes, but it's the exception more than the norm, which is the inverse for comics.

It make sense, I agree.

However, I reorganized my folders so that one-shots are now in independent folders. I also removed the serie metadata extraction for these libraries. It now almost looks good. And I would have an extra-question:
when choosing to ignore serie metadata, could we ignore the komga Serie screen layer too?
For series, it make sense to Browse --> Serie (with books list) --> Book 
For one-shot, Serie layer just repeat book metadata, so it would make sense to jump from Browse --> Book directly

That is another way to work around my request: if serie metadata is disable from library, user doesn't go through Serie screen.

**Comment by gotson** [comment]
> I also removed the serie metadata extraction for these libraries.

You don't need to, if you put them in separate folders.

> when choosing to ignore serie metadata, could we ignore the komga Serie screen layer too?

Those are 2 completely unrelated things, so no. Series metadata import and the fact that the series is a one shot is different.

---

Concerning skipping the series view, it's not possible at the moment, nor planned.

**Comment by sonostrass** [comment]
> Concerning skipping the series view, it's not possible at the moment, nor planned.

Ok. Now I think I asked everything I needed and have a clear view of what-is and what-could.
Thanks again for your concern. ^^
