### ISSUE TITLE
Data import tuning & new views

### ISSUE THREAD

**Issue by aussiehuddo** [gotson/komga#794]
### Describe your suggested feature

I suggest adding a way to tune what is imported from book data. I use ComicRack with comicvine plugin to fetch the data and write it into the cbz files, which is then imported into Komga. However, issues arise with the titles of comics, especially collected or TPB editions which don't often don't include the vol number or just say "TPB". Would like a way to import all other details except for the title and just use the filename as the title.

Also extra views would be good, instead of just posters, List view with a small image of the cover on the left and then the title on the right would be good for comics with long names.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
A better way is to fix your metadata.
