### ISSUE TITLE
Unclear OS compatibility information, no CUI/GUI on Fat Jar execution

### ISSUE THREAD

**Issue by The7thSage** [gotson/komga#8]
I first want to thank you for what you are attempting/executing.I have followed other's work on the creation of comic servers namely Tachiyomi-Server (only a client, actually), ubooqity, HappyPanda-X (Most Detailed Metadata+Search), ComicRack. It is awesome to see someone finally adding this func. to Tachiyomi

Even though I kind of settled with Happypanda-X/ComicRack lately, I would like to take this application for a spin, I run Windows 10 Home on the PC that holds my comics. Docker, unfortunately is only Windows 10 Pro. Using the jar, does absolutely nothing, as far as I can tell.

I can also run Ubuntu live on my laptop, and am currently wrangling with wrapping my head getting the container to be created and starting the application.

So I guess my request would be for clearer documentation so that I can know what the application looks like when its running. This might just me being ingorant/dumb, if so my apologies.

**Comment by gotson** [comment]
Hello,

Indeed the documentation for running the fat jar is scarce at the moment.

In the meantime, could you please provide some details on how you are running the jar on windows 10, along with your version of Java?

**Comment by gotson** [comment]
If you could also post the full logs when running Komga to gist I could have a look and try to see what's wrong/missing.

**Comment by The7thSage** [comment]
When running the fat jar I placed the sample application.yml in the directory, then edited it to my liking. Then I attempted two ways to run the application: One was right click context menu: "open with">Java Platform SE Binary. Using this method allows me to execute other .jars from file explorer, but you can't really tell if you actually ran it. Second, I used command line "D:\Tools\Manga\01Server\Komga\komga-0.3.4.jar to execute and it showed it ran with a blank line, but nothing happened. 

Here is my Java version: Java version 8 update 221 (build 1.8.0_221-b11) 
I will work on getting logs, but java wants to be difficult, and isn't allowing me to configure it through the shortcut. Also I sanity checked myself with a Jar I knew worked (ubooquity), only command-line method worked this time? I may try reinstalling java then replying back 2 U if I can configure and run with context menu.

**Comment by The7thSage** [comment]
After Reinstall, I can now configure, but not-click context. also java game me this in command line when executing Komga specifically. 
"Java Version 8 Update 221 (build 1.8.0_221-b11)
Error: Could not find or load main class version"
So I guess that's the log, there was nothing dumped into %appdata%/Sun/Java/Deployment where the internet tells me I should get a log.b At least it's something.

**Comment by gotson** [comment]
Hi, could you try opening a command prompt and from the directory containing the jar, try the following :

```
java -jar komga-0.3.4.jar
```

**Comment by The7thSage** [comment]
Thank you so much, that did the trick, it now boots. (I can log the rest of the goings-on as I think the edits to the yml seemed rather "hacky" compared to what the usage guide says.
1 I just deleted Root-folder, I guess it defaults to Komga folder
2 I changed server url into jdbc:h2:~/config/database.h2;DB_CLOSE_DELAY=-1 Since the Application told me I needed either . or ~ in the url. 

Thank you so much for the help. The only other unclear part I found was regarding paths, when dropping into a folder came out like "\D:\" in example is like "\" and Normal windows is "D:\" None of these work. 
👍 👍

**Comment by The7thSage** [comment]
(also no Idea where database file went, and I have java.jar in directory, IDK *Shrugs*

**Comment by gotson** [comment]
I am on holidays right now, next week I'll add a sample `application.yml` specific to Windows, indeed the paths are using backslash and should be escaped in yaml files, not so intuitive.

For the root folder it's mandatory, there's no defaulting. 
You can try with a path like that : `root-folder: D:\\files\\pdf`

**Comment by The7thSage** [comment]
Ok I'll close the issu then, thats all, enjoy your holiday, I'd rather not intrude. Great work, one last time.

**Comment by gotson** [comment]
I'll keep it open, the doc definitely needs brushing up, and having someone in need for it makes it even more important to do it! Shouldn't be too much of a hassle, and once ready you can give me your feedback too!

**Comment by The7thSage** [comment]
AOK then. 👍

**Comment by gotson** [comment]
@The7thSage i have updated the README and added some sample configuration files for Windows. If you have time i would appreciate your feedback !

**Comment by The7thSage** [comment]
I just got some time to check it out yesterday, I think you are solid. The only think I could possibly see is changing the D:\ Drive to the C drive for those less tech-savvy. However, I would imagine knowlege of drive letters comes hand-in-hand with knowledge of command prompt.
I switched to the proper format, and the database shows right up, both relative and absolute paths.
(I'll leave the previous database in whatever limbo ~/ leads to I have plenty of space.)

**Comment by gotson** [comment]
I'm working on v0.5.0 right now, which will manage multiple libraries. There won't be any configuration necessary, and there will be a web UI to configure the library file path. 🙂

**Comment by gotson** [comment]
> (I'll leave the previous database in whatever limbo ~/ leads to I have plenty of space.)

Normally `~` should point to your home or user directory.

**Comment by gotson** [comment]
Hi @The7thSage, I released [v0.5.0 ](https://github.com/gotson/komga/releases/tag/v0.5.0)which comes with a web interface to add/remove libraries. That should simplify the configuration required.

I'll close this issue, as i think all your concerns have been addressed. In case you still have concerns feel free to reopen the issue ! :)
