### ISSUE TITLE
Viewing logs within Komga interface

### ISSUE THREAD

**Issue by waz1500** [gotson/komga#80]
Would you be interested in adding a way to view Komga's logs/logfile directly within the dashboard and without using a terminal to view it?
This would help those trying to self-diagnose issues and help maybe others who don't know/aren't comfortable using a terminal. 

Maybe with a nice export as zip/rar option that users could use to attach to their github issue to help with the diagnosis.

**Comment by gotson** [comment]
Hello,

Logs are available at `/actuator/logfile`.

There are so many ways to retrieve and view logs, I have no interest in adding one of my own. 

Personally I retrieve all the logs of all my docker containers using telegraf which sends them to an influxdb database. I can view logs using a new grafana dashboard.
