### ISSUE TITLE
[Feature Request] Import series tags and genre tags from a locally stored file

### ISSUE THREAD

**Issue by zachstultz** [gotson/komga#802]
### Describe your suggested feature

So as it is currently, to my knowledge, the only option we currently have for locally stored series metadata to be read by Komga is a series.json file that mylar is known for generating.

But this is rather limited, as there's no support for genre tags and tag tags. 

I'd like to be able to read all related metadata that Komga can present in the web-ui for a series inside of a local file, so in the event that my database gets corrupted, I don't have to worry.

I wouldn't mind if it's in the form of adding custom support for genre tags and tags tag in the series.json file or support for an externally stored comicinfo.xml in the series folder, or something completely different all together, I don't really mind what route it is. I would just like to have all relevant series metadata to be able to be read from a locally stored file.

The amount of series metadata provided by a series.json:
![image](https://user-images.githubusercontent.com/8385256/153075806-3f27fe7e-f6bf-48de-a8de-0c9d7fecb664.png)

The amount I'd like to have from reading a locally stored file:
![image](https://user-images.githubusercontent.com/8385256/153077510-a69aa978-3a3d-467c-9000-28a73bec6d08.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Series metadata is also imported from `ComicInfo.xml` files from the books in the series, see [here](https://komga.org/guides/scan-analysis-refresh.html#series-metadata).

> The Genre field will be split by ,. All genres from all books will be added to the Series.

Series will also aggregate the tags from each book, and `Tags` element is now supported in `ComicInfo.xml`

So you could achieve exactly what you want by using `ComicInfo.xml`. You would need to tag only a single book for this to work.

---

Similar to #408 I have no plans to support unofficial formats. If ever we manage to create a [new metadata format](https://github.com/anansi-project/rfcs) for export, it would be supported.

**Comment by 08shiro80** [comment]
please up, its better as to extra add the comicinfo.xml in on chapter if they are all in one folder anyway
