### ISSUE TITLE
Series are not being collected correctly

### ISSUE THREAD

**Issue by Bandes** [gotson/komga#806]
### Steps to reproduce

I'm not positive what's causing this. My best guess is that my directory structure contains both folders organized by date, and folders for individual series, or perhaps that some of these files are `cbr` files that lack `ComicInfo.xml`?

What happens is that, for instance, I'll get two 'Series' for Action Comics, one will have all of my issues of Action Comics as I would expect, and the other will have a seemingly-random group of comics, including a single issue of Action Comics. 

### Expected behavior

A single Series entry for all comics within a given series, as identified by metadata and/or filename

I would expect that irrespective of what folder the comics are located in, they would be organized by the series defined in their metadata and/or filename.

### Actual behavior

Multiple different series entries, some of which contain a seemingly-random collection of comics, perhaps grouped by date.

### Komga version

v0.150.0-master 

### Operating system

Synology NAS via Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> I would expect that irrespective of what folder the comics are located in, they would be organized by the series defined in their metadata and/or filename.

That is not what is happening. 

In Komga, [1 series = 1 folder](https://komga.org/guides/scan-analysis-refresh.html#what-happens-during-a-scan):

> Komga will create a Series for each subfolder of any library, whatever the depth of this subfolder in your directory structure
