### ISSUE TITLE
Page Up and Page Down Support in the Webreader

### ISSUE THREAD

**Issue by loocool2** [gotson/komga#808]
### Describe your suggested feature

Page navigation would be more intuitive as these keys are used to navigate webpages and other applications as well

### Other details

As these keys are not direction specific, some concessions may need to be made code-wise

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Using those keys to move to previous/next page would prevent scrolling tall images via those keys, no?
