### ISSUE TITLE
Komga only always shows the ebooks images?  How can I read the text?

### ISSUE THREAD

**Issue by cocoonkid** [gotson/komga#813]
### Steps to reproduce

1.Open webreader
2. Click on Ebook to read
3.  Only images are shown and the number of pages is just the number of images.

### Expected behavior

1.Open webreader
2. Click on Ebook to read
3.  Text and images are shown and I can read.

### Actual behavior

1.Open webreader
2. Click on Ebook to read
3.  Only images are shown and the number of pages is just the number of images.

### NOTE

This only pertains to epub.  PDF work as they should so far.

### Komga version

v0.152.0-master 

### Operating system

Docker Image

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by cocoonkid** [comment]
In Discord I was told that the webreader cannot read epubs.  This should be made clear in the feature section.  I understand why it doesn't work but that this is working is basically assumed otherwise.

Should really be made clear.

**Comment by HeuristicPerson** [comment]
Is there any public place where more info about the matter can be seen? Being epubs basically html documents, it's a bit weird that Komga is not compatible with them.

**Comment by Kussie** [comment]
> Is there any public place where more info about the matter can be read? Being epubs basically html documents, it's a bit weird that Komga is not compatible with them.

Gotson would probably be able to answer but basically the idea is just focus on what Komga was designed for Comics rather then brooks.

**Comment by DieselTech** [comment]
> Is there any public place where more info about the matter can be read?

https://komga.org/guides/#what-media-and-devices-work

**Comment by HeuristicPerson** [comment]
I already saw that and it doesn't provide much information apart from the fact that, indeed, Komga only supports epub images.
