### ISSUE TITLE
Move more config items to webui

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#815]
### Describe your suggested feature

Move options such as cron,  scan on startup, library exclusions for scan, sesssion key, remember me validity, session timeout, delete empty collections, delete empty read lists, and threads min and max to the web ui and stored in the DB, Make command line and application.xml a priority but have the database config options apply if they exist. Adding a restart server button if needed that would read those in.

Other options such as http port, database location could probably be added but for example, database location would most likely need to MOVE the database to a new location.  Http port would likely need a serious warning.

Another thing I'd like to see is the ability to view server logs in real time or at least get some idea of what is currently happening when the server is busy. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> get some idea of what is currently happening when the server is busy.

https://komga.org/faq/#komga-seems-slow-how-can-i-check-what-s-going-on

**Comment by billsargent** [comment]
> > get some idea of what is currently happening when the server is busy.
> 
> https://komga.org/faq/#komga-seems-slow-how-can-i-check-what-s-going-on

Yes. I tail the logs from the command line or watch the output from the console.

**Comment by gotson** [comment]
> > > get some idea of what is currently happening when the server is busy.
> > 
> > 
> > https://komga.org/faq/#komga-seems-slow-how-can-i-check-what-s-going-on
> 
> Yes. I tail the logs from the command line or watch the output from the console.

It's more complicated than what I pointed out, which tells you how much tasks are still pending to be done.

Logs are usually a mean of investigation, but are not usually a good indicator of activity. They could tell too much or too little depending on their configuration.

**Comment by billsargent** [comment]
> > > > get some idea of what is currently happening when the server is busy.
> > > 
> > > 
> > > https://komga.org/faq/#komga-seems-slow-how-can-i-check-what-s-going-on
> > 
> > 
> > Yes. I tail the logs from the command line or watch the output from the console.
> 
> It's more complicated than what I pointed out, which tells you how much tasks are still pending to be done.
> 
> Logs are usually a mean of investigation, but are not usually a good indicator of activity. They could tell too much or too little depending on their configuration.

Yes I use it to make sure the little NAS i'm running this on hasn't ran out of RAM or anything... as long as I'm stilling seeing inserts or things like that, its ok. I grep the logs too for errors. I'm running this on a Screen session there. 

btw it might be better to have the logs split. sqlite insert information, for example, it its own log.

**Comment by gotson** [comment]
Errors are not necessarily relevant, as errors do occur in the course of the normal activity.

> btw it might be better to have the logs split. sqlite insert information, for example, it its own log.

It usually isn't, at least for me doing investigations for support, because information is split.

You can configure everything the way you want though, spring boot is very flexible.

**Comment by billsargent** [comment]
Moving away from the logging, what are your thoughts on having some of the config in the UI?

**Comment by gotson** [comment]
> Moving away from the logging, what are your thoughts on having some of the config in the UI?

it's something I want to do, among a lot of other things :)

**Comment by billsargent** [comment]
> > Moving away from the logging, what are your thoughts on having some of the config in the UI?
> 
> it's something I want to do, among a lot of other things :)

I look forward to the work you're doing :)

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
