### ISSUE TITLE
Opening multiple tabs of webui freezes it

### ISSUE THREAD

**Issue by ivaniskandar** [gotson/komga#816]
### Steps to reproduce

Open 6 tabs of webui of any page.

### Expected behavior

Works normally as tested with the demo server which I believe is running an older version.

### Actual behavior

Opening the sixth tab freezes the rest of the tabs until the sixth tab is closed.

### Logs

`2022-02-22 22:10:28.977  WARN 1 --- [http-nio-8080-exec-7] o.s.web.servlet.PageNotFound             : No mapping for GET /dashboard`

https://pastebin.com/3FJ7rFHa

### Komga version

v0.152.0-master

### Operating system

Docker on Synology DSM

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Works normally as tested with the demo server which I believe is running an older version.

Not true, it always runs the latest version.

---

this is probably your browser that cannot handle the load. Komga is a Single Page Application, it is quite heavy for browsers. It is also not made for opening multiple tabs.

**Comment by ivaniskandar** [comment]
I've tried the demo server with the exact same browser instance. Is it an issue with my server configuration then?

**Comment by Kussie** [comment]
Just tried opening 10 tabs on my instance which is running 0.152 and had no issues, could browse and navigate in each tab without issues,

**Comment by ivaniskandar** [comment]
Are you using docker to deploy the instance?

> Just tried opening 10 tabs on my instance which is running 0.152 and had no issues, could browse and navigate in each tab without issues,

Are you using docker to deploy yours?

**Comment by ivaniskandar** [comment]
I've made a fresh empty instance using docker on digital ocean [here](http://188.166.119.184).
login: `demo@kom.ga`
pass: `komga-demo`

using this command to create the container
```
docker create \
  --name=komga \
  -p 80:8080 \
  --mount type=bind,source=/config,target=/config \
  --mount type=bind,source=/data,target=/data \
  --restart unless-stopped \
  gotson/komga
```

I can still replicate the issue.
