### ISSUE TITLE
OAuth Admin Roles

### ISSUE THREAD

**Issue by coolmule0** [gotson/komga#819]
### Describe your suggested feature

Provide a way to have admin users from OIDC/OAuth-realm be admin users within Komga. 

A extension to this feature is to also provide a way for the other roles, such as "page streaming" and "file download", to be set through the OAuth-realm.

### Other details

Komga has various types of roles, including user and admin. These affect how much a user can interact with various elements of Komga. It should be possible to have these roles specified at the OAuth manager end (e.g. Keycloak, Authelia). This allows OAuth managers to easily set admin privileges for multiple Komga users, as well as privileges across other services the OAuth manager handles, quickly and efficiently.

OAuth managers can specify a mapping such that the OAuth user with certain roles can be translated into a Komga user with certain roles. The obvious one is that OAuth-realm admins should be Komga admins. When an OAuth-managed user loses admin status, this propagates into Komga and they lose admin status for the site also.  An example of this feature elsewhere is with [Nextcloud Social Login](https://apps.nextcloud.com/apps/sociallogin). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is not detailed enough, please add more information or i'll close it.
