### ISSUE TITLE
Hide book page count in series view

### ISSUE THREAD

**Issue by svew** [gotson/komga#823]
### Describe your suggested feature

Add an option to a series/all series to hide the page count for its books. It's not all that useful (for me, and others I'm sure), and takes up a lot of vertical space

Before:
![image](https://user-images.githubusercontent.com/44253688/156456473-73fae1e0-02f9-400f-9364-bbd69b533aaf.png)

After:
![image](https://user-images.githubusercontent.com/44253688/156457192-fac3121c-fcbf-4cb5-9ab4-f6fd3dfbff9a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The bottom area is also used to display other kind of information, for example when changing the sort.
