### ISSUE TITLE
Order the targets in duplicate page

### ISSUE THREAD

**Issue by tomandocubatas** [gotson/komga#825]
### Describe your suggested feature

I think it would be a good option if the cards were ordered in the duplicate pages functionality, in such a way that those cards that can be acted on would appear first.
For example, first those targets that you can act on by removing the matches.
Right now sometimes the cards you can act on are on page 2, 3, etc.

![imagen](https://user-images.githubusercontent.com/36165495/156609701-7687abc5-5812-437a-be24-69da22070ca7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
For now the number of matches is retrieved client side, which makes sorting impossible.
