### ISSUE TITLE
Enable touch swipe to change page in the web reader.

### ISSUE THREAD

**Issue by IcySon55** [gotson/komga#829]
### Describe your suggested feature

When using the web reader, it would fantastic for the feel if you could change the page by swiping left and right. Especially while reading on a touch enabled Windows PC like a Surface.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's already available, just enable it in the reader settings.
<img width="506" alt="Screenshot 2022-03-06 at 16 29 23" src="https://user-images.githubusercontent.com/2139133/156915345-9691abda-d7ac-41f1-821c-e59df0c63e20.png">
