### ISSUE TITLE
[Bug] Docker Port forward

### ISSUE THREAD

**Issue by TopHatMan** [gotson/komga#83]
### Komga environment
- **OS**: Linux os docker unraid
- **Komga version**: latest commit
- [ ] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Actual behavior
What happened instead.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.

I have komga running on host port 8080 , I can not get it go with my port forwarding on my router.

**Comment by gotson** [comment]
please take the time to fill the template and provide all the necessary information

**Comment by gotson** [comment]
Please take the time to fill all the template sections (docker image version, actual and expected behaviour) and also what you have tried so far, for instance accessing your Komga instance directly, without going through your router port forwarding.

**Comment by TopHatMan** [comment]
I will close it and re open it later then.
