### ISSUE TITLE
Full support for jpeg xl

### ISSUE THREAD

**Issue by TheHardew** [gotson/komga#831]
### Describe your suggested feature

Please add support for reading jpeg xl image files. It can losslessly compress existing jpeg files by about 20%, Adobe and Facebook have already declared that they will support the format (in fact you can already upload some jpeg xl files to facebook). I believe it could become really popular.
 
Jpeg xl in cbz can already be displayed with google chrome (with the jxl flag turned on) or with tachiyomi, however cover image generation fails.

You can look here to check how tachiyomi handles it: https://github.com/tachiyomiorg/image-decoder

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
As you noticed, there is already limited support for jxl which I added recently, so indeed browser will display, and tachiyomi too.

Komga doesn't need to decode images for everything, only for some actions, like :
- generating covers
- converting on the fly (if you read via opds for example, some formats would be converted)
- duplicate page detection
- dimension analysis

You can use custom covers to go around the cover generation issue.

Komga relies on 3rd party libraries for image decoding, mostly the very good https://github.com/haraldk/TwelveMonkeys

There is no java library for jxl yet, and the best bet is https://github.com/haraldk/TwelveMonkeys/issues/643

That's a long shot though.

Keep in mind that standard adoption is slow, take webp for instance. It's not yet supported everywhere.

**Comment by BuZZ-dEE** [comment]
There is a [bounty for TwelveMonkeys JPEG-XL read and write support](https://app.bountysource.com/issues/105544002-jpeg-xl-jxl-read-and-write-support).

**Comment by TheHardew** [comment]
For twelvemonkeys do you need a decoder written only in java or can it link to libjxl in C? I'm trying to judge how likely it is someone will be able to write it.

**Comment by gotson** [comment]
> For twelvemonkeys do you need a decoder written only in java or can it link to libjxl in C? I'm trying to judge how likely it is someone will be able to write it.

Twelvemonkeys is pure Java.

The problem with decoders in C is that you need to interface with JNI and write custom C code for the interop. I already use one for webp, but you need to compile it for all systems, which is tedious.

Project Panama should help in that regards, but is not finalized yet, and would require a very recent version of Java.

**Comment by gotson** [comment]
I have released the first version of https://github.com/gotson/NightMonkeys which has an imageio plugin for jpeg xl. This can be integrated in Komga, but requires to launch Java with specific version and arguments.

@TheHardew do you use Komga via jar or Docker, or another method?

**Comment by TheHardew** [comment]
I use the jar. I was wondering why I had 8k empty files in /tmp starting with "imageio".

**Comment by gotson** [comment]
The jar would be easier to accommodate, you would need jdk 18 and some extra command line parameters, and also the jxl library installed locally.

What's your os?

**Comment by gotson** [comment]
> Edit: To be precise, I use the Arch User Repository package, but it would probably be quite easy to edit that.

It's a third party maintained integration, so 🤷🏻‍♂️

**Comment by gotson** [comment]
What's your os?

**Comment by TheHardew** [comment]
Arch Linux. 
I have Komga 0.153.2-1, Java 18, libjxl v0.7.0 79d85890.

**Comment by TheHardew** [comment]
All the Arch package does is it installs the jar and the /usr/bin/komga file:
```
#!/bin/sh
exec /usr/bin/java -jar '/usr/share/java/komga/komga.jar' "$@"
```

**Comment by TheHardew** [comment]
I set `LD_LIBRARY_PATH` to `/usr/lib` because that's where `libjxl.so` is. I started Komga with `/usr/bin/java --enable-native-access=ALL-UNNAMED --add-modules jdk.incubator.foreign -jar /usr/share/java/komga/komga.jar`. It did not work. When I get home I'll try to use the latest release version of libjxl, instead of this one compiled from git.

**Comment by gotson** [comment]
> I set `LD_LIBRARY_PATH` to `/usr/lib` because that's where `libjxl.so` is. I started Komga with `/usr/bin/java --enable-native-access=ALL-UNNAMED --add-modules jdk.incubator.foreign -jar /usr/share/java/komga/komga.jar`. It did not work. When I get home I'll try to use the latest release version of libjxl, instead of this one compiled from git.

Well of course it did not work, I have not released anything 🤷🏻

**Comment by TheHardew** [comment]
Works wonderful, thank you very much!

**Comment by gotson** [comment]
> Works wonderfully, thank you very much!

bit surprised since i haven't released Komga with that lib included

**Comment by TheHardew** [comment]
I built in myself.

**Comment by whalehub** [comment]
In case anyone else stumbles across this issue and is struggling to get Komga to recognize their native JXL library: The library file has to be renamed or symlinked to `libjxl.so`. Komga won't recognize the native library if it's called, e.g. `libjxl.so.0.6.1` or `libjxl.so.0.7.0`. (@gotson Is this intentional or a bug?)

This is how I set it up, using Debian 11 as an example:

1. Download and install `libjxl` and its dependencies.
```
whalehub@pdh:~# curl -LO http://ftp.debian.org/debian/pool/main/h/highway/libhwy0_0.16.0-1_amd64.deb
whalehub@pdh:~# curl -LO http://ftp.debian.org/debian/pool/main/j/jpeg-xl/libjxl0.7_0.7.0~git20220325.7594374+ds-3_amd64.deb
whalehub@pdh:~# sudo dpkg -i libhwy0_0.16.0-1_amd64.deb libjxl0.7_0.7.0~git20220325.7594374+ds-3_amd64.deb
```

2. Create a symbolic link to the file name that is expected by Komga:
```
whalehub@pdh:~# cd /usr/lib/x86_64-linux-gnu
whalehub@pdh:~# ln -s libjxl.so.0.7.0 libjxl.so
```

3. Set the `LD_LIBRARY_PATH` variable to the library folder (preferably in a systemd service file):
```
whalehub@pdh:~# LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
```

4. Launch Komga.
```
whalehub@pdh:~# java --add-modules jdk.incubator.foreign --enable-native-access=ALL-UNNAMED -jar /usr/local/bin/komga.jar
```
5. Verify that Komga successfully loads the native library.
```
INFO 2581598 --- [main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Loaded libjxl v0.7.0
INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Using native WebP library
INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPG, JPEG 2000, tiff, bmp, PCX, bigtiff, wbp, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jpeg-lossless, jbig2, jxl, jpg, JPEG2000, BMP, pcx, WBP, GIF, Jpeg XL, png, BIGTIFF, raw, JPEG-LOSSLESS, webp, JBIG2, pnm, TIF, jpeg2000, WEBP, WebP, jpeg 2000]
INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/gif, image/x-windows-pcx, image/x-pc-paintbrush, image/x-raw, image/webp, image/x-pcx, image/x-portable-bitmap, image/png, image/x-jb2, image/pcx, image/x-windows-bmp, image/x-webp, image/jpeg2000, image/x-bmp, image/jp2, image/x-png, image/x-portable-pixmap, image/x-jbig2, image/tiff, image/x-tiff, image/x-portable-anymap, image/jxl]
```

**Comment by gotson** [comment]
> In case anyone else stumbles across this issue and is struggling to get Komga to recognize their native JXL library: The library file has to be renamed or symlinked to `libjxl.so`. Komga won't recognize the native library if it's called, e.g. `libjxl.so.0.6.1` or `libjxl.so.0.7.0`. (@gotson Is this intentional or a bug?)
> 
> This is how I set it up, using Debian 11 as an example:
> 
> 1. Download and install `libjxl` and its dependencies. The required packages are only available in Debian Sid and Experimental, so they have to be installed using `dpkg` instead of `apt`.
> 
> ```
> whalehub@pdh:~# curl -LO http://ftp.debian.org/debian/pool/main/h/highway/libhwy0_0.16.0-1_amd64.deb
> whalehub@pdh:~# curl -LO http://ftp.debian.org/debian/pool/main/j/jpeg-xl/libjxl0.7_0.7.0~git20220325.7594374+ds-3_amd64.deb
> whalehub@pdh:~# sudo dpkg -i libhwy0_0.16.0-1_amd64.deb libjxl0.7_0.7.0~git20220325.7594374+ds-3_amd64.deb
> ```
> 
> 2. Create a symbolic link to the file name that is expected by Komga:
> 
> ```
> whalehub@pdh:~# cd /usr/lib/x86_64-linux-gnu
> whalehub@pdh:~# sudo ln -s libjxl.so.0.7.0 libjxl.so
> ```
> 
> 3. Set the `LD_LIBRARY_PATH` variable to the library folder (preferably in a systemd service file):
> 
> ```
> whalehub@pdh:~# LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
> ```
> 
> 4. Launch Komga.
> 
> ```
> whalehub@pdh:~# java --add-modules jdk.incubator.foreign --enable-native-access=ALL-UNNAMED -jar /usr/local/bin/komga.jar
> ```
> 
> 5. Verify that Komga successfully loads the native library.
> 
> ```
> INFO 2581598 --- [main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Loaded libjxl v0.7.0
> INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Using native WebP library
> INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Supported read formats: [JPG, JPEG 2000, tiff, bmp, PCX, bigtiff, wbp, gif, WBMP, PNG, RAW, JPEG, PNM, BigTIFF, tif, TIFF, wbmp, jpeg, jpeg-lossless, jbig2, jxl, jpg, JPEG2000, BMP, pcx, WBP, GIF, Jpeg XL, png, BIGTIFF, raw, JPEG-LOSSLESS, webp, JBIG2, pnm, TIF, jpeg2000, WEBP, WebP, jpeg 2000]
> INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Supported read mediaTypes: [image/vnd.wap.wbmp, image/jpeg, image/x-portable-graymap, image/bmp, image/gif, image/x-windows-pcx, image/x-pc-paintbrush, image/x-raw, image/webp, image/x-pcx, image/x-portable-bitmap, image/png, image/x-jb2, image/pcx, image/x-windows-bmp, image/x-webp, image/jpeg2000, image/x-bmp, image/jp2, image/x-png, image/x-portable-pixmap, image/x-jbig2, image/tiff, image/x-tiff, image/x-portable-anymap, image/jxl]
> ```

Java expects the making as you mention, that's how it is. There should always be those normal names, the ones with added numbers are not standard AFAIK.

Installing with homebrew creates those links by default.

**Comment by whalehub** [comment]
>  Java expects the naming as you mention, that's how it is. There should always be those normal names, the ones with added numbers are not standard AFAIK.

At least on Debian, it looks like many library packages only include library files with the added numbers, e.g. [libwebp](https://packages.debian.org/bullseye/amd64/libwebp6/filelist) or [libavif](https://packages.debian.org/bullseye-backports/amd64/libavif13/filelist), so even when the package eventually moves from Debian Experimental to Debian 12, Java won't be able to find the native library if you install it using a package manager. From what I could find during a quick search, the same naming convention with the numbers is used by [Alpine Linux](https://pkgs.alpinelinux.org/contents?branch=edge&name=libjxl&arch=x86_64&repo=community), [Fedora](https://koji.fedoraproject.org/koji/rpminfo?rpmID=28945701) and [Red Hat/CentOS](https://koji.fedoraproject.org/koji/rpminfo?rpmID=28616179).

I just noticed that Komga recognizes the native WebP library even though it isn't named `libwebp.so`.

```
root@pdh:~# ls -lha /usr/lib/x86_64-linux-gnu | grep libwebp.so
lrwxrwxrwx  1 root root    16 Jun  5  2021 libwebp.so.6 -> libwebp.so.6.0.2
-rw-r--r--  1 root root  407K Jun  5  2021 libwebp.so.6.0.2
```

I'm sadly not proficient enough in Java to figure out why the package `com.luciad.imageio.webp` is able to find it like this.

**Comment by gotson** [comment]
`com.luciad.imageio.webp` doesn't use native libraries, but a specific version bundled in the `jar`, along with some JNI code.

**Comment by whalehub** [comment]
> `com.luciad.imageio.webp` doesn't use native libraries, but a specific version bundled in the `jar`, along with some JNI code.

Is the following line from the logs generated by a different package? The reason I thought it was `com.luciad.imageio.webp` is because of [this commit](https://github.com/gotson/komga/commit/15caea3b99b76162aa636bcd691032a4510f32ff#diff-432dc4ec02cab7ed88d15a87a45824936c79d0f6cdad39c37ae45d2d57e282ecR27).

```
INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Using native WebP library
```

**Comment by gotson** [comment]
> > `com.luciad.imageio.webp` doesn't use native libraries, but a specific version bundled in the `jar`, along with some JNI code.
> 
> Is the following line from the logs generated by a different package? The reason I thought it was `com.luciad.imageio.webp` is because of [this commit](https://github.com/gotson/komga/commit/15caea3b99b76162aa636bcd691032a4510f32ff#diff-432dc4ec02cab7ed88d15a87a45824936c79d0f6cdad39c37ae45d2d57e282ecR27).
> 
> ```
> INFO 2581598 --- [main] o.g.k.i.image.ImageConverter             : Using native WebP library
> ```

Trust me when I say it doesn't use the native lib on your system, but a bundled native lib in the jar.
