### ISSUE TITLE
Keep manga/comic *in use* (persistence) until being exited fully.

### ISSUE THREAD

**Issue by vegedb** [gotson/komga#832]
### Steps to reproduce

1. Mount samba fileshare to ramdisk
2. Set ramdisk to flush/delete/clear when any item goes "**STALE**" at 1s
3. Use Web Browser or Tachiyomi
4. Test a 200MB comic

### Expected behavior

The 200MB comic should NOT get stale at any point of reading it.
Similar how a video file works, when the player exits, the 200MB file exits along with it not during watching the video.
Similarly, a 200MB comic shouldn't exit at any point, ramdisk won't detect as it being stale.

### Actual behavior

1. 1st instance of open it will download to ramdisk 0-200MB
2. During reading, ramdisk clears/flushes it as it "detects" the 200MB file is "**STALE**"
3. Ramdisk will keep on downloading 0-200MB at **every single page**

### Komga version

v0.153.0

### Operating system

Ubuntu 20.04 LTS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't even understand what your problem is. Can you maybe describe the symptoms?

**Comment by vegedb** [comment]
Sure,

For mounts, Komga downloads the whole comic file. 200MB fully.

Now, after downloading 200MB fully, Komga immediately "releases" it. This shouldn't happen for various reasons like buffering etc.

Komga should keep it as "downloading" phase/stage and not "release" it at all. 
Prevent komga from "releasing" it until you fully exit the comic fully.

**Comment by gotson** [comment]
> Now, after downloading 200MB fully, Komga immediately "releases" it. This shouldn't happen for various reasons like buffering etc.
> 
> Komga should keep it as "downloading" phase/stage and not "release" it at all. Prevent komga from "releasing" it until you fully exit the comic fully.

What are those terms you use like "releasing" or "downloading" referring to exactly?

**Comment by vegedb** [comment]
When you click on "read" using the web interface. 

The file will be downloaded fully from my SMB server to RAMDISK as cache.

Now, after downloading, komga don't care about the file in ramdisk anymore and forgets it has already downloaded it.

After swiping to next page, SAME FILE, Komga initiates a download sequence again. 

Then it forgets again.

And it downloads again.

Forgets again.

Goes on and on.

**Comment by gotson** [comment]
Filesystems work by opening and closing files. There is no reason for Komga to keep a file open for no reason. Once a page is read, the enclosing file can be closed.

You seem to assume that the application should handle the caching of your remote filesystem, but that's not the application's job. That's the filesystem's job.

For instance if you use a tool like rclone to mount a Google drive as a filesystem, rclone lets you configure caching etc.

I am not familiar with smb or that ramdisk you mention, but purging something after 1 second doesn't seem like a good idea.

Anyhow, this is not an application concern, and should be addressed at the filesystem level.

**Comment by vegedb** [comment]
> I am not familiar with smb or that ramdisk you mention, but purging something after 1 second doesn't seem like a good idea.

The main reason I keep it so low is to prevent it to be stale in RAM when not in used. No point in having it in RAM if its not used. And from my logic, once you finish reading a comic, you don't need to go back to it.

I have always done it for video playback too. Videos don't get purged if you pause/play no matter what player/client is used.


>  There is no reason for Komga to keep a file open for no reason. Once a page is read, the enclosing file can be closed.

Any reason this is too difficult to implement. It would be logical to keep the downloaded file in retainer until its closed or finish reading.

> You seem to assume that the application should handle the caching of your remote filesystem, but that's not the application's job. That's the filesystem's job.

I'm not asking for komga to do any caching AT ALL. Just keep it in retainer or at least hold it enough preventing it from going stale. Prevent it from closing the file.
