### ISSUE TITLE
Image split

### ISSUE THREAD

**Issue by kilala117** [gotson/komga#833]
### Describe your suggested feature

I think there should be quite a few people who have this need, since a lot of the manga collected is in a double page. 
It is hard to read on a device with a vertical screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Please provide a more detailed description.

**Comment by TehUncleDolan** [comment]
I suppose they want the WebReader to have a dual page split mode, like [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/pull/4252#issuecomment-755765067).

It's indeed quite convenient.

**Comment by lsl330** [comment]
> Please provide a more detailed description.

This is a very convenient feature, because many comics are scanned in double pages, which can be more easily read after splitting
