### ISSUE TITLE
[Feature Request] Reader Settings as a User setting rather than per-browser cookie

### ISSUE THREAD

**Issue by primetoxinz** [gotson/komga#84]
Currently, the Reader settings, such as single/double page, screen fit and others that may be added in the future, are stored as cookies. 
This works fine in most contexts, but often users change device, browser, or have to clear cookies for various reasons.

My suggestion is to have a Reader settings section under the Account settings. Optionally, the cookies could be maintained and have precedence over the server side Account settings.

**Comment by gotson** [comment]
> or have to clear cookies for various reasons.

Could you expand on this one? What reasons would that be?

---

Moving those settings per user does not necessarily make sense, as those settings are not related to a particular user:
- Single/Double page is mostly depending on the book and the screen size
- Screen Fit is related to the screen size
- reading direction depends directly of the book type

If settings were per user, and let's say you had a wide screen on your desktop PC, you may want to use double pages. But if you switch to your Tablet (and let's assume you don't use any OPDS client) you don't want the Fit to change to double pages as you wouldn't have the screen real estate for that.

Some information will also be coming from book metadata, for example reading direction will be a metadata field, and will override cookie settings for the reader. So when you open a manga, it will be set a RTL automatically.

**Comment by primetoxinz** [comment]
> Could you expand on this one? What reasons would that be?
Not to say that cookie clearing is a common occurrence, that just an example of potential downsides to settings being stored in that way. I've had personal experiences where the only solution to an issue was to clear all browser cookies.

I agree with all your reasons that it is beneficial for the data to be client side, I suppose maybe I did not think it entirely through before asking. 
My original inclination was that I dislike having the potential to lose any settings for a web app, even if it's ~3 quick buttons.

To given an overcomplicated solution to a non-problem, users setting with per-device reader settings is technically possible ;)

**Comment by gotson** [comment]
> To given an overcomplicated solution to a non-problem, users setting with per-device reader settings is technically possible ;)

I don't want to over-complexify something whereas the actual problem is a non-problem :)
