### ISSUE TITLE
Support for DjVu format

### ISSUE THREAD

**Issue by SubZeroPL** [gotson/komga#840]
### Describe your suggested feature

I think it would be nice if Komga had support for new format: [DjVu](https://en.wikipedia.org/wiki/DjVu). This format (as far as I know) is mostly used for newspapers, magazines etc. Format is open source so I think it's implementing should not be very difficult.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Format is open source so I think

There's no java library for this format, probably because no one is actually using it 🤷🏻

**Comment by TehUncleDolan** [comment]
To bo honest it's used, especially for scanned books/documents (but PDF is more mainstream, even though it's less good for that).

But yeah never seen it used for comics/mangas/BD, so not really relevant to Komga IMHO.

And even though format is open-source, it doesn't seem to be patent-free...

**Comment by 0x00ff** [comment]
There is a js lib/viewer for djvu - [djvujs](https://github.com/RussCoder/djvujs).
