### ISSUE TITLE
I suggest the function.

### ISSUE THREAD

**Issue by thestreetdj** [gotson/komga#841]
### Describe your suggested feature

1. Make sure to select a reading method for each study and apply it to its subfolders.

2. Please allow me to read the metadata online and enter the address myself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand anything of what you've written.
