### ISSUE TITLE
Docker instalation error

### ISSUE THREAD

**Issue by Nfivez** [gotson/komga#843]
### Steps to reproduce

1. follow komga.org docker installation(either cli/compose will work) 

### Expected behavior

Installation works correctly

### Actual behavior

Installation gets permission denied because there is no actual docker user.

### Logs

When using the console in portainer, it shows no group ID 1000. It also shows I have no user and proceeds to restart initialization.

### Komga version

0.153.1

### Operating system

Ubuntu 20.04 LTS

### Other details

Fix: By removing the user line in docker-compose/docker cli command. I am not sure if it was intended or just older docker version needing a groupid while newer does not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You need to know what you are doing, and choose the user ID and group ID to something that exists on your system.
