### ISSUE TITLE
Search results incomplete / indexing issue

### ISSUE THREAD

**Issue by MelanieTanaka** [gotson/komga#845]
### Steps to reproduce

Perform a search for a series that is known to be present and is accessible via komga and can be read

1. start typing name of series
2. some partial matches may show up but there is clearly results missing
3. click "search all" just to be sure, same results present

### Expected behavior

I expect to see an accurate list of available series matching the search term on my komga server

### Actual behavior

I see an incomplete list (in some cases no results at all). View image example:

"live" search bar results with visible series in the list that should show up: 
![image](https://user-images.githubusercontent.com/45699059/159765359-f1ae16a1-0d6a-45a0-9a54-f77d07a8fdb8.png)

search results page for same as above:
![image](https://user-images.githubusercontent.com/45699059/159765443-08279974-a288-403c-b972-0c6dfd7781ff.png)

### Logs

Tried to look through the logs for the words "search" only one line showed up:

`2022-03-23 12:48:50.241  INFO 19735 --- [main] o.g.k.i.scheduler.SearchIndexController  : Lucene index version: 4`

### Komga version

v0.153.1-master, .jar file

### Operating system

Ubuntu Server 18.04

### Other details

Before bothering to debug further I want to point out I have close to 5000 series in my library, containing nearly 150k "books". If Komga hasn't been tested to support indexing that much content then makes sense so let me know if there's any point continuing.

It took about 3 days to scan the library, make the series/books cover images etc. The server has been idle now doing nothing for several days, I've restarted the service a few times since then to try and encourage it to generate better search results. Don't know if there is some command line or other things I can use to check on this. The web interface doesn't seem to have any information about this or the ability to manage the search indexing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> Before bothering to debug further I want to point out I have close to 5000 series in my library, containing nearly 150k "books". If Komga hasn't been tested to support indexing that much content then makes sense so let me know if there's any point continuing.

Komga works with bigger libraries.

Maybe the process stopped for some reason while indexing. Indexing for search is done when entities change. You can try to edit the series metadata (change whatever you want, like the age rating), it should then be indexed again.

**Comment by MelanieTanaka** [comment]
That seems to do the trick. If I do it 100 series at a time hoping it won't crash and shouldn't take too long to do manually.
Thanks for the help.

**Comment by gotson** [comment]
A better solution would be to recreate the whole index.

You can:
- stop Komga
- delete the `lucene` directory that sits in your configuration directory
- start Komga

The logs will show the progress on the index rebuilding.

**Comment by MelanieTanaka** [comment]
Doing that solved it, thanks.
