### ISSUE TITLE
Unable to delete unavailable comic

### ISSUE THREAD

**Issue by Naatan** [gotson/komga#848]
### Steps to reproduce

1. Import a comic
2. Delete the file from the filesystem
3. Allow komga to detect the file as being "Unavailable" as a result
4. Attempt to delete the Comic from komga

### Expected behavior

The comic is deleted from Komga

### Actual behavior

Comic remains in "Unavailable" state

### Komga version

0.153.1

### Operating system

Ubuntu 20.04

### Other details

The comic in question had a "Media type is not supported" comment, which might contribute to the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You need to empty the trash, not delete. You cannot delete something that doesn't exist.

Read the documentation about the trash feature.
