### ISSUE TITLE
Komga requires login almost every time

### ISSUE THREAD

**Issue by Bazzu85** [gotson/komga#851]
### Steps to reproduce

1. Open komga on chrome for android
2. Login
3. Close tab or saved page
4. Open again

Sometimes the login is requested 

### Expected behavior

No login required every time

### Actual behavior

Check this video: https://youtube.com/shorts/OqtoI1mCbFQ?feature=share

Seems to be very similar to #39 

### Komga version

0.153.1

### Operating system

Windows 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Did you enable remember me? https://komga.org/installation/configuration.html#komga-rememberme-key-komga-remember-me-key-key

**Comment by Bazzu85** [comment]
I'll try today but no, I don't use this argument in nssm..
Why don't you add a checkbox during login? Or an option in webui?
Thx

**Comment by Bazzu85** [comment]
I can confirm that with start argument the app keeps the login..
