### ISSUE TITLE
Back arrow takes you back to first page

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#852]
### Steps to reproduce

1. Navigate to any other page than 1.
2. Open a title to view
3. Click back arrow at the top

### Expected behavior

The back arrow should return you to the page number you were last on.

### Actual behavior

Returns to page 1. 

### Komga version

0.153.0

### Operating system

Asustor NAS GNU linux

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand the steps you wrote, they are not detailed enough.

**Comment by billsargent** [comment]
1. Pick a library
2. Navigate to any page other than 1 (i.e. 5)
3. Select a comic and open it.  
4. Use the back arrow at the top to go back to the list of comics

You'll be at Page 1 rather than the page the one you were previously on. 

Does this help?

**Comment by gotson** [comment]
That's normal. The back arrow in the ui is to take you to the library containing the series.

To go back in history, use your browser's back button.
