### ISSUE TITLE
Ability to create subfolders

### ISSUE THREAD

**Issue by Smeety** [gotson/komga#854]
### Describe your suggested feature

It would be really nice to have the ability to make subfolders for Volumes/Seasons/Parts so the structure could go like
Series>Volume>Chapter

Main Series:
![Screenshot 2022-04-01 011521](https://user-images.githubusercontent.com/44217655/161166661-39aabe76-9db5-4f75-8378-aadef80cf2c9.png)
Subfolder/Volume:
![image](https://user-images.githubusercontent.com/44217655/161166645-9a0edf1d-6576-40fe-949a-155d6014de5a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I have no plans to do this, Komga is flexible enough so this should not be needed.

For Comics, the Volume is usually deported to the Series level.

For Manga, you can mix & match chapters and tankobon in the same Series, but most people choose to either collect one or the other.

If that's something you really want, i suggest you take a look at Kavita, which has official support for this for manga.
