### ISSUE TITLE
Add to read list: show most recently modified at the top

### ISSUE THREAD

**Issue by chelming** [gotson/komga#862]
### Describe your suggested feature

When you're creating a custom read list and adding a bunch of things, it'd be nice if the most recently modified read list was displayed at the top. I could temp rename it to something like `!Read List` but that seems sketchy.

If you don't store modified times on read lists and don't have any intention to, you can feel free to close this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There's a modified time on the readlist itself, but not on its content.

**Comment by gotson** [comment]
I was checking that part of the code recently, and it actually works, when updating a readlist content, the modified date of the readlist is updated also, as the whole object is updated in DB. So that seems feasible.
