### ISSUE TITLE
Load ComicInfo.xml that is inside the folder of a series

### ISSUE THREAD

**Issue by Deivu** [gotson/komga#866]
### Describe your suggested feature

In addition on needing to load the ComicInfo.xml inside the .cbz archive, having it load the ComicInfo.xml in the series folder would be a great addition (if present, and enabled) if possible.

eg:
Series Folder
  - ComicInfo.xml
  - 001.cbz
  - 002.cbz

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Comicinfo.xml is expected at the root of the archive this is how all apps expect it.

**Comment by MKH-42** [comment]
Helle Deivu,

maybe this can help you: 
There is another request to read ComicInfo.xml Format outside of the comic. It is Issue #408.
When you want to use ComicInfo.xml for series information: There is already the posibility to use series.json.
Have a look here: https://komga.org/guides/scan-analysis-refresh.html#import-metadata-generated-by-mylar
