### ISSUE TITLE
Announce New Books To Discord Via Webooks

### ISSUE THREAD

**Issue by tacticaljj** [gotson/komga#874]
### Describe your suggested feature

The ability to announce new books to a Discord channel using Webhooks and Discord Bots. The announcement would show a thumbnail of the comic and or a Thumbnail, Title and the Story/Plot summary.  This could work very much the same way you can announce new movies from Plex to Discord as shown in the attached example image:

![example](https://user-images.githubusercontent.com/104578074/165782014-16d8956c-7b72-4c27-a826-b306d06c6a1e.JPG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I have no plans to add notifications to various systems. There is already a server sent events endpoint that will convey information about what's going on, it could be used to add 3rd party notifications.
