### ISSUE TITLE
Translate speech bubbles when Tapped

### ISSUE THREAD

**Issue by cloudycloud47** [gotson/komga#876]
### Describe your suggested feature

 Ok I get this is a LONG stretch but I love GOOGLE LENS for it's OCR auto translate feature.
There are lots of mainstream comics that have characters speaking in different languages, sometimes short phrases but sometimes context important speech.
I use my Cell phone to scan the comic pages on my Tablet or computer screen to get the translation.

It would be cool if you could set a 'Native' language in Komga and then when a speech bubble has foreign text, you could tap it for auto translate.
Tapping again would hide the translation.

I can't begin to understand how to go about it but it would be a great enhancement.

This feature could be used to translate whole comics to a different language if if you set your native language to something other than the comic language.

Google AI to identify speech bubbles
https://blog.google/products/google-play/google-play-books-introduces-bubble-zoom/
https://cloud.google.com/functions/docs/tutorials/ocr

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's way out of scope of this project.
