### ISSUE TITLE
Option to Ignore Epubs Entirely

### ISSUE THREAD

**Issue by silasfelinus** [gotson/komga#877]
### Describe your suggested feature

Most of my books have 2 copies, a pdf with the proper number of pages, and an epub that displays in every reader (Calibre web, Kybooks, Ubooquity) except Komga (for reasons discussed elsewhere).

An option to disable epub files entirely either in server settings or library would be wonderful (or to ignore individual files on a case by case basis).

### Other details

As a hail mary, I attempted to create an exception by setting "KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS" to "#recycle,@eaDir,@Recycle,*.epub" as a Docker environmental variable, but it didn't seem to work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
XY problem. Why do you have 2 copies in the first place?

**Comment by silasfelinus** [comment]
I've generally found epubs to be a more flexible format (when supported), they resize to screens much better than pdfs, plus pdfs are generally a pain. I originally had most epubs, but then converted everything that I could to pdf so they could be read in komga. 

In an optimal serup, I'd have a pdf, aw3, and epub in each folder, unless one format truly rises to surpass and encompass the others

**Comment by gotson** [comment]
Komga supports epub so I'm not sure why you had to convert to pdf?

**Comment by gotson** [comment]
Or are you specifically talking about text epub, not image epub?

**Comment by silasfelinus** [comment]
Yes. I have a large-ish book collection (9k titles). Most of the epubs are text epubs (I'd estimate that was originally the most common format).

I'd originally got komga just for comics. Then added the book collection, but many of the epubs required converting. Now I've got an even larger collection and a combination of epubs (some image, some text) and pdfs.

**Comment by gotson** [comment]
Depending how you consume them, if the client downloads the file for example, like any opds client, then you don't necessarily need to convert.

The books will show with 1 page (usually the cover), and won't read in the webreader, but would work in kybook for example.

**Comment by silasfelinus** [comment]
My primary use with Komga is as a self-hosted webservice. The 1-2 page epubs are clutter that reduce the benefits of the "Recent" libraries as most listings are doubled up.

I can work around them for my own use, but I want to remove them before I share the library with others.

**Comment by silasfelinus** [comment]
The fallback plan is to create a unique Komga library of pdfs, but that would involve extra hassle and inefficient space allocation.

**Comment by gotson** [comment]
Converting text books to image pdf is really not a good solution, you should look at software that handles text books natively.

**Comment by jjhhgg100123** [comment]
Interested in this as well. On top of it being useful for ebooks, I'd use it for a series where I may have only downloaded a chapter or two but kept it in my library folder for "organization". It get a bit messy with them taking up space without covers and such.

Maintaining a separate library for them would be a pain to do by hand.

**Comment by gotson** [comment]
🎉 This issue has been resolved in `v1.5.0` ([Release Notes](https://github.com/gotson/komga/releases/tag/v1.5.0))
