### ISSUE TITLE
Add alternative titles metadata field for Series

### ISSUE THREAD

**Issue by ArnaudPiroelle** [gotson/komga#878]
### Describe your suggested feature

Many manga have one or more alternative titles depending on the publishing country, editor or edition name.

Example:
```
EN: Attack on Titan
FR: L'Attaque des Titans
JP: Shingeki no Kyojin / 進撃の巨人
```

To properly manage my collection, I would like to have the ability to edit the metadata and so retrieve a manga from any of its titles in the search engine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's not alternative titles, but titles in different languages.

There shouldn't be any reason to have the English title for a Japanese Manga published in French for instance.

**Comment by gotson** [comment]
> To properly manage my collection, I would like to have the ability to edit the metadata and so retrieve a manga from any of its titles in the search engine

That's not very clear. You want to be able to search by all those titles, is that it?

**Comment by ArnaudPiroelle** [comment]
Yes.

For example, if I have set a manga with the name `Attack on Titan` with an alternative name `Shingeki no Kyojin`, I should be able to search both of these names in the search field an retrieve the manga `Attack on Titan`.

If possible these alternative names should be available from the `/api/v1/series` and `/api/v1/series/{seriesId}` enpoints.

**Comment by ArnaudPiroelle** [comment]
And there is a reason to ask this feature, I want to be able to retrieve from my collection all missing informations on online manga databases like `myanimelist`, `kitsu` or `nautiljon`.

To search a manga or a book on these databases, I need to have all alternative titles.

**Comment by gotson** [comment]
> And there is a reason to ask this feature, I want to be able to retrieve from my collection all missing informations on online manga databases like `myanimelist`, `kitsu` or `nautiljon`.
> 
> To search a manga or a book on these databases, I need to have all alternative titles.

Can you expand on that?

**Comment by ArnaudPiroelle** [comment]
Depending on how you manage your collection, you should choose the title you set for a series.

Personnally, I like to use the most appropriate name.
In my collection, I use original title for a manga that is not already translated officially and the translated name when is published under license in my country.
But these two titles represent the same series.

When you want to search for metadatas or purchase link for a manga, you should search with different names to find the best matches.
For example: 
When I use MyAnimeList, I search only with english or original title.
When I use Nautiljon, I search only with french title.

On MyAnimeList, when I search "L'attaque des titans", they return 4 pages of result, and no one have the translated title.
I have to search in results the manga with name "Shingeki no Kyojin".
On Nautiljon, I have the same issue when I search with original name, they returns only the translated titles.

So you have to choose which title to use according to the database you are using for your search.

**Comment by gotson** [comment]
Not sure to understand, do you them have some scripts that would perform that search?

If yes, searching with each of the titles will give you even more results..

**Comment by ArnaudPiroelle** [comment]
Currently, I does'nt have scripts but I want to make an application to synchronize metadatas.
Even scripts or applications, I can't remember all translated titles for each mangas when I search a manga in online databases.

**Comment by ispaure** [comment]
For those who might not know, if you edit the metadata in ComicRack (ComicInfo.XML file within .CBZ archives), you can set an alternate series title and it will show in the "Read Lists" tab of Komga. Searching then works by either the main title or alternative title.

For instance, within ComicInfo.XML:
```
<Series>A Certain Scientific Railgun</Series>
<AlternateSeries>To Aru Kagaku no Railgun</AlternateSeries>
```
This limits you to two titles but it should already be enough. You can use English Title as default and Japanese Title as alternate for example (this is what I do).

**Comment by gotson** [comment]
> For those who might not know, if you edit the metadata in ComicRack (ComicInfo.XML file within .CBZ archives), you can set an alternate series title and it will show in the "Read Lists" tab of Komga. Searching then works by either the main title or alternative title.
> 
> For instance, within ComicInfo.XML:
> 
> ```
> <Series>A Certain Scientific Railgun</Series>
> <AlternateSeries>To Aru Kagaku no Railgun</AlternateSeries>
> ```
> 
> This limits you to two titles but it should already be enough. You can use English Title as default and Japanese Title as alternate for example (this is what I do).

The purpose of that field is not to store an alternative title of the series, but to reflect the fact that the book is part of 2 different series, usually for cross-overs.
