### ISSUE TITLE
[Feature Request] Allow Direct Input of Library Root Folder

### ISSUE THREAD

**Issue by hkalexling** [gotson/komga#88]
Thank you for the awesome project! 

I am running komga on a shared server, and I do not have the permission to list the `/home` directory. Now if I were to add a new library at `/home/myuser/books/` using the admin UI, komga would attempt to list the `/home` directory and stuck, and I won't be able to proceed to my home directory `/home/myuser`.
 
It would be great if we can have the option to directly type in the desired root folder.

**Comment by gotson** [comment]
To me this means your server is badly configured, `/` and `/home` should always be readable and traversable.

You can use the api directly or via swagger to create your library with the correct folder if you know it, as the folder exploration dialog is just here to help find a folder.

**Comment by gotson** [comment]
Reopening as I might do something about it later on, but there's a workaround via api anyway.
