### ISSUE TITLE
Scan on series level

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#881]
### Describe your suggested feature

At the moment komga can scan on library level.

![grafik](https://user-images.githubusercontent.com/76835223/167308107-456d84c8-4cbf-4c3d-ad56-d2270b4dbe2e.png)

When a series was changed it is always needed to wait (for the sceduled scan) or to scan the complete library.
It would be nice that we not have a "scan series files" option for series.

At the moment it is possible to analyze or refresh metadata but when the filename was changed it is not possible to refresh only the series. 

![grafik](https://user-images.githubusercontent.com/76835223/167308382-ec5325d0-13a0-4b64-92b4-38ea570ff96b.png)

Reason: When you have bigger libraries this needs a lot of time. This is not necessery when you know you only changed a series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Unless you have a very slow disk, or remote cloud drive, this is not necessary.

**Comment by MKH-42** [comment]
No it is not the slow disk. 
I enabled nearly all options in Komga like deep scan, ISBN, double pages, hashes ..

Maybe this is not a high priority request but it would be nice to have this feature in future :-)

**Comment by gotson** [comment]
You didn't provide metrics on scan time and library size / item count.

**Comment by gotson** [comment]
> I enabled nearly all options in Komga like deep scan, ISBN, double pages, hashes ..

Isbn, double pages, hashes : those have nothing to do with the scan, it's done during analysis or metadata refresh.

Deep scan: why do you enable it? That's probably what's causing the slowness. The documentation clearly mentions it should not be used on a permanent basis, only when asked for to perform troubleshooting.

Start there and disable it, you will get perf increase straight away..

**Comment by MKH-42** [comment]
Thanks for this tip. I tested it.
The reason why I enabled depp scan was that not all files where detected.

This is also in the documentation the hint when to enable deep scan.

But let's close this topic, maybe we can create a this again when other also find a need for this :-)
