### ISSUE TITLE
[Bug] Webui: The scroll position is not preserved in Firefox when navigating between pages

### ISSUE THREAD

**Issue by muchtea** [gotson/komga#89]
### Komga environment
- **OS**: Windows 10
- **Komga version**: v0.14.0
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: latest
- [x] **I have a problem in the web interface**
  - Browser (with version): Firefox 72.0.2 (64-bit)

### Describe the bug
The scroll position is not preserved in Firefox when navigating between pages.

### Steps to reproduce
0. Use Firefox
1. Go to a library and scroll down a little or a lot.
2. Click on a series
3. Click  the back button in Komga or the browser back button to go back to the library view.
4. The scroll position is back at the top instead of where it was before.

### Expected behavior
The scroll position should be preserved when navigating between pages.

### Actual behavior
The scroll position in the library and series views when navigating back and forth is not preserved in Firefox. It always goes back to the top.

### Additional context
In Chrome the scroll position is correctly preserved when navigating (tested in Google Chrome 80.0.3987.87).
I started Firefox in save mode and that didn't change anything, so I don't think any settings or extensions are causing the problem, probably.

**Comment by gotson** [comment]
Note that the back button in the toolbar goes back to the series, and will scroll at the top.

The browser back button is different and does restore the scroll at least on Chrome (which I'm using). I don't use any Chrome specific code for that, so I don't know what Firefox is doing there.

**Comment by muchtea** [comment]
> Note that the back button in the toolbar goes back to the series, and will scroll at the top.

I didn't know that, but the problem still exists with the browser button. However, I googled around a little the past few days and found that adding keep-alive to the router-view in `Home.vue` like this seems to fix the problem for me in Firefox:

```
    <v-content>
      <router-view/>
    </v-content>
```

to 


```
    <v-content>
      <keep-alive>
        <router-view/>
      </keep-alive>
    </v-content>
```

I, however, don't know anything about Vue, so I'm not sure, if this works as a fix or if it shouldn't be used for some reason.

**Comment by gotson** [comment]
`<keep-alive>` seems to be for something different, keeping alive components between navigation, which is not desirable as it would affect the life cycle of components.

However I just remembered I wanted to implement scroll restore when the user input the url directly. I already have the position of the max visible element in the url, I would need to use it and add some anchors to position the view. That's something I had plans to do, but got carried away doing other stuff. I think that should fix the issue on Firefox also.

**Comment by gotson** [comment]
Closing this as much has changed since, especially on pagination.
