### ISSUE TITLE
Error downloading a single file more than 2GB

### ISSUE THREAD

**Issue by gsargent70** [gotson/komga#897]
### Steps to reproduce

go to a series and then go to a single books page.  
Click download

### Expected behavior

File should download to browser

### Actual behavior

If the file is over 2GB in size it goes to a page that says

Hmmm… can't reach this page It looks like the webpage at http://10.0.0.55:9750/api/v1/books/08XPRTP7A0N8F/file might be having issues, or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

### Logs

2022-06-06 14:41:25.665 ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Content-Length exceeds ContentCachingResponseWrapper's maximum (2147483647): 3104029934] with root cause

### Komga version

v0.154.2-master

### Operating system

Linux

### Other details

Running from official docker image

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There is no limit in Komga, it's been tested with huge files by different people.

The limit may be coming from a reverse proxy installed in front of Komga.

**Comment by gotson** [comment]
After testing locally i confirm i can reproduce. Now i remember we tested huge series downloading, but not books themselves.

Series over 2gb download fine, books don't.

**Comment by gsargent70** [comment]
Thanks for confirming.  If there is anything I can do to help with fixing this I would be happy too.

**Comment by gotson** [comment]
> Thanks for confirming. If there is anything I can do to help with fixing this I would be happy too.

I know where, but I don't know why. It's part of the Spring framework, I will need some time to dig in their code.
