### ISSUE TITLE
I cant seem to give Komga enough ram. *Crashy Crashy during initial import/scan*

### ISSUE THREAD

**Issue by hanthecat** [gotson/komga#899]
### Steps to reproduce

Running: 
The latest docker gotson/komga from hub.docker.
Ubuntu 20.04.4 LTS
Linux dockers 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
This is a VM under proxmox with 16gb of ram allocated. 

I am having trouble with a number of pdf files. Some seem to scan fine while other do not. The pdf files are on an NFS mounted directory.

I ask Komga to scan the library. All analysis options are enabled.

I have tested without -Xmx and with -Xmx4g, -Xmx8g and -Xmx12g

### Expected behavior

Keep calm and scan on.

### Actual behavior

Komga fails, restarts then fails at the same file, over and over. Trouble files range in size from 6mb to over 100mb. 
Komga has successfully processed some pdfs over 200mb in size.

### Logs

Komga Log: [logs.txt](https://github.com/gotson/komga/files/8865804/logs.txt)

Server Console:
![server console](https://user-images.githubusercontent.com/18160126/172740734-d56e355e-19be-45a6-84a7-51330218e72e.png)

### Komga version

0.154.2

### Operating system

Ubuntu 20.04.4 LTS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by hanthecat** [comment]
I can upload a "good" and a "notgood" pdf. What would be the prefered location?

**Comment by gotson** [comment]
please provide the Komga logs

**Comment by gotson** [comment]
the logs are truncated, can you provide a full log from startup to crash ?

**Comment by hanthecat** [comment]
Thank you for your help!

Here is the latest rotated gzipped logfile. 
I also forgot to mention that each time the process is killed it leaves behind a lot of files in /tmp. I've seen the temp folder grow to over 100gb. A lot PDFbox*.tmp files

[komga.log.2022-06-08.0.gz](https://github.com/gotson/komga/files/8865977/komga.log.2022-06-08.0.gz)


-rw-r--r-- 1 root root  15269888 Jun  8 11:01 PDFBox912493158654041013.tmp
-rw-r--r-- 1 root root 141557760 Jun  8 16:54 PDFBox9345391528598879937.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 19:00 PDFBox9408805381525113021.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 19:41 PDFBox9480384827116988241.tmp
-rw-r--r-- 1 root root 141557760 Jun  8 16:42 PDFBox9508667401064345887.tmp
-rw-r--r-- 1 root root 141557760 Jun  8 18:21 PDFBox9603715568418738241.tmp
-rw-r--r-- 1 root root  18022400 Jun  8 20:32 PDFBox9690050244507683434.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 19:29 PDFBox9750425843606962239.tmp
-rw-r--r-- 1 root root 141557760 Jun  8 17:33 PDFBox9785537133527622602.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 19:19 PDFBox9815692069770115927.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 18:54 PDFBox982610493444744977.tmp
-rw-r--r-- 1 root root  51773440 Jun  8 19:47 PDFBox987357082771846063.tmp

**Comment by gotson** [comment]
the tmp usage is normal, the PDF library will cache the PDF streams on disk to limit RAM usage.

I have a feeling that your OS is killing the process, instead of the JVM crashing because of OOM. That's what i see in the screenshot you posted above, what is this log exactly ?

**Comment by gotson** [comment]
The komga logs don't have any `java.lang.OutOfMemoryError: Java heap space` which is what would show when the JVM has no more memory. I feel like your OS is preemptively killing the process for some reason.

**Comment by hanthecat** [comment]
I have that feeling as well. If I set the docker to not restart and I inspect the container after a stop, it does not show that it shut down OOM as you might expect.

The screenshot is just the console of the server in the hypervisor. It doesn't let me cut and paste for some reason, that's why it's a screenshot. If it didn't have a screenful of killed process errors it would just be sitting at a login: prompt.

I found this in the docker daemon log. The container number starting 6e9ef83b8c5bc matches Komga's containter.

Jun 08 20:54:55 fox dockerd[1051]: time="2022-06-08T20:54:55.976746219-04:00" level=info msg="Container failed to exit within 10s of signal 15 - using the force" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d
Jun 08 20:54:56 fox dockerd[1051]: time="2022-06-08T20:54:56.092537056-04:00" level=info msg="ignoring event" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 08 20:56:16 fox dockerd[1027]: time="2022-06-08T20:56:16.946485262-04:00" level=info msg="Container failed to exit within 10s of signal 15 - using the force" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d
Jun 08 20:56:17 fox dockerd[1027]: time="2022-06-08T20:56:17.110755532-04:00" level=info msg="ignoring event" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 08 22:07:42 fox dockerd[991]: time="2022-06-08T22:07:42.849952497-04:00" level=info msg="ignoring event" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 08 22:09:09 fox dockerd[991]: time="2022-06-08T22:09:09.613698375-04:00" level=info msg="ignoring event" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 08 22:10:29 fox dockerd[991]: time="2022-06-08T22:10:29.157102555-04:00" level=info msg="ignoring event" container=6e9ef83b8c5bc41d2512b32902f15b0c88eb554ceaf585e6ce2654da557b075d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

**Comment by gotson** [comment]
> I found this in the docker daemon log. The container number starting 6e9ef83b8c5bc matches Komga's container. No clue if it is useful.

Seems like your OS trying to stop the process. If the kill process is not honored after 10s it will force kill the process.

**Comment by hanthecat** [comment]
Seeing that the messages are on the console -- I thought maybe it was the kernel itself ---
Looking at syslog I am seeing this:

Jun  9 00:09:49 fox kernel: [11582.798770] fill_balloon: 1 callbacks suppressed
Jun  9 00:09:49 fox kernel: [11582.798772] virtio_balloon virtio0: Out of puff! Can't get 1 pages
Jun  9 00:09:49 fox kernel: [11583.020069] virtio_balloon virtio0: Out of puff! Can't get 1 pages
Jun  9 00:09:49 fox kernel: [11583.233674] virtio_balloon virtio0: Out of puff! Can't get 1 pages
Jun  9 00:09:49 fox kernel: [11583.441943] virtio_balloon virtio0: Out of puff! Can't get 1 pages
Jun  9 00:09:50 fox kernel: [11583.661821] virtio_balloon virtio0: Out of puff! Can't get 1 pages
Jun  9 00:09:50 fox kernel: [11583.889599] virtio_balloon virtio0: Out of puff! Can't get 1 pages

The VM doesn't have any defined swap. Perhaps that's the issue. While I test that, I attached part of syslog around when Komga is killed.

Syslog: [syslog.txt](https://github.com/gotson/komga/files/8866744/syslog.txt)

**Comment by hanthecat** [comment]
If I am reading this right, swap space belongs on the host, not the VM. I had that set up correctly. So as a test I disabled ram ballooning and -- wow.. Komga is behaving really well now. No OOM killing, no high load averages. Scanning and hashing new pdfs just fine, even all the ones it refused to before. The docker always seemed to be killed around PDFBox, perhaps that's the part of the package that doesn't play nicely with ram ballooning in a qemu vm?

This just goes to show you, that when you're having an issue that google is telling you that no one else is having, it's not paranoid to think that it's only you!

**Comment by gotson** [comment]
Docker in a vm is a weird choice to start with 🙃

Is that fine to close the issue then?

**Comment by hanthecat** [comment]
Sure, why not? A VM is easier to backup. Closing is fine. I am just happy this is documented in case it comes up for others.
