### ISSUE TITLE
[Feature Request] Disregard sub-folders structure, and only use metadata for organizing series

### ISSUE THREAD

**Issue by befuddled-dude** [gotson/komga#907]
### Describe your suggested feature

(Apologies if this is a dupe. I searched a bit but didn't find this)

I have a bunch of folders full of North American comics that are not very organized by series, but most by date, and some other areas of 'grouped' folders, but not very hard-and-fast by series.  Almost 100% of the files do have ComicInfo.xml metadata that are very well populated with series name, issue number, publisher, creators, etc. 

Unfortunately, Komga expects all subfolders to homogeneous, containing only issues of one given series.  I see that that is by design, based on the docs (https://komga.org/guides/scan-analysis-refresh.html#what-happens-during-a-scan).  

So in my folder with a mix of different series, Komga chooses the series from one of the files (from the metadata, I think) that it decides is the correct series for all books in that folder.

Here's a screenshot of an issue of Invincible mixed into a folder with a few issues of The Walking Dead

![image](https://user-images.githubusercontent.com/3521270/174455896-72a9911a-8e36-403a-a986-f464a42ddc93.png)

Clearly all the metadata is getting parsed, and the only problem seems to be the series name.

My feature request that there be an option for the library to not use the subfolder structure at all, and only use the comic file metadata for organizing series.

I haven't looked at the code at all, so I have no idea if the concept of "one series to a subfolder" is really baked into Komga or not, so I can't guess at how complex this feature would be, but I hope you consider it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's been discussed a few times before, this is not something that will happen. Komga is based on 1 folder = 1 series.

**Comment by befuddled-dude** [comment]
OK, thanks for the reply, and understand that you're not going to change your mind. Just out of curiosity, may I ask why, though?  Is it because of the way Komga is architected, and it's just not a reasonable thing to do without a massive redesign?

**Comment by gotson** [comment]
Yes, and because that's how most people store their comics, and also because Komga aims to work the same whether you have metadata or not. If you don't have any, it would show something to your folders, while still allowing to add metadata if you want.
