### ISSUE TITLE
[Windows] komga use 3gb of ram

### ISSUE THREAD

**Issue by Bazzu85** [gotson/komga#912]
### Steps to reproduce

Hi, as title I'm writing because of too much ram used..

these are my metrics:
![image](https://user-images.githubusercontent.com/7345587/176795396-b46e6729-9e58-4d1e-8dd0-52af26537b40.png)

I use a bat with this command:
`java -jar komga.jar --server.port=5001 --komga.remember-me.key="xxxxxxxxxxxx" --komga.remember-me.validity=365d --komga.config-dir="n:\Komga\config"`

this is my memory consumption right after starting the server:
![image](https://user-images.githubusercontent.com/7345587/176795608-a8cc9e38-3a23-465f-8f5c-125b98563160.png)

what described here
https://komga.org/installation/jar.html
is not helpful as I have not OutOfMemoryException..
why is komga using so much of ram?
thx

### Expected behavior

use lesser ram

### Actual behavior

too much ram used!

### Komga version

v0.155.0-master

### Operating system

Windows 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DieselTech** [comment]
https://komga.org/faq/#the-memory-consumption-is-huge
