### ISSUE TITLE
Chapters .5 Wrong Positions for MANGA

### ISSUE THREAD

**Issue by L4stix** [gotson/komga#914]
### Steps to reproduce

![immagine](https://user-images.githubusercontent.com/101519626/177051377-183cbfc6-c03f-4452-b818-9e0642a54c0a.png)

![immagine](https://user-images.githubusercontent.com/101519626/177050477-75070ba3-728f-4aee-9a1e-3e4f0d96fd33.png)

it is possible to solve the problem of chapters .5 within the volumes that are placed before and not after in the reader as it should be (sorted correct above)⬆⭕

### Expected behavior

![immagine](https://user-images.githubusercontent.com/101519626/177051324-7d9917c7-60c9-4389-8de9-5e24dd08793e.png)

Chapter 22 Pag. 79 ⬆⭕ (Reader page 84)

![immagine](https://user-images.githubusercontent.com/101519626/177051273-8b7c4942-480c-4d69-b692-97b54429463a.png)

Chapter 23 Pag. 119⬆⭕ (Reader page 127)

![immagine](https://user-images.githubusercontent.com/101519626/177051288-0934d9c6-70fb-469e-8e44-b2b48d6ac464.png)

Chapter 23.5 Pag. 157⬆⭕ (Reader page 168)

### Actual behavior

![immagine](https://user-images.githubusercontent.com/101519626/177051312-59531ba7-01b2-40e3-8fb1-3cf1b71aee3c.png)
Chapter 22 Pag. 79 ⬆⭕ (Reader page 84)

![immagine](https://user-images.githubusercontent.com/101519626/177050719-0e43b91b-30ec-4d95-8bb2-8615b75c0922.png)
Chapter 23.5 Pag. 157⬆❌ (Reader page 127)

![immagine](https://user-images.githubusercontent.com/101519626/177050809-54ef1e66-bcb2-48ee-9e4f-00df50536fe1.png)
Chapter 23 Pag. 119⬆❌ (Reader page 138)

As you can see from the screens provided, chapter 23.5 has been inserted between chapter 22 and chapter 23 when the true order is chapter 22, chapter 23 and chapter 23.5 (as per the second official screen page of the index of volume 6)

### Komga version

0.155.0

### Operating system

Windows 10 Pro - 64bit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga will assign a sort number for each book, based on the order in the directory. You can edit the sort number to whatever you want to handle corner cases like .5 chapters, negative issues, specials etc.

The reader will follow the order that is defined by the different sort number of the books in the series.

**Comment by farahnur42** [comment]
I'm fairly certain that the view in the screenshot is just them opening the volume (likely a zip file) in Explorer and the volume itself just has nested chapter folders (because Komga doesn't support individual folders with images inside them for "books"). So ideally the solution here would be to not have nested chapter folders within volumes but the reader is still technically not handling sorting correctly.

@L4stix Is my assumption here correct or not?

**Comment by gotson** [comment]
Folders are irrelevant, if filenames within a zip are ordered, then it will display pages in order.

**Comment by farahnur42** [comment]
So just to rule a hunch out I've tried replicating this on my end by A/B-testing a book with the same exact contents, the same 5 chapters from a given title with one .5 chapter in folders zipped up but one archive has zero-padded folder names, and the other does not (similar to the first screenshot from the original issue creator) - and both of them work as expected in the Komga reader. I'll test if removing zero-padding from the filenames *within* those folders changes anything in a bit although if it only affects the extra chapter then I can't really think of a reasonable way to replicate that (maybe I'll test with removing zero-padding for only that extra chapter).

**Comment by L4stix** [comment]
No, the problem is not in the ordering of the chapters on Komga but inside the volume (inside the .zip).
For Komga, a "volume 01.zip" with structure: 
```
Volume 01.zip > 

                         Volume 1 >

                                               Capitolo 001 >
                                                                    xx1.png
                                                                    xx2.png
                                                                    xx3.png
                                               Chapter 002 > 
                                                                    xx1.png
                                                                    xx2.png
                                                                    xx3.png
                                               Chapter 002.5 > 
                                                                    xx1.png
                                                                    xx2.png
                                                                    xx3.png
                                               Chapter 003 > 
                                                                    xx1.png
                                                                    xx2.png
                                                                    xx3.png
                                               
```
The Komga reader, sorts all PNG/JPEG in "Chapter 002.5" folder before the "Chapter 002" folder instead of after.

Temporary FIX - https://mega.nz/file/APBxhJyS#1T3kquYe8teYoVmx92hOwXgk0D0Jz-OQTWBY0MNmX1o

Problematic version for Komga  - https://mega.nz/file/FSATyLAQ#j08HcCIBU8A4HgUq94FtUKUp97wWB1zST3m19NV6GOo

**Comment by awh-tokyo** [comment]
I've had a similar problem with a different book and a different reader.  In that case, Komga handled them properly, but Panels (iOS reader) did not order them properly.  Basically the problem is that different OSes (and different locale collation settings) handle the sort order of files differently.  That is, for example, sometimes É will sort alphabetically after E and sometimes it will sort after Z.  Similarly, sometimes the sort order is ABC...Zabc...z and sometimes it's AaBbCc...Zz.

In this case, the problem is whether "." sorts before or after "[end of string]".  Even that is down to the locale settings.

I've found that the only real way to make sure books work correctly across the board is to name them with the page number **first** and then everything else afterwards (it's such a common problem for me that I've got scripts to do this all automatically).  

That said, all my books are "one directory with a bunch of files in them."  If you really want to have them in separate chapter folders like this, I'd suggest something like:

0010 Chapter 1
0020 Chapter 2
0030 Chapter 3

And then if Chapter 2.5 gets released later on, you can name that "0025 Chapter 25"

The big problem here is that all of the comic book formats rely on sorting images by the OS, but OSes (and locale packs) can't agree on what sort order is, so until some standard can be agreed upon to explicitly lay out pages in the metadata, the only real solution is to name the pages so the sort order is absolutely unambiguous.

**Comment by gotson** [comment]
Komga uses a natural sort algorithm to sort entries in the zip. Those algorithms have their limits, as @awh-tokyo mentioned above.

The best way is to make it unambiguous is to avoid nested folders and have filenames that will sort easily on any system, for example by using leading zeroes.

**Comment by zFerry98** [comment]
I see a question on this case and AGAIN your answer is that you give a damn about it and pass it on to other people...
BUT DID YOU LOOK AROUND BEFORE YOU SPEAK?

# THE FUCKING WORLD IS RELEASING MANGA WITH THIS PORK GOD OF LAYOUT AND YOU DON'T GET IT ?? ARE YOU KIDDING ME?!

REMOVE THIS APPLICATION SHIT THAT IS ALSO A MANGA SERVER!!!! YOU ARE NOT RESPECTING FUCKING HOW MANGAS WORK AND YOU ARE FORCE SHIT COMICS ON MANGA. OPEN ANY OTHER MANGA SERVER AND LEARN FROM THEM TO IMPLEMENT THE MINIMUM BASES!!

**Comment by zFerry98** [comment]
I see a question on this case and AGAIN your answer is that you give a damn about it and pass it on to other people...
BUT DID YOU LOOK AROUND BEFORE YOU SPEAK?

# THE FUCKING WORLD IS RELEASING MANGA WITH THIS PORK GOD OF LAYOUT AND YOU DON'T GET IT ?? ARE YOU KIDDING ME?!

REMOVE THIS APPLICATION SHIT THAT IS ALSO A MANGA SERVER!!!! YOU ARE NOT RESPECTING FUCKING HOW MANGAS WORK AND YOU ARE FORCE SHIT COMICS ON MANGA. OPEN ANY OTHER MANGA SERVER AND LEARN FROM THEM TO IMPLEMENT THE MINIMUM BASES!!

**Comment by hgourvest** [comment]
the problem comes from the separator "/", its numerical value is 47 in the ascii table while the "." has the value 46. The string comparator should consider that this separator is smaller than any other character, so the folder with a shorter name will appear before.

**Comment by L4stix** [comment]
> the problem comes from the separator "/", its numerical value is 47 in the ascii table while the "." has the value 46. The string comparator should consider that this separator is smaller than any other character, so the folder with a shorter name will appear before. Just override the "compareChars" function of the "CaseInsensitiveSimpleNaturalComparator" class.
> 
> ```
>   @Override
>   int compareChars(char c1, char c2) {
>     if (c1 == '/') c1 = 0;
>     if (c2 == '/') c2 = 0;
>     return Character.toLowerCase(c1) - Character.toLowerCase(c2);
>   }
> ```

finally someone who really understands programming that explains to the creator that the problem lies in his code and not in the naming of the files and in the nested folders (which manga have because if one downloads the individual chapters it is not moving the png/jpg to create a single volume without nested folders).

**Comment by L4stix** [comment]
> 

it's true, it's all open source and he works on it when in time, but, he can't answer my request to try to solve the problem that I explained step by step with the attached files also saying that there is no problem in the sorting in the its reader and say that the problem lies in nested folders. The disrespectful one here looks like him saying his program is done right and he has no problems when he actually has them. (I'm not trying to be disrespectful or insult anyone).

**Comment by hgourvest** [comment]
what is good with open source is that you can solve your problem yourself, look at my fork, I tested a fix in a branch.
