### ISSUE TITLE
Respect the folder structure

### ISSUE THREAD

**Issue by lylmiksistemas** [gotson/komga#916]
### Describe your suggested feature

Now Komga will create a Series for each subfolder of any library, whatever the depth of this subfolder in your directory structure, please respect the folders structure.

For example: 

Level 1: Marvel
Level 2 : Captain America
Level 3: Vol 1
Level 3: Vol 2
Level 3: Vol 3
Level 3: Specials

For example my library of DC comics in Spanish are 1481 series,  a list of 1481 items is not useful.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
There's no plan for that.
