### ISSUE TITLE
Change preset author field names.

### ISSUE THREAD

**Issue by Shakahron** [gotson/komga#917]
### Describe your suggested feature

It would be mega handy to be able to change the preset author fields like writer, inker, editor etc. to something else. I use those fields in ComicInfo files to fill in extra information I can't fit anywhere else, it can be a bit cumbersome with the naming schemes though.
![firefox_siRT3QOcrZ](https://user-images.githubusercontent.com/106402227/177409153-b35c9317-7ce3-49d8-9c7d-671d74458ae9.png)
![firefox_xzVWkwGMSU](https://user-images.githubusercontent.com/106402227/177409164-6cec9b27-b530-4e7a-b4a3-a39f15c4b5ce.png)
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's not the intended usage.
