### ISSUE TITLE
Can I select text in PDF file in Webreader?

### ISSUE THREAD

**Issue by EvgeniyDoctor** [gotson/komga#918]
### Describe your suggested feature

Is there a way to select text in PDF?
I use Komga with my PC, not phone or tablet.

### Other details

Komga: v0.155.0-master in Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
No. Komga handles images, not text, so pdf pages are rendered as images.
