### ISSUE TITLE
Preload next chapter in series

### ISSUE THREAD

**Issue by stonechitlin** [gotson/komga#922]
### Describe your suggested feature

I have a rather large library in Komga, so when it does a scan komga slows down to a crawl. An idea occurred to me to make this more user friendly, in that if reading a series, if komga could somehow prefetch or prioritize the next chapter in the currently reading series, utilizing the time spent reading to load that next chapter in advance.

This would give a much more fluid feeling to the user even during the heavy compute times of library scanning.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand what this is about. You mention preloading, which I would understand is about the webreader, but you also mention scanning, which has nothing to do with the webreader.

Can you clarify?

**Comment by gotson** [comment]
I don't understand what this is about. You mention preloading, which I would understand is about the webreader, but you also mention scanning, which has nothing to do with the webreader.

Can you clarify?

**Comment by stonechitlin** [comment]
Sorry, the reason I mention scanning, is that when komga is scanning, the webreader slows down. 

This is the reason for the idea to preload the next chapter for the webreader so that from a user perspective it doesnt feel as slow during the scanning process thats happening in the background.

**Comment by gotson** [comment]
Scanning in itself shouldn't be very slow, but analyzing new or modified books could be.

**Comment by stonechitlin** [comment]
That could certainly be it, as I usually run a scan when adding new things to the library. And this could be unique to me as I have about 1.7 tb and 900 series in my largest manga library.

I just notice during that task how much things slow down hence the feature request.

**Comment by gotson** [comment]
Which version were you running at the time?

**Comment by stonechitlin** [comment]
Either v0.155.0 or v0.155.1

I try and stay as up to date as possible. I am currently on v0.155.3. It does feel snappier even under heavy tasks though I believe from v0.155.2.

**Comment by gotson** [comment]
You could give a spin to SQLite WAL mode with the latest `0.156.0` by setting: `komga.database.journal-mode` to `WAL`.

**Comment by stonechitlin** [comment]
Not too familiar with WAL mode, but doing some homework, I have a slight concern, how often is komga integrating checkpoints?

via https://www.sqlite.org/wal.html
"Checkpointing does require sync operations in order to avoid the possibility of database corruption following a power loss or hard reboot. The WAL must be synced to persistent storage prior to moving content from the WAL into the database and the database file must by synced prior to resetting the WAL. Checkpoint also requires more seeking. The checkpointer makes an effort to do as many sequential page writes to the database as it can (the pages are transferred from WAL to database in ascending order) but even then there will typically be many seek operations interspersed among the page writes. These factors combine to make checkpoints slower than write transactions.

The default strategy is to allow successive write transactions to grow the WAL until the WAL becomes about 1000 pages in size, then to run a checkpoint operation for each subsequent COMMIT until the WAL is reset to be smaller than 1000 pages. By default, the checkpoint will be run automatically by the same thread that does the COMMIT that pushes the WAL over its size limit. This has the effect of causing most COMMIT operations to be very fast but an occasional COMMIT (those that trigger a checkpoint) to be much slower. If that effect is undesirable, then the application can disable automatic checkpointing and run the periodic checkpoints in a separate thread, or separate process."

Also, is there a way to force a checkpoint, for example I need to restart my pc or even just shut down komga in order to update it, so can I run some type of command to ensure everything is synced and that I will not lose data?

**Comment by gotson** [comment]
> Not too familiar with WAL mode, but doing some homework, I have a slight concern, how often is komga integrating checkpoints?

the default.



> Also, is there a way to force a checkpoint, for example I need to restart my pc or even just shut down komga in order to update it, so can I run some type of command to ensure everything is synced and that I will not lose data?

the journal is kept on disk, a reboot should not have impact

**Comment by stonechitlin** [comment]
ah, so really, its a non issue then. the wording on that doc had me concerned that the file was volatile (like something stored in ram only)

**Comment by gotson** [comment]
I made an enhancement to allow any [SQLite pragma](https://www.sqlite.org/pragma.html) ([supported by the JDBC driver](https://github.com/xerial/sqlite-jdbc/blob/3d04d7df0c89240add2c92189adb30b6cb7e6ae0/src/main/java/org/sqlite/SQLiteConfig.java#L354)) to be passed easily by the Komga configuration.

For example:
```yml
komga:
  database:
    pragmas:
      page_size: 1024
      synchronous: OFF
```

Those are examples only, changing the pragmas will have effect on the database! Some could lead to data corruption if misused.
