### ISSUE TITLE
Reader overlay and page turning

### ISSUE THREAD

**Issue by primetoxinz** [gotson/komga#93]
In the reader, currently you can change the page by using the left and right clickable zones.

Yet if the overlay menu is up, the clickable zones can't used because the overlay elements are on top. 
Is this intentional?

If it is intentional that the page-turning zones don't work with the overlay, then what would you think about making those zones close the menu? This will make closing the overlay easier on a mobile device, rather than having to click the very small X button.

**Comment by gotson** [comment]
The overlay menu is mostly inspired by the one from Ubooquity, but I am not fond of it at all. The webreader was mostly done for browsers, as mobile users can use apps, either OPDS readers or Tachiyomi for Android. Thus the overlay is not responsive enough for smaller screens.

I am thinking of scrapping it completely and redoing something better, in line with material design, that would work both on large screen desktops and smaller screens.

**Comment by gotson** [comment]
superseded  by #102
