### ISSUE TITLE
[Feature Request] Always preload/prefetch the next few pages in the webreader

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#932]
### Describe your suggested feature

Currently, if you read a manga in the webreader, every time you switch to the next page, there's a delay between the action of switching to the next page and actually seeing the next page because the client always downloads it on-demand. The webreader experience could be made more smooth/seamless by eliminating this delay. One way to achieve this would be to always preload/prefetch the next few pages whenever you switch to the next page.

### Other details

The solution I proposed is used in production e.g. by the webreader [Cubari](https://github.com/subject-f/cubarimoe) ([example](https://cubari.moe/read/imgur/IS756yu/1/1/)), If you look at the Network tab in DevTools, you can see that it always loads the next couple of pages when you turn a page. On MangaDex, meanwhile, the entire chapter is prefetched/preloaded ahead of time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
This is already done for a long time, you can verify this in the network tab too.

**Comment by whalehub** [comment]
@gotson Unfortunately, that does not appear to be the case. When I open a chapter, the first six pages are preloaded, but after that, all pages are loaded on demand. You can see what it looks like on my end [here](https://xbb.datahoarder.dev/VUSu3/xiduwaTo28.mp4).

**Comment by gotson** [comment]
@whalehub i can't see which page you're on, but the webreader always loads a few pages before/after the current one.

See [here](https://imgur.com/a/vSHibl6) on the demo, with page number showing, you can clearly see it preloads.
