### ISSUE TITLE
Scroll speed control to webtoon reader mode

### ISSUE THREAD

**Issue by Enrique-Venegas-A** [gotson/komga#936]
### Describe your suggested feature

When reading in webtoon mode (or whatever else it applies to), it would be useful to be able to control the scroll speed of the down/up keys, this would be fantastic for when a mouse/touch screen are not available, I can see it as a slider or a 1 to 10 multiplier.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
It's entirely controlled by your browser.

**Comment by Enrique-Venegas-A** [comment]
> It's entirely controlled by your browser.

Hello,

When started to google for a way to do it, I realized that I probably didn't use the right words for what I meant and there might be a confusion.

I meant this:
https://stackoverflow.com/questions/18564561/how-to-specify-how-many-pixels-scroll-moves-on-each-step

working example here, set "step" variable to change the amount of steps for each scroll:
http://jsfiddle.net/skmasq/mP974/

**Comment by gotson** [comment]
In the first message you mention the speed of the up/down key, while in the second message it's all about the step of the mouse wheel.

**Comment by Enrique-Venegas-A** [comment]
> In the first message you mention the speed of the up/down key, while in the second message it's all about the step of the mouse wheel.

Hello,

The second message was to demonstrate the action I meant in the beginning, that it was not "entirely controlled" by the browser, in the example I mentioned "each scroll" to be clearer about what you could expect opening the link.

In the example it's binded to the 'mousewheel', but you can bind that to any other key, the important part is the function that does the action itself.
