### ISSUE TITLE
Add links to series metadata

### ISSUE THREAD

**Issue by PhilippKammann** [gotson/komga#938]
### Describe your suggested feature

(Similar to #750 but for the series view)

Adding a button/clickable link to open websites associated with the series (Comicvine, Anilist, MyAnimeList etc.)
Similar to the 'Link' tab in the book editing dialog.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
But there's no links at the series level in the metadata.

**Comment by PhilippKammann** [comment]
There are other Komga-exclusive metadata fields - for example Tags - that are not populated by a _ComicInfo.xml_ or _series.json_.
So that could be a new Komga-exclusive field.

**Comment by gotson** [comment]
I'm not sure to understand what's the request, as series do not have links as part or their metadata.

Is this to add links in the series metadata, like books have ?

**Comment by PhilippKammann** [comment]
Yes. The exact same a for books. 
A link in the book will point to the book on Comicvine and a link in the series will point to the series on Comicvine for example.

The request would be to be able to add these links to the series metadata the same way as you can add link to book metadata
