### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by ghost** [gotson/komga#939]
### Describe your suggested feature

I have many service in my server, and they're using LDAP for auth, If Komga have LDAP support that make user in my server login easily

### Other details

Look up Spring Support https://spring.io/projects/spring-ldap

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by DaiYuANg** [comment]
I am happy to contribute for this issue

**Comment by RatCornu** [comment]
Is there any news or plan on this issue ?

**Comment by Tiagoez** [comment]
😡
