### ISSUE TITLE
Hide or Remove Selected Pages

### ISSUE THREAD

**Issue by TleTuNag** [gotson/komga#943]
### Describe your suggested feature

hello.
I am using Komga very well.

I currently have a book that contains unnecessary pages.

To remove these pages

1. Find a book path (or download a book from Komga)
2. unzip the book
3. delete page
4. recompression
5. replace the original
6. analyze book

etc.

It requires cumbersome work.

So I want the webui to do that.

Thanks for all your work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Duplicate of #800
