### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by ytak01** [gotson/komga#952]
### Steps to reproduce

1,Comic is Download
2,Show ErrorPage
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 18 13:04:15 JST 2022
There was an unexpected error (type=Not Acceptable, status=406).
Could not find acceptable representation

### Expected behavior

Comic is download

### Actual behavior

ErrorPage

### Komga version

0.157.0

### Operating system

Windows11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand much of what you wrote. Can you provide logs ?

**Comment by ytak01** [comment]
sorry
I attach the lo
[komga.log](https://github.com/gotson/komga/files/9367968/komga.log)
g

**Comment by gotson** [comment]
Could you provide the details for the failing API call, via the [Network dev tool](https://developer.chrome.com/docs/devtools/network/#details) of your browser ?

The API call that fail should be shown in red, and the path should be something like `https://<your-server>/api/v1/books/09MYD1VJBCMSV/file`.

I would need details from both the Request and Response tab.

**Comment by ytak01** [comment]
![2022-08-18 15_57_38-Window](https://user-images.githubusercontent.com/1092622/185324100-ca084ed7-19c2-40e2-ab0b-49469f70a449.png)
Request and Response tab.?

**Comment by gotson** [comment]
click on `file` and it will show more content on the right with more tabs.

**Comment by gotson** [comment]
Do you have some browser extensions ? I see that the request is initiated by `turbolinks.js`.

Can you try to disable all extensions, and try again?

**Comment by ytak01** [comment]
Thank you for your reply.

I removed Adblock and now I can download.

thank you
