### ISSUE TITLE
bottom pagination hidden by navigation bar on some display breakpoints

### ISSUE THREAD

**Issue by billsargent** [gotson/komga#953]
### Describe your suggested feature

Pagination navigation exists at the top of listed books, but not at the bottom. If you scroll to the bottom of a big list, you need to scroll all the way back to the top to go to the nxt page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
I don't understand as this has been implemented in #305 already

**Comment by billsargent** [comment]
You're absolutely right. On my tablet in android it does not though. I'm on my laptop right now and it shows up just fine.

**Comment by gotson** [comment]
It's made to always show, it doesn't depend on the viewport size.

**Comment by billsargent** [comment]
![image](https://user-images.githubusercontent.com/32219940/185407430-8f969ca1-7d3d-4197-ab76-28c1b331b312.png)
Top...

![image](https://user-images.githubusercontent.com/32219940/185407523-ec6f9cb8-15e5-4d32-89fc-625869ac10bb.png)
Bottom

**Comment by gotson** [comment]
Maybe try basic troubleshooting: use a different browser, clear the cache, try in desktop mode, check on another device

**Comment by billsargent** [comment]
It's the same in Kiwi browser and Opera.

**Comment by gotson** [comment]
what's your tablet ?

**Comment by billsargent** [comment]
Samsung Galaxy Tab A7. 
SM-T500 running Android 12 with One UI 4.1

**Comment by gotson** [comment]
I have a Samsung Galaxy S21, and a Samsung Galaxy Tab S5E, none have the problem.

**Comment by billsargent** [comment]
I will continue to investigate.

**Comment by billsargent** [comment]
When i switch to "Desktop site" in Chrome and Kiwi (I think Kiwi is based on the Chromium engine), i see the pagination at the bottom

**Comment by billsargent** [comment]
Same in Opera. With the desktop and not mobile site, it shows up.

**Comment by gotson** [comment]
I managed to reproduce with the Chrome dev tools, simulating an iPad Air.
