### ISSUE TITLE
Comixology no longer exists, Komga still links to it.

### ISSUE THREAD

**Issue by nstephenh** [gotson/komga#954]
### Steps to reproduce

Import Library
Click on comic
See link in links section
Click Link

### Expected behavior

Taken to comixology
https://www.comixology.com/Star-Wars-Bounty-Hunters-2020-25/digital-comic/994947

### Actual behavior

Redirected to amazon's generic comics page:
https://www.amazon.com/kindle-dbs/comics-store/home?_encoding=UTF8&merchant=&ref=nav_ya_signin&#nav-top

### Komga version

0.157.0

### Operating system

FreeBSD (TrueNas Jail) TrueNAS-13.0-U1.1

### Other details

I think the issue is that amazon has retired comixology? If so, the links should be removed and re-implemented later with actual amazon links.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by nstephenh** [comment]
If this is a link that exists in the comic's metadata, my apologies. I didn't put it there and assumed this was metadata pulled by Komga from elsewhere.

**Comment by gotson** [comment]
> If this is a link that exists in the comic's metadata, my apologies. I didn't put it there and assumed this was metadata pulled by Komga from elsewhere.

It is indeed, coming from your `Comicinfo.xml`. Fix your metadata to fix the links.
