### ISSUE TITLE
allow docker preprocessing script

### ISSUE THREAD

**Issue by mybuntu-git2** [gotson/komga#957]
### Describe your suggested feature

I would like to be able to run komga with docker-compose and a preprocessing script specified within the yml.
this could allow to centralise orchestration of other sanity checks or metadata fetching flows, from within the docker yml of komga, when restarting it.

I think about this because my data dir is mounted so I want to run sanity checks before komga starts but guess could be used for other stuff as well, e.g. format conversions, metadata fetch, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
To make sure that the dirs are mounted you should use something outside the container, like a systemd dependency of the docker service to the nfs service for example.

You can also build your own docker image with custom scripts if you want.

**Comment by mybuntu-git2** [comment]
I did not think about the systemd solution, thanks. I'll close the request because the explanation actually fulfils the need.
