### ISSUE TITLE
Add iOS Homescreen Friendly Icon

### ISSUE THREAD

**Issue by electblake** [gotson/komga#959]
### Describe your suggested feature

After using a bunch of OPDS readers on my ipad, I found myself using komga server directly in Safari - even easier is adding it to my homescreen as an "App"

Currently the icon is a circle which looks less pretty (black background in corners)

Could you add a single HTML meta tag for ios icon and tailor logo for it? (square icon vs circle logo), something similar to:

```html
<link rel="apple-touch-icon" href="touch-icon-iphone.png" />
<link rel="apple-touch-icon" sizes="72x72" href="touch-icon-ipad.png" />
<link rel="apple-touch-icon" sizes="114x114" href="touch-icon-iphone4.png" />
<link rel="apple-touch-icon" sizes="144x144" href="touch-icon-retina-ipad.png" />
```

Thanks for komga! keep it up!

### Other details

https://stackoverflow.com/questions/20440512/why-use-link-rel-apple-touch-icon-image-src for some reference, simple enough

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by darthmooguy** [comment]
It's already been done in the latest release. https://github.com/gotson/komga/releases/tag/v0.157.1

You need to remove and re-add the shortcut to your home screen for the icon to update!
