### ISSUE TITLE
[Bug] Sub Folders Not Being Created As Series

### ISSUE THREAD

**Issue by spslater** [gotson/komga#96]
### Komga environment
- **OS**: Ubuntu 18.04.3 LTS
- **Komga version**:  komga-0.14.1.jar
- **Java version**: 
  - openjdk 11.0.6 2020-01-14
  - OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
  - OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
- **Browser (with version)**: Firefox 72.0.2 (64-bit)

### Describe the bug
When I add a new library, it is only importing the files in the selected root folder and not created series based on the sub folders. 

### Steps to reproduce
1. Add a new library with sub folders. 

### Expected behavior
The sub folders are added as series to the library.

### Actual behavior
Only the files not in sub folders are added as one series.

### Additional context
Example:
```
Comics/
├── Private Eye/
│   ├── Volume 1.cbz
│   └── Volume 2.cbz
└── One Shot.cbz
```

In this case, only `One Shot` is being created in a series called Comics, but the `Private Eye` series is not being created.

### Log file
https://gist.github.com/spslater/a3962c313998872ccaf0e29e09db278d

**Comment by gotson** [comment]
Hi, could you please provide:

- a text file describing your directory structure. Using `bash` you can use `find $(pwd)` from the directory containing your library.
- the complete log file of Komga. If you can provide the log file of the run when you add the library, so i can see the complete information about the can.

**Comment by spslater** [comment]
[comics.log](https://github.com/gotson/komga/files/4222707/comics.log)
[komga.log](https://github.com/gotson/komga/files/4222709/komga.log)

**Comment by gotson** [comment]
That's very weird. I don't know what's happening. I'll add some debug logs in the `FileSystemScanner` and ship a new version so we can track better what's going on.

**Comment by gotson** [comment]
Could you try v`0.14.2` and set the configuration `logging.level.org.gotson.komga` to `TRACE`, and post the `komga.log` here?

**Comment by spslater** [comment]
Sorry for the delay, was in the middle of moving. Where would I set the log level? Does it go in the `application.yml` file or somewhere else? And should I still use the 0.14.2 version? or the latest version (0.16.4)?

**Comment by gotson** [comment]
You can set the config either in `application.yml` or environment variables (as mentionned [here](https://komga.org/configuration/)).

You can use any version up from `0.14.2`, so the latest will do.

**Comment by spslater** [comment]
[komga.log](https://github.com/gotson/komga/files/4294402/komga.log)

Here's the log from when running version 0.16.4

**Comment by gotson** [comment]
could you advise whether you are using the `jar` or `docker` method to run Komga ?

If using the `jar` could you provide the output of the command `java -version`, along with which Operating System you are using, and on which kind of mount your comics are located (NFS, Samba, directly on the disk of your OS...).

**Comment by spslater** [comment]
I'm using the jar method. 
```
java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

uname -a
Linux fayette 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a                                                                                                                          uniontown@fayette
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
``` 
The comics are saved on mounted drives, different one than the OS, but physically in the same computer (attached via SATA or USB)

**Comment by gotson** [comment]
The `walk` method in the scanner doesn't seem to go into subdirectories, even before any filtering or anything is applied.

The `TRACE` log `GetSeries` should be displayed for each and every file and folder in th library. For you it just stops at the top directory. 

Could you check the permissions of the directory tree to make sure it's traversable by the user running Komga? 

Could you also try to add a subset of the library on the local drive, and try to add that as a library?

**Comment by spslater** [comment]
It seems like it's having issues with symlinks. I created a library on the local drive, with a series inside of it, and that worked as expected. I then created a symlink to the library that worked in the same folder and it wasn't picking up the series inside of it. 

So the way it's layed out below, the `test` library is working and has the 3 expected series: `test`, `Gotham Academy`, and `Gotham Girls`. While the `four` library only has the `four` series. 

``` 
.
├── application.yml
├── comics.log
├── four -> test
├── komga-0.16.4.jar
├── komga-database.h2.mv.db
├── komga.log
└── test
    ├── 1602 Witch Hunter Angela 1 (of 4).cbz
    ├── Action Comics (Vol 1) 957.cbz
    ├── Agents of Atlas 1 (of 1).cbz
    ├── Attack on Titan v01.cbz
    ├── Extraordinary X-Men (Vol 1) 001.cbz
    ├── Fade Out, The (Vol 1) 001.cbz
    ├── Gotham Academy
    │   ├── Gotham Academy (Vol 1) 001.cbz
    │   ├── Gotham Academy (Vol 1) 002.cbz
    │   ├── Gotham Academy (Vol 1) 003.cbz
    │   ├── Gotham Academy (Vol 1) 004.cbz
    │   ├── Gotham Academy (Vol 1) 005.cbz
    └── Gotham Girls
        ├── Gotham Girls 1 (of 5).cbz
        ├── Gotham Girls 2 (of 5).cbz
        ├── Gotham Girls 3 (of 5).cbz
        ├── Gotham Girls 4 (of 5).cbz
        └── Gotham Girls 5 (of 5).cbz
```

**Comment by gotson** [comment]
Indeed, the scanner only picks up directories: https://github.com/gotson/komga/blob/dcba8f18bbe5d07f3c511916c2ba6c8cfa79887d/komga/src/main/kotlin/org/gotson/komga/domain/service/FileSystemScanner.kt#L42

How extensively do you use Symlinks, and is there a way not to use them ?

Adding symlinks support could prove complex:
- it could generate recursive situations
- the real path of the symlink would be outside the library path, meaning another library could be added and some items would end up with the same URL, which is used to find items to update

**Comment by spslater** [comment]
It's just to the library directory itself so I can have it organized nicely in my home folder instead of the /mnt folder. It's a super easy fix. Thanks.

**Comment by gotson** [comment]
Thanks, i'll close the issue for now then !

**Comment by gotson** [comment]
Actually i checked and found where it could add a `follow links` option, which works and doesn't use real paths. That works with the case you mention. I'll add a fix, check for when this issue will be `released` if you want to use it !
