### ISSUE TITLE
bdgest.com / bedetheque.com to be added as a scrapper

### ISSUE THREAD

**Issue by Flyingfufu** [gotson/komga#97]
Is your feature request related to a problem? Please describe.
ComicVine do find only few of my ebooks

Describe the solution you'd like
I would love to see bdgest.com / bedetheque.com to be added as a scrapper. It would add approx. 40.000+ series, 260.000+ albums.

Describe alternatives you've considered
Here seems to be a possible solution (I hope) : https://github.com/givka/bedetheque-scraper/

Thanks for your work !
Regards,

**Comment by gotson** [comment]
Hi, bedetheque and appbubble are the 2 candidates for metadata, as mentionned in #11. There is however a concern about the legality of this.

- Bedetheque has copyright on all their data.
- AppBubble is getting their data from a third party provider, and cannot redistribute the data.

For the moment i need to finish adding the metadata model with manual edits for books, then i will think about how to retrieve metadata from external sources.

**Comment by Flyingfufu** [comment]
Hi Thanks for your quick feedback, and shame on me to have missed [#11](https://github.com/gotson/komga/issues/11).
Pleased however to see the link is of interest !

Keep on doing this great job, I like it !!!

**Comment by gotson** [comment]
Closed in favor of #11
