### ISSUE TITLE
Docker: Get list of pending tasks on the command line

### ISSUE THREAD

**Issue by rhaussmann** [gotson/komga#974]
### Describe your suggested feature

I'm scanning my library with Komga but it seems to be going slower than expected (faster now I turned off Deep Scan). I'd still like to shut Chrome (a memory hog) and check the task status using the command line into docker. Is there a way to do this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Not easily. You can tail the logs, or you can listen to the http server sent events stream (the same one the webui uses to know how many tasks there are).
