### ISSUE TITLE
Thumbnail not properly generating from PNG images

### ISSUE THREAD

**Issue by PenDrag0n7** [gotson/komga#976]
### Steps to reproduce

Ran into an issue with some png images.
which aren't getting their thumbnail generated correctly

I have provided 2 samples images in zip files,
[Sample_2.zip](https://github.com/gotson/komga/files/9603561/Sample_2.zip)
[Sample_1.zip](https://github.com/gotson/komga/files/9603562/Sample_1.zip)

### Expected behavior

The thumbnail should have been created without distortion.

### Actual behavior

Thumbnails are distorted
Sample 1: image has a blue tint vs Sample 3 which is the same image converted to JPEG
Sample 2: Image has missing detail (PNG4 with missing color channels)
![image](https://user-images.githubusercontent.com/43438388/191152732-15d38ce2-30c8-4500-9c2d-76555ee3d403.png)

### Komga version

v0.157.1

### Operating system

Docker (linux)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Thumbnail depends on 3rd party libraries for thumbnail generation and also for image readers.
