### ISSUE TITLE
Relax parsing on series.json file

### ISSUE THREAD

**Issue by awh-tokyo** [gotson/komga#977]
### Describe your suggested feature

Currently, any missing fields in series.json cause the file to be ignored and a stack trace to be left in the log files.  I'm using hand-crafted series.json files not created by Mylar and have to put a bunch of empty/unused fields into each one to allow Komga to read them.  It would be nice if missing fields (or at least ones not used by Komga) could simply be ignored rather than cause a parse error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga follows the [schema](https://github.com/mylar3/mylar3/wiki/series.json-schema-%28version-1.0.1%29) of series.json.
