### ISSUE TITLE
Can't load Komga after library scan or analysis

### ISSUE THREAD

**Issue by scottbrosnahan** [gotson/komga#981]
### Steps to reproduce

Step 1 - login to komga
step 2 - scan library or anlayse library
step 3 - gets stuck on loading, then cant access page on localhost or on ip page, Paperback connection also stops working

### Expected behavior

Scan library and add new manga, not get stuck all the time

### Actual behavior

gets stuck on loading, then cant access page on localhost or on ip page, Paperback connection also stops working

### Logs

[komga.log](https://github.com/gotson/komga/files/9668956/komga.log)

### Komga version

0.157.2

### Operating system

Windows 11 2022 update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
in your logs: `java.lang.OutOfMemoryError: Java heap space`

Give it more memory.
