### ISSUE TITLE
Loading module jdk.incubator.foreign with Java 19 breaks Komga

### ISSUE THREAD

**Issue by unfinishedh** [gotson/komga#982]
### Steps to reproduce

Hi,

Lately, I have been testing Komga's jpeg xl support on my Raspberry Pi. It took me a while, but with the help of the [previous issue](https://github.com/gotson/komga/issues/831) and a bit of tinkering due to the arm architechture of the Pi I was able to configure it successfully. However, after installing the recently released Java 19, it seems to break Komga altogether due to the an issue with the jdk.incubator.foreign module. The commandline only reports `java.lang.module.FindException: Module jdk.incubator.foreign not found`

Removing `--add-modules jdk.incubator.foreign --enable-native-access=ALL-UNNAMED` from the startup options allows Komga to boot with Java 19, although obviuosly, without jpeg xl enabled.

On the other hand, if I just revert back to Java 18 (temurin-18-jdk), everything works as expected.

My config:
libjxl v0.8.0 fe7d16bc [NEON] (compiled from source)
temurin-19-jdk (installed from [their repo](https://adoptium.net/installation/linux/))
Komga-0.157.2 jar file from github

### Expected behavior

Being able to start Komga with working jpeg xl support.

### Actual behavior

Komga crashes at boot.

### Logs

 pi@raspberrypi:~ $ java --add-modules jdk.incubator.foreign --enable-native-access=ALL-UNNAMED -Djava.library.path=/usr/
local/lib/aarch64-linux-gnu/ -jar .komga/komga.jar --logging.level.org.gotson.komga=DEBUG
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.incubator.foreign not found

pi@raspberrypi:~ $ java --version
openjdk 19 2022-09-20
OpenJDK Runtime Environment Temurin-19+36 (build 19+36)
OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)

### Komga version

0.157.2

### Operating system

Rapsberry Pi OS lite (Debian Bullseye arm64)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That's normal, project Panama graduated from incubator to preview in Java 19. Use Java 18.
