### ISSUE TITLE
Failed to load native library:sqlite-3.36.0.3

### ISSUE THREAD

**Issue by reyqn** [gotson/komga#984]
### Steps to reproduce

Run docker-compose up -d on libreelec (rpi pi4) with docker-compose.yml from the documentation

### Expected behavior

Komga should start without crashing

### Actual behavior

It crashes

### Logs

[komga-logs.txt](https://github.com/gotson/komga/files/9757901/komga-logs.txt)

### Komga version

0.157.2

### Operating system

Libreelec 10.0.2

### Other details

```
uname -a
Linux LibreELEC 5.10.95 #⁠1 SMP Sat Mar 5 15:50:44 CET 2022 aarch64 GNU/Linux
```

```
lscpu
Architecture:                    aarch64
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.50
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

```
java --version
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode, sharing)
```

PS: This seem related to #945, but it looks like it isn't the same exactly?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
#945 is different, it's a platform for which the 3rd party library has not been compiled for. RPI4 works fine with standard raspbian normally.

```
OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so. osinfo: Linux/aarch64
```

It's related to https://github.com/xerial/sqlite-jdbc/issues/436

**Comment by reyqn** [comment]
Ok thanks, I've subscribed to the issue you linked, if you need me to do something to help I can try.

**Comment by gotson** [comment]
> Ok thanks, I've subscribed to the issue you linked, if you need me to do something to help I can try.

Ideally we need to reproduce your issue in a simpler fashion, for instance without Komga.

Can you try to [follow those steps](https://github.com/gotson/komga/issues/945#issuecomment-1214503917) and confirm whether you get the same error i highlighted above (stack guard)?

**Comment by reyqn** [comment]
Actually I can't even run java (nor javac) from the container: java says 
`Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`
javac says command not found.
Checking java executable (/opt/java/openjdk/bin/java) seems to indicate it is a 32 bits ELF.
`/opt/java/openjdk/bin# od -An -t x1 -j 4 -N 1 java
 01`

It seems like the wrong jdk is installed or something? It seems like it's just a 32 bits JRE

`root@9c0c0c7e123e:/opt/java/openjdk# cat release
IMPLEMENTOR="Eclipse Adoptium"
IMPLEMENTOR_VERSION="Temurin-11.0.16.1+1"
JAVA_VERSION="11.0.16.1"
JAVA_VERSION_DATE="2022-08-12"
LIBC="default"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.ldap jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="arm"
OS_NAME="Linux"
SOURCE=".:git:5698142c8486"
BUILD_SOURCE="git:26148823"
BUILD_SOURCE_REPO="https://github.com/adoptium/temurin-build.git"
SOURCE_REPO="https://github.com/adoptium/jdk11u.git"
FULL_VERSION="11.0.16.1+1"
SEMANTIC_VERSION="11.0.16.1+1"
BUILD_INFO="OS: Linux Version: 5.4.0-110-generic"
JVM_VARIANT="Hotspot"
JVM_VERSION="11.0.16.1+1"
IMAGE_TYPE="JRE"`

When downloading the aarch64 version manually I get LIBC="gnu", OS_ARCH="aarch64" and IMAGE_TYPE="JDK"

**Comment by gotson** [comment]
ideally you should be testing this outside of a container, using a local JDK.

**Comment by reyqn** [comment]
Sadly LibreElec doesn't have a package manager, the only way I can install new programs is via docker

**Comment by gotson** [comment]
you can probably find some docker image for java for your architecture then, that should achieve the same thing

**Comment by gotson** [comment]
could you do a `docker version` ? We had the case before with some people running rpi where the docker was running 32bits while the OS was 64 bits and that caused some incompatibilities.

**Comment by gotson** [comment]
similar previous issue: https://github.com/gotson/komga/issues/354#issuecomment-743741241

**Comment by gotson** [comment]
in that case then everything should be 32bits, right?

can you do a `java -version` somewhere, either in the java container, or Komga container ?

**Comment by reyqn** [comment]
Yes everything is 32 bits
```
java --version
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode, sharing)
```
However, from the logs:
```
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
```
It seems like libsqlitejdbc.so is 64bits here, but I have no idea where it comes from

**Comment by gotson** [comment]
Good catch, i hadn't seen this part of the error message:

```
Failed to load native library:sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-5bced81e-2973-425c-bfc2-fdb48bbe0f5c-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
```

So apparently sqlite-jdbc thinks your system is aarch64, while it is arm, and thus loads the wrong native library, hence the 'wrong ELF class' message.

**Comment by reyqn** [comment]
```
root@9c0c0c7e123e:/app# uname -m
aarch64
```
Apparently even though docker is 32 bits, inside the container uname reports aarch64.

Also I noticed that komga uses an old version of sqlite-jdbc, even though it seems like you've done lots of work on it recently. Is this intentional?

**Comment by gotson** [comment]
is that inside the container ? can you also do `uname -m` outside the container ?

**Comment by reyqn** [comment]
```
LibreELEC:~/docker/komga # docker exec -it komga bash
root@9c0c0c7e123e:/app# uname -m
aarch64
root@9c0c0c7e123e:/app# LibreELEC:~/docker/komga # uname -m
aarch64
```
Yeah I've got the same output inside or outside the container

**Comment by reyqn** [comment]
https://github.com/moby/moby/issues/611#issuecomment-26013167

Apparently it's to be expected, you can't rely on uname to check the container's architecture.

**Comment by gotson** [comment]
If you have the same result inside and outside the container then it's not a docker problem.

**Comment by gotson** [comment]
I would expect your system to say `arm` for `uname -m`, at least outside the container, but it doesn't.

Can you check on that lead on the libreelec forums maybe?

**Comment by reyqn** [comment]
Well LibreElec is aarch64, only the userland is 32bits. So uname reacts as expected.
I've tried tricking the container so that it reports 32 bits like so by adding this to the dockerfile:
`entrypoint: ["linux32", "java", "org.springframework.boot.loader.JarLauncher", "--spring.config.additional-location=file:/config/"]`

However I have this issue now:
```
WARNING! readelf not found. Cannot check if running on an armhf system, armel architecture will be presumed.
WARNING! readelf not found. Cannot check if running on an armhf system, armel architecture will be presumed.
Failed to load native library:sqlite-3.36.0.3-b11a8ea9-128a-4359-9159-e0bd94abf44f-libsqlitejdbc.so. osinfo: Linux/arm
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-b11a8ea9-128a-4359-9159-e0bd94abf44f-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-b11a8ea9-128a-4359-9159-e0bd94abf44f-libsqlitejdbc.so: cannot open shared object file: No such file or directory
```

with linux32, uname reports this:
```
root@a264dd910c08:/app# linux32 uname -a
Linux a264dd910c08 5.10.95 #1 SMP Sat Mar 5 15:50:44 CET 2022 armv8l armv8l armv8l GNU/Linux
root@a264dd910c08:/app# linux32 uname -m
armv8l
```

**Comment by gotson** [comment]
> Well LibreElec is aarch64, only the userland is 32bits. So uname reacts as expected.

I don't know enough about rpi to understand what that means tbh.

**Comment by reyqn** [comment]
The kernel is 64 bits, but every package is 32 bits, from what I understand, so docker is a 32 bits elf running on a 64 bits host

**Comment by gotson** [comment]
Can you look into having a aarch64 docker running on there maybe?

**Comment by reyqn** [comment]
I could use some community images that have 64bits userlands, but I would loose access to widevine, and thus couldn't decode drm protected streams.

I think I should be able to run 32bits containers on my system (after all, I'm running multiple containers already), the issue is just that sqlite-jdbc thinks it's running in a 64bits environment when it's actually a 32bits one

**Comment by gotson** [comment]
Would you be able to provide the output of `file - L /bin/sh` both inside and outside the container?

**Comment by reyqn** [comment]
Here it is:
```
root@d94b3646261a:/app# file -L /bin/sh
/bin/sh: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=e6ac335fd994c320dc2930194e9992d9755c477c, for GNU/Linux 3.2.0, stripped
```

I can't install the file command in libreelec though so I can't run it from outside the container

**Comment by reyqn** [comment]
Ok so I got it working. I changed the entrypoint like I said before, and installed the readelf package in the container (since there was a warning about it). With both fixes, the server is up.

**Comment by reyqn** [comment]
In the end, all this does is force the resolveArmArchType() method form sqlite-jdbc's OSInfo to return "armv7", since linux32 makes uname report armv8l and not aarch64, and armv8 is compatible with armv7 apparently.

**Comment by reyqn** [comment]
After reading the source code, doing this: `entrypoint: ["linux32", "java", "-Dsun.arch.abi=gnueabihf", "org.springframework.boot.loader.JarLauncher", "--spring.config.additional-location=file:/config/"]` is enough, you don't have to install readelf

**Comment by gotson** [comment]
I'm not familiar with `linux32`, what does that do exactly?

**Comment by reyqn** [comment]
I wasn't either, apparently it's a symlink to the [setarch](https://man7.org/linux/man-pages/man8/setarch.8.html) command (probably with linux32 as an argument)

**Comment by gotson** [comment]
Glad you sorted things out, but in the long run that will be a hassle to maintain and update for you.

I think you have a good point with uname nor reporting correctly within docker, and while it's an edge case, I think it's worth trying to enhance the arch detection in sqlite-jdbc.

The problem I see is that the output of `file` may be inconsistent among systems, I'm wondering how to best implement that.

Another solution would be to have some kind of override of the detected arch through a Java system property.

**Comment by reyqn** [comment]
Yeah I think adding just a manual workaround should be enough. it's not like it affects a lot of people.

**Comment by gotson** [comment]
@reyqn please have a look here https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#override-detected-architecture

You can pass those options through the `JAVA_TOOL_OPTIONS` environment variable if you're on Docker.

**Comment by reyqn** [comment]
This works with JAVA_TOOL_OPTIONS=-Dorg.sqlite.osinfo.architecture=armv7

**Comment by gotson** [comment]
> Maybe this should be documented?

It's documented, link above.

**Comment by reyqn** [comment]
Well it's documented in sqlite-jdbc, but maybe the docker option could be mentioned somewhere in the komga doc?

**Comment by gotson** [comment]
> Well it's documented in sqlite-jdbc, but maybe the docker option could be mentioned somewhere in the komga doc?

It's not Docker specific, `JAVA_TOOL_OPTIONS` is a well known option for anyone who used the JVM. This also don't need to be in Komga IMH because it's a very specific edge case, so i'm happy to handle this directly in troubleshooting issues.

**Comment by reyqn** [comment]
Ok I don't really know docker. Thanks again for the fix.
