### ISSUE TITLE
UI not responding during scan

### ISSUE THREAD

**Issue by gajewsk2** [gotson/komga#985]
### Steps to reproduce

1. Start a library scan (seems like an automatic scan that - I'm not sure if other scans can cause it)
2. Try to navigate UI

### Expected behavior

You should still be able to navigate library even when scans are in progress 

### Actual behavior

![image](https://user-images.githubusercontent.com/4039913/196007948-0db2c035-591d-458f-9530-afb764454119.png)

### Logs

https://www.dropbox.com/s/gzf8tbc6g3e3uwq/komga.log?dl=1

### Komga version

0.154.1

### Operating system

Windows 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Can you provide logs from startup, not in DEBUG?

**Comment by gajewsk2** [comment]
I believe these are from startup. It just happened now after starting another scan manually. 
https://www.dropbox.com/s/gewnuyr8cq14jqr/logs.zip?dl=0
