### ISSUE TITLE
Socket activation

### ISSUE THREAD

**Issue by mybuntu-git2** [gotson/komga#986]
### Describe your suggested feature

I am quite ignorant on the matter myself but as the moments of the day in which my komga is accessed are predictable, I would like to have it run on demand the rest of the day.
My understanding is that socket activation would allow komga docker to be off and release some ram and startup on demand when the port is actively accessed.
Is this an issue, and is it doable?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
That is outside the scope of this project, as it is generic to selfhosting and not specific to Komga. You may want to check https://www.reddit.com/r/selfhosted/
