### ISSUE TITLE
Books with mostly text only shows icons/images from the book, no text

### ISSUE THREAD

**Issue by DuckersMcQuack** [gotson/komga#987]
### Steps to reproduce

Is this one only meant for comics and not plain books? It read all my books perfectly with title and picture, but no text for the content. 

### Expected behavior

Showing text from books

### Actual behavior

Showing every page being only images

### Komga version

Latest 

### Operating system

Unraid 6.10.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by darthmooguy** [comment]
https://komga.org/guides/#komga-supports-these-media-file-types

Komga doesn't support text in epub, only images.

**Comment by DuckersMcQuack** [comment]
Gotcha. Will keep konga for my comics/manga.
