### ISSUE TITLE
Series language not translated in WebUI

### ISSUE THREAD

**Issue by Sandman-618** [gotson/komga#988]
### Steps to reproduce

1. Change Komga WebUI language (here: German)
2. Enter IETF BCP 47 tag in series metadata settings (here: de-de)

<img width="221" alt="Screenshot 2022-10-23 135142" src="https://user-images.githubusercontent.com/103930610/197390800-656c4272-2088-48f9-9850-b150d15de14e.png">

### Expected behavior

The series page should display the series language icon in the specified Komga WebUI language
The icon should say "Deutsch" instead of "German"

### Actual behavior

The series language is always displayed in english, even if WebUI is set to German

I havent found a translatable string for this. Checked Weblate and source code.

Maybe line 139 of /komga-webui/src/views/BrowseSeries.vue gives a hint.

<img width="161" alt="Screenshot 2022-10-23 135215" src="https://user-images.githubusercontent.com/103930610/197391009-cd06bf51-7c72-45a2-963c-171a53f532fd.png">

### Komga version

0.157.2

### Operating system

Unraid 6.9.2 docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
The value is coming from a [library](https://github.com/mattcg/language-tags) that uses IANA's data to show the language description. As you can see in the [raw IANA file](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) there's just too many languages, and there is no official translation for those values.
