### ISSUE TITLE
Health Check API

### ISSUE THREAD

**Issue by trekie86** [gotson/komga#992]
### Describe your suggested feature

I use a program called [Uptime-Kuma](https://github.com/louislam/uptime-kuma) to monitor my self-hosted services. Rather than hitting the Komga webpage and waiting for the site to render before returning a 200 OK, it would be great to add a health check to the REST APIs that can be used for lightweight status checks. 

I checked the OpenAPI spec: https://github.com/gotson/komga/blob/master/komga/docs/openapi.json and did not find any endpoints that would fit this need. Additionally, it would be great if this health check could run without auth so that external tools can integrate easily and not pass around basic credentials across the wire.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga uses Spring Boot, which includes management APIs, and [one endpoint](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health) displays the health status. You can find it at `/actuator/health`.

Currently the actuator endpoints are limited to ADMIN roles. I will do a small change to allow the health endpoint to show limited details to unauthorized users.
