### ISSUE TITLE
Some books have negative volume counts after migrating to another host.

### ISSUE THREAD

**Issue by IcySon55** [gotson/komga#993]
### Steps to reproduce

Previous configuration:
Windows, v0.154.1

New configuration:
TrueNAS Jails, FreeBSD, openJDK17, v0.157.2

1. Copied the database.sqlite file over into the VM and libraries and books appeared as before.
2. Edited the Library to direct it to the new storage location `/media` which is hosted by TrueNAS.
3. Ran Analyze on the one library and most books updated their paths correctly, but some ended up with negative numbers of volumes,

Directory structure of media and contained files is identical to the original Windows host.

### Expected behavior

Update the file paths and volume counts normally.

### Actual behavior

Some of the books have negative volume counts.

### Komga version

0.157.2

### Operating system

FreeBSD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
run a deep scan _ONCE_ (don't leave it on afterwards)

**Comment by IcySon55** [comment]
Alright, after a bit of poking around I found the Deep Scan option and have started it

Perhaps since it's not meant to be used often, it could be a one time click with confirmation instead of a checkbox?

Will report results when it completes.

**Comment by IcySon55** [comment]
The deep scan appears to have corrected the volume counts.

Thanks!
