### ISSUE TITLE
Do not display pages in Komga when image files have non-image filenames in cbz

### ISSUE THREAD

**Issue by jeremydouglass** [gotson/komga#997]
### Describe your suggested feature

Feature:

Make it is possible to name an image file in a CBZ for non-viewing in Komga. Valid image files in a CBZ may be named in such a way that they are not loaded by the Komga viewer:

-   image files with a non-image extension, example: "cover.jpg.bak"
-   mage files with a . prefix to indicate a hidden file, example ".cover.jpg"

For example, neither of these file names display as pages in SimpleComic, however both images still display in Komga (0.157.4-master) when added to a cbz file and analyzed.

The feature could support either or both of the conventions above. Or it could introduce its own explicit convention --  it will only ignore files ending in '.ignore' or '.skip' and load anything else.

### Other details

CBZ files may include alternate covers, letter pages, credits, banners, packaging, add-on pages from doujinshi circles or translators or advertising pages related to the digital publisher or distributor, but these are not always part of the desired viewing content. There is a use case for keeping these image files in the CBZ alongside viewing pages, yet marking them as not for viewing

Currently Komga displays all viewable image files in a zip/cbz. This includes linux/macos "hidden" files beginning with a "." (e.g. ".alternate-cover.jpeg"), and files named with a non-image file extension (e.g. "credits.jpeg.bak") and files with no valid extension anywhere in the filename (e.g. "letters.bak" or "slipcover"). It appears that Komga simply checks the file header bytes for a magic number and displays any valid image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Komga doesn't trust or care about file extensions, only about the media type.

**Comment by gotson** [comment]
> This includes linux/macos "hidden" files beginning with a "." (e.g. ".alternate-cover.jpeg")

you should clean your archives, those have nothing to do in a CBZ

> and files named with a non-image file extension (e.g. "credits.jpeg.bak") and files with no valid extension anywhere in the filename (e.g. "letters.bak" or "slipcover")

This is probably because you make your own archives, no archives being shared have any of this

**Comment by jeremydouglass** [comment]
Hi gotson,

Thank you so much for taking the time to read my issue (and for Komga).

From reading your response advising me to "clean my archives" I am sorry if I was unclear -- this was a *feature request*, not a bug report or a problem with bad data. I was providing examples filenames only as an example of how the described feature (the ability to intentionally hide images) could be implemented. I was not claiming that for example the Digital Comics Museum CBZs are full of "." or ".bak" files, and that Komga is failing to filter them, and that is a bug. Instead, I am saying that there are use cases for a user intentionally hiding an image file in a CBZ as a non-image, and this is already supported by most other readers, and this might be accomplished in a line or two of code -- might Komga might support this. I do understand if you still don't want to, but I want to make sure we understand each other.

I do understand that currently "Komga doesn't trust or care about file extensions, only about the media type." My follow-up point is only that this makes Komga treat CBZ files differently than most other CBZ viewers, including Kavita, YACReader, Simple Comic, and many others, all of which hide page images whose ZIP filename strings are explicitly marked as non-images. Komga is unusual in not behaving in this way. Of course, that doesn't make it a bug, as CBZ is not a standard! It just means that there is a case where CBZ file behaves one way in most readers, but differently just in Komga.

For example, if you download a DCM comic and import into Kavita (36 pgs) then rename one of its pages with a '.' prefix or a '.bak' suffix in the CBZ, then rescan in Kavita, the hidden page disappears from the page count (35 pgs) and is not shown in the web viewer, as desired. This is possible without the user needing to delete the page image file data from the CBZ -- and the user may restore the page later by changing the name.

I would guess (?) from very briefly looking at the Komga code that this feature (the ability to intentionally hide images) could be supported through a single extra line of code filtering select filenames from komga.infrastructure.mediacontainer.ContentDetector, although I haven't tested this.

**Comment by gotson** [comment]
I have no intention of supporting this.
